# EEG-only experiments (text2text template)

This notebook is adapted from the text2text workflow but uses only EEG features.
Text2text features are not concatenated into the training matrix.

Targets/splits covered:
- `match_mismatch`: binary + multiclass
- `match_mismatch_general`: binary + multiclass

In [1]:
from __future__ import annotations

import os
import json
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd
from umap import UMAP

from experiment_code.read_data import get_data_for_split
from experiment_code.run_experiments import _build_groups_mm_for_mm
from experiment_code.optuna_code import run_and_log, fit_best_and_test

# Data root: contains datasets_splitted_screen_match_mismatch*
ROOT = Path(r"C:\Users\LEGION\data\СB")
os.chdir(ROOT)
print("cwd:", Path.cwd())

cwd: C:\Users\LEGION\data\СB

In [2]:
# Optuna / CV settings aligned with your ES experiments
TARGETS = ["match_mismatch", "match_mismatch_general"]
SPLITS = ["binary", "multiclass"]

USE_EARLY_STOPPING = True
REFIT_CV = False
REFIT_TEST = True
USE_MIN = False

CV = 4
N_TRIALS_XGB = 100
N_TRIALS_CB = 50

# Output location under project folder (not ROOT)
PROJECT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\dataset_v2")
OUT_DIR = PROJECT_DIR / "optuna_results_eye_text2text"
OUT_DIR.mkdir(parents=True, exist_ok=True)

FI_DIR = OUT_DIR / "feature_importances_eye_text2text"
FI_DIR.mkdir(parents=True, exist_ok=True)
REFIT_TOP_N = 30

# Compress only these text2text sets with UMAP (fit on train, transform on test)
UMAP_TARGET_SETS = {"freq_bands", "stat", "corr", "cov_freq"}
UMAP_N_COMPONENTS = 100
# Keep only columns with no NaN in train (same style as previous experiments)
CLEAN_TRAIN_COLUMNS = False

In [ ]:
def _prefix_cols(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    return df.add_prefix(prefix)


def _load_text2text_parquet(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    if "pid_rn" not in df.columns:
        raise KeyError(f"'pid_rn' column not found in {path}")
    df = df.set_index("pid_rn")
    df.index = df.index.astype(str)
    return df


def _apply_umap_train_test(
    text_train: pd.DataFrame,
    text_test: pd.DataFrame,
    *,
    text_set_name: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    tr = text_train.apply(pd.to_numeric, errors="coerce")
    te = text_test.apply(pd.to_numeric, errors="coerce")

    train_means = tr.mean(numeric_only=True)
    tr = tr.fillna(train_means).fillna(0.0)
    te = te.fillna(train_means).fillna(0.0)

    n_components = int(min(UMAP_N_COMPONENTS, max(2, tr.shape[1])))
    reducer = UMAP(
        n_components=n_components,
    )

    print(
        f"[{text_set_name}] UMAP compression: "
        f"train/test features {tr.shape[1]} -> {n_components}"
    )

    z_train = reducer.fit_transform(tr)
    z_test = reducer.transform(te)

    cols = [f"{text_set_name}__umap_{i:03d}" for i in range(n_components)]
    tr_umap = pd.DataFrame(z_train, index=text_train.index, columns=cols)
    te_umap = pd.DataFrame(z_test, index=text_test.index, columns=cols)
    return tr_umap, te_umap


def _prepare_joined_X(
    train_index: pd.Index,
    test_index: pd.Index,
    text_all: pd.DataFrame,
    text_set_name: str,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    # Index match because text2text is not pre-split
    text_train = text_all.reindex(train_index)
    text_test = text_all.reindex(test_index)

    missing_train = int(text_train.isna().all(axis=1).sum())
    missing_test = int(text_test.isna().all(axis=1).sum())
    print(f"[{text_set_name}] rows missing after index match -> train: {missing_train}, test: {missing_test}")

    if text_set_name in UMAP_TARGET_SETS:
        text_train_model, text_test_model = _apply_umap_train_test(
            text_train,
            text_test,
            text_set_name=text_set_name,
        )
    else:
        text_train_model = _prefix_cols(text_train, f"{text_set_name}__")
        text_test_model = _prefix_cols(text_test, f"{text_set_name}__")

    # EEG-only setup: use only EEG-set features from the selected parquet.
    X_train = text_train_model
    X_test = text_test_model

    if CLEAN_TRAIN_COLUMNS:
        keep_cols = X_train.columns[X_train.notna().all(axis=0)]
        X_train = X_train[keep_cols]
        X_test = X_test.reindex(columns=keep_cols)

    return X_train, X_test


def _build_no_neutral_mask(stim_df: pd.DataFrame, target: str, split: str) -> pd.Series:
    mask = pd.Series(True, index=stim_df.index)

    if "valence" in stim_df.columns:
        valence = pd.to_numeric(stim_df["valence"], errors="coerce")
        mask &= valence != 2

    if split == "binary":
        if target == "match_mismatch_general" and "exp_general_multi" in stim_df.columns:
            exp_general_multi = pd.to_numeric(stim_df["exp_general_multi"], errors="coerce")
            mask &= exp_general_multi != 2
        elif "IAT_results2" in stim_df.columns:
            iat = stim_df["IAT_results2"].astype(str).str.strip().str.lower()
            mask &= iat != "neutral"

    return mask.fillna(False)


def _load_eeg_for_task(target: str, split: str, no_neutral: bool = False):
    df, tgt, _ = get_data_for_split(X_name="screen", target=target, split=split)

    train_index = df["all_features"]["X_train"].index.astype(str)
    test_index = df["all_features"]["X_test"].index.astype(str)
    stim_train = df["stimuli_features"]["X_train"].copy()
    stim_test = df["stimuli_features"]["X_test"].copy()

    y_train = tgt["cb"]["y_train"].copy()
    y_test = tgt["cb"]["y_test"].copy()

    if no_neutral:
        mask_train = _build_no_neutral_mask(stim_train, target=target, split=split)
        mask_test = _build_no_neutral_mask(stim_test, target=target, split=split)

        train_index = train_index[mask_train.to_numpy()]
        test_index = test_index[mask_test.to_numpy()]
        y_train = y_train.loc[mask_train]
        y_test = y_test.loc[mask_test]
        stim_train = stim_train.loc[mask_train]

    groups = np.array([str(i).split("_")[0] for i in train_index])

    if target in ("match_mismatch", "match_mismatch_general"):
        groups_mm = _build_groups_mm_for_mm(X_train_index=train_index, stim_train_df=stim_train)
    else:
        groups_mm = None

    problem = "binary" if split == "binary" else "multiclass"
    return train_index, test_index, y_train, y_test, groups, groups_mm, problem


def run_text2text_set(
    text_set_name: str,
    text_all: pd.DataFrame,
    *,
    do_refit: bool = True,
    top_n_features: int = REFIT_TOP_N,
):
    # Enforce index used for matching with eye-tracking splits.
    if "pid_rn" in text_all.columns:
        text_all = text_all.set_index("pid_rn")
    text_all = text_all.copy()
    text_all.index = text_all.index.astype(str)

    # 'key' must never be used as a feature.
    if "key" in text_all.columns:
        text_all = text_all.drop(columns=["key"])

    text_features = int(text_all.shape[1])
    print(f"[{text_set_name}] text2text feature count after cleanup: {text_features}")

    rows = []

    for target in TARGETS:
        for split in SPLITS:
            for no_neutral in [False, True]:
                problem = "binary" if split == "binary" else "multiclass"
                neutral_suffix = "__no_neutral" if no_neutral else ""
                train_features_name = (
                    f"exp__X_name=screen+{text_set_name}"
                    f"__target={target}"
                    f"__problem={problem}"
                    f"__feat=all_features+{text_set_name}"
                    f"__ES__refitTEST"
                    f"{neutral_suffix}"
                )
                out_path = OUT_DIR / f"{train_features_name}.json"

                if out_path.exists():
                    print("\n" + "=" * 80)
                    print(f"Skipping existing experiment: {train_features_name}")
                    with open(out_path, encoding="utf-8") as f:
                        results = json.load(f)
                    rows.append({
                        "text_set": text_set_name,
                        "target": target,
                        "split": split,
                        "no_neutral": no_neutral,
                        "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                        "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                        "file": str(out_path),
                    })
                    continue

                train_index, test_index, y_train, y_test, groups, groups_mm, problem = _load_eeg_for_task(
                    target,
                    split,
                    no_neutral=no_neutral,
                )
                X_train, X_test = _prepare_joined_X(train_index, test_index, text_all, text_set_name)

                print("\n" + "=" * 80)
                print(f"Running: {train_features_name}")
                print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

                results = run_and_log(
                    train_features=train_features_name,
                    problem=problem,
                    X_train=X_train,
                    X_test=X_test,
                    y_train=y_train,
                    y_test=y_test,
                    strat_train=y_train,
                    groups=groups,
                    groups_mm=groups_mm,
                    use_early_stopping=USE_EARLY_STOPPING,
                    refit_cv=REFIT_CV,
                    refit_test=REFIT_TEST,
                    n_trials_xgb=N_TRIALS_XGB,
                    n_trials_cb=N_TRIALS_CB,
                    cv=CV,
                    gpu=False,
                    use_min=USE_MIN,
                    cat_cols=None,
                    target_names=None,
                    out_path=out_path,
                )

                if do_refit:
                    print("\n" + "-" * 80)
                    print("Refit best iteration + metrics + top features")
                    for model_name in ["xgb", "catboost"]:
                        best_params = results[model_name].get("suggested_params", {})
                        if not best_params:
                            print(f"\n=== Skip refit {model_name.upper()} (no suggested params) ===")
                            continue

                        print(f"\n=== Refit {model_name.upper()} with saved best params ===")
                        out_refit = fit_best_and_test(
                            model_name=model_name,
                            best_params=best_params,
                            problem=problem,
                            X_train=X_train,
                            X_test=X_test,
                            y_train=y_train,
                            y_test=y_test,
                            strat_train=y_train,
                            groups=groups,
                            groups_mm=groups_mm,
                            use_early_stopping=True,
                            early_stopping_rounds=100,
                            target_names=None,
                            cat_cols=None,
                            gpu=False,
                            refit_test=True,
                        )

                        model = out_refit["model"]
                        if model_name == "xgb":
                            importances = model.feature_importances_
                        else:
                            importances = model.get_feature_importance()

                        fi = pd.DataFrame({
                            "feature": X_train.columns,
                            "importance": importances,
                        }).sort_values("importance", ascending=False)

                        fi_path = FI_DIR / f"{train_features_name}__{model_name}.csv"
                        fi.to_csv(fi_path, index=False)
                        print(f"Saved feature importances: {fi_path}")
                        print(f"Top {top_n_features} features for {model_name.upper()}:")
                        display(fi.head(top_n_features))

                rows.append({
                    "text_set": text_set_name,
                    "target": target,
                    "split": split,
                    "no_neutral": no_neutral,
                    "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                    "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                    "file": str(out_path),
                })

    summary = pd.DataFrame(rows)
    display(summary)
    return summary

In [4]:
# Explicit text2text parquet sets
TEXT2TEXT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\text2text_features")
TEXT2TEXT_FILES = {
    "corr": TEXT2TEXT_DIR / "corr.parquet",
    "cov_freq": TEXT2TEXT_DIR / "cov_freq.parquet",
    "envelope": TEXT2TEXT_DIR / "envelope.parquet",
    "freq_bands": TEXT2TEXT_DIR / "freq_bands.parquet",
    "PID": TEXT2TEXT_DIR / "PID.parquet",
    "stat": TEXT2TEXT_DIR / "stat.parquet",
}

print("text2text dir:", TEXT2TEXT_DIR)
for k, p in TEXT2TEXT_FILES.items():
    print(f"{k:10s} -> {p} | exists={p.exists()}")
    print(pd.read_parquet(p).shape)

text2text dir: C:\Users\LEGION\Projects\CB_exepriment\text2text_features
corr       -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\corr.parquet | exists=True
(5592, 1832)
cov_freq   -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\cov_freq.parquet | exists=True
(5592, 36297)
envelope   -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\envelope.parquet | exists=True
(5592, 429)
freq_bands -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\freq_bands.parquet | exists=True
(5592, 18363)
PID        -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\PID.parquet | exists=True
(5592, 612)
stat       -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\stat.parquet | exists=True
(5592, 8237)

In [5]:
# Set: corr
text_corr = pd.read_parquet(TEXT2TEXT_FILES["corr"])
print("corr shape:", text_corr.shape)
summary_corr = run_text2text_set("corr", text_corr)
summary_corr

corr shape: (5592, 1832)
[corr] text2text feature count after cleanup: 1830

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__ES__refitTEST

,text_set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.399740,0.400511,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.621334,0.669227,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.406654,0.532466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.797868,0.794106,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.399740,0.400511,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.621334,0.669227,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.406654,0.532466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.797868,0.794106,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [6]:
# Set: cov_freq
text_cov_freq = pd.read_parquet(TEXT2TEXT_FILES["cov_freq"])
print("cov_freq shape:", text_cov_freq.shape)
summary_cov_freq = run_text2text_set("cov_freq", text_cov_freq)
summary_cov_freq

cov_freq shape: (5592, 36297)
[cov_freq] text2text feature count after cleanup: 36295

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST

,text_set,target,split,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,0.399740,0.415582,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,multiclass,0.619349,0.626280,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch_general,binary,0.475352,0.579789,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch_general,multiclass,0.801701,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,0.399740,0.415582,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,multiclass,0.619349,0.626280,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch_general,binary,0.475352,0.579789,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch_general,multiclass,0.801701,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [7]:
# Set: envelope
text_envelope = pd.read_parquet(TEXT2TEXT_FILES["envelope"])
print("envelope shape:", text_envelope.shape)
summary_envelope = run_text2text_set("envelope", text_envelope)
summary_envelope

envelope shape: (5592, 429)
[envelope] text2text feature count after cleanup: 427

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__ES__refitTEST

,text_set,target,split,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,0.399740,0.436447,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,multiclass,0.632589,0.659056,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch_general,binary,0.398957,0.504534,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch_general,multiclass,0.812691,0.803043,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,0.399740,0.436447,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,multiclass,0.632589,0.659056,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch_general,binary,0.398957,0.504534,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch_general,multiclass,0.812691,0.803043,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [8]:
# Set: freq_bands
text_freq_bands = pd.read_parquet(TEXT2TEXT_FILES["freq_bands"])
print("freq_bands shape:", text_freq_bands.shape)
summary_freq_bands = run_text2text_set("freq_bands", text_freq_bands)
summary_freq_bands

freq_bands shape: (5592, 18363)
[freq_bands] text2text feature count after cleanup: 18361

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST

,text_set,target,split,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,0.399740,0.413223,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,multiclass,0.639669,0.620434,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch_general,binary,0.398957,0.509769,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch_general,multiclass,0.806212,0.792472,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,0.399740,0.413223,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,multiclass,0.639669,0.620434,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch_general,binary,0.398957,0.509769,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch_general,multiclass,0.806212,0.792472,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [9]:
# Set: PID
text_PID = pd.read_parquet(TEXT2TEXT_FILES["PID"])
print("PID shape:", text_PID.shape)
summary_PID = run_text2text_set("PID", text_PID)
summary_PID

PID shape: (5592, 612)
[PID] text2text feature count after cleanup: 610

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST

[I 2026-04-09 11:25:19,590] A new study created in memory with name: multiclass_xgb

[PID] rows missing after index match -> train: 1193, test: 131

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST
X_train: (4146, 1080), X_test: (461, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 11:25:53,170] Trial 0 finished with value: 0.6570647149336668 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6570647149336668.
[I 2026-04-09 11:26:16,535] Trial 1 finished with value: 0.6509148244905224 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6570647149336668.
[I 2026-04-09 11:26:51,327] Trial 2 finished with value: 0.657240097940272 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.657240097940272.
[I 2026-04-09 11:27:12,892] Trial 3 finished with value: 0.654981052050113 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.657240097940272.
[I 2026-04-09 11:27:36,266] Trial 4 finished with value: 0.6564591054458001 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.657240097940272.
[I 2026-04-09 11:28:13,049] Trial 5 finished with value: 0.6590715485660266 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 5 with value: 0.6590715485660266.
[I 2026-04-09 11:28:26,892] Trial 6 finished with value: 0.652032548936499 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 5 with value: 0.6590715485660266.
[I 2026-04-09 11:29:09,086] Trial 7 finished with value: 0.6624221347531271 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 7 with value: 0.6624221347531271.
[I 2026-04-09 11:29:29,731] Trial 8 finished with value: 0.6514794835069295 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 7 with value: 0.6624221347531271.
[I 2026-04-09 11:30:35,856] Trial 9 finished with value: 0.6623201238764779 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 7 with value: 0.6624221347531271.
[I 2026-04-09 11:31:24,892] Trial 10 finished with value: 0.6554587717227596 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 6.0796977549919955, 'subsample': 0.8386834652924317, 'colsample_bytree': 0.9984958032960148, 'gamma': 1.343695477455153, 'reg_alpha': 9.157669588453277, 'reg_lambda': 7.2116802788205145}. Best is trial 7 with value: 0.6624221347531271.
[I 2026-04-09 11:32:39,902] Trial 11 finished with value: 0.6644577533748004 and parameters: {'learning_rate': 0.02089779586392043, 'max_depth': 7, 'min_child_weight': 2.1219156280219513, 'subsample': 0.804330492726395, 'colsample_bytree': 0.8277506537128274, 'gamma': 0.6941890889293743, 'reg_alpha': 0.19895007030204176, 'reg_lambda': 0.11611475940337539}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:33:41,246] Trial 12 finished with value: 0.6570424704428663 and parameters: {'learning_rate': 0.03204182671067435, 'max_depth': 8, 'min_child_weight': 2.2198058327301933, 'subsample': 0.8270227306279164, 'colsample_bytree': 0.8266420405575274, 'gamma': 0.6394074757286348, 'reg_alpha': 0.0031841301424337977, 'reg_lambda': 0.2283158677263137}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:34:33,598] Trial 13 finished with value: 0.6575417965617006 and parameters: {'learning_rate': 0.03189675559745468, 'max_depth': 7, 'min_child_weight': 2.4162493410850194, 'subsample': 0.8861192197466043, 'colsample_bytree': 0.8685753186474328, 'gamma': 1.1918886387101697, 'reg_alpha': 0.6219860865205207, 'reg_lambda': 0.0151557614491512}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:35:45,552] Trial 14 finished with value: 0.6637562638457645 and parameters: {'learning_rate': 0.02012431600829789, 'max_depth': 7, 'min_child_weight': 1.1157937296124318, 'subsample': 0.8143976461378967, 'colsample_bytree': 0.8230225154054815, 'gamma': 1.4342030207173062, 'reg_alpha': 0.00010631849056947566, 'reg_lambda': 0.18384655478056627}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:36:54,862] Trial 15 finished with value: 0.6612836004930257 and parameters: {'learning_rate': 0.020069475674219642, 'max_depth': 7, 'min_child_weight': 1.0628416416306987, 'subsample': 0.8230878249354645, 'colsample_bytree': 0.8174395718106435, 'gamma': 1.4919749451196884, 'reg_alpha': 0.00019273676716594963, 'reg_lambda': 0.00016599250040776937}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:37:45,262] Trial 16 finished with value: 0.6574263869749939 and parameters: {'learning_rate': 0.04605402385866375, 'max_depth': 8, 'min_child_weight': 1.0109342673565944, 'subsample': 0.9119186247116834, 'colsample_bytree': 0.8921254911151859, 'gamma': 0.855198763442772, 'reg_alpha': 0.00010543792781593167, 'reg_lambda': 0.9080484832243305}. Best is trial 11 with value: 0.6644577533748004.
[I 2026-04-09 11:38:59,157] Trial 17 finished with value: 0.667887609509531 and parameters: {'learning_rate': 0.025088459466204353, 'max_depth': 7, 'min_child_weight': 1.404591799972248, 'subsample': 0.7405375604260702, 'colsample_bytree': 0.8401186005417874, 'gamma': 0.5308300924473123, 'reg_alpha': 0.0035970628817152232, 'reg_lambda': 0.007780059588957784}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:40:08,765] Trial 18 finished with value: 0.6533500139117137 and parameters: {'learning_rate': 0.02760464355872065, 'max_depth': 7, 'min_child_weight': 1.4708348399206885, 'subsample': 0.742904755879342, 'colsample_bytree': 0.7844663925138409, 'gamma': 0.4133404396771981, 'reg_alpha': 0.005404058892421204, 'reg_lambda': 0.006809368659728113}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:40:47,980] Trial 19 finished with value: 0.6610747401733331 and parameters: {'learning_rate': 0.07125094355774181, 'max_depth': 8, 'min_child_weight': 2.408383025315213, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.8541879201227646, 'gamma': 0.5867131155382987, 'reg_alpha': 0.0012970753064544325, 'reg_lambda': 0.013612983451982738}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:41:26,911] Trial 20 finished with value: 0.6588573823566318 and parameters: {'learning_rate': 0.04202056729911136, 'max_depth': 4, 'min_child_weight': 2.007241180709328, 'subsample': 0.7667593286370472, 'colsample_bytree': 0.8966532963488568, 'gamma': 0.84415394341317, 'reg_alpha': 0.06878735231570768, 'reg_lambda': 0.0030260406883185482}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:42:39,807] Trial 21 finished with value: 0.6611141409810269 and parameters: {'learning_rate': 0.02503471488348673, 'max_depth': 7, 'min_child_weight': 1.2740396670035827, 'subsample': 0.801651637983695, 'colsample_bytree': 0.830370081810396, 'gamma': 0.45693027753376914, 'reg_alpha': 0.0006559879975896574, 'reg_lambda': 0.03060819962622547}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:43:53,808] Trial 22 finished with value: 0.6617475604511411 and parameters: {'learning_rate': 0.020560229810188537, 'max_depth': 7, 'min_child_weight': 1.2044753949219393, 'subsample': 0.7439386823087754, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.3266065687769162, 'reg_alpha': 0.01490769858845059, 'reg_lambda': 0.23851897875898298}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:44:58,231] Trial 23 finished with value: 0.6614016527422557 and parameters: {'learning_rate': 0.026200565694058684, 'max_depth': 8, 'min_child_weight': 1.712368515490205, 'subsample': 0.8624876173334466, 'colsample_bytree': 0.800124668641317, 'gamma': 0.9578603613744315, 'reg_alpha': 0.00032324079085304936, 'reg_lambda': 0.03113312454798587}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:45:51,422] Trial 24 finished with value: 0.6619038722107815 and parameters: {'learning_rate': 0.02775550991314997, 'max_depth': 6, 'min_child_weight': 2.8607670606754, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.8458780208280289, 'gamma': 1.5968046283026516, 'reg_alpha': 0.0013768231171186274, 'reg_lambda': 1.5689940733121257}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:46:44,978] Trial 25 finished with value: 0.6611850776354253 and parameters: {'learning_rate': 0.04041249306377316, 'max_depth': 7, 'min_child_weight': 1.5194741818145292, 'subsample': 0.7585775953269742, 'colsample_bytree': 0.9108456578870305, 'gamma': 0.6714844326495821, 'reg_alpha': 0.044057485989428435, 'reg_lambda': 0.21132507926812702}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:47:28,189] Trial 26 finished with value: 0.6558746027426879 and parameters: {'learning_rate': 0.05625265643266363, 'max_depth': 7, 'min_child_weight': 1.189656976106312, 'subsample': 0.8439488186748025, 'colsample_bytree': 0.854116274507259, 'gamma': 0.4236240326060677, 'reg_alpha': 0.009358923139271886, 'reg_lambda': 0.08445771665309221}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:48:37,958] Trial 27 finished with value: 0.6648207410722202 and parameters: {'learning_rate': 0.0238298221048016, 'max_depth': 6, 'min_child_weight': 1.953540685517277, 'subsample': 0.7207454049306011, 'colsample_bytree': 0.8114640982895894, 'gamma': 0.286588693616594, 'reg_alpha': 0.0021534440895039585, 'reg_lambda': 0.00035756316269210055}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:49:30,376] Trial 28 finished with value: 0.6592589349358264 and parameters: {'learning_rate': 0.035723901008036636, 'max_depth': 6, 'min_child_weight': 2.0906393633631777, 'subsample': 0.7017567138016809, 'colsample_bytree': 0.7744171694449439, 'gamma': 0.22620650963484418, 'reg_alpha': 0.002219615747753108, 'reg_lambda': 0.0002741458935062077}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:50:20,027] Trial 29 finished with value: 0.6603656561810783 and parameters: {'learning_rate': 0.02404620882243502, 'max_depth': 4, 'min_child_weight': 2.8049566984400154, 'subsample': 0.7277245152113173, 'colsample_bytree': 0.8057350571154883, 'gamma': 0.30052076805588435, 'reg_alpha': 0.0005756958590880655, 'reg_lambda': 0.0005501710538711947}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:51:06,706] Trial 30 finished with value: 0.6629331256443697 and parameters: {'learning_rate': 0.028237936673421365, 'max_depth': 5, 'min_child_weight': 4.140646528769087, 'subsample': 0.722430892450008, 'colsample_bytree': 0.7661190822009092, 'gamma': 0.7610398532029564, 'reg_alpha': 0.010359517424654326, 'reg_lambda': 0.00012474533139253144}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:52:19,684] Trial 31 finished with value: 0.6593871869096054 and parameters: {'learning_rate': 0.023082651036729022, 'max_depth': 7, 'min_child_weight': 1.7609723170068112, 'subsample': 0.7547800210916986, 'colsample_bytree': 0.8304121982107345, 'gamma': 0.4963311091210705, 'reg_alpha': 0.00019196477079606316, 'reg_lambda': 0.0060069244089338975}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:53:29,120] Trial 32 finished with value: 0.6583525188065186 and parameters: {'learning_rate': 0.022651861961155824, 'max_depth': 6, 'min_child_weight': 1.8830254578817571, 'subsample': 0.8067308110518718, 'colsample_bytree': 0.8109638261811146, 'gamma': 0.05771683202274555, 'reg_alpha': 0.0010203978910710053, 'reg_lambda': 0.0004743045308279552}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:54:37,584] Trial 33 finished with value: 0.6587007151165788 and parameters: {'learning_rate': 0.030088046530175376, 'max_depth': 7, 'min_child_weight': 1.4473154872667844, 'subsample': 0.717475938286163, 'colsample_bytree': 0.8472651102103891, 'gamma': 0.35966453300825985, 'reg_alpha': 0.003421916434598793, 'reg_lambda': 0.3520555411047283}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:55:50,819] Trial 34 finished with value: 0.6557970989515648 and parameters: {'learning_rate': 0.03817338324585823, 'max_depth': 8, 'min_child_weight': 1.1364533754251334, 'subsample': 0.9408008086573181, 'colsample_bytree': 0.7898624398624682, 'gamma': 0.22478564146584842, 'reg_alpha': 0.7415914022914122, 'reg_lambda': 3.5516460967097347}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:56:10,964] Trial 35 finished with value: 0.6543067740979474 and parameters: {'learning_rate': 0.13739588267969374, 'max_depth': 6, 'min_child_weight': 1.3477776162017103, 'subsample': 0.7737524523929303, 'colsample_bytree': 0.8721734993439851, 'gamma': 0.9544887509629347, 'reg_alpha': 0.00010084428246738034, 'reg_lambda': 0.0014269203017051315}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:57:11,433] Trial 36 finished with value: 0.656824826367781 and parameters: {'learning_rate': 0.020434076332215636, 'max_depth': 5, 'min_child_weight': 2.5439448183470534, 'subsample': 0.8688427392752163, 'colsample_bytree': 0.8366408102842496, 'gamma': 0.7403989609194466, 'reg_alpha': 0.15864825326797627, 'reg_lambda': 0.0444835998611586}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:58:15,221] Trial 37 finished with value: 0.6640059317808745 and parameters: {'learning_rate': 0.05036055777592587, 'max_depth': 8, 'min_child_weight': 1.5688865958204077, 'subsample': 0.8264662552217417, 'colsample_bytree': 0.8147979503155238, 'gamma': 0.0362959963969714, 'reg_alpha': 0.005955567689322555, 'reg_lambda': 0.10386216102077771}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:58:44,857] Trial 38 finished with value: 0.6520308599365616 and parameters: {'learning_rate': 0.19852051149181543, 'max_depth': 8, 'min_child_weight': 1.634494647767139, 'subsample': 0.7335797507274485, 'colsample_bytree': 0.7574360005636968, 'gamma': 0.04908327382982641, 'reg_alpha': 0.005386738011255898, 'reg_lambda': 0.01571119601860721}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 11:59:19,559] Trial 39 finished with value: 0.6591471296309239 and parameters: {'learning_rate': 0.09364664749430403, 'max_depth': 8, 'min_child_weight': 3.323108318079665, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.7959793553795198, 'gamma': 0.16569292731790297, 'reg_alpha': 0.019426747742822274, 'reg_lambda': 0.003346863909069109}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:00:24,884] Trial 40 finished with value: 0.6569544842115497 and parameters: {'learning_rate': 0.04931765356386612, 'max_depth': 8, 'min_child_weight': 1.8530112881990872, 'subsample': 0.7763205873483855, 'colsample_bytree': 0.7275752081298277, 'gamma': 0.0249788767681091, 'reg_alpha': 0.04897202634695153, 'reg_lambda': 0.08944866037086571}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:00:56,914] Trial 41 finished with value: 0.6535546256301621 and parameters: {'learning_rate': 0.06174207027829031, 'max_depth': 7, 'min_child_weight': 1.3102421176489132, 'subsample': 0.8217028181702868, 'colsample_bytree': 0.8187138055307617, 'gamma': 1.7802713772449135, 'reg_alpha': 0.009142715825112734, 'reg_lambda': 0.12745522970653753}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:02:17,255] Trial 42 finished with value: 0.6617105549564896 and parameters: {'learning_rate': 0.02248581106006753, 'max_depth': 7, 'min_child_weight': 1.561777978108263, 'subsample': 0.7968709212651909, 'colsample_bytree': 0.7794288835951115, 'gamma': 0.5458311406323662, 'reg_alpha': 0.0025007402035799736, 'reg_lambda': 0.4527782044468493}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:03:29,446] Trial 43 finished with value: 0.6619266737348063 and parameters: {'learning_rate': 0.025383029438033573, 'max_depth': 6, 'min_child_weight': 2.1791021273220705, 'subsample': 0.8534789520558753, 'colsample_bytree': 0.8686691755263772, 'gamma': 0.31512846273038614, 'reg_alpha': 0.0003349226595155499, 'reg_lambda': 0.06038998090152908}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:04:30,016] Trial 44 finished with value: 0.653312113706323 and parameters: {'learning_rate': 0.035311579768541934, 'max_depth': 7, 'min_child_weight': 1.1295966433683782, 'subsample': 0.8844410337197464, 'colsample_bytree': 0.8092676689843782, 'gamma': 0.1881889641297732, 'reg_alpha': 3.7355773538538304, 'reg_lambda': 0.9510640048950318}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:05:06,055] Trial 45 finished with value: 0.6612659729752545 and parameters: {'learning_rate': 0.03004543199095362, 'max_depth': 3, 'min_child_weight': 1.3866553499028824, 'subsample': 0.835307063711986, 'colsample_bytree': 0.8383298010957568, 'gamma': 0.09699661181595198, 'reg_alpha': 0.26956413155131514, 'reg_lambda': 0.16229725994773753}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:05:29,655] Trial 46 finished with value: 0.6534300198860161 and parameters: {'learning_rate': 0.08127736875874281, 'max_depth': 8, 'min_child_weight': 1.9001391756707666, 'subsample': 0.7858286440276969, 'colsample_bytree': 0.8207867250217609, 'gamma': 1.942545108598805, 'reg_alpha': 0.025912598140714074, 'reg_lambda': 0.02293846436288686}. Best is trial 17 with value: 0.667887609509531.
[I 2026-04-09 12:06:38,408] Trial 47 finished with value: 0.6578638845811825 and parameters: {'learning_rate': 0.022069431053349096, 'max_depth': 6, 'min_child_weight': 1.0181413690274939, 'subsample': 0.8142565181861561, 'colsample_bytree': 0.8821943241895397, 'gamma': 1.0885558402500353, 'reg_alpha': 0.14192427153080298, 'reg_lambda': 0.049566566382887985}. Best is trial 17 with value: 0.667887609509531.

[I 2026-04-09 12:43:51,375] A new study created in memory with name: multiclass_catboost

[I 2026-04-09 12:43:51,372] Trial 99 finished with value: 0.6624152834392288 and parameters: {'learning_rate': 0.023634823313404857, 'max_depth': 3, 'min_child_weight': 5.458089621682127, 'subsample': 0.7466043813334211, 'colsample_bytree': 0.9211888026751155, 'gamma': 1.640315947398829, 'reg_alpha': 0.8449093098894853, 'reg_lambda': 0.008526915881616243}. Best is trial 81 with value: 0.6688594541174624.

Best model (xgb) CV score: 0.66886
Best params: {'learning_rate': 0.02350350376931667, 'max_depth': 3, 'min_child_weight': 4.059852682485556, 'subsample': 0.7268016303794373, 'colsample_bytree': 0.7490775788356872, 'gamma': 1.608599590101127, 'reg_alpha': 0.18140339274416478, 'reg_lambda': 0.00034796279935912555}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-09 12:44:21,355] Trial 0 finished with value: 0.6533998260169147 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6533998260169147.
[I 2026-04-09 12:45:28,192] Trial 1 finished with value: 0.6637126813458977 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 12:46:24,032] Trial 2 finished with value: 0.663671759951573 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 12:48:21,787] Trial 3 finished with value: 0.6596386778695678 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 12:51:10,448] Trial 4 finished with value: 0.646211584617533 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 12:56:12,728] Trial 5 finished with value: 0.6574529984670903 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 12:57:56,554] Trial 6 finished with value: 0.6586375974426052 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 13:00:58,188] Trial 7 finished with value: 0.6569513124400699 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 13:09:06,626] Trial 8 finished with value: 0.6511732020010773 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 13:10:33,967] Trial 9 finished with value: 0.6551926634459019 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6637126813458977.
[I 2026-04-09 13:11:53,199] Trial 10 finished with value: 0.6643080747369161 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 10 with value: 0.6643080747369161.
[I 2026-04-09 13:13:12,950] Trial 11 finished with value: 0.6628052448432722 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02005507141938724, 'depth': 4, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.20696700950514785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9614099298964858}. Best is trial 10 with value: 0.6643080747369161.
[I 2026-04-09 13:15:41,110] Trial 12 finished with value: 0.6582344679161739 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027764326872075, 'depth': 5, 'l2_leaf_reg': 13.859731742356656, 'random_strength': 0.02812276405828626, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9357491826204533}. Best is trial 10 with value: 0.6643080747369161.
[I 2026-04-09 13:16:44,864] Trial 13 finished with value: 0.6661189470288069 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03322501342278858, 'depth': 5, 'l2_leaf_reg': 5.838384756610479, 'random_strength': 0.41707559629394864, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8632850879711638}. Best is trial 13 with value: 0.6661189470288069.
[I 2026-04-09 13:17:41,081] Trial 14 finished with value: 0.669392049074137 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03370473289704124, 'depth': 5, 'l2_leaf_reg': 5.074742486962073, 'random_strength': 0.4100750513516051, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8751822615532037}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:18:36,117] Trial 15 finished with value: 0.6677232600903912 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03699604572505095, 'depth': 5, 'l2_leaf_reg': 4.469785293618988, 'random_strength': 0.4826792756902898, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8606167786973328}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:19:26,890] Trial 16 finished with value: 0.6625944929725555 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0456381581549657, 'depth': 5, 'l2_leaf_reg': 3.063719395525494, 'random_strength': 0.5657469824738883, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8533169096507082}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:20:24,350] Trial 17 finished with value: 0.6648628635673539 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033266921637459576, 'depth': 5, 'l2_leaf_reg': 3.4259063853980054, 'random_strength': 0.9538818842389969, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8572171363230319}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:21:05,970] Trial 18 finished with value: 0.663098116045075 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12236828332473569, 'depth': 6, 'l2_leaf_reg': 2.5170514356418203, 'random_strength': 0.6057389642617784, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9052798496970411}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:21:45,734] Trial 19 finished with value: 0.6661319072562475 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.058757686271242525, 'depth': 5, 'l2_leaf_reg': 6.037264986150572, 'random_strength': 0.5004464317464911, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7947265525057776}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:22:47,017] Trial 20 finished with value: 0.6599869007087059 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03486157207427892, 'depth': 5, 'l2_leaf_reg': 6.548528117273506, 'random_strength': 0.3937119620267663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9985354975991252}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:23:26,265] Trial 21 finished with value: 0.6657842365730059 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05503368372350892, 'depth': 5, 'l2_leaf_reg': 4.998279252766929, 'random_strength': 0.5062505609811581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8078940946681937}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:24:35,576] Trial 22 finished with value: 0.6619178921531174 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0583592900248928, 'depth': 6, 'l2_leaf_reg': 7.202129302884919, 'random_strength': 0.4935524273697246, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8152999995582851}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:25:24,283] Trial 23 finished with value: 0.6619797486081723 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039113981185853616, 'depth': 5, 'l2_leaf_reg': 3.7160198720941273, 'random_strength': 0.3359085288976157, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8994073075052955}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:28:06,555] Trial 24 finished with value: 0.6614915239384458 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029269931186043263, 'depth': 6, 'l2_leaf_reg': 9.255301713642998, 'random_strength': 0.7216385650811468, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7726253161952403}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:28:29,977] Trial 25 finished with value: 0.6634470602622138 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.052958380070673994, 'depth': 4, 'l2_leaf_reg': 2.5606975990537832, 'random_strength': 0.5289368372867533, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8262789129993652}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:29:06,822] Trial 26 finished with value: 0.6621523398613721 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0400793822082507, 'depth': 5, 'l2_leaf_reg': 5.64705976968263, 'random_strength': 0.4280224749247682, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:30:53,237] Trial 27 finished with value: 0.6613581207742827 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025713100633815357, 'depth': 6, 'l2_leaf_reg': 8.260309244424205, 'random_strength': 0.3104961941525005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8930720592438481}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:31:37,794] Trial 28 finished with value: 0.6619636049547168 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06008533680278842, 'depth': 5, 'l2_leaf_reg': 4.267920103718801, 'random_strength': 0.5648217924765327, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7827440114420318}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:32:13,434] Trial 29 finished with value: 0.641895159208626 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06720102616547326, 'depth': 4, 'l2_leaf_reg': 2.378432489616166, 'random_strength': 0.7363850071619753, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:32:35,950] Trial 30 finished with value: 0.6590029052161964 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11046216696028498, 'depth': 4, 'l2_leaf_reg': 1.7230976878437325, 'random_strength': 0.2622204051910455, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7260818355949821}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:33:34,185] Trial 31 finished with value: 0.6688276052565129 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03434456743986508, 'depth': 5, 'l2_leaf_reg': 6.0580020974421265, 'random_strength': 0.41388022055020357, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8605893033510459}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:34:44,915] Trial 32 finished with value: 0.6684063208692673 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029723598411849905, 'depth': 5, 'l2_leaf_reg': 5.550490214401384, 'random_strength': 0.38298887045490354, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.836628742629196}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:35:24,243] Trial 33 finished with value: 0.6683215311799283 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023922803451067606, 'depth': 4, 'l2_leaf_reg': 5.070851711091754, 'random_strength': 0.36849254971330714, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8435601911550803}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:36:24,430] Trial 34 finished with value: 0.6656266493609626 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022759635293145477, 'depth': 4, 'l2_leaf_reg': 11.770194845109927, 'random_strength': 0.12205710719047413, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8436074519297185}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:37:01,613] Trial 35 finished with value: 0.6685253706976516 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03010541296608349, 'depth': 4, 'l2_leaf_reg': 7.398832966712246, 'random_strength': 0.3685178097786453, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8788916831540913}. Best is trial 14 with value: 0.669392049074137.
[I 2026-04-09 13:37:28,648] Trial 36 finished with value: 0.6725279303462685 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029070704553949393, 'depth': 4, 'l2_leaf_reg': 7.477127221494707, 'random_strength': 0.36185441401212187, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8899063563316792}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:37:55,807] Trial 37 finished with value: 0.6638926059305068 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.042763395396532525, 'depth': 4, 'l2_leaf_reg': 8.004299805384276, 'random_strength': 0.16228359294275788, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9195336930672197}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:38:24,614] Trial 38 finished with value: 0.6650203277312362 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.026289124649140138, 'depth': 4, 'l2_leaf_reg': 11.772409506902857, 'random_strength': 0.21380259356400716, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.12221043743904225}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:38:50,133] Trial 39 finished with value: 0.6701318584700597 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031817583935583885, 'depth': 4, 'l2_leaf_reg': 6.893215199825507, 'random_strength': 0.43101387179992995, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8856433141377169}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:39:27,121] Trial 40 finished with value: 0.6633844804711968 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03398899805924656, 'depth': 4, 'l2_leaf_reg': 9.227597382455714, 'random_strength': 0.4463816752904371, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.4532051511681003}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:39:53,361] Trial 41 finished with value: 0.6699262473415089 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03071239325393147, 'depth': 4, 'l2_leaf_reg': 7.20496315195792, 'random_strength': 0.3325463777468716, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8775848422193672}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:40:13,141] Trial 42 finished with value: 0.6650824739623159 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04970838293147314, 'depth': 4, 'l2_leaf_reg': 6.864378232451267, 'random_strength': 0.2863159631397325, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.880686930597832}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:40:40,365] Trial 43 finished with value: 0.6656576512080922 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03219312995720406, 'depth': 4, 'l2_leaf_reg': 8.747502756548732, 'random_strength': 0.32590520969069814, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9224806358469549}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:47:09,903] Trial 44 finished with value: 0.666263220007751 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023427395577749317, 'depth': 7, 'l2_leaf_reg': 10.978448525736182, 'random_strength': 0.42232865763536215, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8776497517367897}. Best is trial 36 with value: 0.6725279303462685.
[I 2026-04-09 13:47:34,388] Trial 45 finished with value: 0.6661131540025667 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.041445276781307556, 'depth': 4, 'l2_leaf_reg': 6.51709575611034, 'random_strength': 0.22820063856834538, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9120381497756592}. Best is trial 36 with value: 0.6725279303462685.

                                         feature  importance
276     eye__fix_duration_AOI_aggregated_Pos_min    0.022874
184          eye__fix_duration_AOI_FD_Neg1_count    0.022613
29        eye__sac_length_AOI_aggregated_Neg_min    0.020072
177            eye__fix_duration_AOI_FD_Neg1_max    0.016650
62        eye__sac_speed_AOI_aggregated_Pos_mean    0.016568
30        eye__sac_length_AOI_aggregated_Neg_max    0.014650
61         eye__sac_speed_AOI_aggregated_Pos_max    0.013592
175          eye__fix_duration_AOI_FD_Neg1_first    0.012613
54        eye__sac_length_AOI_aggregated_Pos_max    0.012601
63      eye__sac_speed_AOI_aggregated_Pos_median    0.012439
31       eye__sac_length_AOI_aggregated_Neg_mean    0.010870
55       eye__sac_length_AOI_aggregated_Pos_mean    0.010784
56     eye__sac_length_AOI_aggregated_Pos_median    0.010001
176            eye__fix_duration_AOI_FD_Neg1_min    0.009148
178           eye__fix_duration_AOI_FD_Neg1_mean    0.009014
53        eye__sac_length_AOI_aggregated_Pos_min    0.008082
277     eye__fix_duration_AOI_aggregated_Pos_max    0.006952
34        eye__sac_length_AOI_aggregated_Neg_sum    0.006474
782          PID__PID_C4_first_deriv_energy_mean    0.005930
32     eye__sac_length_AOI_aggregated_Neg_median    0.005787
183            eye__fix_duration_AOI_FD_Neg1_sum    0.005673
274  eye__fix_duration_AOI_aggregated_None_count    0.005449
194          eye__fix_duration_AOI_FD_None_count    0.005166
60         eye__sac_speed_AOI_aggregated_Pos_min    0.005148
797          PID__PID_F6_first_deriv_energy_mean    0.004936
47     eye__sac_length_AOI_aggregated_None_count    0.004332
791          PID__PID_Cz_first_deriv_energy_mean    0.003942
838        PID__PID_AF7_second_deriv_energy_mean    0.003837
533               PID__PID_AF7_second_deriv_mean    0.003818
191       eye__fix_duration_AOI_FD_None_kurtosis    0.003635

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.77404
              precision    recall  f1-score   support

           0       0.77      0.63      0.70       156
           1       0.80      0.74      0.77       180
           2       0.75      1.00      0.86       125

    accuracy                           0.77       461
   macro avg       0.77      0.79      0.77       461
weighted avg       0.78      0.77      0.77       461

Confusion matrix:
 [[ 99  33  24]
 [ 29 133  18]
 [  0   0 125]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\feature_importances_eye_text2text\exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
258    eye__fix_duration_AOI_aggregated_Neg_mean    9.757130
39      eye__sac_speed_AOI_aggregated_Neg_median    6.285012
35      eye__sac_length_AOI_aggregated_Neg_count    5.699372
30        eye__sac_length_AOI_aggregated_Neg_max    4.912150
175          eye__fix_duration_AOI_FD_Neg1_first    4.503257
32     eye__sac_length_AOI_aggregated_Neg_median    4.222576
176            eye__fix_duration_AOI_FD_Neg1_min    3.514817
256     eye__fix_duration_AOI_aggregated_Neg_min    3.190887
34        eye__sac_length_AOI_aggregated_Neg_sum    3.178013
184          eye__fix_duration_AOI_FD_Neg1_count    2.762312
53        eye__sac_length_AOI_aggregated_Pos_min    2.715755
61         eye__sac_speed_AOI_aggregated_Pos_max    2.523253
257     eye__fix_duration_AOI_aggregated_Neg_max    2.361758
62        eye__sac_speed_AOI_aggregated_Pos_mean    2.338375
259  eye__fix_duration_AOI_aggregated_Neg_median    2.261234
29        eye__sac_length_AOI_aggregated_Neg_min    2.126712
277     eye__fix_duration_AOI_aggregated_Pos_max    2.065764
264   eye__fix_duration_AOI_aggregated_Neg_count    1.794878
55       eye__sac_length_AOI_aggregated_Pos_mean    1.704520
263     eye__fix_duration_AOI_aggregated_Neg_sum    1.635440
59      eye__sac_length_AOI_aggregated_Pos_count    1.634082
208           eye__fix_duration_AOI_FD_Pos1_mean    1.590968
31       eye__sac_length_AOI_aggregated_Neg_mean    1.473243
206            eye__fix_duration_AOI_FD_Pos1_min    1.357964
58        eye__sac_length_AOI_aggregated_Pos_sum    1.220840
179         eye__fix_duration_AOI_FD_Neg1_median    1.179713
37         eye__sac_speed_AOI_aggregated_Neg_max    1.091512
46       eye__sac_length_AOI_aggregated_None_sum    1.086535
276     eye__fix_duration_AOI_aggregated_Pos_min    1.064329
275   eye__fix_duration_AOI_aggregated_Pos_first    1.015702

,text_set,target,split,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,0.399740,0.443317,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,multiclass,0.627365,0.624341,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch_general,binary,0.398957,0.478687,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch_general,multiclass,0.795993,0.774045,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,0.399740,0.443317,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,multiclass,0.627365,0.624341,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch_general,binary,0.398957,0.478687,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch_general,multiclass,0.795993,0.774045,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [10]:
# Set: stat
text_stat = pd.read_parquet(TEXT2TEXT_FILES["stat"])
print("stat shape:", text_stat.shape)
summary_stat = run_text2text_set("stat", text_stat)
summary_stat

stat shape: (5592, 8237)
[stat] text2text feature count after cleanup: 8235
[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

[I 2026-04-09 13:52:39,992] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 13:52:44,604] Trial 0 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-09 13:52:50,560] Trial 1 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-09 13:52:56,167] Trial 2 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-09 13:53:02,206] Trial 3 finished with value: 0.400146279923372 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-09 13:53:08,533] Trial 4 finished with value: 0.4084872047054853 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:14,794] Trial 5 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:20,600] Trial 6 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:27,280] Trial 7 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:33,446] Trial 8 finished with value: 0.4029898185245832 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:40,681] Trial 9 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:45,640] Trial 10 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.07985847190685645, 'max_depth': 8, 'min_child_weight': 5.7644975171451085, 'subsample': 0.8853830026900457, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4769827267624924, 'reg_alpha': 9.072541150259902, 'reg_lambda': 0.00015423477789158795}. Best is trial 4 with value: 0.4084872047054853.
[I 2026-04-09 13:53:51,391] Trial 11 finished with value: 0.4096988860618514 and parameters: {'learning_rate': 0.10792903804549149, 'max_depth': 7, 'min_child_weight': 2.0632174240992716, 'subsample': 0.9075863567066681, 'colsample_bytree': 0.9145278309276617, 'gamma': 1.2615827674464564, 'reg_alpha': 1.811950242626371, 'reg_lambda': 0.002691378467733369}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:53:57,940] Trial 12 finished with value: 0.4062801052292092 and parameters: {'learning_rate': 0.07561377665306217, 'max_depth': 7, 'min_child_weight': 1.9785115086708194, 'subsample': 0.91226032947221, 'colsample_bytree': 0.999748196231103, 'gamma': 1.4468467635740234, 'reg_alpha': 1.174699620577957, 'reg_lambda': 0.006067797792775078}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:02,376] Trial 13 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.12844075092236562, 'max_depth': 7, 'min_child_weight': 2.452792920089121, 'subsample': 0.9260903047700676, 'colsample_bytree': 0.9021555920100515, 'gamma': 1.9769544774983088, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.00013075557194894895}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:08,780] Trial 14 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.1246669235867374, 'max_depth': 7, 'min_child_weight': 1.1157937296124318, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8204904540159066, 'gamma': 1.3242779353320264, 'reg_alpha': 0.00010480002361979782, 'reg_lambda': 0.0015125735928679636}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:13,630] Trial 15 finished with value: 0.40030569258278464 and parameters: {'learning_rate': 0.06281412715448802, 'max_depth': 3, 'min_child_weight': 5.788333534030292, 'subsample': 0.9907425579887397, 'colsample_bytree': 0.9190607752204869, 'gamma': 1.7055985710563375, 'reg_alpha': 0.0052624690677942785, 'reg_lambda': 0.00922948629070968}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:21,161] Trial 16 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.08533042118530673, 'max_depth': 8, 'min_child_weight': 2.4778655412358472, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8697240947421665, 'gamma': 0.7225884405958181, 'reg_alpha': 0.2970915416400644, 'reg_lambda': 0.0006135731265857054}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:27,194] Trial 17 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.10937919961077498, 'max_depth': 7, 'min_child_weight': 5.534761521181527, 'subsample': 0.9036602785507087, 'colsample_bytree': 0.9583705008325315, 'gamma': 1.245382399139096, 'reg_alpha': 0.07012968339615325, 'reg_lambda': 0.0038559561514423355}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:33,808] Trial 18 finished with value: 0.4065408651829825 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 7, 'min_child_weight': 2.4928618423835385, 'subsample': 0.9420160242614785, 'colsample_bytree': 0.8313188771741552, 'gamma': 1.710245698698066, 'reg_alpha': 0.673684512281111, 'reg_lambda': 0.00036460414934968006}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:39,821] Trial 19 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.15243611890008724, 'max_depth': 8, 'min_child_weight': 4.280142507481086, 'subsample': 0.8675910314884802, 'colsample_bytree': 0.8992628542973774, 'gamma': 0.5027434350038814, 'reg_alpha': 2.926663816617869, 'reg_lambda': 0.0023805889009396526}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:45,471] Trial 20 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.042350163788700664, 'max_depth': 4, 'min_child_weight': 7.150872829730187, 'subsample': 0.8207531213984746, 'colsample_bytree': 0.9866803963716699, 'gamma': 0.9262158820602485, 'reg_alpha': 0.005842369188262318, 'reg_lambda': 0.017348574039185}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:51,953] Trial 21 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.06631140506079448, 'max_depth': 7, 'min_child_weight': 2.385016772405048, 'subsample': 0.9414435068417403, 'colsample_bytree': 0.8236979463098082, 'gamma': 1.6933292393840693, 'reg_alpha': 0.49873064771391346, 'reg_lambda': 0.00031221306375853127}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:54:58,907] Trial 22 finished with value: 0.40062348610446163 and parameters: {'learning_rate': 0.05935076662418546, 'max_depth': 7, 'min_child_weight': 2.9231862330137433, 'subsample': 0.8952571143318928, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.8226463497599472, 'reg_alpha': 0.09788971087576712, 'reg_lambda': 0.00043808415534596264}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:55:04,820] Trial 23 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.09305631432839585, 'max_depth': 8, 'min_child_weight': 1.4911017557224766, 'subsample': 0.9433669916479679, 'colsample_bytree': 0.8277959417932532, 'gamma': 1.5350054274177183, 'reg_alpha': 0.8796512233108671, 'reg_lambda': 0.0014994697171216405}. Best is trial 11 with value: 0.4096988860618514.
[I 2026-04-09 13:55:10,316] Trial 24 finished with value: 0.41794446732884927 and parameters: {'learning_rate': 0.07220914023184906, 'max_depth': 6, 'min_child_weight': 2.1264455655280803, 'subsample': 0.9650472788715693, 'colsample_bytree': 0.890896158660567, 'gamma': 1.3449968628172997, 'reg_alpha': 4.261487185480772, 'reg_lambda': 0.0002523429684948399}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:15,426] Trial 25 finished with value: 0.4080684983458234 and parameters: {'learning_rate': 0.10287159015679795, 'max_depth': 6, 'min_child_weight': 1.043127258260343, 'subsample': 0.9680230254439856, 'colsample_bytree': 0.9188519655395371, 'gamma': 1.249467951173325, 'reg_alpha': 4.405963149320362, 'reg_lambda': 0.00010275701907606124}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:20,118] Trial 26 finished with value: 0.405104151950116 and parameters: {'learning_rate': 0.1440341819543721, 'max_depth': 6, 'min_child_weight': 1.9128059130603985, 'subsample': 0.9950275800498969, 'colsample_bytree': 0.8807007671624207, 'gamma': 1.3749988651583263, 'reg_alpha': 3.791136061618814, 'reg_lambda': 0.026487878859922043}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:24,934] Trial 27 finished with value: 0.40316743295392116 and parameters: {'learning_rate': 0.07815561448604773, 'max_depth': 5, 'min_child_weight': 4.462651900933986, 'subsample': 0.8735922662138826, 'colsample_bytree': 0.9062656285910101, 'gamma': 0.9925717200855599, 'reg_alpha': 0.1590288321112953, 'reg_lambda': 0.0011353416661146708}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:30,635] Trial 28 finished with value: 0.4063995740528631 and parameters: {'learning_rate': 0.05056040074102512, 'max_depth': 7, 'min_child_weight': 3.1591320119828703, 'subsample': 0.913224625233086, 'colsample_bytree': 0.9482892142516701, 'gamma': 1.561681047423052, 'reg_alpha': 1.7706656242491827, 'reg_lambda': 0.0036465149290195466}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:34,171] Trial 29 finished with value: 0.4102937471504534 and parameters: {'learning_rate': 0.19839989166716254, 'max_depth': 4, 'min_child_weight': 3.81723063814416, 'subsample': 0.9652264226502867, 'colsample_bytree': 0.9256157727103769, 'gamma': 1.2343066454237617, 'reg_alpha': 5.753079807724836, 'reg_lambda': 0.00019974275020931753}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:38,143] Trial 30 finished with value: 0.4019228667903203 and parameters: {'learning_rate': 0.18748251884555237, 'max_depth': 4, 'min_child_weight': 3.9567445723774686, 'subsample': 0.9688204747340797, 'colsample_bytree': 0.8609757028064935, 'gamma': 1.1529499247077486, 'reg_alpha': 5.544154050118195, 'reg_lambda': 0.00020281649381084086}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:41,819] Trial 31 finished with value: 0.39966596490722633 and parameters: {'learning_rate': 0.19767836445055886, 'max_depth': 3, 'min_child_weight': 3.555035993941399, 'subsample': 0.9153985797968336, 'colsample_bytree': 0.923934158005812, 'gamma': 1.236688247947316, 'reg_alpha': 9.647330316171226, 'reg_lambda': 0.000719082027795475}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:46,805] Trial 32 finished with value: 0.39966596490722633 and parameters: {'learning_rate': 0.14445728026025265, 'max_depth': 4, 'min_child_weight': 2.087266991673358, 'subsample': 0.9296491934436573, 'colsample_bytree': 0.9667134770043112, 'gamma': 0.8541217953445293, 'reg_alpha': 2.377396951973199, 'reg_lambda': 5.2330693225521046}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:53,390] Trial 33 finished with value: 0.41051730937576464 and parameters: {'learning_rate': 0.044668616158777104, 'max_depth': 5, 'min_child_weight': 5.124801018411309, 'subsample': 0.9582082245086326, 'colsample_bytree': 0.8906397508419133, 'gamma': 1.3656900244473071, 'reg_alpha': 1.3791545784980441, 'reg_lambda': 0.0002598796472935813}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:55:59,112] Trial 34 finished with value: 0.40651200129392584 and parameters: {'learning_rate': 0.03562576852888588, 'max_depth': 4, 'min_child_weight': 5.042126539767544, 'subsample': 0.9578135168919922, 'colsample_bytree': 0.8914650382634366, 'gamma': 1.365914522387552, 'reg_alpha': 0.7575464804529611, 'reg_lambda': 0.00025122898923172826}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:05,317] Trial 35 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.024284773322738092, 'max_depth': 5, 'min_child_weight': 1.2762902883554468, 'subsample': 0.9847199104377456, 'colsample_bytree': 0.8431313876900295, 'gamma': 1.1541347355182958, 'reg_alpha': 1.98037001337723, 'reg_lambda': 0.0007484811036421435}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:10,441] Trial 36 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.04164117883649767, 'max_depth': 4, 'min_child_weight': 2.8475298749697275, 'subsample': 0.9585134423788754, 'colsample_bytree': 0.7833745228700946, 'gamma': 0.9937676738033192, 'reg_alpha': 0.002277853505196298, 'reg_lambda': 0.00031811145638454695}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:15,259] Trial 37 finished with value: 0.4009083301040268 and parameters: {'learning_rate': 0.053835771245663126, 'max_depth': 5, 'min_child_weight': 1.7289566352694972, 'subsample': 0.9785482037213632, 'colsample_bytree': 0.8780886809968591, 'gamma': 1.577893977186256, 'reg_alpha': 4.7652531458545155, 'reg_lambda': 0.00011079465667735099}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:21,197] Trial 38 finished with value: 0.40225912958402754 and parameters: {'learning_rate': 0.04928896632341969, 'max_depth': 5, 'min_child_weight': 3.7416065861413674, 'subsample': 0.9315942622993971, 'colsample_bytree': 0.928698082618482, 'gamma': 1.387609916981438, 'reg_alpha': 0.42543347236951934, 'reg_lambda': 0.000548634751625756}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:27,285] Trial 39 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.028522992696152435, 'max_depth': 6, 'min_child_weight': 6.957907726235103, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.7996395421646056, 'gamma': 1.258007205512923, 'reg_alpha': 0.012797744257730474, 'reg_lambda': 0.27608497748487243}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:32,212] Trial 40 finished with value: 0.400146279923372 and parameters: {'learning_rate': 0.038576401164847354, 'max_depth': 3, 'min_child_weight': 2.0970268515471875, 'subsample': 0.7282571436393164, 'colsample_bytree': 0.9126914488512208, 'gamma': 1.050216981087254, 'reg_alpha': 1.2576226844342646, 'reg_lambda': 0.00022386143888951824}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:37,664] Trial 41 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.09311311930742017, 'max_depth': 6, 'min_child_weight': 6.799206027641376, 'subsample': 0.8865988807182966, 'colsample_bytree': 0.9427663272423723, 'gamma': 1.7802713772449135, 'reg_alpha': 0.20485236122602593, 'reg_lambda': 0.0009716561060072432}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:42,690] Trial 42 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.07260734606832535, 'max_depth': 6, 'min_child_weight': 4.8945354882087395, 'subsample': 0.9538298743812592, 'colsample_bytree': 0.8906175611258308, 'gamma': 1.8665591248355065, 'reg_alpha': 0.04713209193993019, 'reg_lambda': 0.0023182849567212507}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:47,666] Trial 43 finished with value: 0.40062348610446163 and parameters: {'learning_rate': 0.057357770952688715, 'max_depth': 5, 'min_child_weight': 8.247439323739567, 'subsample': 0.8549550007917873, 'colsample_bytree': 0.9310034736326338, 'gamma': 0.008050105358543558, 'reg_alpha': 2.5766083812285285, 'reg_lambda': 1.5550251683113594}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:51,364] Trial 44 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.16813529054984547, 'max_depth': 5, 'min_child_weight': 6.375701468569855, 'subsample': 0.9261228121771062, 'colsample_bytree': 0.9533170639152052, 'gamma': 1.4865962653763531, 'reg_alpha': 5.487818937344375, 'reg_lambda': 0.015040794325266268}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:56:58,358] Trial 45 finished with value: 0.40588320941710665 and parameters: {'learning_rate': 0.07106836872500344, 'max_depth': 7, 'min_child_weight': 4.895239603652572, 'subsample': 0.9723847059510078, 'colsample_bytree': 0.977103904837278, 'gamma': 0.28033953368701825, 'reg_alpha': 1.0964944562655459, 'reg_lambda': 0.0055355235710283154}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:57:04,373] Trial 46 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.08729564552661336, 'max_depth': 6, 'min_child_weight': 7.992477471972146, 'subsample': 0.7044631716730756, 'colsample_bytree': 0.8674553585287559, 'gamma': 1.62635875349203, 'reg_alpha': 0.1451400512784598, 'reg_lambda': 0.00018302403220777218}. Best is trial 24 with value: 0.41794446732884927.
[I 2026-04-09 13:57:09,367] Trial 47 finished with value: 0.40491816697726857 and parameters: {'learning_rate': 0.11017167617235361, 'max_depth': 4, 'min_child_weight': 3.295257934385074, 'subsample': 0.9050371106609506, 'colsample_bytree': 0.851031775095118, 'gamma': 0.7066823293687511, 'reg_alpha': 0.36228508341641047, 'reg_lambda': 0.0005081412736040609}. Best is trial 24 with value: 0.41794446732884927.

[I 2026-04-09 14:01:31,875] A new study created in memory with name: binary_catboost

[I 2026-04-09 14:01:31,870] Trial 99 finished with value: 0.4017543837337614 and parameters: {'learning_rate': 0.06611713449321957, 'max_depth': 5, 'min_child_weight': 2.385242473095195, 'subsample': 0.9296835783019717, 'colsample_bytree': 0.7200072766461083, 'gamma': 1.2843860002572904, 'reg_alpha': 2.2958467353737184, 'reg_lambda': 0.00021996321571138833}. Best is trial 24 with value: 0.41794446732884927.

Best model (xgb) CV score: 0.41794
Best params: {'learning_rate': 0.07220914023184906, 'max_depth': 6, 'min_child_weight': 2.1264455655280803, 'subsample': 0.9650472788715693, 'colsample_bytree': 0.890896158660567, 'gamma': 1.3449968628172997, 'reg_alpha': 4.261487185480772, 'reg_lambda': 0.0002523429684948399}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-09 14:01:36,857] Trial 0 finished with value: 0.4024269155986411 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4024269155986411.
[I 2026-04-09 14:01:46,912] Trial 1 finished with value: 0.4088904053636494 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4088904053636494.
[I 2026-04-09 14:01:54,416] Trial 2 finished with value: 0.42288819764821295 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.42288819764821295.
[I 2026-04-09 14:02:10,511] Trial 3 finished with value: 0.41237690936959426 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.42288819764821295.
[I 2026-04-09 14:02:30,101] Trial 4 finished with value: 0.45732600598889706 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:02:57,335] Trial 5 finished with value: 0.4230993834598096 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:03:10,233] Trial 6 finished with value: 0.4020082734710525 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:03:29,277] Trial 7 finished with value: 0.4007818691904268 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:03:57,274] Trial 8 finished with value: 0.4022008180978657 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:04:09,623] Trial 9 finished with value: 0.40506760778862655 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:04:14,454] Trial 10 finished with value: 0.4283542657282816 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.45732600598889706.
[I 2026-04-09 14:04:19,255] Trial 11 finished with value: 0.46889935943634864 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.7651302031192428, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9606029800630493}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:24,007] Trial 12 finished with value: 0.4631189136370766 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 5, 'l2_leaf_reg': 1.9426894697963841, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.994759737357233}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:28,838] Trial 13 finished with value: 0.4429095758050758 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12821872834050937, 'depth': 5, 'l2_leaf_reg': 2.869741965176845, 'random_strength': 0.0019953199023174653, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9990262441311949}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:33,621] Trial 14 finished with value: 0.44640735702854056 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13517895405905175, 'depth': 5, 'l2_leaf_reg': 1.0048860545911136, 'random_strength': 0.2590914992532189, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8791010705732631}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:38,063] Trial 15 finished with value: 0.45112374277780043 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1983058867595879, 'depth': 5, 'l2_leaf_reg': 2.7164936480539428, 'random_strength': 0.0031871620871804594, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.983281286847926}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:41,417] Trial 16 finished with value: 0.4306136890465115 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12138843123043136, 'depth': 4, 'l2_leaf_reg': 2.717623750426407, 'random_strength': 0.4776807852053371, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8677845342335468}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:47,341] Trial 17 finished with value: 0.45381522728253293 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14275466267871886, 'depth': 6, 'l2_leaf_reg': 1.3718551066349767, 'random_strength': 0.14684118999577356, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9180378512700119}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:04:53,250] Trial 18 finished with value: 0.4173743190092165 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.037571908436305174, 'depth': 5, 'l2_leaf_reg': 4.017839861830454, 'random_strength': 0.35807103528149264, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8320558356371248}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:00,479] Trial 19 finished with value: 0.4508038570978993 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10636814424224962, 'depth': 6, 'l2_leaf_reg': 2.1467385130540935, 'random_strength': 0.21878235521475725, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9394716488088194}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:04,000] Trial 20 finished with value: 0.4471736980311956 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16003507395365793, 'depth': 4, 'l2_leaf_reg': 5.961237427925943, 'random_strength': 0.07645692078703961, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9992641033718818}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:09,034] Trial 21 finished with value: 0.4419832276935405 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18722110879072262, 'depth': 5, 'l2_leaf_reg': 1.4652488539637256, 'random_strength': 0.05600767928246393, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7770313214063104}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:29,055] Trial 22 finished with value: 0.4594046012032732 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15666142900040927, 'depth': 8, 'l2_leaf_reg': 1.2730677748069794, 'random_strength': 0.08890093055409821, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7217265015665683}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:36,112] Trial 23 finished with value: 0.4559096171365801 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10986685370376416, 'depth': 6, 'l2_leaf_reg': 1.23801565034115, 'random_strength': 0.1117876660708359, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7121030183699014}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:47,658] Trial 24 finished with value: 0.4458199508648561 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14959624639032026, 'depth': 7, 'l2_leaf_reg': 2.1585183896107467, 'random_strength': 0.007828742607430383, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6137033072113567}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:52,577] Trial 25 finished with value: 0.41930673060139834 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05829916383468929, 'depth': 5, 'l2_leaf_reg': 3.451669656729292, 'random_strength': 0.33321508149976586, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8155398920037588}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:05:55,724] Trial 26 finished with value: 0.44032209307037623 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1580959934406388, 'depth': 4, 'l2_leaf_reg': 1.311877475887007, 'random_strength': 0.21300963189760164, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:06:00,674] Trial 27 finished with value: 0.4316747013724764 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09985657721719118, 'depth': 5, 'l2_leaf_reg': 2.1125107162657346, 'random_strength': 0.5580958091533104, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9540948842021966}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:06:07,499] Trial 28 finished with value: 0.4438457699582603 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1957239173414031, 'depth': 6, 'l2_leaf_reg': 3.183290362192217, 'random_strength': 0.39766675666751683, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8918726922639373}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:06:12,572] Trial 29 finished with value: 0.4007818691904268 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.059466403331839356, 'depth': 4, 'l2_leaf_reg': 1.781053092343938, 'random_strength': 0.1408851011800677, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:06:34,012] Trial 30 finished with value: 0.45535285131324327 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11647694374806004, 'depth': 8, 'l2_leaf_reg': 1.1570132074442094, 'random_strength': 0.20492172738126832, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.966114685821196}. Best is trial 11 with value: 0.46889935943634864.
[I 2026-04-09 14:06:53,496] Trial 31 finished with value: 0.47556911411613556 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1658975179866956, 'depth': 8, 'l2_leaf_reg': 1.5681597877346551, 'random_strength': 0.07105402779643503, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7385445379504939}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:07:13,168] Trial 32 finished with value: 0.4528265690777536 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16394459719828589, 'depth': 8, 'l2_leaf_reg': 2.4003295554743613, 'random_strength': 0.09714278731761508, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7361733417724051}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:07:24,488] Trial 33 finished with value: 0.4449132139709251 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13382132713454645, 'depth': 7, 'l2_leaf_reg': 1.6649844243637826, 'random_strength': 0.16003059483817922, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6623054403083354}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:07:47,944] Trial 34 finished with value: 0.4402994956068319 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0922374121701823, 'depth': 8, 'l2_leaf_reg': 1.5552004777423185, 'random_strength': 0.04738010972471107, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8334852591490913}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:08:02,091] Trial 35 finished with value: 0.4372170630096212 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 7, 'l2_leaf_reg': 1.1690157040746703, 'random_strength': 0.2629417792892584, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7912739908663046}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:08:22,138] Trial 36 finished with value: 0.46867887551372606 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16398304169097708, 'depth': 8, 'l2_leaf_reg': 1.9471161022238734, 'random_strength': 0.11518630638584501, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7248821881604635}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:08:43,243] Trial 37 finished with value: 0.4600314314293308 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1739434669338095, 'depth': 8, 'l2_leaf_reg': 2.029355438164266, 'random_strength': 0.18577028554479053, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6736947839908504}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:08:53,805] Trial 38 finished with value: 0.47194880249847343 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13232951186592376, 'depth': 7, 'l2_leaf_reg': 2.446279334553259, 'random_strength': 0.047966071991268754, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12221043743904225}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:09:07,219] Trial 39 finished with value: 0.44178859381536995 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06992107212211822, 'depth': 7, 'l2_leaf_reg': 5.332225837012162, 'random_strength': 0.1266989799607552, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.4180462534866333}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:09:28,901] Trial 40 finished with value: 0.42626581068193015 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08699117658544306, 'depth': 8, 'l2_leaf_reg': 2.45030742242394, 'random_strength': 0.552147364907, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4532051511681003}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:09:40,154] Trial 41 finished with value: 0.4357787596967343 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1426901332151118, 'depth': 7, 'l2_leaf_reg': 1.6549177845663, 'random_strength': 0.03879561138101794, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.2907563020932256}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:09:59,523] Trial 42 finished with value: 0.42952067503072716 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17391473747233574, 'depth': 8, 'l2_leaf_reg': 1.8398418058520185, 'random_strength': 0.05377075136251255, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.848341272915878}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:10:10,968] Trial 43 finished with value: 0.45702592933272057 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19758171140955022, 'depth': 7, 'l2_leaf_reg': 3.5742288422822925, 'random_strength': 0.10101839216179453, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.015511881399920935}. Best is trial 31 with value: 0.47556911411613556.
[I 2026-04-09 14:10:18,096] Trial 44 finished with value: 0.43366620911331755 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12150696030309363, 'depth': 6, 'l2_leaf_reg': 2.4271767433433786, 'random_strength': 0.03581243278834375, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.9134481426253878}. Best is trial 31 with value: 0.47556911411613556.

                                        feature  importance
567                              stat__umap_097    0.085871
495                              stat__umap_025    0.081414
557                              stat__umap_087    0.065786
262   eye__fix_duration_AOI_aggregated_Neg_skew    0.049751
424        eye__corm_euclidean_length_2_rho_250    0.038754
389    eye__rec_metric_euclidean_length_1_rho_5    0.038564
278   eye__fix_duration_AOI_aggregated_Pos_mean    0.037219
297                        eye__fuzzy_m_2_r_800    0.036751
536                              stat__umap_066    0.036675
551                              stat__umap_081    0.034349
20                 eye__sac_angle_to_x_kurtosis    0.031848
22                   eye__sac_angle_between_min    0.031649
356        eye__lyapunov_exponent_m_3_tau_2_T_1    0.030783
34       eye__sac_length_AOI_aggregated_Neg_sum    0.029544
275  eye__fix_duration_AOI_aggregated_Pos_first    0.029459
53       eye__sac_length_AOI_aggregated_Pos_min    0.028806
38       eye__sac_speed_AOI_aggregated_Neg_mean    0.026642
527                              stat__umap_057    0.025906
10                          eye__sac_speed_mean    0.024131
181      eye__fix_duration_AOI_FD_Neg1_kurtosis    0.024066
521                              stat__umap_051    0.021981
60        eye__sac_speed_AOI_aggregated_Pos_min    0.021270
62       eye__sac_speed_AOI_aggregated_Pos_mean    0.018689
185         eye__fix_duration_AOI_FD_None_first    0.018575
0                           eye__sac_length_min    0.016482
544                              stat__umap_074    0.015649
263    eye__fix_duration_AOI_aggregated_Neg_sum    0.012620
333               eye__sample_entropy_m=2_r=100    0.012374
176           eye__fix_duration_AOI_FD_Neg1_min    0.011471
192          eye__fix_duration_AOI_FD_None_skew    0.011368

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.42535
              precision    recall  f1-score   support

           0       0.65      0.88      0.75       307
           1       0.22      0.06      0.10       154

    accuracy                           0.61       461
   macro avg       0.44      0.47      0.43       461
weighted avg       0.51      0.61      0.53       461

Confusion matrix:
 [[271  36]
 [144  10]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\feature_importances_eye_text2text\exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
557                               stat__umap_087    9.697170
263     eye__fix_duration_AOI_aggregated_Neg_sum    9.285600
60         eye__sac_speed_AOI_aggregated_Pos_min    8.376088
561                               stat__umap_091    6.173115
474                               stat__umap_004    5.582361
545                               stat__umap_075    4.556085
551                               stat__umap_081    4.178411
4                            eye__sac_length_std    4.059335
274  eye__fix_duration_AOI_aggregated_None_count    3.637808
275   eye__fix_duration_AOI_aggregated_Pos_first    3.549397
283     eye__fix_duration_AOI_aggregated_Pos_sum    3.446110
503                               stat__umap_033    3.117139
477                               stat__umap_007    3.069199
264   eye__fix_duration_AOI_aggregated_Neg_count    3.059876
47     eye__sac_length_AOI_aggregated_None_count    3.034401
160                        eye__reg_speed_median    3.003318
277     eye__fix_duration_AOI_aggregated_Pos_max    2.904326
480                               stat__umap_010    2.813398
270    eye__fix_duration_AOI_aggregated_None_std    2.718942
368                   eye__fractal_dim_m_3_tau_2    2.358442
358         eye__lyapunov_exponent_m_3_tau_2_T_4    1.908301
313             eye__gridded_entropy_grid_size_5    1.614593
10                           eye__sac_speed_mean    1.588264
518                               stat__umap_048    1.582453
548                               stat__umap_078    1.500815
387                eye__corr_dim_m_4_tau_2_r_200    1.085926
339                eye__sample_entropy_m=3_r=200    1.046600
296                         eye__fuzzy_m_2_r_400    0.537464
355         eye__lyapunov_exponent_m_3_tau_1_T_4    0.515062
569                               stat__umap_099    0.000000

[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

[I 2026-04-09 14:12:39,316] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 14:12:53,183] Trial 0 finished with value: 0.584282967333483 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.584282967333483.
[I 2026-04-09 14:13:03,837] Trial 1 finished with value: 0.5820102147214415 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.584282967333483.
[I 2026-04-09 14:13:22,059] Trial 2 finished with value: 0.5813150660835831 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.584282967333483.
[I 2026-04-09 14:13:32,507] Trial 3 finished with value: 0.5850953902099365 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:13:43,681] Trial 4 finished with value: 0.5834711892391442 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:13:59,372] Trial 5 finished with value: 0.580608462220081 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:14:06,745] Trial 6 finished with value: 0.5790143299692682 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:14:26,213] Trial 7 finished with value: 0.573457586673174 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:14:35,925] Trial 8 finished with value: 0.5774262119653422 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:15:02,892] Trial 9 finished with value: 0.5838776023551946 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 3 with value: 0.5850953902099365.
[I 2026-04-09 14:15:15,979] Trial 10 finished with value: 0.5893735652115306 and parameters: {'learning_rate': 0.08757688804274504, 'max_depth': 3, 'min_child_weight': 4.926890130404868, 'subsample': 0.8636522230468259, 'colsample_bytree': 0.8646722768462439, 'gamma': 1.411720649791067, 'reg_alpha': 9.265570153067632, 'reg_lambda': 8.122224546810095}. Best is trial 10 with value: 0.5893735652115306.
[I 2026-04-09 14:15:27,384] Trial 11 finished with value: 0.5917383553082947 and parameters: {'learning_rate': 0.0862754992306428, 'max_depth': 3, 'min_child_weight': 4.928424312424371, 'subsample': 0.8622852909563201, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.2957804292612796, 'reg_alpha': 9.52866280527941, 'reg_lambda': 5.975817202898658}. Best is trial 11 with value: 0.5917383553082947.
[I 2026-04-09 14:15:38,639] Trial 12 finished with value: 0.5967358989783071 and parameters: {'learning_rate': 0.07313057902644354, 'max_depth': 3, 'min_child_weight': 5.2632762903781405, 'subsample': 0.8533111603054561, 'colsample_bytree': 0.845235942520865, 'gamma': 1.4498559141176184, 'reg_alpha': 9.356833111719883, 'reg_lambda': 8.615067167390345}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:15:50,312] Trial 13 finished with value: 0.5896691598503994 and parameters: {'learning_rate': 0.06492294965644875, 'max_depth': 3, 'min_child_weight': 2.145123124916511, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.8176955515976587, 'gamma': 1.4030051519904494, 'reg_alpha': 8.457871731466039, 'reg_lambda': 9.723756468311608}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:15:57,421] Trial 14 finished with value: 0.590479599410007 and parameters: {'learning_rate': 0.12900808294784968, 'max_depth': 4, 'min_child_weight': 5.972219673487665, 'subsample': 0.8250091618240228, 'colsample_bytree': 0.8881699126650688, 'gamma': 1.4705148990600059, 'reg_alpha': 1.4388846773732515, 'reg_lambda': 1.186069177689351}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:16:07,311] Trial 15 finished with value: 0.5886104209054096 and parameters: {'learning_rate': 0.06483410659075636, 'max_depth': 3, 'min_child_weight': 2.4370747834999373, 'subsample': 0.8375460781488447, 'colsample_bytree': 0.8279431186491103, 'gamma': 1.2513887824418548, 'reg_alpha': 0.0003362014187651234, 'reg_lambda': 0.00016599250040776937}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:16:16,784] Trial 16 finished with value: 0.5882319649521582 and parameters: {'learning_rate': 0.12345957554158152, 'max_depth': 4, 'min_child_weight': 6.098806807282297, 'subsample': 0.9027095858716521, 'colsample_bytree': 0.8968973468136499, 'gamma': 0.7552852538767579, 'reg_alpha': 0.0043466878579049295, 'reg_lambda': 0.21568760088362365}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:16:29,099] Trial 17 finished with value: 0.5901838501391847 and parameters: {'learning_rate': 0.04339805738694319, 'max_depth': 3, 'min_child_weight': 4.2538784311888875, 'subsample': 0.9345993170135337, 'colsample_bytree': 0.8334694686086871, 'gamma': 1.6373335275931558, 'reg_alpha': 3.4450630323844456, 'reg_lambda': 2.5310996823984957}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:16:40,255] Trial 18 finished with value: 0.5873368491403979 and parameters: {'learning_rate': 0.0733657667303629, 'max_depth': 4, 'min_child_weight': 2.825565863170994, 'subsample': 0.8192152563685501, 'colsample_bytree': 0.7885486349733412, 'gamma': 0.9085738670364132, 'reg_alpha': 0.7028854350792807, 'reg_lambda': 0.011397783591272139}. Best is trial 12 with value: 0.5967358989783071.
[I 2026-04-09 14:16:47,045] Trial 19 finished with value: 0.5973022085376115 and parameters: {'learning_rate': 0.09201472759738434, 'max_depth': 3, 'min_child_weight': 7.06196742492347, 'subsample': 0.8719662641736328, 'colsample_bytree': 0.9942318571111104, 'gamma': 1.206463866769301, 'reg_alpha': 7.755904810928424, 'reg_lambda': 0.345480884752595}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:16:54,004] Trial 20 finished with value: 0.58464357302004 and parameters: {'learning_rate': 0.11001753636744815, 'max_depth': 4, 'min_child_weight': 7.257136967698049, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.9916083231045422, 'gamma': 1.6310076046701614, 'reg_alpha': 0.7706873238040423, 'reg_lambda': 0.44889641021011334}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:01,772] Trial 21 finished with value: 0.5878445685033467 and parameters: {'learning_rate': 0.0919802073409407, 'max_depth': 3, 'min_child_weight': 6.795706004347252, 'subsample': 0.8756408394012846, 'colsample_bytree': 0.9146940831822119, 'gamma': 1.2174838489163413, 'reg_alpha': 9.548011800828698, 'reg_lambda': 2.945611347977827}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:14,021] Trial 22 finished with value: 0.5830426213012041 and parameters: {'learning_rate': 0.05353697968993597, 'max_depth': 3, 'min_child_weight': 1.0411844002676933, 'subsample': 0.890307663228039, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.2528393540068623, 'reg_alpha': 3.250704278867989, 'reg_lambda': 9.834262598159954}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:22,368] Trial 23 finished with value: 0.5845191212520419 and parameters: {'learning_rate': 0.14388569165780934, 'max_depth': 4, 'min_child_weight': 4.91940795076332, 'subsample': 0.8474103107219574, 'colsample_bytree': 0.8524789205247496, 'gamma': 0.5586849888896056, 'reg_alpha': 3.7597240145914874, 'reg_lambda': 1.5181283159310215}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:32,302] Trial 24 finished with value: 0.5769009700595686 and parameters: {'learning_rate': 0.07220914023184906, 'max_depth': 3, 'min_child_weight': 4.224192942268756, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.9722543606208806, 'gamma': 1.502102200421473, 'reg_alpha': 0.683231416154697, 'reg_lambda': 0.20910237888236807}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:40,505] Trial 25 finished with value: 0.5775845923645297 and parameters: {'learning_rate': 0.09962251742782256, 'max_depth': 4, 'min_child_weight': 7.569105616754718, 'subsample': 0.9277354873911228, 'colsample_bytree': 0.801768517628047, 'gamma': 1.0503542849447276, 'reg_alpha': 0.07618130827241452, 'reg_lambda': 0.015819192698718246}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:17:52,923] Trial 26 finished with value: 0.5896450622767416 and parameters: {'learning_rate': 0.05625265643266363, 'max_depth': 3, 'min_child_weight': 5.3291296842921705, 'subsample': 0.8765607806353347, 'colsample_bytree': 0.9096888767824233, 'gamma': 1.268498096285596, 'reg_alpha': 0.00010170183971949589, 'reg_lambda': 4.3894225804525036}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:00,077] Trial 27 finished with value: 0.5763298775481065 and parameters: {'learning_rate': 0.197201818863264, 'max_depth': 8, 'min_child_weight': 3.447178739097493, 'subsample': 0.8471301842639481, 'colsample_bytree': 0.8674287427459931, 'gamma': 1.730970631774125, 'reg_alpha': 4.855290179085893, 'reg_lambda': 1.142505603866674}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:10,401] Trial 28 finished with value: 0.5843243890411911 and parameters: {'learning_rate': 0.08342488697243093, 'max_depth': 5, 'min_child_weight': 3.7985560082995815, 'subsample': 0.8040252666053532, 'colsample_bytree': 0.9604506361987702, 'gamma': 1.9866693832639757, 'reg_alpha': 1.5040390889259683, 'reg_lambda': 4.654601559870334}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:18,057] Trial 29 finished with value: 0.5849662462153354 and parameters: {'learning_rate': 0.14475876742206714, 'max_depth': 4, 'min_child_weight': 7.67805657476944, 'subsample': 0.7233675973388282, 'colsample_bytree': 0.8391692898584817, 'gamma': 0.9087435656785283, 'reg_alpha': 0.006932672920588903, 'reg_lambda': 1.9041798869157738}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:28,547] Trial 30 finished with value: 0.5727138065794859 and parameters: {'learning_rate': 0.10577007710886371, 'max_depth': 7, 'min_child_weight': 5.383066038065926, 'subsample': 0.7544898811997702, 'colsample_bytree': 0.7818986753134338, 'gamma': 0.6078691954282296, 'reg_alpha': 0.0021076064801747027, 'reg_lambda': 0.29005401983550877}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:36,243] Trial 31 finished with value: 0.5889612163281976 and parameters: {'learning_rate': 0.13340591538587862, 'max_depth': 4, 'min_child_weight': 6.251933894680165, 'subsample': 0.8297417135846714, 'colsample_bytree': 0.8853843306986299, 'gamma': 1.4862586538233828, 'reg_alpha': 1.6632324987457183, 'reg_lambda': 1.0107555713694423}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:49,050] Trial 32 finished with value: 0.5875126868724794 and parameters: {'learning_rate': 0.04457759425008305, 'max_depth': 3, 'min_child_weight': 9.9711224388853, 'subsample': 0.8608277950676178, 'colsample_bytree': 0.8551983901822886, 'gamma': 1.3423316939551382, 'reg_alpha': 5.815828252455305, 'reg_lambda': 3.963332325950383}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:18:59,283] Trial 33 finished with value: 0.5794450060422166 and parameters: {'learning_rate': 0.07403282165230961, 'max_depth': 4, 'min_child_weight': 6.529619931439437, 'subsample': 0.830306582396913, 'colsample_bytree': 0.810972679041189, 'gamma': 1.5273201396562697, 'reg_alpha': 2.1337679602374027, 'reg_lambda': 0.9228161215594628}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:19:08,877] Trial 34 finished with value: 0.5908093395916683 and parameters: {'learning_rate': 0.0942561902966885, 'max_depth': 3, 'min_child_weight': 3.8339835721781155, 'subsample': 0.8845255004950713, 'colsample_bytree': 0.921303798809577, 'gamma': 1.1738123335637574, 'reg_alpha': 9.847139094802964, 'reg_lambda': 1.7655429317422575}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:19:17,969] Trial 35 finished with value: 0.5913390021126498 and parameters: {'learning_rate': 0.08798501737179618, 'max_depth': 3, 'min_child_weight': 2.8409657148189646, 'subsample': 0.8839628977838501, 'colsample_bytree': 0.9903276165956001, 'gamma': 1.1448528986960955, 'reg_alpha': 5.288746734982323, 'reg_lambda': 4.596797231909137}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:19:29,035] Trial 36 finished with value: 0.5838144635175265 and parameters: {'learning_rate': 0.060451565953422756, 'max_depth': 3, 'min_child_weight': 2.66950466468764, 'subsample': 0.9251399214406782, 'colsample_bytree': 0.9965813136893801, 'gamma': 0.8988147361604725, 'reg_alpha': 4.083603469544598, 'reg_lambda': 0.03351359500008778}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:19:38,608] Trial 37 finished with value: 0.5866146103790968 and parameters: {'learning_rate': 0.08017329411969384, 'max_depth': 3, 'min_child_weight': 2.208763976531367, 'subsample': 0.9065182404467309, 'colsample_bytree': 0.9556594771852862, 'gamma': 0.72229109412551, 'reg_alpha': 0.35935365171724193, 'reg_lambda': 5.093568757413489}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:19:57,806] Trial 38 finished with value: 0.5800549321632797 and parameters: {'learning_rate': 0.035676369811634, 'max_depth': 5, 'min_child_weight': 2.9699094267673622, 'subsample': 0.8661885108975137, 'colsample_bytree': 0.9775324107892063, 'gamma': 0.3723858029621918, 'reg_alpha': 1.0701928566121923, 'reg_lambda': 0.10174684050630985}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:20:08,481] Trial 39 finished with value: 0.5927183067381966 and parameters: {'learning_rate': 0.06897367138048562, 'max_depth': 3, 'min_child_weight': 4.738616238470856, 'subsample': 0.9453929545131516, 'colsample_bytree': 0.9322629043983561, 'gamma': 0.995036237175219, 'reg_alpha': 0.420183138793443, 'reg_lambda': 0.4280917457852313}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:20:23,100] Trial 40 finished with value: 0.5955553738477225 and parameters: {'learning_rate': 0.04979981014150503, 'max_depth': 5, 'min_child_weight': 4.861626977542478, 'subsample': 0.9650521384317441, 'colsample_bytree': 0.9278617805024505, 'gamma': 1.0063235524468552, 'reg_alpha': 0.05713673641935538, 'reg_lambda': 0.5301198179867876}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:20:39,828] Trial 41 finished with value: 0.5824949975037106 and parameters: {'learning_rate': 0.04821280131767595, 'max_depth': 7, 'min_child_weight': 4.9481954698287245, 'subsample': 0.9602639650718225, 'colsample_bytree': 0.9321802857254173, 'gamma': 1.0019464070043305, 'reg_alpha': 0.06302099228453896, 'reg_lambda': 0.04972866489649956}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:20:50,959] Trial 42 finished with value: 0.5894276128571331 and parameters: {'learning_rate': 0.06710806016728046, 'max_depth': 5, 'min_child_weight': 4.58949898448927, 'subsample': 0.9946577474257253, 'colsample_bytree': 0.9558255871046485, 'gamma': 1.3542714368294448, 'reg_alpha': 0.01146037507512434, 'reg_lambda': 0.4321954086463454}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:21:04,652] Trial 43 finished with value: 0.591804302312902 and parameters: {'learning_rate': 0.05043448701515728, 'max_depth': 6, 'min_child_weight': 5.585765494013126, 'subsample': 0.9481153206470624, 'colsample_bytree': 0.8758904900868666, 'gamma': 1.0966313154244713, 'reg_alpha': 0.14668834701526617, 'reg_lambda': 0.15134362987973926}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:21:19,621] Trial 44 finished with value: 0.5855907070220409 and parameters: {'learning_rate': 0.03876387964136756, 'max_depth': 6, 'min_child_weight': 8.31537541165046, 'subsample': 0.9505182281480581, 'colsample_bytree': 0.9000374498254549, 'gamma': 1.0666047751649732, 'reg_alpha': 0.05341355534327363, 'reg_lambda': 0.13796827564312775}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:21:35,134] Trial 45 finished with value: 0.5938251418019077 and parameters: {'learning_rate': 0.048640703037715186, 'max_depth': 6, 'min_child_weight': 5.559723896484098, 'subsample': 0.972474792543747, 'colsample_bytree': 0.9431111381967993, 'gamma': 0.8390231640579819, 'reg_alpha': 0.15718501981672822, 'reg_lambda': 0.5780609000736447}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:22:00,729] Trial 46 finished with value: 0.5869370826927827 and parameters: {'learning_rate': 0.026618052617827792, 'max_depth': 7, 'min_child_weight': 4.031134412392157, 'subsample': 0.9773368384957757, 'colsample_bytree': 0.9415465772475826, 'gamma': 0.8663399105189328, 'reg_alpha': 0.1459593692304007, 'reg_lambda': 0.5028758395804241}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:22:14,240] Trial 47 finished with value: 0.576792037750415 and parameters: {'learning_rate': 0.058315135880701495, 'max_depth': 7, 'min_child_weight': 3.3839384371276893, 'subsample': 0.9757933847874055, 'colsample_bytree': 0.9277673333833532, 'gamma': 0.758268832699605, 'reg_alpha': 0.03175965188858132, 'reg_lambda': 0.7568351739350487}. Best is trial 19 with value: 0.5973022085376115.
[I 2026-04-09 14:22:31,782] Trial 48 finished with value: 0.5778655758094888 and parameters: {'learning_rate': 0.03002623479577835, 'max_depth': 6, 'min_child_weight': 6.8863953400872955, 'subsample': 0.9642498377979896, 'colsample_bytree': 0.9488847519947207, 'gamma': 0.9531496677999135, 'reg_alpha': 0.20361221196913296, 'reg_lambda': 0.004371197626165927}. Best is trial 19 with value: 0.5973022085376115.

[I 2026-04-09 14:36:34,438] A new study created in memory with name: multiclass_catboost

[I 2026-04-09 14:36:34,435] Trial 99 finished with value: 0.5886424762145777 and parameters: {'learning_rate': 0.03204815106748051, 'max_depth': 6, 'min_child_weight': 3.97587341575121, 'subsample': 0.9207534782654766, 'colsample_bytree': 0.9917430361222195, 'gamma': 0.3185267968171856, 'reg_alpha': 0.12089839313654059, 'reg_lambda': 1.566537431146833}. Best is trial 73 with value: 0.5984927430859246.

Best model (xgb) CV score: 0.59849
Best params: {'learning_rate': 0.05713733568078149, 'max_depth': 5, 'min_child_weight': 5.180316995043173, 'subsample': 0.9693655650822954, 'colsample_bytree': 0.9634702514910307, 'gamma': 0.8081175660075194, 'reg_alpha': 0.057285837917596075, 'reg_lambda': 0.6809846892239279}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-09 14:36:54,935] Trial 0 finished with value: 0.5642992649893797 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5642992649893797.
[I 2026-04-09 14:37:33,749] Trial 1 finished with value: 0.588605675712339 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:38:02,286] Trial 2 finished with value: 0.5814128927098737 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:38:58,022] Trial 3 finished with value: 0.5846343239178987 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:40:21,765] Trial 4 finished with value: 0.5619009058256292 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:42:34,206] Trial 5 finished with value: 0.5801532006922673 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:43:30,003] Trial 6 finished with value: 0.577685542461338 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:45:09,062] Trial 7 finished with value: 0.5766627351777631 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:48:42,317] Trial 8 finished with value: 0.570677141650228 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.588605675712339.
[I 2026-04-09 14:49:22,479] Trial 9 finished with value: 0.5902337451964669 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:49:34,212] Trial 10 finished with value: 0.5807909139865894 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15550029108275915, 'depth': 5, 'l2_leaf_reg': 1.2809979042149076, 'random_strength': 0.9947887102560302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9526058892396143}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:49:55,636] Trial 11 finished with value: 0.589016234209436 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020555942730797597, 'depth': 4, 'l2_leaf_reg': 2.782896042508208, 'random_strength': 0.9499939533376446, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.610132565398292}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:50:12,608] Trial 12 finished with value: 0.5898232032701031 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03703255942764144, 'depth': 5, 'l2_leaf_reg': 2.5246809349924084, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.625699328116167}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:50:44,855] Trial 13 finished with value: 0.5831056224157257 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03640226145578456, 'depth': 6, 'l2_leaf_reg': 1.0427054096823423, 'random_strength': 0.8312664814007409, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.603622633353522}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:50:56,772] Trial 14 finished with value: 0.5856050571307707 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12255376550219486, 'depth': 5, 'l2_leaf_reg': 2.257313132718344, 'random_strength': 0.7979387716527236, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8791010705732631}. Best is trial 9 with value: 0.5902337451964669.
[I 2026-04-09 14:51:11,511] Trial 15 finished with value: 0.5984139660061565 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05807390906332477, 'depth': 5, 'l2_leaf_reg': 3.369740739399583, 'random_strength': 0.8928037541580407, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6645387228783595}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:52:05,860] Trial 16 finished with value: 0.5918122610911714 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05219399788945581, 'depth': 7, 'l2_leaf_reg': 3.7344029023245366, 'random_strength': 0.5657469824738883, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6881401497390961}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:52:20,186] Trial 17 finished with value: 0.5961645828480141 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0593808534112181, 'depth': 5, 'l2_leaf_reg': 4.133163714673548, 'random_strength': 0.5976479090253086, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8209911986048593}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:52:34,603] Trial 18 finished with value: 0.5882745204039154 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06031030447267993, 'depth': 5, 'l2_leaf_reg': 6.133652903374695, 'random_strength': 0.4438470223237908, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8523249955395609}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:52:48,211] Trial 19 finished with value: 0.5814471143624043 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11141774005593937, 'depth': 5, 'l2_leaf_reg': 5.645389285076141, 'random_strength': 0.6845307236446835, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8303314759163367}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:53:24,088] Trial 20 finished with value: 0.5879452037253535 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028056450040323623, 'depth': 6, 'l2_leaf_reg': 3.2354767911092965, 'random_strength': 0.5511833689046378, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9201367309412973}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:54:12,606] Trial 21 finished with value: 0.5886594650276842 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05519973989478201, 'depth': 7, 'l2_leaf_reg': 3.6816604694096466, 'random_strength': 0.5813683555379292, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6878647563698672}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:54:27,796] Trial 22 finished with value: 0.585313678535388 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.050534502920758145, 'depth': 5, 'l2_leaf_reg': 5.044626044284127, 'random_strength': 0.3762726594652155, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7778548319352842}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:54:53,301] Trial 23 finished with value: 0.5902161715405815 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0632880236067383, 'depth': 6, 'l2_leaf_reg': 3.4065759199247183, 'random_strength': 0.5395478323018795, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.730294783083873}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:55:04,161] Trial 24 finished with value: 0.5864434672750158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03897594564084308, 'depth': 4, 'l2_leaf_reg': 7.369175314835457, 'random_strength': 0.722098849518875, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7976966680122867}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:55:38,282] Trial 25 finished with value: 0.5921772451033717 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030539716027891847, 'depth': 6, 'l2_leaf_reg': 3.984698004687111, 'random_strength': 0.8749884787609519, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9986863284042589}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:56:13,452] Trial 26 finished with value: 0.5966057539622948 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.030273506550586627, 'depth': 6, 'l2_leaf_reg': 2.071285547476672, 'random_strength': 0.8770528095614132, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:56:34,598] Trial 27 finished with value: 0.5912467815906302 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.032268980599861455, 'depth': 5, 'l2_leaf_reg': 1.8276965838588288, 'random_strength': 0.9184596551244129, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.30094396714113597}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:56:55,299] Trial 28 finished with value: 0.590523432464433 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.024923028921800813, 'depth': 5, 'l2_leaf_reg': 2.79931659341182, 'random_strength': 0.768274502589992, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.22090791623893452}. Best is trial 15 with value: 0.5984139660061565.
[I 2026-04-09 14:57:06,667] Trial 29 finished with value: 0.6056296893542125 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06279783862488059, 'depth': 4, 'l2_leaf_reg': 2.1437886390860443, 'random_strength': 0.8710313074976282, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.3784693681010873}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:57:20,900] Trial 30 finished with value: 0.5962526812687562 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06857048361615115, 'depth': 4, 'l2_leaf_reg': 1.5891395834224804, 'random_strength': 0.9026794621928784, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.1542365856120274}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:57:35,196] Trial 31 finished with value: 0.5978094840441888 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09286127545943783, 'depth': 4, 'l2_leaf_reg': 2.0385680754875817, 'random_strength': 0.884597779566383, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.259351445089207}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:57:48,839] Trial 32 finished with value: 0.5934771286374803 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09940607974088812, 'depth': 4, 'l2_leaf_reg': 2.094916127545344, 'random_strength': 0.8169383637243167, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.554522876838992}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:57:58,378] Trial 33 finished with value: 0.593364189248906 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09439800988760545, 'depth': 4, 'l2_leaf_reg': 1.3972116004115853, 'random_strength': 0.9500163346651065, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.9194913189285436}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:58:28,674] Trial 34 finished with value: 0.5920046386607518 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.042387248040989034, 'depth': 4, 'l2_leaf_reg': 1.9304401060241636, 'random_strength': 0.7290694956282759, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 2.0261962570107213}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:58:37,443] Trial 35 finished with value: 0.5824528973271886 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1254446218836168, 'depth': 4, 'l2_leaf_reg': 2.425185788385624, 'random_strength': 0.8969437363464127, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.013688539194893323}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:58:49,091] Trial 36 finished with value: 0.5953356220770979 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08665403446509502, 'depth': 4, 'l2_leaf_reg': 1.6956492268800945, 'random_strength': 0.8535043502456193, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.7320967631777365}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 14:59:04,788] Trial 37 finished with value: 0.5829007001127701 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06935325932977954, 'depth': 4, 'l2_leaf_reg': 2.9621486872960587, 'random_strength': 0.7846741834649192, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 2.0394655695542703}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:00:45,588] Trial 38 finished with value: 0.5730582511955867 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04457596407926739, 'depth': 6, 'l2_leaf_reg': 1.3179582800613847, 'random_strength': 0.6692398809038578, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.8637053158276324}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:00:54,279] Trial 39 finished with value: 0.588470372068033 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1416256380553241, 'depth': 4, 'l2_leaf_reg': 2.185746631959255, 'random_strength': 0.9444687191537074, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.7417859843737507}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:02:07,501] Trial 40 finished with value: 0.5855837680719018 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.023900637011643158, 'depth': 5, 'l2_leaf_reg': 1.4983959298327665, 'random_strength': 0.2551267960781407, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.9255490431805433}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:02:21,496] Trial 41 finished with value: 0.598071715319249 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0687624014197378, 'depth': 4, 'l2_leaf_reg': 1.6649497122642165, 'random_strength': 0.8794322928805073, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.119831429051028}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:02:35,040] Trial 42 finished with value: 0.5962897762919741 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07921303778354105, 'depth': 4, 'l2_leaf_reg': 1.9240872950179218, 'random_strength': 0.8520749854274715, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.2812391859244054}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:02:50,100] Trial 43 finished with value: 0.589696713237257 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0704015457524825, 'depth': 4, 'l2_leaf_reg': 1.1451771856504764, 'random_strength': 0.7422899287260446, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.6190348222293967}. Best is trial 29 with value: 0.6056296893542125.
[I 2026-04-09 15:02:58,632] Trial 44 finished with value: 0.6020107890262959 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1866304651597556, 'depth': 4, 'l2_leaf_reg': 2.487379040615275, 'random_strength': 0.9727321766324001, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.5966218247296773}. Best is trial 29 with value: 0.6056296893542125.

                                               feature  importance
29              eye__sac_length_AOI_aggregated_Neg_min    0.055197
257           eye__fix_duration_AOI_aggregated_Neg_max    0.030492
62              eye__sac_speed_AOI_aggregated_Pos_mean    0.022011
259        eye__fix_duration_AOI_aggregated_Neg_median    0.021590
55             eye__sac_length_AOI_aggregated_Pos_mean    0.019376
53              eye__sac_length_AOI_aggregated_Pos_min    0.019313
36               eye__sac_speed_AOI_aggregated_Neg_min    0.018964
35            eye__sac_length_AOI_aggregated_Neg_count    0.013802
54              eye__sac_length_AOI_aggregated_Pos_max    0.010144
47           eye__sac_length_AOI_aggregated_None_count    0.008893
63            eye__sac_speed_AOI_aggregated_Pos_median    0.008721
263           eye__fix_duration_AOI_aggregated_Neg_sum    0.007779
194                eye__fix_duration_AOI_FD_None_count    0.006911
515                                     stat__umap_045    0.006126
58              eye__sac_length_AOI_aggregated_Pos_sum    0.005690
276           eye__fix_duration_AOI_aggregated_Pos_min    0.005414
174                            eye__fix_duration_count    0.005371
30              eye__sac_length_AOI_aggregated_Neg_max    0.005163
46             eye__sac_length_AOI_aggregated_None_sum    0.004785
60               eye__sac_speed_AOI_aggregated_Pos_min    0.004269
279        eye__fix_duration_AOI_aggregated_Pos_median    0.004134
283           eye__fix_duration_AOI_aggregated_Pos_sum    0.004132
90   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.004071
486                                     stat__umap_016    0.003932
56           eye__sac_length_AOI_aggregated_Pos_median    0.003850
256           eye__fix_duration_AOI_aggregated_Neg_min    0.003841
77   eye__sac_length_from_Neg_to_Target_from_Neg_to...    0.003772
89   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.003693
394                 eye__det_euclidean_length_1_rho_25    0.003690
335                      eye__sample_entropy_m=2_r=400    0.003504

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.64700
              precision    recall  f1-score   support

           0       0.56      0.52      0.54       166
           1       0.57      0.49      0.53       170
           2       0.78      0.98      0.87       125

    accuracy                           0.64       461
   macro avg       0.64      0.67      0.65       461
weighted avg       0.62      0.64      0.63       461

Confusion matrix:
 [[ 87  63  16]
 [ 68  84  18]
 [  1   1 123]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\feature_importances_eye_text2text\exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
29       eye__sac_length_AOI_aggregated_Neg_min    5.948343
30       eye__sac_length_AOI_aggregated_Neg_max    4.530255
264  eye__fix_duration_AOI_aggregated_Neg_count    4.235593
35     eye__sac_length_AOI_aggregated_Neg_count    4.036373
256    eye__fix_duration_AOI_aggregated_Neg_min    3.259116
59     eye__sac_length_AOI_aggregated_Pos_count    3.206799
255  eye__fix_duration_AOI_aggregated_Neg_first    3.107308
46      eye__sac_length_AOI_aggregated_None_sum    2.943411
284  eye__fix_duration_AOI_aggregated_Pos_count    2.644159
31      eye__sac_length_AOI_aggregated_Neg_mean    1.812425
56    eye__sac_length_AOI_aggregated_Pos_median    1.718230
39     eye__sac_speed_AOI_aggregated_Neg_median    1.701907
257    eye__fix_duration_AOI_aggregated_Neg_max    1.525714
278   eye__fix_duration_AOI_aggregated_Pos_mean    1.509805
206           eye__fix_duration_AOI_FD_Pos1_min    1.508120
36        eye__sac_speed_AOI_aggregated_Neg_min    1.453627
34       eye__sac_length_AOI_aggregated_Neg_sum    1.322388
60        eye__sac_speed_AOI_aggregated_Pos_min    1.288577
32    eye__sac_length_AOI_aggregated_Neg_median    1.273311
38       eye__sac_speed_AOI_aggregated_Neg_mean    1.152714
276    eye__fix_duration_AOI_aggregated_Pos_min    1.059192
263    eye__fix_duration_AOI_aggregated_Neg_sum    1.006552
53       eye__sac_length_AOI_aggregated_Pos_min    1.004588
54       eye__sac_length_AOI_aggregated_Pos_max    0.961980
214         eye__fix_duration_AOI_FD_Pos1_count    0.860948
47    eye__sac_length_AOI_aggregated_None_count    0.835309
62       eye__sac_speed_AOI_aggregated_Pos_mean    0.812956
184         eye__fix_duration_AOI_FD_Neg1_count    0.798173
37        eye__sac_speed_AOI_aggregated_Neg_max    0.738457
207           eye__fix_duration_AOI_FD_Pos1_max    0.714148

[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

[I 2026-04-09 15:05:47,013] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 15:05:53,571] Trial 0 finished with value: 0.44958353456584466 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.44958353456584466.
[I 2026-04-09 15:06:01,402] Trial 1 finished with value: 0.481283912550463 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.481283912550463.
[I 2026-04-09 15:06:08,742] Trial 2 finished with value: 0.46496818065118084 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 1 with value: 0.481283912550463.
[I 2026-04-09 15:06:15,140] Trial 3 finished with value: 0.4621987625755025 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 1 with value: 0.481283912550463.
[I 2026-04-09 15:06:21,965] Trial 4 finished with value: 0.47569109811669863 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 1 with value: 0.481283912550463.
[I 2026-04-09 15:06:29,033] Trial 5 finished with value: 0.4638954288571261 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 1 with value: 0.481283912550463.
[I 2026-04-09 15:06:34,736] Trial 6 finished with value: 0.4893193718454541 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:06:42,473] Trial 7 finished with value: 0.45833584293669766 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:06:48,922] Trial 8 finished with value: 0.46792133479158515 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:06:57,493] Trial 9 finished with value: 0.44158551762239884 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:07:03,021] Trial 10 finished with value: 0.4595701468246009 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:07:07,502] Trial 11 finished with value: 0.45501571728220885 and parameters: {'learning_rate': 0.1991845344630195, 'max_depth': 8, 'min_child_weight': 2.0632174240992716, 'subsample': 0.999003097174853, 'colsample_bytree': 0.8552825013098554, 'gamma': 1.9420066754256295, 'reg_alpha': 8.362151729162303, 'reg_lambda': 0.00013386192543122697}. Best is trial 6 with value: 0.4893193718454541.
[I 2026-04-09 15:07:13,428] Trial 12 finished with value: 0.4939755181522328 and parameters: {'learning_rate': 0.1362745396441923, 'max_depth': 8, 'min_child_weight': 2.372469494103088, 'subsample': 0.9327608479770944, 'colsample_bytree': 0.8115347564620432, 'gamma': 1.3820801780564986, 'reg_alpha': 0.005440170097178139, 'reg_lambda': 0.5849924428028535}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:18,625] Trial 13 finished with value: 0.4664801441768532 and parameters: {'learning_rate': 0.1395445738342445, 'max_depth': 4, 'min_child_weight': 2.3527346379720164, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.8072609219884682, 'gamma': 1.482683391887113, 'reg_alpha': 0.00496556400257899, 'reg_lambda': 0.8409895220435655}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:25,702] Trial 14 finished with value: 0.4591441604469107 and parameters: {'learning_rate': 0.08176705251458778, 'max_depth': 7, 'min_child_weight': 5.293870612391065, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8881699126650688, 'gamma': 1.3357616358263678, 'reg_alpha': 0.003951021561695887, 'reg_lambda': 0.49258163286769713}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:31,003] Trial 15 finished with value: 0.48015509197874706 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 4, 'min_child_weight': 2.605443591982054, 'subsample': 0.8393242113391094, 'colsample_bytree': 0.8108543741131289, 'gamma': 1.7115526270782075, 'reg_alpha': 0.019266011237656783, 'reg_lambda': 0.012913316357799428}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:36,758] Trial 16 finished with value: 0.4610728719369943 and parameters: {'learning_rate': 0.15035172001077482, 'max_depth': 7, 'min_child_weight': 6.098806807282297, 'subsample': 0.9118737240157142, 'colsample_bytree': 0.8921254911151859, 'gamma': 1.3498287457412264, 'reg_alpha': 0.00011375014133041703, 'reg_lambda': 0.26355122320964325}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:41,870] Trial 17 finished with value: 0.45992817298934296 and parameters: {'learning_rate': 0.0971355829393903, 'max_depth': 3, 'min_child_weight': 3.8978272320225624, 'subsample': 0.7413090097418402, 'colsample_bytree': 0.8911833935295822, 'gamma': 1.956369767257795, 'reg_alpha': 0.0009976940809307319, 'reg_lambda': 2.262454764612923}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:49,111] Trial 18 finished with value: 0.45249916789059785 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 5, 'min_child_weight': 2.72242568661687, 'subsample': 0.8760497535368478, 'colsample_bytree': 0.7843830386678734, 'gamma': 0.810824578052045, 'reg_alpha': 0.04566692225045115, 'reg_lambda': 9.699586322297742}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:07:55,568] Trial 19 finished with value: 0.4483774939161209 and parameters: {'learning_rate': 0.11196820228941953, 'max_depth': 8, 'min_child_weight': 6.755767154796553, 'subsample': 0.9458938643669037, 'colsample_bytree': 0.829213749065781, 'gamma': 1.633286492050634, 'reg_alpha': 0.0017107182314749943, 'reg_lambda': 1.75144139558839}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:01,837] Trial 20 finished with value: 0.4753122040763437 and parameters: {'learning_rate': 0.14723685073103868, 'max_depth': 7, 'min_child_weight': 1.2778798052910343, 'subsample': 0.8207531213984746, 'colsample_bytree': 0.8329385856673193, 'gamma': 1.212620360204875, 'reg_alpha': 0.009657249161570035, 'reg_lambda': 0.17595027314880748}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:07,254] Trial 21 finished with value: 0.4864695439495934 and parameters: {'learning_rate': 0.17044892169734435, 'max_depth': 8, 'min_child_weight': 1.8691073325470773, 'subsample': 0.9560589851593888, 'colsample_bytree': 0.7077123442346311, 'gamma': 0.4315237439661536, 'reg_alpha': 1.3476423486107838, 'reg_lambda': 0.0001433227397308474}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:13,459] Trial 22 finished with value: 0.4646033382287693 and parameters: {'learning_rate': 0.15955608841625393, 'max_depth': 8, 'min_child_weight': 1.6596025884573775, 'subsample': 0.9368232749706285, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.44025541499721327, 'reg_alpha': 0.7531840515124048, 'reg_lambda': 0.00010275428111230916}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:18,902] Trial 23 finished with value: 0.4622991233222278 and parameters: {'learning_rate': 0.1933285875823261, 'max_depth': 7, 'min_child_weight': 2.362218811461379, 'subsample': 0.8994416402644109, 'colsample_bytree': 0.7177568769788184, 'gamma': 0.8318751950696683, 'reg_alpha': 0.0760399149297615, 'reg_lambda': 0.01681800748930421}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:24,555] Trial 24 finished with value: 0.4639065653542113 and parameters: {'learning_rate': 0.13193430125743874, 'max_depth': 8, 'min_child_weight': 2.8607670606754, 'subsample': 0.9933471127726692, 'colsample_bytree': 0.8704061626970631, 'gamma': 0.5467100660806413, 'reg_alpha': 4.753413378228821, 'reg_lambda': 0.004611419708199076}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:30,779] Trial 25 finished with value: 0.44371631164588643 and parameters: {'learning_rate': 0.1016886921873424, 'max_depth': 5, 'min_child_weight': 2.0897621364476353, 'subsample': 0.7000695502104095, 'colsample_bytree': 0.7660007204464017, 'gamma': 1.5033826381470379, 'reg_alpha': 0.032457164831065755, 'reg_lambda': 0.0331941511621147}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:38,134] Trial 26 finished with value: 0.4663150413468599 and parameters: {'learning_rate': 0.07812161999403253, 'max_depth': 7, 'min_child_weight': 4.632713032668859, 'subsample': 0.9676295497500442, 'colsample_bytree': 0.9197740012817117, 'gamma': 0.9502107485978555, 'reg_alpha': 0.011457469214315797, 'reg_lambda': 0.34650363647031596}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:44,116] Trial 27 finished with value: 0.4687677485863163 and parameters: {'learning_rate': 0.15866934656795595, 'max_depth': 8, 'min_child_weight': 1.245144851379123, 'subsample': 0.9228012605540291, 'colsample_bytree': 0.9755378965373238, 'gamma': 0.7015970841847103, 'reg_alpha': 0.6555477800938578, 'reg_lambda': 0.00035756316269210055}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:49,318] Trial 28 finished with value: 0.44843284953485807 and parameters: {'learning_rate': 0.17337881095611732, 'max_depth': 4, 'min_child_weight': 7.5799147357663745, 'subsample': 0.8150391226653676, 'colsample_bytree': 0.8312202460490259, 'gamma': 0.33087365021310144, 'reg_alpha': 0.0016195524991496932, 'reg_lambda': 1.5025221569075002}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:08:56,019] Trial 29 finished with value: 0.44532981345274913 and parameters: {'learning_rate': 0.06481799315131652, 'max_depth': 6, 'min_child_weight': 3.644796378738195, 'subsample': 0.7532791722752649, 'colsample_bytree': 0.7630521417190215, 'gamma': 1.8152286726915792, 'reg_alpha': 0.0003837347004431255, 'reg_lambda': 0.10030892512926887}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:02,038] Trial 30 finished with value: 0.4724265890667087 and parameters: {'learning_rate': 0.1306279747853857, 'max_depth': 5, 'min_child_weight': 3.402299727010828, 'subsample': 0.8821341007450447, 'colsample_bytree': 0.9083264493985033, 'gamma': 1.2370019069315308, 'reg_alpha': 0.08609985261151698, 'reg_lambda': 3.8719776140021014}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:08,014] Trial 31 finished with value: 0.4727893540329935 and parameters: {'learning_rate': 0.1698977849155973, 'max_depth': 8, 'min_child_weight': 1.800687927442628, 'subsample': 0.9568316596747727, 'colsample_bytree': 0.7021938352476829, 'gamma': 0.14140631788349306, 'reg_alpha': 2.5103905060118192, 'reg_lambda': 0.0003420353102101175}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:13,617] Trial 32 finished with value: 0.4719026551002589 and parameters: {'learning_rate': 0.16559893626701808, 'max_depth': 8, 'min_child_weight': 1.932579329021728, 'subsample': 0.9822968827861577, 'colsample_bytree': 0.7329347976824132, 'gamma': 0.0654938388128133, 'reg_alpha': 2.551762627961334, 'reg_lambda': 0.00039175208295104413}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:19,337] Trial 33 finished with value: 0.45704395267453896 and parameters: {'learning_rate': 0.19612179531881274, 'max_depth': 8, 'min_child_weight': 1.4775752287887707, 'subsample': 0.9408585234639535, 'colsample_bytree': 0.7263275524342191, 'gamma': 0.3465347996408604, 'reg_alpha': 0.9689931248171754, 'reg_lambda': 0.0009419265658214157}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:25,648] Trial 34 finished with value: 0.4757946961328788 and parameters: {'learning_rate': 0.10964030154319276, 'max_depth': 7, 'min_child_weight': 2.2739786229370127, 'subsample': 0.9308875356715824, 'colsample_bytree': 0.7715539963963036, 'gamma': 0.005694447106033281, 'reg_alpha': 9.694699904430951, 'reg_lambda': 0.0001904278528665983}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:33,035] Trial 35 finished with value: 0.4664761083384787 and parameters: {'learning_rate': 0.08918162532939632, 'max_depth': 8, 'min_child_weight': 1.481737850341722, 'subsample': 0.958804457775392, 'colsample_bytree': 0.7515369034823846, 'gamma': 0.22419367632240972, 'reg_alpha': 3.054742086148835, 'reg_lambda': 0.003276613404818146}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:39,175] Trial 36 finished with value: 0.46841037807210273 and parameters: {'learning_rate': 0.04805521975498662, 'max_depth': 7, 'min_child_weight': 9.999978053662037, 'subsample': 0.8905243122042814, 'colsample_bytree': 0.7176685174392942, 'gamma': 0.45846511206195006, 'reg_alpha': 0.31861049355742493, 'reg_lambda': 0.0011716704457219774}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:47,117] Trial 37 finished with value: 0.4530740647683513 and parameters: {'learning_rate': 0.03771107996234771, 'max_depth': 6, 'min_child_weight': 2.944543120715152, 'subsample': 0.8555326202990784, 'colsample_bytree': 0.7923913749304496, 'gamma': 0.24699053253185754, 'reg_alpha': 0.01416793138270592, 'reg_lambda': 0.908771609799562}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:52,588] Trial 38 finished with value: 0.44507220299249495 and parameters: {'learning_rate': 0.1395587980622254, 'max_depth': 5, 'min_child_weight': 1.0280658892170897, 'subsample': 0.9785441762853213, 'colsample_bytree': 0.8096050433362245, 'gamma': 0.978070472752393, 'reg_alpha': 0.15126723466934308, 'reg_lambda': 0.0007227425616484823}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:09:58,640] Trial 39 finished with value: 0.4811956821910339 and parameters: {'learning_rate': 0.12144920890409976, 'max_depth': 7, 'min_child_weight': 1.814495825551955, 'subsample': 0.8113281686337351, 'colsample_bytree': 0.8690813029343932, 'gamma': 1.6197544612015196, 'reg_alpha': 0.420183138793443, 'reg_lambda': 0.05577309336082642}. Best is trial 12 with value: 0.4939755181522328.
[I 2026-04-09 15:10:04,061] Trial 40 finished with value: 0.4964977580560719 and parameters: {'learning_rate': 0.17708577839495104, 'max_depth': 8, 'min_child_weight': 4.190299732473478, 'subsample': 0.7581940414976092, 'colsample_bytree': 0.7364744078599914, 'gamma': 1.7992104198690713, 'reg_alpha': 0.0027501250062720657, 'reg_lambda': 0.002528632208823848}. Best is trial 40 with value: 0.4964977580560719.
[I 2026-04-09 15:10:09,675] Trial 41 finished with value: 0.4647569687178044 and parameters: {'learning_rate': 0.16832263088444105, 'max_depth': 8, 'min_child_weight': 4.30803182367434, 'subsample': 0.7656044517880918, 'colsample_bytree': 0.737892027590279, 'gamma': 1.7802713772449137, 'reg_alpha': 0.0025295924808234065, 'reg_lambda': 0.0023955615227135765}. Best is trial 40 with value: 0.4964977580560719.
[I 2026-04-09 15:10:14,717] Trial 42 finished with value: 0.46987910560925406 and parameters: {'learning_rate': 0.1862756787215696, 'max_depth': 8, 'min_child_weight': 2.4974225582298484, 'subsample': 0.7315505244364541, 'colsample_bytree': 0.720707633726062, 'gamma': 1.8697112893831702, 'reg_alpha': 0.006540708792050514, 'reg_lambda': 0.006954031350229458}. Best is trial 40 with value: 0.4964977580560719.
[I 2026-04-09 15:10:20,025] Trial 43 finished with value: 0.49959937560436846 and parameters: {'learning_rate': 0.14710573733315352, 'max_depth': 8, 'min_child_weight': 5.202826827088681, 'subsample': 0.7113699353927412, 'colsample_bytree': 0.9996533142159789, 'gamma': 1.992109309702552, 'reg_alpha': 0.04914597061650634, 'reg_lambda': 0.0006369313037162391}. Best is trial 43 with value: 0.49959937560436846.
[I 2026-04-09 15:10:29,478] Trial 44 finished with value: 0.44327990008142676 and parameters: {'learning_rate': 0.02188029840119486, 'max_depth': 8, 'min_child_weight': 4.8282857693344745, 'subsample': 0.7062681519881421, 'colsample_bytree': 0.9894320636776458, 'gamma': 1.979215001051725, 'reg_alpha': 0.04757671455834634, 'reg_lambda': 0.00020856939297494477}. Best is trial 43 with value: 0.49959937560436846.
[I 2026-04-09 15:10:35,534] Trial 45 finished with value: 0.46161837452520665 and parameters: {'learning_rate': 0.14222797165534906, 'max_depth': 7, 'min_child_weight': 5.576641401580147, 'subsample': 0.7165879169247931, 'colsample_bytree': 0.953593014679421, 'gamma': 1.725020507227054, 'reg_alpha': 0.0007597198026094003, 'reg_lambda': 0.0006357176841566614}. Best is trial 43 with value: 0.49959937560436846.
[I 2026-04-09 15:10:41,157] Trial 46 finished with value: 0.4448355264242795 and parameters: {'learning_rate': 0.18204486595458172, 'max_depth': 8, 'min_child_weight': 7.71981198228722, 'subsample': 0.7537566762701138, 'colsample_bytree': 0.7515290376756409, 'gamma': 1.9003066603700216, 'reg_alpha': 0.0030809638446785787, 'reg_lambda': 0.000252026451546283}. Best is trial 43 with value: 0.49959937560436846.
[I 2026-04-09 15:10:46,507] Trial 47 finished with value: 0.4634663108763497 and parameters: {'learning_rate': 0.15280931302481954, 'max_depth': 4, 'min_child_weight': 4.0586300200198115, 'subsample': 0.7752894688572773, 'colsample_bytree': 0.9252841637620428, 'gamma': 1.5634544407332487, 'reg_alpha': 0.00806332226565912, 'reg_lambda': 4.068476605360055}. Best is trial 43 with value: 0.49959937560436846.

[I 2026-04-09 15:15:48,696] A new study created in memory with name: binary_catboost

[I 2026-04-09 15:15:48,692] Trial 99 finished with value: 0.48977891599843293 and parameters: {'learning_rate': 0.1351742627549677, 'max_depth': 4, 'min_child_weight': 6.889396924478221, 'subsample': 0.8052748193855621, 'colsample_bytree': 0.9673458625374389, 'gamma': 1.4510601314859515, 'reg_alpha': 0.09924472746905902, 'reg_lambda': 0.003170446188854479}. Best is trial 89 with value: 0.5058402496651486.

Best model (xgb) CV score: 0.50584
Best params: {'learning_rate': 0.12434050521879933, 'max_depth': 4, 'min_child_weight': 7.456538602116196, 'subsample': 0.8166095805856031, 'colsample_bytree': 0.9575762543577029, 'gamma': 1.7525012772731614, 'reg_alpha': 0.18755591511596176, 'reg_lambda': 0.0016335293364954117}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-09 15:15:57,503] Trial 0 finished with value: 0.4902012690653885 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4902012690653885.
[I 2026-04-09 15:16:12,579] Trial 1 finished with value: 0.4906750685490626 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4906750685490626.
[I 2026-04-09 15:16:22,863] Trial 2 finished with value: 0.4915738617255643 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4915738617255643.
[I 2026-04-09 15:16:43,847] Trial 3 finished with value: 0.5134275422913885 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5134275422913885.
[I 2026-04-09 15:17:05,883] Trial 4 finished with value: 0.5182562116627112 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:17:37,809] Trial 5 finished with value: 0.4826139651739154 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:17:57,986] Trial 6 finished with value: 0.48414510654912446 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:18:36,424] Trial 7 finished with value: 0.475185654472472 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:19:28,197] Trial 8 finished with value: 0.4751231799189044 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:19:42,268] Trial 9 finished with value: 0.5070216972926855 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:19:47,719] Trial 10 finished with value: 0.4944492684273099 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.5182562116627112.
[I 2026-04-09 15:20:00,286] Trial 11 finished with value: 0.5246472873409893 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 4.651607675299369, 'random_strength': 0.016584038838684367, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 11 with value: 0.5246472873409893.
[I 2026-04-09 15:20:23,026] Trial 12 finished with value: 0.5233727035873371 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 3.672310184878952, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.870940447219903}. Best is trial 11 with value: 0.5246472873409893.
[I 2026-04-09 15:20:36,527] Trial 13 finished with value: 0.5164318519887214 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12821872834050937, 'depth': 7, 'l2_leaf_reg': 4.148284442416459, 'random_strength': 0.0020777312464156164, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8906367837209281}. Best is trial 11 with value: 0.5246472873409893.
[I 2026-04-09 15:20:44,495] Trial 14 finished with value: 0.48636187077936494 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13517895405905175, 'depth': 6, 'l2_leaf_reg': 2.9430541593810493, 'random_strength': 0.2590914992532189, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8561869311413425}. Best is trial 11 with value: 0.5246472873409893.
[I 2026-04-09 15:21:07,027] Trial 15 finished with value: 0.5354954688186574 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1983058867595879, 'depth': 8, 'l2_leaf_reg': 5.933807715553448, 'random_strength': 0.003318386420095399, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9814769576437812}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:21:21,723] Trial 16 finished with value: 0.5110482066520354 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12129586202247182, 'depth': 7, 'l2_leaf_reg': 6.34283093029632, 'random_strength': 0.4701581643461224, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:21:45,154] Trial 17 finished with value: 0.5333925063771887 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14275466267871886, 'depth': 8, 'l2_leaf_reg': 6.141132079942002, 'random_strength': 0.20033743450365546, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9919359775122162}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:21:50,184] Trial 18 finished with value: 0.5058080300104465 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10148368561184581, 'depth': 5, 'l2_leaf_reg': 7.5497101760096, 'random_strength': 0.17911596661267287, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.998940256994706}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:22:25,949] Trial 19 finished with value: 0.5146610955511755 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.051860059172843136, 'depth': 8, 'l2_leaf_reg': 2.93868220378548, 'random_strength': 0.36808163042855613, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9375954485394866}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:22:53,636] Trial 20 finished with value: 0.5171119317825765 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14724478112125605, 'depth': 8, 'l2_leaf_reg': 19.60965277102468, 'random_strength': 0.1615027486899613, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.941385354825648}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:23:05,325] Trial 21 finished with value: 0.5266883333696333 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15712544502273593, 'depth': 7, 'l2_leaf_reg': 6.227004185978281, 'random_strength': 0.08368532781010633, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8142954177832318}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:23:28,935] Trial 22 finished with value: 0.5141488805150024 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10501464864153166, 'depth': 8, 'l2_leaf_reg': 5.960315502944872, 'random_strength': 0.10894345675444755, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9603241365754367}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:23:42,068] Trial 23 finished with value: 0.5267499652441594 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1537084334075049, 'depth': 7, 'l2_leaf_reg': 9.685683070735568, 'random_strength': 0.2463583390544556, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7994578167239308}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:24:08,516] Trial 24 finished with value: 0.5146271332274727 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12085626606923884, 'depth': 8, 'l2_leaf_reg': 9.609483156107508, 'random_strength': 0.25808781029778516, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7771352405482137}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:24:16,229] Trial 25 finished with value: 0.4989364989800398 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19834341371779646, 'depth': 6, 'l2_leaf_reg': 12.32121720319971, 'random_strength': 0.3780455540079231, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8878361588468973}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:24:35,820] Trial 26 finished with value: 0.49821337628164014 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.036511154136177004, 'depth': 7, 'l2_leaf_reg': 7.917845506468569, 'random_strength': 0.22275495131267412, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:25:01,999] Trial 27 finished with value: 0.529780005936785 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14642748505879027, 'depth': 8, 'l2_leaf_reg': 6.064042100448817, 'random_strength': 0.5580958091533104, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9132852271744875}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:25:38,791] Trial 28 finished with value: 0.5073283776254817 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06008533680278842, 'depth': 8, 'l2_leaf_reg': 5.401018716148513, 'random_strength': 0.6193568288007452, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9694891850262131}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:25:49,295] Trial 29 finished with value: 0.487492840064457 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11105639178536106, 'depth': 5, 'l2_leaf_reg': 3.2150477246607894, 'random_strength': 0.5874440235504843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.682610778645282}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:26:18,024] Trial 30 finished with value: 0.5143648562195591 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0649796064495645, 'depth': 8, 'l2_leaf_reg': 2.6234253118570665, 'random_strength': 0.5365856760216451, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9103107032027494}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:26:43,568] Trial 31 finished with value: 0.5326210859983834 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15000741908941115, 'depth': 8, 'l2_leaf_reg': 8.425375610711043, 'random_strength': 0.4425560927302018, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9656579647678473}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:27:06,806] Trial 32 finished with value: 0.5065317090299728 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13855166097917812, 'depth': 8, 'l2_leaf_reg': 7.175157943627681, 'random_strength': 0.4223534344088412, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9775005190306916}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:27:11,258] Trial 33 finished with value: 0.5072333619136403 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09148173951623338, 'depth': 4, 'l2_leaf_reg': 5.42432975619459, 'random_strength': 0.7032293199779268, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.910664709454628}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:27:39,710] Trial 34 finished with value: 0.5107817032285438 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16364027294554837, 'depth': 8, 'l2_leaf_reg': 12.263428586939105, 'random_strength': 0.5224459992269288, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9640343747238527}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:28:23,557] Trial 35 finished with value: 0.4925151678960325 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 8, 'l2_leaf_reg': 8.371114465691987, 'random_strength': 0.7688323607326528, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9998569887419392}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:28:45,432] Trial 36 finished with value: 0.5244559561445707 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18795883448527784, 'depth': 8, 'l2_leaf_reg': 5.206646549855558, 'random_strength': 0.30121107176278694, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9226322517211356}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:28:59,491] Trial 37 finished with value: 0.5300242399976302 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14176549564384405, 'depth': 7, 'l2_leaf_reg': 2.2897565261691324, 'random_strength': 0.13101918913098345, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9545018985540729}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:29:14,908] Trial 38 finished with value: 0.5171676317466126 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08517224626031777, 'depth': 7, 'l2_leaf_reg': 1.3179582800613847, 'random_strength': 0.12679656615056348, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.12221043743904225}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:29:29,417] Trial 39 finished with value: 0.5219295698684578 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11507723573386033, 'depth': 7, 'l2_leaf_reg': 4.047679322938718, 'random_strength': 0.06527281824432271, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.957304750492535}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:29:37,799] Trial 40 finished with value: 0.5157005645250197 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17466990670202745, 'depth': 6, 'l2_leaf_reg': 2.37492363180728, 'random_strength': 0.19219401685730433, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.4532051511681003}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:30:05,046] Trial 41 finished with value: 0.5183062810226851 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13977132776427084, 'depth': 8, 'l2_leaf_reg': 2.1779073369484228, 'random_strength': 0.32440551888968777, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9750407982528231}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:30:33,282] Trial 42 finished with value: 0.5225681118589114 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15220751854127937, 'depth': 8, 'l2_leaf_reg': 7.101338272632055, 'random_strength': 0.5573709005245499, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9463032924270858}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:31:01,510] Trial 43 finished with value: 0.5167585216427322 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13018529152486347, 'depth': 8, 'l2_leaf_reg': 8.747502756548732, 'random_strength': 0.0512900602900605, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9826188533748212}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:31:13,853] Trial 44 finished with value: 0.5291798256108824 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16558980909420323, 'depth': 7, 'l2_leaf_reg': 4.732395000748978, 'random_strength': 0.14751809354121834, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9043122572328312}. Best is trial 15 with value: 0.5354954688186574.
[I 2026-04-09 15:31:38,626] Trial 45 finished with value: 0.5237577754258148 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17660178410176033, 'depth': 8, 'l2_leaf_reg': 11.407676310570617, 'random_strength': 0.4288645977759793, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9342460282280178}. Best is trial 15 with value: 0.5354954688186574.

                                               feature  importance
32           eye__sac_length_AOI_aggregated_Neg_median    0.109246
183                  eye__fix_duration_AOI_FD_Neg1_sum    0.066074
53              eye__sac_length_AOI_aggregated_Pos_min    0.056388
60               eye__sac_speed_AOI_aggregated_Pos_min    0.048021
176                  eye__fix_duration_AOI_FD_Neg1_min    0.047291
562                                     stat__umap_092    0.045589
500                                     stat__umap_030    0.044410
553                                     stat__umap_083    0.033071
472                                     stat__umap_002    0.031517
279        eye__fix_duration_AOI_aggregated_Pos_median    0.028699
488                                     stat__umap_018    0.023262
520                                     stat__umap_050    0.021659
525                                     stat__umap_055    0.021500
563                                     stat__umap_093    0.021018
564                                     stat__umap_094    0.019141
539                                     stat__umap_069    0.018889
59            eye__sac_length_AOI_aggregated_Pos_count    0.018461
419                 eye__lam_euclidean_length_2_rho_50    0.017481
489                                     stat__umap_019    0.016945
487                                     stat__umap_017    0.016509
299                               eye__fuzzy_m_3_r_400    0.016465
5                                  eye__sac_length_sum    0.016142
559                                     stat__umap_089    0.015577
509                                     stat__umap_039    0.015533
498                                     stat__umap_028    0.014968
471                                     stat__umap_001    0.014957
545                                     stat__umap_075    0.014272
503                                     stat__umap_033    0.014227
528                                     stat__umap_058    0.014047
84   eye__sac_speed_from_Neg_to_Target_from_Neg_to_...    0.013801

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.58539
              precision    recall  f1-score   support

           0       0.71      0.87      0.78       306
           1       0.54      0.30      0.39       155

    accuracy                           0.68       461
   macro avg       0.63      0.59      0.59       461
weighted avg       0.65      0.68      0.65       461

Confusion matrix:
 [[266  40]
 [108  47]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\feature_importances_eye_text2text\exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
60         eye__sac_speed_AOI_aggregated_Pos_min   15.308794
183            eye__fix_duration_AOI_FD_Neg1_sum    6.426038
263     eye__fix_duration_AOI_aggregated_Neg_sum    6.250330
29        eye__sac_length_AOI_aggregated_Neg_min    5.588774
56     eye__sac_length_AOI_aggregated_Pos_median    2.966440
486                               stat__umap_016    2.938546
560                               stat__umap_090    2.890391
307                 eye__phase_entropy_m_3_tau_2    2.747164
175          eye__fix_duration_AOI_FD_Neg1_first    2.683831
464                                eye__imf0_min    2.561135
472                               stat__umap_002    2.367232
528                               stat__umap_058    2.252474
564                               stat__umap_094    2.174386
53        eye__sac_length_AOI_aggregated_Pos_min    2.124714
527                               stat__umap_057    1.800636
166                        eye__fix_duration_min    1.671149
516                               stat__umap_046    1.651215
470                               stat__umap_000    1.634548
167                        eye__fix_duration_max    1.570224
421   eye__rec_metric_euclidean_length_2_rho_250    1.513026
504                               stat__umap_034    1.484878
274  eye__fix_duration_AOI_aggregated_None_count    1.462515
31       eye__sac_length_AOI_aggregated_Neg_mean    1.420780
495                               stat__umap_025    1.325331
526                               stat__umap_056    1.295717
539                               stat__umap_069    1.235140
351         eye__lyapunov_exponent_m_2_tau_2_T_2    1.207983
55       eye__sac_length_AOI_aggregated_Pos_mean    1.154530
561                               stat__umap_091    1.153356
483                               stat__umap_013    1.123287

[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

[I 2026-04-09 15:33:49,622] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-09 15:34:05,444] Trial 0 finished with value: 0.6573021170177182 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6573021170177182.
[I 2026-04-09 15:34:17,961] Trial 1 finished with value: 0.6417022281024043 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6573021170177182.
[I 2026-04-09 15:34:38,758] Trial 2 finished with value: 0.6622807493866013 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:34:50,127] Trial 3 finished with value: 0.653495854180875 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:35:01,629] Trial 4 finished with value: 0.6572144126346888 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:35:17,903] Trial 5 finished with value: 0.6543114836382887 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:35:26,387] Trial 6 finished with value: 0.6438320693741348 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:35:48,560] Trial 7 finished with value: 0.655844927722456 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:35:58,159] Trial 8 finished with value: 0.6618669385824333 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:36:29,873] Trial 9 finished with value: 0.6607441628397118 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:36:50,625] Trial 10 finished with value: 0.6581688614181137 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8323975169664899, 'colsample_bytree': 0.8251024923043149, 'gamma': 1.4856799266904641, 'reg_alpha': 0.000753460297138337, 'reg_lambda': 0.00839106795699683}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:37:04,010] Trial 11 finished with value: 0.6589417146768086 and parameters: {'learning_rate': 0.1040641083764713, 'max_depth': 4, 'min_child_weight': 1.8509892703399673, 'subsample': 0.7706037283090471, 'colsample_bytree': 0.8277506537128274, 'gamma': 1.2951782940621737, 'reg_alpha': 9.16157529770763, 'reg_lambda': 0.00013386192543122697}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:37:26,217] Trial 12 finished with value: 0.6561555546741036 and parameters: {'learning_rate': 0.03499279857296113, 'max_depth': 7, 'min_child_weight': 1.4849676189966616, 'subsample': 0.7011809824550942, 'colsample_bytree': 0.8756542573168521, 'gamma': 1.5298001508083239, 'reg_alpha': 0.004426984370678881, 'reg_lambda': 0.01041615996010209}. Best is trial 2 with value: 0.6622807493866013.
[I 2026-04-09 15:37:37,902] Trial 13 finished with value: 0.6669905080710395 and parameters: {'learning_rate': 0.06933320335699729, 'max_depth': 4, 'min_child_weight': 1.0222605184782243, 'subsample': 0.8255825599237012, 'colsample_bytree': 0.7970216666951853, 'gamma': 1.1262964914320015, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.0008353832502148781}. Best is trial 13 with value: 0.6669905080710395.
[I 2026-04-09 15:37:49,495] Trial 14 finished with value: 0.6580773096544745 and parameters: {'learning_rate': 0.07098444143011085, 'max_depth': 3, 'min_child_weight': 1.0870273688132326, 'subsample': 0.8364476943088845, 'colsample_bytree': 0.7923381324485034, 'gamma': 1.5719437299462427, 'reg_alpha': 0.0001004306624937685, 'reg_lambda': 0.0001117549875288084}. Best is trial 13 with value: 0.6669905080710395.
[I 2026-04-09 15:38:06,618] Trial 15 finished with value: 0.6618936238231393 and parameters: {'learning_rate': 0.04045248226040531, 'max_depth': 4, 'min_child_weight': 2.4074154934038456, 'subsample': 0.9132837012381982, 'colsample_bytree': 0.7035193179308173, 'gamma': 0.684152480075638, 'reg_alpha': 0.0043861958461116745, 'reg_lambda': 0.02359270857204869}. Best is trial 13 with value: 0.6669905080710395.
[I 2026-04-09 15:38:28,281] Trial 16 finished with value: 0.6576145656813764 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 5, 'min_child_weight': 1.409432987501817, 'subsample': 0.8196591312632868, 'colsample_bytree': 0.7816735409776918, 'gamma': 1.7352188376971578, 'reg_alpha': 0.0045923956759843405, 'reg_lambda': 9.968625683962115}. Best is trial 13 with value: 0.6669905080710395.
[I 2026-04-09 15:38:42,601] Trial 17 finished with value: 0.6573211603710865 and parameters: {'learning_rate': 0.05168609267354756, 'max_depth': 4, 'min_child_weight': 2.2186321290223736, 'subsample': 0.8715702573267258, 'colsample_bytree': 0.8102981516792178, 'gamma': 1.2887986000683975, 'reg_alpha': 0.0007778750916052477, 'reg_lambda': 0.1359490889687767}. Best is trial 13 with value: 0.6669905080710395.
[I 2026-04-09 15:38:54,839] Trial 18 finished with value: 0.6686787377962319 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 3, 'min_child_weight': 1.21051535723404, 'subsample': 0.7446808508456166, 'colsample_bytree': 0.8721888907468756, 'gamma': 1.9970403958572902, 'reg_alpha': 0.011369323040656817, 'reg_lambda': 0.0007081527398579118}. Best is trial 18 with value: 0.6686787377962319.
[I 2026-04-09 15:39:07,589] Trial 19 finished with value: 0.67269918546476 and parameters: {'learning_rate': 0.06491901059388135, 'max_depth': 3, 'min_child_weight': 1.2295599815697866, 'subsample': 0.7421659449956863, 'colsample_bytree': 0.8646154266266405, 'gamma': 0.4614629025328767, 'reg_alpha': 0.013598346963629675, 'reg_lambda': 0.0004600932739946204}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:39:17,714] Trial 20 finished with value: 0.6626516919618032 and parameters: {'learning_rate': 0.12974842342255155, 'max_depth': 3, 'min_child_weight': 2.4257083082583843, 'subsample': 0.7243020725394241, 'colsample_bytree': 0.87010991418268, 'gamma': 0.4933578665583995, 'reg_alpha': 0.06174363365969817, 'reg_lambda': 0.00044247158557228}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:39:30,928] Trial 21 finished with value: 0.6664603543022417 and parameters: {'learning_rate': 0.06125236668320993, 'max_depth': 3, 'min_child_weight': 1.2079835425046797, 'subsample': 0.7512054439093984, 'colsample_bytree': 0.8537452657189555, 'gamma': 0.855086491533449, 'reg_alpha': 0.01411147004322895, 'reg_lambda': 0.0003500664041612397}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:39:41,748] Trial 22 finished with value: 0.6672860396905381 and parameters: {'learning_rate': 0.07810490638804024, 'max_depth': 3, 'min_child_weight': 1.005838761060864, 'subsample': 0.7461521842803491, 'colsample_bytree': 0.9126236302782932, 'gamma': 0.3819294956753477, 'reg_alpha': 0.0019221626041503507, 'reg_lambda': 0.0017583565177542878}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:39:53,070] Trial 23 finished with value: 0.6632469995101867 and parameters: {'learning_rate': 0.0820680679568849, 'max_depth': 3, 'min_child_weight': 1.1803365219463633, 'subsample': 0.7526157327551473, 'colsample_bytree': 0.9029731802887735, 'gamma': 0.31491447055842947, 'reg_alpha': 0.012811130772066089, 'reg_lambda': 0.0028148997145472894}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:06,307] Trial 24 finished with value: 0.6605283848830745 and parameters: {'learning_rate': 0.05665489478814188, 'max_depth': 3, 'min_child_weight': 1.8772822893738257, 'subsample': 0.700131001920093, 'colsample_bytree': 0.901942230829208, 'gamma': 0.434683957689644, 'reg_alpha': 0.0004546372383473624, 'reg_lambda': 0.004397497916130692}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:18,301] Trial 25 finished with value: 0.6606078898970532 and parameters: {'learning_rate': 0.08768688499115425, 'max_depth': 4, 'min_child_weight': 1.3090470809072234, 'subsample': 0.8011532879934636, 'colsample_bytree': 0.9119933170366595, 'gamma': 0.8127947297452212, 'reg_alpha': 0.001855412085672327, 'reg_lambda': 0.0002377492800725625}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:26,419] Trial 26 finished with value: 0.6689817470340268 and parameters: {'learning_rate': 0.136271130453551, 'max_depth': 3, 'min_child_weight': 1.6052482263124435, 'subsample': 0.7272803732452405, 'colsample_bytree': 0.9833552251532973, 'gamma': 1.9991361650069521, 'reg_alpha': 0.00017062622551640706, 'reg_lambda': 0.0010274543331118687}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:33,654] Trial 27 finished with value: 0.6506290643359668 and parameters: {'learning_rate': 0.19907241498477082, 'max_depth': 3, 'min_child_weight': 1.6157395105501808, 'subsample': 0.7257825119077564, 'colsample_bytree': 0.9948520612969032, 'gamma': 1.9643651260840589, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 0.0006936755109674871}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:41,834] Trial 28 finished with value: 0.6674225702806615 and parameters: {'learning_rate': 0.1355852907707668, 'max_depth': 4, 'min_child_weight': 2.019547603194838, 'subsample': 0.7606703704048665, 'colsample_bytree': 0.8446781763238197, 'gamma': 1.7912910198983876, 'reg_alpha': 0.0632731977424815, 'reg_lambda': 0.0002741458935062077}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:40:55,906] Trial 29 finished with value: 0.6655268889986875 and parameters: {'learning_rate': 0.044655662732009424, 'max_depth': 4, 'min_child_weight': 2.8341078362114063, 'subsample': 0.7299381942473461, 'colsample_bytree': 0.9909581895090221, 'gamma': 1.3968135514391964, 'reg_alpha': 0.0003386650941599483, 'reg_lambda': 0.004366230260443754}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:04,537] Trial 30 finished with value: 0.6608471907399835 and parameters: {'learning_rate': 0.11117264362235514, 'max_depth': 3, 'min_child_weight': 4.140646528769087, 'subsample': 0.7152393846057098, 'colsample_bytree': 0.96398386802783, 'gamma': 1.8902432670445082, 'reg_alpha': 0.6852999662358916, 'reg_lambda': 0.018502244216073403}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:12,669] Trial 31 finished with value: 0.6715987501076637 and parameters: {'learning_rate': 0.1409246554767278, 'max_depth': 4, 'min_child_weight': 1.954409027329548, 'subsample': 0.7610346363658362, 'colsample_bytree': 0.8475969307364434, 'gamma': 1.9950200818626715, 'reg_alpha': 0.05414934084357923, 'reg_lambda': 0.00022973071266218557}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:20,425] Trial 32 finished with value: 0.6683579967206057 and parameters: {'learning_rate': 0.1393274442969894, 'max_depth': 3, 'min_child_weight': 1.642926494747625, 'subsample': 0.8076377565295616, 'colsample_bytree': 0.8518927494781683, 'gamma': 1.958481870022585, 'reg_alpha': 0.009738079542171298, 'reg_lambda': 0.0007577207230488287}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:28,356] Trial 33 finished with value: 0.6518125334477155 and parameters: {'learning_rate': 0.1525418022570547, 'max_depth': 4, 'min_child_weight': 1.2414891847629221, 'subsample': 0.7382069818539542, 'colsample_bytree': 0.8882655020886201, 'gamma': 1.6673457226351442, 'reg_alpha': 0.04301176944021707, 'reg_lambda': 0.00010410890146736002}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:36,600] Trial 34 finished with value: 0.6615159204458405 and parameters: {'learning_rate': 0.09544338386799958, 'max_depth': 3, 'min_child_weight': 1.6007616948737564, 'subsample': 0.7679179262038351, 'colsample_bytree': 0.8192975335575743, 'gamma': 1.7097103627952228, 'reg_alpha': 0.0015073774731810732, 'reg_lambda': 0.00021605424207795865}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:46,944] Trial 35 finished with value: 0.656675899291471 and parameters: {'learning_rate': 0.1934474872442372, 'max_depth': 8, 'min_child_weight': 2.86201730078925, 'subsample': 0.7157207481764604, 'colsample_bytree': 0.842194521134303, 'gamma': 0.18974693329058995, 'reg_alpha': 0.12326988486516442, 'reg_lambda': 0.0010808599323699581}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:41:56,515] Trial 36 finished with value: 0.6597553782969187 and parameters: {'learning_rate': 0.12048402839660462, 'max_depth': 5, 'min_child_weight': 1.3583691623714609, 'subsample': 0.7783038256093353, 'colsample_bytree': 0.8605366951268604, 'gamma': 1.994212807413833, 'reg_alpha': 0.5276035624181439, 'reg_lambda': 0.0005803188785072992}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:42:04,814] Trial 37 finished with value: 0.6595533490392244 and parameters: {'learning_rate': 0.16402975050381152, 'max_depth': 3, 'min_child_weight': 2.180064663442876, 'subsample': 0.8555326202990784, 'colsample_bytree': 0.889896720769294, 'gamma': 1.8694111826564153, 'reg_alpha': 0.010046210383978443, 'reg_lambda': 0.0027137150450852877}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:42:17,143] Trial 38 finished with value: 0.663205089845748 and parameters: {'learning_rate': 0.06701149532940072, 'max_depth': 4, 'min_child_weight': 5.586068858324622, 'subsample': 0.7599916615691354, 'colsample_bytree': 0.9248430289902366, 'gamma': 1.6094115677462724, 'reg_alpha': 0.0002183587277390486, 'reg_lambda': 0.00037576322923883043}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:42:25,820] Trial 39 finished with value: 0.6630053807816866 and parameters: {'learning_rate': 0.09544973445398916, 'max_depth': 4, 'min_child_weight': 1.1804128729420287, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9609858516875162, 'gamma': 1.7924239893786873, 'reg_alpha': 0.30738606428473825, 'reg_lambda': 0.00022130850111489418}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:42:44,870] Trial 40 finished with value: 0.6573846476144037 and parameters: {'learning_rate': 0.04753392772633607, 'max_depth': 5, 'min_child_weight': 1.5007737109345372, 'subsample': 0.9312647070030003, 'colsample_bytree': 0.7765380388234422, 'gamma': 0.03715268658761328, 'reg_alpha': 0.025209462030688568, 'reg_lambda': 0.0013036152914572359}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:42:52,750] Trial 41 finished with value: 0.6677182153641844 and parameters: {'learning_rate': 0.14371961754499937, 'max_depth': 3, 'min_child_weight': 1.7637314996834588, 'subsample': 0.8013814721843238, 'colsample_bytree': 0.8408219698066907, 'gamma': 1.9902305360680739, 'reg_alpha': 0.007055724398415136, 'reg_lambda': 0.0006903868878784947}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:00,369] Trial 42 finished with value: 0.6632812990692302 and parameters: {'learning_rate': 0.17087100793912238, 'max_depth': 3, 'min_child_weight': 1.7063205764649112, 'subsample': 0.7983437087518473, 'colsample_bytree': 0.8550749506484792, 'gamma': 1.8093491679046987, 'reg_alpha': 0.02064262873225708, 'reg_lambda': 0.0005113163539891073}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:10,064] Trial 43 finished with value: 0.6589841990511929 and parameters: {'learning_rate': 0.12303538694096823, 'max_depth': 7, 'min_child_weight': 1.4391919798923936, 'subsample': 0.7378336306192993, 'colsample_bytree': 0.8307055086905067, 'gamma': 1.8783428470219048, 'reg_alpha': 0.03569531784128883, 'reg_lambda': 0.002351043744080238}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:18,720] Trial 44 finished with value: 0.661412525423803 and parameters: {'learning_rate': 0.10805925370882043, 'max_depth': 3, 'min_child_weight': 1.9768275850711927, 'subsample': 0.7767669418201121, 'colsample_bytree': 0.8671350904543453, 'gamma': 1.92278017106414, 'reg_alpha': 0.16425855502708742, 'reg_lambda': 0.00015631519830536293}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:27,384] Trial 45 finished with value: 0.6667014048538459 and parameters: {'learning_rate': 0.1443664615993612, 'max_depth': 3, 'min_child_weight': 1.1038927333572175, 'subsample': 0.8159818544431026, 'colsample_bytree': 0.9467904747136902, 'gamma': 0.9316832854253472, 'reg_alpha': 0.008053119773856253, 'reg_lambda': 0.005691062268324672}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:33,463] Trial 46 finished with value: 0.6580881202545261 and parameters: {'learning_rate': 0.18083937972163505, 'max_depth': 3, 'min_child_weight': 1.3115522289847505, 'subsample': 0.7121977381149515, 'colsample_bytree': 0.8077772039348602, 'gamma': 1.719021504695654, 'reg_alpha': 0.07789316440116613, 'reg_lambda': 0.5028758395804253}. Best is trial 19 with value: 0.67269918546476.
[I 2026-04-09 15:43:41,056] Trial 47 finished with value: 0.661911757022172 and parameters: {'learning_rate': 0.15300872268139512, 'max_depth': 4, 'min_child_weight': 1.5610866866013557, 'subsample': 0.7630351175611221, 'colsample_bytree': 0.8899232920417154, 'gamma': 1.4783171425071615, 'reg_alpha': 0.016260761946764228, 'reg_lambda': 0.0011045888987871065}. Best is trial 19 with value: 0.67269918546476.

[I 2026-04-09 15:53:20,327] A new study created in memory with name: multiclass_catboost

[I 2026-04-09 15:53:20,323] Trial 99 finished with value: 0.6649896420022853 and parameters: {'learning_rate': 0.056142976226852576, 'max_depth': 3, 'min_child_weight': 4.467497946518811, 'subsample': 0.7567756059888736, 'colsample_bytree': 0.7349164684774108, 'gamma': 1.6215699095869343, 'reg_alpha': 0.00027563100394057186, 'reg_lambda': 0.00511278463681901}. Best is trial 65 with value: 0.677213965628718.

Best model (xgb) CV score: 0.67721
Best params: {'learning_rate': 0.06327693577939092, 'max_depth': 3, 'min_child_weight': 3.374720715347757, 'subsample': 0.7440950657756252, 'colsample_bytree': 0.7385870002920583, 'gamma': 1.8513825237823012, 'reg_alpha': 0.0002350258407632858, 'reg_lambda': 0.005677219192502088}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-09 15:53:34,974] Trial 0 finished with value: 0.6534611515237535 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6534611515237535.
[I 2026-04-09 15:54:13,528] Trial 1 finished with value: 0.6642248821524731 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6642248821524731.
[I 2026-04-09 15:54:41,270] Trial 2 finished with value: 0.6689663213694816 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 15:55:39,178] Trial 3 finished with value: 0.6618718808165294 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 15:56:58,632] Trial 4 finished with value: 0.6571603473845231 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 15:59:03,612] Trial 5 finished with value: 0.6643978245953857 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:00:04,172] Trial 6 finished with value: 0.6552693152450952 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:01:31,525] Trial 7 finished with value: 0.6573936683278152 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:04:59,738] Trial 8 finished with value: 0.6479588455558762 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:05:40,634] Trial 9 finished with value: 0.6607238271948477 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:05:56,420] Trial 10 finished with value: 0.6680321140259188 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.040269472988759346, 'depth': 5, 'l2_leaf_reg': 5.1892447574518465, 'random_strength': 0.402192133386275, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9290346996252341}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:06:12,373] Trial 11 finished with value: 0.6662719057977753 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039688510872899645, 'depth': 5, 'l2_leaf_reg': 5.365538882909708, 'random_strength': 0.4258355123760916, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9494635180573001}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:06:32,332] Trial 12 finished with value: 0.6615776789090427 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03251444710110255, 'depth': 5, 'l2_leaf_reg': 6.949461600155238, 'random_strength': 0.33546401309849905, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8769747357034408}. Best is trial 2 with value: 0.6689663213694816.
[I 2026-04-09 16:06:45,918] Trial 13 finished with value: 0.6719493451051088 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05112260807044497, 'depth': 5, 'l2_leaf_reg': 2.8824168632634826, 'random_strength': 0.5416015158264689, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8327699903801722}. Best is trial 13 with value: 0.6719493451051088.
[I 2026-04-09 16:07:11,210] Trial 14 finished with value: 0.6756909104232108 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0545067764947917, 'depth': 6, 'l2_leaf_reg': 3.1765242172998045, 'random_strength': 0.9711042545282231, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8213062013981732}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:07:23,042] Trial 15 finished with value: 0.6592519874406433 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12450272923273262, 'depth': 5, 'l2_leaf_reg': 2.7544085124614925, 'random_strength': 0.8798833392165663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8463248437114305}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:07:48,761] Trial 16 finished with value: 0.6682589749495466 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05219399788945581, 'depth': 6, 'l2_leaf_reg': 3.0468703933905927, 'random_strength': 0.9777864983056361, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8324742193566149}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:07:57,540] Trial 17 finished with value: 0.6701186957970752 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.058427474083642336, 'depth': 4, 'l2_leaf_reg': 2.8093264736779213, 'random_strength': 0.6073683048265693, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8948496747322341}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:08:08,015] Trial 18 finished with value: 0.6738354878680892 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10922936507276139, 'depth': 5, 'l2_leaf_reg': 1.7209605016239704, 'random_strength': 0.5509887326523585, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.998940256994706}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:08:25,243] Trial 19 finished with value: 0.667200807774983 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15360967997703137, 'depth': 6, 'l2_leaf_reg': 1.0431711469541898, 'random_strength': 0.9807728570370347, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9796905648411014}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:09:00,414] Trial 20 finished with value: 0.6564635043621473 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11174086542141344, 'depth': 7, 'l2_leaf_reg': 2.10327174265179, 'random_strength': 0.7594621052777439, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9983563972109731}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:09:12,411] Trial 21 finished with value: 0.6739081004645939 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06356849528116322, 'depth': 5, 'l2_leaf_reg': 1.391107891936582, 'random_strength': 0.535291503633385, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8078940946681937}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:09:24,724] Trial 22 finished with value: 0.6666483188442972 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06370420375364685, 'depth': 5, 'l2_leaf_reg': 1.4765341937623395, 'random_strength': 0.5422402442726458, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7778548319352842}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:09:44,363] Trial 23 finished with value: 0.6620741434662593 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1029610423770398, 'depth': 6, 'l2_leaf_reg': 1.4394735148028284, 'random_strength': 0.7366880152694889, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7180118884342727}. Best is trial 14 with value: 0.6756909104232108.
[I 2026-04-09 16:09:51,213] Trial 24 finished with value: 0.679339971029113 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13779738961806276, 'depth': 4, 'l2_leaf_reg': 2.178999416792304, 'random_strength': 0.8634604401789102, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8937539493098821}. Best is trial 24 with value: 0.679339971029113.
[I 2026-04-09 16:09:57,587] Trial 25 finished with value: 0.6700513838206849 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19748764681852474, 'depth': 4, 'l2_leaf_reg': 2.2587844430549158, 'random_strength': 0.8888090384810352, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8016849253908013}. Best is trial 24 with value: 0.679339971029113.
[I 2026-04-09 16:10:04,367] Trial 26 finished with value: 0.6736253606030557 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1441304512545532, 'depth': 4, 'l2_leaf_reg': 1.2731554584126024, 'random_strength': 0.8131164398161632, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 24 with value: 0.679339971029113.
[I 2026-04-09 16:10:15,552] Trial 27 finished with value: 0.6827932333089567 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032268980599861455, 'depth': 4, 'l2_leaf_reg': 3.7289714152131666, 'random_strength': 0.9184596551244129, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.875878978639966}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:10:27,047] Trial 28 finished with value: 0.6772711079596571 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0308766484886228, 'depth': 4, 'l2_leaf_reg': 3.492051415276117, 'random_strength': 0.9260210240243343, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8999135743823408}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:10:52,539] Trial 29 finished with value: 0.6547771947550926 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03083973038065317, 'depth': 4, 'l2_leaf_reg': 3.5023858260961607, 'random_strength': 0.9184196858954476, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:11:06,629] Trial 30 finished with value: 0.6793623016457977 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020230344976258988, 'depth': 4, 'l2_leaf_reg': 3.7731140207423994, 'random_strength': 0.8165046302561295, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.887457869128874}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:11:20,818] Trial 31 finished with value: 0.6751003573694914 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022229483394338705, 'depth': 4, 'l2_leaf_reg': 3.8136858149861474, 'random_strength': 0.8161939360034707, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8973158850541484}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:11:32,407] Trial 32 finished with value: 0.6793826684179026 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028097604808132243, 'depth': 4, 'l2_leaf_reg': 2.2337673632648594, 'random_strength': 0.7057739026981756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8772258822026294}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:11:43,747] Trial 33 finished with value: 0.6782753427318028 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024729774069625007, 'depth': 4, 'l2_leaf_reg': 2.258463695111541, 'random_strength': 0.6983289515101831, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8608116323064908}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:11:59,116] Trial 34 finished with value: 0.6681379279443824 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02584436874622073, 'depth': 4, 'l2_leaf_reg': 2.4404977762737694, 'random_strength': 0.8050028622946999, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9397502626023202}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:12:09,587] Trial 35 finished with value: 0.680881577766944 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03492220194347332, 'depth': 4, 'l2_leaf_reg': 1.8916496027634029, 'random_strength': 0.696634143851673, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9277199449654323}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:12:20,268] Trial 36 finished with value: 0.6719529575233278 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03560481107288148, 'depth': 4, 'l2_leaf_reg': 5.614045751965339, 'random_strength': 0.620643926987438, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9226322517211356}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:12:35,906] Trial 37 finished with value: 0.6632903934085714 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027074595779445973, 'depth': 4, 'l2_leaf_reg': 4.239330348094426, 'random_strength': 0.6938223733201873, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9615827782380251}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:12:49,948] Trial 38 finished with value: 0.6765345988181094 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02002620032529677, 'depth': 4, 'l2_leaf_reg': 7.5089581485111205, 'random_strength': 0.7513909238214003, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12221043743904225}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:13:18,103] Trial 39 finished with value: 0.6635624410236435 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02307592307635512, 'depth': 5, 'l2_leaf_reg': 1.7836311584738112, 'random_strength': 0.6653712842235311, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8705867532894543}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:13:32,285] Trial 40 finished with value: 0.6693131834133644 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02820601386862086, 'depth': 4, 'l2_leaf_reg': 10.06795044277389, 'random_strength': 0.2551267960781407, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.4532051511681003}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:13:42,380] Trial 41 finished with value: 0.6781472700685918 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.035701346023798715, 'depth': 4, 'l2_leaf_reg': 1.8362440542548106, 'random_strength': 0.8499122630120249, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9027852681064658}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:13:51,429] Trial 42 finished with value: 0.6749945236011828 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04369106631989384, 'depth': 4, 'l2_leaf_reg': 2.5231968232952027, 'random_strength': 0.7846790319398995, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9145452477307208}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:13:59,232] Trial 43 finished with value: 0.6801489129695942 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0885758958597263, 'depth': 4, 'l2_leaf_reg': 2.013586062587457, 'random_strength': 0.938848712910304, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8700617596961988}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:14:07,093] Trial 44 finished with value: 0.6738512242402248 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08416945136364036, 'depth': 4, 'l2_leaf_reg': 1.9240000121903684, 'random_strength': 0.9361207342934321, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8584685679948677}. Best is trial 27 with value: 0.6827932333089567.
[I 2026-04-09 16:14:24,932] Trial 45 finished with value: 0.6666350481360293 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023561845738073028, 'depth': 5, 'l2_leaf_reg': 1.1801519408361993, 'random_strength': 0.003701014064702468, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.879396285111309}. Best is trial 27 with value: 0.6827932333089567.

                                               feature  importance
276           eye__fix_duration_AOI_aggregated_Pos_min    0.049305
30              eye__sac_length_AOI_aggregated_Neg_max    0.029191
62              eye__sac_speed_AOI_aggregated_Pos_mean    0.027826
55             eye__sac_length_AOI_aggregated_Pos_mean    0.026835
176                  eye__fix_duration_AOI_FD_Neg1_min    0.024355
29              eye__sac_length_AOI_aggregated_Neg_min    0.024344
177                  eye__fix_duration_AOI_FD_Neg1_max    0.023283
56           eye__sac_length_AOI_aggregated_Pos_median    0.018503
184                eye__fix_duration_AOI_FD_Neg1_count    0.018419
175                eye__fix_duration_AOI_FD_Neg1_first    0.015231
31             eye__sac_length_AOI_aggregated_Neg_mean    0.014362
178                 eye__fix_duration_AOI_FD_Neg1_mean    0.013828
63            eye__sac_speed_AOI_aggregated_Pos_median    0.013134
58              eye__sac_length_AOI_aggregated_Pos_sum    0.011461
59            eye__sac_length_AOI_aggregated_Pos_count    0.011457
183                  eye__fix_duration_AOI_FD_Neg1_sum    0.011085
53              eye__sac_length_AOI_aggregated_Pos_min    0.010441
271     eye__fix_duration_AOI_aggregated_None_kurtosis    0.009058
535                                     stat__umap_065    0.008689
277           eye__fix_duration_AOI_aggregated_Pos_max    0.008604
278          eye__fix_duration_AOI_aggregated_Pos_mean    0.007996
54              eye__sac_length_AOI_aggregated_Pos_max    0.006820
214                eye__fix_duration_AOI_FD_Pos1_count    0.006800
481                                     stat__umap_011    0.006661
34              eye__sac_length_AOI_aggregated_Neg_sum    0.006628
47           eye__sac_length_AOI_aggregated_None_count    0.006424
266          eye__fix_duration_AOI_aggregated_None_min    0.006257
60               eye__sac_speed_AOI_aggregated_Pos_min    0.006208
96   eye__sac_speed_from_Pos_to_Target_from_Pos_to_...    0.005761
194                eye__fix_duration_AOI_FD_None_count    0.005720

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.80777
              precision    recall  f1-score   support

           0       0.85      0.67      0.75       156
           1       0.84      0.79      0.82       180
           2       0.75      1.00      0.86       125

    accuracy                           0.81       461
   macro avg       0.81      0.82      0.81       461
weighted avg       0.82      0.81      0.81       461

Confusion matrix:
 [[105  27  24]
 [ 19 143  18]
 [  0   0 125]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\feature_importances_eye_text2text\exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
256     eye__fix_duration_AOI_aggregated_Neg_min    6.327715
35      eye__sac_length_AOI_aggregated_Neg_count    5.948342
259  eye__fix_duration_AOI_aggregated_Neg_median    5.646431
264   eye__fix_duration_AOI_aggregated_Neg_count    5.397057
32     eye__sac_length_AOI_aggregated_Neg_median    4.918009
38        eye__sac_speed_AOI_aggregated_Neg_mean    4.581234
36         eye__sac_speed_AOI_aggregated_Neg_min    4.244335
255   eye__fix_duration_AOI_aggregated_Neg_first    3.169397
263     eye__fix_duration_AOI_aggregated_Neg_sum    3.142982
31       eye__sac_length_AOI_aggregated_Neg_mean    2.860741
29        eye__sac_length_AOI_aggregated_Neg_min    2.769619
58        eye__sac_length_AOI_aggregated_Pos_sum    2.684677
61         eye__sac_speed_AOI_aggregated_Pos_max    2.634979
60         eye__sac_speed_AOI_aggregated_Pos_min    2.562283
37         eye__sac_speed_AOI_aggregated_Neg_max    2.292582
34        eye__sac_length_AOI_aggregated_Neg_sum    2.022725
55       eye__sac_length_AOI_aggregated_Pos_mean    1.923419
178           eye__fix_duration_AOI_FD_Neg1_mean    1.892008
284   eye__fix_duration_AOI_aggregated_Pos_count    1.851831
183            eye__fix_duration_AOI_FD_Neg1_sum    1.510932
179         eye__fix_duration_AOI_FD_Neg1_median    1.403756
184          eye__fix_duration_AOI_FD_Neg1_count    1.399460
59      eye__sac_length_AOI_aggregated_Pos_count    1.394506
258    eye__fix_duration_AOI_aggregated_Neg_mean    1.382237
53        eye__sac_length_AOI_aggregated_Pos_min    1.333813
56     eye__sac_length_AOI_aggregated_Pos_median    1.289547
39      eye__sac_speed_AOI_aggregated_Neg_median    1.199206
207            eye__fix_duration_AOI_FD_Pos1_max    0.989612
175          eye__fix_duration_AOI_FD_Neg1_first    0.970229
279  eye__fix_duration_AOI_aggregated_Pos_median    0.921564

,text_set,target,split,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,0.399740,0.425346,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,multiclass,0.638100,0.647005,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch_general,binary,0.449997,0.585391,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch_general,multiclass,0.816845,0.807769,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,0.399740,0.425346,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,multiclass,0.638100,0.647005,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch_general,binary,0.449997,0.585391,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch_general,multiclass,0.816845,0.807769,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [11]:
# Combine summaries from all explicit sets
all_summaries = [
    summary_corr,
    summary_cov_freq,
    summary_envelope,
    summary_freq_bands,
    summary_PID,
    summary_stat,
]
all_results = pd.concat(all_summaries, ignore_index=True)
all_results

,text_set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.399740,0.400511,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.621334,0.669227,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.406654,0.532466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.797868,0.794106,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch,binary,0.399740,0.415582,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch,multiclass,0.619349,0.626280,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,binary,0.475352,0.579789,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,0.801701,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...
8,envelope,match_mismatch,binary,0.399740,0.436447,C:\Users\LEGION\Projects\CB_exepriment\dataset...
9,envelope,match_mismatch,multiclass,0.632589,0.659056,C:\Users\LEGION\Projects\CB_exepriment\dataset...
10,envelope,match_mismatch_general,binary,0.398957,0.504534,C:\Users\LEGION\Projects\CB_exepriment\dataset...
11,envelope,match_mismatch_general,multiclass,0.812691,0.803043,C:\Users\LEGION\Projects\CB_exepriment\dataset...
12,freq_bands,match_mismatch,binary,0.399740,0.413223,C:\Users\LEGION\Projects\CB_exepriment\dataset...
13,freq_bands,match_mismatch,multiclass,0.639669,0.620434,C:\Users\LEGION\Projects\CB_exepriment\dataset...
14,freq_bands,match_mismatch_general,binary,0.398957,0.509769,C:\Users\LEGION\Projects\CB_exepriment\dataset...
15,freq_bands,match_mismatch_general,multiclass,0.806212,0.792472,C:\Users\LEGION\Projects\CB_exepriment\dataset...
16,PID,match_mismatch,binary,0.399740,0.443317,C:\Users\LEGION\Projects\CB_exepriment\dataset...
17,PID,match_mismatch,multiclass,0.627365,0.624341,C:\Users\LEGION\Projects\CB_exepriment\dataset...
18,PID,match_mismatch_general,binary,0.398957,0.478687,C:\Users\LEGION\Projects\CB_exepriment\dataset...
19,PID,match_mismatch_general,multiclass,0.795993,0.774045,C:\Users\LEGION\Projects\CB_exepriment\dataset...
20,stat,match_mismatch,binary,0.399740,0.425346,C:\Users\LEGION\Projects\CB_exepriment\dataset...
21,stat,match_mismatch,multiclass,0.638100,0.647005,C:\Users\LEGION\Projects\CB_exepriment\dataset...
22,stat,match_mismatch_general,binary,0.449997,0.585391,C:\Users\LEGION\Projects\CB_exepriment\dataset...
23,stat,match_mismatch_general,multiclass,0.816845,0.807769,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [12]:
# Save + quick inspection
summary_path = OUT_DIR / "summary_eye_text2text.csv"
all_results.to_csv(summary_path, index=False)
print("Saved summary:", summary_path)

all_results.groupby(["text_set", "target", "split"], as_index=False)[["xgb_test", "catboost_test"]].mean()

Saved summary: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text\summary_eye_text2text.csv

      text_set                  target       split  xgb_test  catboost_test
0          PID          match_mismatch      binary  0.399740       0.443317
1          PID          match_mismatch  multiclass  0.627365       0.624341
2          PID  match_mismatch_general      binary  0.398957       0.478687
3          PID  match_mismatch_general  multiclass  0.795993       0.774045
4         corr          match_mismatch      binary  0.399740       0.400511
5         corr          match_mismatch  multiclass  0.621334       0.669227
6         corr  match_mismatch_general      binary  0.406654       0.532466
7         corr  match_mismatch_general  multiclass  0.797868       0.794106
8     cov_freq          match_mismatch      binary  0.399740       0.415582
9     cov_freq          match_mismatch  multiclass  0.619349       0.626280
10    cov_freq  match_mismatch_general      binary  0.475352       0.579789
11    cov_freq  match_mismatch_general  multiclass  0.801701       0.803497
12    envelope          match_mismatch      binary  0.399740       0.436447
13    envelope          match_mismatch  multiclass  0.632589       0.659056
14    envelope  match_mismatch_general      binary  0.398957       0.504534
15    envelope  match_mismatch_general  multiclass  0.812691       0.803043
16  freq_bands          match_mismatch      binary  0.399740       0.413223
17  freq_bands          match_mismatch  multiclass  0.639669       0.620434
18  freq_bands  match_mismatch_general      binary  0.398957       0.509769
19  freq_bands  match_mismatch_general  multiclass  0.806212       0.792472
20        stat          match_mismatch      binary  0.399740       0.425346
21        stat          match_mismatch  multiclass  0.638100       0.647005
22        stat  match_mismatch_general      binary  0.449997       0.585391
23        stat  match_mismatch_general  multiclass  0.816845       0.807769