# EEG-only experiments (FTAR template)

This notebook mirrors the FTAR workflow structure but uses only EEG features in `X_train`/`X_test`.
FTAR/text2text features are not concatenated into the training matrix.

Targets/splits covered:
- `match_mismatch`: binary + multiclass
- `match_mismatch_general`: binary + multiclass

In [1]:
from __future__ import annotations

import os
import json
from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd
from umap import UMAP

from experiment_code.read_data import get_data_for_split
from experiment_code.run_experiments import _build_groups_mm_for_mm
from experiment_code.optuna_code import run_and_log, fit_best_and_test

ROOT = Path(r"C:\Users\LEGION\data\СB")
os.chdir(ROOT)
print("cwd:", Path.cwd())

cwd: C:\Users\LEGION\data\СB

In [2]:
TARGETS = ["match_mismatch", "match_mismatch_general"]
SPLITS = ["binary", "multiclass"]

USE_EARLY_STOPPING = True
REFIT_CV = False
REFIT_TEST = True
USE_MIN = False

CV = 4
N_TRIALS_XGB = 100
N_TRIALS_CB = 50

PROJECT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\dataset_v2")
OUT_DIR = PROJECT_DIR / "optuna_results_eye_ftar"
OUT_DIR.mkdir(parents=True, exist_ok=True)

FI_DIR = OUT_DIR / "feature_importances_eye_ftar"
FI_DIR.mkdir(parents=True, exist_ok=True)
REFIT_TOP_N = 30

UMAP_TARGET_SETS = {"freq_bands", "stat", "corr", "cov_freq"}
UMAP_N_COMPONENTS = 100
UMAP_N_NEIGHBORS = 30
UMAP_MIN_DIST = 0.0
UMAP_METRIC = "cosine"
UMAP_RANDOM_STATE = 1717

CLEAN_TRAIN_COLUMNS = False

In [ ]:
def _prefix_cols(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    return df.add_prefix(prefix)


def _load_ftar_parquet(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    if "pid_rn" not in df.columns:
        raise KeyError(f"'pid_rn' column not found in {path}")
    df = df.set_index("pid_rn")
    df.index = df.index.astype(str)
    return df


def _apply_umap_train_test(
    text_train: pd.DataFrame,
    text_test: pd.DataFrame,
    *,
    text_set_name: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    tr = text_train.apply(pd.to_numeric, errors="coerce")
    te = text_test.apply(pd.to_numeric, errors="coerce")

    train_means = tr.mean(numeric_only=True)
    tr = tr.fillna(train_means).fillna(0.0)
    te = te.fillna(train_means).fillna(0.0)

    n_components = int(min(UMAP_N_COMPONENTS, max(2, tr.shape[1])))
    reducer = UMAP(
        n_components=n_components,
        n_neighbors=UMAP_N_NEIGHBORS,
        min_dist=UMAP_MIN_DIST,
        metric=UMAP_METRIC,
        random_state=UMAP_RANDOM_STATE,
    )

    print(
        f"[{text_set_name}] UMAP compression: "
        f"train/test features {tr.shape[1]} -> {n_components}"
    )

    z_train = reducer.fit_transform(tr)
    z_test = reducer.transform(te)

    cols = [f"{text_set_name}__umap_{i:03d}" for i in range(n_components)]
    tr_umap = pd.DataFrame(z_train, index=text_train.index, columns=cols)
    te_umap = pd.DataFrame(z_test, index=text_test.index, columns=cols)
    return tr_umap, te_umap


def _prepare_joined_X(
    train_index: pd.Index,
    test_index: pd.Index,
    text_all: pd.DataFrame,
    text_set_name: str,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    text_train = text_all.reindex(train_index)
    text_test = text_all.reindex(test_index)

    missing_train = int(text_train.isna().all(axis=1).sum())
    missing_test = int(text_test.isna().all(axis=1).sum())
    print(f"[{text_set_name}] rows missing after index match -> train: {missing_train}, test: {missing_test}")

    if text_set_name in UMAP_TARGET_SETS:
        text_train_model, text_test_model = _apply_umap_train_test(
            text_train,
            text_test,
            text_set_name=text_set_name,
        )
    else:
        text_train_model = _prefix_cols(text_train, f"{text_set_name}__")
        text_test_model = _prefix_cols(text_test, f"{text_set_name}__")

    # EEG-only setup: use only EEG-set features from the selected parquet.
    X_train = text_train_model
    X_test = text_test_model

    if CLEAN_TRAIN_COLUMNS:
        keep_cols = X_train.columns[X_train.notna().all(axis=0)]
        X_train = X_train[keep_cols]
        X_test = X_test.reindex(columns=keep_cols)

    return X_train, X_test


def _build_no_neutral_mask(stim_df: pd.DataFrame, target: str, split: str) -> pd.Series:
    mask = pd.Series(True, index=stim_df.index)

    if "valence" in stim_df.columns:
        valence = pd.to_numeric(stim_df["valence"], errors="coerce")
        mask &= valence != 2

    if split == "binary":
        if target == "match_mismatch_general" and "exp_general_multi" in stim_df.columns:
            exp_general_multi = pd.to_numeric(stim_df["exp_general_multi"], errors="coerce")
            mask &= exp_general_multi != 2
        elif "IAT_results2" in stim_df.columns:
            iat = stim_df["IAT_results2"].astype(str).str.strip().str.lower()
            mask &= iat != "neutral"

    return mask.fillna(False)


def _load_eeg_for_task(target: str, split: str, no_neutral: bool = False):
    df, tgt, _ = get_data_for_split(X_name="screen", target=target, split=split)

    train_index = df["all_features"]["X_train"].index.astype(str)
    test_index = df["all_features"]["X_test"].index.astype(str)
    stim_train = df["stimuli_features"]["X_train"].copy()
    stim_test = df["stimuli_features"]["X_test"].copy()

    y_train = tgt["cb"]["y_train"].copy()
    y_test = tgt["cb"]["y_test"].copy()

    if no_neutral:
        mask_train = _build_no_neutral_mask(stim_train, target=target, split=split)
        mask_test = _build_no_neutral_mask(stim_test, target=target, split=split)

        train_index = train_index[mask_train.to_numpy()]
        test_index = test_index[mask_test.to_numpy()]
        y_train = y_train.loc[mask_train]
        y_test = y_test.loc[mask_test]
        stim_train = stim_train.loc[mask_train]

    groups = np.array([str(i).split("_")[0] for i in train_index])

    if target in ("match_mismatch", "match_mismatch_general"):
        groups_mm = _build_groups_mm_for_mm(X_train_index=train_index, stim_train_df=stim_train)
    else:
        groups_mm = None

    problem = "binary" if split == "binary" else "multiclass"
    return train_index, test_index, y_train, y_test, groups, groups_mm, problem


def run_ftar_set(
    text_set_name: str,
    text_all: pd.DataFrame,
    *,
    do_refit: bool = True,
    top_n_features: int = REFIT_TOP_N,
):
    if "pid_rn" in text_all.columns:
        text_all = text_all.set_index("pid_rn")
    text_all = text_all.copy()
    text_all.index = text_all.index.astype(str)

    if "key" in text_all.columns:
        text_all = text_all.drop(columns=["key"])

    print(f"[{text_set_name}] ftar feature count after cleanup: {int(text_all.shape[1])}")

    rows = []

    for target in TARGETS:
        for split in SPLITS:
            for no_neutral in [False, True]:
                problem = "binary" if split == "binary" else "multiclass"
                neutral_suffix = "__no_neutral" if no_neutral else ""
                train_features_name = (
                    f"exp__X_name=screen+{text_set_name}"
                    f"__target={target}"
                    f"__problem={problem}"
                    f"__feat=all_features+{text_set_name}"
                    f"__ES__refitTEST"
                    f"{neutral_suffix}"
                )
                out_path = OUT_DIR / f"{train_features_name}.json"

                if out_path.exists():
                    print("\n" + "=" * 80)
                    print(f"Skipping existing experiment: {train_features_name}")
                    with open(out_path, encoding="utf-8") as f:
                        results = json.load(f)
                    rows.append({
                        "set": text_set_name,
                        "target": target,
                        "split": split,
                        "no_neutral": no_neutral,
                        "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                        "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                        "file": str(out_path),
                    })
                    continue

                train_index, test_index, y_train, y_test, groups, groups_mm, problem = _load_eeg_for_task(
                    target,
                    split,
                    no_neutral=no_neutral,
                )
                X_train, X_test = _prepare_joined_X(train_index, test_index, text_all, text_set_name)

                print("\n" + "=" * 80)
                print(f"Running: {train_features_name}")
                print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

                results = run_and_log(
                    train_features=train_features_name,
                    problem=problem,
                    X_train=X_train,
                    X_test=X_test,
                    y_train=y_train,
                    y_test=y_test,
                    strat_train=y_train,
                    groups=groups,
                    groups_mm=groups_mm,
                    use_early_stopping=USE_EARLY_STOPPING,
                    refit_cv=REFIT_CV,
                    refit_test=REFIT_TEST,
                    n_trials_xgb=N_TRIALS_XGB,
                    n_trials_cb=N_TRIALS_CB,
                    cv=CV,
                    gpu=False,
                    use_min=USE_MIN,
                    cat_cols=None,
                    target_names=None,
                    out_path=out_path,
                )

                if do_refit:
                    print("\n" + "-" * 80)
                    print("Refit best iteration + metrics + top features")
                    for model_name in ["xgb", "catboost"]:
                        best_params = results[model_name].get("suggested_params", {})
                        if not best_params:
                            print(f"\n=== Skip refit {model_name.upper()} (no suggested params) ===")
                            continue

                        print(f"\n=== Refit {model_name.upper()} with saved best params ===")
                        out_refit = fit_best_and_test(
                            model_name=model_name,
                            best_params=best_params,
                            problem=problem,
                            X_train=X_train,
                            X_test=X_test,
                            y_train=y_train,
                            y_test=y_test,
                            strat_train=y_train,
                            groups=groups,
                            groups_mm=groups_mm,
                            use_early_stopping=True,
                            early_stopping_rounds=100,
                            target_names=None,
                            cat_cols=None,
                            gpu=False,
                            refit_test=True,
                        )

                        model = out_refit["model"]
                        if model_name == "xgb":
                            importances = model.feature_importances_
                        else:
                            importances = model.get_feature_importance()

                        fi = pd.DataFrame({
                            "feature": X_train.columns,
                            "importance": importances,
                        }).sort_values("importance", ascending=False)

                        fi_path = FI_DIR / f"{train_features_name}__{model_name}.csv"
                        fi.to_csv(fi_path, index=False)
                        print(f"Saved feature importances: {fi_path}")
                        print(f"Top {top_n_features} features for {model_name.upper()}:")
                        display(fi.head(top_n_features))

                rows.append({
                    "set": text_set_name,
                    "target": target,
                    "split": split,
                    "no_neutral": no_neutral,
                    "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                    "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                    "file": str(out_path),
                })

    summary = pd.DataFrame(rows)
    display(summary)
    return summary

In [4]:
FTAR_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\ftar_features")
FTAR_FILES = {
    "corr": FTAR_DIR / "corr.parquet",
    "cov_freq": FTAR_DIR / "cov_freq.parquet",
    "envelope": FTAR_DIR / "envelope.parquet",
    "freq_bands": FTAR_DIR / "freq_bands.parquet",
    "PID": FTAR_DIR / "PID.parquet",
    "stat": FTAR_DIR / "stat.parquet",
}

print("ftar dir:", FTAR_DIR)
for k, p in FTAR_FILES.items():
    print(f"{k:10s} -> {p} | exists={p.exists()}")

ftar dir: C:\Users\LEGION\Projects\CB_exepriment\ftar_features
corr       -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\corr.parquet | exists=True
cov_freq   -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\cov_freq.parquet | exists=True
envelope   -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\envelope.parquet | exists=True
freq_bands -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\freq_bands.parquet | exists=True
PID        -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\PID.parquet | exists=True
stat       -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\stat.parquet | exists=True

In [5]:
text_corr = _load_ftar_parquet(FTAR_FILES["corr"])
print("corr shape:", text_corr.shape)
summary_corr = run_ftar_set("corr", text_corr)
summary_corr

corr shape: (4442, 1831)
[corr] ftar feature count after cleanup: 1830

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__ES__refitTEST

,set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [6]:
text_cov_freq = _load_ftar_parquet(FTAR_FILES["cov_freq"])
print("cov_freq shape:", text_cov_freq.shape)
summary_cov_freq = run_ftar_set("cov_freq", text_cov_freq)
summary_cov_freq

cov_freq shape: (4442, 36296)
[cov_freq] ftar feature count after cleanup: 36295

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST

,set,target,split,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,multiclass,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch_general,binary,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch_general,multiclass,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,multiclass,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch_general,binary,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch_general,multiclass,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [7]:
text_envelope = _load_ftar_parquet(FTAR_FILES["envelope"])
print("envelope shape:", text_envelope.shape)
summary_envelope = run_ftar_set("envelope", text_envelope)
summary_envelope

envelope shape: (4442, 428)
[envelope] ftar feature count after cleanup: 427

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__ES__refitTEST

,set,target,split,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,multiclass,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch_general,binary,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch_general,multiclass,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,multiclass,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch_general,binary,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch_general,multiclass,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [8]:
text_freq_bands = _load_ftar_parquet(FTAR_FILES["freq_bands"])
print("freq_bands shape:", text_freq_bands.shape)
summary_freq_bands = run_ftar_set("freq_bands", text_freq_bands)
summary_freq_bands

freq_bands shape: (4442, 18362)
[freq_bands] ftar feature count after cleanup: 18361

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST

,set,target,split,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,multiclass,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch_general,binary,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch_general,multiclass,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,multiclass,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch_general,binary,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch_general,multiclass,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [9]:
text_PID = _load_ftar_parquet(FTAR_FILES["PID"])
print("PID shape:", text_PID.shape)
summary_PID = run_ftar_set("PID", text_PID)
summary_PID

PID shape: (4442, 611)
[PID] ftar feature count after cleanup: 610

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__ES__refitTEST

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__ES__refitTEST

[I 2026-04-10 10:40:58,017] A new study created in memory with name: binary_xgb

[PID] rows missing after index match -> train: 1832, test: 187

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST
X_train: (4146, 1080), X_test: (461, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 10:41:07,877] Trial 0 finished with value: 0.4413351213180705 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.4413351213180705.
[I 2026-04-10 10:41:20,499] Trial 1 finished with value: 0.43599372363115946 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.4413351213180705.
[I 2026-04-10 10:41:32,798] Trial 2 finished with value: 0.44097547725272845 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.4413351213180705.
[I 2026-04-10 10:41:43,660] Trial 3 finished with value: 0.4719008708882687 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.4719008708882687.
[I 2026-04-10 10:41:55,368] Trial 4 finished with value: 0.4674723320997658 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.4719008708882687.
[I 2026-04-10 10:42:06,577] Trial 5 finished with value: 0.46095451771870405 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.4719008708882687.
[I 2026-04-10 10:42:14,979] Trial 6 finished with value: 0.4882786735492676 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:42:27,784] Trial 7 finished with value: 0.4612506854773297 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:42:37,785] Trial 8 finished with value: 0.4360644075490273 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:42:52,907] Trial 9 finished with value: 0.43960546538428746 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:01,188] Trial 10 finished with value: 0.4690968302405482 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:09,898] Trial 11 finished with value: 0.4642841556690107 and parameters: {'learning_rate': 0.09943849583797226, 'max_depth': 4, 'min_child_weight': 5.262425700550083, 'subsample': 0.8570136783071851, 'colsample_bytree': 0.8814033552282943, 'gamma': 0.7242576829236649, 'reg_alpha': 0.014535822853933776, 'reg_lambda': 0.6360241878025359}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:19,162] Trial 12 finished with value: 0.4551640886981351 and parameters: {'learning_rate': 0.13421923310831954, 'max_depth': 5, 'min_child_weight': 5.2632762903781405, 'subsample': 0.8607534236043293, 'colsample_bytree': 0.8984053333540004, 'gamma': 1.3820801780564986, 'reg_alpha': 0.0031841301424337977, 'reg_lambda': 0.6028019569150654}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:26,899] Trial 13 finished with value: 0.43496220454711365 and parameters: {'learning_rate': 0.07142118896925374, 'max_depth': 4, 'min_child_weight': 6.848753397434836, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.8298439728713858, 'gamma': 0.7497632881663117, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.8281558812990174}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:34,367] Trial 14 finished with value: 0.4435953038345629 and parameters: {'learning_rate': 0.14646547269530377, 'max_depth': 3, 'min_child_weight': 4.028851417685709, 'subsample': 0.824622091152145, 'colsample_bytree': 0.9941983631899374, 'gamma': 1.939034111737197, 'reg_alpha': 0.6207388548340136, 'reg_lambda': 0.011924988205055102}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:44,194] Trial 15 finished with value: 0.4349433012464621 and parameters: {'learning_rate': 0.09466421880379894, 'max_depth': 5, 'min_child_weight': 2.383705088570773, 'subsample': 0.9021346382700595, 'colsample_bytree': 0.918728031615981, 'gamma': 0.47492654949154745, 'reg_alpha': 0.06975638223757245, 'reg_lambda': 0.00016599250040776937}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:43:54,759] Trial 16 finished with value: 0.47462976033723925 and parameters: {'learning_rate': 0.0994401329156947, 'max_depth': 7, 'min_child_weight': 9.598316713028954, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8433042355616011, 'gamma': 0.9591133743081539, 'reg_alpha': 0.0018972237150351793, 'reg_lambda': 0.25088663350893325}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:04,851] Trial 17 finished with value: 0.4654275497210704 and parameters: {'learning_rate': 0.13065654227290657, 'max_depth': 8, 'min_child_weight': 9.599467738622398, 'subsample': 0.7477396018075242, 'colsample_bytree': 0.8131557307738727, 'gamma': 1.2807653293339092, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 0.1782489046046313}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:13,538] Trial 18 finished with value: 0.4636484808441499 and parameters: {'learning_rate': 0.1918531530561474, 'max_depth': 7, 'min_child_weight': 7.2209050006504025, 'subsample': 0.8303437614139795, 'colsample_bytree': 0.8754263123186682, 'gamma': 1.6850588179098898, 'reg_alpha': 0.0027494526537908816, 'reg_lambda': 3.018259665263208}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:27,379] Trial 19 finished with value: 0.4659965617500453 and parameters: {'learning_rate': 0.05784708762154941, 'max_depth': 7, 'min_child_weight': 2.527738132232532, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.8397449075315706, 'gamma': 0.9380829130779358, 'reg_alpha': 0.0008831841291476058, 'reg_lambda': 0.02263970557704084}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:37,141] Trial 20 finished with value: 0.44180712455435445 and parameters: {'learning_rate': 0.15198641817447917, 'max_depth': 7, 'min_child_weight': 7.320479695283187, 'subsample': 0.7460747360522432, 'colsample_bytree': 0.7882293720083653, 'gamma': 1.212620360204875, 'reg_alpha': 0.007989384654088319, 'reg_lambda': 0.2094503113106978}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:47,461] Trial 21 finished with value: 0.45603915062451805 and parameters: {'learning_rate': 0.10158897249458328, 'max_depth': 5, 'min_child_weight': 4.828482442538415, 'subsample': 0.8203007546790928, 'colsample_bytree': 0.9140325158811934, 'gamma': 0.8893945856481018, 'reg_alpha': 0.03769861416186484, 'reg_lambda': 1.8152407948001104}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:44:56,184] Trial 22 finished with value: 0.4740679013581583 and parameters: {'learning_rate': 0.0783675694440378, 'max_depth': 4, 'min_child_weight': 9.79161037255636, 'subsample': 0.864408237085189, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.4601823294108962, 'reg_alpha': 0.0012818445356957326, 'reg_lambda': 0.2537590124114626}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:04,771] Trial 23 finished with value: 0.4540965988463496 and parameters: {'learning_rate': 0.08232323093252338, 'max_depth': 4, 'min_child_weight': 9.37668908467671, 'subsample': 0.8863854619661737, 'colsample_bytree': 0.7224584873106381, 'gamma': 0.48458951504998526, 'reg_alpha': 0.0018922246873457685, 'reg_lambda': 0.2503662818064834}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:12,722] Trial 24 finished with value: 0.46871405879371003 and parameters: {'learning_rate': 0.07220914023184906, 'max_depth': 3, 'min_child_weight': 6.478267349579329, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.7023486227822291, 'gamma': 1.5968046283026516, 'reg_alpha': 0.0013608936276482122, 'reg_lambda': 0.02972846053320697}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:22,929] Trial 25 finished with value: 0.43839942534550363 and parameters: {'learning_rate': 0.046719380282814145, 'max_depth': 4, 'min_child_weight': 7.828961427565586, 'subsample': 0.9374132580549379, 'colsample_bytree': 0.8592155789820901, 'gamma': 0.5321536705324239, 'reg_alpha': 0.00024144624475957153, 'reg_lambda': 9.628953846559758}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:34,044] Trial 26 finished with value: 0.4680584049507546 and parameters: {'learning_rate': 0.1172188719947062, 'max_depth': 8, 'min_child_weight': 9.549297298641072, 'subsample': 0.9950275800498969, 'colsample_bytree': 0.7793603136206904, 'gamma': 0.26633596657340286, 'reg_alpha': 0.010330790272053435, 'reg_lambda': 1.2949575262949025}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:45,236] Trial 27 finished with value: 0.46718038648546817 and parameters: {'learning_rate': 0.06395372072447483, 'max_depth': 6, 'min_child_weight': 5.882120288390302, 'subsample': 0.7580785394426199, 'colsample_bytree': 0.8109724685273204, 'gamma': 0.6730175256517305, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 0.33359305167348374}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:45:53,643] Trial 28 finished with value: 0.4729204367863593 and parameters: {'learning_rate': 0.16079469645252256, 'max_depth': 4, 'min_child_weight': 8.02563882139109, 'subsample': 0.8744801567634972, 'colsample_bytree': 0.8855384406796288, 'gamma': 0.32949250772516125, 'reg_alpha': 0.027582032103009375, 'reg_lambda': 0.05265330035118498}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:05,797] Trial 29 finished with value: 0.43260633820556854 and parameters: {'learning_rate': 0.03958874062146549, 'max_depth': 5, 'min_child_weight': 3.806532535737354, 'subsample': 0.8042324858240751, 'colsample_bytree': 0.760005063649962, 'gamma': 0.33660024223024065, 'reg_alpha': 0.00047130060461607917, 'reg_lambda': 4.1889264422097545}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:12,864] Trial 30 finished with value: 0.4767966527146402 and parameters: {'learning_rate': 0.11460642471199127, 'max_depth': 3, 'min_child_weight': 6.228163624844928, 'subsample': 0.8384474419166692, 'colsample_bytree': 0.7113089070094042, 'gamma': 1.1529499247077486, 'reg_alpha': 0.0010023235842387384, 'reg_lambda': 0.10540734436228827}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:20,377] Trial 31 finished with value: 0.47171112181577785 and parameters: {'learning_rate': 0.11594258428141073, 'max_depth': 3, 'min_child_weight': 9.840805196789299, 'subsample': 0.8394379019799262, 'colsample_bytree': 0.7121089788851123, 'gamma': 1.9877595682663847, 'reg_alpha': 0.0007991759241585593, 'reg_lambda': 0.10339254614093422}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:28,902] Trial 32 finished with value: 0.45896954960520614 and parameters: {'learning_rate': 0.08922923736144861, 'max_depth': 4, 'min_child_weight': 8.164826486614043, 'subsample': 0.8444170063774857, 'colsample_bytree': 0.7244459665490421, 'gamma': 1.0590678308505308, 'reg_alpha': 0.004317567794266512, 'reg_lambda': 0.36651549181044196}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:36,576] Trial 33 finished with value: 0.47327410890475985 and parameters: {'learning_rate': 0.11054232524279026, 'max_depth': 3, 'min_child_weight': 6.192560496207007, 'subsample': 0.9305490300151547, 'colsample_bytree': 0.7646906320213158, 'gamma': 1.4470417902682378, 'reg_alpha': 0.0013778988208209678, 'reg_lambda': 1.445120742391963}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:44,520] Trial 34 finished with value: 0.46296937152181616 and parameters: {'learning_rate': 0.13780746933865368, 'max_depth': 4, 'min_child_weight': 7.349901368394379, 'subsample': 0.8842196514498832, 'colsample_bytree': 0.741208469698218, 'gamma': 0.009817863125296589, 'reg_alpha': 0.00023602699472769008, 'reg_lambda': 0.012533014069101272}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:46:51,626] Trial 35 finished with value: 0.46049145319463947 and parameters: {'learning_rate': 0.18145810617660424, 'max_depth': 3, 'min_child_weight': 8.383270722868403, 'subsample': 0.7710827277998954, 'colsample_bytree': 0.8153710244079824, 'gamma': 1.8410342195645404, 'reg_alpha': 0.007350668678041615, 'reg_lambda': 0.09243535364756106}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:47:00,951] Trial 36 finished with value: 0.4412839780634319 and parameters: {'learning_rate': 0.07833089691835869, 'max_depth': 5, 'min_child_weight': 9.999978053662037, 'subsample': 0.7322694937695796, 'colsample_bytree': 0.7017742055627695, 'gamma': 1.264224003947366, 'reg_alpha': 0.0005760513769031425, 'reg_lambda': 0.0044054856338788025}. Best is trial 6 with value: 0.4882786735492676.
[I 2026-04-10 10:47:08,437] Trial 37 finished with value: 0.49131527614659554 and parameters: {'learning_rate': 0.16402975050381152, 'max_depth': 3, 'min_child_weight': 5.564741710209645, 'subsample': 0.8433561802463895, 'colsample_bytree': 0.7663837831433489, 'gamma': 0.16052449657914786, 'reg_alpha': 0.0021898360994558894, 'reg_lambda': 0.43389674523284344}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:47:19,686] Trial 38 finished with value: 0.46905332961304014 and parameters: {'learning_rate': 0.1684333457262146, 'max_depth': 7, 'min_child_weight': 4.407366687472745, 'subsample': 0.8411020755119787, 'colsample_bytree': 0.7674583826989784, 'gamma': 0.2090164223958043, 'reg_alpha': 0.01651128181991703, 'reg_lambda': 0.04111614744110114}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:47:28,995] Trial 39 finished with value: 0.4889143266661419 and parameters: {'learning_rate': 0.1690719157036032, 'max_depth': 8, 'min_child_weight': 5.594794647614693, 'subsample': 0.806443983688922, 'colsample_bytree': 0.7996395421646056, 'gamma': 1.6462389564096043, 'reg_alpha': 0.043112054853291476, 'reg_lambda': 0.5517705681697425}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:47:36,783] Trial 40 finished with value: 0.45579395141420465 and parameters: {'learning_rate': 0.16232280877500746, 'max_depth': 3, 'min_child_weight': 5.65473863182806, 'subsample': 0.7988076914577151, 'colsample_bytree': 0.7951717687281481, 'gamma': 1.7315612196978645, 'reg_alpha': 0.05713673641935538, 'reg_lambda': 0.9351263307152171}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:47:46,087] Trial 41 finished with value: 0.47161164068109107 and parameters: {'learning_rate': 0.196732933352168, 'max_depth': 8, 'min_child_weight': 3.437972807368656, 'subsample': 0.8143010972858565, 'colsample_bytree': 0.8432218980507085, 'gamma': 1.5836201340879064, 'reg_alpha': 0.09856798170717498, 'reg_lambda': 0.38433163821485095}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:47:56,115] Trial 42 finished with value: 0.46651460769374076 and parameters: {'learning_rate': 0.1286694081834426, 'max_depth': 8, 'min_child_weight': 4.8945354882087395, 'subsample': 0.7751223869671157, 'colsample_bytree': 0.8658040341314212, 'gamma': 1.8002668896283258, 'reg_alpha': 0.20175044679770393, 'reg_lambda': 0.13463299366272646}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:48:05,724] Trial 43 finished with value: 0.4720515110343636 and parameters: {'learning_rate': 0.1464703288761579, 'max_depth': 7, 'min_child_weight': 2.727554303836472, 'subsample': 0.8307115866279534, 'colsample_bytree': 0.8282566004224481, 'gamma': 1.8549755735212676, 'reg_alpha': 0.0026595809946110666, 'reg_lambda': 0.5313110635287279}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:48:15,665] Trial 44 finished with value: 0.4673504429118573 and parameters: {'learning_rate': 0.1736975397021044, 'max_depth': 6, 'min_child_weight': 6.443134196607404, 'subsample': 0.7956473589761388, 'colsample_bytree': 0.7991576247493136, 'gamma': 1.176401583947662, 'reg_alpha': 0.00556462485926343, 'reg_lambda': 4.339335008734703}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:48:27,091] Trial 45 finished with value: 0.4477920526045175 and parameters: {'learning_rate': 0.10555801192223206, 'max_depth': 8, 'min_child_weight': 4.3584453692245715, 'subsample': 0.762832148284882, 'colsample_bytree': 0.7551642934244417, 'gamma': 1.5539917890327812, 'reg_alpha': 0.0141594511062643, 'reg_lambda': 2.115660425364487}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:48:43,436] Trial 46 finished with value: 0.4405798462643354 and parameters: {'learning_rate': 0.026618052617827792, 'max_depth': 8, 'min_child_weight': 5.401189449644858, 'subsample': 0.8485359084072739, 'colsample_bytree': 0.7761938807285488, 'gamma': 1.9067631578072435, 'reg_alpha': 0.48811983908954726, 'reg_lambda': 0.05683047544928256}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:48:53,369] Trial 47 finished with value: 0.46234298964123144 and parameters: {'learning_rate': 0.12652310739790362, 'max_depth': 6, 'min_child_weight': 6.771917283818522, 'subsample': 0.7827294357299172, 'colsample_bytree': 0.7337547765540192, 'gamma': 1.4127648590390685, 'reg_alpha': 0.04132148136136755, 'reg_lambda': 0.8090423147609552}. Best is trial 37 with value: 0.49131527614659554.
[I 2026-04-10 10:49:03,317] Trial 48 finished with value: 0.43232799967982516 and parameters: {'learning_rate': 0.15120959338848491, 'max_depth': 7, 'min_child_weight': 2.0271005066004473, 'subsample': 0.8565509110782262, 'colsample_bytree': 0.900366255481246, 'gamma': 0.8302066467137484, 'reg_alpha': 0.840019337386767, 'reg_lambda': 0.174775614578045}. Best is trial 37 with value: 0.49131527614659554.

[I 2026-04-10 10:56:33,261] A new study created in memory with name: binary_catboost

[I 2026-04-10 10:56:33,258] Trial 99 finished with value: 0.46351491951869184 and parameters: {'learning_rate': 0.14509504670653056, 'max_depth': 3, 'min_child_weight': 4.023848902344339, 'subsample': 0.9216939896009595, 'colsample_bytree': 0.9259424185524792, 'gamma': 1.5994417835042247, 'reg_alpha': 0.01143449415929899, 'reg_lambda': 0.2911989932804193}. Best is trial 37 with value: 0.49131527614659554.

Best model (xgb) CV score: 0.49132
Best params: {'learning_rate': 0.16402975050381152, 'max_depth': 3, 'min_child_weight': 5.564741710209645, 'subsample': 0.8433561802463895, 'colsample_bytree': 0.7663837831433489, 'gamma': 0.16052449657914786, 'reg_alpha': 0.0021898360994558894, 'reg_lambda': 0.43389674523284344}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 10:56:44,262] Trial 0 finished with value: 0.47006000831659867 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.47006000831659867.
[I 2026-04-10 10:57:05,608] Trial 1 finished with value: 0.4711802342739021 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4711802342739021.
[I 2026-04-10 10:57:21,894] Trial 2 finished with value: 0.4821368120270315 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4821368120270315.
[I 2026-04-10 10:57:55,534] Trial 3 finished with value: 0.4860166768428823 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.4860166768428823.
[I 2026-04-10 10:58:36,823] Trial 4 finished with value: 0.512404236695967 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 10:59:37,907] Trial 5 finished with value: 0.4876235488812898 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:00:14,375] Trial 6 finished with value: 0.4671264067690501 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:01:08,101] Trial 7 finished with value: 0.4605878361645217 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:02:27,237] Trial 8 finished with value: 0.4409952751428613 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:02:53,808] Trial 9 finished with value: 0.47800263576805313 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:03:02,235] Trial 10 finished with value: 0.4781335293738508 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:03:45,820] Trial 11 finished with value: 0.5015288951462304 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17040099770125652, 'depth': 8, 'l2_leaf_reg': 3.747473826638779, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12665706747865135}. Best is trial 4 with value: 0.512404236695967.
[I 2026-04-10 11:04:25,871] Trial 12 finished with value: 0.5283468822607105 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 2.6880148841981213, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.566664895898511}. Best is trial 12 with value: 0.5283468822607105.
[I 2026-04-10 11:05:08,770] Trial 13 finished with value: 0.5186094631606972 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 8, 'l2_leaf_reg': 2.3484710269750506, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9139832467937251}. Best is trial 12 with value: 0.5283468822607105.
[I 2026-04-10 11:05:32,195] Trial 14 finished with value: 0.5223016006098615 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1162415606552535, 'depth': 7, 'l2_leaf_reg': 2.8315286074484805, 'random_strength': 0.252013748684086, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9102734222494313}. Best is trial 12 with value: 0.5283468822607105.
[I 2026-04-10 11:05:45,434] Trial 15 finished with value: 0.5302225660556894 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12725930491366905, 'depth': 6, 'l2_leaf_reg': 3.04155704323224, 'random_strength': 0.2483631178055416, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.1476548084452305}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:05:59,693] Trial 16 finished with value: 0.5010191479009833 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13079296705117346, 'depth': 6, 'l2_leaf_reg': 6.302008546180917, 'random_strength': 0.4279734494566218, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.4063432980469533}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:06:08,784] Trial 17 finished with value: 0.474446784484116 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14275466267871886, 'depth': 5, 'l2_leaf_reg': 1.0511092432010225, 'random_strength': 0.15553226230154732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.0055084444478573}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:06:17,736] Trial 18 finished with value: 0.5154771414538175 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19967953135609368, 'depth': 5, 'l2_leaf_reg': 2.9559607834840995, 'random_strength': 0.2641707342828546, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.5656973048804599}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:06:28,149] Trial 19 finished with value: 0.4838987850123905 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05192304823622825, 'depth': 5, 'l2_leaf_reg': 5.43267490798305, 'random_strength': 0.36808163042855613, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.002692084722570015}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:06:54,091] Trial 20 finished with value: 0.49838198304517667 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10506191103345666, 'depth': 7, 'l2_leaf_reg': 3.339474334379472, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.0234813714065307}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:07:18,341] Trial 21 finished with value: 0.5140757420568298 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10778620373234754, 'depth': 7, 'l2_leaf_reg': 2.77042352029848, 'random_strength': 0.25102386345387556, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9964803502561563}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:07:32,573] Trial 22 finished with value: 0.46648658569996576 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1423909161787617, 'depth': 6, 'l2_leaf_reg': 2.4974494794192017, 'random_strength': 0.10744380734998016, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 3.9313293138673977}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:07:56,073] Trial 23 finished with value: 0.5143573192304922 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1537973302669925, 'depth': 7, 'l2_leaf_reg': 1.460632421057667, 'random_strength': 0.23529729566574883, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8505309697318253}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:08:11,033] Trial 24 finished with value: 0.4979639104946543 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11940407810144651, 'depth': 6, 'l2_leaf_reg': 2.0837699629914046, 'random_strength': 0.3545509037819315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.9682268662157292}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:08:47,777] Trial 25 finished with value: 0.4834263874754723 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05829916383468929, 'depth': 7, 'l2_leaf_reg': 3.451669656729292, 'random_strength': 0.520822867375887, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.7717663137121602}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:09:33,534] Trial 26 finished with value: 0.5112545286179 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09592866223005314, 'depth': 8, 'l2_leaf_reg': 4.955507548938064, 'random_strength': 0.0560360897098804, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8505740585666579}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:09:56,296] Trial 27 finished with value: 0.4672007008697747 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.032268980599861455, 'depth': 6, 'l2_leaf_reg': 1.3113336584034643, 'random_strength': 0.19601935922458713, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 2.0482237577453426}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:10:19,819] Trial 28 finished with value: 0.49635482374992035 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19676464874096314, 'depth': 7, 'l2_leaf_reg': 2.376660340187491, 'random_strength': 0.416223007986702, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9960251179196212}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:11:15,317] Trial 29 finished with value: 0.49659352880840635 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11455963653644612, 'depth': 8, 'l2_leaf_reg': 2.0159745042886117, 'random_strength': 0.12115872780470982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.4508923671465133}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:11:22,502] Trial 30 finished with value: 0.47134972167952216 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06893925713040859, 'depth': 4, 'l2_leaf_reg': 6.128804030474622, 'random_strength': 0.3160995006630638, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.5408149476615461}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:12:08,110] Trial 31 finished with value: 0.5275092138760185 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15447775230228997, 'depth': 8, 'l2_leaf_reg': 2.9904527120001583, 'random_strength': 0.00476165546190499, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9056381390715453}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:12:50,373] Trial 32 finished with value: 0.5082239962946701 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15301043535225084, 'depth': 8, 'l2_leaf_reg': 2.9295427035130492, 'random_strength': 0.19135493859180747, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8965939046344106}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:13:37,581] Trial 33 finished with value: 0.5058279294540231 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16272805519276534, 'depth': 8, 'l2_leaf_reg': 3.76291197670585, 'random_strength': 0.052234999700172494, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8311320016818377}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:14:03,890] Trial 34 finished with value: 0.50855023643166 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08948658156444385, 'depth': 7, 'l2_leaf_reg': 4.127763761429549, 'random_strength': 0.1282426986240161, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9397502626023202}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:14:17,294] Trial 35 finished with value: 0.49581001256685076 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1364022915231537, 'depth': 6, 'l2_leaf_reg': 3.2222142888320775, 'random_strength': 0.07319768042028194, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8823505978182284}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:15:32,283] Trial 36 finished with value: 0.48862288321705016 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0369055818079162, 'depth': 8, 'l2_leaf_reg': 1.831165826242227, 'random_strength': 0.1910288785593165, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.800377135725997}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:15:57,157] Trial 37 finished with value: 0.5070775615038341 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1739434669338095, 'depth': 7, 'l2_leaf_reg': 7.863600076760807, 'random_strength': 0.003719164687551285, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9638054808300491}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:16:39,412] Trial 38 finished with value: 0.5147373474303037 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.120232136528205, 'depth': 8, 'l2_leaf_reg': 2.413363199093771, 'random_strength': 0.09403394384446662, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8869609416159823}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:17:08,896] Trial 39 finished with value: 0.48837494878247 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08573205116272525, 'depth': 7, 'l2_leaf_reg': 1.527024074575116, 'random_strength': 0.3321318072153522, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4330896819303987}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:17:54,909] Trial 40 finished with value: 0.5044491344002833 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09995955278440068, 'depth': 8, 'l2_leaf_reg': 4.230316284870407, 'random_strength': 0.6057649066230499, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8017068196168917}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:18:38,201] Trial 41 finished with value: 0.5102062427069747 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1289863162621931, 'depth': 8, 'l2_leaf_reg': 2.2854880075084423, 'random_strength': 0.004023652715598963, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9193014071933295}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:19:20,076] Trial 42 finished with value: 0.5274070035695051 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15232083841101737, 'depth': 8, 'l2_leaf_reg': 2.6795491082056344, 'random_strength': 0.0434547466412623, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9065477559296746}. Best is trial 15 with value: 0.5302225660556894.
[I 2026-04-10 11:20:01,686] Trial 43 finished with value: 0.5319554140626388 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18908814802069318, 'depth': 8, 'l2_leaf_reg': 2.6446572731499307, 'random_strength': 0.05775459701402475, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8616641588419969}. Best is trial 43 with value: 0.5319554140626388.
[I 2026-04-10 11:20:45,489] Trial 44 finished with value: 0.4999262522116481 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18663046515975554, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.04934310560127659, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8616570745957896}. Best is trial 43 with value: 0.5319554140626388.

                                        feature  importance
183           eye__fix_duration_AOI_FD_Neg1_sum    0.211869
184         eye__fix_duration_AOI_FD_Neg1_count    0.175976
60        eye__sac_speed_AOI_aggregated_Pos_min    0.125013
1027               PID__PID_C5_data_energy_mean    0.095398
486                PID__PID_Cz_first_deriv_mean    0.082541
471               PID__PID_AF4_first_deriv_mean    0.062193
547               PID__PID_Cz_second_deriv_mean    0.058344
278   eye__fix_duration_AOI_aggregated_Pos_mean    0.056507
572               PID__PID_P1_second_deriv_mean    0.051354
577               PID__PID_P6_second_deriv_mean    0.032128
1022              PID__PID_AF8_data_energy_mean    0.024344
419          eye__lam_euclidean_length_2_rho_50    0.024333
15                      eye__sac_angle_to_x_min    0.000000
16                      eye__sac_angle_to_x_max    0.000000
17                     eye__sac_angle_to_x_mean    0.000000
18                   eye__sac_angle_to_x_median    0.000000
19                      eye__sac_angle_to_x_std    0.000000
20                 eye__sac_angle_to_x_kurtosis    0.000000
21                     eye__sac_angle_to_x_skew    0.000000
22                   eye__sac_angle_between_min    0.000000
23                   eye__sac_angle_between_max    0.000000
1023               PID__PID_C1_data_energy_mean    0.000000
55      eye__sac_length_AOI_aggregated_Pos_mean    0.000000
1055              PID__PID_Fpz_data_energy_mean    0.000000
1047              PID__PID_FC4_data_energy_mean    0.000000
31      eye__sac_length_AOI_aggregated_Neg_mean    0.000000
1079              PID__PID_TP8_data_energy_mean    0.000000
0                           eye__sac_length_min    0.000000
1                           eye__sac_length_max    0.000000
2                          eye__sac_length_mean    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.56718
              precision    recall  f1-score   support

           0       0.70      0.87      0.78       306
           1       0.52      0.27      0.36       155

    accuracy                           0.67       461
   macro avg       0.61      0.57      0.57       461
weighted avg       0.64      0.67      0.64       461

Confusion matrix:
 [[267  39]
 [113  42]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
184          eye__fix_duration_AOI_FD_Neg1_count   11.396639
60         eye__sac_speed_AOI_aggregated_Pos_min   11.155772
53        eye__sac_length_AOI_aggregated_Pos_min    8.718672
183            eye__fix_duration_AOI_FD_Neg1_sum    8.150618
34        eye__sac_length_AOI_aggregated_Neg_sum    6.879980
504                PID__PID_Fp1_first_deriv_mean    5.955926
478                 PID__PID_C5_first_deriv_mean    4.638320
649              PID__PID_T7_first_integral_mean    3.658401
464                                eye__imf0_min    3.580396
814          PID__PID_O2_first_deriv_energy_mean    3.573841
386                 eye__corr_dim_m_4_tau_2_r_50    3.478968
492                 PID__PID_F6_first_deriv_mean    3.441145
421   eye__rec_metric_euclidean_length_2_rho_250    3.282161
849        PID__PID_CP4_second_deriv_energy_mean    3.084192
806         PID__PID_FCz_first_deriv_energy_mean    3.000211
585               PID__PID_PO8_second_deriv_mean    2.977299
856         PID__PID_F4_second_deriv_energy_mean    2.353569
167                        eye__fix_duration_max    2.294415
804         PID__PID_FC5_first_deriv_energy_mean    2.120971
18                    eye__sac_angle_to_x_median    1.904835
213            eye__fix_duration_AOI_FD_Pos1_sum    1.768595
776         PID__PID_AF4_first_deriv_energy_mean    1.586245
837        PID__PID_AF4_second_deriv_energy_mean    0.998829
22                    eye__sac_angle_between_min    0.000000
23                    eye__sac_angle_between_max    0.000000
1023                PID__PID_C1_data_energy_mean    0.000000
55       eye__sac_length_AOI_aggregated_Pos_mean    0.000000
1055               PID__PID_Fpz_data_energy_mean    0.000000
1047               PID__PID_FC4_data_energy_mean    0.000000
31       eye__sac_length_AOI_aggregated_Neg_mean    0.000000

[I 2026-04-10 11:25:03,803] A new study created in memory with name: multiclass_xgb

[PID] rows missing after index match -> train: 1832, test: 187

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST
X_train: (4146, 1080), X_test: (461, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 11:25:37,921] Trial 0 finished with value: 0.6689807502948794 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:26:06,408] Trial 1 finished with value: 0.6553499518925888 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:26:47,918] Trial 2 finished with value: 0.6598781742104046 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:27:11,841] Trial 3 finished with value: 0.6672103291837501 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:27:36,830] Trial 4 finished with value: 0.658999073458042 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:28:16,099] Trial 5 finished with value: 0.6625789167610322 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:28:30,946] Trial 6 finished with value: 0.6646877681376454 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:29:19,463] Trial 7 finished with value: 0.6624203885708789 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:29:42,644] Trial 8 finished with value: 0.656150067463615 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:30:56,313] Trial 9 finished with value: 0.6620338168331493 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.6689807502948794.
[I 2026-04-10 11:31:24,473] Trial 10 finished with value: 0.670379382229132 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 10 with value: 0.670379382229132.
[I 2026-04-10 11:31:53,954] Trial 11 finished with value: 0.6707989991345585 and parameters: {'learning_rate': 0.050044732845096966, 'max_depth': 3, 'min_child_weight': 2.350150709689129, 'subsample': 0.7005578980255978, 'colsample_bytree': 0.8260781920528338, 'gamma': 0.5892553864010996, 'reg_alpha': 0.00014565587242354827, 'reg_lambda': 6.69351503516026}. Best is trial 11 with value: 0.6707989991345585.
[I 2026-04-10 11:32:21,477] Trial 12 finished with value: 0.668195669605669 and parameters: {'learning_rate': 0.06208010340123145, 'max_depth': 3, 'min_child_weight': 2.2037205970521683, 'subsample': 0.7008546103358549, 'colsample_bytree': 0.8389293880967175, 'gamma': 0.5196431454502325, 'reg_alpha': 0.000107858142176364, 'reg_lambda': 8.615341223564362}. Best is trial 11 with value: 0.6707989991345585.
[I 2026-04-10 11:32:59,387] Trial 13 finished with value: 0.6604025261633807 and parameters: {'learning_rate': 0.03584405138383709, 'max_depth': 3, 'min_child_weight': 1.0764439920962336, 'subsample': 0.7412811968694027, 'colsample_bytree': 0.8321491384813121, 'gamma': 0.5204131854130056, 'reg_alpha': 0.0006800006465266606, 'reg_lambda': 9.500746988982208}. Best is trial 11 with value: 0.6707989991345585.
[I 2026-04-10 11:33:56,836] Trial 14 finished with value: 0.6701673563032842 and parameters: {'learning_rate': 0.020318895291643095, 'max_depth': 4, 'min_child_weight': 2.4495967734910398, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8880624944018081, 'gamma': 1.3468916294386473, 'reg_alpha': 0.00010017553816456137, 'reg_lambda': 0.8398003912485209}. Best is trial 11 with value: 0.6707989991345585.
[I 2026-04-10 11:34:26,798] Trial 15 finished with value: 0.6764898838797858 and parameters: {'learning_rate': 0.04336611736595831, 'max_depth': 3, 'min_child_weight': 2.5948644840009556, 'subsample': 0.8253715325091303, 'colsample_bytree': 0.8017337204096803, 'gamma': 0.8456489594094208, 'reg_alpha': 0.001694554333420286, 'reg_lambda': 0.00016599250040776937}. Best is trial 15 with value: 0.6764898838797858.
[I 2026-04-10 11:34:55,200] Trial 16 finished with value: 0.6632371104054816 and parameters: {'learning_rate': 0.07191563898547705, 'max_depth': 4, 'min_child_weight': 4.725860382448061, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8034550801739322, 'gamma': 0.7717191424338035, 'reg_alpha': 0.0026422550529369726, 'reg_lambda': 0.008593003551665814}. Best is trial 15 with value: 0.6764898838797858.
[I 2026-04-10 11:35:35,989] Trial 17 finished with value: 0.6776133132755675 and parameters: {'learning_rate': 0.026797295253272537, 'max_depth': 3, 'min_child_weight': 2.7085062044185384, 'subsample': 0.8870911863689172, 'colsample_bytree': 0.8805231471216542, 'gamma': 1.3769170463887486, 'reg_alpha': 0.0026161889646800227, 'reg_lambda': 0.0002528955442099275}. Best is trial 17 with value: 0.6776133132755675.
[I 2026-04-10 11:36:22,516] Trial 18 finished with value: 0.6749182600157092 and parameters: {'learning_rate': 0.0271225174609706, 'max_depth': 4, 'min_child_weight': 3.0450943589102124, 'subsample': 0.908135330166006, 'colsample_bytree': 0.8795539425963669, 'gamma': 1.4048951818323814, 'reg_alpha': 0.004826006574368273, 'reg_lambda': 0.00012717420925272599}. Best is trial 17 with value: 0.6776133132755675.
[I 2026-04-10 11:37:03,963] Trial 19 finished with value: 0.6795004663793842 and parameters: {'learning_rate': 0.025618070821313947, 'max_depth': 3, 'min_child_weight': 5.372991445105575, 'subsample': 0.891582127351271, 'colsample_bytree': 0.7832779407298713, 'gamma': 1.2763326476302224, 'reg_alpha': 0.0010639959186754904, 'reg_lambda': 0.0001010866314508922}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:37:51,392] Trial 20 finished with value: 0.6707366760520269 and parameters: {'learning_rate': 0.026476299400112462, 'max_depth': 4, 'min_child_weight': 6.070731033407083, 'subsample': 0.9192446129921864, 'colsample_bytree': 0.9086921765912382, 'gamma': 1.3509121765969363, 'reg_alpha': 0.0006390585349004805, 'reg_lambda': 0.00044247158557228}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:38:27,043] Trial 21 finished with value: 0.6759219916627452 and parameters: {'learning_rate': 0.026386668182949408, 'max_depth': 3, 'min_child_weight': 4.046758993442458, 'subsample': 0.8772495903740531, 'colsample_bytree': 0.7111774891106754, 'gamma': 1.571968939001171, 'reg_alpha': 0.0016491129201535555, 'reg_lambda': 0.00011422337716364987}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:38:59,676] Trial 22 finished with value: 0.6710445881334859 and parameters: {'learning_rate': 0.03923031032040324, 'max_depth': 3, 'min_child_weight': 5.757389528180074, 'subsample': 0.8230105014621976, 'colsample_bytree': 0.7829286654385987, 'gamma': 0.9463679589203879, 'reg_alpha': 0.007635849013197997, 'reg_lambda': 0.0002970534583514371}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:39:45,551] Trial 23 finished with value: 0.6717767378608612 and parameters: {'learning_rate': 0.028271415313006358, 'max_depth': 4, 'min_child_weight': 2.9883642039063343, 'subsample': 0.8785429378804966, 'colsample_bytree': 0.8627154256932144, 'gamma': 1.2078560144530046, 'reg_alpha': 0.013296190417773435, 'reg_lambda': 0.004094712108968314}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:40:30,279] Trial 24 finished with value: 0.6760936414195937 and parameters: {'learning_rate': 0.02269234750054311, 'max_depth': 3, 'min_child_weight': 7.060978512647974, 'subsample': 0.9324584691851526, 'colsample_bytree': 0.8126682432026622, 'gamma': 1.5968046283026516, 'reg_alpha': 0.0015944000796838378, 'reg_lambda': 0.00029075315310401713}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:41:12,008] Trial 25 finished with value: 0.6759786425158802 and parameters: {'learning_rate': 0.03120371759566877, 'max_depth': 4, 'min_child_weight': 1.8696170200172455, 'subsample': 0.8181629067531045, 'colsample_bytree': 0.7710544591762933, 'gamma': 0.8091114251451053, 'reg_alpha': 0.0004160735786649834, 'reg_lambda': 0.00010194188852127875}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:41:44,152] Trial 26 finished with value: 0.6719589732799109 and parameters: {'learning_rate': 0.039950955901647545, 'max_depth': 3, 'min_child_weight': 5.082670430524074, 'subsample': 0.9950275800498969, 'colsample_bytree': 0.8532485536524781, 'gamma': 1.2252382754463076, 'reg_alpha': 0.002033251739315289, 'reg_lambda': 0.0012226035135023876}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:42:52,874] Trial 27 finished with value: 0.6656299931319187 and parameters: {'learning_rate': 0.023866040108828906, 'max_depth': 8, 'min_child_weight': 3.834456396073965, 'subsample': 0.8548697737053434, 'colsample_bytree': 0.7115685703846131, 'gamma': 0.9925717200855599, 'reg_alpha': 0.013065653303278498, 'reg_lambda': 0.00025968993181567276}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:43:19,016] Trial 28 finished with value: 0.6666515316093972 and parameters: {'learning_rate': 0.06043458484801468, 'max_depth': 5, 'min_child_weight': 2.7864262185826254, 'subsample': 0.8886007906125593, 'colsample_bytree': 0.90938580064446, 'gamma': 1.769275214449451, 'reg_alpha': 0.0010679102414720535, 'reg_lambda': 0.0038541675546165115}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:43:50,839] Trial 29 finished with value: 0.6704518297282901 and parameters: {'learning_rate': 0.042065542803975446, 'max_depth': 4, 'min_child_weight': 3.3828390460273656, 'subsample': 0.940960296666434, 'colsample_bytree': 0.762246912320195, 'gamma': 1.4843595225401447, 'reg_alpha': 0.0003126692265060119, 'reg_lambda': 0.0005844774100574882}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:44:46,634] Trial 30 finished with value: 0.6615117105875175 and parameters: {'learning_rate': 0.02912435807529128, 'max_depth': 7, 'min_child_weight': 3.6769941410545988, 'subsample': 0.8070467005175801, 'colsample_bytree': 0.8077337178748415, 'gamma': 1.2347918799663256, 'reg_alpha': 0.04796268779915355, 'reg_lambda': 0.018502244216073403}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:45:33,981] Trial 31 finished with value: 0.6748404367321381 and parameters: {'learning_rate': 0.022228905258126246, 'max_depth': 3, 'min_child_weight': 7.02886807097012, 'subsample': 0.9276934345209528, 'colsample_bytree': 0.8171014388648739, 'gamma': 1.653226578900761, 'reg_alpha': 0.0022911619059839097, 'reg_lambda': 0.00023578933865536615}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:46:15,424] Trial 32 finished with value: 0.6787984832703383 and parameters: {'learning_rate': 0.024534035662560856, 'max_depth': 3, 'min_child_weight': 7.567609698281934, 'subsample': 0.9043806146944121, 'colsample_bytree': 0.7844597421428345, 'gamma': 1.503691921890484, 'reg_alpha': 0.001002567670935824, 'reg_lambda': 0.0009120456207168118}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:46:47,708] Trial 33 finished with value: 0.679152396530563 and parameters: {'learning_rate': 0.03676023486750346, 'max_depth': 3, 'min_child_weight': 7.474185854738012, 'subsample': 0.9576100684558987, 'colsample_bytree': 0.790388555577509, 'gamma': 1.4783501460134627, 'reg_alpha': 0.00025045873825809453, 'reg_lambda': 0.000783279514204742}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:47:24,690] Trial 34 finished with value: 0.6659083189548024 and parameters: {'learning_rate': 0.0349674970785086, 'max_depth': 4, 'min_child_weight': 7.623433009486479, 'subsample': 0.9590544915483314, 'colsample_bytree': 0.7773336624741368, 'gamma': 1.4716210523643758, 'reg_alpha': 0.000237083273740977, 'reg_lambda': 0.0016000928985202517}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:48:07,654] Trial 35 finished with value: 0.6794093888146713 and parameters: {'learning_rate': 0.024382796783133456, 'max_depth': 3, 'min_child_weight': 5.277069059118097, 'subsample': 0.9083150483469142, 'colsample_bytree': 0.7512081773095469, 'gamma': 1.7235456086058878, 'reg_alpha': 0.0006223663526674902, 'reg_lambda': 0.000841874073265976}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:48:50,373] Trial 36 finished with value: 0.6630653260679191 and parameters: {'learning_rate': 0.024780042885738658, 'max_depth': 4, 'min_child_weight': 9.999978053662037, 'subsample': 0.9537328215716407, 'colsample_bytree': 0.7262205835194464, 'gamma': 1.7726521391628696, 'reg_alpha': 9.849954646989671, 'reg_lambda': 0.0008350033803468739}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:49:07,144] Trial 37 finished with value: 0.6702640766170042 and parameters: {'learning_rate': 0.13901036356689667, 'max_depth': 3, 'min_child_weight': 5.349758260595568, 'subsample': 0.9082942015205822, 'colsample_bytree': 0.7582999827290754, 'gamma': 1.9539929868484127, 'reg_alpha': 0.0007534387233263059, 'reg_lambda': 0.003518284199012031}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:49:58,249] Trial 38 finished with value: 0.6585487599881789 and parameters: {'learning_rate': 0.03084253978527317, 'max_depth': 7, 'min_child_weight': 6.709491698652845, 'subsample': 0.9785441762853213, 'colsample_bytree': 0.7884986099852597, 'gamma': 1.7001926800022917, 'reg_alpha': 0.00028102844994225225, 'reg_lambda': 0.000760306778247008}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:50:38,690] Trial 39 finished with value: 0.6620715012931564 and parameters: {'learning_rate': 0.03570505702852336, 'max_depth': 5, 'min_child_weight': 8.241463845427335, 'subsample': 0.8656725185354252, 'colsample_bytree': 0.7286104779550227, 'gamma': 1.5309761784282971, 'reg_alpha': 0.0004290967959408014, 'reg_lambda': 0.01656724439815745}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:51:32,563] Trial 40 finished with value: 0.6720696758538309 and parameters: {'learning_rate': 0.022455388677414194, 'max_depth': 4, 'min_child_weight': 4.260914535269948, 'subsample': 0.9726601098863613, 'colsample_bytree': 0.7442391500359362, 'gamma': 1.9120262961365149, 'reg_alpha': 0.004831425170463477, 'reg_lambda': 0.002323081369765115}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:52:24,681] Trial 41 finished with value: 0.6769816216651221 and parameters: {'learning_rate': 0.020178716669159883, 'max_depth': 3, 'min_child_weight': 6.144948814928545, 'subsample': 0.8962059272749594, 'colsample_bytree': 0.7570405763732926, 'gamma': 1.3883724577918681, 'reg_alpha': 0.0009507784656250235, 'reg_lambda': 0.000499609385808323}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:53:10,675] Trial 42 finished with value: 0.6773602175201205 and parameters: {'learning_rate': 0.024951495157735593, 'max_depth': 3, 'min_child_weight': 4.676504823038493, 'subsample': 0.9133967648974284, 'colsample_bytree': 0.7940181832429473, 'gamma': 1.1330986139890966, 'reg_alpha': 0.004201437417794996, 'reg_lambda': 0.0010362409035891845}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:53:26,688] Trial 43 finished with value: 0.6643113149316847 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 3, 'min_child_weight': 7.933650085123017, 'subsample': 0.94200567617356, 'colsample_bytree': 0.9996533142159789, 'gamma': 1.2902084523849082, 'reg_alpha': 0.00020360031155308855, 'reg_lambda': 0.0004005024404847482}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:54:03,186] Trial 44 finished with value: 0.6676878931468793 and parameters: {'learning_rate': 0.03142380392425442, 'max_depth': 3, 'min_child_weight': 9.973033167728879, 'subsample': 0.8799836922859791, 'colsample_bytree': 0.7756793203266555, 'gamma': 1.6922377673929236, 'reg_alpha': 0.0008783649136414758, 'reg_lambda': 0.0001964631188849961}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:54:42,356] Trial 45 finished with value: 0.6787318400395037 and parameters: {'learning_rate': 0.028384017875288183, 'max_depth': 3, 'min_child_weight': 5.622449219831643, 'subsample': 0.8990737564883508, 'colsample_bytree': 0.7011103042194107, 'gamma': 1.4568202883096055, 'reg_alpha': 0.00037613201983813254, 'reg_lambda': 0.007301762075106772}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:55:03,331] Trial 46 finished with value: 0.6745087221729958 and parameters: {'learning_rate': 0.08454065662958099, 'max_depth': 3, 'min_child_weight': 6.473735899775146, 'subsample': 0.86082925064785, 'colsample_bytree': 0.7043554471760359, 'gamma': 1.4704607503190839, 'reg_alpha': 0.0004935428171005276, 'reg_lambda': 0.0068747687256912795}. Best is trial 19 with value: 0.6795004663793842.
[I 2026-04-10 11:55:29,619] Trial 47 finished with value: 0.6724979079120976 and parameters: {'learning_rate': 0.05447674702519796, 'max_depth': 4, 'min_child_weight': 5.460340046593587, 'subsample': 0.9240368208862885, 'colsample_bytree': 0.7360614172158959, 'gamma': 1.60618998782483, 'reg_alpha': 0.00018213405554823442, 'reg_lambda': 0.12798868145855913}. Best is trial 19 with value: 0.6795004663793842.

[I 2026-04-10 12:28:19,007] A new study created in memory with name: multiclass_catboost

[I 2026-04-10 12:28:19,004] Trial 99 finished with value: 0.68286328593151 and parameters: {'learning_rate': 0.021748786584157253, 'max_depth': 3, 'min_child_weight': 5.576886651451907, 'subsample': 0.9353259528315623, 'colsample_bytree': 0.7342279405732629, 'gamma': 1.7343143371829373, 'reg_alpha': 0.00017979236512815383, 'reg_lambda': 0.18057196546557824}. Best is trial 99 with value: 0.68286328593151.

Best model (xgb) CV score: 0.68286
Best params: {'learning_rate': 0.021748786584157253, 'max_depth': 3, 'min_child_weight': 5.576886651451907, 'subsample': 0.9353259528315623, 'colsample_bytree': 0.7342279405732629, 'gamma': 1.7343143371829373, 'reg_alpha': 0.00017979236512815383, 'reg_lambda': 0.18057196546557824}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 12:28:49,458] Trial 0 finished with value: 0.6629756201561514 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6629756201561514.
[I 2026-04-10 12:30:01,919] Trial 1 finished with value: 0.676918730761628 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.676918730761628.
[I 2026-04-10 12:31:01,616] Trial 2 finished with value: 0.6824481556606999 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:33:09,914] Trial 3 finished with value: 0.6703674307026848 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:35:59,659] Trial 4 finished with value: 0.6618644970639259 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:40:50,789] Trial 5 finished with value: 0.6646892683768433 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:42:42,180] Trial 6 finished with value: 0.6750954697076252 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:45:49,894] Trial 7 finished with value: 0.6655353184974736 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:53:42,248] Trial 8 finished with value: 0.6564104208158815 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 2 with value: 0.6824481556606999.
[I 2026-04-10 12:55:10,350] Trial 9 finished with value: 0.6856581259381134 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 12:55:33,228] Trial 10 finished with value: 0.6805796222185839 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15550029108275915, 'depth': 5, 'l2_leaf_reg': 1.2809979042149076, 'random_strength': 0.9947887102560302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9526058892396143}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 12:56:41,797] Trial 11 finished with value: 0.6798098273702832 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04305859697474522, 'depth': 6, 'l2_leaf_reg': 4.7987227278603894, 'random_strength': 0.4258355123760916, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.610132565398292}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 12:58:54,286] Trial 12 finished with value: 0.6837860568142399 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.037332033986380006, 'depth': 7, 'l2_leaf_reg': 2.7728115183376625, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8686828876459834}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 13:01:45,512] Trial 13 finished with value: 0.6812229348455517 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03383769175128965, 'depth': 7, 'l2_leaf_reg': 2.629249930915953, 'random_strength': 0.9924481806327542, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8986405911929543}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 13:02:56,963] Trial 14 finished with value: 0.6703540587921251 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12255376550219486, 'depth': 7, 'l2_leaf_reg': 1.0032083071393918, 'random_strength': 0.7979387716527236, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8507133185741099}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 13:03:46,003] Trial 15 finished with value: 0.681209956197406 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05844684424268191, 'depth': 6, 'l2_leaf_reg': 2.5091649733870947, 'random_strength': 0.8684748238717221, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8556243242261268}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 13:04:27,924] Trial 16 finished with value: 0.68204229582792 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03056176507536318, 'depth': 5, 'l2_leaf_reg': 2.9354741760257905, 'random_strength': 0.6037211866313934, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 9 with value: 0.6856581259381134.
[I 2026-04-10 13:05:38,783] Trial 17 finished with value: 0.6859188123945029 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10591704030318361, 'depth': 7, 'l2_leaf_reg': 1.0344675917789714, 'random_strength': 0.8591548648914785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6139089554995273}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:06:03,498] Trial 18 finished with value: 0.6782554409324151 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12578874207371252, 'depth': 5, 'l2_leaf_reg': 1.099836257457014, 'random_strength': 0.8561000968592354, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6090721630062388}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:09:59,473] Trial 19 finished with value: 0.6752798167422803 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10225426413630351, 'depth': 8, 'l2_leaf_reg': 1.5235750922982971, 'random_strength': 0.7059567984827617, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6620985450984024}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:11:29,319] Trial 20 finished with value: 0.6779715327834748 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06099001103204992, 'depth': 7, 'l2_leaf_reg': 1.5746880004587926, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6516708309291913}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:12:57,882] Trial 21 finished with value: 0.6783818775395181 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10361049885630397, 'depth': 7, 'l2_leaf_reg': 2.0689150927243407, 'random_strength': 0.9036717729904239, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8078940946681937}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:14:11,718] Trial 22 finished with value: 0.6745929876603042 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13826116284876147, 'depth': 7, 'l2_leaf_reg': 1.329678717691701, 'random_strength': 0.9125842178610074, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6004575747249266}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:19:27,048] Trial 23 finished with value: 0.6745459320214127 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0515346972791448, 'depth': 8, 'l2_leaf_reg': 3.7160198720941273, 'random_strength': 0.7858716837439924, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.891406249715886}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:22:26,868] Trial 24 finished with value: 0.6784195959947484 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03685227783661514, 'depth': 7, 'l2_leaf_reg': 6.301732208466098, 'random_strength': 0.9549214235042631, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7331067721051978}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:23:12,180] Trial 25 finished with value: 0.6765860142518049 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07329788701429239, 'depth': 6, 'l2_leaf_reg': 1.0006947539296425, 'random_strength': 0.835484319704602, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8016849253908013}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:24:28,953] Trial 26 finished with value: 0.677813486029316 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09456689626721794, 'depth': 7, 'l2_leaf_reg': 2.0276908471016046, 'random_strength': 0.7372048739674053, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:27:55,354] Trial 27 finished with value: 0.663174704422514 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18911527296647498, 'depth': 8, 'l2_leaf_reg': 3.59753180331332, 'random_strength': 0.5572564868770116, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6442682216010479}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:28:43,529] Trial 28 finished with value: 0.6771358247220277 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.061314469451358655, 'depth': 6, 'l2_leaf_reg': 1.358474833234324, 'random_strength': 0.9277738944398083, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9291353201225732}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:31:05,863] Trial 29 finished with value: 0.6518188483231167 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08700102701292303, 'depth': 7, 'l2_leaf_reg': 1.856016704292085, 'random_strength': 0.6977566628115286, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:31:54,018] Trial 30 finished with value: 0.6671669918443237 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11713131612906422, 'depth': 6, 'l2_leaf_reg': 2.3591809427574275, 'random_strength': 0.8163752604936733, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6999178916808287}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:32:58,186] Trial 31 finished with value: 0.674922154591408 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04323984218469783, 'depth': 6, 'l2_leaf_reg': 5.994838423270012, 'random_strength': 0.3540782005135376, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7422921733460072}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:33:31,704] Trial 32 finished with value: 0.6665745569172603 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.040421943014178195, 'depth': 5, 'l2_leaf_reg': 8.870945075739947, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7844662178377397}. Best is trial 17 with value: 0.6859188123945029.
[I 2026-04-10 13:33:56,020] Trial 33 finished with value: 0.6891342117721079 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026567537508033923, 'depth': 4, 'l2_leaf_reg': 7.536472731494689, 'random_strength': 0.4250916001245252, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8396416125497485}. Best is trial 33 with value: 0.6891342117721079.
[I 2026-04-10 13:34:34,374] Trial 34 finished with value: 0.6763008386626422 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026065205742889355, 'depth': 4, 'l2_leaf_reg': 6.759057309731878, 'random_strength': 0.24332089251903077, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8630636835110295}. Best is trial 33 with value: 0.6891342117721079.
[I 2026-04-10 13:35:02,630] Trial 35 finished with value: 0.690884508818721 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02021747711521038, 'depth': 4, 'l2_leaf_reg': 3.2308985240155645, 'random_strength': 0.4771046256334318, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8250129033525764}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:35:31,786] Trial 36 finished with value: 0.6889570902159038 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02054852315351, 'depth': 4, 'l2_leaf_reg': 5.397983604918515, 'random_strength': 0.5040356466525117, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8258555940821485}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:36:06,136] Trial 37 finished with value: 0.6819348046431567 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.021060065190180083, 'depth': 4, 'l2_leaf_reg': 5.457248684381108, 'random_strength': 0.398567029550877, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8205331975494926}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:36:30,699] Trial 38 finished with value: 0.6865316531879565 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.027206357692021402, 'depth': 4, 'l2_leaf_reg': 14.009361993240928, 'random_strength': 0.49012372932583786, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12221043743904225}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:37:04,894] Trial 39 finished with value: 0.6783991293690219 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.024251296967682672, 'depth': 4, 'l2_leaf_reg': 13.632344447497307, 'random_strength': 0.47743167321794355, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.4180462534866333}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:37:31,207] Trial 40 finished with value: 0.684262367514936 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.028396638672782755, 'depth': 4, 'l2_leaf_reg': 11.313805020246203, 'random_strength': 0.536493170677715, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4532051511681003}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:38:03,554] Trial 41 finished with value: 0.6874085539987784 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.022791344585698012, 'depth': 4, 'l2_leaf_reg': 19.95939869142108, 'random_strength': 0.3380367821839193, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.2907563020932256}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:38:33,829] Trial 42 finished with value: 0.6836830523409996 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0234974351476546, 'depth': 4, 'l2_leaf_reg': 19.87582066038242, 'random_strength': 0.3328246762902327, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.245405143265138}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:39:03,150] Trial 43 finished with value: 0.6852869798657619 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.020325872839757918, 'depth': 4, 'l2_leaf_reg': 17.10533081490925, 'random_strength': 0.24668471158677874, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.008811084796338936}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:39:27,110] Trial 44 finished with value: 0.6902408022743185 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02878487422717393, 'depth': 4, 'l2_leaf_reg': 13.069278209737721, 'random_strength': 0.40782834209454394, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.9865392723420132}. Best is trial 35 with value: 0.690884508818721.
[I 2026-04-10 13:40:19,501] Trial 45 finished with value: 0.674605952700335 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.023023045292472604, 'depth': 5, 'l2_leaf_reg': 8.170268131503716, 'random_strength': 0.412099129219076, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.0028565455528105}. Best is trial 35 with value: 0.690884508818721.

                                        feature  importance
184         eye__fix_duration_AOI_FD_Neg1_count    0.023741
1061               PID__PID_P2_data_energy_mean    0.021881
62       eye__sac_speed_AOI_aggregated_Pos_mean    0.021316
803        PID__PID_FC4_first_deriv_energy_mean    0.015711
177           eye__fix_duration_AOI_FD_Neg1_max    0.015093
29       eye__sac_length_AOI_aggregated_Neg_min    0.014573
56    eye__sac_length_AOI_aggregated_Pos_median    0.014454
63     eye__sac_speed_AOI_aggregated_Pos_median    0.014410
30       eye__sac_length_AOI_aggregated_Neg_max    0.013659
276    eye__fix_duration_AOI_aggregated_Pos_min    0.013136
952     PID__PID_POz_first_integral_energy_mean    0.012043
175         eye__fix_duration_AOI_FD_Neg1_first    0.010108
55      eye__sac_length_AOI_aggregated_Pos_mean    0.010067
801        PID__PID_FC2_first_deriv_energy_mean    0.009747
846       PID__PID_CP1_second_deriv_energy_mean    0.009434
278   eye__fix_duration_AOI_aggregated_Pos_mean    0.008300
54       eye__sac_length_AOI_aggregated_Pos_max    0.008168
800        PID__PID_FC1_first_deriv_energy_mean    0.008135
496               PID__PID_FC2_first_deriv_mean    0.007979
1021              PID__PID_AF7_data_energy_mean    0.007821
178          eye__fix_duration_AOI_FD_Neg1_mean    0.007821
53       eye__sac_length_AOI_aggregated_Pos_min    0.007758
523               PID__PID_PO7_first_deriv_mean    0.007392
763                      PID__PID_PO3_data_mean    0.007285
899     PID__PID_AF7_first_integral_energy_mean    0.007179
809        PID__PID_Fp1_first_deriv_energy_mean    0.006491
176           eye__fix_duration_AOI_FD_Neg1_min    0.006369
31      eye__sac_length_AOI_aggregated_Neg_mean    0.006190
179        eye__fix_duration_AOI_FD_Neg1_median    0.006146
571               PID__PID_Oz_second_deriv_mean    0.006089

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.81488
              precision    recall  f1-score   support

           0       0.84      0.68      0.75       156
           1       0.82      0.83      0.83       180
           2       0.79      0.97      0.87       125

    accuracy                           0.82       461
   macro avg       0.82      0.83      0.81       461
weighted avg       0.82      0.82      0.81       461

Confusion matrix:
 [[106  28  22]
 [ 20 149  11]
 [  0   4 121]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
258   eye__fix_duration_AOI_aggregated_Neg_mean    6.226080
30       eye__sac_length_AOI_aggregated_Neg_max    5.225802
35     eye__sac_length_AOI_aggregated_Neg_count    5.147610
39     eye__sac_speed_AOI_aggregated_Neg_median    5.112660
184         eye__fix_duration_AOI_FD_Neg1_count    4.598573
256    eye__fix_duration_AOI_aggregated_Neg_min    4.479764
264  eye__fix_duration_AOI_aggregated_Neg_count    3.663158
32    eye__sac_length_AOI_aggregated_Neg_median    3.650338
276    eye__fix_duration_AOI_aggregated_Pos_min    3.300797
34       eye__sac_length_AOI_aggregated_Neg_sum    3.178662
31      eye__sac_length_AOI_aggregated_Neg_mean    2.872572
53       eye__sac_length_AOI_aggregated_Pos_min    2.765610
178          eye__fix_duration_AOI_FD_Neg1_mean    2.393009
175         eye__fix_duration_AOI_FD_Neg1_first    2.356539
29       eye__sac_length_AOI_aggregated_Neg_min    2.326222
275  eye__fix_duration_AOI_aggregated_Pos_first    2.003297
179        eye__fix_duration_AOI_FD_Neg1_median    1.960162
277    eye__fix_duration_AOI_aggregated_Pos_max    1.772660
63     eye__sac_speed_AOI_aggregated_Pos_median    1.691142
55      eye__sac_length_AOI_aggregated_Pos_mean    1.527947
37        eye__sac_speed_AOI_aggregated_Neg_max    1.513595
257    eye__fix_duration_AOI_aggregated_Neg_max    1.360285
283    eye__fix_duration_AOI_aggregated_Pos_sum    1.340007
263    eye__fix_duration_AOI_aggregated_Neg_sum    1.283190
59     eye__sac_length_AOI_aggregated_Pos_count    1.249316
58       eye__sac_length_AOI_aggregated_Pos_sum    1.190735
284  eye__fix_duration_AOI_aggregated_Pos_count    1.177876
56    eye__sac_length_AOI_aggregated_Pos_median    1.130266
255  eye__fix_duration_AOI_aggregated_Neg_first    0.974823
46      eye__sac_length_AOI_aggregated_None_sum    0.961310

,set,target,split,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,multiclass,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch_general,binary,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch_general,multiclass,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,multiclass,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch_general,binary,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch_general,multiclass,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [10]:
text_stat = _load_ftar_parquet(FTAR_FILES["stat"])
print("stat shape:", text_stat.shape)
summary_stat = run_ftar_set("stat", text_stat)
summary_stat

stat shape: (4442, 8236)
[stat] ftar feature count after cleanup: 8235
[stat] rows missing after index match -> train: 1832, test: 187
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-10 13:46:47,079] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 13:46:51,349] Trial 0 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-10 13:46:57,080] Trial 1 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-10 13:47:02,815] Trial 2 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.4007818691904268.
[I 2026-04-10 13:47:08,624] Trial 3 finished with value: 0.40435996915758105 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.40435996915758105.
[I 2026-04-10 13:47:14,482] Trial 4 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.40435996915758105.
[I 2026-04-10 13:47:20,253] Trial 5 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.40435996915758105.
[I 2026-04-10 13:47:25,245] Trial 6 finished with value: 0.4036994536572686 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 3 with value: 0.40435996915758105.
[I 2026-04-10 13:47:31,285] Trial 7 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 3 with value: 0.40435996915758105.
[I 2026-04-10 13:47:36,826] Trial 8 finished with value: 0.4190184459378726 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:47:43,072] Trial 9 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:47:46,513] Trial 10 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.11205588890315138, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8345351823143565, 'colsample_bytree': 0.8543230417001932, 'gamma': 1.3577299273807322, 'reg_alpha': 9.489578816424906, 'reg_lambda': 0.00015640362680098967}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:47:51,640] Trial 11 finished with value: 0.40245608586409615 and parameters: {'learning_rate': 0.09943849583797226, 'max_depth': 4, 'min_child_weight': 2.174985497459924, 'subsample': 0.8770939713813252, 'colsample_bytree': 0.9144574715071777, 'gamma': 0.810300425187616, 'reg_alpha': 1.242194288693258, 'reg_lambda': 5.975817202898658}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:47:57,246] Trial 12 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.12089264714327194, 'max_depth': 7, 'min_child_weight': 4.475381097837407, 'subsample': 0.8322625695799458, 'colsample_bytree': 0.999748196231103, 'gamma': 1.17498604192392, 'reg_alpha': 0.8323564817789441, 'reg_lambda': 0.0057996628441294}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:01,868] Trial 13 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.07232827237408766, 'max_depth': 4, 'min_child_weight': 2.1881316983127173, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.9257125038420886, 'gamma': 0.6195340614967051, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.8281558812990174}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:07,527] Trial 14 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.13092588836893918, 'max_depth': 7, 'min_child_weight': 5.293870612391065, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8188354553909843, 'gamma': 1.4300503604766472, 'reg_alpha': 0.0001096145847994451, 'reg_lambda': 0.0001149404517214395}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:13,266] Trial 15 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.08769579437557089, 'max_depth': 5, 'min_child_weight': 2.605443591982054, 'subsample': 0.8031267263964212, 'colsample_bytree': 0.8836559825946437, 'gamma': 0.9301080514901593, 'reg_alpha': 0.4144625954675359, 'reg_lambda': 0.010162408101986087}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:17,804] Trial 16 finished with value: 0.4019228667903203 and parameters: {'learning_rate': 0.05967297880371984, 'max_depth': 3, 'min_child_weight': 1.3197480093163605, 'subsample': 0.7492036760782387, 'colsample_bytree': 0.9704490579145556, 'gamma': 0.46895517605916637, 'reg_alpha': 2.822422792379161, 'reg_lambda': 0.36107906515189375}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:23,995] Trial 17 finished with value: 0.4150647839000155 and parameters: {'learning_rate': 0.14277021042832214, 'max_depth': 8, 'min_child_weight': 3.916452611281411, 'subsample': 0.8715702573267258, 'colsample_bytree': 0.8911833935295822, 'gamma': 0.808498565619014, 'reg_alpha': 0.006150532125758031, 'reg_lambda': 0.002020636042702406}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:29,142] Trial 18 finished with value: 0.4045460821046586 and parameters: {'learning_rate': 0.14785596611390225, 'max_depth': 8, 'min_child_weight': 1.50262817616095, 'subsample': 0.9318271613739229, 'colsample_bytree': 0.8868948588223814, 'gamma': 1.3220862940109341, 'reg_alpha': 0.0036864843926879714, 'reg_lambda': 0.0010287362555794165}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:33,750] Trial 19 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.1767980278765189, 'max_depth': 8, 'min_child_weight': 2.7149132715321422, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.8371043328927599, 'gamma': 1.5672833694357762, 'reg_alpha': 0.005384705762740276, 'reg_lambda': 0.0025805725527009464}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:37,839] Trial 20 finished with value: 0.4004647609383973 and parameters: {'learning_rate': 0.19061349036007305, 'max_depth': 7, 'min_child_weight': 6.070731033407083, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.9713676384331917, 'gamma': 1.1605249997997444, 'reg_alpha': 0.001125139554077667, 'reg_lambda': 0.00044247158557228}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:42,716] Trial 21 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.13262910811854842, 'max_depth': 8, 'min_child_weight': 1.5976654198493225, 'subsample': 0.9263199607979542, 'colsample_bytree': 0.8864446130834075, 'gamma': 1.2923241385280066, 'reg_alpha': 0.004935420378364322, 'reg_lambda': 0.0004564327532206686}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:48,214] Trial 22 finished with value: 0.40829119212727294 and parameters: {'learning_rate': 0.1462148202878013, 'max_depth': 8, 'min_child_weight': 1.0411844002676933, 'subsample': 0.939167956379652, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.9889146419284166, 'reg_alpha': 0.0014465800732849606, 'reg_lambda': 0.01671804150864419}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:48:53,797] Trial 23 finished with value: 0.40763928627783563 and parameters: {'learning_rate': 0.14681270220650725, 'max_depth': 7, 'min_child_weight': 1.1553150659238751, 'subsample': 0.8884330763379913, 'colsample_bytree': 0.7893423650618838, 'gamma': 0.956088506003455, 'reg_alpha': 0.00043165877946253, 'reg_lambda': 0.013291734081041857}. Best is trial 8 with value: 0.4190184459378726.
[I 2026-04-10 13:49:00,381] Trial 24 finished with value: 0.4194102988501816 and parameters: {'learning_rate': 0.10782271438784388, 'max_depth': 8, 'min_child_weight': 1.0026474131790024, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.7023486227822291, 'gamma': 0.7088824721980708, 'reg_alpha': 0.06184559495277037, 'reg_lambda': 0.0028103177991887613}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:06,713] Trial 25 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.10710607406054583, 'max_depth': 6, 'min_child_weight': 1.8696170200172455, 'subsample': 0.8102664503344786, 'colsample_bytree': 0.8611318064771043, 'gamma': 0.7221554815769999, 'reg_alpha': 0.07009353679142627, 'reg_lambda': 0.003409560126502486}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:15,063] Trial 26 finished with value: 0.3999865218410787 and parameters: {'learning_rate': 0.07110334564756741, 'max_depth': 8, 'min_child_weight': 1.2487516733363169, 'subsample': 0.8170758967242452, 'colsample_bytree': 0.9047589663185494, 'gamma': 0.38330175512946907, 'reg_alpha': 0.013839680247445654, 'reg_lambda': 0.00025953467384372486}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:21,224] Trial 27 finished with value: 0.4019228667903203 and parameters: {'learning_rate': 0.084202815753675, 'max_depth': 7, 'min_child_weight': 3.7426346459794204, 'subsample': 0.7580785394426199, 'colsample_bytree': 0.8143628432832134, 'gamma': 0.7136827139286881, 'reg_alpha': 0.05668698819946785, 'reg_lambda': 0.002269817403412894}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:27,973] Trial 28 finished with value: 0.4164216149210521 and parameters: {'learning_rate': 0.1177009551384302, 'max_depth': 8, 'min_child_weight': 1.6913557622055726, 'subsample': 0.8497817313912044, 'colsample_bytree': 0.950734926698295, 'gamma': 0.4922572382616635, 'reg_alpha': 0.016023441248100397, 'reg_lambda': 0.031767200342723234}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:35,564] Trial 29 finished with value: 0.4024269155986411 and parameters: {'learning_rate': 0.043474038904341844, 'max_depth': 7, 'min_child_weight': 1.8038878965861835, 'subsample': 0.7737318187734572, 'colsample_bytree': 0.9528923746601379, 'gamma': 0.23394180177672735, 'reg_alpha': 0.017307240547805577, 'reg_lambda': 0.021648087711898863}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:42,160] Trial 30 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.11602009389458831, 'max_depth': 6, 'min_child_weight': 1.5663107968574295, 'subsample': 0.7362355843290266, 'colsample_bytree': 0.9896914339326168, 'gamma': 0.5006806200137118, 'reg_alpha': 0.04796268779915355, 'reg_lambda': 0.004358838353893153}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:49,253] Trial 31 finished with value: 0.41489195091904296 and parameters: {'learning_rate': 0.09863563140321487, 'max_depth': 8, 'min_child_weight': 2.3331581863885087, 'subsample': 0.8570923411225502, 'colsample_bytree': 0.9123610912573642, 'gamma': 0.8508576566893162, 'reg_alpha': 0.010459008447122067, 'reg_lambda': 0.03380511202544572}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:49:55,832] Trial 32 finished with value: 0.4006032992713221 and parameters: {'learning_rate': 0.15666385998661295, 'max_depth': 8, 'min_child_weight': 3.1521845519063216, 'subsample': 0.8257754471427002, 'colsample_bytree': 0.9496528225619765, 'gamma': 0.3737558913160639, 'reg_alpha': 0.001883581689955673, 'reg_lambda': 0.000914662155480078}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:00,870] Trial 33 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.19598818793139447, 'max_depth': 8, 'min_child_weight': 1.173405093451527, 'subsample': 0.8660748228284258, 'colsample_bytree': 0.7085777078616161, 'gamma': 0.6519823678719451, 'reg_alpha': 0.0005056602123340404, 'reg_lambda': 0.22804455175091817}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:07,960] Trial 34 finished with value: 0.40245608586409615 and parameters: {'learning_rate': 0.12504103047835677, 'max_depth': 7, 'min_child_weight': 1.8029417056224284, 'subsample': 0.8470057614577238, 'colsample_bytree': 0.7778907768652055, 'gamma': 0.04329833481801526, 'reg_alpha': 3.870621289132388, 'reg_lambda': 0.05033028856409485}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:14,769] Trial 35 finished with value: 0.4028685576456497 and parameters: {'learning_rate': 0.09022871591207424, 'max_depth': 8, 'min_child_weight': 4.067241492508067, 'subsample': 0.903039368482533, 'colsample_bytree': 0.9530723547595535, 'gamma': 1.091356464178782, 'reg_alpha': 0.12953307489861307, 'reg_lambda': 0.0005012143384413888}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:21,445] Trial 36 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.07582165152255538, 'max_depth': 7, 'min_child_weight': 3.1706861010214373, 'subsample': 0.7965506541210348, 'colsample_bytree': 0.9345854653591733, 'gamma': 0.5096231782486863, 'reg_alpha': 0.03753903627695459, 'reg_lambda': 0.0016614203748980987}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:28,799] Trial 37 finished with value: 0.4033449070374004 and parameters: {'learning_rate': 0.06352149348583366, 'max_depth': 8, 'min_child_weight': 1.4497586105560627, 'subsample': 0.7708858225944155, 'colsample_bytree': 0.9007180131841376, 'gamma': 0.2602487996032118, 'reg_alpha': 0.5974964649503192, 'reg_lambda': 0.0062152003204020085}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:34,354] Trial 38 finished with value: 0.4055676277266712 and parameters: {'learning_rate': 0.1587951056926235, 'max_depth': 5, 'min_child_weight': 5.1560705711786685, 'subsample': 0.8841397553761005, 'colsample_bytree': 0.8656611705379555, 'gamma': 0.8340805615587132, 'reg_alpha': 0.010318760580869982, 'reg_lambda': 0.0012131591815366292}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:40,538] Trial 39 finished with value: 0.40375521178237583 and parameters: {'learning_rate': 0.10778668845622603, 'max_depth': 6, 'min_child_weight': 6.957907726235103, 'subsample': 0.8693393056541892, 'colsample_bytree': 0.9253043480716573, 'gamma': 0.7438954896710837, 'reg_alpha': 0.2678888927307879, 'reg_lambda': 0.10067490853114709}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:46,969] Trial 40 finished with value: 0.40234522647612225 and parameters: {'learning_rate': 0.13211209712671165, 'max_depth': 7, 'min_child_weight': 2.8754180636202804, 'subsample': 0.7282571436393164, 'colsample_bytree': 0.8159790385085472, 'gamma': 0.8946124944640184, 'reg_alpha': 0.02846066011297086, 'reg_lambda': 0.00022606019735921484}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:50:53,870] Trial 41 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.10017255861931752, 'max_depth': 8, 'min_child_weight': 2.279029436311561, 'subsample': 0.8575026568016475, 'colsample_bytree': 0.9009419120876669, 'gamma': 0.8586304887149825, 'reg_alpha': 0.00872829847867085, 'reg_lambda': 0.02788115886604693}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:00,845] Trial 42 finished with value: 0.4086681683284766 and parameters: {'learning_rate': 0.09405140200006823, 'max_depth': 8, 'min_child_weight': 1.969898807628973, 'subsample': 0.8519204368761599, 'colsample_bytree': 0.9143842501556776, 'gamma': 1.1077575703087106, 'reg_alpha': 0.002818373933866252, 'reg_lambda': 0.03966256719950897}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:07,371] Trial 43 finished with value: 0.40156329443360056 and parameters: {'learning_rate': 0.10605046480966747, 'max_depth': 8, 'min_child_weight': 2.442679066984428, 'subsample': 0.8248974370382287, 'colsample_bytree': 0.8411590926273959, 'gamma': 1.0346140135511355, 'reg_alpha': 0.007789067007781173, 'reg_lambda': 0.009168863941454795}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:16,111] Trial 44 finished with value: 0.4045321718092639 and parameters: {'learning_rate': 0.02188029840119486, 'max_depth': 8, 'min_child_weight': 1.6648421301272773, 'subsample': 0.7811096066287728, 'colsample_bytree': 0.7242563932669124, 'gamma': 0.5655933705900972, 'reg_alpha': 0.020844211615677143, 'reg_lambda': 0.15339560285236958}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:20,985] Trial 45 finished with value: 0.4058915155449479 and parameters: {'learning_rate': 0.13386171049082962, 'max_depth': 4, 'min_child_weight': 2.089299977981531, 'subsample': 0.8409809535205413, 'colsample_bytree': 0.9433813027518809, 'gamma': 0.3719591384156563, 'reg_alpha': 1.4854157471537102, 'reg_lambda': 0.04808312735861429}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:25,968] Trial 46 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.1666537359880101, 'max_depth': 7, 'min_child_weight': 3.58239168771542, 'subsample': 0.8975217599218915, 'colsample_bytree': 0.9697200217917441, 'gamma': 0.7674279919453574, 'reg_alpha': 0.0008917168817318616, 'reg_lambda': 0.005474748208527671}. Best is trial 24 with value: 0.4194102988501816.
[I 2026-04-10 13:51:31,803] Trial 47 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.11776756639246001, 'max_depth': 8, 'min_child_weight': 2.526158178834435, 'subsample': 0.8127407988425984, 'colsample_bytree': 0.872795708953651, 'gamma': 0.6838029704392531, 'reg_alpha': 0.14324683929548382, 'reg_lambda': 0.02285916812128081}. Best is trial 24 with value: 0.4194102988501816.

[I 2026-04-10 13:56:31,531] A new study created in memory with name: binary_catboost

[I 2026-04-10 13:56:31,528] Trial 99 finished with value: 0.4007818691904268 and parameters: {'learning_rate': 0.09619649279241006, 'max_depth': 5, 'min_child_weight': 9.55279294256798, 'subsample': 0.8880809258434822, 'colsample_bytree': 0.7002082494666375, 'gamma': 0.9188226004851024, 'reg_alpha': 0.0029050001749184352, 'reg_lambda': 0.0006574117240480262}. Best is trial 51 with value: 0.42171670037671033.

Best model (xgb) CV score: 0.42172
Best params: {'learning_rate': 0.11516860182945018, 'max_depth': 8, 'min_child_weight': 2.013143161521747, 'subsample': 0.8550063732283457, 'colsample_bytree': 0.9160399687484648, 'gamma': 1.0867913859734482, 'reg_alpha': 0.002643607376443078, 'reg_lambda': 0.049359397326142834}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 13:56:36,071] Trial 0 finished with value: 0.4024269155986411 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4024269155986411.
[I 2026-04-10 13:56:46,239] Trial 1 finished with value: 0.4081976679171548 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4081976679171548.
[I 2026-04-10 13:56:55,482] Trial 2 finished with value: 0.4148741950449265 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4148741950449265.
[I 2026-04-10 13:57:09,846] Trial 3 finished with value: 0.40642073694803216 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.4148741950449265.
[I 2026-04-10 13:57:30,304] Trial 4 finished with value: 0.45938337339571933 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:57:55,701] Trial 5 finished with value: 0.41283022657521845 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:58:10,693] Trial 6 finished with value: 0.40652438422531295 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:58:26,246] Trial 7 finished with value: 0.4004647609383973 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:58:55,844] Trial 8 finished with value: 0.40030569258278464 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:09,761] Trial 9 finished with value: 0.41766199126916925 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:14,555] Trial 10 finished with value: 0.4256559437201155 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:19,249] Trial 11 finished with value: 0.43617966436774447 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.7651302031192428, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9606029800630493}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:23,854] Trial 12 finished with value: 0.43696660690442546 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 5, 'l2_leaf_reg': 1.9426894697963841, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.994759737357233}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:28,809] Trial 13 finished with value: 0.42178141520016427 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 5, 'l2_leaf_reg': 2.869741965176845, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8530372066106942}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:33,155] Trial 14 finished with value: 0.4181470799628578 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11980834084297441, 'depth': 5, 'l2_leaf_reg': 1.0042999777217867, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8424234616468694}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 13:59:52,890] Trial 15 finished with value: 0.4281592988229841 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1983058867595879, 'depth': 8, 'l2_leaf_reg': 2.566528746990451, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7749871487988538}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:00,027] Trial 16 finished with value: 0.4458685274972485 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12769952952541253, 'depth': 6, 'l2_leaf_reg': 1.3607865727422728, 'random_strength': 0.09255807539467345, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:11,632] Trial 17 finished with value: 0.43475608276560895 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1394996961358249, 'depth': 7, 'l2_leaf_reg': 1.2616269885717815, 'random_strength': 0.4656569951267181, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8801223986344741}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:19,044] Trial 18 finished with value: 0.4096603638625502 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10208311126159297, 'depth': 6, 'l2_leaf_reg': 4.297692645836977, 'random_strength': 0.12338383043806003, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.731449173064617}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:33,194] Trial 19 finished with value: 0.4154045916633184 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.051518582818118774, 'depth': 7, 'l2_leaf_reg': 2.9364576468481016, 'random_strength': 0.25867306959368175, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6027236636140153}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:40,164] Trial 20 finished with value: 0.43830260933843473 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14724478112125605, 'depth': 6, 'l2_leaf_reg': 1.2395132393802317, 'random_strength': 0.3937119620267663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.822026085437717}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:47,235] Trial 21 finished with value: 0.4194055602311137 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1406484141409489, 'depth': 6, 'l2_leaf_reg': 1.2580162393782834, 'random_strength': 0.4123264876993609, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8078940946681937}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:00:53,771] Trial 22 finished with value: 0.43662968628054677 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15463630448581095, 'depth': 6, 'l2_leaf_reg': 1.4086766688648271, 'random_strength': 0.548801195130663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9012389963141829}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:01:05,598] Trial 23 finished with value: 0.4473154526377872 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11220547592922192, 'depth': 7, 'l2_leaf_reg': 2.3091208313346003, 'random_strength': 0.22962574213454892, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8133914781725257}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:01:27,084] Trial 24 finished with value: 0.42739225659115193 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10727817645006563, 'depth': 8, 'l2_leaf_reg': 2.3824742923266418, 'random_strength': 0.08365877092444227, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7331067721051978}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:01:51,244] Trial 25 finished with value: 0.4283395641954197 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05829916383468929, 'depth': 8, 'l2_leaf_reg': 3.451669656729292, 'random_strength': 0.2445730549485309, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9986863284042589}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:02:02,809] Trial 26 finished with value: 0.4484186545615927 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11327158230515194, 'depth': 7, 'l2_leaf_reg': 1.510912062884666, 'random_strength': 0.21834274258133501, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2578643405925001}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:02:15,218] Trial 27 finished with value: 0.43072817194627483 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09706390576952498, 'depth': 7, 'l2_leaf_reg': 2.2388267897836025, 'random_strength': 0.2094343064948979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.30094396714113597}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:02:41,389] Trial 28 finished with value: 0.4278595925157184 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.035557434255315074, 'depth': 8, 'l2_leaf_reg': 3.6184591445228116, 'random_strength': 0.34149429332589576, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.22090791623893452}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:02:56,138] Trial 29 finished with value: 0.41732780359247557 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11442873227724254, 'depth': 7, 'l2_leaf_reg': 5.924230514846995, 'random_strength': 0.5468500420230062, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.3784693681010873}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:03:20,005] Trial 30 finished with value: 0.4059461294836666 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06675084944309499, 'depth': 8, 'l2_leaf_reg': 1.7102123840607473, 'random_strength': 0.08059479351129284, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 4.4993264036145195}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:03:32,690] Trial 31 finished with value: 0.4233506737143859 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08930346017304557, 'depth': 7, 'l2_leaf_reg': 1.96694171118861, 'random_strength': 0.10391538142689581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.370956938236069}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:03:40,644] Trial 32 finished with value: 0.41024768024032676 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1268238270606708, 'depth': 6, 'l2_leaf_reg': 1.5019635569568064, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.164704118387009}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:03:44,383] Trial 33 finished with value: 0.425383787096691 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.166924005748709, 'depth': 4, 'l2_leaf_reg': 1.476894411636568, 'random_strength': 0.21871985251955298, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6701369229393936}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:03:56,239] Trial 34 finished with value: 0.4537015517345097 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13012394734151897, 'depth': 7, 'l2_leaf_reg': 2.0939555129207044, 'random_strength': 0.06379253204983007, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9087813423872702}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:04:09,040] Trial 35 finished with value: 0.43226346215400846 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08437881618575595, 'depth': 7, 'l2_leaf_reg': 2.1813021908630392, 'random_strength': 0.16082059774872098, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8986051454895897}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:04:30,635] Trial 36 finished with value: 0.40458677000894033 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0369055818079162, 'depth': 7, 'l2_leaf_reg': 3.286543675581052, 'random_strength': 0.06925857200179317, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.660264593122457}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:04:57,419] Trial 37 finished with value: 0.41173233419191646 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06935325932977954, 'depth': 8, 'l2_leaf_reg': 5.611258028906467, 'random_strength': 0.267470577887518, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7862795621092139}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:05:09,599] Trial 38 finished with value: 0.4272173538550422 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1095503727774865, 'depth': 7, 'l2_leaf_reg': 1.620215588569556, 'random_strength': 0.20780226818365757, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.8762205740270945}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:05:30,475] Trial 39 finished with value: 0.44627828697958305 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16623045009969442, 'depth': 8, 'l2_leaf_reg': 2.5411621892639733, 'random_strength': 0.12579029187773771, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7482494117924047}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:05:42,490] Trial 40 finished with value: 0.4223213392696141 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14930247656857162, 'depth': 7, 'l2_leaf_reg': 2.097590469116468, 'random_strength': 0.03709693060547279, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.04641615518621}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:06:03,192] Trial 41 finished with value: 0.43625301178991327 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17213043475481316, 'depth': 8, 'l2_leaf_reg': 2.779777312532893, 'random_strength': 0.13952271324636795, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7496908099556138}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:06:23,668] Trial 42 finished with value: 0.4369904236912801 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18413633372113128, 'depth': 8, 'l2_leaf_reg': 2.446491649581778, 'random_strength': 0.31810097501113327, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8078704656740565}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:06:45,781] Trial 43 finished with value: 0.44781550159778266 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13238699481219313, 'depth': 8, 'l2_leaf_reg': 1.1422113796351874, 'random_strength': 0.13952177315932893, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7084023590730016}. Best is trial 4 with value: 0.45938337339571933.
[I 2026-04-10 14:06:58,302] Trial 44 finished with value: 0.4212357749842204 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09416465192011007, 'depth': 7, 'l2_leaf_reg': 1.1199318727116085, 'random_strength': 0.05488924072900614, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7007859777487051}. Best is trial 4 with value: 0.45938337339571933.

                                           feature  importance
262      eye__fix_duration_AOI_aggregated_Neg_skew    0.045425
481                                 stat__umap_011    0.044037
182             eye__fix_duration_AOI_FD_Neg1_skew    0.042124
493                                 stat__umap_023    0.040286
503                                 stat__umap_033    0.040217
372                  eye__corr_dim_m_2_tau_1_r_200    0.031819
212             eye__fix_duration_AOI_FD_Pos1_skew    0.031136
161                             eye__reg_speed_std    0.030624
170                          eye__fix_duration_std    0.030510
54          eye__sac_length_AOI_aggregated_Pos_max    0.030355
23                      eye__sac_angle_between_max    0.029600
377                   eye__corr_dim_m_3_tau_1_r_50    0.028593
261  eye__fix_duration_AOI_aggregated_Neg_kurtosis    0.027622
163                            eye__reg_speed_skew    0.027458
157                             eye__reg_speed_min    0.026898
202             eye__fix_duration_AOI_FD_Neg2_skew    0.026332
335                  eye__sample_entropy_m=2_r=400    0.026043
542                                 stat__umap_072    0.024541
356           eye__lyapunov_exponent_m_3_tau_2_T_1    0.024458
4                              eye__sac_length_std    0.023915
186              eye__fix_duration_AOI_FD_None_min    0.023824
22                      eye__sac_angle_between_min    0.021948
42         eye__sac_length_AOI_aggregated_None_max    0.021518
187              eye__fix_duration_AOI_FD_None_max    0.021486
59        eye__sac_length_AOI_aggregated_Pos_count    0.021377
21                        eye__sac_angle_to_x_skew    0.021210
386                   eye__corr_dim_m_4_tau_2_r_50    0.020534
537                                 stat__umap_067    0.019746
11                           eye__sac_speed_median    0.019527
393      eye__rec_metric_euclidean_length_1_rho_25    0.019335

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.43607
              precision    recall  f1-score   support

           0       0.67      0.95      0.78       307
           1       0.33      0.05      0.09       154

    accuracy                           0.65       461
   macro avg       0.50      0.50      0.44       461
weighted avg       0.55      0.65      0.55       461

Confusion matrix:
 [[291  16]
 [146   8]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
277     eye__fix_duration_AOI_aggregated_Pos_max    9.568549
257     eye__fix_duration_AOI_aggregated_Neg_max    8.783236
488                               stat__umap_018    8.772822
183            eye__fix_duration_AOI_FD_Neg1_sum    6.008322
476                               stat__umap_006    5.215709
495                               stat__umap_025    3.799112
504                               stat__umap_034    3.785178
517                               stat__umap_047    3.171872
381                eye__corr_dim_m_3_tau_2_r_200    3.123850
40         eye__sac_speed_AOI_aggregated_Neg_std    3.011090
465                                eye__imf0_max    2.947666
316                          eye__hurst_exponent    2.707768
482                               stat__umap_012    2.686343
379                eye__corr_dim_m_3_tau_1_r_400    2.598439
432           eye__corm_euclidean_length_3_rho_5    2.593244
10                           eye__sac_speed_mean    2.584272
8                             eye__sac_speed_min    2.545111
426          eye__det_euclidean_length_2_rho_500    2.470348
508                               stat__umap_038    2.391534
164                           eye__reg_mask_mean    2.369428
535                               stat__umap_065    2.283942
163                          eye__reg_speed_skew    2.269647
42       eye__sac_length_AOI_aggregated_None_max    2.198675
274  eye__fix_duration_AOI_aggregated_None_count    1.955141
295                         eye__fuzzy_m_2_r_200    1.909414
210            eye__fix_duration_AOI_FD_Pos1_std    1.888069
480                               stat__umap_010    1.811638
171                   eye__fix_duration_kurtosis    1.772659
497                               stat__umap_027    1.586724
339                eye__sample_entropy_m=3_r=200    1.190202

[stat] rows missing after index match -> train: 1832, test: 187
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-10 14:09:50,155] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 14:10:02,254] Trial 0 finished with value: 0.5789936832201856 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5789936832201856.
[I 2026-04-10 14:10:12,327] Trial 1 finished with value: 0.5768610269776758 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5789936832201856.
[I 2026-04-10 14:10:26,853] Trial 2 finished with value: 0.5809499338011739 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5809499338011739.
[I 2026-04-10 14:10:35,710] Trial 3 finished with value: 0.5864438561465987 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.5864438561465987.
[I 2026-04-10 14:10:45,442] Trial 4 finished with value: 0.5891827411868189 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:11:01,580] Trial 5 finished with value: 0.5805165602773505 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:11:08,691] Trial 6 finished with value: 0.5672714460041368 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:11:25,967] Trial 7 finished with value: 0.5832303068797775 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:11:35,212] Trial 8 finished with value: 0.5746468957675699 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:04,348] Trial 9 finished with value: 0.5788590474838298 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:13,872] Trial 10 finished with value: 0.586539092588528 and parameters: {'learning_rate': 0.07985847190685645, 'max_depth': 8, 'min_child_weight': 5.7644975171451085, 'subsample': 0.8853830026900457, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4769827267624924, 'reg_alpha': 9.072541150259902, 'reg_lambda': 0.00015423477789158795}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:23,528] Trial 11 finished with value: 0.582878856900817 and parameters: {'learning_rate': 0.08340624238172284, 'max_depth': 8, 'min_child_weight': 5.4313767025149335, 'subsample': 0.893839626256697, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.55887448767108, 'reg_alpha': 9.420436700655088, 'reg_lambda': 0.00013386192543122697}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:32,880] Trial 12 finished with value: 0.5861499809429009 and parameters: {'learning_rate': 0.07561377665306217, 'max_depth': 7, 'min_child_weight': 5.9752070205206556, 'subsample': 0.9150707272847923, 'colsample_bytree': 0.8200086342488122, 'gamma': 1.4341884397263645, 'reg_alpha': 9.122108443295133, 'reg_lambda': 0.0002151847716653377}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:41,833] Trial 13 finished with value: 0.5764512690886339 and parameters: {'learning_rate': 0.11590443861538359, 'max_depth': 7, 'min_child_weight': 2.2174243287787054, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.8982052198001709, 'gamma': 1.979013798034184, 'reg_alpha': 0.0014860826225950691, 'reg_lambda': 0.0024890652675014007}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:12:56,003] Trial 14 finished with value: 0.5734476884048572 and parameters: {'learning_rate': 0.0642128149764116, 'max_depth': 8, 'min_child_weight': 6.193294580335647, 'subsample': 0.843949145174496, 'colsample_bytree': 0.9916923326444256, 'gamma': 1.3274497225194715, 'reg_alpha': 0.00010120803577490972, 'reg_lambda': 0.006522520406563256}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:13:04,273] Trial 15 finished with value: 0.5821435646839839 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 7, 'min_child_weight': 2.605443591982054, 'subsample': 0.9299561357198776, 'colsample_bytree': 0.8350884718349774, 'gamma': 1.7344599894515131, 'reg_alpha': 1.0793361912384043, 'reg_lambda': 0.00038818117779263476}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:13:15,705] Trial 16 finished with value: 0.58133699611299 and parameters: {'learning_rate': 0.0489025517956362, 'max_depth': 3, 'min_child_weight': 4.6647440638508675, 'subsample': 0.9942231535523712, 'colsample_bytree': 0.9115147692385368, 'gamma': 1.2861345846332304, 'reg_alpha': 0.008983863676974733, 'reg_lambda': 0.009760594576952502}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:13:25,924] Trial 17 finished with value: 0.5763701840603389 and parameters: {'learning_rate': 0.07429680162629006, 'max_depth': 7, 'min_child_weight': 7.318616462957624, 'subsample': 0.8870911863689172, 'colsample_bytree': 0.9337618063103539, 'gamma': 1.7152208634075365, 'reg_alpha': 0.11688768024367346, 'reg_lambda': 0.000943156445892148}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:13:45,983] Trial 18 finished with value: 0.5845900713854641 and parameters: {'learning_rate': 0.03692651027057032, 'max_depth': 8, 'min_child_weight': 3.918771677114889, 'subsample': 0.8448407216354642, 'colsample_bytree': 0.8074213105844478, 'gamma': 0.8753094426437581, 'reg_alpha': 0.5575803026989805, 'reg_lambda': 0.0001301520782772361}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:13:54,764] Trial 19 finished with value: 0.5821425937355257 and parameters: {'learning_rate': 0.09820612998650861, 'max_depth': 7, 'min_child_weight': 6.959145681677243, 'subsample': 0.8110338040151214, 'colsample_bytree': 0.8514360044554516, 'gamma': 1.8593795170423038, 'reg_alpha': 3.2938836281197914, 'reg_lambda': 0.003774994879520613}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:07,205] Trial 20 finished with value: 0.5842479700932356 and parameters: {'learning_rate': 0.05766350962985036, 'max_depth': 8, 'min_child_weight': 2.7402286143342476, 'subsample': 0.9337970224757005, 'colsample_bytree': 0.9666755515637406, 'gamma': 1.489652013481267, 'reg_alpha': 0.1369204181336299, 'reg_lambda': 0.019314747658901}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:17,907] Trial 21 finished with value: 0.585175773555009 and parameters: {'learning_rate': 0.08985649056814686, 'max_depth': 4, 'min_child_weight': 4.944779149728349, 'subsample': 0.8831500796248434, 'colsample_bytree': 0.9190262075391779, 'gamma': 0.7682134743116297, 'reg_alpha': 0.5679546269935524, 'reg_lambda': 8.97280857425151}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:26,701] Trial 22 finished with value: 0.5803545488281351 and parameters: {'learning_rate': 0.1405994315702103, 'max_depth': 5, 'min_child_weight': 4.251173621197766, 'subsample': 0.8724415121631384, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.5340103811959349, 'reg_alpha': 0.3209074150838193, 'reg_lambda': 0.13919838890434982}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:35,200] Trial 23 finished with value: 0.5863061696263532 and parameters: {'learning_rate': 0.101905976105421, 'max_depth': 4, 'min_child_weight': 7.089214860653243, 'subsample': 0.8212856175843006, 'colsample_bytree': 0.8793205537663409, 'gamma': 1.1442709478182689, 'reg_alpha': 0.0565891482643651, 'reg_lambda': 0.8503846385383349}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:43,068] Trial 24 finished with value: 0.5857171881772452 and parameters: {'learning_rate': 0.06866970784149266, 'max_depth': 3, 'min_child_weight': 5.11284056023292, 'subsample': 0.9048284516267785, 'colsample_bytree': 0.9551600560923356, 'gamma': 0.8766183569880129, 'reg_alpha': 4.067943640564627, 'reg_lambda': 0.00039763489993440934}. Best is trial 4 with value: 0.5891827411868189.
[I 2026-04-10 14:14:50,718] Trial 25 finished with value: 0.5892675193138712 and parameters: {'learning_rate': 0.13495079053879566, 'max_depth': 5, 'min_child_weight': 3.3801045426435685, 'subsample': 0.8756070472854934, 'colsample_bytree': 0.9952224978180996, 'gamma': 0.6023786404713665, 'reg_alpha': 0.6974254663669006, 'reg_lambda': 0.3873464602786107}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:14:59,965] Trial 26 finished with value: 0.5770977567151578 and parameters: {'learning_rate': 0.1440791477853818, 'max_depth': 7, 'min_child_weight': 3.3226806080214204, 'subsample': 0.9521317187681627, 'colsample_bytree': 0.9959782000084468, 'gamma': 0.47684561011190413, 'reg_alpha': 0.9737957144168642, 'reg_lambda': 0.2169245950299018}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:15:06,777] Trial 27 finished with value: 0.5856236662726187 and parameters: {'learning_rate': 0.19915016512101796, 'max_depth': 6, 'min_child_weight': 1.047845756968512, 'subsample': 0.9114470018830568, 'colsample_bytree': 0.9824051790876697, 'gamma': 1.3397348737806856, 'reg_alpha': 4.448735174226179, 'reg_lambda': 0.020440473841813727}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:15:16,548] Trial 28 finished with value: 0.584107247731833 and parameters: {'learning_rate': 0.14234983569204313, 'max_depth': 8, 'min_child_weight': 2.6886403539216976, 'subsample': 0.8202303274092494, 'colsample_bytree': 0.9528112283856441, 'gamma': 0.6574541181298034, 'reg_alpha': 1.5903146100964587, 'reg_lambda': 0.0009054620410850425}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:15:30,482] Trial 29 finished with value: 0.5694379467363156 and parameters: {'learning_rate': 0.08194044450484951, 'max_depth': 7, 'min_child_weight': 6.146192223733693, 'subsample': 0.8645327158747165, 'colsample_bytree': 0.7859889234199949, 'gamma': 0.36366373521814577, 'reg_alpha': 0.06661339609154406, 'reg_lambda': 0.0003313559143238185}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:15:40,395] Trial 30 finished with value: 0.5819621792289963 and parameters: {'learning_rate': 0.06244879520463036, 'max_depth': 4, 'min_child_weight': 3.744936919881296, 'subsample': 0.9327377593966233, 'colsample_bytree': 0.9071224507904275, 'gamma': 1.7974831330531318, 'reg_alpha': 0.010359517424654326, 'reg_lambda': 3.7565559563948794}. Best is trial 25 with value: 0.5892675193138712.
[I 2026-04-10 14:15:48,640] Trial 31 finished with value: 0.5893626971080032 and parameters: {'learning_rate': 0.10103569982969385, 'max_depth': 5, 'min_child_weight': 4.307044998400575, 'subsample': 0.8702464185009813, 'colsample_bytree': 0.8848236498395817, 'gamma': 0.9244380643047826, 'reg_alpha': 0.302720844530998, 'reg_lambda': 0.7239056105398644}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:15:56,326] Trial 32 finished with value: 0.583794898835532 and parameters: {'learning_rate': 0.10848225997557388, 'max_depth': 5, 'min_child_weight': 3.596565927734636, 'subsample': 0.895670629275931, 'colsample_bytree': 0.8840743211354025, 'gamma': 0.9736096794018362, 'reg_alpha': 0.620576238377235, 'reg_lambda': 2.384599854724349}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:16:06,986] Trial 33 finished with value: 0.5783063117112546 and parameters: {'learning_rate': 0.08647657118930212, 'max_depth': 4, 'min_child_weight': 5.566446019091273, 'subsample': 0.8340699529517397, 'colsample_bytree': 0.8470000814672892, 'gamma': 0.7321906285226443, 'reg_alpha': 0.22433815164612708, 'reg_lambda': 0.31444914874719365}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:16:18,246] Trial 34 finished with value: 0.5799184999060123 and parameters: {'learning_rate': 0.12625148195211022, 'max_depth': 5, 'min_child_weight': 4.307404411003338, 'subsample': 0.871203807508141, 'colsample_bytree': 0.9310546712632279, 'gamma': 0.3518679656136416, 'reg_alpha': 0.04951352790796572, 'reg_lambda': 1.7655429317422575}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:16:33,870] Trial 35 finished with value: 0.5821723341007419 and parameters: {'learning_rate': 0.04160111268740359, 'max_depth': 6, 'min_child_weight': 2.227560808492034, 'subsample': 0.9532967717325809, 'colsample_bytree': 0.868857418654333, 'gamma': 1.6548632852688054, 'reg_alpha': 0.2415308783469737, 'reg_lambda': 0.9207329236737881}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:16:43,520] Trial 36 finished with value: 0.5784140279542509 and parameters: {'learning_rate': 0.16709360637652126, 'max_depth': 5, 'min_child_weight': 9.999978053662037, 'subsample': 0.8604472617348955, 'colsample_bytree': 0.8922181673501122, 'gamma': 0.12776366750988005, 'reg_alpha': 2.35364499082693, 'reg_lambda': 0.0444835998611586}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:16:51,281] Trial 37 finished with value: 0.5748994434369017 and parameters: {'learning_rate': 0.0975395662007302, 'max_depth': 4, 'min_child_weight': 7.772014529905587, 'subsample': 0.7559126361055413, 'colsample_bytree': 0.8313192475629019, 'gamma': 1.2141168262143784, 'reg_alpha': 0.022081701573264004, 'reg_lambda': 0.3635965145693448}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:07,459] Trial 38 finished with value: 0.5860811742467777 and parameters: {'learning_rate': 0.05345034029239244, 'max_depth': 5, 'min_child_weight': 3.0479260598705284, 'subsample': 0.9223413773430162, 'colsample_bytree': 0.9747708001434746, 'gamma': 0.978070472752393, 'reg_alpha': 5.07099764437006, 'reg_lambda': 9.455449528288975}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:19,119] Trial 39 finished with value: 0.5840975660072609 and parameters: {'learning_rate': 0.06878120469170008, 'max_depth': 6, 'min_child_weight': 4.23643107992449, 'subsample': 0.9686201761731281, 'colsample_bytree': 0.9184031857996366, 'gamma': 1.535329535074196, 'reg_alpha': 0.0016727736468209688, 'reg_lambda': 0.10067490853114709}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:27,087] Trial 40 finished with value: 0.577649810359327 and parameters: {'learning_rate': 0.13106442543489558, 'max_depth': 8, 'min_child_weight': 6.4962009450913625, 'subsample': 0.8806305088866302, 'colsample_bytree': 0.7765380388234422, 'gamma': 1.641847635101703, 'reg_alpha': 0.17757165163330993, 'reg_lambda': 1.149713362648947}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:37,105] Trial 41 finished with value: 0.5810071902647291 and parameters: {'learning_rate': 0.0943190848227848, 'max_depth': 5, 'min_child_weight': 4.807200502392207, 'subsample': 0.8600384145878099, 'colsample_bytree': 0.9458906410204245, 'gamma': 0.8668132920821983, 'reg_alpha': 0.41088985959775526, 'reg_lambda': 0.3822805358881274}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:49,163] Trial 42 finished with value: 0.5813580945568413 and parameters: {'learning_rate': 0.07770431707676391, 'max_depth': 5, 'min_child_weight': 5.462994231810118, 'subsample': 0.8982733779616258, 'colsample_bytree': 0.9623864515686733, 'gamma': 0.7065896550329858, 'reg_alpha': 1.5964028501923269, 'reg_lambda': 4.261489605330996}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:17:57,649] Trial 43 finished with value: 0.5796303604301634 and parameters: {'learning_rate': 0.1602490903337693, 'max_depth': 6, 'min_child_weight': 3.4455925076368836, 'subsample': 0.8025855029237592, 'colsample_bytree': 0.8691526560201583, 'gamma': 1.0338629556319916, 'reg_alpha': 0.8005656164286727, 'reg_lambda': 0.6737833849976671}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:18:20,024] Trial 44 finished with value: 0.5793174503901465 and parameters: {'learning_rate': 0.025308440279021516, 'max_depth': 5, 'min_child_weight': 8.286389003832669, 'subsample': 0.8535212952878314, 'colsample_bytree': 0.9332348234995693, 'gamma': 0.8200623870934755, 'reg_alpha': 0.03591115699079709, 'reg_lambda': 0.18651485735535875}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:18:30,538] Trial 45 finished with value: 0.5802666627929766 and parameters: {'learning_rate': 0.1100644294287774, 'max_depth': 6, 'min_child_weight': 4.127853281710501, 'subsample': 0.7165879169247931, 'colsample_bytree': 0.999808428475493, 'gamma': 0.5991310534151287, 'reg_alpha': 0.33593517730410893, 'reg_lambda': 0.06579139683276464}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:18:38,624] Trial 46 finished with value: 0.577788582817022 and parameters: {'learning_rate': 0.1097202073461265, 'max_depth': 4, 'min_child_weight': 2.974937600414261, 'subsample': 0.8348718334462579, 'colsample_bytree': 0.8994187204522868, 'gamma': 1.9817473554957776, 'reg_alpha': 0.07682245183281794, 'reg_lambda': 0.0016448508712491208}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:18:46,387] Trial 47 finished with value: 0.5767105914824471 and parameters: {'learning_rate': 0.19088674252674134, 'max_depth': 5, 'min_child_weight': 4.62703004449454, 'subsample': 0.8766302354667203, 'colsample_bytree': 0.8559364297068994, 'gamma': 1.4049357495461405, 'reg_alpha': 7.282316971102583, 'reg_lambda': 0.0002050853515983898}. Best is trial 31 with value: 0.5893626971080032.
[I 2026-04-10 14:19:01,418] Trial 48 finished with value: 0.5879913544416537 and parameters: {'learning_rate': 0.07125233741923177, 'max_depth': 6, 'min_child_weight': 2.292073238692499, 'subsample': 0.891423235809407, 'colsample_bytree': 0.9835573826614459, 'gamma': 0.4560630217417941, 'reg_alpha': 2.066627986834923, 'reg_lambda': 0.004371197626165927}. Best is trial 31 with value: 0.5893626971080032.

[I 2026-04-10 14:31:10,120] A new study created in memory with name: multiclass_catboost

[I 2026-04-10 14:31:10,116] Trial 99 finished with value: 0.5885685247737726 and parameters: {'learning_rate': 0.07586664164698442, 'max_depth': 6, 'min_child_weight': 3.351539545558992, 'subsample': 0.8458483145609901, 'colsample_bytree': 0.8926762696215046, 'gamma': 1.727979016997892, 'reg_alpha': 0.07280595506664173, 'reg_lambda': 0.00040732819535226094}. Best is trial 81 with value: 0.593629026223002.

Best model (xgb) CV score: 0.59363
Best params: {'learning_rate': 0.07435001770290524, 'max_depth': 6, 'min_child_weight': 3.976374870376421, 'subsample': 0.8441142160329994, 'colsample_bytree': 0.9516625999590653, 'gamma': 0.6999205077091206, 'reg_alpha': 0.11064945543970187, 'reg_lambda': 0.002413860570556398}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 14:31:25,148] Trial 0 finished with value: 0.572534510553623 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.572534510553623.
[I 2026-04-10 14:31:58,891] Trial 1 finished with value: 0.5749630012961416 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5749630012961416.
[I 2026-04-10 14:32:25,326] Trial 2 finished with value: 0.5848569851714582 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5848569851714582.
[I 2026-04-10 14:33:21,875] Trial 3 finished with value: 0.5776961377890816 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.5848569851714582.
[I 2026-04-10 14:34:39,543] Trial 4 finished with value: 0.5695396848521672 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.5848569851714582.
[I 2026-04-10 14:36:56,157] Trial 5 finished with value: 0.5884427501355608 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 5 with value: 0.5884427501355608.
[I 2026-04-10 14:37:50,972] Trial 6 finished with value: 0.5742588566137803 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 5 with value: 0.5884427501355608.
[I 2026-04-10 14:39:22,523] Trial 7 finished with value: 0.5730805149347339 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 5 with value: 0.5884427501355608.
[I 2026-04-10 14:42:56,676] Trial 8 finished with value: 0.5670323175699933 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 5 with value: 0.5884427501355608.
[I 2026-04-10 14:43:39,465] Trial 9 finished with value: 0.5907478619301053 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 9 with value: 0.5907478619301053.
[I 2026-04-10 14:43:50,198] Trial 10 finished with value: 0.594186160887666 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15550029108275915, 'depth': 5, 'l2_leaf_reg': 1.2809979042149076, 'random_strength': 0.9947887102560302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9526058892396143}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:43:59,759] Trial 11 finished with value: 0.5933321520374184 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.0055865908574264, 'random_strength': 0.9740569036396177, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9614469323901528}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:10,125] Trial 12 finished with value: 0.575771448568694 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19910621050598845, 'depth': 5, 'l2_leaf_reg': 1.0085704638043405, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9695283780396771}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:21,191] Trial 13 finished with value: 0.576688118470421 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13079075812018592, 'depth': 5, 'l2_leaf_reg': 2.0776672888066567, 'random_strength': 0.9856537396873218, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9715986510881334}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:32,817] Trial 14 finished with value: 0.5772646874786289 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13013395538647238, 'depth': 5, 'l2_leaf_reg': 3.3885725092083554, 'random_strength': 0.8404900018516125, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8791010705732631}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:44,156] Trial 15 finished with value: 0.587862411856477 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12725930491366905, 'depth': 5, 'l2_leaf_reg': 1.4312229361278432, 'random_strength': 0.8707190509767808, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8992203463950514}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:50,529] Trial 16 finished with value: 0.5941663517012366 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15938476477516944, 'depth': 4, 'l2_leaf_reg': 3.0288129467455445, 'random_strength': 0.6214660893299195, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8691090890441088}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:44:57,362] Trial 17 finished with value: 0.593149240989299 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11145654274644243, 'depth': 4, 'l2_leaf_reg': 2.7449770360872834, 'random_strength': 0.6263503087387519, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8543523082621147}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:45:06,579] Trial 18 finished with value: 0.5797276014814325 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05869502227655196, 'depth': 4, 'l2_leaf_reg': 5.7529312391774745, 'random_strength': 0.5209027449269557, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8277928233341015}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:45:23,599] Trial 19 finished with value: 0.5750803994971521 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15360967997703137, 'depth': 6, 'l2_leaf_reg': 2.7638572551708656, 'random_strength': 0.486766778546476, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9176168089828345}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:45:34,546] Trial 20 finished with value: 0.5900193040722669 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03723605925084384, 'depth': 4, 'l2_leaf_reg': 1.455326985331247, 'random_strength': 0.752217167941259, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9994200117989197}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:45:45,228] Trial 21 finished with value: 0.5887479027677874 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1652563578403174, 'depth': 5, 'l2_leaf_reg': 1.1716113829147636, 'random_strength': 0.9290211053739494, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9399235609565197}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:45:57,261] Trial 22 finished with value: 0.5840590321252227 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10942717078829303, 'depth': 5, 'l2_leaf_reg': 2.490565015349917, 'random_strength': 0.7652359255633379, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9389542823388447}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:46:07,424] Trial 23 finished with value: 0.5834785066852612 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15331725395670548, 'depth': 5, 'l2_leaf_reg': 1.33753244620741, 'random_strength': 0.9283361094645206, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8540270670684871}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:46:30,929] Trial 24 finished with value: 0.5924422299707361 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10211435932291611, 'depth': 6, 'l2_leaf_reg': 1.8671119953508337, 'random_strength': 0.8074402907723954, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7981788967106411}. Best is trial 10 with value: 0.594186160887666.
[I 2026-04-10 14:46:36,615] Trial 25 finished with value: 0.605703967553019 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19846979036160958, 'depth': 4, 'l2_leaf_reg': 3.6442131827163133, 'random_strength': 0.5662562005798994, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9986863284042589}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:46:42,382] Trial 26 finished with value: 0.5880332645143876 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1398563108599135, 'depth': 4, 'l2_leaf_reg': 3.789088006970945, 'random_strength': 0.40290316291915007, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:46:49,022] Trial 27 finished with value: 0.5911255834638375 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18911527296647498, 'depth': 4, 'l2_leaf_reg': 6.068418848109113, 'random_strength': 0.56865664627836, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9926606956826497}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:46:55,540] Trial 28 finished with value: 0.5951834434042966 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1923512897535043, 'depth': 4, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.6905766996934817, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9145145292776101}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:07,401] Trial 29 finished with value: 0.5571476686490353 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19515267938504477, 'depth': 4, 'l2_leaf_reg': 2.3096752895693307, 'random_strength': 0.7002679337331117, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.682610778645282}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:14,765] Trial 30 finished with value: 0.5801376386383057 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09493244255739705, 'depth': 4, 'l2_leaf_reg': 5.228692430686142, 'random_strength': 0.566953499522696, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9110701632753113}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:21,359] Trial 31 finished with value: 0.5772967077534547 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1568780730369213, 'depth': 4, 'l2_leaf_reg': 3.3670387541347804, 'random_strength': 0.5875448516708333, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8866914402011773}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:28,001] Trial 32 finished with value: 0.5769008523974121 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11893543289402568, 'depth': 4, 'l2_leaf_reg': 3.015530541974759, 'random_strength': 0.2430639899320472, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9369523350317678}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:34,097] Trial 33 finished with value: 0.576943044236825 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14420550631541265, 'depth': 4, 'l2_leaf_reg': 1.8380021200605228, 'random_strength': 0.4275324322787787, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8628684864411141}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:47:41,600] Trial 34 finished with value: 0.5829364570983255 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19939968375834863, 'depth': 4, 'l2_leaf_reg': 7.5469800964086, 'random_strength': 0.7110173458201074, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9397502626023202}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:48:06,646] Trial 35 finished with value: 0.5815966467492057 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 5, 'l2_leaf_reg': 3.9963701773956286, 'random_strength': 0.5222008786544401, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8235783577934663}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:48:13,077] Trial 36 finished with value: 0.5795231895189004 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17169903575784817, 'depth': 4, 'l2_leaf_reg': 4.951513240851335, 'random_strength': 0.6852036213656216, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9752934885299434}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:48:32,840] Trial 37 finished with value: 0.5789692853925321 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06285726355281986, 'depth': 5, 'l2_leaf_reg': 7.863600076760807, 'random_strength': 0.3484359561956496, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9166763800908362}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:48:39,689] Trial 38 finished with value: 0.5725879245164169 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17063484203431414, 'depth': 4, 'l2_leaf_reg': 3.4562858088500046, 'random_strength': 0.6213630323006543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.12221043743904225}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:49:04,554] Trial 39 finished with value: 0.5773977343317771 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08713154458905033, 'depth': 6, 'l2_leaf_reg': 2.161407883881695, 'random_strength': 0.7898852844251392, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.957707746480069}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:49:11,178] Trial 40 finished with value: 0.5759513805552243 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14241776856783714, 'depth': 4, 'l2_leaf_reg': 1.6955249692557246, 'random_strength': 0.14571683914765543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.4532051511681003}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:49:21,858] Trial 41 finished with value: 0.5810613697078729 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1745677970727167, 'depth': 5, 'l2_leaf_reg': 1.1792437984887763, 'random_strength': 0.9008245972536474, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9982147204280446}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:49:56,979] Trial 42 finished with value: 0.5821349814236275 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18168723821698612, 'depth': 7, 'l2_leaf_reg': 1.2081219156154541, 'random_strength': 0.9357017599517654, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9587823915635423}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:50:08,509] Trial 43 finished with value: 0.5907152515163231 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16024048088328932, 'depth': 5, 'l2_leaf_reg': 4.386160878258926, 'random_strength': 0.9988443807199296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9186432365799019}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:50:33,242] Trial 44 finished with value: 0.5823227672138058 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12420185969717869, 'depth': 6, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.8309193569446909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9762992059988802}. Best is trial 25 with value: 0.605703967553019.
[I 2026-04-10 14:50:43,392] Trial 45 finished with value: 0.5684539840166003 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.137494660235121, 'depth': 5, 'l2_leaf_reg': 1.5177253131754789, 'random_strength': 0.003701014064702468, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8819602275292855}. Best is trial 25 with value: 0.605703967553019.

                                               feature  importance
29              eye__sac_length_AOI_aggregated_Neg_min    0.048595
259        eye__fix_duration_AOI_aggregated_Neg_median    0.018503
55             eye__sac_length_AOI_aggregated_Pos_mean    0.018103
36               eye__sac_speed_AOI_aggregated_Neg_min    0.017186
53              eye__sac_length_AOI_aggregated_Pos_min    0.016790
277           eye__fix_duration_AOI_aggregated_Pos_max    0.012242
207                  eye__fix_duration_AOI_FD_Pos1_max    0.012147
257           eye__fix_duration_AOI_aggregated_Neg_max    0.012106
62              eye__sac_speed_AOI_aggregated_Pos_mean    0.010067
63            eye__sac_speed_AOI_aggregated_Pos_median    0.007903
47           eye__sac_length_AOI_aggregated_None_count    0.007362
54              eye__sac_length_AOI_aggregated_Pos_max    0.007294
35            eye__sac_length_AOI_aggregated_Neg_count    0.006547
484                                     stat__umap_014    0.006443
194                eye__fix_duration_AOI_FD_None_count    0.005575
58              eye__sac_length_AOI_aggregated_Pos_sum    0.005170
258          eye__fix_duration_AOI_aggregated_Neg_mean    0.004740
255         eye__fix_duration_AOI_aggregated_Neg_first    0.004655
263           eye__fix_duration_AOI_aggregated_Neg_sum    0.004594
276           eye__fix_duration_AOI_aggregated_Pos_min    0.004228
487                                     stat__umap_017    0.003946
372                      eye__corr_dim_m_2_tau_1_r_200    0.003662
511                                     stat__umap_041    0.003651
492                                     stat__umap_022    0.003625
97   eye__sac_speed_from_Pos_to_Target_from_Pos_to_...    0.003605
46             eye__sac_length_AOI_aggregated_None_sum    0.003604
480                                     stat__umap_010    0.003598
479                                     stat__umap_009    0.003576
278          eye__fix_duration_AOI_aggregated_Pos_mean    0.003565
77   eye__sac_length_from_Neg_to_Target_from_Neg_to...    0.003533

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.61886
              precision    recall  f1-score   support

           0       0.52      0.40      0.45       166
           1       0.53      0.54      0.53       170
           2       0.78      0.99      0.87       125

    accuracy                           0.61       461
   macro avg       0.61      0.64      0.62       461
weighted avg       0.59      0.61      0.60       461

Confusion matrix:
 [[ 67  80  19]
 [ 62  91  17]
 [  0   1 124]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                               feature  importance
259        eye__fix_duration_AOI_aggregated_Neg_median   14.513194
36               eye__sac_speed_AOI_aggregated_Neg_min   12.616983
38              eye__sac_speed_AOI_aggregated_Neg_mean   10.442752
35            eye__sac_length_AOI_aggregated_Neg_count    7.934175
58              eye__sac_length_AOI_aggregated_Pos_sum    7.221473
255         eye__fix_duration_AOI_aggregated_Neg_first    5.983339
61               eye__sac_speed_AOI_aggregated_Pos_max    5.916427
60               eye__sac_speed_AOI_aggregated_Pos_min    4.631215
264         eye__fix_duration_AOI_aggregated_Neg_count    4.566958
184                eye__fix_duration_AOI_FD_Neg1_count    3.461729
213                  eye__fix_duration_AOI_FD_Pos1_sum    2.920501
62              eye__sac_speed_AOI_aggregated_Pos_mean    2.906845
207                  eye__fix_duration_AOI_FD_Pos1_max    2.165341
523                                     stat__umap_053    1.583626
46             eye__sac_length_AOI_aggregated_None_sum    1.324633
271     eye__fix_duration_AOI_aggregated_None_kurtosis    0.919682
0                                  eye__sac_length_min    0.808282
98   eye__sac_speed_from_Pos_to_Target_from_Pos_to_...    0.797253
568                                     stat__umap_098    0.677459
87   eye__sac_speed_from_Neg_to_Target_from_Neg_to_...    0.673844
274        eye__fix_duration_AOI_aggregated_None_count    0.671153
194                eye__fix_duration_AOI_FD_None_count    0.620155
191             eye__fix_duration_AOI_FD_None_kurtosis    0.608025
495                                     stat__umap_025    0.453127
79   eye__sac_length_from_Neg_to_Target_from_Neg_to...    0.444061
508                                     stat__umap_038    0.409746
505                                     stat__umap_035    0.396361
97   eye__sac_speed_from_Pos_to_Target_from_Pos_to_...    0.383435
488                                     stat__umap_018    0.376676
394                 eye__det_euclidean_length_1_rho_25    0.369266

[stat] rows missing after index match -> train: 1832, test: 187
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-10 14:52:54,485] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 14:52:59,458] Trial 0 finished with value: 0.4542438307731913 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.4542438307731913.
[I 2026-04-10 14:53:05,186] Trial 1 finished with value: 0.4497775210497654 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.4542438307731913.
[I 2026-04-10 14:53:10,955] Trial 2 finished with value: 0.45052445152588505 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.4542438307731913.
[I 2026-04-10 14:53:16,181] Trial 3 finished with value: 0.449720936144306 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.4542438307731913.
[I 2026-04-10 14:53:22,134] Trial 4 finished with value: 0.49678710303812657 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:28,599] Trial 5 finished with value: 0.47269359725885135 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:33,746] Trial 6 finished with value: 0.4709404471466637 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:40,876] Trial 7 finished with value: 0.4622431853856275 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:46,668] Trial 8 finished with value: 0.4681596080377467 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:54,551] Trial 9 finished with value: 0.43827043917769865 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:53:59,543] Trial 10 finished with value: 0.4539868691296507 and parameters: {'learning_rate': 0.07985847190685645, 'max_depth': 8, 'min_child_weight': 5.7644975171451085, 'subsample': 0.8853830026900457, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4769827267624924, 'reg_alpha': 9.072541150259902, 'reg_lambda': 0.00015423477789158795}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:06,076] Trial 11 finished with value: 0.43953600665978343 and parameters: {'learning_rate': 0.05603078838330604, 'max_depth': 7, 'min_child_weight': 6.189915253734567, 'subsample': 0.9978302082199063, 'colsample_bytree': 0.8245896337220607, 'gamma': 1.4455861182253593, 'reg_alpha': 0.012651599006804258, 'reg_lambda': 0.005133571338118793}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:10,996] Trial 12 finished with value: 0.4562856669951701 and parameters: {'learning_rate': 0.06742246852069361, 'max_depth': 3, 'min_child_weight': 5.9752070205206556, 'subsample': 0.9199196696056875, 'colsample_bytree': 0.999748196231103, 'gamma': 0.4948823463977708, 'reg_alpha': 0.001646769566762215, 'reg_lambda': 0.008034390020894974}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:17,605] Trial 13 finished with value: 0.4460228663006429 and parameters: {'learning_rate': 0.047540081707996756, 'max_depth': 7, 'min_child_weight': 9.331580799667103, 'subsample': 0.9825961012116274, 'colsample_bytree': 0.7071124854874881, 'gamma': 1.969698580906368, 'reg_alpha': 0.08530325950319723, 'reg_lambda': 0.00015764742688390395}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:24,489] Trial 14 finished with value: 0.4766096179693967 and parameters: {'learning_rate': 0.10371773199355588, 'max_depth': 7, 'min_child_weight': 4.761740157031387, 'subsample': 0.9160122134884335, 'colsample_bytree': 0.8979423852414217, 'gamma': 0.07785518835685812, 'reg_alpha': 0.00010480002361979782, 'reg_lambda': 0.008445970991867896}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:30,587] Trial 15 finished with value: 0.4726218074056177 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 7, 'min_child_weight': 2.4370747834999373, 'subsample': 0.9117399378246747, 'colsample_bytree': 0.9066375832522441, 'gamma': 0.8689851452860138, 'reg_alpha': 0.00019276792016837205, 'reg_lambda': 0.0008692052596681178}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:37,758] Trial 16 finished with value: 0.4665021791271335 and parameters: {'learning_rate': 0.08533042118530673, 'max_depth': 8, 'min_child_weight': 4.672530518334317, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.9103699897752633, 'gamma': 1.2940919465662697, 'reg_alpha': 0.00010543860087248106, 'reg_lambda': 0.01823398289539074}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:44,522] Trial 17 finished with value: 0.45566089972631707 and parameters: {'learning_rate': 0.12818012641007476, 'max_depth': 7, 'min_child_weight': 2.77059802128678, 'subsample': 0.835143889525212, 'colsample_bytree': 0.8371000028968741, 'gamma': 0.559565273069881, 'reg_alpha': 0.0031754095364727253, 'reg_lambda': 0.002833771849527033}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:50,673] Trial 18 finished with value: 0.4630869073763291 and parameters: {'learning_rate': 0.06849214977957828, 'max_depth': 7, 'min_child_weight': 4.345615590300492, 'subsample': 0.9318271613739229, 'colsample_bytree': 0.8786990961987029, 'gamma': 1.7292640858385435, 'reg_alpha': 0.9672593308444457, 'reg_lambda': 0.00036460414934968006}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:54:56,892] Trial 19 finished with value: 0.44186581449787876 and parameters: {'learning_rate': 0.10392466254293156, 'max_depth': 8, 'min_child_weight': 6.724980004202298, 'subsample': 0.8742739930443821, 'colsample_bytree': 0.9593148012239937, 'gamma': 0.2731142686509397, 'reg_alpha': 0.0006600338646861673, 'reg_lambda': 0.2028286802625633}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:55:02,393] Trial 20 finished with value: 0.48414691378134694 and parameters: {'learning_rate': 0.1548075715732674, 'max_depth': 4, 'min_child_weight': 2.4918965888983133, 'subsample': 0.9013560123276296, 'colsample_bytree': 0.9152865652623268, 'gamma': 0.7952258517349472, 'reg_alpha': 0.14254713605422456, 'reg_lambda': 0.017348574039185}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:55:07,695] Trial 21 finished with value: 0.46106803975894817 and parameters: {'learning_rate': 0.19029346809733624, 'max_depth': 4, 'min_child_weight': 2.3047375004058175, 'subsample': 0.902216177979539, 'colsample_bytree': 0.9109841952487913, 'gamma': 0.7676954991803082, 'reg_alpha': 0.09737130030451557, 'reg_lambda': 0.01930765677538556}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:55:12,609] Trial 22 finished with value: 0.48069575047909724 and parameters: {'learning_rate': 0.14684978174482233, 'max_depth': 3, 'min_child_weight': 1.0411844002676933, 'subsample': 0.8497380977890847, 'colsample_bytree': 0.9869515892269317, 'gamma': 1.3266065687769162, 'reg_alpha': 0.25606373969269647, 'reg_lambda': 0.0028022858308602524}. Best is trial 4 with value: 0.49678710303812657.
[I 2026-04-10 14:55:17,474] Trial 23 finished with value: 0.5119226244710557 and parameters: {'learning_rate': 0.14635834833527492, 'max_depth': 3, 'min_child_weight': 1.296975968039863, 'subsample': 0.8241663692387317, 'colsample_bytree': 0.9926829952571687, 'gamma': 1.2372774008368206, 'reg_alpha': 0.4137998161446513, 'reg_lambda': 0.0014635708172616331}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:22,731] Trial 24 finished with value: 0.4459826677611908 and parameters: {'learning_rate': 0.14297839174327748, 'max_depth': 4, 'min_child_weight': 1.004947991011469, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.9407281831506489, 'gamma': 1.2142557641285938, 'reg_alpha': 0.6170675227769657, 'reg_lambda': 0.0004549499536533644}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:27,104] Trial 25 finished with value: 0.45363724788717996 and parameters: {'learning_rate': 0.15188192347420104, 'max_depth': 3, 'min_child_weight': 1.9171660719723147, 'subsample': 0.8896282632425061, 'colsample_bytree': 0.9622063022797849, 'gamma': 1.6858204975700013, 'reg_alpha': 4.299963071183629, 'reg_lambda': 0.00135399580538343}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:32,263] Trial 26 finished with value: 0.4873584164458213 and parameters: {'learning_rate': 0.18971192603822265, 'max_depth': 4, 'min_child_weight': 1.285640852463408, 'subsample': 0.9489958641316353, 'colsample_bytree': 0.9345933237457225, 'gamma': 0.9459634809291066, 'reg_alpha': 0.0630107237088706, 'reg_lambda': 0.020945248829040797}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:36,927] Trial 27 finished with value: 0.47423871290984765 and parameters: {'learning_rate': 0.19959839833792142, 'max_depth': 3, 'min_child_weight': 1.2903790587289106, 'subsample': 0.9420891179543777, 'colsample_bytree': 0.9828824946194585, 'gamma': 0.9925717200855599, 'reg_alpha': 0.05074795147704276, 'reg_lambda': 0.00035756316269210055}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:42,585] Trial 28 finished with value: 0.47005235066603174 and parameters: {'learning_rate': 0.08342488697243093, 'max_depth': 4, 'min_child_weight': 1.3131944899091792, 'subsample': 0.9563279518758412, 'colsample_bytree': 0.9331237826949108, 'gamma': 1.5145913166538376, 'reg_alpha': 0.012734016978132968, 'reg_lambda': 0.0036070196966529753}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:47,797] Trial 29 finished with value: 0.493025400017993 and parameters: {'learning_rate': 0.1251222775170421, 'max_depth': 4, 'min_child_weight': 3.6987519235600392, 'subsample': 0.8611025539794476, 'colsample_bytree': 0.9529059243849687, 'gamma': 1.8342602443761291, 'reg_alpha': 0.6928968290407976, 'reg_lambda': 0.28241799609129575}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:52,905] Trial 30 finished with value: 0.48605917489892214 and parameters: {'learning_rate': 0.11506637355420017, 'max_depth': 3, 'min_child_weight': 3.7340276907689707, 'subsample': 0.8169585822814927, 'colsample_bytree': 0.9969010138313844, 'gamma': 1.811251595414335, 'reg_alpha': 0.6965087411537346, 'reg_lambda': 3.8719776140021116}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:55:58,014] Trial 31 finished with value: 0.4943520523550522 and parameters: {'learning_rate': 0.13712931629887465, 'max_depth': 4, 'min_child_weight': 3.627903217808344, 'subsample': 0.8570923411225502, 'colsample_bytree': 0.9509485928878287, 'gamma': 1.5750427275828163, 'reg_alpha': 0.3634767271450039, 'reg_lambda': 1.052513045378373}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:04,072] Trial 32 finished with value: 0.4665761845849561 and parameters: {'learning_rate': 0.09256728112720057, 'max_depth': 5, 'min_child_weight': 3.5246456543516294, 'subsample': 0.8530226019292576, 'colsample_bytree': 0.9664381621183683, 'gamma': 1.5829341358616913, 'reg_alpha': 2.03024567890628, 'reg_lambda': 8.541729896188427}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:08,310] Trial 33 finished with value: 0.4568965180205996 and parameters: {'learning_rate': 0.12753553899329606, 'max_depth': 3, 'min_child_weight': 7.390544267281987, 'subsample': 0.8126857852934956, 'colsample_bytree': 0.9543105131060206, 'gamma': 1.8427239656438112, 'reg_alpha': 0.4343163951510108, 'reg_lambda': 0.5463557789281764}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:12,866] Trial 34 finished with value: 0.4560374146774079 and parameters: {'learning_rate': 0.07387974626350594, 'max_depth': 4, 'min_child_weight': 5.143740239082637, 'subsample': 0.871203807508141, 'colsample_bytree': 0.9801466505522847, 'gamma': 1.7794572467140615, 'reg_alpha': 3.4913816507357156, 'reg_lambda': 1.7655429317422575}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:18,466] Trial 35 finished with value: 0.4505224381873106 and parameters: {'learning_rate': 0.1053365974854385, 'max_depth': 5, 'min_child_weight': 4.067241492508067, 'subsample': 0.7583363771866218, 'colsample_bytree': 0.9261677071059683, 'gamma': 1.3667527093706497, 'reg_alpha': 0.22346327431096524, 'reg_lambda': 1.2101131553726938}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:23,435] Trial 36 finished with value: 0.4762909170630174 and parameters: {'learning_rate': 0.16530362979196403, 'max_depth': 4, 'min_child_weight': 2.967413166612368, 'subsample': 0.8461617255748067, 'colsample_bytree': 0.774037819678975, 'gamma': 1.6119894765907696, 'reg_alpha': 0.3320270185098544, 'reg_lambda': 0.2994971249431535}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:30,827] Trial 37 finished with value: 0.47032094460653495 and parameters: {'learning_rate': 0.03771107996234771, 'max_depth': 5, 'min_child_weight': 2.0612736529280333, 'subsample': 0.7100433549147293, 'colsample_bytree': 0.8878803607207294, 'gamma': 1.912156037783258, 'reg_alpha': 1.0700605772697864, 'reg_lambda': 0.06045009677735278}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:35,647] Trial 38 finished with value: 0.4581773243125137 and parameters: {'learning_rate': 0.13676657223596078, 'max_depth': 3, 'min_child_weight': 3.7805982574319486, 'subsample': 0.8634879045501628, 'colsample_bytree': 0.9479203956928358, 'gamma': 1.9967325376063068, 'reg_alpha': 0.03162468017817588, 'reg_lambda': 0.10174684050630985}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:42,941] Trial 39 finished with value: 0.4315373401537173 and parameters: {'learning_rate': 0.0609022343211986, 'max_depth': 6, 'min_child_weight': 1.601876803909072, 'subsample': 0.8296585961706634, 'colsample_bytree': 0.8636535256079341, 'gamma': 1.1922673446887277, 'reg_alpha': 0.13659434115062052, 'reg_lambda': 0.33461622813468633}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:48,610] Trial 40 finished with value: 0.49394762304768547 and parameters: {'learning_rate': 0.09425208705401046, 'max_depth': 5, 'min_child_weight': 3.2150207441363143, 'subsample': 0.7282571436393164, 'colsample_bytree': 0.8139718825083427, 'gamma': 1.5940229862035928, 'reg_alpha': 4.158789189227485, 'reg_lambda': 1.2125172620094113}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:53,460] Trial 41 finished with value: 0.4599221137702308 and parameters: {'learning_rate': 0.09311311930742017, 'max_depth': 5, 'min_child_weight': 3.4828955322204624, 'subsample': 0.7560156138064845, 'colsample_bytree': 0.8031612703257403, 'gamma': 1.5770044156476073, 'reg_alpha': 6.010256480942131, 'reg_lambda': 1.6847813834190504}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:56:58,166] Trial 42 finished with value: 0.5055825319644437 and parameters: {'learning_rate': 0.11615259773262708, 'max_depth': 4, 'min_child_weight': 3.3016909917497945, 'subsample': 0.7312503852170777, 'colsample_bytree': 0.8121249685019469, 'gamma': 1.6830655446932812, 'reg_alpha': 2.2364959782562543, 'reg_lambda': 0.9393843129947649}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:03,287] Trial 43 finished with value: 0.4703362712497666 and parameters: {'learning_rate': 0.11479742286112593, 'max_depth': 5, 'min_child_weight': 2.7721612161626843, 'subsample': 0.7326495588839089, 'colsample_bytree': 0.8056584433048727, 'gamma': 1.4275133884856561, 'reg_alpha': 2.786663505350214, 'reg_lambda': 4.035202295185456}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:11,489] Trial 44 finished with value: 0.45460780460305 and parameters: {'learning_rate': 0.02188029840119486, 'max_depth': 6, 'min_child_weight': 7.631277901843356, 'subsample': 0.7030205557370574, 'colsample_bytree': 0.781237865280041, 'gamma': 1.715019122078859, 'reg_alpha': 1.6506257560481084, 'reg_lambda': 1.023118171308884}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:16,960] Trial 45 finished with value: 0.43998386214371826 and parameters: {'learning_rate': 0.1669257483480678, 'max_depth': 5, 'min_child_weight': 3.170275379140767, 'subsample': 0.7281139862298035, 'colsample_bytree': 0.8293295912652207, 'gamma': 1.4943374376774177, 'reg_alpha': 1.3511360217717396, 'reg_lambda': 9.716249134050667}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:23,738] Trial 46 finished with value: 0.4326085512916924 and parameters: {'learning_rate': 0.07775314987930908, 'max_depth': 6, 'min_child_weight': 2.197355304433547, 'subsample': 0.7704001113574357, 'colsample_bytree': 0.8453609386205689, 'gamma': 1.633817973687959, 'reg_alpha': 0.4920758017774271, 'reg_lambda': 0.6901495979559573}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:28,514] Trial 47 finished with value: 0.4619130501842808 and parameters: {'learning_rate': 0.09026471974225565, 'max_depth': 4, 'min_child_weight': 5.197315020792321, 'subsample': 0.8002016032519073, 'colsample_bytree': 0.8148294742800432, 'gamma': 1.1828569492905567, 'reg_alpha': 9.508868542516439, 'reg_lambda': 2.7499276723945303}. Best is trial 23 with value: 0.5119226244710557.
[I 2026-04-10 14:57:33,840] Trial 48 finished with value: 0.497040546847348 and parameters: {'learning_rate': 0.09823595644031928, 'max_depth': 5, 'min_child_weight': 1.6401368402710708, 'subsample': 0.7404067384519255, 'colsample_bytree': 0.7849789949230177, 'gamma': 1.4158559697255926, 'reg_alpha': 5.092286696609204, 'reg_lambda': 0.13938678315100064}. Best is trial 23 with value: 0.5119226244710557.

[I 2026-04-10 15:01:54,801] A new study created in memory with name: binary_catboost

[I 2026-04-10 15:01:54,798] Trial 99 finished with value: 0.47205417541768724 and parameters: {'learning_rate': 0.17247915410389053, 'max_depth': 3, 'min_child_weight': 9.552792942567976, 'subsample': 0.7065798828732923, 'colsample_bytree': 0.7008118241696909, 'gamma': 1.3939809594173638, 'reg_alpha': 0.004589483220645772, 'reg_lambda': 0.0019162631868715435}. Best is trial 69 with value: 0.5166479171715253.

Best model (xgb) CV score: 0.51665
Best params: {'learning_rate': 0.12791310386338053, 'max_depth': 5, 'min_child_weight': 5.006808336621269, 'subsample': 0.7124518097600581, 'colsample_bytree': 0.7830012936824529, 'gamma': 1.750719659258102, 'reg_alpha': 0.5099697914134839, 'reg_lambda': 0.004922735775198206}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 15:02:00,620] Trial 0 finished with value: 0.4641299778737355 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4641299778737355.
[I 2026-04-10 15:02:12,640] Trial 1 finished with value: 0.5042510673836806 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5042510673836806.
[I 2026-04-10 15:02:21,704] Trial 2 finished with value: 0.49840015570957547 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.5042510673836806.
[I 2026-04-10 15:02:38,574] Trial 3 finished with value: 0.5127031513249045 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5127031513249045.
[I 2026-04-10 15:02:58,133] Trial 4 finished with value: 0.5497391171725781 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:03:29,583] Trial 5 finished with value: 0.5150806535246399 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:03:47,911] Trial 6 finished with value: 0.4919381989855148 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:04:14,468] Trial 7 finished with value: 0.4696474658664822 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:05:00,086] Trial 8 finished with value: 0.46930905343544793 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:05:13,225] Trial 9 finished with value: 0.4932967425545753 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:05:18,066] Trial 10 finished with value: 0.5031488058901342 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:05:38,085] Trial 11 finished with value: 0.516086966042867 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17040099770125652, 'depth': 8, 'l2_leaf_reg': 3.747473826638779, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12665706747865135}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:05:58,244] Trial 12 finished with value: 0.5444857749284187 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 2.6880148841981213, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.566664895898511}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:06:18,719] Trial 13 finished with value: 0.5418086467626854 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 8, 'l2_leaf_reg': 2.3484710269750506, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9139832467937251}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:06:31,354] Trial 14 finished with value: 0.5399517492699678 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11980834084297441, 'depth': 7, 'l2_leaf_reg': 1.0042999777217867, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8424234616468694}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:06:38,230] Trial 15 finished with value: 0.531729483332299 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1983058867595879, 'depth': 6, 'l2_leaf_reg': 2.566528746990451, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.1476548084452305}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:06:58,610] Trial 16 finished with value: 0.532587129692731 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12769952952541253, 'depth': 8, 'l2_leaf_reg': 1.4536742812967862, 'random_strength': 0.09255807539467345, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.81657743120335}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:07:11,105] Trial 17 finished with value: 0.5182150676324184 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14275466267871886, 'depth': 7, 'l2_leaf_reg': 3.1473461970805605, 'random_strength': 0.4440752281517034, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.3482608843364388}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:07:20,472] Trial 18 finished with value: 0.47023005452238825 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03658019444872611, 'depth': 5, 'l2_leaf_reg': 1.4078460751151975, 'random_strength': 0.22683551332574908, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.284517710941218}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:07:42,862] Trial 19 finished with value: 0.5137601736425704 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10082895789437417, 'depth': 8, 'l2_leaf_reg': 5.006896390200882, 'random_strength': 0.08594438316270561, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6006784563476701}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:07:50,125] Trial 20 finished with value: 0.5205216828009669 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16003507395365793, 'depth': 6, 'l2_leaf_reg': 6.548528117273506, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9951687696099387}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:08:11,844] Trial 21 finished with value: 0.5441733387406718 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11574413589416342, 'depth': 8, 'l2_leaf_reg': 2.6028936606763473, 'random_strength': 0.008924457378010748, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8752035810416156}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:08:31,496] Trial 22 finished with value: 0.5356930804645637 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19883740207438072, 'depth': 8, 'l2_leaf_reg': 2.6466400475668244, 'random_strength': 0.0007976720012887982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8691789063359949}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:08:42,749] Trial 23 finished with value: 0.5218292899204422 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10986685370376416, 'depth': 7, 'l2_leaf_reg': 2.001717986584308, 'random_strength': 0.07542867169203196, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7575016462999107}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:09:03,641] Trial 24 finished with value: 0.5330832966248614 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14905433746556937, 'depth': 8, 'l2_leaf_reg': 3.0806305372954204, 'random_strength': 0.2316884681027302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7680744849594581}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:09:17,063] Trial 25 finished with value: 0.5170903517599419 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05829916383468929, 'depth': 7, 'l2_leaf_reg': 1.4423972004819452, 'random_strength': 0.37909571302872885, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8879620190692518}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:09:37,465] Trial 26 finished with value: 0.52106002415896 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14311609806197523, 'depth': 8, 'l2_leaf_reg': 3.501880494280505, 'random_strength': 0.09525429183661689, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.3380733010652666}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:09:41,986] Trial 27 finished with value: 0.5269428209148126 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17136304612470854, 'depth': 5, 'l2_leaf_reg': 2.1669893553518667, 'random_strength': 0.24513139323349786, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9704819931630654}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:09:55,006] Trial 28 finished with value: 0.4672456750941486 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1961380278855692, 'depth': 7, 'l2_leaf_reg': 5.789888795256498, 'random_strength': 0.06358331394673271, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 3.7489196797792594}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:10:20,138] Trial 29 finished with value: 0.5191482743095047 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09947265237671638, 'depth': 8, 'l2_leaf_reg': 1.6528570206743902, 'random_strength': 0.1408851011800677, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.7738066445496041}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:10:43,207] Trial 30 finished with value: 0.5235542204743808 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06695389000596022, 'depth': 8, 'l2_leaf_reg': 1.2335806116000338, 'random_strength': 0.1640627898154589, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7133565573933586}. Best is trial 4 with value: 0.5497391171725781.
[I 2026-04-10 15:11:04,357] Trial 31 finished with value: 0.5538481913287718 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12761995533472953, 'depth': 8, 'l2_leaf_reg': 2.517106327549094, 'random_strength': 0.00932374999107674, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9395015466573928}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:11:24,985] Trial 32 finished with value: 0.5444866468178351 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13482320389668478, 'depth': 8, 'l2_leaf_reg': 2.9295427035130492, 'random_strength': 0.04254593882314693, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9456752576949073}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:11:28,717] Trial 33 finished with value: 0.5207329890160429 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13466871601905053, 'depth': 4, 'l2_leaf_reg': 1.9294219108755344, 'random_strength': 0.13721527640260495, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.954590618261972}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:11:40,319] Trial 34 finished with value: 0.5435818330736152 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16239492735730487, 'depth': 7, 'l2_leaf_reg': 3.026361105140059, 'random_strength': 0.2073878618456078, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9979235787949021}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:12:11,231] Trial 35 finished with value: 0.5258945446912267 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 8, 'l2_leaf_reg': 3.736996459650334, 'random_strength': 0.051669359488719584, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8122673880026917}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:12:23,652] Trial 36 finished with value: 0.5320858463726986 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15025482443850027, 'depth': 7, 'l2_leaf_reg': 2.2268464378857593, 'random_strength': 0.11518630638584501, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9226322517211356}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:12:46,423] Trial 37 finished with value: 0.5424356621782294 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08641004748210981, 'depth': 8, 'l2_leaf_reg': 1.6274657112576596, 'random_strength': 0.31939439335392683, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8480272279548515}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:13:26,311] Trial 38 finished with value: 0.5014699106640581 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.057935982273818215, 'depth': 8, 'l2_leaf_reg': 1.1955679943755502, 'random_strength': 0.2705101647913263, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.032250724631051}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:13:37,366] Trial 39 finished with value: 0.5276529215182753 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17462358073589584, 'depth': 7, 'l2_leaf_reg': 4.088649199334818, 'random_strength': 0.17959188035620732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7296302621811005}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:13:41,494] Trial 40 finished with value: 0.5034891544846531 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08699117658544306, 'depth': 4, 'l2_leaf_reg': 10.06795044277389, 'random_strength': 0.3799062750278092, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.7600869898375504}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:14:02,559] Trial 41 finished with value: 0.5303733933246055 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.115426411313793, 'depth': 8, 'l2_leaf_reg': 2.6857653036072864, 'random_strength': 0.03879561138101794, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8904640941364509}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:14:23,520] Trial 42 finished with value: 0.5426792952518474 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1051594171123038, 'depth': 8, 'l2_leaf_reg': 2.80400312528174, 'random_strength': 0.05230571459956761, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9549612111175918}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:14:44,703] Trial 43 finished with value: 0.526215878045219 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13018529152486347, 'depth': 8, 'l2_leaf_reg': 2.2380411811293452, 'random_strength': 0.006260337725128698, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9040336474448529}. Best is trial 31 with value: 0.5538481913287718.
[I 2026-04-10 15:15:06,221] Trial 44 finished with value: 0.5155268853137748 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18663046515975554, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.12718756288503752, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8616570745957896}. Best is trial 31 with value: 0.5538481913287718.

                                         feature  importance
183            eye__fix_duration_AOI_FD_Neg1_sum    0.051734
276     eye__fix_duration_AOI_aggregated_Pos_min    0.046382
53        eye__sac_length_AOI_aggregated_Pos_min    0.032966
284   eye__fix_duration_AOI_aggregated_Pos_count    0.031160
175          eye__fix_duration_AOI_FD_Neg1_first    0.028344
38        eye__sac_speed_AOI_aggregated_Neg_mean    0.025569
278    eye__fix_duration_AOI_aggregated_Pos_mean    0.024519
55       eye__sac_length_AOI_aggregated_Pos_mean    0.019580
556                               stat__umap_086    0.018981
60         eye__sac_speed_AOI_aggregated_Pos_min    0.017325
279  eye__fix_duration_AOI_aggregated_Pos_median    0.016404
355         eye__lyapunov_exponent_m_3_tau_1_T_4    0.015349
528                               stat__umap_058    0.014119
302                         eye__fuzzy_m_4_r_400    0.014028
538                               stat__umap_068    0.013456
547                               stat__umap_077    0.013224
545                               stat__umap_075    0.012456
335                eye__sample_entropy_m=2_r=400    0.012370
395           eye__lam_euclidean_length_1_rho_25    0.012359
314                     eye__incremental_entropy    0.011782
56     eye__sac_length_AOI_aggregated_Pos_median    0.011612
471                               stat__umap_001    0.011415
401   eye__rec_metric_euclidean_length_1_rho_250    0.011384
338                eye__sample_entropy_m=3_r=100    0.011053
422          eye__det_euclidean_length_2_rho_250    0.010595
568                               stat__umap_098    0.010488
348         eye__lyapunov_exponent_m_2_tau_1_T_2    0.010442
492                               stat__umap_022    0.010102
537                               stat__umap_067    0.010011
477                               stat__umap_007    0.009973

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.55490
              precision    recall  f1-score   support

           0       0.70      0.87      0.78       306
           1       0.50      0.25      0.33       155

    accuracy                           0.66       461
   macro avg       0.60      0.56      0.55       461
weighted avg       0.63      0.66      0.63       461

Confusion matrix:
 [[267  39]
 [116  39]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
60         eye__sac_speed_AOI_aggregated_Pos_min   14.873290
473                               stat__umap_003    8.109581
183            eye__fix_duration_AOI_FD_Neg1_sum    7.786923
29        eye__sac_length_AOI_aggregated_Neg_min    5.695653
34        eye__sac_length_AOI_aggregated_Neg_sum    4.399365
510                               stat__umap_040    3.980217
465                                eye__imf0_max    3.847678
464                                eye__imf0_min    3.547633
401   eye__rec_metric_euclidean_length_1_rho_250    2.311175
537                               stat__umap_067    2.236311
32     eye__sac_length_AOI_aggregated_Neg_median    2.137103
17                      eye__sac_angle_to_x_mean    1.946743
11                         eye__sac_speed_median    1.877399
478                               stat__umap_008    1.732490
525                               stat__umap_055    1.623515
256     eye__fix_duration_AOI_aggregated_Neg_min    1.529182
279  eye__fix_duration_AOI_aggregated_Pos_median    1.514163
515                               stat__umap_045    1.448762
15                       eye__sac_angle_to_x_min    1.369118
53        eye__sac_length_AOI_aggregated_Pos_min    1.276321
309                 eye__phase_entropy_m_4_tau_2    1.203593
486                               stat__umap_016    1.167807
28                   eye__sac_angle_between_skew    1.104747
472                               stat__umap_002    1.090797
8                             eye__sac_speed_min    1.044994
552                               stat__umap_082    1.024982
354         eye__lyapunov_exponent_m_3_tau_1_T_2    1.001503
173                        eye__fix_duration_sum    0.980474
395           eye__lam_euclidean_length_1_rho_25    0.947494
370                   eye__fractal_dim_m_4_tau_2    0.936698

[stat] rows missing after index match -> train: 1832, test: 187
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-10 15:17:58,408] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-10 15:18:13,768] Trial 0 finished with value: 0.6659585795288199 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:18:26,523] Trial 1 finished with value: 0.6442377737158883 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:18:44,690] Trial 2 finished with value: 0.6631430851234643 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:18:55,441] Trial 3 finished with value: 0.658642360464435 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:19:06,353] Trial 4 finished with value: 0.6561525857438 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:19:22,896] Trial 5 finished with value: 0.6481536324946698 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.6659585795288199.
[I 2026-04-10 15:19:30,138] Trial 6 finished with value: 0.6726747572955154 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:19:50,819] Trial 7 finished with value: 0.6574193463467932 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:00,674] Trial 8 finished with value: 0.6593397302212295 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:29,706] Trial 9 finished with value: 0.6587670459129039 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:37,023] Trial 10 finished with value: 0.665988148504066 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:44,151] Trial 11 finished with value: 0.664033857996224 and parameters: {'learning_rate': 0.19928490475258703, 'max_depth': 3, 'min_child_weight': 2.3108399558144663, 'subsample': 0.7003857515532862, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.5525904909866688, 'reg_alpha': 0.000185939809238877, 'reg_lambda': 5.991143401742846}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:52,196] Trial 12 finished with value: 0.6676164504775285 and parameters: {'learning_rate': 0.13890160106568872, 'max_depth': 3, 'min_child_weight': 1.1710422715470166, 'subsample': 0.7448378414577058, 'colsample_bytree': 0.8629975808647283, 'gamma': 1.3835099137413096, 'reg_alpha': 0.002747173075943202, 'reg_lambda': 1.1176528058255835}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:20:58,526] Trial 13 finished with value: 0.6665446620487101 and parameters: {'learning_rate': 0.1395445738342445, 'max_depth': 4, 'min_child_weight': 5.32911732339547, 'subsample': 0.8406163099536311, 'colsample_bytree': 0.8218438182916648, 'gamma': 1.980864894875216, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.5826939555612602}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:09,079] Trial 14 finished with value: 0.6707583735599209 and parameters: {'learning_rate': 0.08176705251458778, 'max_depth': 4, 'min_child_weight': 2.228775599913356, 'subsample': 0.7533165692412906, 'colsample_bytree': 0.8881699126650688, 'gamma': 1.3373977625256825, 'reg_alpha': 0.0063169573211942845, 'reg_lambda': 0.6522425729176119}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:19,771] Trial 15 finished with value: 0.6619162077135355 and parameters: {'learning_rate': 0.07493979204046018, 'max_depth': 4, 'min_child_weight': 2.4370747834999373, 'subsample': 0.8312007996434815, 'colsample_bytree': 0.8997199704416934, 'gamma': 1.2513887824418548, 'reg_alpha': 0.021812466956831665, 'reg_lambda': 0.00016599250040776937}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:28,443] Trial 16 finished with value: 0.6592774411348025 and parameters: {'learning_rate': 0.10719331164243828, 'max_depth': 5, 'min_child_weight': 2.480939316275052, 'subsample': 0.7530229364402534, 'colsample_bytree': 0.8984310486157346, 'gamma': 1.799148334078496, 'reg_alpha': 0.008983863676974733, 'reg_lambda': 0.2512688475082513}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:42,234] Trial 17 finished with value: 0.6601389322913385 and parameters: {'learning_rate': 0.06071847403900251, 'max_depth': 4, 'min_child_weight': 6.663639311118699, 'subsample': 0.8138950278678949, 'colsample_bytree': 0.9964340432341179, 'gamma': 0.7484292950465277, 'reg_alpha': 0.001098660424711482, 'reg_lambda': 0.018867535841271068}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:51,831] Trial 18 finished with value: 0.6624843581856891 and parameters: {'learning_rate': 0.09330137070176413, 'max_depth': 7, 'min_child_weight': 4.189270561764596, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.8246945505628626, 'gamma': 1.997994039671716, 'reg_alpha': 0.05965442475265956, 'reg_lambda': 1.9253855625275396}. Best is trial 6 with value: 0.6726747572955154.
[I 2026-04-10 15:21:59,700] Trial 19 finished with value: 0.6739730848423654 and parameters: {'learning_rate': 0.1508961678558086, 'max_depth': 5, 'min_child_weight': 2.030844927398802, 'subsample': 0.7421659449956863, 'colsample_bytree': 0.8994256574897828, 'gamma': 1.2763326476302224, 'reg_alpha': 0.5974912510135608, 'reg_lambda': 0.2684849324718805}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:08,395] Trial 20 finished with value: 0.6526619535402277 and parameters: {'learning_rate': 0.14443982274151962, 'max_depth': 7, 'min_child_weight': 7.320479695283187, 'subsample': 0.8664465043311603, 'colsample_bytree': 0.825964897176414, 'gamma': 0.8671413398772443, 'reg_alpha': 0.7431839359395703, 'reg_lambda': 0.012990779275666834}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:18,142] Trial 21 finished with value: 0.6571440561540585 and parameters: {'learning_rate': 0.12098051998472621, 'max_depth': 5, 'min_child_weight': 1.9285633820502484, 'subsample': 0.7512054439093984, 'colsample_bytree': 0.8976212353284782, 'gamma': 1.2515613970991164, 'reg_alpha': 6.667764044747457, 'reg_lambda': 0.27545125981470864}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:25,319] Trial 22 finished with value: 0.6611679546678372 and parameters: {'learning_rate': 0.15248211455347324, 'max_depth': 4, 'min_child_weight': 2.9573288124343406, 'subsample': 0.7285512056785656, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.6708768224551442, 'reg_alpha': 0.014813659607326567, 'reg_lambda': 0.191780868419138}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:36,139] Trial 23 finished with value: 0.6568599294743696 and parameters: {'learning_rate': 0.08204268106817622, 'max_depth': 5, 'min_child_weight': 1.5190096656851277, 'subsample': 0.8104993072670958, 'colsample_bytree': 0.887321625237362, 'gamma': 1.2596925705892716, 'reg_alpha': 0.0760399149297615, 'reg_lambda': 0.8955842908358148}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:45,970] Trial 24 finished with value: 0.6616603393967161 and parameters: {'learning_rate': 0.16789914754000484, 'max_depth': 4, 'min_child_weight': 2.0644960209102368, 'subsample': 0.7001781393167994, 'colsample_bytree': 0.9195272994512828, 'gamma': 0.4612476301307389, 'reg_alpha': 0.04164072903784178, 'reg_lambda': 3.869089254689021}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:22:55,344] Trial 25 finished with value: 0.6677859720998107 and parameters: {'learning_rate': 0.12560997436972032, 'max_depth': 5, 'min_child_weight': 2.7371739412791407, 'subsample': 0.7655936961240856, 'colsample_bytree': 0.872880242949677, 'gamma': 0.9740854309528459, 'reg_alpha': 0.008180631973674617, 'reg_lambda': 0.3873464602786107}. Best is trial 19 with value: 0.6739730848423654.
[I 2026-04-10 15:23:06,699] Trial 26 finished with value: 0.6756106472742001 and parameters: {'learning_rate': 0.060976354636957275, 'max_depth': 3, 'min_child_weight': 3.6970791401297953, 'subsample': 0.7387071073035839, 'colsample_bytree': 0.8386843696454813, 'gamma': 1.4026702936653823, 'reg_alpha': 0.001501143159389054, 'reg_lambda': 1.6774713156708425}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:23:20,275] Trial 27 finished with value: 0.6708064202697449 and parameters: {'learning_rate': 0.04517011571923281, 'max_depth': 3, 'min_child_weight': 4.5492396175238135, 'subsample': 0.7297662165213779, 'colsample_bytree': 0.8408809889495475, 'gamma': 1.5683783790899097, 'reg_alpha': 0.001480860050210427, 'reg_lambda': 1.7481795848163493}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:23:32,371] Trial 28 finished with value: 0.6630204051123813 and parameters: {'learning_rate': 0.06195262260946557, 'max_depth': 8, 'min_child_weight': 9.676919498973382, 'subsample': 0.8088438067387685, 'colsample_bytree': 0.8084082010323955, 'gamma': 1.769275214449451, 'reg_alpha': 4.960933442166954, 'reg_lambda': 0.05597745584784731}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:23:44,110] Trial 29 finished with value: 0.6713392072620052 and parameters: {'learning_rate': 0.04759023941377886, 'max_depth': 3, 'min_child_weight': 3.7618515515612234, 'subsample': 0.7197258822892314, 'colsample_bytree': 0.7887529138760851, 'gamma': 1.1253096915871805, 'reg_alpha': 0.00048746225384536105, 'reg_lambda': 0.11329193889102686}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:24:04,875] Trial 30 finished with value: 0.6584926414760947 and parameters: {'learning_rate': 0.03363256231449593, 'max_depth': 6, 'min_child_weight': 5.450144525893764, 'subsample': 0.7397892192541853, 'colsample_bytree': 0.9660880477207299, 'gamma': 1.5192854681922228, 'reg_alpha': 0.5355908328801713, 'reg_lambda': 2.5352799840256495}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:24:17,803] Trial 31 finished with value: 0.6682350916015393 and parameters: {'learning_rate': 0.04572618327648617, 'max_depth': 3, 'min_child_weight': 3.2704821341526094, 'subsample': 0.7134611943631547, 'colsample_bytree': 0.773550426545445, 'gamma': 1.1501166498307842, 'reg_alpha': 0.00014015798581236262, 'reg_lambda': 0.11019239763604798}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:24:31,987] Trial 32 finished with value: 0.6678971346846445 and parameters: {'learning_rate': 0.0406683486697561, 'max_depth': 3, 'min_child_weight': 3.5710651516131118, 'subsample': 0.7165289941809863, 'colsample_bytree': 0.7854722272672946, 'gamma': 0.9619206484403829, 'reg_alpha': 0.0005694213494016143, 'reg_lambda': 1.456483276817338}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:24:43,272] Trial 33 finished with value: 0.6702501409779449 and parameters: {'learning_rate': 0.07152140792361583, 'max_depth': 4, 'min_child_weight': 3.64420188050201, 'subsample': 0.771965573064678, 'colsample_bytree': 0.8448027697975664, 'gamma': 1.396642920574482, 'reg_alpha': 0.001872522169497168, 'reg_lambda': 0.02945070586340688}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:24:54,797] Trial 34 finished with value: 0.6739237627856156 and parameters: {'learning_rate': 0.052225996019742114, 'max_depth': 3, 'min_child_weight': 3.911184761463872, 'subsample': 0.7700122230244498, 'colsample_bytree': 0.7961688274608799, 'gamma': 0.6240129966631065, 'reg_alpha': 0.00025121681118123385, 'reg_lambda': 0.3720861929468681}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:25:11,539] Trial 35 finished with value: 0.66426961538698 and parameters: {'learning_rate': 0.056174567328707216, 'max_depth': 5, 'min_child_weight': 4.626491986868542, 'subsample': 0.7649261676332355, 'colsample_bytree': 0.9167140633999551, 'gamma': 0.46263023559483163, 'reg_alpha': 0.00021788476026927668, 'reg_lambda': 0.47005644743118935}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:25:39,986] Trial 36 finished with value: 0.6597540619537352 and parameters: {'learning_rate': 0.027331846925226094, 'max_depth': 7, 'min_child_weight': 7.5184271761780606, 'subsample': 0.7896870747221957, 'colsample_bytree': 0.8057023997339645, 'gamma': 0.6331563883165535, 'reg_alpha': 2.35364499082693, 'reg_lambda': 3.583612050453471}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:25:54,276] Trial 37 finished with value: 0.6567681243775063 and parameters: {'learning_rate': 0.09933450370172674, 'max_depth': 8, 'min_child_weight': 1.6505850867801617, 'subsample': 0.8663564385209807, 'colsample_bytree': 0.876576005707085, 'gamma': 0.28975050297121485, 'reg_alpha': 0.0009914303014354623, 'reg_lambda': 0.20347884102961836}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:26:01,198] Trial 38 finished with value: 0.6675783057234967 and parameters: {'learning_rate': 0.1684333457262146, 'max_depth': 3, 'min_child_weight': 2.696527221886682, 'subsample': 0.7410028772483804, 'colsample_bytree': 0.8422760481938112, 'gamma': 1.6679992270329511, 'reg_alpha': 0.14088650060723554, 'reg_lambda': 0.833359911377676}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:26:18,543] Trial 39 finished with value: 0.6584648426121358 and parameters: {'learning_rate': 0.040063991787129695, 'max_depth': 5, 'min_child_weight': 5.153832905814272, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9184031857996366, 'gamma': 0.7663279001852905, 'reg_alpha': 0.00011022581075208787, 'reg_lambda': 0.0361315544619677}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:26:35,148] Trial 40 finished with value: 0.6621540705739389 and parameters: {'learning_rate': 0.07039059940797347, 'max_depth': 6, 'min_child_weight': 6.390730092849743, 'subsample': 0.7747913746357226, 'colsample_bytree': 0.7168944841696966, 'gamma': 0.1436417890203172, 'reg_alpha': 0.2849102817936404, 'reg_lambda': 0.007901834258187267}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:26:46,638] Trial 41 finished with value: 0.6705897084291782 and parameters: {'learning_rate': 0.0578857869378198, 'max_depth': 3, 'min_child_weight': 3.9531699187535976, 'subsample': 0.7137110731238752, 'colsample_bytree': 0.7563938391034349, 'gamma': 1.0449316659213308, 'reg_alpha': 0.0005243100687864156, 'reg_lambda': 0.08297008580544514}. Best is trial 26 with value: 0.6756106472742001.
[I 2026-04-10 15:26:58,986] Trial 42 finished with value: 0.6772460598159482 and parameters: {'learning_rate': 0.050251585248697585, 'max_depth': 3, 'min_child_weight': 3.746138262052589, 'subsample': 0.7363777521935886, 'colsample_bytree': 0.7769136963627897, 'gamma': 1.1803238544096517, 'reg_alpha': 0.00036139153983439157, 'reg_lambda': 0.12050071438704313}. Best is trial 42 with value: 0.6772460598159482.
[I 2026-04-10 15:27:13,211] Trial 43 finished with value: 0.6716568451044409 and parameters: {'learning_rate': 0.053094422483132855, 'max_depth': 4, 'min_child_weight': 3.1441685337976826, 'subsample': 0.7637837458386231, 'colsample_bytree': 0.7723916071484599, 'gamma': 0.9022265147103838, 'reg_alpha': 0.00030311356776042503, 'reg_lambda': 0.38558266132484925}. Best is trial 42 with value: 0.6772460598159482.
[I 2026-04-10 15:27:24,642] Trial 44 finished with value: 0.6746001131031575 and parameters: {'learning_rate': 0.06717052382353525, 'max_depth': 3, 'min_child_weight': 4.919610806127243, 'subsample': 0.7971307651833303, 'colsample_bytree': 0.8021070178516594, 'gamma': 1.1825845990539963, 'reg_alpha': 0.0010585264734529957, 'reg_lambda': 0.18651485735535875}. Best is trial 42 with value: 0.6772460598159482.
[I 2026-04-10 15:27:36,408] Trial 45 finished with value: 0.6756747784079864 and parameters: {'learning_rate': 0.06563312157333358, 'max_depth': 3, 'min_child_weight': 4.875590507022149, 'subsample': 0.7964145351229632, 'colsample_bytree': 0.8001642079226693, 'gamma': 1.1699266676763456, 'reg_alpha': 0.0007597198026094003, 'reg_lambda': 0.15535190827518858}. Best is trial 42 with value: 0.6772460598159482.
[I 2026-04-10 15:27:47,356] Trial 46 finished with value: 0.6784911209436147 and parameters: {'learning_rate': 0.07009583660899268, 'max_depth': 3, 'min_child_weight': 4.931861132690605, 'subsample': 0.885041630042275, 'colsample_bytree': 0.7391223283909663, 'gamma': 1.1839994483108722, 'reg_alpha': 0.000881983214929205, 'reg_lambda': 0.005280940949348942}. Best is trial 46 with value: 0.6784911209436147.
[I 2026-04-10 15:27:59,020] Trial 47 finished with value: 0.6690328252080189 and parameters: {'learning_rate': 0.06608595164662187, 'max_depth': 3, 'min_child_weight': 4.860189745397005, 'subsample': 0.8941129311170479, 'colsample_bytree': 0.7380331356189694, 'gamma': 1.1605136830547926, 'reg_alpha': 0.0008836429782773298, 'reg_lambda': 0.0035777802864952394}. Best is trial 46 with value: 0.6784911209436147.
[I 2026-04-10 15:28:08,480] Trial 48 finished with value: 0.6735908487412386 and parameters: {'learning_rate': 0.09112308542266709, 'max_depth': 3, 'min_child_weight': 5.730394889149514, 'subsample': 0.8839774101766495, 'colsample_bytree': 0.7239093536971478, 'gamma': 1.419988730926806, 'reg_alpha': 0.0031168247064426325, 'reg_lambda': 0.004371197626165927}. Best is trial 46 with value: 0.6784911209436147.

[I 2026-04-10 15:38:01,508] A new study created in memory with name: multiclass_catboost

[I 2026-04-10 15:38:01,504] Trial 99 finished with value: 0.668299286565791 and parameters: {'learning_rate': 0.13846005589780952, 'max_depth': 3, 'min_child_weight': 1.4922242197235882, 'subsample': 0.7484485395945358, 'colsample_bytree': 0.888680420989839, 'gamma': 1.6345806324016354, 'reg_alpha': 0.5548189094318127, 'reg_lambda': 0.0029337372972659506}. Best is trial 46 with value: 0.6784911209436147.

Best model (xgb) CV score: 0.67849
Best params: {'learning_rate': 0.07009583660899268, 'max_depth': 3, 'min_child_weight': 4.931861132690605, 'subsample': 0.885041630042275, 'colsample_bytree': 0.7391223283909663, 'gamma': 1.1839994483108722, 'reg_alpha': 0.000881983214929205, 'reg_lambda': 0.005280940949348942}

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-10 15:38:18,483] Trial 0 finished with value: 0.6601303954086258 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6601303954086258.
[I 2026-04-10 15:38:58,108] Trial 1 finished with value: 0.6688321472305213 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6688321472305213.
[I 2026-04-10 15:39:26,808] Trial 2 finished with value: 0.6752876339517311 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:40:26,089] Trial 3 finished with value: 0.6743074450967828 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:41:46,513] Trial 4 finished with value: 0.6555823126859738 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:44:13,202] Trial 5 finished with value: 0.6713713937205928 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:45:05,633] Trial 6 finished with value: 0.6623105062398829 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:46:52,317] Trial 7 finished with value: 0.6608916808093573 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:50:36,865] Trial 8 finished with value: 0.6639756713377953 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 2 with value: 0.6752876339517311.
[I 2026-04-10 15:51:20,264] Trial 9 finished with value: 0.6775939730005404 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 9 with value: 0.6775939730005404.
[I 2026-04-10 15:51:31,610] Trial 10 finished with value: 0.6774238360127458 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15550029108275915, 'depth': 5, 'l2_leaf_reg': 1.2809979042149076, 'random_strength': 0.9947887102560302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9526058892396143}. Best is trial 9 with value: 0.6775939730005404.
[I 2026-04-10 15:51:42,335] Trial 11 finished with value: 0.6781070525884804 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.0055865908574264, 'random_strength': 0.9740569036396177, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9614469323901528}. Best is trial 11 with value: 0.6781070525884804.
[I 2026-04-10 15:51:53,845] Trial 12 finished with value: 0.6731715521252589 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1254266894001504, 'depth': 5, 'l2_leaf_reg': 1.008515403467193, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9357491826204533}. Best is trial 11 with value: 0.6781070525884804.
[I 2026-04-10 15:52:15,087] Trial 13 finished with value: 0.6713697295957294 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11898154973533921, 'depth': 6, 'l2_leaf_reg': 2.4370555549349335, 'random_strength': 0.8312664814007409, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8613994204926704}. Best is trial 11 with value: 0.6781070525884804.
[I 2026-04-10 15:52:33,859] Trial 14 finished with value: 0.685815804626591 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04234001494954542, 'depth': 5, 'l2_leaf_reg': 2.6406059539676168, 'random_strength': 0.9155639943141536, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6108156537876648}. Best is trial 14 with value: 0.685815804626591.
[I 2026-04-10 15:52:54,684] Trial 15 finished with value: 0.6813566396158788 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03615822789069425, 'depth': 5, 'l2_leaf_reg': 2.8746263122809177, 'random_strength': 0.8721890309737571, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8714706986308531}. Best is trial 14 with value: 0.685815804626591.
[I 2026-04-10 15:53:13,905] Trial 16 finished with value: 0.6758531655150454 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03516782748920392, 'depth': 5, 'l2_leaf_reg': 3.6707559128589913, 'random_strength': 0.5911289728648254, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8535280553355442}. Best is trial 14 with value: 0.685815804626591.
[I 2026-04-10 15:53:23,742] Trial 17 finished with value: 0.6890055919489899 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032137942695715176, 'depth': 4, 'l2_leaf_reg': 2.9125341475769937, 'random_strength': 0.841617414890688, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.613804346671224}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:53:35,584] Trial 18 finished with value: 0.6866218547842773 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0290625826214462, 'depth': 4, 'l2_leaf_reg': 5.414886599314566, 'random_strength': 0.7074586204636575, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6079060220339148}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:53:48,284] Trial 19 finished with value: 0.6872152942358423 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025997852504109506, 'depth': 4, 'l2_leaf_reg': 5.795530173888481, 'random_strength': 0.719121456658947, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6002084686319717}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:53:57,912] Trial 20 finished with value: 0.6802009819216448 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.053389038308698025, 'depth': 4, 'l2_leaf_reg': 6.328432574173331, 'random_strength': 0.5403540417857632, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6657484549901347}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:54:09,946] Trial 21 finished with value: 0.6828421428704352 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02795338637899447, 'depth': 4, 'l2_leaf_reg': 5.9963976886803465, 'random_strength': 0.7300873584639261, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6022022956013123}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:54:21,626] Trial 22 finished with value: 0.6873679649293944 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030443586202498273, 'depth': 4, 'l2_leaf_reg': 5.575495686561692, 'random_strength': 0.7517897334111748, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.657993658297079}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:54:36,582] Trial 23 finished with value: 0.6870634683447423 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020145855104628577, 'depth': 4, 'l2_leaf_reg': 3.5821752813899828, 'random_strength': 0.7755237638223994, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6667647512677055}. Best is trial 17 with value: 0.6890055919489899.
[I 2026-04-10 15:54:47,267] Trial 24 finished with value: 0.6890280390302234 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033849810857827435, 'depth': 4, 'l2_leaf_reg': 7.76727053216172, 'random_strength': 0.45979257821235137, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7260666058081409}. Best is trial 24 with value: 0.6890280390302234.
[I 2026-04-10 15:54:55,869] Trial 25 finished with value: 0.6824259897995366 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05829916383468929, 'depth': 4, 'l2_leaf_reg': 8.255719748139715, 'random_strength': 0.4756683534265142, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7366217129107753}. Best is trial 24 with value: 0.6890280390302234.
[I 2026-04-10 15:55:12,468] Trial 26 finished with value: 0.6753757178952939 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03673516666925891, 'depth': 5, 'l2_leaf_reg': 12.075100349443963, 'random_strength': 0.38947583564314103, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 24 with value: 0.6890280390302234.
[I 2026-04-10 15:55:25,366] Trial 27 finished with value: 0.6895367162646525 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032268980599861455, 'depth': 4, 'l2_leaf_reg': 8.172175660057684, 'random_strength': 0.5580958091533104, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7939579433544518}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:56:03,708] Trial 28 finished with value: 0.6808893529915934 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03322651802115874, 'depth': 6, 'l2_leaf_reg': 19.586787577215784, 'random_strength': 0.5654988776164962, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8118311414102553}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:56:27,102] Trial 29 finished with value: 0.6573417829889548 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06448799572756013, 'depth': 4, 'l2_leaf_reg': 2.1517031575589023, 'random_strength': 0.27766077916292564, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.682610778645282}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:56:39,976] Trial 30 finished with value: 0.6879529579826021 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023776122343775404, 'depth': 4, 'l2_leaf_reg': 7.521015107271955, 'random_strength': 0.42161453960522544, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8130076318022446}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:56:52,183] Trial 31 finished with value: 0.6849018041735482 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02379707637987963, 'depth': 4, 'l2_leaf_reg': 7.439821343064936, 'random_strength': 0.4064098199544115, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8023185903572889}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:57:04,510] Trial 32 finished with value: 0.6740099880243624 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02424103037761197, 'depth': 4, 'l2_leaf_reg': 7.174495211949328, 'random_strength': 0.18296263807801488, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7773119214073315}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:57:15,079] Trial 33 finished with value: 0.6822206208306866 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04055412619570493, 'depth': 4, 'l2_leaf_reg': 9.222627385843225, 'random_strength': 0.3024640729566559, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8298453001835712}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:57:43,405] Trial 34 finished with value: 0.6762690040947615 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03110622531928065, 'depth': 5, 'l2_leaf_reg': 12.467248825412716, 'random_strength': 0.4400515010148901, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7349266884786119}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:57:52,440] Trial 35 finished with value: 0.6810822268962332 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04856540086248817, 'depth': 4, 'l2_leaf_reg': 3.2308985240155645, 'random_strength': 0.35175265909096964, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7748728870401698}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:58:15,884] Trial 36 finished with value: 0.6828035398335742 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022453040550709912, 'depth': 5, 'l2_leaf_reg': 4.721128842601031, 'random_strength': 0.5306019713177068, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9014476337028774}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:58:37,839] Trial 37 finished with value: 0.6721801891366948 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02700731227354172, 'depth': 4, 'l2_leaf_reg': 10.987957415164214, 'random_strength': 0.2136655651907201, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7167973731122598}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:58:47,822] Trial 38 finished with value: 0.6829521504282773 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03786087532766457, 'depth': 4, 'l2_leaf_reg': 8.642722026692967, 'random_strength': 0.6326460331513906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.12221043743904225}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:59:28,190] Trial 39 finished with value: 0.6766101794998116 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04598095904823247, 'depth': 6, 'l2_leaf_reg': 15.27293445814073, 'random_strength': 0.6181559291784684, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.6990064142436702}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:59:47,750] Trial 40 finished with value: 0.6827793396702868 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03261407604677115, 'depth': 5, 'l2_leaf_reg': 1.7880266128945397, 'random_strength': 0.12082618753702501, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.4532051511681003}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 15:59:58,674] Trial 41 finished with value: 0.6885546445418806 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030870508340531455, 'depth': 4, 'l2_leaf_reg': 6.833803367440586, 'random_strength': 0.6720032248869456, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.643689651578587}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 16:00:11,497] Trial 42 finished with value: 0.6851869358728958 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02644534898717107, 'depth': 4, 'l2_leaf_reg': 7.090665889591965, 'random_strength': 0.5004570225094445, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6373853290252375}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 16:00:27,582] Trial 43 finished with value: 0.6878869824184946 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02208276206210579, 'depth': 4, 'l2_leaf_reg': 10.0506595714868, 'random_strength': 0.6835405700167875, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6855970941561395}. Best is trial 27 with value: 0.6895367162646525.
[I 2026-04-10 16:00:38,501] Trial 44 finished with value: 0.6915466587893463 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030751048519472166, 'depth': 4, 'l2_leaf_reg': 4.6585042153212495, 'random_strength': 0.8159268022008451, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8262146393588699}. Best is trial 44 with value: 0.6915466587893463.
[I 2026-04-10 16:00:49,482] Trial 45 finished with value: 0.6849600394454822 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04036387366991557, 'depth': 4, 'l2_leaf_reg': 4.985312457210157, 'random_strength': 0.7929157495500838, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7661583028016294}. Best is trial 44 with value: 0.6915466587893463.

                                       feature  importance
55     eye__sac_length_AOI_aggregated_Pos_mean    0.043536
184        eye__fix_duration_AOI_FD_Neg1_count    0.042884
276   eye__fix_duration_AOI_aggregated_Pos_min    0.031125
30      eye__sac_length_AOI_aggregated_Neg_max    0.029370
62      eye__sac_speed_AOI_aggregated_Pos_mean    0.029092
29      eye__sac_length_AOI_aggregated_Neg_min    0.027288
177          eye__fix_duration_AOI_FD_Neg1_max    0.026435
56   eye__sac_length_AOI_aggregated_Pos_median    0.021382
183          eye__fix_duration_AOI_FD_Neg1_sum    0.014309
277   eye__fix_duration_AOI_aggregated_Pos_max    0.013483
53      eye__sac_length_AOI_aggregated_Pos_min    0.012411
176          eye__fix_duration_AOI_FD_Neg1_min    0.012312
31     eye__sac_length_AOI_aggregated_Neg_mean    0.011730
557                             stat__umap_087    0.011479
63    eye__sac_speed_AOI_aggregated_Pos_median    0.011309
484                             stat__umap_014    0.010454
178         eye__fix_duration_AOI_FD_Neg1_mean    0.009558
498                             stat__umap_028    0.009469
278  eye__fix_duration_AOI_aggregated_Pos_mean    0.008785
488                             stat__umap_018    0.008781
500                             stat__umap_030    0.008696
175        eye__fix_duration_AOI_FD_Neg1_first    0.007933
496                             stat__umap_026    0.007856
60       eye__sac_speed_AOI_aggregated_Pos_min    0.007439
480                             stat__umap_010    0.007146
562                             stat__umap_092    0.006870
54      eye__sac_length_AOI_aggregated_Pos_max    0.006545
47   eye__sac_length_AOI_aggregated_None_count    0.006395
34      eye__sac_length_AOI_aggregated_Neg_sum    0.006366
535                             stat__umap_065    0.006059

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.81732
              precision    recall  f1-score   support

           0       0.84      0.69      0.76       156
           1       0.83      0.81      0.82       180
           2       0.78      0.99      0.87       125

    accuracy                           0.82       461
   macro avg       0.82      0.83      0.82       461
weighted avg       0.82      0.82      0.81       461

Confusion matrix:
 [[107  28  21]
 [ 20 146  14]
 [  0   1 124]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
256     eye__fix_duration_AOI_aggregated_Neg_min    5.342998
264   eye__fix_duration_AOI_aggregated_Neg_count    4.547047
32     eye__sac_length_AOI_aggregated_Neg_median    4.338516
259  eye__fix_duration_AOI_aggregated_Neg_median    4.277134
35      eye__sac_length_AOI_aggregated_Neg_count    4.270068
36         eye__sac_speed_AOI_aggregated_Neg_min    3.858447
37         eye__sac_speed_AOI_aggregated_Neg_max    3.679243
58        eye__sac_length_AOI_aggregated_Pos_sum    3.101144
263     eye__fix_duration_AOI_aggregated_Neg_sum    2.674663
257     eye__fix_duration_AOI_aggregated_Neg_max    2.615513
31       eye__sac_length_AOI_aggregated_Neg_mean    2.614425
61         eye__sac_speed_AOI_aggregated_Pos_max    2.374007
255   eye__fix_duration_AOI_aggregated_Neg_first    2.363050
29        eye__sac_length_AOI_aggregated_Neg_min    2.265975
34        eye__sac_length_AOI_aggregated_Neg_sum    2.260477
60         eye__sac_speed_AOI_aggregated_Pos_min    2.182309
184          eye__fix_duration_AOI_FD_Neg1_count    2.018385
38        eye__sac_speed_AOI_aggregated_Neg_mean    1.873052
258    eye__fix_duration_AOI_aggregated_Neg_mean    1.633312
55       eye__sac_length_AOI_aggregated_Pos_mean    1.621516
53        eye__sac_length_AOI_aggregated_Pos_min    1.595058
279  eye__fix_duration_AOI_aggregated_Pos_median    1.511068
59      eye__sac_length_AOI_aggregated_Pos_count    1.422912
183            eye__fix_duration_AOI_FD_Neg1_sum    1.400692
178           eye__fix_duration_AOI_FD_Neg1_mean    1.385959
62        eye__sac_speed_AOI_aggregated_Pos_mean    1.380623
179         eye__fix_duration_AOI_FD_Neg1_median    1.378599
46       eye__sac_length_AOI_aggregated_None_sum    1.311407
176            eye__fix_duration_AOI_FD_Neg1_min    1.265423
175          eye__fix_duration_AOI_FD_Neg1_first    1.084151

,set,target,split,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,multiclass,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch_general,binary,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch_general,multiclass,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,multiclass,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch_general,binary,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch_general,multiclass,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [11]:
all_summaries = [
    summary_corr,
    summary_cov_freq,
    summary_envelope,
    summary_freq_bands,
    summary_PID,
    summary_stat,
]
all_results = pd.concat(all_summaries, ignore_index=True)
all_results

,set,target,split,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,multiclass,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch_general,binary,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch_general,multiclass,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch,binary,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch,multiclass,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,binary,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...
8,envelope,match_mismatch,binary,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
9,envelope,match_mismatch,multiclass,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
10,envelope,match_mismatch_general,binary,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
11,envelope,match_mismatch_general,multiclass,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...
12,freq_bands,match_mismatch,binary,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
13,freq_bands,match_mismatch,multiclass,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
14,freq_bands,match_mismatch_general,binary,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
15,freq_bands,match_mismatch_general,multiclass,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...
16,PID,match_mismatch,binary,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
17,PID,match_mismatch,multiclass,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
18,PID,match_mismatch_general,binary,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
19,PID,match_mismatch_general,multiclass,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...
20,stat,match_mismatch,binary,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
21,stat,match_mismatch,multiclass,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
22,stat,match_mismatch_general,binary,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
23,stat,match_mismatch_general,multiclass,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [12]:
summary_path = OUT_DIR / "summary_eye_ftar.csv"
all_results.to_csv(summary_path, index=False)
print("Saved summary:", summary_path)

all_results.groupby(["set", "target", "split"], as_index=False)[["xgb_test", "catboost_test"]].mean()

Saved summary: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\summary_eye_ftar.csv

           set                  target       split  xgb_test  catboost_test
0          PID          match_mismatch      binary  0.399740       0.402184
1          PID          match_mismatch  multiclass  0.623863       0.614744
2          PID  match_mismatch_general      binary  0.404235       0.567179
3          PID  match_mismatch_general  multiclass  0.802558       0.814880
4         corr          match_mismatch      binary  0.398399       0.414870
5         corr          match_mismatch  multiclass  0.596315       0.608868
6         corr  match_mismatch_general      binary  0.426946       0.529915
7         corr  match_mismatch_general  multiclass  0.799472       0.808972
8     cov_freq          match_mismatch      binary  0.399740       0.403406
9     cov_freq          match_mismatch  multiclass  0.621595       0.628659
10    cov_freq  match_mismatch_general      binary  0.398957       0.576895
11    cov_freq  match_mismatch_general  multiclass  0.802246       0.803497
12    envelope          match_mismatch      binary  0.399740       0.410272
13    envelope          match_mismatch  multiclass  0.621856       0.621466
14    envelope  match_mismatch_general      binary  0.398957       0.554178
15    envelope  match_mismatch_general  multiclass  0.806555       0.808673
16  freq_bands          match_mismatch      binary  0.399740       0.416763
17  freq_bands          match_mismatch  multiclass  0.633477       0.628659
18  freq_bands  match_mismatch_general      binary  0.484267       0.531461
19  freq_bands  match_mismatch_general  multiclass  0.808328       0.801248
20        stat          match_mismatch      binary  0.399740       0.436073
21        stat          match_mismatch  multiclass  0.626858       0.618859
22        stat  match_mismatch_general      binary  0.439737       0.554900
23        stat  match_mismatch_general  multiclass  0.801435       0.817319