
# Eye tracking + text2text + TabR (Optuna, GPU)

This notebook mirrors the structure of `experiments_eye_text2text_index_match.ipynb`, but replaces tree models with a **TabR-style retrieval-augmented tabular deep model** trained on **GPU** and tuned with **Optuna**.

Main differences from the original notebook:
- uses a **TabR-like PyTorch model** instead of XGBoost / CatBoost
- tunes **model parameters and training parameters jointly**
- runs **grouped CV** on the training split
- saves each experiment to a **separate folder**
- keeps the same **eye-tracking + text2text index-matching** logic

Notes:
- the implementation is intentionally self-contained inside the notebook
- retrieval is performed on GPU with PyTorch tensors
- the code assumes all features are numerical after preprocessing / concatenation

In [1]:

from __future__ import annotations

import os
import gc
import json
import math
import random
from copy import deepcopy
from pathlib import Path
from typing import Dict, Tuple, Optional, List

import numpy as np
import pandas as pd
from umap import UMAP

import optuna
from optuna.samplers import TPESampler

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.metrics import f1_score, accuracy_score
from sklearn.model_selection import GroupKFold, StratifiedKFold

from experiment_code.read_data import get_data_for_split
from experiment_code.run_experiments import _build_groups_mm_for_mm


# Data root: contains datasets_splitted_screen_match_mismatch*
ROOT = Path(r"C:\Users\LEGION\data\СB")
os.chdir(ROOT)
print("cwd:", Path.cwd())

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", DEVICE)
if DEVICE.type == "cuda":
    print("cuda:", torch.cuda.get_device_name(0))

cwd: C:\Users\LEGION\data\СB
device: cuda
cuda: NVIDIA GeForce RTX 4080 Laptop GPU

In [2]:

# Main settings
TARGETS = ["match_mismatch", "match_mismatch_general"]
SPLITS = ["binary", "multiclass"]

CV = 4
N_TRIALS_TABR = 60
RANDOM_STATE = 42

USE_UMAP_FOR = {"freq_bands", "stat", "corr", "cov_freq"}
UMAP_N_COMPONENTS = 100
CLEAN_TRAIN_COLUMNS = False

MAX_EPOCHS_DEFAULT = 100
EARLY_STOPPING_PATIENCE_DEFAULT = 20
N_WORKERS = 0

# Output location under project folder
PROJECT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\dataset_v2")
OUT_DIR = PROJECT_DIR / "optuna_results_eye_text2text_tabr"
OUT_DIR.mkdir(parents=True, exist_ok=True)

MODELS_DIR = OUT_DIR / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

TRIALS_DIR = OUT_DIR / "optuna_trials"
TRIALS_DIR.mkdir(parents=True, exist_ok=True)

PREDS_DIR = OUT_DIR / "predictions"
PREDS_DIR.mkdir(parents=True, exist_ok=True)

SUMMARY_DIR = OUT_DIR / "summaries"
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)

TEXT2TEXT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\text2text_features")
TEXT2TEXT_FILES = {
    "corr": TEXT2TEXT_DIR / "corr.parquet",
    "cov_freq": TEXT2TEXT_DIR / "cov_freq.parquet",
    "envelope": TEXT2TEXT_DIR / "envelope.parquet",
    "freq_bands": TEXT2TEXT_DIR / "freq_bands.parquet",
    "PID": TEXT2TEXT_DIR / "PID.parquet",
    "stat": TEXT2TEXT_DIR / "stat.parquet",
}

In [3]:

def seed_everything(seed: int = RANDOM_STATE) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


def _prefix_cols(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    return df.add_prefix(prefix)


def _load_text2text_parquet(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    if "pid_rn" not in df.columns:
        raise KeyError(f"'pid_rn' column not found in {path}")
    df = df.set_index("pid_rn")
    df.index = df.index.astype(str)
    return df


def _apply_umap_train_test(
    text_train: pd.DataFrame,
    text_test: pd.DataFrame,
    *,
    text_set_name: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    tr = text_train.apply(pd.to_numeric, errors="coerce")
    te = text_test.apply(pd.to_numeric, errors="coerce")

    train_means = tr.mean(numeric_only=True)
    tr = tr.fillna(train_means).fillna(0.0)
    te = te.fillna(train_means).fillna(0.0)

    n_components = int(min(UMAP_N_COMPONENTS, max(2, tr.shape[1])))
    reducer = UMAP(n_components=n_components, random_state=RANDOM_STATE)

    print(
        f"[{text_set_name}] UMAP compression: "
        f"train/test features {tr.shape[1]} -> {n_components}"
    )

    z_train = reducer.fit_transform(tr)
    z_test = reducer.transform(te)

    cols = [f"{text_set_name}__umap_{i:03d}" for i in range(n_components)]
    tr_umap = pd.DataFrame(z_train, index=text_train.index, columns=cols)
    te_umap = pd.DataFrame(z_test, index=text_test.index, columns=cols)
    return tr_umap, te_umap


def _prepare_joined_X(
    eye_train: pd.DataFrame,
    eye_test: pd.DataFrame,
    text_all: pd.DataFrame,
    text_set_name: str,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    text_train = text_all.reindex(eye_train.index)
    text_test = text_all.reindex(eye_test.index)

    missing_train = int(text_train.isna().all(axis=1).sum())
    missing_test = int(text_test.isna().all(axis=1).sum())
    print(f"[{text_set_name}] rows missing after index match -> train: {missing_train}, test: {missing_test}")

    if text_set_name in USE_UMAP_FOR:
        text_train_model, text_test_model = _apply_umap_train_test(
            text_train,
            text_test,
            text_set_name=text_set_name,
        )
    else:
        text_train_model = _prefix_cols(text_train, f"{text_set_name}__")
        text_test_model = _prefix_cols(text_test, f"{text_set_name}__")

    X_train = pd.concat([
        _prefix_cols(eye_train, "eye__"),
        text_train_model,
    ], axis=1)
    X_test = pd.concat([
        _prefix_cols(eye_test, "eye__"),
        text_test_model,
    ], axis=1)

    if CLEAN_TRAIN_COLUMNS:
        keep_cols = X_train.columns[X_train.notna().all(axis=0)]
        X_train = X_train[keep_cols]
        X_test = X_test.reindex(columns=keep_cols)

    # numeric-only, fit preprocessing on train only
    X_train = X_train.apply(pd.to_numeric, errors="coerce")
    X_test = X_test.apply(pd.to_numeric, errors="coerce")

    means = X_train.mean(axis=0)
    stds = X_train.std(axis=0).replace(0.0, 1.0)

    X_train = X_train.fillna(means).fillna(0.0)
    X_test = X_test.fillna(means).fillna(0.0)

    X_train = (X_train - means) / stds
    X_test = (X_test - means) / stds

    X_train = X_train.replace([np.inf, -np.inf], 0.0)
    X_test = X_test.replace([np.inf, -np.inf], 0.0)

    return X_train.astype(np.float32), X_test.astype(np.float32)


def _build_no_neutral_mask(stim_df: pd.DataFrame, target: str, split: str) -> pd.Series:
    mask = pd.Series(True, index=stim_df.index)

    if "valence" in stim_df.columns:
        valence = pd.to_numeric(stim_df["valence"], errors="coerce")
        mask &= valence != 2

    if split == "binary":
        if target == "match_mismatch_general" and "exp_general_multi" in stim_df.columns:
            exp_general_multi = pd.to_numeric(stim_df["exp_general_multi"], errors="coerce")
            mask &= exp_general_multi != 2
        elif "IAT_results2" in stim_df.columns:
            iat = stim_df["IAT_results2"].astype(str).str.strip().str.lower()
            mask &= iat != "neutral"

    return mask.fillna(False)


def _load_eye_for_task(target: str, split: str, no_neutral: bool = False):
    df, tgt, _ = get_data_for_split(X_name="screen", target=target, split=split)

    eye_train = df["all_features"]["X_train"].copy()
    eye_test = df["all_features"]["X_test"].copy()
    stim_train = df["stimuli_features"]["X_train"].copy()
    stim_test = df["stimuli_features"]["X_test"].copy()

    y_train = tgt["cb"]["y_train"].copy()
    y_test = tgt["cb"]["y_test"].copy()

    if no_neutral:
        mask_train = _build_no_neutral_mask(stim_train, target=target, split=split)
        mask_test = _build_no_neutral_mask(stim_test, target=target, split=split)

        eye_train = eye_train.loc[mask_train]
        eye_test = eye_test.loc[mask_test]
        y_train = y_train.loc[mask_train]
        y_test = y_test.loc[mask_test]
        stim_train = stim_train.loc[mask_train]

    groups = np.array([str(i).split("_")[0] for i in eye_train.index])

    if target in ("match_mismatch", "match_mismatch_general"):
        groups_mm = _build_groups_mm_for_mm(X_train_index=eye_train.index, stim_train_df=stim_train)
    else:
        groups_mm = None

    problem = "binary" if split == "binary" else "multiclass"
    return eye_train, eye_test, y_train, y_test, groups, groups_mm, problem

In [4]:

class NumpyTabularDataset(Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = torch.tensor(X, dtype=torch.float32)
        if y.ndim != 1:
            y = y.reshape(-1)
        self.y = torch.tensor(y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


class TabRModel(nn.Module):
    """
    Simplified TabR-style model for numerical tabular data.

    Architecture:
    1. encoder -> latent representation z
    2. key projection for retrieval
    3. retrieve top-k neighbours from candidate set (train fold)
    4. aggregate label-aware context
    5. predictor head

    Designed to stay close in spirit to the official TabR structure while being
    self-contained and easy to tune in a notebook.
    """
    def __init__(
        self,
        input_dim: int,
        n_classes: int,
        d_main: int = 256,
        d_block: int = 512,
        encoder_n_blocks: int = 2,
        predictor_n_blocks: int = 2,
        context_dropout: float = 0.1,
        dropout0: float = 0.1,
        dropout1: float = 0.1,
        normalization: str = "LayerNorm",
        activation: str = "ReLU",
        k_neighbors: int = 32,
        label_smoothing: float = 0.0,
    ):
        super().__init__()
        self.n_classes = n_classes
        self.k_neighbors = k_neighbors
        self.label_smoothing = label_smoothing

        Norm = getattr(nn, normalization)
        Act = getattr(nn, activation)

        self.input = nn.Linear(input_dim, d_main)

        def make_block():
            return nn.Sequential(
                Norm(d_main),
                nn.Linear(d_main, d_block),
                Act(),
                nn.Dropout(dropout0),
                nn.Linear(d_block, d_main),
                nn.Dropout(dropout1),
            )

        self.encoder_blocks = nn.ModuleList([make_block() for _ in range(encoder_n_blocks)])
        self.norm_before_retrieval = Norm(d_main)
        self.key_proj = nn.Linear(d_main, d_main)
        self.context_transform = nn.Sequential(
            nn.Linear(d_main, d_block),
            Act(),
            nn.Dropout(dropout0),
            nn.Linear(d_block, d_main, bias=False),
        )
        self.context_dropout = nn.Dropout(context_dropout)

        self.label_encoder = nn.Embedding(n_classes, d_main)

        self.predictor_blocks = nn.ModuleList([make_block() for _ in range(predictor_n_blocks)])
        self.head = nn.Sequential(
            Norm(d_main),
            Act(),
            nn.Linear(d_main, n_classes),
        )

    def encode(self, x: torch.Tensor):
        z = self.input(x)
        for block in self.encoder_blocks:
            z = z + block(z)
        k = self.key_proj(self.norm_before_retrieval(z))
        return z, k

    def retrieve_context(
        self,
        query_k: torch.Tensor,
        cand_z: torch.Tensor,
        cand_k: torch.Tensor,
        cand_y: torch.Tensor,
    ) -> torch.Tensor:
        # negative squared distance
        # shapes: query [B, D], cand [N, D]
        # gpu-friendly exact retrieval for moderate-size folds
        q2 = (query_k ** 2).sum(dim=1, keepdim=True)          # [B, 1]
        c2 = (cand_k ** 2).sum(dim=1).unsqueeze(0)            # [1, N]
        sim = -(q2 - 2.0 * query_k @ cand_k.T + c2)          # [B, N]

        k = min(self.k_neighbors, cand_k.shape[0])
        top_sim, top_idx = torch.topk(sim, k=k, dim=1)

        probs = F.softmax(top_sim, dim=1)
        probs = self.context_dropout(probs)

        neigh_z = cand_z[top_idx]                            # [B, k, D]
        neigh_y = cand_y[top_idx]                            # [B, k]
        neigh_y_emb = self.label_encoder(neigh_y)            # [B, k, D]

        values = neigh_y_emb + self.context_transform(query_k[:, None, :] - neigh_z)
        context = (probs.unsqueeze(1) @ values).squeeze(1)   # [B, D]
        return context

    def forward(
        self,
        x: torch.Tensor,
        candidate_x: torch.Tensor,
        candidate_y: torch.Tensor,
    ) -> torch.Tensor:
        z, k = self.encode(x)
        cand_z, cand_k = self.encode(candidate_x)
        context = self.retrieve_context(k, cand_z, cand_k, candidate_y)
        h = z + context
        for block in self.predictor_blocks:
            h = h + block(h)
        return self.head(h)

In [5]:

def make_loaders(X_train, y_train, batch_size, shuffle=True):
    ds = NumpyTabularDataset(X_train, y_train)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=N_WORKERS,
        pin_memory=(DEVICE.type == "cuda"),
        drop_last=False,
    )


def predict_proba_tabr(
    model: nn.Module,
    X_eval: np.ndarray,
    X_candidates: np.ndarray,
    y_candidates: np.ndarray,
    batch_size: int = 1024,
) -> np.ndarray:
    model.eval()

    X_cand_t = torch.tensor(X_candidates, dtype=torch.float32, device=DEVICE)
    y_cand_t = torch.tensor(y_candidates, dtype=torch.long, device=DEVICE)

    all_logits = []
    with torch.no_grad():
        for start in range(0, len(X_eval), batch_size):
            xb = torch.tensor(X_eval[start:start+batch_size], dtype=torch.float32, device=DEVICE)
            logits = model(xb, X_cand_t, y_cand_t)
            all_logits.append(logits.detach().cpu())
    logits = torch.cat(all_logits, dim=0)
    probs = torch.softmax(logits, dim=1).numpy()
    return probs


def compute_metrics(y_true, y_pred):
    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro")),
    }


def train_one_fold(
    X_tr: np.ndarray,
    y_tr: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    params: dict,
    seed: int = RANDOM_STATE,
):
    seed_everything(seed)

    model = TabRModel(
        input_dim=X_tr.shape[1],
        n_classes=int(len(np.unique(y_tr))),
        d_main=params["d_main"],
        d_block=params["d_block"],
        encoder_n_blocks=params["encoder_n_blocks"],
        predictor_n_blocks=params["predictor_n_blocks"],
        context_dropout=params["context_dropout"],
        dropout0=params["dropout0"],
        dropout1=params["dropout1"],
        normalization=params["normalization"],
        activation=params["activation"],
        k_neighbors=params["k_neighbors"],
        label_smoothing=params["label_smoothing"],
    ).to(DEVICE)

    optimizer_name = params["optimizer"]
    lr = params["lr"]
    weight_decay = params["weight_decay"]

    if optimizer_name == "adamw":
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    elif optimizer_name == "adam":
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        optimizer = torch.optim.RAdam(model.parameters(), lr=lr, weight_decay=weight_decay)

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=max(4, params["patience"] // 3),
    )

    criterion = nn.CrossEntropyLoss(label_smoothing=params["label_smoothing"])

    loader = make_loaders(X_tr, y_tr, params["batch_size"], shuffle=True)

    X_tr_t = torch.tensor(X_tr, dtype=torch.float32, device=DEVICE)
    y_tr_t = torch.tensor(y_tr, dtype=torch.long, device=DEVICE)

    best_state = None
    best_score = -np.inf
    best_epoch = -1
    no_improve = 0
    history = []

    for epoch in range(params["max_epochs"]):
        model.train()
        epoch_losses = []

        for xb, yb in loader:
            xb = xb.to(DEVICE, non_blocking=True)
            yb = yb.to(DEVICE, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)
            logits = model(xb, X_tr_t, y_tr_t)
            loss = criterion(logits, yb)
            loss.backward()

            if params["grad_clip"] is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), params["grad_clip"])

            optimizer.step()
            epoch_losses.append(loss.item())

        val_probs = predict_proba_tabr(
            model=model,
            X_eval=X_val,
            X_candidates=X_tr,
            y_candidates=y_tr,
            batch_size=params["eval_batch_size"],
        )
        val_pred = val_probs.argmax(axis=1)
        val_metrics = compute_metrics(y_val, val_pred)
        val_score = val_metrics["macro_f1"]
        scheduler.step(val_score)

        history.append({
            "epoch": epoch,
            "train_loss": float(np.mean(epoch_losses)),
            **{f"val_{k}": v for k, v in val_metrics.items()}
        })

        if val_score > best_score:
            best_score = val_score
            best_epoch = epoch
            best_state = deepcopy(model.state_dict())
            no_improve = 0
        else:
            no_improve += 1

        if no_improve >= params["patience"]:
            break

    if best_state is None:
        raise RuntimeError("Training finished without a best checkpoint.")

    model.load_state_dict(best_state)
    return model, best_score, best_epoch, history

In [6]:

def suggest_tabr_params(trial: optuna.Trial, n_features: int, n_classes: int) -> dict:
    d_main = trial.suggest_categorical("d_main", [128, 192, 256, 384, 512])
    d_mult = trial.suggest_categorical("d_mult", [1.5, 2.0, 2.5, 3.0, 4.0])

    params = {
        # model
        "d_main": d_main,
        "d_block": int(d_main * d_mult),
        "encoder_n_blocks": trial.suggest_int("encoder_n_blocks", 1, 4),
        "predictor_n_blocks": trial.suggest_int("predictor_n_blocks", 1, 4),
        "context_dropout": trial.suggest_float("context_dropout", 0.0, 0.4),
        "dropout0": trial.suggest_float("dropout0", 0.0, 0.4),
        "dropout1": trial.suggest_float("dropout1", 0.0, 0.4),
        "normalization": trial.suggest_categorical("normalization", ["LayerNorm"]),
        "activation": trial.suggest_categorical("activation", ["ReLU", "GELU"]),
        "k_neighbors": trial.suggest_categorical("k_neighbors", [8, 16, 24, 32, 48, 64]),

        # training
        "optimizer": trial.suggest_categorical("optimizer", ["adamw", "adam", "radam"]),
        "lr": trial.suggest_float("lr", 1e-4, 5e-3, log=True),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 5e-3, log=True),
        "batch_size": trial.suggest_categorical("batch_size", [128, 256, 512, 1024]),
        "eval_batch_size": trial.suggest_categorical("eval_batch_size", [256, 512, 1024, 2048]),
        "max_epochs": trial.suggest_int("max_epochs", 80, MAX_EPOCHS_DEFAULT),
        "patience": trial.suggest_int("patience", 12, EARLY_STOPPING_PATIENCE_DEFAULT),
        "grad_clip": trial.suggest_categorical("grad_clip", [None, 1.0, 2.0, 5.0]),
        "label_smoothing": trial.suggest_float("label_smoothing", 0.0, 0.1),
    }
    return params


def run_cv_optuna(
    X: pd.DataFrame,
    y: pd.Series,
    groups: np.ndarray,
    *,
    study_name: str,
    n_trials: int = N_TRIALS_TABR,
    cv: int = CV,
    seed: int = RANDOM_STATE,
):
    X_np = X.to_numpy(dtype=np.float32)
    y_np = np.asarray(y).astype(int)

    def objective(trial: optuna.Trial) -> float:
        params = suggest_tabr_params(trial, n_features=X_np.shape[1], n_classes=len(np.unique(y_np)))
        splitter = GroupKFold(n_splits=cv)

        fold_scores = []
        for fold_idx, (tr_idx, va_idx) in enumerate(splitter.split(X_np, y_np, groups=groups)):
            X_tr, X_va = X_np[tr_idx], X_np[va_idx]
            y_tr, y_va = y_np[tr_idx], y_np[va_idx]

            model, best_score, best_epoch, history = train_one_fold(
                X_tr=X_tr,
                y_tr=y_tr,
                X_val=X_va,
                y_val=y_va,
                params=params,
                seed=seed + fold_idx,
            )
            fold_scores.append(best_score)

            trial.report(np.mean(fold_scores), step=fold_idx)
            if trial.should_prune():
                raise optuna.TrialPruned()

            del model
            gc.collect()
            if DEVICE.type == "cuda":
                torch.cuda.empty_cache()

        return float(np.mean(fold_scores))

    sampler = TPESampler(seed=seed, multivariate=True)
    study = optuna.create_study(
        direction="maximize",
        study_name=study_name,
        sampler=sampler,
    )
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    trials_df = study.trials_dataframe()
    return study, trials_df

In [7]:

def fit_best_and_test_tabr(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_test: pd.DataFrame,
    y_test: pd.Series,
    best_params: dict,
    *,
    seed: int = RANDOM_STATE,
):
    X_train_np = X_train.to_numpy(dtype=np.float32)
    X_test_np = X_test.to_numpy(dtype=np.float32)
    y_train_np = np.asarray(y_train).astype(int)
    y_test_np = np.asarray(y_test).astype(int)

    # hold out a small validation part from train for early stopping
    val_splitter = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    tr_idx, va_idx = next(val_splitter.split(X_train_np, y_train_np))

    X_tr, X_va = X_train_np[tr_idx], X_train_np[va_idx]
    y_tr, y_va = y_train_np[tr_idx], y_train_np[va_idx]

    model, best_score, best_epoch, history = train_one_fold(
        X_tr=X_tr,
        y_tr=y_tr,
        X_val=X_va,
        y_val=y_va,
        params=best_params,
        seed=seed,
    )

    test_probs = predict_proba_tabr(
        model=model,
        X_eval=X_test_np,
        X_candidates=X_train_np,
        y_candidates=y_train_np,
        batch_size=best_params["eval_batch_size"],
    )
    test_pred = test_probs.argmax(axis=1)
    test_metrics = compute_metrics(y_test_np, test_pred)

    return {
        "model": model,
        "best_score_internal_val": float(best_score),
        "best_epoch": int(best_epoch),
        "history": history,
        "test_metrics": test_metrics,
        "test_pred": test_pred,
        "test_probs": test_probs,
    }

In [8]:

def run_text2text_set_tabr(
    text_set_name: str,
    text_all: pd.DataFrame,
    *,
    n_trials: int = N_TRIALS_TABR,
    do_test_fit: bool = True,
):
    if "pid_rn" in text_all.columns:
        text_all = text_all.set_index("pid_rn")
    text_all = text_all.copy()
    text_all.index = text_all.index.astype(str)

    if "key" in text_all.columns:
        text_all = text_all.drop(columns=["key"])

    text_features = int(text_all.shape[1])
    print(f"[{text_set_name}] text2text feature count after cleanup: {text_features}")

    rows = []

    for target in TARGETS:
        for split in SPLITS:
            for no_neutral in [False, True]:
                problem = "binary" if split == "binary" else "multiclass"
                neutral_suffix = "__no_neutral" if no_neutral else ""
                exp_name = (
                    f"tabr__X_name=screen+{text_set_name}"
                    f"__target={target}"
                    f"__problem={problem}"
                    f"__feat=all_features+{text_set_name}"
                    f"__gpu_optuna"
                    f"{neutral_suffix}"
                )
                exp_dir = OUT_DIR / exp_name
                exp_dir.mkdir(parents=True, exist_ok=True)

                report_path = exp_dir / "report.json"
                if report_path.exists():
                    print("\n" + "=" * 80)
                    print(f"Skipping existing experiment: {exp_name}")
                    with open(report_path, "r", encoding="utf-8") as f:
                        report = json.load(f)
                    rows.append({
                        "text_set": text_set_name,
                        "target": target,
                        "split": split,
                        "no_neutral": no_neutral,
                        "tabr_test_macro_f1": report["test_metrics"]["macro_f1"],
                        "tabr_test_accuracy": report["test_metrics"]["accuracy"],
                        "file": str(report_path),
                    })
                    continue

                eye_train, eye_test, y_train, y_test, groups, groups_mm, problem = _load_eye_for_task(
                    target,
                    split,
                    no_neutral=no_neutral,
                )
                X_train, X_test = _prepare_joined_X(eye_train, eye_test, text_all, text_set_name)

                print("\n" + "=" * 80)
                print(f"Running: {exp_name}")
                print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

                study, trials_df = run_cv_optuna(
                    X=X_train,
                    y=y_train,
                    groups=groups,
                    study_name=exp_name,
                    n_trials=n_trials,
                    cv=CV,
                    seed=RANDOM_STATE,
                )

                best_params = study.best_trial.params
                if "d_block" not in best_params:
                    best_params["d_block"] = int(best_params["d_main"] * best_params["d_mult"])
                with open(exp_dir / "best_params.json", "w", encoding="utf-8") as f:
                    json.dump(best_params, f, indent=2, ensure_ascii=False)

                trials_df.to_csv(exp_dir / "optuna_trials.csv", index=False)

                final_out = fit_best_and_test_tabr(
                    X_train=X_train,
                    y_train=y_train,
                    X_test=X_test,
                    y_test=y_test,
                    best_params=best_params,
                    seed=RANDOM_STATE,
                )

                pred_df = pd.DataFrame({
                    "index": X_test.index.astype(str),
                    "y_true": np.asarray(y_test).astype(int),
                    "y_pred": final_out["test_pred"].astype(int),
                })
                for i in range(final_out["test_probs"].shape[1]):
                    pred_df[f"proba_{i}"] = final_out["test_probs"][:, i]
                pred_df.to_csv(exp_dir / "test_predictions.csv", index=False)

                torch.save(final_out["model"].state_dict(), exp_dir / "tabr_model.pt")

                report = {
                    "experiment_name": exp_name,
                    "text_set": text_set_name,
                    "target": target,
                    "split": split,
                    "problem": problem,
                    "n_train": int(X_train.shape[0]),
                    "n_test": int(X_test.shape[0]),
                    "n_features": int(X_train.shape[1]),
                    "device": str(DEVICE),
                    "best_trial_number": int(study.best_trial.number),
                    "best_cv_macro_f1": float(study.best_value),
                    "best_params": best_params,
                    "best_epoch_internal_val": int(final_out["best_epoch"]),
                    "test_metrics": final_out["test_metrics"],
                    "report_file": str(report_path),
                }

                with open(report_path, "w", encoding="utf-8") as f:
                    json.dump(report, f, indent=2, ensure_ascii=False)

                rows.append({
                    "text_set": text_set_name,
                    "target": target,
                    "split": split,
                    "no_neutral": no_neutral,
                    "tabr_test_macro_f1": float(final_out["test_metrics"]["macro_f1"]),
                    "tabr_test_accuracy": float(final_out["test_metrics"]["accuracy"]),
                    "file": str(report_path),
                })

                del final_out
                gc.collect()
                if DEVICE.type == "cuda":
                    torch.cuda.empty_cache()

    summary = pd.DataFrame(rows)
    display(summary)
    return summary

In [9]:

print("text2text dir:", TEXT2TEXT_DIR)
for k, p in TEXT2TEXT_FILES.items():
    print(f"{k:10s} -> {p} | exists={p.exists()}")
    if p.exists():
        print(pd.read_parquet(p).shape)

text2text dir: C:\Users\LEGION\Projects\CB_exepriment\text2text_features
corr       -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\corr.parquet | exists=True
(5592, 1832)
cov_freq   -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\cov_freq.parquet | exists=True
(5592, 36297)
envelope   -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\envelope.parquet | exists=True
(5592, 429)
freq_bands -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\freq_bands.parquet | exists=True
(5592, 18363)
PID        -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\PID.parquet | exists=True
(5592, 612)
stat       -> C:\Users\LEGION\Projects\CB_exepriment\text2text_features\stat.parquet | exists=True
(5592, 8237)

In [10]:

# Set: corr
text_corr = pd.read_parquet(TEXT2TEXT_FILES["corr"])
print("corr shape:", text_corr.shape)
summary_corr = run_text2text_set_tabr("corr", text_corr)
summary_corr

corr shape: (5592, 1832)
[corr] text2text feature count after cleanup: 1830

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__gpu_optuna__no_neutral

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,corr,match_mismatch,binary,False,0.508172,0.550976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.425768,0.538690,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.567961,0.555315,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,0.544316,0.544643,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.506735,0.577007,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.477679,0.535714,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.649632,0.650759,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,0.582120,0.589286,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,corr,match_mismatch,binary,False,0.508172,0.550976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.425768,0.538690,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.567961,0.555315,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,0.544316,0.544643,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.506735,0.577007,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.477679,0.535714,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.649632,0.650759,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,0.582120,0.589286,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [11]:

# Set: cov_freq
text_cov_freq = pd.read_parquet(TEXT2TEXT_FILES["cov_freq"])
print("cov_freq shape:", text_cov_freq.shape)
summary_cov_freq = run_text2text_set_tabr("cov_freq", text_cov_freq)
summary_cov_freq

cov_freq shape: (5592, 36297)
[cov_freq] text2text feature count after cleanup: 36295

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__gpu_optuna__no_neutral

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,cov_freq,match_mismatch,binary,False,0.492957,0.548807,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,binary,True,0.468639,0.577381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch,multiclass,False,0.552524,0.535792,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch,multiclass,True,0.498864,0.500000,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch_general,binary,False,0.557298,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch_general,binary,True,0.559892,0.654762,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,multiclass,False,0.621884,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,True,0.520323,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,cov_freq,match_mismatch,binary,False,0.492957,0.548807,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,binary,True,0.468639,0.577381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch,multiclass,False,0.552524,0.535792,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch,multiclass,True,0.498864,0.500000,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch_general,binary,False,0.557298,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch_general,binary,True,0.559892,0.654762,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,multiclass,False,0.621884,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,True,0.520323,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [12]:

# Set: envelope
text_envelope = pd.read_parquet(TEXT2TEXT_FILES["envelope"])
print("envelope shape:", text_envelope.shape)
summary_envelope = run_text2text_set_tabr("envelope", text_envelope)
summary_envelope

envelope shape: (5592, 429)
[envelope] text2text feature count after cleanup: 427

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__gpu_optuna__no_neutral

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,envelope,match_mismatch,binary,False,0.499941,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,binary,True,0.403539,0.520833,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch,multiclass,False,0.535088,0.524946,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch,multiclass,True,0.502972,0.502976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,envelope,match_mismatch_general,binary,False,0.552176,0.609544,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,envelope,match_mismatch_general,binary,True,0.538310,0.601190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,envelope,match_mismatch_general,multiclass,False,0.587256,0.583514,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,envelope,match_mismatch_general,multiclass,True,0.603547,0.607143,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,envelope,match_mismatch,binary,False,0.499941,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,binary,True,0.403539,0.520833,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch,multiclass,False,0.535088,0.524946,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch,multiclass,True,0.502972,0.502976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,envelope,match_mismatch_general,binary,False,0.552176,0.609544,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,envelope,match_mismatch_general,binary,True,0.538310,0.601190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,envelope,match_mismatch_general,multiclass,False,0.587256,0.583514,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,envelope,match_mismatch_general,multiclass,True,0.603547,0.607143,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [13]:

# Set: freq_bands
text_freq_bands = pd.read_parquet(TEXT2TEXT_FILES["freq_bands"])
print("freq_bands shape:", text_freq_bands.shape)
summary_freq_bands = run_text2text_set_tabr("freq_bands", text_freq_bands)
summary_freq_bands

freq_bands shape: (5592, 18363)
[freq_bands] text2text feature count after cleanup: 18361

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__gpu_optuna__no_neutral

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,freq_bands,match_mismatch,binary,False,0.444435,0.503254,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,binary,True,0.485601,0.592262,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch,multiclass,False,0.555486,0.537961,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch,multiclass,True,0.494224,0.497024,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,freq_bands,match_mismatch_general,binary,False,0.527205,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,freq_bands,match_mismatch_general,binary,True,0.547881,0.642857,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,freq_bands,match_mismatch_general,multiclass,False,0.693793,0.687636,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,freq_bands,match_mismatch_general,multiclass,True,0.663218,0.666667,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,freq_bands,match_mismatch,binary,False,0.444435,0.503254,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,binary,True,0.485601,0.592262,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch,multiclass,False,0.555486,0.537961,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch,multiclass,True,0.494224,0.497024,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,freq_bands,match_mismatch_general,binary,False,0.527205,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,freq_bands,match_mismatch_general,binary,True,0.547881,0.642857,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,freq_bands,match_mismatch_general,multiclass,False,0.693793,0.687636,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,freq_bands,match_mismatch_general,multiclass,True,0.663218,0.666667,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [14]:

# Set: PID
text_PID = pd.read_parquet(TEXT2TEXT_FILES["PID"])
print("PID shape:", text_PID.shape)
summary_PID = run_text2text_set_tabr("PID", text_PID)
summary_PID

PID shape: (5592, 612)
[PID] text2text feature count after cleanup: 610

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__gpu_optuna

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__gpu_optuna__no_neutral

================================================================================
Skipping existing experiment: tabr__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__gpu_optuna
[PID] rows missing after index match -> train: 1004, test: 104

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 10:57:38,697] A new study created in memory with name: tabr__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__gpu_optuna__no_neutral

================================================================================
Running: tabr__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__gpu_optuna__no_neutral
X_train: (3016, 1080), X_test: (336, 1080)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 10:57:49,992] Trial 0 finished with value: 0.5442200352056208 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5442200352056208.
[I 2026-04-14 10:58:09,801] Trial 1 finished with value: 0.6000166409453915 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 10:58:20,079] Trial 2 finished with value: 0.544259403363513 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 10:58:46,776] Trial 3 finished with value: 0.5470062866474092 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 10:58:57,945] Trial 4 finished with value: 0.5492179769467516 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 10:58:59,989] Trial 5 pruned.
[I 2026-04-14 10:59:02,171] Trial 6 pruned.
[I 2026-04-14 10:59:04,495] Trial 7 pruned.
[I 2026-04-14 10:59:15,872] Trial 8 finished with value: 0.5478402581178137 and parameters: {'d_main': 256, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 3, 'context_dropout': 0.010604524216648726, 'dropout0': 0.23431023250938532, 'dropout1': 0.37609209656998305, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00014832651791730684, 'weight_decay': 1.167890125531533e-06, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 82, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.02820345725713065}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 10:59:20,380] Trial 9 pruned.
[I 2026-04-14 10:59:55,988] Trial 10 finished with value: 0.5768910017899292 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:00:28,197] Trial 11 finished with value: 0.5716460740442582 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39712509626059955, 'dropout0': 0.07904000679456186, 'dropout1': 0.1613812032159982, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.00424558651276101, 'weight_decay': 0.0022063664582440763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.059342324127145206}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:01:11,740] Trial 12 finished with value: 0.5866816573644165 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.32982709093296103, 'dropout0': 0.15146994791019802, 'dropout1': 0.14909628032060154, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.001857099958263517, 'weight_decay': 6.813822791771272e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 80, 'patience': 18, 'grad_clip': 5.0, 'label_smoothing': 0.03591914737041467}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:01:37,088] Trial 13 finished with value: 0.5996422205901387 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.1961855324427587, 'dropout0': 0.13660648681236293, 'dropout1': 0.021631521037705166, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0025730608945544564, 'weight_decay': 0.0007341254377909726, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.024701390620112004}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:02:03,924] Trial 14 finished with value: 0.5897313336245754 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.29427141055018485, 'dropout0': 0.02548152868809317, 'dropout1': 0.1474043269314995, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.002507711108159037, 'weight_decay': 0.00048497459594190313, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 87, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.006068219952540237}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:02:08,071] Trial 15 pruned.
[I 2026-04-14 11:02:12,041] Trial 16 pruned.
[I 2026-04-14 11:02:27,160] Trial 17 finished with value: 0.5663690297695221 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.3304495420004808, 'dropout0': 0.07444386723512761, 'dropout1': 0.192296918182707, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'radam', 'lr': 0.000887328071030671, 'weight_decay': 0.00038306595429711624, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.02209343319672202}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:02:30,462] Trial 18 pruned.
[I 2026-04-14 11:02:36,475] Trial 19 pruned.
[I 2026-04-14 11:02:48,489] Trial 20 finished with value: 0.5901632749736078 and parameters: {'d_main': 256, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3183145925032152, 'dropout0': 0.0022442744138120377, 'dropout1': 0.08138747120254178, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0035805949450720513, 'weight_decay': 0.002367767815267558, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.01107639248179311}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:02:50,536] Trial 21 pruned.
[I 2026-04-14 11:03:08,242] Trial 22 finished with value: 0.5834507937239917 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.28646052813994716, 'dropout0': 0.09803237666695061, 'dropout1': 0.009968247863484839, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0016446993064760508, 'weight_decay': 0.0004465008913664499, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 86, 'patience': 15, 'grad_clip': None, 'label_smoothing': 0.022459206026402737}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:03:20,867] Trial 23 finished with value: 0.5718759753604363 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.15526589947317943, 'dropout0': 0.20711923680368266, 'dropout1': 0.006399901033059945, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0023381498153163902, 'weight_decay': 0.001981382929756556, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 17, 'grad_clip': None, 'label_smoothing': 0.03518442572052745}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:03:22,708] Trial 24 pruned.
[I 2026-04-14 11:03:35,802] Trial 25 finished with value: 0.5919400941783846 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.36500698882876603, 'dropout0': 0.0870178703188971, 'dropout1': 0.057338639374917524, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.00473522516977528, 'weight_decay': 0.004314130864679661, 'batch_size': 1024, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.03267459318715371}. Best is trial 1 with value: 0.6000166409453915.
[I 2026-04-14 11:03:52,745] Trial 26 finished with value: 0.6075339759705156 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.33769637472841124, 'dropout0': 0.08515047417902985, 'dropout1': 0.02982389094929104, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0017805469915238418, 'weight_decay': 0.0007984894646406125, 'batch_size': 1024, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 20, 'grad_clip': 5.0, 'label_smoothing': 0.043520165443332856}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:03:58,372] Trial 27 pruned.
[I 2026-04-14 11:04:21,919] Trial 28 finished with value: 0.59544449817752 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.10823687400126775, 'dropout0': 0.05576466877098753, 'dropout1': 0.05517583328330795, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0017817593831917194, 'weight_decay': 0.001977444693596989, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.02528577896487664}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:04:24,469] Trial 29 pruned.
[I 2026-04-14 11:04:57,950] Trial 30 finished with value: 0.6011170434131141 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.34513105015294115, 'dropout0': 0.07822843565606594, 'dropout1': 0.0717258794053299, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0006420079253960156, 'weight_decay': 0.0003107719794434265, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 90, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.031059892695165233}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:05:04,433] Trial 31 pruned.
[I 2026-04-14 11:05:40,543] Trial 32 finished with value: 0.6043475535932462 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.3520070675655671, 'dropout0': 0.1912517444892543, 'dropout1': 0.010518861454405337, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0005008488971800889, 'weight_decay': 0.00021295147272580952, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.03167895571484905}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:06:27,947] Trial 33 finished with value: 0.6054833736617204 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.33489937956575294, 'dropout0': 0.1656617220165007, 'dropout1': 0.03599179821314216, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.00029785817090896994, 'weight_decay': 0.000889649567494086, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 83, 'patience': 15, 'grad_clip': 5.0, 'label_smoothing': 0.023089811592389736}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:06:50,461] Trial 34 finished with value: 0.5919810178010445 and parameters: {'d_main': 192, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.38176077683087734, 'dropout0': 0.19398546238217407, 'dropout1': 0.055481710220024766, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.000913738203669824, 'weight_decay': 0.0012049396978389003, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 83, 'patience': 20, 'grad_clip': 5.0, 'label_smoothing': 0.04864292907631344}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:06:59,811] Trial 35 pruned.
[I 2026-04-14 11:07:04,145] Trial 36 pruned.
[I 2026-04-14 11:08:01,857] Trial 37 finished with value: 0.6001108782799784 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.3208612284374597, 'dropout0': 0.108152270297729, 'dropout1': 0.09630563254298954, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0002251662068600056, 'weight_decay': 0.00046959616602894354, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 92, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.015689708745029292}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:08:04,140] Trial 38 pruned.
[I 2026-04-14 11:08:46,990] Trial 39 finished with value: 0.6020858986834381 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.25986885022050504, 'dropout0': 0.06987482104697507, 'dropout1': 0.012243364373804484, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0031593313419143155, 'weight_decay': 0.0025516857239237965, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 89, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.0523521328970087}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:09:24,296] Trial 40 finished with value: 0.5905248302099241 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.23827446270695127, 'dropout0': 0.08934568802132944, 'dropout1': 0.056640413489600826, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.00016373733522283938, 'weight_decay': 0.00034712449085391283, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 80, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.022492958402949608}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:09:30,620] Trial 41 pruned.
[I 2026-04-14 11:09:38,987] Trial 42 pruned.
[I 2026-04-14 11:09:40,819] Trial 43 pruned.
[I 2026-04-14 11:10:12,229] Trial 44 finished with value: 0.594667718119265 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.3283085350691914, 'dropout0': 0.10433279158576877, 'dropout1': 0.026367169195555186, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.0003001836660445194, 'weight_decay': 0.002112127439476123, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 81, 'patience': 16, 'grad_clip': 5.0, 'label_smoothing': 0.043785783922917286}. Best is trial 26 with value: 0.6075339759705156.
[I 2026-04-14 11:10:18,988] Trial 45 pruned.
[I 2026-04-14 11:11:04,775] Trial 46 finished with value: 0.6116196753896807 and parameters: {'d_main': 192, 'd_mult': 2.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.3609748977998658, 'dropout0': 0.061650050665887364, 'dropout1': 0.005900997825218845, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0033612233264610288, 'weight_decay': 0.002034938738715607, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 85, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.03561838066832908}. Best is trial 46 with value: 0.6116196753896807.
[I 2026-04-14 11:11:11,521] Trial 47 pruned.
[I 2026-04-14 11:11:13,036] Trial 48 pruned.
[I 2026-04-14 11:11:21,092] Trial 49 pruned.
[I 2026-04-14 11:13:22,351] Trial 50 finished with value: 0.5927232157986557 and parameters: {'d_main': 512, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.31774377619286553, 'dropout0': 0.0802501701682665, 'dropout1': 0.044310236777233974, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0032500990440370646, 'weight_decay': 0.004303286451251429, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.05649358389032523}. Best is trial 46 with value: 0.6116196753896807.
[I 2026-04-14 11:13:27,872] Trial 51 pruned.
[I 2026-04-14 11:14:13,213] Trial 52 finished with value: 0.6037188899532655 and parameters: {'d_main': 192, 'd_mult': 1.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.3248727139022216, 'dropout0': 0.0911364051754957, 'dropout1': 0.04675622427027694, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.003819229990518056, 'weight_decay': 0.0013190053235878586, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 88, 'patience': 20, 'grad_clip': 5.0, 'label_smoothing': 0.04297111442953321}. Best is trial 46 with value: 0.6116196753896807.
[I 2026-04-14 11:14:38,433] Trial 53 finished with value: 0.5979452245962265 and parameters: {'d_main': 192, 'd_mult': 1.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 3, 'context_dropout': 0.37497812357547516, 'dropout0': 0.281807701549725, 'dropout1': 0.11259986523627555, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.002748778772609775, 'weight_decay': 0.0043090107619206544, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.0307904528549017}. Best is trial 46 with value: 0.6116196753896807.
[I 2026-04-14 11:14:46,639] Trial 54 pruned.
[I 2026-04-14 11:14:52,995] Trial 55 pruned.
[I 2026-04-14 11:14:58,237] Trial 56 pruned.
[I 2026-04-14 11:15:01,351] Trial 57 pruned.

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,PID,match_mismatch,binary,False,0.509131,0.570499,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,binary,True,0.412698,0.559524,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch,multiclass,False,0.591670,0.585683,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch,multiclass,True,0.526278,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,PID,match_mismatch_general,binary,False,0.512506,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,PID,match_mismatch_general,binary,True,0.479882,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,PID,match_mismatch_general,multiclass,False,0.581319,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,PID,match_mismatch_general,multiclass,True,0.554460,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,PID,match_mismatch,binary,False,0.509131,0.570499,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,binary,True,0.412698,0.559524,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch,multiclass,False,0.591670,0.585683,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch,multiclass,True,0.526278,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,PID,match_mismatch_general,binary,False,0.512506,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,PID,match_mismatch_general,binary,True,0.479882,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,PID,match_mismatch_general,multiclass,False,0.581319,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,PID,match_mismatch_general,multiclass,True,0.554460,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [15]:

# Set: stat
text_stat = pd.read_parquet(TEXT2TEXT_FILES["stat"])
print("stat shape:", text_stat.shape)
summary_stat = run_text2text_set_tabr("stat", text_stat)
summary_stat

stat shape: (5592, 8237)
[stat] text2text feature count after cleanup: 8235
[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 11:16:08,693] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__gpu_optuna

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__gpu_optuna
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 11:16:17,174] Trial 0 finished with value: 0.4964346509868236 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.4964346509868236.
[I 2026-04-14 11:16:30,331] Trial 1 finished with value: 0.5023656254183245 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.5023656254183245.
[I 2026-04-14 11:16:49,514] Trial 2 finished with value: 0.5194748356872118 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 2 with value: 0.5194748356872118.
[I 2026-04-14 11:17:31,981] Trial 3 finished with value: 0.49632709395515334 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 2 with value: 0.5194748356872118.
[I 2026-04-14 11:17:51,866] Trial 4 finished with value: 0.5096890057291776 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 2 with value: 0.5194748356872118.
[I 2026-04-14 11:18:13,695] Trial 5 finished with value: 0.517235569881313 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.15723908986670418, 'dropout0': 0.35681862207084536, 'dropout1': 0.25245545039890516, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004175380307518435, 'weight_decay': 0.0024213408972073107, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 88, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.0696029796674973}. Best is trial 2 with value: 0.5194748356872118.
[I 2026-04-14 11:18:19,623] Trial 6 pruned.
[I 2026-04-14 11:18:39,374] Trial 7 finished with value: 0.5199852137638126 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.38505936587117007, 'dropout0': 0.33439204820488233, 'dropout1': 0.2783896824374792, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.0010947002036624288, 'weight_decay': 3.5652340426862525e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 94, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.043385164923797306}. Best is trial 7 with value: 0.5199852137638126.
[I 2026-04-14 11:18:43,917] Trial 8 pruned.
[I 2026-04-14 11:18:46,761] Trial 9 pruned.
[I 2026-04-14 11:18:51,684] Trial 10 pruned.
[I 2026-04-14 11:18:53,389] Trial 11 pruned.
[I 2026-04-14 11:18:56,349] Trial 12 pruned.
[I 2026-04-14 11:18:58,421] Trial 13 pruned.
[I 2026-04-14 11:19:02,501] Trial 14 pruned.
[I 2026-04-14 11:19:17,158] Trial 15 finished with value: 0.5204679359795413 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.12408846746137592, 'dropout0': 0.04789671676320952, 'dropout1': 0.009132254768267345, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.004238564089801298, 'weight_decay': 0.004345254466140302, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 85, 'patience': 13, 'grad_clip': 5.0, 'label_smoothing': 0.016991157539812538}. Best is trial 15 with value: 0.5204679359795413.
[I 2026-04-14 11:19:18,726] Trial 16 pruned.
[I 2026-04-14 11:19:35,308] Trial 17 finished with value: 0.5150166746744022 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.22866908600223257, 'dropout0': 0.10665236878922485, 'dropout1': 0.08998986507046117, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.004139296958758525, 'weight_decay': 0.00037658877108729386, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 90, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.011986065413301574}. Best is trial 15 with value: 0.5204679359795413.
[I 2026-04-14 11:19:39,946] Trial 18 pruned.
[I 2026-04-14 11:19:57,785] Trial 19 finished with value: 0.5112646231738335 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 1, 'context_dropout': 0.3327751441344151, 'dropout0': 0.10775690666294219, 'dropout1': 0.06825799233612079, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037780799476241933, 'weight_decay': 0.0004743169734953651, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.03765198841476776}. Best is trial 15 with value: 0.5204679359795413.
[I 2026-04-14 11:19:59,829] Trial 20 pruned.
[I 2026-04-14 11:20:02,215] Trial 21 pruned.
[I 2026-04-14 11:20:20,199] Trial 22 finished with value: 0.5253243036569235 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.09051288361883413, 'dropout0': 0.021180230531734873, 'dropout1': 0.2023809398926349, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.00417224419480588, 'weight_decay': 0.004827139703756242, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 90, 'patience': 15, 'grad_clip': 5.0, 'label_smoothing': 0.0068855244605701}. Best is trial 22 with value: 0.5253243036569235.
[I 2026-04-14 11:20:23,307] Trial 23 pruned.
[I 2026-04-14 11:20:27,805] Trial 24 pruned.
[I 2026-04-14 11:20:28,914] Trial 25 pruned.
[I 2026-04-14 11:20:30,933] Trial 26 pruned.
[I 2026-04-14 11:20:37,281] Trial 27 finished with value: 0.5199196635402386 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 1, 'context_dropout': 0.16126700746082864, 'dropout0': 0.1250579357910494, 'dropout1': 0.2669486898554699, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.0016471037587388684, 'weight_decay': 0.004360327184454262, 'batch_size': 1024, 'eval_batch_size': 256, 'max_epochs': 93, 'patience': 17, 'grad_clip': None, 'label_smoothing': 0.006936381131320358}. Best is trial 22 with value: 0.5253243036569235.
[I 2026-04-14 11:20:41,668] Trial 28 pruned.
[I 2026-04-14 11:20:43,347] Trial 29 pruned.
[I 2026-04-14 11:20:49,956] Trial 30 pruned.
[I 2026-04-14 11:20:51,384] Trial 31 pruned.
[I 2026-04-14 11:21:00,023] Trial 32 finished with value: 0.5157534862254024 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 1, 'context_dropout': 0.23155286566447342, 'dropout0': 0.15143915258068683, 'dropout1': 0.37098121060695044, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.003369901625793238, 'weight_decay': 0.0007433277486160997, 'batch_size': 1024, 'eval_batch_size': 256, 'max_epochs': 94, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.03367951384430788}. Best is trial 22 with value: 0.5253243036569235.
[I 2026-04-14 11:21:01,891] Trial 33 pruned.
[I 2026-04-14 11:21:03,252] Trial 34 pruned.
[I 2026-04-14 11:21:05,799] Trial 35 pruned.
[I 2026-04-14 11:21:25,604] Trial 36 finished with value: 0.514360258762635 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.14925136047490517, 'dropout0': 0.040222893229773876, 'dropout1': 0.09372413754457327, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'radam', 'lr': 0.00232723891961553, 'weight_decay': 0.004125157066717229, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 81, 'patience': 13, 'grad_clip': None, 'label_smoothing': 0.00385905836614955}. Best is trial 22 with value: 0.5253243036569235.
[I 2026-04-14 11:21:29,556] Trial 37 pruned.
[I 2026-04-14 11:21:31,759] Trial 38 pruned.
[I 2026-04-14 11:21:36,224] Trial 39 pruned.
[I 2026-04-14 11:21:48,286] Trial 40 finished with value: 0.5199738617261171 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.13962335088789726, 'dropout0': 0.14622923172954927, 'dropout1': 0.3192873867416392, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.0011811544191189498, 'weight_decay': 0.0011236269504616408, 'batch_size': 1024, 'eval_batch_size': 256, 'max_epochs': 85, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.002834923335868888}. Best is trial 22 with value: 0.5253243036569235.
[I 2026-04-14 11:21:49,976] Trial 41 pruned.
[I 2026-04-14 11:21:52,703] Trial 42 pruned.
[I 2026-04-14 11:22:12,457] Trial 43 finished with value: 0.5267627610710566 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.09862433689361724, 'dropout0': 0.045445205599548455, 'dropout1': 0.29332460779934333, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.002588436627189149, 'weight_decay': 0.0006176120486317223, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 89, 'patience': 15, 'grad_clip': 1.0, 'label_smoothing': 0.01989222225423638}. Best is trial 43 with value: 0.5267627610710566.
[I 2026-04-14 11:23:02,542] Trial 44 finished with value: 0.5294245673079082 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.2058546973772551, 'dropout0': 0.09135976624816965, 'dropout1': 0.3407430071454286, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0024989278938848405, 'weight_decay': 0.0005880083323933591, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 91, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.05042403772533161}. Best is trial 44 with value: 0.5294245673079082.
[I 2026-04-14 11:23:06,669] Trial 45 pruned.
[I 2026-04-14 11:23:11,339] Trial 46 pruned.
[I 2026-04-14 11:23:14,917] Trial 47 pruned.
[I 2026-04-14 11:23:17,988] Trial 48 pruned.
[I 2026-04-14 11:23:48,490] Trial 49 finished with value: 0.5232846561090074 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.340284052015548, 'dropout0': 0.3092231435967694, 'dropout1': 0.19815296221074763, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.0017851179485848924, 'weight_decay': 5.113943807010791e-06, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 96, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.03266958369302234}. Best is trial 44 with value: 0.5294245673079082.
[I 2026-04-14 11:23:52,340] Trial 50 pruned.
[I 2026-04-14 11:24:01,579] Trial 51 pruned.
[I 2026-04-14 11:24:06,222] Trial 52 pruned.
[I 2026-04-14 11:24:08,795] Trial 53 pruned.
[I 2026-04-14 11:24:44,150] Trial 54 finished with value: 0.514681530689387 and parameters: {'d_main': 512, 'd_mult': 4.0, 'encoder_n_blocks': 1, 'predictor_n_blocks': 2, 'context_dropout': 0.3608516820746795, 'dropout0': 0.274747363507065, 'dropout1': 0.20761979083320303, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.0009893330357395962, 'weight_decay': 1.1576160190271686e-05, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 96, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.058983248260765134}. Best is trial 44 with value: 0.5294245673079082.
[I 2026-04-14 11:25:19,686] Trial 55 finished with value: 0.5196439713474615 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.3760394986138813, 'dropout0': 0.274930350869825, 'dropout1': 0.14143771814752099, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.0011145045816213096, 'weight_decay': 1.411640238851541e-05, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 99, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.026054533267885933}. Best is trial 44 with value: 0.5294245673079082.
[I 2026-04-14 11:25:23,691] Trial 56 pruned.
[I 2026-04-14 11:25:32,920] Trial 57 pruned.
[I 2026-04-14 11:25:39,968] Trial 58 pruned.
[I 2026-04-14 11:25:41,672] Trial 59 pruned.
[stat] rows missing after index match -> train: 1004, test: 104
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 11:26:28,299] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__gpu_optuna__no_neutral

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__gpu_optuna__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 11:26:34,803] Trial 0 finished with value: 0.5146127082578629 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5146127082578629.
[I 2026-04-14 11:26:45,795] Trial 1 finished with value: 0.5315531289969064 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.5315531289969064.
[I 2026-04-14 11:26:55,861] Trial 2 finished with value: 0.5292696839446482 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.5315531289969064.
[I 2026-04-14 11:27:19,705] Trial 3 finished with value: 0.5048438138712141 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.5315531289969064.
[I 2026-04-14 11:27:33,802] Trial 4 finished with value: 0.4955695672817107 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.5315531289969064.
[I 2026-04-14 11:27:38,307] Trial 5 pruned.
[I 2026-04-14 11:27:41,918] Trial 6 pruned.
[I 2026-04-14 11:27:44,051] Trial 7 pruned.
[I 2026-04-14 11:27:54,696] Trial 8 pruned.
[I 2026-04-14 11:27:56,726] Trial 9 pruned.
[I 2026-04-14 11:28:21,644] Trial 10 finished with value: 0.5281893899293015 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.5315531289969064.
[I 2026-04-14 11:28:37,648] Trial 11 finished with value: 0.5323421405284525 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.07542246950764894, 'dropout0': 0.10161711586645106, 'dropout1': 0.025049523817679258, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.002769957572686573, 'weight_decay': 0.00015021329913563166, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 14, 'grad_clip': 1.0, 'label_smoothing': 0.03400233374960418}. Best is trial 11 with value: 0.5323421405284525.
[I 2026-04-14 11:29:02,264] Trial 12 finished with value: 0.5392651593368123 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 1, 'context_dropout': 0.10314418937245005, 'dropout0': 0.18223089435544426, 'dropout1': 0.08489076536681174, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.001901574878003524, 'weight_decay': 6.937724914938807e-05, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 82, 'patience': 15, 'grad_clip': 1.0, 'label_smoothing': 0.02342742919409222}. Best is trial 12 with value: 0.5392651593368123.
[I 2026-04-14 11:29:21,861] Trial 13 pruned.
[I 2026-04-14 11:29:24,868] Trial 14 pruned.
[I 2026-04-14 11:29:47,469] Trial 15 finished with value: 0.5396722293406501 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.09186052831391284, 'dropout0': 0.20692108416346114, 'dropout1': 0.21778772550618988, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.0027672297485079357, 'weight_decay': 0.00010903132379876728, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 85, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.02607403745481151}. Best is trial 15 with value: 0.5396722293406501.
[I 2026-04-14 11:29:50,241] Trial 16 pruned.
[I 2026-04-14 11:30:00,552] Trial 17 pruned.
[I 2026-04-14 11:30:03,538] Trial 18 pruned.
[I 2026-04-14 11:30:15,648] Trial 19 finished with value: 0.5327468693845161 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.03579444967898029, 'dropout0': 0.23135291104494551, 'dropout1': 0.2167005115897982, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.0022761118886048294, 'weight_decay': 0.00022190144958912644, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 86, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.007676915592517038}. Best is trial 15 with value: 0.5396722293406501.
[I 2026-04-14 11:30:18,480] Trial 20 pruned.
[I 2026-04-14 11:30:29,193] Trial 21 pruned.
[I 2026-04-14 11:30:31,937] Trial 22 pruned.
[I 2026-04-14 11:30:33,976] Trial 23 pruned.
[I 2026-04-14 11:30:37,536] Trial 24 pruned.
[I 2026-04-14 11:30:41,141] Trial 25 pruned.
[I 2026-04-14 11:30:43,653] Trial 26 pruned.
[I 2026-04-14 11:30:52,585] Trial 27 pruned.
[I 2026-04-14 11:30:54,867] Trial 28 pruned.
[I 2026-04-14 11:30:57,497] Trial 29 pruned.
[I 2026-04-14 11:31:29,103] Trial 30 finished with value: 0.4961536582869184 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.14229270625756715, 'dropout0': 0.16111016920662732, 'dropout1': 0.03447484628370026, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.004018964668964207, 'weight_decay': 0.00023797133336572106, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 12, 'grad_clip': 1.0, 'label_smoothing': 0.012602833445580441}. Best is trial 15 with value: 0.5396722293406501.
[I 2026-04-14 11:31:31,352] Trial 31 pruned.
[I 2026-04-14 11:31:38,720] Trial 32 pruned.
[I 2026-04-14 11:31:40,736] Trial 33 pruned.
[I 2026-04-14 11:32:01,859] Trial 34 finished with value: 0.5407905041648507 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.014749497481775793, 'dropout0': 0.1289752117897947, 'dropout1': 0.12002277980246137, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.004522120959279323, 'weight_decay': 0.0002223148521339128, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.040024779928794524}. Best is trial 34 with value: 0.5407905041648507.
[I 2026-04-14 11:32:16,450] Trial 35 pruned.
[I 2026-04-14 11:32:54,863] Trial 36 finished with value: 0.544765146864496 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.07234427728015905, 'dropout0': 0.19163180349072012, 'dropout1': 0.1569009469866092, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.003421134749399928, 'weight_decay': 0.0003316875278483267, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 82, 'patience': 14, 'grad_clip': 2.0, 'label_smoothing': 0.0447617313678688}. Best is trial 36 with value: 0.544765146864496.
[I 2026-04-14 11:33:00,031] Trial 37 pruned.
[I 2026-04-14 11:33:02,899] Trial 38 pruned.
[I 2026-04-14 11:33:05,134] Trial 39 pruned.
[I 2026-04-14 11:33:08,813] Trial 40 pruned.
[I 2026-04-14 11:33:11,749] Trial 41 pruned.
[I 2026-04-14 11:33:22,509] Trial 42 pruned.
[I 2026-04-14 11:33:26,495] Trial 43 pruned.
[I 2026-04-14 11:33:28,752] Trial 44 pruned.
[I 2026-04-14 11:33:33,663] Trial 45 pruned.
[I 2026-04-14 11:33:43,134] Trial 46 pruned.
[I 2026-04-14 11:34:12,225] Trial 47 finished with value: 0.5457929132391336 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.06188792327073587, 'dropout0': 0.12171213548870115, 'dropout1': 0.20409568252079024, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0030051494376354838, 'weight_decay': 0.0003155090550166899, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 82, 'patience': 13, 'grad_clip': 2.0, 'label_smoothing': 0.02590781572208325}. Best is trial 47 with value: 0.5457929132391336.
[I 2026-04-14 11:34:13,339] Trial 48 pruned.
[I 2026-04-14 11:34:57,808] Trial 49 finished with value: 0.555346205873212 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.12571357402696678, 'dropout0': 0.24677089998745969, 'dropout1': 0.2228750228943785, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.002983417696432703, 'weight_decay': 0.000669696816192227, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 82, 'patience': 16, 'grad_clip': 2.0, 'label_smoothing': 0.008021298075432247}. Best is trial 49 with value: 0.555346205873212.
[I 2026-04-14 11:35:47,678] Trial 50 finished with value: 0.5347356895698523 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.13305738789965343, 'dropout0': 0.24805767543960816, 'dropout1': 0.16833694916824093, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0012692677770328158, 'weight_decay': 0.0012348068900533739, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.025980740697882348}. Best is trial 49 with value: 0.555346205873212.
[I 2026-04-14 11:35:53,395] Trial 51 pruned.
[I 2026-04-14 11:35:59,769] Trial 52 pruned.
[I 2026-04-14 11:36:05,061] Trial 53 pruned.
[I 2026-04-14 11:36:38,949] Trial 54 finished with value: 0.5400887063291288 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.05531580760513743, 'dropout0': 0.15048650782071255, 'dropout1': 0.16389793572984623, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.003859440105405796, 'weight_decay': 0.0019859519348183184, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 85, 'patience': 13, 'grad_clip': 5.0, 'label_smoothing': 0.04107259803238746}. Best is trial 49 with value: 0.555346205873212.
[I 2026-04-14 11:36:59,454] Trial 55 pruned.
[I 2026-04-14 11:37:04,992] Trial 56 pruned.
[I 2026-04-14 11:37:14,404] Trial 57 pruned.
[I 2026-04-14 11:37:19,823] Trial 58 pruned.
[I 2026-04-14 11:37:26,724] Trial 59 pruned.
[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 11:38:05,219] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__gpu_optuna

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__gpu_optuna
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 11:38:31,135] Trial 0 finished with value: 0.5090505356482075 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5090505356482075.
[I 2026-04-14 11:38:56,535] Trial 1 finished with value: 0.5825741739992732 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:39:21,498] Trial 2 finished with value: 0.49487551827140075 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:40:08,990] Trial 3 finished with value: 0.46378798978973784 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:40:43,840] Trial 4 finished with value: 0.48743012797014457 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:41:16,768] Trial 5 finished with value: 0.5109238265504523 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.15723908986670418, 'dropout0': 0.35681862207084536, 'dropout1': 0.25245545039890516, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004175380307518435, 'weight_decay': 0.0024213408972073107, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 88, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.0696029796674973}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:41:49,701] Trial 6 finished with value: 0.5130632271849105 and parameters: {'d_main': 384, 'd_mult': 2.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.32374446219140546, 'dropout0': 0.3240453578716723, 'dropout1': 0.3468289274320415, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0009604629436055072, 'weight_decay': 1.3581551746635542e-06, 'batch_size': 1024, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 16, 'grad_clip': None, 'label_smoothing': 0.00516817211686077}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:42:16,538] Trial 7 finished with value: 0.5612301414433444 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.38505936587117007, 'dropout0': 0.33439204820488233, 'dropout1': 0.2783896824374792, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.0010947002036624288, 'weight_decay': 3.5652340426862525e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 94, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.043385164923797306}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:42:30,857] Trial 8 pruned.
[I 2026-04-14 11:43:08,049] Trial 9 finished with value: 0.5395871935226556 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.30181714963387296, 'dropout0': 0.04124954753437304, 'dropout1': 0.3610211626718267, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0009424401316515453, 'weight_decay': 0.00021734361959774786, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 12, 'grad_clip': 2.0, 'label_smoothing': 0.011706701642760588}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:44:21,837] Trial 10 finished with value: 0.5683797779839922 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:45:18,718] Trial 11 finished with value: 0.5019171737250802 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39712509626059955, 'dropout0': 0.07904000679456186, 'dropout1': 0.1613812032159982, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.00424558651276101, 'weight_decay': 0.0022063664582440763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.059342324127145206}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:46:12,519] Trial 12 finished with value: 0.5654105351255716 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.32982709093296103, 'dropout0': 0.15146994791019802, 'dropout1': 0.14909628032060154, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.001857099958263517, 'weight_decay': 6.813822791771272e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 80, 'patience': 18, 'grad_clip': 5.0, 'label_smoothing': 0.03591914737041467}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:46:22,538] Trial 13 pruned.
[I 2026-04-14 11:46:42,454] Trial 14 finished with value: 0.5814466046823177 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3122437102461093, 'dropout0': 0.1128964869734983, 'dropout1': 0.04644482368458544, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0017841306161028542, 'weight_decay': 2.5766762099090374e-05, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 89, 'patience': 15, 'grad_clip': None, 'label_smoothing': 0.05103124128788783}. Best is trial 1 with value: 0.5825741739992732.
[I 2026-04-14 11:46:48,472] Trial 15 pruned.
[I 2026-04-14 11:47:04,725] Trial 16 finished with value: 0.5883948288678094 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3472747634926119, 'dropout0': 0.05041546071527933, 'dropout1': 0.05022782941419018, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0011974221258591736, 'weight_decay': 0.00020315120551706243, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.03495101658368352}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:47:26,146] Trial 17 finished with value: 0.5760163714869566 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.21406218526842982, 'dropout0': 0.06975910010047442, 'dropout1': 0.11977277830628164, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0022599439381296525, 'weight_decay': 0.0013573676179012156, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 93, 'patience': 14, 'grad_clip': 1.0, 'label_smoothing': 0.03534053559183939}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:48:15,385] Trial 18 finished with value: 0.5648802493928213 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.386549525898094, 'dropout0': 0.006614899724325916, 'dropout1': 0.0676018219560319, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0019991785990839763, 'weight_decay': 0.0005478806949662774, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 86, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.01930236426158053}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:48:27,184] Trial 19 finished with value: 0.5722400267640768 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 1, 'context_dropout': 0.3965037844768406, 'dropout0': 0.10920340198277956, 'dropout1': 0.08665964652375945, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00226541226380743, 'weight_decay': 5.4751236751211014e-05, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 100, 'patience': 15, 'grad_clip': 1.0, 'label_smoothing': 0.05159924073426149}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:49:05,461] Trial 20 finished with value: 0.5729838325935951 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.32912864256850904, 'dropout0': 0.01299416872220802, 'dropout1': 0.17783968548893092, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00107403239544697, 'weight_decay': 0.001813990315727691, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 84, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.027654572469847264}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:49:38,105] Trial 21 finished with value: 0.5708249859547798 and parameters: {'d_main': 384, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.3503605378981804, 'dropout0': 0.03310898306625834, 'dropout1': 0.07119759261286782, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.000557132819233308, 'weight_decay': 5.0778808564424454e-05, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 89, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.011815888097300688}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:49:41,103] Trial 22 pruned.
[I 2026-04-14 11:49:57,504] Trial 23 finished with value: 0.5876669612159676 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.27696886157708833, 'dropout0': 0.022606521186538758, 'dropout1': 0.06225298974835548, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0006216975860325339, 'weight_decay': 0.00029014063128811817, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 92, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.014716275951534415}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:50:09,120] Trial 24 finished with value: 0.5804727156553622 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 1, 'context_dropout': 0.24473243655621862, 'dropout0': 0.11762722916709156, 'dropout1': 0.017428484324669, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0012958811570996762, 'weight_decay': 0.0013697103699383682, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 94, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0357030782740962}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:50:12,363] Trial 25 pruned.
[I 2026-04-14 11:50:28,850] Trial 26 finished with value: 0.5801203593966101 and parameters: {'d_main': 256, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.33805018944179016, 'dropout0': 0.06289713963766913, 'dropout1': 0.019053029779766816, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.0016017764963070565, 'weight_decay': 0.00021387777553787316, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 92, 'patience': 15, 'grad_clip': None, 'label_smoothing': 0.026737857255716167}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:50:33,310] Trial 27 pruned.
[I 2026-04-14 11:50:37,466] Trial 28 pruned.
[I 2026-04-14 11:50:57,216] Trial 29 finished with value: 0.5828629883047498 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3637430548376131, 'dropout0': 0.09259986439885123, 'dropout1': 0.04356778577932926, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0011266219924982216, 'weight_decay': 0.001986939485128948, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 91, 'patience': 16, 'grad_clip': None, 'label_smoothing': 0.01368188835472008}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:51:45,270] Trial 30 finished with value: 0.5879267590240539 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3805016049036511, 'dropout0': 0.048703841337996705, 'dropout1': 0.0013273058398021106, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0028646652490274876, 'weight_decay': 0.0011652289014574574, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.015339959603065088}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:52:35,807] Trial 31 finished with value: 0.579185773406765 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3984067651192895, 'dropout0': 0.025546637051514717, 'dropout1': 0.007503954934723078, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0037869119864876147, 'weight_decay': 0.0017668888514646441, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 14, 'grad_clip': 1.0, 'label_smoothing': 0.04369216570447265}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:53:16,895] Trial 32 finished with value: 0.5856098897585952 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.36554762662056917, 'dropout0': 0.1669769648345383, 'dropout1': 0.004343445700414774, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.00187995227382571, 'weight_decay': 0.0006213800049463889, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 80, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.019809014611027097}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:53:20,210] Trial 33 pruned.
[I 2026-04-14 11:54:23,696] Trial 34 pruned.
[I 2026-04-14 11:54:30,484] Trial 35 pruned.
[I 2026-04-14 11:54:45,671] Trial 36 pruned.
[I 2026-04-14 11:54:51,013] Trial 37 pruned.
[I 2026-04-14 11:54:54,930] Trial 38 pruned.
[I 2026-04-14 11:55:42,386] Trial 39 finished with value: 0.5837497767653381 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.39657286954659643, 'dropout0': 0.22575797387983756, 'dropout1': 0.03347752994695043, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0008492867497758058, 'weight_decay': 0.0003176105496112491, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 80, 'patience': 16, 'grad_clip': None, 'label_smoothing': 0.010344100648258992}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:55:49,881] Trial 40 pruned.
[I 2026-04-14 11:56:08,492] Trial 41 finished with value: 0.5845461999902362 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.37115799891195217, 'dropout0': 0.22990218714229874, 'dropout1': 0.025858019111547816, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0013594867709773833, 'weight_decay': 7.165541842850444e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 80, 'patience': 15, 'grad_clip': 1.0, 'label_smoothing': 0.03821856246086025}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:56:13,799] Trial 42 pruned.
[I 2026-04-14 11:56:16,238] Trial 43 pruned.
[I 2026-04-14 11:56:57,280] Trial 44 finished with value: 0.5835946399423975 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.31454018139027806, 'dropout0': 0.025121792938339493, 'dropout1': 0.039500716941669206, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'radam', 'lr': 0.0011917772978809152, 'weight_decay': 8.535195942069407e-05, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 81, 'patience': 13, 'grad_clip': None, 'label_smoothing': 0.015076287744448223}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:56:59,737] Trial 45 pruned.
[I 2026-04-14 11:57:07,175] Trial 46 pruned.
[I 2026-04-14 11:57:22,669] Trial 47 finished with value: 0.5831354622348168 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.367349556724881, 'dropout0': 0.03219346236988953, 'dropout1': 0.10328974297550435, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0005023818108421951, 'weight_decay': 0.0003898986078769426, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 98, 'patience': 14, 'grad_clip': None, 'label_smoothing': 0.028928771842370072}. Best is trial 16 with value: 0.5883948288678094.
[I 2026-04-14 11:57:41,384] Trial 48 pruned.
[I 2026-04-14 11:57:44,478] Trial 49 pruned.

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 12:03:24,407] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__gpu_optuna__no_neutral

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__gpu_optuna__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 12:03:32,386] Trial 0 finished with value: 0.5055690581460108 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5055690581460108.
[I 2026-04-14 12:03:41,951] Trial 1 finished with value: 0.5362572437003819 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:03:52,315] Trial 2 finished with value: 0.5223325428898822 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:04:25,476] Trial 3 finished with value: 0.5096725913763025 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:04:39,684] Trial 4 finished with value: 0.5143461111863287 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:04:53,098] Trial 5 finished with value: 0.5224028509061995 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.15723908986670418, 'dropout0': 0.35681862207084536, 'dropout1': 0.25245545039890516, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004175380307518435, 'weight_decay': 0.0024213408972073107, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 88, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.0696029796674973}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:04:57,797] Trial 6 pruned.
[I 2026-04-14 12:05:00,412] Trial 7 pruned.
[I 2026-04-14 12:05:04,024] Trial 8 pruned.
[I 2026-04-14 12:05:18,114] Trial 9 finished with value: 0.5193343282242038 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.30181714963387296, 'dropout0': 0.04124954753437304, 'dropout1': 0.3610211626718267, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0009424401316515453, 'weight_decay': 0.00021734361959774786, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 12, 'grad_clip': 2.0, 'label_smoothing': 0.011706701642760588}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:05:51,433] Trial 10 finished with value: 0.5270345589289662 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.5362572437003819.
[I 2026-04-14 12:06:27,790] Trial 11 finished with value: 0.5450761589946714 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39712509626059955, 'dropout0': 0.07904000679456186, 'dropout1': 0.1613812032159982, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.00424558651276101, 'weight_decay': 0.0022063664582440763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.059342324127145206}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:06:47,100] Trial 12 finished with value: 0.5345235133614235 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 1, 'context_dropout': 0.37739701169262896, 'dropout0': 0.03801015619715413, 'dropout1': 0.1189445566373881, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.001556254819747517, 'weight_decay': 0.0034870424637370983, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 83, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.08228902357649145}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:07:00,438] Trial 13 finished with value: 0.5273525066407622 and parameters: {'d_main': 256, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.28509750148942037, 'dropout0': 0.12028725961374612, 'dropout1': 0.15272402516864048, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0010659040931050069, 'weight_decay': 0.0014577183199088754, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.013070013804503951}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:07:31,789] Trial 14 finished with value: 0.5303170812916034 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3382512958231473, 'dropout0': 0.047285499969018534, 'dropout1': 0.18547139590214007, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0031735392841740575, 'weight_decay': 0.0012474048449047025, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.056286110639816964}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:07:58,053] Trial 15 finished with value: 0.5428449835151096 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.19250474053154504, 'dropout0': 0.1318376012950459, 'dropout1': 0.01912840378592484, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.003085866152753004, 'weight_decay': 2.378862492807689e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 16, 'grad_clip': None, 'label_smoothing': 0.005379077207651156}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:08:03,191] Trial 16 pruned.
[I 2026-04-14 12:08:20,222] Trial 17 finished with value: 0.5300554802583909 and parameters: {'d_main': 192, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.08937245891874682, 'dropout0': 0.11801399711580642, 'dropout1': 0.1024448389111667, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00349107477337341, 'weight_decay': 0.00027345799869952933, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 89, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.01755603293667172}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:08:25,519] Trial 18 pruned.
[I 2026-04-14 12:08:36,168] Trial 19 pruned.
[I 2026-04-14 12:09:04,561] Trial 20 finished with value: 0.5307370056039576 and parameters: {'d_main': 256, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.14926882535660943, 'dropout0': 0.07161568061031406, 'dropout1': 0.006301404203303053, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0042870258796456825, 'weight_decay': 8.355394865858487e-05, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 92, 'patience': 17, 'grad_clip': None, 'label_smoothing': 0.0020754157837119206}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:09:08,115] Trial 21 pruned.
[I 2026-04-14 12:09:45,877] Trial 22 finished with value: 0.5407489260702874 and parameters: {'d_main': 512, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39835842789512904, 'dropout0': 0.15492680003969955, 'dropout1': 0.19889597982830134, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004604241917138281, 'weight_decay': 0.0011660521208503832, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.05899369322700919}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:09:49,158] Trial 23 pruned.
[I 2026-04-14 12:09:51,493] Trial 24 pruned.
[I 2026-04-14 12:10:14,388] Trial 25 finished with value: 0.5365627941261233 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.22913520788909125, 'dropout0': 0.16723427929680074, 'dropout1': 0.09665272099605228, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00354598514070063, 'weight_decay': 8.159331468461504e-05, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 85, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.009649245373614447}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:10:23,675] Trial 26 pruned.
[I 2026-04-14 12:11:00,273] Trial 27 finished with value: 0.5374003152290661 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.296654019515333, 'dropout0': 0.17092311760721507, 'dropout1': 0.20378686858442444, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004110551176508591, 'weight_decay': 0.0014094226583887144, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 81, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.06394978982191826}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:11:04,010] Trial 28 pruned.
[I 2026-04-14 12:11:06,125] Trial 29 pruned.
[I 2026-04-14 12:11:11,400] Trial 30 pruned.
[I 2026-04-14 12:11:49,592] Trial 31 finished with value: 0.5434970577779655 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.3942583250715622, 'dropout0': 0.09983096913150254, 'dropout1': 0.09887146115144615, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'radam', 'lr': 0.004151783244148759, 'weight_decay': 0.001933636909845272, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 82, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.08720356409473504}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:11:55,087] Trial 32 pruned.
[I 2026-04-14 12:12:00,013] Trial 33 pruned.
[I 2026-04-14 12:12:02,872] Trial 34 pruned.
[I 2026-04-14 12:12:46,851] Trial 35 finished with value: 0.5390150147921773 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3602895698789782, 'dropout0': 0.1849195114976986, 'dropout1': 0.22428285488214725, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0040463352486468105, 'weight_decay': 0.0033931823336871515, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.07337577442361987}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:13:03,803] Trial 36 pruned.
[I 2026-04-14 12:13:37,512] Trial 37 finished with value: 0.5369465178874503 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.3593863453194071, 'dropout0': 0.24142935103319402, 'dropout1': 0.024872803863315404, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'radam', 'lr': 0.004162960443082224, 'weight_decay': 0.0008508285443322866, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.09073965024178392}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:14:09,956] Trial 38 finished with value: 0.5358639400477212 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39448869748610144, 'dropout0': 0.11992341790512137, 'dropout1': 0.015116095153748399, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'radam', 'lr': 0.0024260909943919174, 'weight_decay': 0.001300418218808526, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 85, 'patience': 17, 'grad_clip': 2.0, 'label_smoothing': 0.08067559394571801}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:14:41,678] Trial 39 finished with value: 0.5339923852750387 and parameters: {'d_main': 512, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.33307275538444475, 'dropout0': 0.18675439841419572, 'dropout1': 0.14572689917235326, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0012140068790750219, 'weight_decay': 0.0004946492273163543, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.05275919901198122}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:14:44,379] Trial 40 pruned.
[I 2026-04-14 12:14:47,653] Trial 41 pruned.
[I 2026-04-14 12:15:31,399] Trial 42 finished with value: 0.540528033193618 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.3020123751438558, 'dropout0': 0.15982988154096053, 'dropout1': 0.1599603811711971, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0014310277900514937, 'weight_decay': 0.003651148798565912, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 83, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.08207495183610723}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:15:39,261] Trial 43 pruned.
[I 2026-04-14 12:15:46,578] Trial 44 pruned.
[I 2026-04-14 12:16:01,456] Trial 45 pruned.
[I 2026-04-14 12:16:07,634] Trial 46 pruned.
[I 2026-04-14 12:17:00,668] Trial 47 finished with value: 0.5297278193671145 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.35239482289093343, 'dropout0': 0.11090050063645374, 'dropout1': 0.18282247142969887, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0005331921886969452, 'weight_decay': 0.0031822857195711015, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': 1.0, 'label_smoothing': 0.07908634392644198}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:17:12,488] Trial 48 pruned.
[I 2026-04-14 12:17:19,699] Trial 49 pruned.
[I 2026-04-14 12:17:29,426] Trial 50 pruned.
[I 2026-04-14 12:17:39,658] Trial 51 pruned.
[I 2026-04-14 12:18:30,816] Trial 52 finished with value: 0.5368471247828239 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.1771215144622051, 'dropout0': 0.13697530049752582, 'dropout1': 0.05050073817646439, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0047536970569474965, 'weight_decay': 0.0021621697942270433, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 86, 'patience': 17, 'grad_clip': None, 'label_smoothing': 0.006676614273129752}. Best is trial 11 with value: 0.5450761589946714.
[I 2026-04-14 12:19:00,533] Trial 53 finished with value: 0.5517723323167556 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.2953330488869643, 'dropout0': 0.20664922377510428, 'dropout1': 0.18044580773800256, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.0022803371677596203, 'weight_decay': 0.0018431659725852041, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 88, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.06651114396780773}. Best is trial 53 with value: 0.5517723323167556.
[I 2026-04-14 12:19:06,158] Trial 54 pruned.
[I 2026-04-14 12:19:12,621] Trial 55 pruned.
[I 2026-04-14 12:19:16,259] Trial 56 pruned.
[I 2026-04-14 12:19:19,526] Trial 57 pruned.
[I 2026-04-14 12:19:23,683] Trial 58 pruned.
[I 2026-04-14 12:19:52,483] Trial 59 finished with value: 0.54015030309695 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.3226190692004243, 'dropout0': 0.38559374375027544, 'dropout1': 0.18182295094566378, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.004199859698935561, 'weight_decay': 0.0006065608601446679, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 89, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.06857050053740704}. Best is trial 53 with value: 0.5517723323167556.
[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 12:20:26,592] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__gpu_optuna

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__gpu_optuna
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 12:20:33,586] Trial 0 finished with value: 0.5376523773309184 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:20:49,503] Trial 1 finished with value: 0.5350783670621742 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:21:02,706] Trial 2 finished with value: 0.5320931297152015 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:21:45,799] Trial 3 finished with value: 0.5271759791673429 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:22:02,647] Trial 4 finished with value: 0.527098801283931 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:22:18,177] Trial 5 pruned.
[I 2026-04-14 12:22:24,798] Trial 6 pruned.
[I 2026-04-14 12:22:27,878] Trial 7 pruned.
[I 2026-04-14 12:22:50,328] Trial 8 finished with value: 0.5343644045022276 and parameters: {'d_main': 256, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 3, 'context_dropout': 0.010604524216648726, 'dropout0': 0.23431023250938532, 'dropout1': 0.37609209656998305, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00014832651791730684, 'weight_decay': 1.167890125531533e-06, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 82, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.02820345725713065}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:22:56,822] Trial 9 pruned.
[I 2026-04-14 12:23:02,104] Trial 10 pruned.
[I 2026-04-14 12:23:37,843] Trial 11 finished with value: 0.5298492042423908 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.32383194473890287, 'dropout0': 0.09747228366174951, 'dropout1': 0.04212226961513885, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0029942904735321884, 'weight_decay': 0.00011963062325273208, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 83, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.056940125824247595}. Best is trial 0 with value: 0.5376523773309184.
[I 2026-04-14 12:23:52,051] Trial 12 finished with value: 0.538885235872153 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.3188311755967872, 'dropout0': 0.1356905558300161, 'dropout1': 0.11430560917666928, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0024623288195867545, 'weight_decay': 0.0002417666787410597, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 19, 'grad_clip': 1.0, 'label_smoothing': 0.0224401686285883}. Best is trial 12 with value: 0.538885235872153.
[I 2026-04-14 12:23:57,173] Trial 13 pruned.
[I 2026-04-14 12:24:00,628] Trial 14 pruned.
[I 2026-04-14 12:24:02,658] Trial 15 pruned.
[I 2026-04-14 12:24:04,947] Trial 16 pruned.
[I 2026-04-14 12:24:18,147] Trial 17 finished with value: 0.5383698760618116 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3707574505500881, 'dropout0': 0.14951002358104065, 'dropout1': 0.26012928914133404, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.0001932626422485217, 'weight_decay': 0.0003258179385873028, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 12, 'grad_clip': 1.0, 'label_smoothing': 0.005836032640566159}. Best is trial 12 with value: 0.538885235872153.
[I 2026-04-14 12:24:20,874] Trial 18 pruned.
[I 2026-04-14 12:24:34,541] Trial 19 finished with value: 0.5367770081344065 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.23117511213801167, 'dropout0': 0.18217091887618725, 'dropout1': 0.25186198394757164, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'radam', 'lr': 0.0003083976957652371, 'weight_decay': 0.0005166402433293683, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.0036482911994803508}. Best is trial 12 with value: 0.538885235872153.
[I 2026-04-14 12:24:42,777] Trial 20 pruned.
[I 2026-04-14 12:24:51,669] Trial 21 finished with value: 0.5352454324240866 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.34508074703543634, 'dropout0': 0.01846635342201941, 'dropout1': 0.2596272825917428, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.0001794230288585926, 'weight_decay': 9.593946813871211e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 87, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.012878284511051129}. Best is trial 12 with value: 0.538885235872153.
[I 2026-04-14 12:24:55,419] Trial 22 pruned.
[I 2026-04-14 12:24:57,008] Trial 23 pruned.
[I 2026-04-14 12:25:00,368] Trial 24 pruned.
[I 2026-04-14 12:25:02,897] Trial 25 pruned.
[I 2026-04-14 12:25:06,063] Trial 26 pruned.
[I 2026-04-14 12:25:17,668] Trial 27 finished with value: 0.5439187436470179 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.2401074896798039, 'dropout0': 0.0267718079765527, 'dropout1': 0.07625507622575108, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.0006568714621752751, 'weight_decay': 5.072792335403898e-05, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 87, 'patience': 13, 'grad_clip': 2.0, 'label_smoothing': 0.01209823245854915}. Best is trial 27 with value: 0.5439187436470179.
[I 2026-04-14 12:25:19,790] Trial 28 pruned.
[I 2026-04-14 12:25:43,152] Trial 29 finished with value: 0.530896978881765 and parameters: {'d_main': 192, 'd_mult': 2.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.3749342283054948, 'dropout0': 0.16300938944390495, 'dropout1': 0.18217212364433405, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00029391612083506404, 'weight_decay': 0.00039528082307578713, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 100, 'patience': 12, 'grad_clip': 2.0, 'label_smoothing': 0.026504695745081887}. Best is trial 27 with value: 0.5439187436470179.
[I 2026-04-14 12:26:04,585] Trial 30 finished with value: 0.5406569388711636 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.2681018822742848, 'dropout0': 0.006615597002862631, 'dropout1': 0.0023907443361180225, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.000674734028534499, 'weight_decay': 3.07454797622336e-05, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 86, 'patience': 13, 'grad_clip': 2.0, 'label_smoothing': 0.018143875691528037}. Best is trial 27 with value: 0.5439187436470179.
[I 2026-04-14 12:26:08,574] Trial 31 pruned.
[I 2026-04-14 12:26:12,265] Trial 32 pruned.
[I 2026-04-14 12:26:14,515] Trial 33 pruned.
[I 2026-04-14 12:26:20,545] Trial 34 pruned.
[I 2026-04-14 12:26:24,793] Trial 35 pruned.
[I 2026-04-14 12:26:30,018] Trial 36 pruned.
[I 2026-04-14 12:26:31,840] Trial 37 pruned.
[I 2026-04-14 12:26:34,623] Trial 38 pruned.
[I 2026-04-14 12:26:38,614] Trial 39 pruned.
[I 2026-04-14 12:26:41,768] Trial 40 pruned.
[I 2026-04-14 12:26:44,108] Trial 41 pruned.
[I 2026-04-14 12:26:45,834] Trial 42 pruned.
[I 2026-04-14 12:26:52,429] Trial 43 pruned.
[I 2026-04-14 12:26:56,159] Trial 44 pruned.
[I 2026-04-14 12:26:58,512] Trial 45 pruned.
[I 2026-04-14 12:27:01,505] Trial 46 pruned.
[I 2026-04-14 12:27:05,280] Trial 47 pruned.
[I 2026-04-14 12:27:07,214] Trial 48 pruned.
[I 2026-04-14 12:27:16,064] Trial 49 finished with value: 0.5374527214872571 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.31128063505205744, 'dropout0': 0.08909493066405261, 'dropout1': 0.03103922499002717, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0003993490455431325, 'weight_decay': 1.062667991778013e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 88, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.007406742802735894}. Best is trial 27 with value: 0.5439187436470179.
[I 2026-04-14 12:27:19,114] Trial 50 pruned.
[I 2026-04-14 12:27:22,124] Trial 51 pruned.
[I 2026-04-14 12:27:23,866] Trial 52 pruned.
[I 2026-04-14 12:27:25,618] Trial 53 pruned.
[I 2026-04-14 12:27:29,390] Trial 54 pruned.
[I 2026-04-14 12:27:54,331] Trial 55 finished with value: 0.5499695119686513 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3653149423750684, 'dropout0': 0.07662718629961665, 'dropout1': 0.02770734554631178, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0002723724118845639, 'weight_decay': 2.6015143590732685e-05, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 93, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.010348097611933563}. Best is trial 55 with value: 0.5499695119686513.
[I 2026-04-14 12:28:23,187] Trial 56 finished with value: 0.552042758727469 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3816681271903596, 'dropout0': 0.08270644288021342, 'dropout1': 0.10855965875485746, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00023177287019496298, 'weight_decay': 4.729941085454895e-06, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 96, 'patience': 13, 'grad_clip': 5.0, 'label_smoothing': 0.014847827501661037}. Best is trial 56 with value: 0.552042758727469.
[I 2026-04-14 12:28:30,467] Trial 57 pruned.
[I 2026-04-14 12:28:54,123] Trial 58 finished with value: 0.5401606222440808 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.2594802521861075, 'dropout0': 0.08765579276216635, 'dropout1': 0.022087343811441992, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00012519697766839454, 'weight_decay': 4.585319100678812e-06, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 91, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.030127711402046772}. Best is trial 56 with value: 0.552042758727469.
[I 2026-04-14 12:28:58,339] Trial 59 pruned.
[stat] rows missing after index match -> train: 1004, test: 104
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 12:29:41,788] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__gpu_optuna__no_neutral

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__gpu_optuna__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 12:29:49,653] Trial 0 finished with value: 0.5003999949403979 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5003999949403979.
[I 2026-04-14 12:30:02,528] Trial 1 finished with value: 0.53461394361819 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.53461394361819.
[I 2026-04-14 12:30:15,267] Trial 2 finished with value: 0.5358480356718426 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 2 with value: 0.5358480356718426.
[I 2026-04-14 12:30:37,400] Trial 3 finished with value: 0.49454529449696927 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 2 with value: 0.5358480356718426.
[I 2026-04-14 12:30:50,191] Trial 4 finished with value: 0.5168752649469213 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 2 with value: 0.5358480356718426.
[I 2026-04-14 12:30:56,372] Trial 5 pruned.
[I 2026-04-14 12:31:02,529] Trial 6 pruned.
[I 2026-04-14 12:31:15,537] Trial 7 finished with value: 0.5372261558507756 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.38505936587117007, 'dropout0': 0.33439204820488233, 'dropout1': 0.2783896824374792, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.0010947002036624288, 'weight_decay': 3.5652340426862525e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 94, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.043385164923797306}. Best is trial 7 with value: 0.5372261558507756.
[I 2026-04-14 12:31:19,215] Trial 8 pruned.
[I 2026-04-14 12:31:24,408] Trial 9 pruned.
[I 2026-04-14 12:31:42,465] Trial 10 pruned.
[I 2026-04-14 12:31:50,344] Trial 11 finished with value: 0.526036620703856 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 1, 'context_dropout': 0.08353688147233676, 'dropout0': 0.14257865551713272, 'dropout1': 0.05038212544293829, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.004520045487971601, 'weight_decay': 9.94305117144006e-05, 'batch_size': 1024, 'eval_batch_size': 256, 'max_epochs': 83, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.008174218264394455}. Best is trial 7 with value: 0.5372261558507756.
[I 2026-04-14 12:31:52,863] Trial 12 pruned.
[I 2026-04-14 12:31:54,634] Trial 13 pruned.
[I 2026-04-14 12:31:58,008] Trial 14 pruned.
[I 2026-04-14 12:32:00,507] Trial 15 pruned.
[I 2026-04-14 12:32:13,381] Trial 16 pruned.
[I 2026-04-14 12:32:14,758] Trial 17 pruned.
[I 2026-04-14 12:32:17,143] Trial 18 pruned.
[I 2026-04-14 12:32:27,487] Trial 19 finished with value: 0.5307272015708484 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 2, 'context_dropout': 0.24038919830351838, 'dropout0': 0.3219316140719513, 'dropout1': 0.26592457911865564, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.0012274469001859177, 'weight_decay': 8.538364864095762e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 93, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.015594676816237593}. Best is trial 7 with value: 0.5372261558507756.
[I 2026-04-14 12:32:29,667] Trial 20 pruned.
[I 2026-04-14 12:32:31,674] Trial 21 pruned.
[I 2026-04-14 12:32:32,971] Trial 22 pruned.
[I 2026-04-14 12:32:38,391] Trial 23 pruned.
[I 2026-04-14 12:32:42,135] Trial 24 pruned.
[I 2026-04-14 12:32:45,052] Trial 25 pruned.
[I 2026-04-14 12:32:47,228] Trial 26 pruned.
[I 2026-04-14 12:32:50,643] Trial 27 pruned.
[I 2026-04-14 12:32:55,014] Trial 28 pruned.
[I 2026-04-14 12:33:06,418] Trial 29 finished with value: 0.52923980647276 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.03474143076261723, 'dropout0': 0.15044426769760422, 'dropout1': 0.009976867436491019, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.002619600405931293, 'weight_decay': 0.00012358820338622572, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 85, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.00029352607184595216}. Best is trial 7 with value: 0.5372261558507756.
[I 2026-04-14 12:33:13,251] Trial 30 pruned.
[I 2026-04-14 12:33:15,117] Trial 31 pruned.
[I 2026-04-14 12:33:16,850] Trial 32 pruned.
[I 2026-04-14 12:33:19,167] Trial 33 pruned.
[I 2026-04-14 12:33:21,650] Trial 34 pruned.
[I 2026-04-14 12:33:24,339] Trial 35 pruned.
[I 2026-04-14 12:33:26,606] Trial 36 pruned.
[I 2026-04-14 12:33:29,039] Trial 37 pruned.
[I 2026-04-14 12:33:31,591] Trial 38 pruned.
[I 2026-04-14 12:33:36,445] Trial 39 pruned.
[I 2026-04-14 12:33:39,908] Trial 40 pruned.
[I 2026-04-14 12:33:54,597] Trial 41 finished with value: 0.5355127953367146 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 2, 'context_dropout': 0.01286234786699415, 'dropout0': 0.11554852950068839, 'dropout1': 0.0065341350001482095, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.0018547942157707967, 'weight_decay': 2.954142555277617e-05, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 16, 'grad_clip': 5.0, 'label_smoothing': 0.029616215044848352}. Best is trial 7 with value: 0.5372261558507756.
[I 2026-04-14 12:33:57,276] Trial 42 pruned.
[I 2026-04-14 12:34:05,349] Trial 43 pruned.
[I 2026-04-14 12:34:21,028] Trial 44 finished with value: 0.5399521521391122 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.023120986397067333, 'dropout0': 0.10075393309499982, 'dropout1': 0.07150026323347007, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.0015596884553120013, 'weight_decay': 3.652223418406487e-05, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 85, 'patience': 18, 'grad_clip': 5.0, 'label_smoothing': 0.02059138427483856}. Best is trial 44 with value: 0.5399521521391122.
[I 2026-04-14 12:34:25,657] Trial 45 pruned.
[I 2026-04-14 12:34:28,902] Trial 46 pruned.
[I 2026-04-14 12:34:35,454] Trial 47 pruned.
[I 2026-04-14 12:34:52,442] Trial 48 finished with value: 0.5423826156905869 and parameters: {'d_main': 256, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.13731348725715378, 'dropout0': 0.010265492730967857, 'dropout1': 0.01318387467401152, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.002978573336396599, 'weight_decay': 0.0014653652870443854, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 88, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.007398083140762776}. Best is trial 48 with value: 0.5423826156905869.
[I 2026-04-14 12:34:53,852] Trial 49 pruned.
[I 2026-04-14 12:35:14,860] Trial 50 finished with value: 0.5393658350404069 and parameters: {'d_main': 256, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.14346955983662177, 'dropout0': 0.05625964426611166, 'dropout1': 0.024842698301446316, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0012677095176318021, 'weight_decay': 0.0019036965124644518, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 91, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.025587224970407416}. Best is trial 48 with value: 0.5423826156905869.
[I 2026-04-14 12:35:17,191] Trial 51 pruned.
[I 2026-04-14 12:35:20,444] Trial 52 pruned.
[I 2026-04-14 12:35:23,145] Trial 53 pruned.
[I 2026-04-14 12:35:27,693] Trial 54 pruned.
[I 2026-04-14 12:35:30,049] Trial 55 pruned.
[I 2026-04-14 12:35:47,312] Trial 56 finished with value: 0.5428920438574776 and parameters: {'d_main': 256, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.08471019430063595, 'dropout0': 0.01130237407600481, 'dropout1': 0.01349177583788922, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.003162043955328457, 'weight_decay': 0.0023560326997072844, 'batch_size': 256, 'eval_batch_size': 256, 'max_epochs': 92, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.015738247392450673}. Best is trial 56 with value: 0.5428920438574776.
[I 2026-04-14 12:35:49,041] Trial 57 pruned.
[I 2026-04-14 12:36:01,329] Trial 58 pruned.
[I 2026-04-14 12:36:06,428] Trial 59 pruned.
[stat] rows missing after index match -> train: 1193, test: 131
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 12:36:31,897] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__gpu_optuna

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__gpu_optuna
X_train: (4146, 570), X_test: (461, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 12:36:57,176] Trial 0 finished with value: 0.5348846668578878 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5348846668578878.
[I 2026-04-14 12:37:31,740] Trial 1 finished with value: 0.6390597217507338 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:37:49,673] Trial 2 finished with value: 0.5246916920908493 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:39:55,539] Trial 3 finished with value: 0.5328532498322653 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:40:47,134] Trial 4 finished with value: 0.5318069078951786 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:40:54,569] Trial 5 pruned.
[I 2026-04-14 12:41:03,441] Trial 6 pruned.
[I 2026-04-14 12:41:35,311] Trial 7 finished with value: 0.599028960828266 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.38505936587117007, 'dropout0': 0.33439204820488233, 'dropout1': 0.2783896824374792, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.0010947002036624288, 'weight_decay': 3.5652340426862525e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 94, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.043385164923797306}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:41:39,686] Trial 8 pruned.
[I 2026-04-14 12:42:31,226] Trial 9 finished with value: 0.5949761417765161 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.30181714963387296, 'dropout0': 0.04124954753437304, 'dropout1': 0.3610211626718267, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0009424401316515453, 'weight_decay': 0.00021734361959774786, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 12, 'grad_clip': 2.0, 'label_smoothing': 0.011706701642760588}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:43:16,554] Trial 10 finished with value: 0.5997939182443119 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:43:26,543] Trial 11 pruned.
[I 2026-04-14 12:44:01,826] Trial 12 finished with value: 0.598900832164604 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.32982709093296103, 'dropout0': 0.15146994791019802, 'dropout1': 0.14909628032060154, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.001857099958263517, 'weight_decay': 6.813822791771272e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 80, 'patience': 18, 'grad_clip': 5.0, 'label_smoothing': 0.03591914737041467}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:44:54,041] Trial 13 finished with value: 0.6085191624738182 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3625305346625074, 'dropout0': 0.062277910009708407, 'dropout1': 0.05604237941177269, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.0025423242554160046, 'weight_decay': 0.0005748051765001817, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 83, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.07558262094403141}. Best is trial 1 with value: 0.6390597217507338.
[I 2026-04-14 12:45:18,447] Trial 14 finished with value: 0.6440800491251644 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3692876122048844, 'dropout0': 0.017503033497055454, 'dropout1': 0.033486140231768484, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0006018311513653375, 'weight_decay': 0.0007979593277555309, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.03263886597609909}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:45:43,597] Trial 15 finished with value: 0.6341874911894403 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.2540134510894007, 'dropout0': 0.0012831688468082185, 'dropout1': 0.15042209267020942, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0004606369971383429, 'weight_decay': 0.00283094163847799, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 83, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.04314493680485144}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:46:01,003] Trial 16 finished with value: 0.6344449391739646 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.3662699122043567, 'dropout0': 0.022538550120305634, 'dropout1': 0.045845540903338, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00048533627153322836, 'weight_decay': 0.002008056400650994, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.02107292024295513}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:46:36,503] Trial 17 finished with value: 0.6439776648263913 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.37835801637182503, 'dropout0': 0.11746017808896286, 'dropout1': 0.2646778416012153, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0017783881394533038, 'weight_decay': 0.0014008860198168793, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 88, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.01545032640287066}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:47:14,187] Trial 18 finished with value: 0.6411677212099341 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.3866102326373226, 'dropout0': 0.005666265498221749, 'dropout1': 0.0492735348482903, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.00044276864528411034, 'weight_decay': 0.0005848023255279295, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 86, 'patience': 19, 'grad_clip': 1.0, 'label_smoothing': 0.01937605970160286}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:47:52,555] Trial 19 finished with value: 0.6360616972652171 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.23613567663942361, 'dropout0': 0.15628410838390214, 'dropout1': 0.2554422617401394, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0017568597323122791, 'weight_decay': 0.0011989901525415615, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 88, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.005084131074929967}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:48:10,796] Trial 20 finished with value: 0.6242067151242146 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3185649361703247, 'dropout0': 0.0019141882002802584, 'dropout1': 0.06063317622872014, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.0011253086296742474, 'weight_decay': 0.0024480209418812756, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.011130040641656819}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:48:48,798] Trial 21 finished with value: 0.5939716682321826 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.3413681138302798, 'dropout0': 0.04581731331744544, 'dropout1': 0.028994663509415212, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'radam', 'lr': 0.00048481575748581977, 'weight_decay': 0.00019515255253916232, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 20, 'grad_clip': 1.0, 'label_smoothing': 0.013374779759996569}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:49:54,580] Trial 22 finished with value: 0.6325611712858829 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.3012309798809157, 'dropout0': 0.010346900595828984, 'dropout1': 0.13313219227777418, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0007303961168950087, 'weight_decay': 0.0006507097087703449, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 89, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.009049603104040384}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:50:13,706] Trial 23 pruned.
[I 2026-04-14 12:51:11,709] Trial 24 finished with value: 0.6270621087007072 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.34220611236252757, 'dropout0': 0.050004143942380425, 'dropout1': 0.24426075322867466, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.0005968633031551139, 'weight_decay': 0.004326360724908762, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 89, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.013244464210515708}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:51:58,431] Trial 25 finished with value: 0.6379971782401626 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.356432265071238, 'dropout0': 0.11449569822549616, 'dropout1': 0.16875418424242922, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.00045922783022013904, 'weight_decay': 0.003415603640452831, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.013533011464168302}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:53:10,512] Trial 26 finished with value: 0.6247828050799784 and parameters: {'d_main': 384, 'd_mult': 4.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.34698838166733365, 'dropout0': 0.0448307154594904, 'dropout1': 0.0273912035299426, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adamw', 'lr': 0.00024380249956984856, 'weight_decay': 0.00020590308511420113, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.03237023045610317}. Best is trial 14 with value: 0.6440800491251644.
[I 2026-04-14 12:53:53,296] Trial 27 finished with value: 0.6515550508719516 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.3343398284724095, 'dropout0': 0.04958819582771401, 'dropout1': 0.016564907998360398, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.00045047571574380606, 'weight_decay': 0.00028712651108906746, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.006154631095449366}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 12:55:20,555] Trial 28 finished with value: 0.6476715755862463 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3020866152168824, 'dropout0': 0.09103262361831549, 'dropout1': 0.012012010514648987, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.000487114002903323, 'weight_decay': 0.0006747543349939183, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.03570720112468488}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 12:55:35,367] Trial 29 pruned.
[I 2026-04-14 12:56:46,106] Trial 30 finished with value: 0.6428121738545274 and parameters: {'d_main': 384, 'd_mult': 1.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.3414144177640893, 'dropout0': 0.044828774200898765, 'dropout1': 0.0555439437943227, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0006663252277879833, 'weight_decay': 3.3089575659184676e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 92, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.025207626824296905}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 12:59:10,885] Trial 31 finished with value: 0.6352368835323547 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.13607894429595135, 'dropout0': 0.11827451818962431, 'dropout1': 0.11782422093925862, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'radam', 'lr': 0.00019856485930885837, 'weight_decay': 0.0014427573876614431, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 83, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.02038952390254259}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 12:59:59,761] Trial 32 finished with value: 0.641598619429453 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 3, 'context_dropout': 0.30844061042993626, 'dropout0': 0.10248918570561831, 'dropout1': 0.02486271312034766, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0011310586602528972, 'weight_decay': 0.001221700403231996, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 85, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.011424990253632604}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 13:01:34,155] Trial 33 finished with value: 0.6495677342172056 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3264232035413479, 'dropout0': 0.09347517400847997, 'dropout1': 0.04732647967392134, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.00022192735361531167, 'weight_decay': 0.0008480729099451386, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.03610123826150455}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 13:02:40,296] Trial 34 finished with value: 0.6438656630183548 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.25610192312288593, 'dropout0': 0.041324800145887054, 'dropout1': 0.037378928332209224, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'adam', 'lr': 0.0001963008446037795, 'weight_decay': 0.001254011186649385, 'batch_size': 128, 'eval_batch_size': 2048, 'max_epochs': 85, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.033907705794203366}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 13:03:06,096] Trial 35 pruned.
[I 2026-04-14 13:03:29,040] Trial 36 finished with value: 0.6386665230608186 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3525946629710059, 'dropout0': 0.1180925219692333, 'dropout1': 0.06029313953066352, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0010951548047964162, 'weight_decay': 0.0008783149889367911, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': 5.0, 'label_smoothing': 0.0384563060168856}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 13:03:35,103] Trial 37 pruned.
[I 2026-04-14 13:04:17,257] Trial 38 finished with value: 0.630021575258906 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.395419929969496, 'dropout0': 0.04066179223106105, 'dropout1': 0.0777679781872155, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 64, 'optimizer': 'radam', 'lr': 0.0006811302233647937, 'weight_decay': 0.0028118503258176067, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.04735673132260103}. Best is trial 27 with value: 0.6515550508719516.
[I 2026-04-14 13:04:22,855] Trial 39 pruned.

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\optuna\_experimental.py:32: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2026-04-14 13:22:36,087] A new study created in memory with name: tabr__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__gpu_optuna__no_neutral

================================================================================
Running: tabr__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__gpu_optuna__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-04-14 13:22:43,582] Trial 0 finished with value: 0.5376339458329044 and parameters: {'d_main': 192, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.3329770563201687, 'dropout0': 0.08493564427131046, 'dropout1': 0.07272998688284026, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.00021839352923182988, 'weight_decay': 7.982478599323911e-05, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 86, 'patience': 12, 'grad_clip': None, 'label_smoothing': 0.0034388521115218396}. Best is trial 0 with value: 0.5376339458329044.
[I 2026-04-14 13:23:07,563] Trial 1 finished with value: 0.5863621482839685 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.36874969400924673, 'dropout0': 0.0353970008207678, 'dropout1': 0.07839314496765809, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0047499747713783975, 'weight_decay': 0.0007186380986530763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': None, 'label_smoothing': 0.03251833220267471}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:23:23,876] Trial 2 finished with value: 0.5543693838926741 and parameters: {'d_main': 256, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.010167650697638076, 'dropout0': 0.04315657079732178, 'dropout1': 0.012571674274693702, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.0037977679442478553, 'weight_decay': 0.0009754680378833336, 'batch_size': 256, 'eval_batch_size': 2048, 'max_epochs': 86, 'patience': 12, 'grad_clip': 5.0, 'label_smoothing': 0.0006952130531190704}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:23:52,214] Trial 3 finished with value: 0.5272509926310771 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10071291833014567, 'dropout0': 0.1988994023569542, 'dropout1': 0.12035132392670787, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.00025777728526856777, 'weight_decay': 0.00030634389416913234, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 97, 'patience': 14, 'grad_clip': 5.0, 'label_smoothing': 0.0016587828927856153}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:24:10,775] Trial 4 finished with value: 0.5434237503067766 and parameters: {'d_main': 512, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.10317665108606225, 'dropout0': 0.26399361841367164, 'dropout1': 0.32688888008048633, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.003214646526467847, 'weight_decay': 0.0007668956091724514, 'batch_size': 1024, 'eval_batch_size': 2048, 'max_epochs': 80, 'patience': 13, 'grad_clip': 1.0, 'label_smoothing': 0.07121792213475359}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:24:27,893] Trial 5 finished with value: 0.5499311327433243 and parameters: {'d_main': 512, 'd_mult': 1.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 4, 'context_dropout': 0.15723908986670418, 'dropout0': 0.35681862207084536, 'dropout1': 0.25245545039890516, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'radam', 'lr': 0.004175380307518435, 'weight_decay': 0.0024213408972073107, 'batch_size': 512, 'eval_batch_size': 256, 'max_epochs': 88, 'patience': 19, 'grad_clip': 5.0, 'label_smoothing': 0.0696029796674973}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:24:30,371] Trial 6 pruned.
[I 2026-04-14 13:24:46,457] Trial 7 finished with value: 0.5524831890561499 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 1, 'predictor_n_blocks': 1, 'context_dropout': 0.38505936587117007, 'dropout0': 0.33439204820488233, 'dropout1': 0.2783896824374792, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 32, 'optimizer': 'adamw', 'lr': 0.0010947002036624288, 'weight_decay': 3.5652340426862525e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 94, 'patience': 16, 'grad_clip': 1.0, 'label_smoothing': 0.043385164923797306}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:24:51,749] Trial 8 pruned.
[I 2026-04-14 13:25:22,014] Trial 9 finished with value: 0.5453271055208502 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.30181714963387296, 'dropout0': 0.04124954753437304, 'dropout1': 0.3610211626718267, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 48, 'optimizer': 'radam', 'lr': 0.0009424401316515453, 'weight_decay': 0.00021734361959774786, 'batch_size': 1024, 'eval_batch_size': 512, 'max_epochs': 90, 'patience': 12, 'grad_clip': 2.0, 'label_smoothing': 0.011706701642760588}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:26:04,002] Trial 10 finished with value: 0.5793186585034149 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3945561399164252, 'dropout0': 0.05974507849646786, 'dropout1': 0.12735560982974398, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adamw', 'lr': 0.00265790208485623, 'weight_decay': 0.00014708428299971567, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 81, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.05018794245675477}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:26:39,643] Trial 11 finished with value: 0.5716672148024841 and parameters: {'d_main': 512, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.39712509626059955, 'dropout0': 0.07904000679456186, 'dropout1': 0.1613812032159982, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 32, 'optimizer': 'adam', 'lr': 0.00424558651276101, 'weight_decay': 0.0022063664582440763, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.059342324127145206}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:27:14,293] Trial 12 finished with value: 0.5791703221986442 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 2, 'context_dropout': 0.32982709093296103, 'dropout0': 0.15146994791019802, 'dropout1': 0.14909628032060154, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 64, 'optimizer': 'adam', 'lr': 0.001857099958263517, 'weight_decay': 6.813822791771272e-05, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 80, 'patience': 18, 'grad_clip': 5.0, 'label_smoothing': 0.03591914737041467}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:27:56,697] Trial 13 finished with value: 0.5826043299426181 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3625305346625074, 'dropout0': 0.062277910009708407, 'dropout1': 0.05604237941177269, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adamw', 'lr': 0.0025423242554160046, 'weight_decay': 0.0005748051765001817, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 83, 'patience': 17, 'grad_clip': 5.0, 'label_smoothing': 0.07558262094403141}. Best is trial 1 with value: 0.5863621482839685.
[I 2026-04-14 13:28:17,467] Trial 14 finished with value: 0.5889586282539727 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3692876122048844, 'dropout0': 0.017503033497055454, 'dropout1': 0.033486140231768484, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0006018311513653375, 'weight_decay': 0.0007979593277555309, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.03263886597609909}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:28:20,415] Trial 15 pruned.
[I 2026-04-14 13:28:35,076] Trial 16 finished with value: 0.5838544929520444 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 2, 'context_dropout': 0.3662699122043567, 'dropout0': 0.022538550120305634, 'dropout1': 0.045845540903338, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00048533627153322836, 'weight_decay': 0.002008056400650994, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 87, 'patience': 18, 'grad_clip': None, 'label_smoothing': 0.02107292024295513}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:28:57,982] Trial 17 finished with value: 0.5743904017986228 and parameters: {'d_main': 128, 'd_mult': 2.5, 'encoder_n_blocks': 3, 'predictor_n_blocks': 3, 'context_dropout': 0.37835801637182503, 'dropout0': 0.11746017808896286, 'dropout1': 0.2646778416012153, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0017783881394533038, 'weight_decay': 0.0014008860198168793, 'batch_size': 256, 'eval_batch_size': 512, 'max_epochs': 88, 'patience': 17, 'grad_clip': 1.0, 'label_smoothing': 0.01545032640287066}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:29:13,637] Trial 18 pruned.
[I 2026-04-14 13:29:31,110] Trial 19 finished with value: 0.5785144062915248 and parameters: {'d_main': 192, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.230199192265655, 'dropout0': 0.09306785467452798, 'dropout1': 0.0824952609059984, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 8, 'optimizer': 'adam', 'lr': 0.0007398187470050346, 'weight_decay': 0.0009044044413254291, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.010056192711965003}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:29:35,432] Trial 20 pruned.
[I 2026-04-14 13:29:51,309] Trial 21 finished with value: 0.5783859246384816 and parameters: {'d_main': 128, 'd_mult': 2.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3810685010999049, 'dropout0': 0.016100061479607953, 'dropout1': 0.021332865882294785, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00038539973892056935, 'weight_decay': 0.0005484381111764465, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 88, 'patience': 17, 'grad_clip': 2.0, 'label_smoothing': 0.009646367891817248}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:29:59,075] Trial 22 pruned.
[I 2026-04-14 13:30:34,804] Trial 23 finished with value: 0.5888167427391682 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.29028992283801536, 'dropout0': 0.10978886798233216, 'dropout1': 0.06792363007968072, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0010516350262762871, 'weight_decay': 0.004101095002945568, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 83, 'patience': 16, 'grad_clip': 2.0, 'label_smoothing': 0.05289138049093094}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:30:40,475] Trial 24 pruned.
[I 2026-04-14 13:30:52,353] Trial 25 finished with value: 0.5809282662260526 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.36500698882876603, 'dropout0': 0.0870178703188971, 'dropout1': 0.057338639374917524, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.00473522516977528, 'weight_decay': 0.004314130864679661, 'batch_size': 1024, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.03267459318715371}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:31:17,445] Trial 26 finished with value: 0.5872608718518769 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.36391301727569664, 'dropout0': 0.029899602023960817, 'dropout1': 0.07472489732054258, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0003724540700831256, 'weight_decay': 6.268797986900544e-05, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 85, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.030968636388411748}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:31:33,165] Trial 27 pruned.
[I 2026-04-14 13:32:02,971] Trial 28 finished with value: 0.5776392695526167 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.1960381053724285, 'dropout0': 0.04027720971744295, 'dropout1': 0.07872879151446645, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adam', 'lr': 0.000844559087811882, 'weight_decay': 0.0033377819567142132, 'batch_size': 128, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 16, 'grad_clip': 2.0, 'label_smoothing': 0.05039730664369405}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:32:26,409] Trial 29 finished with value: 0.5819304147956245 and parameters: {'d_main': 384, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.39170565417722086, 'dropout0': 0.12758319581754368, 'dropout1': 0.20109480749862, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.0005305959166850988, 'weight_decay': 5.687151261990171e-05, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 83, 'patience': 19, 'grad_clip': 2.0, 'label_smoothing': 0.03319199895824154}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:32:42,080] Trial 30 pruned.
[I 2026-04-14 13:32:58,535] Trial 31 pruned.
[I 2026-04-14 13:33:34,079] Trial 32 finished with value: 0.5762601975900828 and parameters: {'d_main': 384, 'd_mult': 2.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.27149479432780355, 'dropout0': 0.2637119524288226, 'dropout1': 0.03670187960965403, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0011172701433606316, 'weight_decay': 0.004351201118817883, 'batch_size': 128, 'eval_batch_size': 256, 'max_epochs': 87, 'patience': 15, 'grad_clip': 2.0, 'label_smoothing': 0.04643894806753001}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:33:36,933] Trial 33 pruned.
[I 2026-04-14 13:33:55,124] Trial 34 finished with value: 0.5841288425577555 and parameters: {'d_main': 128, 'd_mult': 1.5, 'encoder_n_blocks': 4, 'predictor_n_blocks': 3, 'context_dropout': 0.3875453062599024, 'dropout0': 0.15372984922574612, 'dropout1': 0.08276005077213962, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0018861895742928615, 'weight_decay': 0.0011258569980764055, 'batch_size': 512, 'eval_batch_size': 512, 'max_epochs': 82, 'patience': 20, 'grad_clip': None, 'label_smoothing': 0.03828596013640896}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:34:10,123] Trial 35 finished with value: 0.5869630397524384 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3882977715405736, 'dropout0': 0.07257984743022117, 'dropout1': 0.028695889260962937, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.001319307328388387, 'weight_decay': 0.0019501029169969213, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 18, 'grad_clip': 2.0, 'label_smoothing': 0.04563075867567185}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:34:30,545] Trial 36 finished with value: 0.5856974523885545 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 2, 'predictor_n_blocks': 4, 'context_dropout': 0.38676290940933783, 'dropout0': 0.11552798211507061, 'dropout1': 0.18810967855705873, 'normalization': 'LayerNorm', 'activation': 'ReLU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0011679411518632549, 'weight_decay': 0.0008284910040324547, 'batch_size': 512, 'eval_batch_size': 1024, 'max_epochs': 82, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.06757028020305594}. Best is trial 14 with value: 0.5889586282539727.
[I 2026-04-14 13:35:26,689] Trial 37 finished with value: 0.5892823843176902 and parameters: {'d_main': 128, 'd_mult': 4.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.2811164510694798, 'dropout0': 0.13344754484768673, 'dropout1': 0.09367259028982698, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adamw', 'lr': 0.00035802668356517815, 'weight_decay': 0.0021647099195593322, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 86, 'patience': 17, 'grad_clip': 2.0, 'label_smoothing': 0.034722640330851234}. Best is trial 37 with value: 0.5892823843176902.
[I 2026-04-14 13:35:38,452] Trial 38 pruned.
[I 2026-04-14 13:35:40,907] Trial 39 pruned.
[I 2026-04-14 13:35:50,981] Trial 40 pruned.
[I 2026-04-14 13:35:55,100] Trial 41 pruned.
[I 2026-04-14 13:36:13,119] Trial 42 pruned.
[I 2026-04-14 13:36:41,966] Trial 43 finished with value: 0.5802021617272366 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.26142334132599326, 'dropout0': 0.13877057091246897, 'dropout1': 0.010997358214163762, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 16, 'optimizer': 'adamw', 'lr': 0.002734378283806314, 'weight_decay': 0.0015851656435722685, 'batch_size': 128, 'eval_batch_size': 512, 'max_epochs': 84, 'patience': 16, 'grad_clip': 2.0, 'label_smoothing': 0.03640372769349435}. Best is trial 37 with value: 0.5892823843176902.
[I 2026-04-14 13:36:59,826] Trial 44 finished with value: 0.5853761980179846 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 3, 'predictor_n_blocks': 4, 'context_dropout': 0.3323736122173814, 'dropout0': 0.08352414585160686, 'dropout1': 0.06938761593938136, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.00146495565244422, 'weight_decay': 0.0007339103170201847, 'batch_size': 256, 'eval_batch_size': 1024, 'max_epochs': 84, 'patience': 18, 'grad_clip': 1.0, 'label_smoothing': 0.05612216311017004}. Best is trial 37 with value: 0.5892823843176902.
[I 2026-04-14 13:37:09,062] Trial 45 pruned.
[I 2026-04-14 13:37:15,168] Trial 46 pruned.
[I 2026-04-14 13:37:16,961] Trial 47 pruned.
[I 2026-04-14 13:37:31,516] Trial 48 finished with value: 0.5854468912097122 and parameters: {'d_main': 128, 'd_mult': 3.0, 'encoder_n_blocks': 4, 'predictor_n_blocks': 4, 'context_dropout': 0.3213903614570043, 'dropout0': 0.0031360202605568693, 'dropout1': 0.042215192064904886, 'normalization': 'LayerNorm', 'activation': 'GELU', 'k_neighbors': 24, 'optimizer': 'adam', 'lr': 0.0009059048997507671, 'weight_decay': 0.00043653053975074494, 'batch_size': 512, 'eval_batch_size': 2048, 'max_epochs': 81, 'patience': 20, 'grad_clip': 2.0, 'label_smoothing': 0.026634193810436073}. Best is trial 37 with value: 0.5892823843176902.
[I 2026-04-14 13:37:38,996] Trial 49 pruned.

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,stat,match_mismatch,binary,False,0.427984,0.529284,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,binary,True,0.435704,0.476190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch,multiclass,False,0.580387,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch,multiclass,True,0.452381,0.452381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,stat,match_mismatch_general,binary,False,0.575839,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,stat,match_mismatch_general,binary,True,0.510204,0.595238,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,stat,match_mismatch_general,multiclass,False,0.662470,0.659436,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,stat,match_mismatch_general,multiclass,True,0.642384,0.645833,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,stat,match_mismatch,binary,False,0.427984,0.529284,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,binary,True,0.435704,0.476190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch,multiclass,False,0.580387,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch,multiclass,True,0.452381,0.452381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,stat,match_mismatch_general,binary,False,0.575839,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,stat,match_mismatch_general,binary,True,0.510204,0.595238,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,stat,match_mismatch_general,multiclass,False,0.662470,0.659436,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,stat,match_mismatch_general,multiclass,True,0.642384,0.645833,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [16]:

all_summaries = [
    summary_corr,
    summary_cov_freq,
    summary_envelope,
    summary_freq_bands,
    summary_PID,
    summary_stat,
]
all_results = pd.concat(all_summaries, ignore_index=True)
all_results

,text_set,target,split,no_neutral,tabr_test_macro_f1,tabr_test_accuracy,file
0,corr,match_mismatch,binary,False,0.508172,0.550976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.425768,0.538690,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.567961,0.555315,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,0.544316,0.544643,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.506735,0.577007,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.477679,0.535714,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.649632,0.650759,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,0.582120,0.589286,C:\Users\LEGION\Projects\CB_exepriment\dataset...
8,cov_freq,match_mismatch,binary,False,0.492957,0.548807,C:\Users\LEGION\Projects\CB_exepriment\dataset...
9,cov_freq,match_mismatch,binary,True,0.468639,0.577381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
10,cov_freq,match_mismatch,multiclass,False,0.552524,0.535792,C:\Users\LEGION\Projects\CB_exepriment\dataset...
11,cov_freq,match_mismatch,multiclass,True,0.498864,0.500000,C:\Users\LEGION\Projects\CB_exepriment\dataset...
12,cov_freq,match_mismatch_general,binary,False,0.557298,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
13,cov_freq,match_mismatch_general,binary,True,0.559892,0.654762,C:\Users\LEGION\Projects\CB_exepriment\dataset...
14,cov_freq,match_mismatch_general,multiclass,False,0.621884,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
15,cov_freq,match_mismatch_general,multiclass,True,0.520323,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...
16,envelope,match_mismatch,binary,False,0.499941,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
17,envelope,match_mismatch,binary,True,0.403539,0.520833,C:\Users\LEGION\Projects\CB_exepriment\dataset...
18,envelope,match_mismatch,multiclass,False,0.535088,0.524946,C:\Users\LEGION\Projects\CB_exepriment\dataset...
19,envelope,match_mismatch,multiclass,True,0.502972,0.502976,C:\Users\LEGION\Projects\CB_exepriment\dataset...
20,envelope,match_mismatch_general,binary,False,0.552176,0.609544,C:\Users\LEGION\Projects\CB_exepriment\dataset...
21,envelope,match_mismatch_general,binary,True,0.538310,0.601190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
22,envelope,match_mismatch_general,multiclass,False,0.587256,0.583514,C:\Users\LEGION\Projects\CB_exepriment\dataset...
23,envelope,match_mismatch_general,multiclass,True,0.603547,0.607143,C:\Users\LEGION\Projects\CB_exepriment\dataset...
24,freq_bands,match_mismatch,binary,False,0.444435,0.503254,C:\Users\LEGION\Projects\CB_exepriment\dataset...
25,freq_bands,match_mismatch,binary,True,0.485601,0.592262,C:\Users\LEGION\Projects\CB_exepriment\dataset...
26,freq_bands,match_mismatch,multiclass,False,0.555486,0.537961,C:\Users\LEGION\Projects\CB_exepriment\dataset...
27,freq_bands,match_mismatch,multiclass,True,0.494224,0.497024,C:\Users\LEGION\Projects\CB_exepriment\dataset...
28,freq_bands,match_mismatch_general,binary,False,0.527205,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
29,freq_bands,match_mismatch_general,binary,True,0.547881,0.642857,C:\Users\LEGION\Projects\CB_exepriment\dataset...
30,freq_bands,match_mismatch_general,multiclass,False,0.693793,0.687636,C:\Users\LEGION\Projects\CB_exepriment\dataset...
31,freq_bands,match_mismatch_general,multiclass,True,0.663218,0.666667,C:\Users\LEGION\Projects\CB_exepriment\dataset...
32,PID,match_mismatch,binary,False,0.509131,0.570499,C:\Users\LEGION\Projects\CB_exepriment\dataset...
33,PID,match_mismatch,binary,True,0.412698,0.559524,C:\Users\LEGION\Projects\CB_exepriment\dataset...
34,PID,match_mismatch,multiclass,False,0.591670,0.585683,C:\Users\LEGION\Projects\CB_exepriment\dataset...
35,PID,match_mismatch,multiclass,True,0.526278,0.526786,C:\Users\LEGION\Projects\CB_exepriment\dataset...
36,PID,match_mismatch_general,binary,False,0.512506,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
37,PID,match_mismatch_general,binary,True,0.479882,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...
38,PID,match_mismatch_general,multiclass,False,0.581319,0.581345,C:\Users\LEGION\Projects\CB_exepriment\dataset...
39,PID,match_mismatch_general,multiclass,True,0.554460,0.556548,C:\Users\LEGION\Projects\CB_exepriment\dataset...
40,stat,match_mismatch,binary,False,0.427984,0.529284,C:\Users\LEGION\Projects\CB_exepriment\dataset...
41,stat,match_mismatch,binary,True,0.435704,0.476190,C:\Users\LEGION\Projects\CB_exepriment\dataset...
42,stat,match_mismatch,multiclass,False,0.580387,0.568330,C:\Users\LEGION\Projects\CB_exepriment\dataset...
43,stat,match_mismatch,multiclass,True,0.452381,0.452381,C:\Users\LEGION\Projects\CB_exepriment\dataset...
44,stat,match_mismatch_general,binary,False,0.575839,0.622560,C:\Users\LEGION\Projects\CB_exepriment\dataset...
45,stat,match_mismatch_general,binary,True,0.510204,0.595238,C:\Users\LEGION\Projects\CB_exepriment\dataset...
46,stat,match_mismatch_general,multiclass,False,0.662470,0.659436,C:\Users\LEGION\Projects\CB_exepriment\dataset...
47,stat,match_mismatch_general,multiclass,True,0.642384,0.645833,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [17]:

summary_path = OUT_DIR / "summary_eye_text2text_tabr.csv"
all_results.to_csv(summary_path, index=False)
print("Saved summary:", summary_path)

all_results.groupby(["text_set", "target", "split"], as_index=False)[["tabr_test_macro_f1", "tabr_test_accuracy"]].mean()

Saved summary: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_text2text_tabr\summary_eye_text2text_tabr.csv

,text_set,target,split,tabr_test_macro_f1,tabr_test_accuracy
0,PID,match_mismatch,binary,0.460915,0.565011
1,PID,match_mismatch,multiclass,0.558974,0.556235
2,PID,match_mismatch_general,binary,0.496194,0.562439
3,PID,match_mismatch_general,multiclass,0.567889,0.568946
4,corr,match_mismatch,binary,0.466970,0.544833
5,corr,match_mismatch,multiclass,0.556139,0.549979
6,corr,match_mismatch_general,binary,0.492207,0.556360
7,corr,match_mismatch_general,multiclass,0.615876,0.620022
8,cov_freq,match_mismatch,binary,0.480798,0.563094
9,cov_freq,match_mismatch,multiclass,0.525694,0.517896
10,cov_freq,match_mismatch_general,binary,0.558595,0.638661
11,cov_freq,match_mismatch_general,multiclass,0.571104,0.574673
12,envelope,match_mismatch,binary,0.451740,0.551089
13,envelope,match_mismatch,multiclass,0.519030,0.513961
14,envelope,match_mismatch_general,binary,0.545243,0.605367
15,envelope,match_mismatch_general,multiclass,0.595401,0.595328
16,freq_bands,match_mismatch,binary,0.465018,0.547758
17,freq_bands,match_mismatch,multiclass,0.524855,0.517492
18,freq_bands,match_mismatch_general,binary,0.537543,0.612101
19,freq_bands,match_mismatch_general,multiclass,0.678506,0.677151
20,stat,match_mismatch,binary,0.431844,0.502737
21,stat,match_mismatch,multiclass,0.516384,0.510355
22,stat,match_mismatch_general,binary,0.543021,0.608899
23,stat,match_mismatch_general,multiclass,0.652427,0.652635