# Eye tracking + FTAR features experiments

This notebook mirrors the text2text experiment workflow, but uses FTAR feature sets from:
`C:\Users\LEGION\Projects\CB_exepriment\ftar_features`

Targets/splits covered:
- `match_mismatch`: binary + multiclass
- `match_mismatch_general`: binary + multiclass

In [1]:
from __future__ import annotations

import os
import json
from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd
from umap import UMAP

from experiment_code.read_data import get_data_for_split
from experiment_code.run_experiments import _build_groups_mm_for_mm
from experiment_code.optuna_code import run_and_log, fit_best_and_test

ROOT = Path(r"C:\Users\LEGION\data\СB")
os.chdir(ROOT)
print("cwd:", Path.cwd())

cwd: C:\Users\LEGION\data\СB

In [2]:
TARGETS = ["match_mismatch", "match_mismatch_general"]
SPLITS = ["binary", "multiclass"]

USE_EARLY_STOPPING = True
REFIT_CV = False
REFIT_TEST = True
USE_MIN = False

CV = 4
N_TRIALS_XGB = 100
N_TRIALS_CB = 50

PROJECT_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\dataset_v2")
OUT_DIR = PROJECT_DIR / "optuna_results_eye_ftar"
OUT_DIR.mkdir(parents=True, exist_ok=True)

FI_DIR = OUT_DIR / "feature_importances_eye_ftar"
FI_DIR.mkdir(parents=True, exist_ok=True)
REFIT_TOP_N = 30

UMAP_TARGET_SETS = {"freq_bands", "stat", "corr", "cov_freq"}
UMAP_N_COMPONENTS = 100
UMAP_N_NEIGHBORS = 30
UMAP_MIN_DIST = 0.0
UMAP_METRIC = "cosine"
UMAP_RANDOM_STATE = 1717

CLEAN_TRAIN_COLUMNS = False

In [3]:
def _prefix_cols(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    return df.add_prefix(prefix)


def _load_ftar_parquet(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    if "pid_rn" not in df.columns:
        raise KeyError(f"'pid_rn' column not found in {path}")
    df = df.set_index("pid_rn")
    df.index = df.index.astype(str)
    return df


def _apply_umap_train_test(
    text_train: pd.DataFrame,
    text_test: pd.DataFrame,
    *,
    text_set_name: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    tr = text_train.apply(pd.to_numeric, errors="coerce")
    te = text_test.apply(pd.to_numeric, errors="coerce")

    train_means = tr.mean(numeric_only=True)
    tr = tr.fillna(train_means).fillna(0.0)
    te = te.fillna(train_means).fillna(0.0)

    n_components = int(min(UMAP_N_COMPONENTS, max(2, tr.shape[1])))
    reducer = UMAP(
        n_components=n_components,
        n_neighbors=UMAP_N_NEIGHBORS,
        min_dist=UMAP_MIN_DIST,
        metric=UMAP_METRIC,
        random_state=UMAP_RANDOM_STATE,
    )

    print(
        f"[{text_set_name}] UMAP compression: "
        f"train/test features {tr.shape[1]} -> {n_components}"
    )

    z_train = reducer.fit_transform(tr)
    z_test = reducer.transform(te)

    cols = [f"{text_set_name}__umap_{i:03d}" for i in range(n_components)]
    tr_umap = pd.DataFrame(z_train, index=text_train.index, columns=cols)
    te_umap = pd.DataFrame(z_test, index=text_test.index, columns=cols)
    return tr_umap, te_umap


def _prepare_joined_X(
    eye_train: pd.DataFrame,
    eye_test: pd.DataFrame,
    text_all: pd.DataFrame,
    text_set_name: str,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    text_train = text_all.reindex(eye_train.index)
    text_test = text_all.reindex(eye_test.index)

    missing_train = int(text_train.isna().all(axis=1).sum())
    missing_test = int(text_test.isna().all(axis=1).sum())
    print(f"[{text_set_name}] rows missing after index match -> train: {missing_train}, test: {missing_test}")

    if text_set_name in UMAP_TARGET_SETS:
        text_train_model, text_test_model = _apply_umap_train_test(
            text_train,
            text_test,
            text_set_name=text_set_name,
        )
    else:
        text_train_model = _prefix_cols(text_train, f"{text_set_name}__")
        text_test_model = _prefix_cols(text_test, f"{text_set_name}__")

    X_train = pd.concat([
        _prefix_cols(eye_train, "eye__"),
        text_train_model,
    ], axis=1)
    X_test = pd.concat([
        _prefix_cols(eye_test, "eye__"),
        text_test_model,
    ], axis=1)

    if CLEAN_TRAIN_COLUMNS:
        keep_cols = X_train.columns[X_train.notna().all(axis=0)]
        X_train = X_train[keep_cols]
        X_test = X_test.reindex(columns=keep_cols)

    return X_train, X_test


def _build_no_neutral_mask(stim_df: pd.DataFrame, target: str, split: str) -> pd.Series:
    mask = pd.Series(True, index=stim_df.index)

    if "valence" in stim_df.columns:
        valence = pd.to_numeric(stim_df["valence"], errors="coerce")
        mask &= valence != 2

    if split == "binary":
        if target == "match_mismatch_general" and "exp_general_multi" in stim_df.columns:
            exp_general_multi = pd.to_numeric(stim_df["exp_general_multi"], errors="coerce")
            mask &= exp_general_multi != 2
        elif "IAT_results2" in stim_df.columns:
            iat = stim_df["IAT_results2"].astype(str).str.strip().str.lower()
            mask &= iat != "neutral"

    return mask.fillna(False)


def _load_eye_for_task(target: str, split: str, no_neutral: bool = False):
    df, tgt, _ = get_data_for_split(X_name="screen", target=target, split=split)

    eye_train = df["all_features"]["X_train"].copy()
    eye_test = df["all_features"]["X_test"].copy()
    stim_train = df["stimuli_features"]["X_train"].copy()
    stim_test = df["stimuli_features"]["X_test"].copy()

    y_train = tgt["cb"]["y_train"].copy()
    y_test = tgt["cb"]["y_test"].copy()

    if no_neutral:
        mask_train = _build_no_neutral_mask(stim_train, target=target, split=split)
        mask_test = _build_no_neutral_mask(stim_test, target=target, split=split)

        eye_train = eye_train.loc[mask_train]
        eye_test = eye_test.loc[mask_test]
        y_train = y_train.loc[mask_train]
        y_test = y_test.loc[mask_test]
        stim_train = stim_train.loc[mask_train]

    groups = np.array([str(i).split("_")[0] for i in eye_train.index])

    if target in ("match_mismatch", "match_mismatch_general"):
        groups_mm = _build_groups_mm_for_mm(X_train_index=eye_train.index, stim_train_df=stim_train)
    else:
        groups_mm = None

    problem = "binary" if split == "binary" else "multiclass"
    return eye_train, eye_test, y_train, y_test, groups, groups_mm, problem


def run_ftar_set(
    text_set_name: str,
    text_all: pd.DataFrame,
    *,
    do_refit: bool = True,
    top_n_features: int = REFIT_TOP_N,
):
    if "pid_rn" in text_all.columns:
        text_all = text_all.set_index("pid_rn")
    text_all = text_all.copy()
    text_all.index = text_all.index.astype(str)

    if "key" in text_all.columns:
        text_all = text_all.drop(columns=["key"])

    print(f"[{text_set_name}] ftar feature count after cleanup: {int(text_all.shape[1])}")

    rows = []

    for target in TARGETS:
        for split in SPLITS:
            for no_neutral in [False, True]:
                problem = "binary" if split == "binary" else "multiclass"
                neutral_suffix = "__no_neutral" if no_neutral else ""
                train_features_name = (
                    f"exp__X_name=screen+{text_set_name}"
                    f"__target={target}"
                    f"__problem={problem}"
                    f"__feat=all_features+{text_set_name}"
                    f"__ES__refitTEST"
                    f"{neutral_suffix}"
                )
                out_path = OUT_DIR / f"{train_features_name}.json"

                if out_path.exists():
                    print("\n" + "=" * 80)
                    print(f"Skipping existing experiment: {train_features_name}")
                    with open(out_path, encoding="utf-8") as f:
                        results = json.load(f)
                    rows.append({
                        "set": text_set_name,
                        "target": target,
                        "split": split,
                        "no_neutral": no_neutral,
                        "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                        "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                        "file": str(out_path),
                    })
                    continue

                eye_train, eye_test, y_train, y_test, groups, groups_mm, problem = _load_eye_for_task(
                    target,
                    split,
                    no_neutral=no_neutral,
                )
                X_train, X_test = _prepare_joined_X(eye_train, eye_test, text_all, text_set_name)

                print("\n" + "=" * 80)
                print(f"Running: {train_features_name}")
                print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

                results = run_and_log(
                    train_features=train_features_name,
                    problem=problem,
                    X_train=X_train,
                    X_test=X_test,
                    y_train=y_train,
                    y_test=y_test,
                    strat_train=y_train,
                    groups=groups,
                    groups_mm=groups_mm,
                    use_early_stopping=USE_EARLY_STOPPING,
                    refit_cv=REFIT_CV,
                    refit_test=REFIT_TEST,
                    n_trials_xgb=N_TRIALS_XGB,
                    n_trials_cb=N_TRIALS_CB,
                    cv=CV,
                    gpu=False,
                    use_min=USE_MIN,
                    cat_cols=None,
                    target_names=None,
                    out_path=out_path,
                )

                if do_refit:
                    print("\n" + "-" * 80)
                    print("Refit best iteration + metrics + top features")
                    for model_name in ["xgb", "catboost"]:
                        best_params = results[model_name].get("suggested_params", {})
                        if not best_params:
                            print(f"\n=== Skip refit {model_name.upper()} (no suggested params) ===")
                            continue

                        print(f"\n=== Refit {model_name.upper()} with saved best params ===")
                        out_refit = fit_best_and_test(
                            model_name=model_name,
                            best_params=best_params,
                            problem=problem,
                            X_train=X_train,
                            X_test=X_test,
                            y_train=y_train,
                            y_test=y_test,
                            strat_train=y_train,
                            groups=groups,
                            groups_mm=groups_mm,
                            use_early_stopping=True,
                            early_stopping_rounds=100,
                            target_names=None,
                            cat_cols=None,
                            gpu=False,
                            refit_test=True,
                        )

                        model = out_refit["model"]
                        if model_name == "xgb":
                            importances = model.feature_importances_
                        else:
                            importances = model.get_feature_importance()

                        fi = pd.DataFrame({
                            "feature": X_train.columns,
                            "importance": importances,
                        }).sort_values("importance", ascending=False)

                        fi_path = FI_DIR / f"{train_features_name}__{model_name}.csv"
                        fi.to_csv(fi_path, index=False)
                        print(f"Saved feature importances: {fi_path}")
                        print(f"Top {top_n_features} features for {model_name.upper()}:")
                        display(fi.head(top_n_features))

                rows.append({
                    "set": text_set_name,
                    "target": target,
                    "split": split,
                    "no_neutral": no_neutral,
                    "xgb_test": float(results["xgb"]["test_metrics"]["primary"]),
                    "catboost_test": float(results["catboost"]["test_metrics"]["primary"]),
                    "file": str(out_path),
                })

    summary = pd.DataFrame(rows)
    display(summary)
    return summary

In [4]:
FTAR_DIR = Path(r"C:\Users\LEGION\Projects\CB_exepriment\ftar_features")
FTAR_FILES = {
    "corr": FTAR_DIR / "corr.parquet",
    "cov_freq": FTAR_DIR / "cov_freq.parquet",
    "envelope": FTAR_DIR / "envelope.parquet",
    "freq_bands": FTAR_DIR / "freq_bands.parquet",
    "PID": FTAR_DIR / "PID.parquet",
    "stat": FTAR_DIR / "stat.parquet",
}

print("ftar dir:", FTAR_DIR)
for k, p in FTAR_FILES.items():
    print(f"{k:10s} -> {p} | exists={p.exists()}")

ftar dir: C:\Users\LEGION\Projects\CB_exepriment\ftar_features
corr       -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\corr.parquet | exists=True
cov_freq   -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\cov_freq.parquet | exists=True
envelope   -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\envelope.parquet | exists=True
freq_bands -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\freq_bands.parquet | exists=True
PID        -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\PID.parquet | exists=True
stat       -> C:\Users\LEGION\Projects\CB_exepriment\ftar_features\stat.parquet | exists=True

In [5]:
text_corr = _load_ftar_parquet(FTAR_FILES["corr"])
print("corr shape:", text_corr.shape)
summary_corr = run_ftar_set("corr", text_corr)
summary_corr

corr shape: (4442, 1831)
[corr] ftar feature count after cleanup: 1830

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__ES__refitTEST
[corr] rows missing after index match -> train: 1658, test: 160
[corr] UMAP compression: train/test features 1830 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 09:25:58,718] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 09:26:03,076] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:08,305] Trial 1 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:13,082] Trial 2 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:17,777] Trial 3 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:22,271] Trial 4 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:26,890] Trial 5 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:30,835] Trial 6 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:35,884] Trial 7 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:40,379] Trial 8 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:45,890] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:50,147] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:54,559] Trial 11 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1987511993802379, 'max_depth': 8, 'min_child_weight': 2.2044350854903803, 'subsample': 0.991678377353391, 'colsample_bytree': 0.701477667194265, 'gamma': 0.11220060164975498, 'reg_alpha': 9.196828714331065, 'reg_lambda': 0.00013386192543122697}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:26:59,046] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12491658728825787, 'max_depth': 3, 'min_child_weight': 3.253041711071422, 'subsample': 0.9269639649687119, 'colsample_bytree': 0.7934706144492909, 'gamma': 0.019495941942304973, 'reg_alpha': 0.0005436011712873391, 'reg_lambda': 4.172125626964391}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:03,646] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 4, 'min_child_weight': 1.9159793446750535, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.7013693620912469, 'gamma': 0.48600046581571593, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.00011913812992647485}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:11,706] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.040383658844458395, 'max_depth': 8, 'min_child_weight': 1.1157937296124318, 'subsample': 0.7004519003043, 'colsample_bytree': 0.7732828130312976, 'gamma': 0.29464130180941833, 'reg_alpha': 3.421125808225141, 'reg_lambda': 0.006106037730048314}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:16,621] Trial 15 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02128929082732021, 'max_depth': 4, 'min_child_weight': 4.195345625812058, 'subsample': 0.8475571599493473, 'colsample_bytree': 0.844821976965745, 'gamma': 0.7437277813718939, 'reg_alpha': 0.001357616284331662, 'reg_lambda': 0.8741655275059462}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:21,159] Trial 16 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.15108043676026062, 'max_depth': 7, 'min_child_weight': 2.635939156801854, 'subsample': 0.9341462060236994, 'colsample_bytree': 0.7441347259985547, 'gamma': 1.464764475541173, 'reg_alpha': 0.0001690557851152469, 'reg_lambda': 0.0005807427487454919}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:25,186] Trial 17 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0762942305162252, 'max_depth': 4, 'min_child_weight': 4.907699675577318, 'subsample': 0.8181815313452178, 'colsample_bytree': 0.8185597495393847, 'gamma': 0.280536267454658, 'reg_alpha': 0.9024303033822801, 'reg_lambda': 0.018867535841271068}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:31,587] Trial 18 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02775934184434466, 'max_depth': 7, 'min_child_weight': 1.6209726919199594, 'subsample': 0.9566861349051418, 'colsample_bytree': 0.8781514030059229, 'gamma': 1.2460001337349627, 'reg_alpha': 0.005301455447830579, 'reg_lambda': 1.9253855625275396}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:35,430] Trial 19 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.053435117310511156, 'max_depth': 4, 'min_child_weight': 1.0409840411779645, 'subsample': 0.8767777458793767, 'colsample_bytree': 0.7321641349085308, 'gamma': 0.6349333920358116, 'reg_alpha': 0.051727758673718365, 'reg_lambda': 0.2028286802625633}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:40,310] Trial 20 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09641570779344828, 'max_depth': 8, 'min_child_weight': 6.230828787225904, 'subsample': 0.9082899246525548, 'colsample_bytree': 0.7769763586761955, 'gamma': 0.9086848615320234, 'reg_alpha': 0.0008177979046200564, 'reg_lambda': 0.00044247158557228}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:45,507] Trial 21 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.036664573344029006, 'max_depth': 5, 'min_child_weight': 1.260973683340702, 'subsample': 0.7411452533299434, 'colsample_bytree': 0.8007167253279321, 'gamma': 1.6933292393840693, 'reg_alpha': 0.005862290348864694, 'reg_lambda': 0.03430175244923979}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:51,206] Trial 22 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02934164705222114, 'max_depth': 5, 'min_child_weight': 1.383718954125864, 'subsample': 0.7655647256435949, 'colsample_bytree': 0.7712162750826156, 'gamma': 1.4486941198581356, 'reg_alpha': 0.011613525255434064, 'reg_lambda': 0.004920659637507184}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:27:55,257] Trial 23 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04326280942602445, 'max_depth': 3, 'min_child_weight': 1.8625847090208365, 'subsample': 0.8195757058676902, 'colsample_bytree': 0.7218733741534957, 'gamma': 1.5083519548484634, 'reg_alpha': 0.002672717553441807, 'reg_lambda': 0.2503662818064834}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:28:00,056] Trial 24 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0269797226000463, 'max_depth': 4, 'min_child_weight': 2.8607670606754, 'subsample': 0.7032067019907043, 'colsample_bytree': 0.8166399588819715, 'gamma': 0.26418535818823885, 'reg_alpha': 0.00034953038239536285, 'reg_lambda': 0.02809951104717541}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 09:28:05,346] Trial 25 finished with value: 0.40607328831309353 and parameters: {'learning_rate': 0.062167835010909035, 'max_depth': 5, 'min_child_weight': 1.4926028598809695, 'subsample': 0.756092186008002, 'colsample_bytree': 0.760391833162829, 'gamma': 1.1989544688507863, 'reg_alpha': 0.0014891967145060092, 'reg_lambda': 0.0019295679536769522}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:11,426] Trial 26 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06084614044863651, 'max_depth': 7, 'min_child_weight': 3.5477124614393065, 'subsample': 0.7481882366843804, 'colsample_bytree': 0.7589686944772, 'gamma': 1.2616231298773357, 'reg_alpha': 0.00010170183971949589, 'reg_lambda': 0.0018971482700167297}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:16,093] Trial 27 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06902256405487744, 'max_depth': 4, 'min_child_weight': 2.05015886243293, 'subsample': 0.8197749221257318, 'colsample_bytree': 0.8751396205180653, 'gamma': 0.5236151568534858, 'reg_alpha': 0.0015655462610296765, 'reg_lambda': 0.00035756316269210055}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:21,420] Trial 28 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08342488697243093, 'max_depth': 5, 'min_child_weight': 1.5424483229729034, 'subsample': 0.7186531548578046, 'colsample_bytree': 0.7228029420078474, 'gamma': 0.06380319170281623, 'reg_alpha': 0.011548037613622358, 'reg_lambda': 0.0007857543296603184}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:25,970] Trial 29 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.059330186758975584, 'max_depth': 5, 'min_child_weight': 3.8760498146527675, 'subsample': 0.7530449938658371, 'colsample_bytree': 0.8057088717822617, 'gamma': 0.9756022973255583, 'reg_alpha': 0.0003188017920215576, 'reg_lambda': 0.003431664781169453}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:29,344] Trial 30 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0475214677485584, 'max_depth': 3, 'min_child_weight': 1.3433934576724123, 'subsample': 0.722758939159104, 'colsample_bytree': 0.7847276102297208, 'gamma': 1.2370019069315308, 'reg_alpha': 5.544154050118195, 'reg_lambda': 0.016134369432008914}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:33,966] Trial 31 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03370359370179626, 'max_depth': 5, 'min_child_weight': 1.1845548761591835, 'subsample': 0.7650911710629398, 'colsample_bytree': 0.7633181887165331, 'gamma': 1.653226578900761, 'reg_alpha': 0.0015751187621022508, 'reg_lambda': 0.05853392893682434}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:39,291] Trial 32 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.040238728846914255, 'max_depth': 6, 'min_child_weight': 1.4738221271003629, 'subsample': 0.8076377565295616, 'colsample_bytree': 0.7184336841051306, 'gamma': 0.7620570827882197, 'reg_alpha': 0.008677832850918114, 'reg_lambda': 0.00023303630000396286}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:43,301] Trial 33 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09304864945620499, 'max_depth': 5, 'min_child_weight': 1.7520792099054059, 'subsample': 0.7741683255413927, 'colsample_bytree': 0.7534988666630588, 'gamma': 1.767861567536897, 'reg_alpha': 0.6195877209126176, 'reg_lambda': 0.0009201820869743753}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:48,060] Trial 34 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12056118629575856, 'max_depth': 4, 'min_child_weight': 2.2739786229370127, 'subsample': 0.871203807508141, 'colsample_bytree': 0.8253724459376219, 'gamma': 0.2319603403371252, 'reg_alpha': 0.0005975250552047877, 'reg_lambda': 1.7655429317422575}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:54,576] Trial 35 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.024284773322738092, 'max_depth': 6, 'min_child_weight': 2.7878801864508724, 'subsample': 0.7280415619075054, 'colsample_bytree': 0.8615612627708958, 'gamma': 1.8786551021392428, 'reg_alpha': 0.042933273232873555, 'reg_lambda': 0.003319154343648133}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:28:59,752] Trial 36 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05409584298515779, 'max_depth': 5, 'min_child_weight': 4.92549363670468, 'subsample': 0.8035685193837983, 'colsample_bytree': 0.9011724996905588, 'gamma': 1.9840827389075537, 'reg_alpha': 0.0022833224640357776, 'reg_lambda': 0.01171253580369179}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:06,161] Trial 37 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03426918140462277, 'max_depth': 6, 'min_child_weight': 1.3065705808815242, 'subsample': 0.8357409939979424, 'colsample_bytree': 0.787321550959715, 'gamma': 1.3529517726450258, 'reg_alpha': 0.11032361549492484, 'reg_lambda': 0.001295074345551799}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:13,419] Trial 38 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04375230327057051, 'max_depth': 7, 'min_child_weight': 1.0051501613690066, 'subsample': 0.760979883898667, 'colsample_bytree': 0.7393831515294779, 'gamma': 1.0705356339701273, 'reg_alpha': 0.025761712131400095, 'reg_lambda': 0.10174684050630985}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:18,211] Trial 39 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07610927962925086, 'max_depth': 5, 'min_child_weight': 6.957907726235103, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9873753736843738, 'gamma': 1.6139453589716468, 'reg_alpha': 0.31087418112773707, 'reg_lambda': 0.4390983674502461}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:22,814] Trial 40 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.14345399851814886, 'max_depth': 6, 'min_child_weight': 2.5029237730851275, 'subsample': 0.8958065950140971, 'colsample_bytree': 0.7562044990864343, 'gamma': 0.38780837297969245, 'reg_alpha': 0.017370411606955592, 'reg_lambda': 0.00022606019735921484}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:27,322] Trial 41 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.15384874058956868, 'max_depth': 5, 'min_child_weight': 4.609532889707593, 'subsample': 0.9602639650718224, 'colsample_bytree': 0.9247961883251317, 'gamma': 0.15615555563352815, 'reg_alpha': 2.1502105762071255, 'reg_lambda': 7.89135976462019}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:31,029] Trial 42 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.19993487894580958, 'max_depth': 4, 'min_child_weight': 5.376585356830021, 'subsample': 0.7895929545936885, 'colsample_bytree': 0.9623864515686733, 'gamma': 0.837736948277895, 'reg_alpha': 0.4696632222521308, 'reg_lambda': 1.3700757387933435}. Best is trial 25 with value: 0.40607328831309353.
[I 2026-04-15 09:29:36,051] Trial 43 finished with value: 0.4127561173873413 and parameters: {'learning_rate': 0.10622154451412531, 'max_depth': 5, 'min_child_weight': 3.6481894555260252, 'subsample': 0.7353942267479208, 'colsample_bytree': 0.9996533142159789, 'gamma': 0.008050105358543558, 'reg_alpha': 1.6036405852596725, 'reg_lambda': 2.566561914429623}. Best is trial 43 with value: 0.4127561173873413.
[I 2026-04-15 09:29:41,559] Trial 44 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.10907458632919713, 'max_depth': 5, 'min_child_weight': 3.4646159334320825, 'subsample': 0.7314332259815792, 'colsample_bytree': 0.9019515167873803, 'gamma': 0.03310811662229218, 'reg_alpha': 1.1446699613929825, 'reg_lambda': 6.395919238242873}. Best is trial 43 with value: 0.4127561173873413.
[I 2026-04-15 09:29:46,951] Trial 45 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.16701874980745865, 'max_depth': 6, 'min_child_weight': 3.0145085734079617, 'subsample': 0.7114335997315603, 'colsample_bytree': 0.999808428475493, 'gamma': 0.1980930355211895, 'reg_alpha': 3.5293848803356163, 'reg_lambda': 3.1693955335217185}. Best is trial 43 with value: 0.4127561173873413.
[I 2026-04-15 09:29:51,431] Trial 46 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0860997176474532, 'max_depth': 4, 'min_child_weight': 4.054270413967222, 'subsample': 0.7411911574140544, 'colsample_bytree': 0.7093625402977419, 'gamma': 0.3819495255429951, 'reg_alpha': 0.000886886965825095, 'reg_lambda': 0.545877438757828}. Best is trial 43 with value: 0.4127561173873413.
[I 2026-04-15 09:29:57,043] Trial 47 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06998095195990484, 'max_depth': 6, 'min_child_weight': 2.0037357148685357, 'subsample': 0.7767268838170878, 'colsample_bytree': 0.7306176158909164, 'gamma': 0.010225923818322161, 'reg_alpha': 9.290735707239438, 'reg_lambda': 3.231949453939784}. Best is trial 43 with value: 0.4127561173873413.

[I 2026-04-15 09:34:44,223] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 09:34:48,050] Trial 0 finished with value: 0.4175170216299249 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4175170216299249.
[I 2026-04-15 09:34:55,309] Trial 1 finished with value: 0.4357704271263513 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4357704271263513.
[I 2026-04-15 09:35:02,697] Trial 2 finished with value: 0.4376064406663672 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4376064406663672.
[I 2026-04-15 09:35:15,851] Trial 3 finished with value: 0.44490379570272565 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.44490379570272565.
[I 2026-04-15 09:35:36,097] Trial 4 finished with value: 0.4597528087026582 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:35:59,338] Trial 5 finished with value: 0.4375050426025221 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:36:12,307] Trial 6 finished with value: 0.41087761686569807 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:36:26,086] Trial 7 finished with value: 0.4182359841596054 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:36:54,268] Trial 8 finished with value: 0.4128006152866331 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:37:07,162] Trial 9 finished with value: 0.42772460296971243 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:37:11,715] Trial 10 finished with value: 0.4372834625366996 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.4597528087026582.
[I 2026-04-15 09:37:23,099] Trial 11 finished with value: 0.46082858632905493 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 4.651607675299369, 'random_strength': 0.016584038838684367, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 11 with value: 0.46082858632905493.
[I 2026-04-15 09:37:43,256] Trial 12 finished with value: 0.46460141013194345 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 3.672310184878952, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.870940447219903}. Best is trial 12 with value: 0.46460141013194345.
[I 2026-04-15 09:37:54,876] Trial 13 finished with value: 0.47908163034980167 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12821872834050937, 'depth': 7, 'l2_leaf_reg': 4.148284442416459, 'random_strength': 0.0020777312464156164, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8906367837209281}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:01,536] Trial 14 finished with value: 0.46897717989086746 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1162415606552535, 'depth': 6, 'l2_leaf_reg': 3.0754777831745983, 'random_strength': 0.252013748684086, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9053058454282036}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:08,377] Trial 15 finished with value: 0.4551246540979639 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11909420939082363, 'depth': 6, 'l2_leaf_reg': 2.8287792259579017, 'random_strength': 0.2483631178055416, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9814769576437812}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:12,806] Trial 16 finished with value: 0.4547908365469216 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12736941580906352, 'depth': 5, 'l2_leaf_reg': 6.34283093029632, 'random_strength': 0.42930430265932956, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9012912943586011}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:17,346] Trial 17 finished with value: 0.45433816677210886 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11905539155566275, 'depth': 5, 'l2_leaf_reg': 2.7384448272652633, 'random_strength': 0.14616523249231167, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9877840126803682}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:24,740] Trial 18 finished with value: 0.4668297182604527 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.054626192950187315, 'depth': 6, 'l2_leaf_reg': 2.5170514356418203, 'random_strength': 0.2659094234501002, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8369076660811569}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:40,392] Trial 19 finished with value: 0.45304524697398574 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.035236475622424886, 'depth': 7, 'l2_leaf_reg': 6.066601521555666, 'random_strength': 0.36808163042855613, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9394716488088194}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:46,960] Trial 20 finished with value: 0.4234634740872387 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13773768435303743, 'depth': 6, 'l2_leaf_reg': 1.213986904980901, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8877360164579796}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:54,245] Trial 21 finished with value: 0.46317931319725864 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05658334637706949, 'depth': 6, 'l2_leaf_reg': 2.7591345591909384, 'random_strength': 0.2603163820202221, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8259861193190353}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:38:58,894] Trial 22 finished with value: 0.45937351420727457 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09918718570141412, 'depth': 5, 'l2_leaf_reg': 2.2983221971425656, 'random_strength': 0.1963872936916164, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8524397886719057}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:06,039] Trial 23 finished with value: 0.46664256995535836 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05852941498258112, 'depth': 6, 'l2_leaf_reg': 3.7160198720941273, 'random_strength': 0.1010237987620512, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7994578167239308}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:19,705] Trial 24 finished with value: 0.4622847131327923 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0378273644365385, 'depth': 7, 'l2_leaf_reg': 3.4789963734240126, 'random_strength': 0.3441929305387217, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9259566669087994}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:26,449] Trial 25 finished with value: 0.4393901434487849 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14590974506210658, 'depth': 6, 'l2_leaf_reg': 2.126699789718528, 'random_strength': 0.5100575060484112, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7892447879924296}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:31,231] Trial 26 finished with value: 0.46542688658766795 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09896198910007814, 'depth': 5, 'l2_leaf_reg': 1.398369152745291, 'random_strength': 0.22991662977107533, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:43,124] Trial 27 finished with value: 0.4596950391504923 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06468701215690163, 'depth': 7, 'l2_leaf_reg': 5.758770807184991, 'random_strength': 0.005850617977777861, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9004522550678541}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:39:51,932] Trial 28 finished with value: 0.43823237524302805 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030842895566175563, 'depth': 6, 'l2_leaf_reg': 3.154262486042001, 'random_strength': 0.41790050451094696, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8467135683148539}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:09,231] Trial 29 finished with value: 0.411385687550687 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.048735185127244084, 'depth': 7, 'l2_leaf_reg': 2.3773035569859218, 'random_strength': 0.12115872780470982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.682610778645282}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:12,981] Trial 30 finished with value: 0.4400712382301627 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06893925713040859, 'depth': 4, 'l2_leaf_reg': 1.9736763970294595, 'random_strength': 0.5365856760216451, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.966114685821196}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:20,501] Trial 31 finished with value: 0.46189978250097957 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05385402538410514, 'depth': 6, 'l2_leaf_reg': 3.7569385859858055, 'random_strength': 0.09702656941728205, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8023185903572889}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:28,668] Trial 32 finished with value: 0.46163963896183074 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05793703510133098, 'depth': 6, 'l2_leaf_reg': 5.050366480939409, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8087201593175951}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:37,163] Trial 33 finished with value: 0.4609650145548634 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.040015733975190856, 'depth': 6, 'l2_leaf_reg': 4.145828675557496, 'random_strength': 0.0792320974162579, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8714685299629535}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:42,994] Trial 34 finished with value: 0.4429407966288292 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08947025922244799, 'depth': 5, 'l2_leaf_reg': 8.282400666529199, 'random_strength': 0.28817358699859497, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7508067193540683}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:49,582] Trial 35 finished with value: 0.46650873890189476 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10965181424667862, 'depth': 6, 'l2_leaf_reg': 3.2308985240155645, 'random_strength': 0.19994416545351137, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7805252165291044}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:40:52,708] Trial 36 finished with value: 0.4644396268548255 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15034013343544259, 'depth': 4, 'l2_leaf_reg': 7.249568114109302, 'random_strength': 0.06562621427471976, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9226322517211356}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:00,049] Trial 37 finished with value: 0.4703680301211943 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08493211948912455, 'depth': 6, 'l2_leaf_reg': 1.6265926821736472, 'random_strength': 0.1551872546656022, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7300327764711851}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:12,088] Trial 38 finished with value: 0.45585748635238926 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08821138520179676, 'depth': 7, 'l2_leaf_reg': 1.5302600789830862, 'random_strength': 0.32668558680460047, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12221043743904225}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:16,646] Trial 39 finished with value: 0.4713273270753572 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06992107212211822, 'depth': 5, 'l2_leaf_reg': 2.570724927820655, 'random_strength': 0.15827626735298647, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8677520046747301}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:20,196] Trial 40 finished with value: 0.42727235222848264 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07468328332501246, 'depth': 4, 'l2_leaf_reg': 1.7880266128945397, 'random_strength': 0.1616692652272202, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4532051511681003}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:25,037] Trial 41 finished with value: 0.45200017626483857 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08415121479010954, 'depth': 5, 'l2_leaf_reg': 2.4650251958130873, 'random_strength': 0.211826424527513, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8686816189771605}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:29,562] Trial 42 finished with value: 0.46683369608992226 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10687067639237707, 'depth': 5, 'l2_leaf_reg': 1.2630270662588445, 'random_strength': 0.13092421868673432, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.699632411461211}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:34,227] Trial 43 finished with value: 0.45771107239901154 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10786752497978848, 'depth': 5, 'l2_leaf_reg': 1.2004000077231487, 'random_strength': 0.0510001227477943, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7115461612606921}. Best is trial 13 with value: 0.47908163034980167.
[I 2026-04-15 09:41:37,464] Trial 44 finished with value: 0.44087967617876317 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10820576261442806, 'depth': 4, 'l2_leaf_reg': 1.0333592473614839, 'random_strength': 0.1474578763759984, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6660629905509684}. Best is trial 13 with value: 0.47908163034980167.

                                        feature  importance
505                              corr__umap_035    0.052740
494                              corr__umap_024    0.038584
497                              corr__umap_027    0.037188
556                              corr__umap_086    0.032652
210           eye__fix_duration_AOI_FD_Pos1_std    0.031924
561                              corr__umap_091    0.031310
275  eye__fix_duration_AOI_aggregated_Pos_first    0.030178
465                               eye__imf0_max    0.028628
507                              corr__umap_037    0.027122
169                    eye__fix_duration_median    0.026424
10                          eye__sac_speed_mean    0.022735
60        eye__sac_speed_AOI_aggregated_Pos_min    0.022457
161                          eye__reg_speed_std    0.022390
518                              corr__umap_048    0.021546
405  eye__rec_metric_euclidean_length_1_rho_500    0.021163
524                              corr__umap_054    0.021018
475                              corr__umap_005    0.020352
170                       eye__fix_duration_std    0.020269
422         eye__det_euclidean_length_2_rho_250    0.020017
527                              corr__umap_057    0.019773
12                           eye__sac_speed_std    0.018862
384               eye__corr_dim_m_4_tau_1_r_200    0.018807
533                              corr__umap_063    0.017692
176           eye__fix_duration_AOI_FD_Neg1_min    0.017661
463                            eye__imf0_median    0.017392
16                      eye__sac_angle_to_x_max    0.016299
7                          eye__sac_length_skew    0.015367
22                   eye__sac_angle_between_min    0.015041
462                               eye__imf0_std    0.014732
263    eye__fix_duration_AOI_aggregated_Neg_sum    0.014160

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.44377
              precision    recall  f1-score   support

           0       0.67      0.93      0.78       227
           1       0.30      0.06      0.11       109

    accuracy                           0.65       336
   macro avg       0.49      0.50      0.44       336
weighted avg       0.55      0.65      0.56       336

Confusion matrix:
 [[211  16]
 [102   7]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+corr__target=match_mismatch__problem=binary__feat=all_features+corr__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                      feature  importance
540                            corr__umap_070   10.573486
568                            corr__umap_098    8.543090
55    eye__sac_length_AOI_aggregated_Pos_mean    8.188261
500                            corr__umap_030    6.144319
283  eye__fix_duration_AOI_aggregated_Pos_sum    4.438687
499                            corr__umap_029    4.279336
555                            corr__umap_085    3.638867
565                            corr__umap_095    3.284312
495                            corr__umap_025    3.259541
554                            corr__umap_084    2.721627
60      eye__sac_speed_AOI_aggregated_Pos_min    2.633099
471                            corr__umap_001    2.588733
277  eye__fix_duration_AOI_aggregated_Pos_max    2.353213
546                            corr__umap_076    2.344391
7                        eye__sac_length_skew    2.293103
518                            corr__umap_048    2.234004
497                            corr__umap_027    2.229314
563                            corr__umap_093    2.142978
505                            corr__umap_035    2.077423
494                            corr__umap_024    2.072462
532                            corr__umap_062    1.911602
521                            corr__umap_051    1.757097
19                    eye__sac_angle_to_x_std    1.684097
488                            corr__umap_018    1.664820
167                     eye__fix_duration_max    1.621806
26                 eye__sac_angle_between_std    1.473722
152                    eye__reg_length_median    1.460994
465                             eye__imf0_max    1.232456
179      eye__fix_duration_AOI_FD_Neg1_median    1.171016
561                            corr__umap_091    1.128819

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__ES__refitTEST
[corr] rows missing after index match -> train: 1658, test: 160
[corr] UMAP compression: train/test features 1830 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 09:43:21,224] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+corr__target=match_mismatch__problem=multiclass__feat=all_features+corr__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 09:43:28,151] Trial 0 finished with value: 0.5167187524899288 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5167187524899288.
[I 2026-04-15 09:43:36,141] Trial 1 finished with value: 0.5173942002121068 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.5173942002121068.
[I 2026-04-15 09:43:44,165] Trial 2 finished with value: 0.5286535279912163 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5286535279912163.
[I 2026-04-15 09:43:51,176] Trial 3 finished with value: 0.5163005232487917 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.5286535279912163.
[I 2026-04-15 09:43:57,877] Trial 4 finished with value: 0.5324038496741423 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.5324038496741423.
[I 2026-04-15 09:44:07,096] Trial 5 finished with value: 0.5088406907028258 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.5324038496741423.
[I 2026-04-15 09:44:12,386] Trial 6 finished with value: 0.5341461761916946 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.5341461761916946.
[I 2026-04-15 09:44:22,711] Trial 7 finished with value: 0.5046977079731748 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.5341461761916946.
[I 2026-04-15 09:44:28,646] Trial 8 finished with value: 0.5281328413532718 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.5341461761916946.
[I 2026-04-15 09:44:40,106] Trial 9 finished with value: 0.5281666439161954 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.5341461761916946.
[I 2026-04-15 09:44:45,574] Trial 10 finished with value: 0.5403806598871959 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 10 with value: 0.5403806598871959.
[I 2026-04-15 09:44:50,962] Trial 11 finished with value: 0.5459936250566773 and parameters: {'learning_rate': 0.19928490475258703, 'max_depth': 3, 'min_child_weight': 2.3108399558144663, 'subsample': 0.7003857515532862, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.5525904909866688, 'reg_alpha': 0.000185939809238877, 'reg_lambda': 5.991143401742846}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:44:56,521] Trial 12 finished with value: 0.5335219052774125 and parameters: {'learning_rate': 0.19001657682154638, 'max_depth': 3, 'min_child_weight': 1.0277001574826408, 'subsample': 0.7008546103358549, 'colsample_bytree': 0.845235942520865, 'gamma': 1.4415935609939878, 'reg_alpha': 0.00010846875746792476, 'reg_lambda': 8.615080016175616}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:45:02,435] Trial 13 finished with value: 0.5121940896426181 and parameters: {'learning_rate': 0.12410932460697534, 'max_depth': 3, 'min_child_weight': 2.166399188953496, 'subsample': 0.7412255582492263, 'colsample_bytree': 0.8515547915330101, 'gamma': 1.4601336031562036, 'reg_alpha': 0.0007493693765798017, 'reg_lambda': 9.500540100715765}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:45:07,650] Trial 14 finished with value: 0.5405269789822835 and parameters: {'learning_rate': 0.19959049508024268, 'max_depth': 4, 'min_child_weight': 2.457598498095955, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8880624944018081, 'gamma': 1.3585035843518556, 'reg_alpha': 0.00010017901135484514, 'reg_lambda': 0.8477717119907059}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:45:13,323] Trial 15 finished with value: 0.5447865390940435 and parameters: {'learning_rate': 0.12655063460659607, 'max_depth': 4, 'min_child_weight': 2.4370747834999373, 'subsample': 0.8487777503738585, 'colsample_bytree': 0.8996358449400135, 'gamma': 1.2513887824418548, 'reg_alpha': 0.004309394829594551, 'reg_lambda': 0.7180371291630383}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:45:19,751] Trial 16 finished with value: 0.5293348405855353 and parameters: {'learning_rate': 0.12932716286568818, 'max_depth': 4, 'min_child_weight': 2.5680826679195397, 'subsample': 0.9182852554062144, 'colsample_bytree': 0.8136626354725327, 'gamma': 0.7225884405958181, 'reg_alpha': 0.003344306776329649, 'reg_lambda': 1.8569849231544222}. Best is trial 11 with value: 0.5459936250566773.
[I 2026-04-15 09:45:25,849] Trial 17 finished with value: 0.5502871317715148 and parameters: {'learning_rate': 0.0757107188838502, 'max_depth': 4, 'min_child_weight': 4.907699675577318, 'subsample': 0.8410527291583754, 'colsample_bytree': 0.9040872744739058, 'gamma': 1.2236897605322707, 'reg_alpha': 0.00394927860776442, 'reg_lambda': 0.2058197484047974}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:45:32,311] Trial 18 finished with value: 0.5154888713143477 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 3, 'min_child_weight': 5.224091826226014, 'subsample': 0.8278121509244132, 'colsample_bytree': 0.9874282329380343, 'gamma': 1.6806681082794075, 'reg_alpha': 0.0016833335803052476, 'reg_lambda': 0.011397783591272139}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:45:39,345] Trial 19 finished with value: 0.5277473993223505 and parameters: {'learning_rate': 0.07926309759084964, 'max_depth': 4, 'min_child_weight': 6.3981657835471815, 'subsample': 0.8880257485823237, 'colsample_bytree': 0.8143176228199928, 'gamma': 1.0061494687654013, 'reg_alpha': 0.015577109275725427, 'reg_lambda': 0.00011509949482230567}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:45:45,493] Trial 20 finished with value: 0.5066925385918482 and parameters: {'learning_rate': 0.042350163788700664, 'max_depth': 3, 'min_child_weight': 4.007776920998683, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.9097134929101489, 'gamma': 1.6601980324494632, 'reg_alpha': 0.0003045092375225589, 'reg_lambda': 0.3257701527841956}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:45:51,486] Trial 21 finished with value: 0.523860360079318 and parameters: {'learning_rate': 0.14233246757006995, 'max_depth': 4, 'min_child_weight': 2.8523451481750093, 'subsample': 0.8260003319319114, 'colsample_bytree': 0.9016498529957141, 'gamma': 1.2036063400893482, 'reg_alpha': 0.0059806850605957675, 'reg_lambda': 2.2362762736505597}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:45:57,860] Trial 22 finished with value: 0.5420954361923526 and parameters: {'learning_rate': 0.10332399115493597, 'max_depth': 4, 'min_child_weight': 1.972386402077985, 'subsample': 0.8141876133925556, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.2437180298628587, 'reg_alpha': 0.0016213265501045075, 'reg_lambda': 0.21399830173903064}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:05,878] Trial 23 finished with value: 0.5065146596260491 and parameters: {'learning_rate': 0.0889751730841278, 'max_depth': 5, 'min_child_weight': 1.4299433447676253, 'subsample': 0.8663220934701257, 'colsample_bytree': 0.920629853368673, 'gamma': 0.8380646530153671, 'reg_alpha': 0.010269301617526256, 'reg_lambda': 3.090805782689655}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:11,569] Trial 24 finished with value: 0.5113128006304704 and parameters: {'learning_rate': 0.1464281275174454, 'max_depth': 3, 'min_child_weight': 3.2490463189556813, 'subsample': 0.9203983058259789, 'colsample_bytree': 0.8658456430406561, 'gamma': 1.30922513851934, 'reg_alpha': 0.0015056139493266636, 'reg_lambda': 1.0592478092262818}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:17,709] Trial 25 finished with value: 0.5131591191948635 and parameters: {'learning_rate': 0.11125100742890155, 'max_depth': 4, 'min_child_weight': 4.493228840787698, 'subsample': 0.7642047093179776, 'colsample_bytree': 0.8273774885990757, 'gamma': 1.5733959046059405, 'reg_alpha': 0.07184153779176658, 'reg_lambda': 0.02267992098981532}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:24,878] Trial 26 finished with value: 0.5383777614234394 and parameters: {'learning_rate': 0.06646308277435159, 'max_depth': 5, 'min_child_weight': 2.328629821966405, 'subsample': 0.851075876355965, 'colsample_bytree': 0.8807007671624207, 'gamma': 1.9991361650069521, 'reg_alpha': 0.003137218174208601, 'reg_lambda': 0.2631248560944187}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:30,180] Trial 27 finished with value: 0.544488893585015 and parameters: {'learning_rate': 0.15151771949198573, 'max_depth': 3, 'min_child_weight': 6.970867707567396, 'subsample': 0.8065061053915995, 'colsample_bytree': 0.9689162987138302, 'gamma': 1.809511348357829, 'reg_alpha': 0.000222979762149347, 'reg_lambda': 0.14178082489131547}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:37,955] Trial 28 finished with value: 0.5236165500118163 and parameters: {'learning_rate': 0.08342488697243093, 'max_depth': 4, 'min_child_weight': 2.797162559507432, 'subsample': 0.882569308871092, 'colsample_bytree': 0.9182763008374059, 'gamma': 0.9439104003666332, 'reg_alpha': 0.000768231185909226, 'reg_lambda': 4.3889924965803155}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:47,810] Trial 29 finished with value: 0.5276203259234715 and parameters: {'learning_rate': 0.051661432577547746, 'max_depth': 7, 'min_child_weight': 3.738436622017613, 'subsample': 0.7548765505824182, 'colsample_bytree': 0.7803587372748191, 'gamma': 1.138319098935235, 'reg_alpha': 0.05706607885333583, 'reg_lambda': 1.399596048422289}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:53,423] Trial 30 finished with value: 0.5133120477977762 and parameters: {'learning_rate': 0.16100935501405064, 'max_depth': 3, 'min_child_weight': 5.189207831134769, 'subsample': 0.9233218299147409, 'colsample_bytree': 0.8314575448676064, 'gamma': 0.5076131178991343, 'reg_alpha': 5.544154050118195, 'reg_lambda': 4.07879752293545}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:46:59,289] Trial 31 finished with value: 0.5357995399524267 and parameters: {'learning_rate': 0.14454699169171314, 'max_depth': 3, 'min_child_weight': 7.02886807097012, 'subsample': 0.8048626915251212, 'colsample_bytree': 0.9659508704746469, 'gamma': 1.7136967053668581, 'reg_alpha': 0.00021440935477801416, 'reg_lambda': 0.09100583085287}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:47:04,615] Trial 32 finished with value: 0.5429727906772167 and parameters: {'learning_rate': 0.1595415860484878, 'max_depth': 4, 'min_child_weight': 7.082574177793442, 'subsample': 0.8391713004006858, 'colsample_bytree': 0.9571132011614166, 'gamma': 1.7889952508401388, 'reg_alpha': 0.0004885534094075655, 'reg_lambda': 0.028722926716426282}. Best is trial 17 with value: 0.5502871317715148.
[I 2026-04-15 09:47:10,534] Trial 33 finished with value: 0.550565047497161 and parameters: {'learning_rate': 0.13591109180120567, 'max_depth': 3, 'min_child_weight': 1.7753313980169647, 'subsample': 0.8112102579758673, 'colsample_bytree': 0.9896258627657109, 'gamma': 1.5297949610755834, 'reg_alpha': 0.00018161949526552667, 'reg_lambda': 0.21159839229050686}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:16,691] Trial 34 finished with value: 0.5331693642067348 and parameters: {'learning_rate': 0.09806644122206337, 'max_depth': 4, 'min_child_weight': 1.730952094377908, 'subsample': 0.8616806639316663, 'colsample_bytree': 0.992258968986271, 'gamma': 1.509567866873657, 'reg_alpha': 0.006079373688003773, 'reg_lambda': 0.485514601657259}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:22,696] Trial 35 finished with value: 0.51573650373173 and parameters: {'learning_rate': 0.13028703671600939, 'max_depth': 8, 'min_child_weight': 2.0518872170339337, 'subsample': 0.8807305749522237, 'colsample_bytree': 0.9000454684172045, 'gamma': 1.3317619975292154, 'reg_alpha': 0.0009405595817636981, 'reg_lambda': 0.05167979172606139}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:28,432] Trial 36 finished with value: 0.5282017818440268 and parameters: {'learning_rate': 0.11134716146066517, 'max_depth': 3, 'min_child_weight': 1.2967132187635075, 'subsample': 0.9039251893533077, 'colsample_bytree': 0.8723680827301958, 'gamma': 1.2454637425788357, 'reg_alpha': 0.00017275510666100267, 'reg_lambda': 0.37574562985908144}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:35,733] Trial 37 finished with value: 0.5249744449483651 and parameters: {'learning_rate': 0.07220884420645834, 'max_depth': 5, 'min_child_weight': 1.4579943944731715, 'subsample': 0.7039134032848413, 'colsample_bytree': 0.9370087677416155, 'gamma': 1.5683495757015327, 'reg_alpha': 0.010362249486204908, 'reg_lambda': 0.908771609799562}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:43,586] Trial 38 finished with value: 0.513805008287828 and parameters: {'learning_rate': 0.05562742750053194, 'max_depth': 4, 'min_child_weight': 1.9099119380156904, 'subsample': 0.7276477091135832, 'colsample_bytree': 0.9496194343839207, 'gamma': 1.387609916981438, 'reg_alpha': 0.7652689559765227, 'reg_lambda': 0.17085127037279307}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:49,162] Trial 39 finished with value: 0.5181837278164858 and parameters: {'learning_rate': 0.17583180911020255, 'max_depth': 5, 'min_child_weight': 1.601876803909072, 'subsample': 0.9369555194214146, 'colsample_bytree': 0.9237910110838797, 'gamma': 0.9620833532821518, 'reg_alpha': 0.0026636699143631503, 'reg_lambda': 1.5798875963818442}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:47:54,976] Trial 40 finished with value: 0.5398249904336941 and parameters: {'learning_rate': 0.09458797342430678, 'max_depth': 3, 'min_child_weight': 2.9048581787212218, 'subsample': 0.7776741401577425, 'colsample_bytree': 0.8968372465513696, 'gamma': 1.5786632757582537, 'reg_alpha': 0.03552285551550351, 'reg_lambda': 0.011640749949206813}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:00,565] Trial 41 finished with value: 0.5469480152060415 and parameters: {'learning_rate': 0.15288820540493808, 'max_depth': 3, 'min_child_weight': 8.250400217887666, 'subsample': 0.803568680441382, 'colsample_bytree': 0.9999752592446086, 'gamma': 1.85484523731562, 'reg_alpha': 0.0004409288403475639, 'reg_lambda': 0.12036430784119281}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:05,842] Trial 42 finished with value: 0.5292315481159379 and parameters: {'learning_rate': 0.17087100793912238, 'max_depth': 3, 'min_child_weight': 9.84074033590184, 'subsample': 0.8269655243974068, 'colsample_bytree': 0.996471650923697, 'gamma': 1.89907113742409, 'reg_alpha': 0.0004399912792606533, 'reg_lambda': 0.06726603563050795}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:11,721] Trial 43 finished with value: 0.5104350354965425 and parameters: {'learning_rate': 0.12504479389314943, 'max_depth': 7, 'min_child_weight': 3.4804729923161553, 'subsample': 0.7988693178318043, 'colsample_bytree': 0.9769084655988677, 'gamma': 1.7072463648512908, 'reg_alpha': 0.0001591807354442902, 'reg_lambda': 0.5583673400594092}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:19,525] Trial 44 finished with value: 0.5189198992546382 and parameters: {'learning_rate': 0.02188029840119486, 'max_depth': 3, 'min_child_weight': 8.31537541165046, 'subsample': 0.8580290708126327, 'colsample_bytree': 0.9825844007005246, 'gamma': 1.1579980050615155, 'reg_alpha': 0.0005218688787168182, 'reg_lambda': 0.1061937930208517}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:24,415] Trial 45 finished with value: 0.5177955841352668 and parameters: {'learning_rate': 0.19823653302353825, 'max_depth': 4, 'min_child_weight': 1.2248980439037327, 'subsample': 0.762832148284882, 'colsample_bytree': 0.999808428475493, 'gamma': 1.8668029972546998, 'reg_alpha': 0.0010280256066382961, 'reg_lambda': 0.02164734939142994}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:29,764] Trial 46 finished with value: 0.5283442647581358 and parameters: {'learning_rate': 0.13849613767411723, 'max_depth': 3, 'min_child_weight': 2.234728914856234, 'subsample': 0.8164714169310412, 'colsample_bytree': 0.9548741005457707, 'gamma': 1.0508994211878697, 'reg_alpha': 0.000372883470071775, 'reg_lambda': 0.0027516616755635273}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:35,932] Trial 47 finished with value: 0.5380216418872248 and parameters: {'learning_rate': 0.037889799669519345, 'max_depth': 3, 'min_child_weight': 4.87838067757435, 'subsample': 0.8382423464187043, 'colsample_bytree': 0.8430376922421504, 'gamma': 1.4055633731938855, 'reg_alpha': 0.0023850812572773035, 'reg_lambda': 0.039608724166937385}. Best is trial 33 with value: 0.550565047497161.
[I 2026-04-15 09:48:41,247] Trial 48 finished with value: 0.5250437673195502 and parameters: {'learning_rate': 0.10663555451200211, 'max_depth': 4, 'min_child_weight': 5.837711842750803, 'subsample': 0.7479962152529178, 'colsample_bytree': 0.8831604786153071, 'gamma': 1.9664635263326917, 'reg_alpha': 0.00010312463723965323, 'reg_lambda': 5.12747688241271}. Best is trial 33 with value: 0.550565047497161.

[I 2026-04-15 09:52:44,840] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 09:52:51,462] Trial 0 finished with value: 0.5016819493743552 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5016819493743552.
[I 2026-04-15 09:52:59,607] Trial 1 finished with value: 0.5265929874240318 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:53:14,008] Trial 2 finished with value: 0.5007982996954505 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:53:33,399] Trial 3 finished with value: 0.5233023814039124 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:54:10,259] Trial 4 finished with value: 0.5100240826233692 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:54:55,687] Trial 5 finished with value: 0.48927152999177226 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:55:19,119] Trial 6 finished with value: 0.5083329992150449 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:55:39,094] Trial 7 finished with value: 0.49588499810951414 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:56:31,636] Trial 8 finished with value: 0.4703512400083191 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:56:50,978] Trial 9 finished with value: 0.5090573882221849 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:57:00,965] Trial 10 finished with value: 0.5229240999931348 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 1 with value: 0.5265929874240318.
[I 2026-04-15 09:57:11,966] Trial 11 finished with value: 0.5268193035782068 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03348469920743832, 'depth': 5, 'l2_leaf_reg': 10.466444324483772, 'random_strength': 0.5950158754059278, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.622187261552841}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:57:24,690] Trial 12 finished with value: 0.48530202716039905 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031222380286557255, 'depth': 5, 'l2_leaf_reg': 6.565531658457727, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6280513913200843}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:57:38,434] Trial 13 finished with value: 0.5080698653639951 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033456846134581275, 'depth': 5, 'l2_leaf_reg': 12.822663012444984, 'random_strength': 0.4875665096082098, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.603513652274123}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:57:47,292] Trial 14 finished with value: 0.5188714887202797 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029212246807366084, 'depth': 5, 'l2_leaf_reg': 5.074742486962073, 'random_strength': 0.0009654705471253411, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8791010705732631}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:57:54,559] Trial 15 finished with value: 0.5222420687657952 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025205257405628973, 'depth': 4, 'l2_leaf_reg': 13.415300028032739, 'random_strength': 0.594232700948295, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6980485160987138}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:58:01,692] Trial 16 finished with value: 0.521491586815676 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05219399788945581, 'depth': 5, 'l2_leaf_reg': 7.522230360973634, 'random_strength': 0.3788754515751092, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6913258324588829}. Best is trial 11 with value: 0.5268193035782068.
[I 2026-04-15 09:58:07,251] Trial 17 finished with value: 0.535546282804789 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03877696433253156, 'depth': 4, 'l2_leaf_reg': 11.342878590708327, 'random_strength': 0.20458519629947178, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8209911986048593}. Best is trial 17 with value: 0.535546282804789.
[I 2026-04-15 09:58:15,587] Trial 18 finished with value: 0.5104976025340134 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.038185476970674335, 'depth': 5, 'l2_leaf_reg': 3.1804871873053115, 'random_strength': 0.5769033525634435, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8523249955395609}. Best is trial 17 with value: 0.535546282804789.
[I 2026-04-15 09:58:27,917] Trial 19 finished with value: 0.5385405447951166 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12170625700594725, 'depth': 6, 'l2_leaf_reg': 2.824854809186434, 'random_strength': 0.7485614479472406, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8303314759163367}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:58:38,852] Trial 20 finished with value: 0.5244432101500678 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13097106766159983, 'depth': 6, 'l2_leaf_reg': 2.6816725490896114, 'random_strength': 0.8504289112475044, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.83987292510528}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:58:45,708] Trial 21 finished with value: 0.5001685223825066 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1176555678920623, 'depth': 5, 'l2_leaf_reg': 3.0518613313756604, 'random_strength': 0.7300873584639261, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9090270781936924}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:58:59,120] Trial 22 finished with value: 0.5104814803732896 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05749527988766944, 'depth': 6, 'l2_leaf_reg': 9.36437739498916, 'random_strength': 0.8045436474541685, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7970469115588112}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:03,253] Trial 23 finished with value: 0.5317885179714543 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19938181693767976, 'depth': 4, 'l2_leaf_reg': 5.445361258929107, 'random_strength': 0.9124076147422964, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8058563134314877}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:06,997] Trial 24 finished with value: 0.5204795504904179 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17161609244058526, 'depth': 4, 'l2_leaf_reg': 2.0797661644551635, 'random_strength': 0.9155609466982837, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8153850331509459}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:10,715] Trial 25 finished with value: 0.5164908434009172 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1989350012547665, 'depth': 4, 'l2_leaf_reg': 6.135906255931162, 'random_strength': 0.9650512716473458, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9986863284042589}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:29,194] Trial 26 finished with value: 0.520268842553641 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1365942278633688, 'depth': 7, 'l2_leaf_reg': 3.6629826470559914, 'random_strength': 0.8991403299812896, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:34,231] Trial 27 finished with value: 0.5302679679542668 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09965054469654629, 'depth': 4, 'l2_leaf_reg': 5.4869629857370805, 'random_strength': 0.7220967185775348, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7687857394957288}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:49,227] Trial 28 finished with value: 0.5029396848334384 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1624591769875432, 'depth': 6, 'l2_leaf_reg': 1.4187831097922743, 'random_strength': 0.4017222032082699, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8984101688779544}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 09:59:54,868] Trial 29 finished with value: 0.5159039791544675 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0628547313289788, 'depth': 4, 'l2_leaf_reg': 2.2854487807751513, 'random_strength': 0.1818861310311614, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:00,033] Trial 30 finished with value: 0.534923634181192 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15164629075644886, 'depth': 4, 'l2_leaf_reg': 3.933188320602294, 'random_strength': 0.5324829610190565, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.803551884203507}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:05,096] Trial 31 finished with value: 0.49536777422467415 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15568607480199873, 'depth': 4, 'l2_leaf_reg': 3.972992757869551, 'random_strength': 0.5427735377907323, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8088964711381982}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:09,565] Trial 32 finished with value: 0.5178130023112488 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11277243732233003, 'depth': 4, 'l2_leaf_reg': 2.563888554049511, 'random_strength': 0.6671240585214677, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8523201886688575}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:14,723] Trial 33 finished with value: 0.5107907685529338 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13822295666968917, 'depth': 4, 'l2_leaf_reg': 3.480299299695279, 'random_strength': 0.7960186141105956, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7894750977178409}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:19,307] Trial 34 finished with value: 0.5015334343674669 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19877738664127118, 'depth': 4, 'l2_leaf_reg': 1.714290597515975, 'random_strength': 0.2961309229592378, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7349266884786119}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:27,297] Trial 35 finished with value: 0.5233868495152088 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15103796529935018, 'depth': 5, 'l2_leaf_reg': 7.881870224787871, 'random_strength': 0.4393997898589782, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8271682123628413}. Best is trial 19 with value: 0.5385405447951166.
[I 2026-04-15 10:00:31,862] Trial 36 finished with value: 0.5547372185378472 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09608884882454823, 'depth': 4, 'l2_leaf_reg': 4.756673344722687, 'random_strength': 0.08740194506482135, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8781114126148699}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:00:38,385] Trial 37 finished with value: 0.5233473723196803 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09148378272595663, 'depth': 5, 'l2_leaf_reg': 2.815777085904454, 'random_strength': 0.11011145803817626, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8697961745497591}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:00:59,232] Trial 38 finished with value: 0.5147795670459769 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1137230021917754, 'depth': 7, 'l2_leaf_reg': 1.3179582800613847, 'random_strength': 0.22238998388112152, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.12221043743904225}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:01:12,071] Trial 39 finished with value: 0.5409849130464652 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06992107212211822, 'depth': 6, 'l2_leaf_reg': 4.393122579303308, 'random_strength': 0.0499006900014036, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9355447328665553}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:01:25,342] Trial 40 finished with value: 0.5166012500703105 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0659569565619378, 'depth': 6, 'l2_leaf_reg': 2.3280285039282793, 'random_strength': 0.008049043718594322, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.4532051511681003}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:01:35,328] Trial 41 finished with value: 0.5410767690332922 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08229625385082809, 'depth': 6, 'l2_leaf_reg': 4.35465628859686, 'random_strength': 0.09235308590215713, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9441057308448005}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:01:46,377] Trial 42 finished with value: 0.5186255963649178 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0856001446852093, 'depth': 6, 'l2_leaf_reg': 4.6417767454186745, 'random_strength': 0.06798738374224281, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9385486437521494}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:02:09,275] Trial 43 finished with value: 0.5040782680810777 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07444806969211568, 'depth': 7, 'l2_leaf_reg': 6.467786590865389, 'random_strength': 0.12236780337704212, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.940129194895246}. Best is trial 36 with value: 0.5547372185378472.
[I 2026-04-15 10:02:19,756] Trial 44 finished with value: 0.5377155192997706 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10145734483013198, 'depth': 6, 'l2_leaf_reg': 4.4141089650394685, 'random_strength': 0.05101785559765494, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9693974848053195}. Best is trial 36 with value: 0.5547372185378472.

                                      feature  importance
213         eye__fix_duration_AOI_FD_Pos1_sum   19.571424
283  eye__fix_duration_AOI_aggregated_Pos_sum   15.507368
530                            corr__umap_060   14.972842
540                            corr__umap_070   13.278978
494                            corr__umap_024    8.223304
207         eye__fix_duration_AOI_FD_Pos1_max    8.183390
527                            corr__umap_057    5.432375
170                     eye__fix_duration_std    4.940585
490                            corr__umap_020    3.966588
474                            corr__umap_004    3.484402
168                    eye__fix_duration_mean    2.438743
20               eye__sac_angle_to_x_kurtosis    0.000000
21                   eye__sac_angle_to_x_skew    0.000000
22                 eye__sac_angle_between_min    0.000000
23                 eye__sac_angle_between_max    0.000000
24                eye__sac_angle_between_mean    0.000000
25              eye__sac_angle_between_median    0.000000
513                            corr__umap_043    0.000000
57     eye__sac_length_AOI_aggregated_Pos_std    0.000000
545                            corr__umap_075    0.000000
537                            corr__umap_067    0.000000
33     eye__sac_length_AOI_aggregated_Neg_std    0.000000
569                            corr__umap_099    0.000000
0                         eye__sac_length_min    0.000000
1                         eye__sac_length_max    0.000000
2                        eye__sac_length_mean    0.000000
3                      eye__sac_length_median    0.000000
4                         eye__sac_length_std    0.000000
5                         eye__sac_length_sum    0.000000
6                    eye__sac_length_kurtosis    0.000000

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__ES__refitTEST
[corr] rows missing after index match -> train: 1658, test: 160
[corr] UMAP compression: train/test features 1830 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 10:04:47,531] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 10:04:51,622] Trial 0 finished with value: 0.46805288758403507 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.46805288758403507.
[I 2026-04-15 10:04:56,005] Trial 1 finished with value: 0.4705228345310095 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.4705228345310095.
[I 2026-04-15 10:05:00,666] Trial 2 finished with value: 0.48711497966057105 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.48711497966057105.
[I 2026-04-15 10:05:04,810] Trial 3 finished with value: 0.4662987413777121 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.48711497966057105.
[I 2026-04-15 10:05:08,996] Trial 4 finished with value: 0.45446859502759746 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.48711497966057105.
[I 2026-04-15 10:05:13,547] Trial 5 finished with value: 0.46078921285184005 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 2 with value: 0.48711497966057105.
[I 2026-04-15 10:05:17,070] Trial 6 finished with value: 0.48836708747939683 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.48836708747939683.
[I 2026-04-15 10:05:22,055] Trial 7 finished with value: 0.4502958942107947 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.48836708747939683.
[I 2026-04-15 10:05:26,615] Trial 8 finished with value: 0.4548169829228095 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.48836708747939683.
[I 2026-04-15 10:05:33,876] Trial 9 finished with value: 0.460359278370441 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.48836708747939683.
[I 2026-04-15 10:05:38,270] Trial 10 finished with value: 0.4673987680616455 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.48836708747939683.
[I 2026-04-15 10:05:44,324] Trial 11 finished with value: 0.510905233321819 and parameters: {'learning_rate': 0.02892233549974803, 'max_depth': 4, 'min_child_weight': 2.0632174240992716, 'subsample': 0.7552007048968172, 'colsample_bytree': 0.8277506537128274, 'gamma': 1.9653408366428464, 'reg_alpha': 0.008246295702960541, 'reg_lambda': 0.6190388625923278}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:05:49,770] Trial 12 finished with value: 0.49298283956283895 and parameters: {'learning_rate': 0.02206894317379378, 'max_depth': 3, 'min_child_weight': 2.158609633387336, 'subsample': 0.7007294325911076, 'colsample_bytree': 0.8552620759154461, 'gamma': 1.9787591584130297, 'reg_alpha': 0.004276189057829091, 'reg_lambda': 0.607354793366673}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:05:55,482] Trial 13 finished with value: 0.4586982655185714 and parameters: {'learning_rate': 0.020706588051260858, 'max_depth': 3, 'min_child_weight': 2.3905626572629437, 'subsample': 0.7012740987614869, 'colsample_bytree': 0.8152250818441382, 'gamma': 1.4739629881482226, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.8409895220435655}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:01,180] Trial 14 finished with value: 0.4935251115082105 and parameters: {'learning_rate': 0.027959751284261446, 'max_depth': 4, 'min_child_weight': 2.3243917145192965, 'subsample': 0.8232547850336159, 'colsample_bytree': 0.8880624944018081, 'gamma': 1.966867519850192, 'reg_alpha': 0.002748885779508337, 'reg_lambda': 0.010607489782014975}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:06,795] Trial 15 finished with value: 0.4666748238450861 and parameters: {'learning_rate': 0.03176694048952753, 'max_depth': 4, 'min_child_weight': 2.559600206607746, 'subsample': 0.8348368522561531, 'colsample_bytree': 0.8996358449400135, 'gamma': 1.3977616671674873, 'reg_alpha': 0.0012293364524432959, 'reg_lambda': 0.00016599250040776937}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:12,047] Trial 16 finished with value: 0.4679648281693505 and parameters: {'learning_rate': 0.04351514810744496, 'max_depth': 4, 'min_child_weight': 1.4123259987229952, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8136626354725327, 'gamma': 1.6840947290923096, 'reg_alpha': 0.00010967002170160583, 'reg_lambda': 0.011132462335461252}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:17,834] Trial 17 finished with value: 0.45641070527759886 and parameters: {'learning_rate': 0.02787158091356686, 'max_depth': 4, 'min_child_weight': 4.907699675577318, 'subsample': 0.8870911863689172, 'colsample_bytree': 0.8951394494369396, 'gamma': 1.2236897605322707, 'reg_alpha': 0.012183260101225635, 'reg_lambda': 0.01128788430515987}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:22,938] Trial 18 finished with value: 0.46488602784274313 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 4, 'min_child_weight': 2.7453391899645445, 'subsample': 0.7543655957773596, 'colsample_bytree': 0.8246028769629669, 'gamma': 1.6827254229226243, 'reg_alpha': 0.0016833335803052476, 'reg_lambda': 0.17064354730886802}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:28,016] Trial 19 finished with value: 0.46241443486044476 and parameters: {'learning_rate': 0.02598696712030664, 'max_depth': 3, 'min_child_weight': 1.059972794948725, 'subsample': 0.8099359784546718, 'colsample_bytree': 0.9942318571111104, 'gamma': 0.7900830006485098, 'reg_alpha': 0.04689250238136265, 'reg_lambda': 0.01764567731199089}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:33,838] Trial 20 finished with value: 0.45711141937886757 and parameters: {'learning_rate': 0.04062695499103881, 'max_depth': 5, 'min_child_weight': 1.9666710651613823, 'subsample': 0.9187518128288744, 'colsample_bytree': 0.7815426511038929, 'gamma': 1.2949977718089345, 'reg_alpha': 0.010602817984138027, 'reg_lambda': 0.004119751544499884}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:39,244] Trial 21 finished with value: 0.4971552699840853 and parameters: {'learning_rate': 0.025087946668038277, 'max_depth': 3, 'min_child_weight': 2.1647159276410264, 'subsample': 0.7615228552568324, 'colsample_bytree': 0.859013476113369, 'gamma': 1.9666142404039448, 'reg_alpha': 0.0033994235376915115, 'reg_lambda': 1.9544934217995473}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:47,099] Trial 22 finished with value: 0.4650666705962667 and parameters: {'learning_rate': 0.027174838661515932, 'max_depth': 3, 'min_child_weight': 1.5898055952009342, 'subsample': 0.7544394714947532, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.7997130072577616, 'reg_alpha': 8.70290869543081, 'reg_lambda': 2.944133183151258}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:52,846] Trial 23 finished with value: 0.45994303985320983 and parameters: {'learning_rate': 0.036580386074053096, 'max_depth': 4, 'min_child_weight': 3.01055184954997, 'subsample': 0.8146176299590988, 'colsample_bytree': 0.8742294884113392, 'gamma': 1.9652498166864638, 'reg_alpha': 0.0013429864951192711, 'reg_lambda': 2.254975576477381}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:06:57,323] Trial 24 finished with value: 0.470333024797403 and parameters: {'learning_rate': 0.055878729929919796, 'max_depth': 3, 'min_child_weight': 2.180455454812394, 'subsample': 0.8566866583348862, 'colsample_bytree': 0.8421036227771447, 'gamma': 1.5968046283026516, 'reg_alpha': 0.00036756810570399225, 'reg_lambda': 0.19691935769451333}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:04,486] Trial 25 finished with value: 0.47297329738136457 and parameters: {'learning_rate': 0.026551459352151058, 'max_depth': 4, 'min_child_weight': 3.4054013099930835, 'subsample': 0.761587043699844, 'colsample_bytree': 0.9111481283250722, 'gamma': 1.777590753053508, 'reg_alpha': 0.007379206836111697, 'reg_lambda': 9.628953846559758}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:10,141] Trial 26 finished with value: 0.47167930562589067 and parameters: {'learning_rate': 0.024207508062346526, 'max_depth': 5, 'min_child_weight': 1.7683553288605374, 'subsample': 0.8102634347865632, 'colsample_bytree': 0.836883722810494, 'gamma': 1.9991361650069521, 'reg_alpha': 0.0022673689893531264, 'reg_lambda': 0.030539538970666774}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:14,575] Trial 27 finished with value: 0.4955777685214674 and parameters: {'learning_rate': 0.02883741356392343, 'max_depth': 3, 'min_child_weight': 3.9354031488163796, 'subsample': 0.7317636952055064, 'colsample_bytree': 0.8709678504139668, 'gamma': 1.5953455198751834, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 1.6449837161495668}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:19,690] Trial 28 finished with value: 0.47247860112944445 and parameters: {'learning_rate': 0.03773501297767915, 'max_depth': 3, 'min_child_weight': 4.416683571417364, 'subsample': 0.7350297864427116, 'colsample_bytree': 0.865927501529344, 'gamma': 1.5550745611764791, 'reg_alpha': 0.00011047778735115058, 'reg_lambda': 1.5478521180099132}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:24,407] Trial 29 finished with value: 0.4613891367678823 and parameters: {'learning_rate': 0.05370802791392482, 'max_depth': 3, 'min_child_weight': 3.991616015990577, 'subsample': 0.7178949787886987, 'colsample_bytree': 0.7887529138760851, 'gamma': 1.8234652237137041, 'reg_alpha': 0.00047130060461607917, 'reg_lambda': 3.40703820139502}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:29,769] Trial 30 finished with value: 0.48312107851763314 and parameters: {'learning_rate': 0.046683624584463415, 'max_depth': 4, 'min_child_weight': 5.450144525893764, 'subsample': 0.7367758483538198, 'colsample_bytree': 0.9142389267802247, 'gamma': 0.5076131178991343, 'reg_alpha': 0.0006447566368522076, 'reg_lambda': 0.29005401983550877}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:35,610] Trial 31 finished with value: 0.4707399388134069 and parameters: {'learning_rate': 0.031992740431931725, 'max_depth': 4, 'min_child_weight': 2.8760603562863203, 'subsample': 0.7613919929686068, 'colsample_bytree': 0.8798784141089265, 'gamma': 1.8704355278997864, 'reg_alpha': 0.014890351653751478, 'reg_lambda': 5.03318820887244}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:43,212] Trial 32 finished with value: 0.4796969460699659 and parameters: {'learning_rate': 0.029766005065352673, 'max_depth': 8, 'min_child_weight': 3.6991407583924234, 'subsample': 0.8010134490359758, 'colsample_bytree': 0.8337560946795247, 'gamma': 1.7514114053427152, 'reg_alpha': 0.047780744288981665, 'reg_lambda': 1.59984924992595}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:48,197] Trial 33 finished with value: 0.4667354919823081 and parameters: {'learning_rate': 0.024050428626995086, 'max_depth': 3, 'min_child_weight': 2.3987467396845825, 'subsample': 0.8306593990317183, 'colsample_bytree': 0.8078898437153245, 'gamma': 1.5765145460344057, 'reg_alpha': 0.00019782735099009083, 'reg_lambda': 0.3302038307156428}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:07:53,986] Trial 34 finished with value: 0.4727695694277201 and parameters: {'learning_rate': 0.023032875144182004, 'max_depth': 4, 'min_child_weight': 1.961965632802749, 'subsample': 0.7663570616493388, 'colsample_bytree': 0.8515177103155046, 'gamma': 1.8938563177214423, 'reg_alpha': 0.0029854056902977994, 'reg_lambda': 0.07852593849785866}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:08:00,289] Trial 35 finished with value: 0.4589704566696155 and parameters: {'learning_rate': 0.03611750149231636, 'max_depth': 7, 'min_child_weight': 7.0655104654048335, 'subsample': 0.775007917312238, 'colsample_bytree': 0.9226485055410241, 'gamma': 1.7080198254818661, 'reg_alpha': 0.006778158769821304, 'reg_lambda': 1.1062545886260553}. Best is trial 11 with value: 0.510905233321819.
[I 2026-04-15 10:08:04,284] Trial 36 finished with value: 0.5195049996845964 and parameters: {'learning_rate': 0.13469108396399915, 'max_depth': 3, 'min_child_weight': 1.2533474091079702, 'subsample': 0.8729701432673623, 'colsample_bytree': 0.774037819678975, 'gamma': 1.3041370445819171, 'reg_alpha': 0.0008842260189299357, 'reg_lambda': 0.0044054856338788025}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:08,382] Trial 37 finished with value: 0.5018704124764206 and parameters: {'learning_rate': 0.13901036356689667, 'max_depth': 3, 'min_child_weight': 1.2477236515733117, 'subsample': 0.8773980951015634, 'colsample_bytree': 0.7627329459492401, 'gamma': 0.9055694078056846, 'reg_alpha': 0.0009348686890460012, 'reg_lambda': 0.00045629257672837617}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:12,462] Trial 38 finished with value: 0.4590466695633584 and parameters: {'learning_rate': 0.13435856689119172, 'max_depth': 3, 'min_child_weight': 1.198697914445159, 'subsample': 0.8751508845938594, 'colsample_bytree': 0.7292030177914023, 'gamma': 0.8263423136517867, 'reg_alpha': 0.0007574489936658618, 'reg_lambda': 0.0003384708686246029}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:16,532] Trial 39 finished with value: 0.4946804189273488 and parameters: {'learning_rate': 0.13322255056672344, 'max_depth': 3, 'min_child_weight': 1.2744558859185893, 'subsample': 0.9253159750682973, 'colsample_bytree': 0.7640408298182997, 'gamma': 0.9620833532821518, 'reg_alpha': 0.0010043261268273564, 'reg_lambda': 0.0010129358087879999}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:22,595] Trial 40 finished with value: 0.46106761379035144 and parameters: {'learning_rate': 0.09710329241274235, 'max_depth': 7, 'min_child_weight': 1.4774160296801973, 'subsample': 0.8476583911361402, 'colsample_bytree': 0.7638636543938383, 'gamma': 0.41001975288654846, 'reg_alpha': 0.00022467357166500355, 'reg_lambda': 0.0023057417087430153}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:26,718] Trial 41 finished with value: 0.48883053148578876 and parameters: {'learning_rate': 0.14350378669652536, 'max_depth': 3, 'min_child_weight': 1.2238453911329552, 'subsample': 0.9068176868053346, 'colsample_bytree': 0.7784267610864686, 'gamma': 1.3107409426707544, 'reg_alpha': 0.00023967635470939827, 'reg_lambda': 0.0005350529802662954}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:30,834] Trial 42 finished with value: 0.5166636995264419 and parameters: {'learning_rate': 0.0991850655719627, 'max_depth': 3, 'min_child_weight': 1.7518710691822745, 'subsample': 0.9472491712941472, 'colsample_bytree': 0.8041518227702017, 'gamma': 1.1623026167480583, 'reg_alpha': 0.0006787969033108115, 'reg_lambda': 0.004429912364235536}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:35,005] Trial 43 finished with value: 0.5087267046026528 and parameters: {'learning_rate': 0.10753024549744601, 'max_depth': 3, 'min_child_weight': 1.7894165164934208, 'subsample': 0.9568539439080118, 'colsample_bytree': 0.8016520515879464, 'gamma': 1.0148477301672578, 'reg_alpha': 0.0017393122410679918, 'reg_lambda': 0.00414761758456979}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:39,051] Trial 44 finished with value: 0.4566245844859791 and parameters: {'learning_rate': 0.10211516878909413, 'max_depth': 5, 'min_child_weight': 1.619974969177265, 'subsample': 0.9979399023558567, 'colsample_bytree': 0.801047639746261, 'gamma': 0.9658397429445862, 'reg_alpha': 0.0007615461305303066, 'reg_lambda': 0.0035450390149661054}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:42,923] Trial 45 finished with value: 0.4615722017934406 and parameters: {'learning_rate': 0.07901299606249311, 'max_depth': 3, 'min_child_weight': 1.11041305072377, 'subsample': 0.9565641133508931, 'colsample_bytree': 0.7410557371920821, 'gamma': 1.1520384135756037, 'reg_alpha': 0.0016949350169414498, 'reg_lambda': 0.005733402108609059}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:46,949] Trial 46 finished with value: 0.4623192882697156 and parameters: {'learning_rate': 0.15763627402213445, 'max_depth': 3, 'min_child_weight': 1.8025713033752657, 'subsample': 0.9447536416877851, 'colsample_bytree': 0.7726050078797916, 'gamma': 0.7769629455387882, 'reg_alpha': 0.0005419531293195197, 'reg_lambda': 0.00011599524049994559}. Best is trial 36 with value: 0.5195049996845964.
[I 2026-04-15 10:08:51,767] Trial 47 finished with value: 0.4967479264041196 and parameters: {'learning_rate': 0.11245952264257893, 'max_depth': 5, 'min_child_weight': 1.4642234942629415, 'subsample': 0.9851289743063716, 'colsample_bytree': 0.793189031009052, 'gamma': 0.6561152672931927, 'reg_alpha': 0.006819968096918562, 'reg_lambda': 0.0010400677074131426}. Best is trial 36 with value: 0.5195049996845964.

[I 2026-04-15 10:12:27,936] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.44011
              precision    recall  f1-score   support

           0       0.70      0.97      0.81       234
           1       0.33      0.04      0.07       102

    accuracy                           0.68       336
   macro avg       0.52      0.50      0.44       336
weighted avg       0.59      0.68      0.59       336

Confusion matrix:
 [[226   8]
 [ 98   4]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 10:12:33,284] Trial 0 finished with value: 0.5264867397215074 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5264867397215074.
[I 2026-04-15 10:12:45,930] Trial 1 finished with value: 0.5690074055232681 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5690074055232681.
[I 2026-04-15 10:12:54,783] Trial 2 finished with value: 0.562806271619779 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.5690074055232681.
[I 2026-04-15 10:13:12,741] Trial 3 finished with value: 0.577549933932902 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:13:32,258] Trial 4 finished with value: 0.5620381466121158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:14:06,292] Trial 5 finished with value: 0.5748104484347407 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:14:23,458] Trial 6 finished with value: 0.5707446294344243 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:14:52,289] Trial 7 finished with value: 0.5642857600276155 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:15:35,447] Trial 8 finished with value: 0.5546177705134838 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:15:48,898] Trial 9 finished with value: 0.5707572575694868 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:15:54,076] Trial 10 finished with value: 0.5663573711801293 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1570794430403163, 'depth': 5, 'l2_leaf_reg': 5.721398227528868, 'random_strength': 0.9905905821371315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9500025439539328}. Best is trial 3 with value: 0.577549933932902.
[I 2026-04-15 10:16:08,359] Trial 11 finished with value: 0.5878253337745755 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11253920142059598, 'depth': 7, 'l2_leaf_reg': 2.662526128923081, 'random_strength': 0.6729776286708733, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.12665706747865135}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:16:23,913] Trial 12 finished with value: 0.5783816191233733 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12226996737193573, 'depth': 7, 'l2_leaf_reg': 3.0487689960093807, 'random_strength': 0.5902492181451736, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.566664895898511}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:16:31,408] Trial 13 finished with value: 0.559403696407841 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12456527727349298, 'depth': 6, 'l2_leaf_reg': 2.794509930771249, 'random_strength': 0.5425996471792227, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.07104276866682985}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:16:49,493] Trial 14 finished with value: 0.5649738298536416 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11801919482219568, 'depth': 7, 'l2_leaf_reg': 2.9366299392359014, 'random_strength': 0.5113177067359264, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.04419917373479931}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:16:58,611] Trial 15 finished with value: 0.5600786477357448 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12725930491366905, 'depth': 6, 'l2_leaf_reg': 2.5928554952000256, 'random_strength': 0.7564087652454612, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.21210978252071}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:17:06,781] Trial 16 finished with value: 0.5600777641369432 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05219399788945581, 'depth': 5, 'l2_leaf_reg': 1.3148127085468448, 'random_strength': 0.918144756068022, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.2794595544677556}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:17:20,798] Trial 17 finished with value: 0.5838787775275434 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.18800999344616837, 'depth': 7, 'l2_leaf_reg': 3.5388279123899506, 'random_strength': 0.6372779784319408, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.5846830805071181}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:17:25,803] Trial 18 finished with value: 0.5424827839517719 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19984127714379707, 'depth': 5, 'l2_leaf_reg': 4.7584389542599235, 'random_strength': 0.7562797422551338, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.9176697499592925}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:18:13,855] Trial 19 finished with value: 0.5623990456328775 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.15360967997703137, 'depth': 8, 'l2_leaf_reg': 2.0664816505082415, 'random_strength': 0.4122971633258843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.6421883260277292}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:18:33,963] Trial 20 finished with value: 0.5722685895921843 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09902477730701538, 'depth': 7, 'l2_leaf_reg': 6.484605416088232, 'random_strength': 0.6828389325999049, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.7429825377505492}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:18:48,438] Trial 21 finished with value: 0.5749245110727252 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14579916936432386, 'depth': 7, 'l2_leaf_reg': 3.7545190851880714, 'random_strength': 0.5640418765134843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.49445107105037156}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:19:04,676] Trial 22 finished with value: 0.5739556223474855 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10829188135523003, 'depth': 7, 'l2_leaf_reg': 3.490370584038011, 'random_strength': 0.5955812315981186, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.6986788234259407}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:19:28,276] Trial 23 finished with value: 0.5655974838181923 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19976385057557877, 'depth': 8, 'l2_leaf_reg': 2.3168335960274375, 'random_strength': 0.8010338024432337, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.9313798231443535}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:19:46,373] Trial 24 finished with value: 0.5632957189583181 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1425918326273767, 'depth': 7, 'l2_leaf_reg': 3.4512285787264387, 'random_strength': 0.6731407694306932, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.6220067027866368}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:19:54,455] Trial 25 finished with value: 0.5695163758591532 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06142282787738138, 'depth': 6, 'l2_leaf_reg': 1.5028042287167294, 'random_strength': 0.4452042464927296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.018237343024895186}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:20:07,022] Trial 26 finished with value: 0.5800199597677079 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1716163768665842, 'depth': 7, 'l2_leaf_reg': 5.336166168366137, 'random_strength': 0.3110569546492601, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.0387653943755124}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:20:13,838] Trial 27 finished with value: 0.5675221691746073 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.16916816356916398, 'depth': 6, 'l2_leaf_reg': 5.8360731127538, 'random_strength': 0.3313932213280784, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.103291599214591}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:01,519] Trial 28 finished with value: 0.5538520983410037 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03322651802115874, 'depth': 8, 'l2_leaf_reg': 5.086952956302918, 'random_strength': 0.3881105996340738, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.923622257568288}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:20,597] Trial 29 finished with value: 0.5447417101361072 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09930356006484894, 'depth': 7, 'l2_leaf_reg': 7.867454296038797, 'random_strength': 0.23248901024797647, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.4508923671465133}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:27,857] Trial 30 finished with value: 0.5732669753496065 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1385844291744137, 'depth': 6, 'l2_leaf_reg': 1.887089170621408, 'random_strength': 0.037696356698014244, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.9954787500285593}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:40,829] Trial 31 finished with value: 0.571436390876547 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17421623582677054, 'depth': 7, 'l2_leaf_reg': 3.306963019219955, 'random_strength': 0.6017819552870379, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.3453866380553632}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:52,317] Trial 32 finished with value: 0.571450267848588 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12228149648242814, 'depth': 7, 'l2_leaf_reg': 4.034327234466101, 'random_strength': 0.5015230680723729, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5846518311460458}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:21:57,459] Trial 33 finished with value: 0.5675061194364597 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06745024361339165, 'depth': 4, 'l2_leaf_reg': 2.319654201114874, 'random_strength': 0.17589429692815559, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.38825547602998106}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:22:25,784] Trial 34 finished with value: 0.575051417550476 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08848660541015613, 'depth': 7, 'l2_leaf_reg': 3.041646829744834, 'random_strength': 0.7046474690112375, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8978403702475195}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:22:45,623] Trial 35 finished with value: 0.5591128722671158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17691133625585045, 'depth': 8, 'l2_leaf_reg': 7.272651217714434, 'random_strength': 0.27191949388701797, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.838972334674102}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:23:08,296] Trial 36 finished with value: 0.5692063258766065 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0369055818079162, 'depth': 7, 'l2_leaf_reg': 1.816459795690333, 'random_strength': 0.5838446530569423, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7715902431879442}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:23:32,977] Trial 37 finished with value: 0.5827576845728755 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13912843200618177, 'depth': 8, 'l2_leaf_reg': 8.964855293430027, 'random_strength': 0.6238929386716533, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2651214030793845}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:23:53,875] Trial 38 finished with value: 0.5636539903422547 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15855686956884718, 'depth': 8, 'l2_leaf_reg': 8.914788820935017, 'random_strength': 0.8384146728392186, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9977875830457904}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:24:16,156] Trial 39 finished with value: 0.5794156218394211 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1976711114358196, 'depth': 8, 'l2_leaf_reg': 13.868792077622764, 'random_strength': 0.719677699385582, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.16426356056323074}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:24:39,336] Trial 40 finished with value: 0.5750273007294162 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10887630632089465, 'depth': 8, 'l2_leaf_reg': 11.468139420664704, 'random_strength': 0.6354664719938159, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.9140510788659165}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:25:02,576] Trial 41 finished with value: 0.5805570541261109 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.18892862432359114, 'depth': 8, 'l2_leaf_reg': 19.961629235362214, 'random_strength': 0.7176493765171484, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2812677782132904}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:25:24,389] Trial 42 finished with value: 0.5777052625359421 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1799355655415816, 'depth': 8, 'l2_leaf_reg': 19.768821507435742, 'random_strength': 0.6353918704194359, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.34659881739540044}. Best is trial 11 with value: 0.5878253337745755.
[I 2026-04-15 10:25:47,876] Trial 43 finished with value: 0.5895749358228359 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13892998890002592, 'depth': 8, 'l2_leaf_reg': 11.94715018488423, 'random_strength': 0.8810929837977658, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.35870069037995}. Best is trial 43 with value: 0.5895749358228359.
[I 2026-04-15 10:26:09,997] Trial 44 finished with value: 0.5710008528161215 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1386371459718334, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.8912448969610106, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.31351480656870095}. Best is trial 43 with value: 0.5895749358228359.

                                               feature  importance
60               eye__sac_speed_AOI_aggregated_Pos_min    0.134893
523                                     corr__umap_053    0.055419
56           eye__sac_length_AOI_aggregated_Pos_median    0.052129
511                                     corr__umap_041    0.047245
563                                     corr__umap_093    0.043796
568                                     corr__umap_098    0.043139
183                  eye__fix_duration_AOI_FD_Neg1_sum    0.040414
485                                     corr__umap_015    0.037744
534                                     corr__umap_064    0.037385
559                                     corr__umap_089    0.036439
479                                     corr__umap_009    0.035678
515                                     corr__umap_045    0.034240
541                                     corr__umap_071    0.033111
339                      eye__sample_entropy_m=3_r=200    0.031243
32           eye__sac_length_AOI_aggregated_Neg_median    0.030387
535                                     corr__umap_065    0.029826
526                                     corr__umap_056    0.029806
5                                  eye__sac_length_sum    0.028824
560                                     corr__umap_090    0.028376
512                                     corr__umap_042    0.027587
471                                     corr__umap_001    0.026724
507                                     corr__umap_037    0.022606
555                                     corr__umap_085    0.021904
504                                     corr__umap_034    0.021363
317                              eye__hurst_exponent.1    0.018963
506                                     corr__umap_036    0.018376
47           eye__sac_length_AOI_aggregated_None_count    0.015942
521                                     corr__umap_051    0.013652
101  eye__sac_length_from_Target_to_Pos_from_Target...    0.002787
4                                  eye__sac_length_std    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.48674
              precision    recall  f1-score   support

           0       0.71      0.93      0.80       234
           1       0.41      0.11      0.17       102

    accuracy                           0.68       336
   macro avg       0.56      0.52      0.49       336
weighted avg       0.62      0.68      0.61       336

Confusion matrix:
 [[218  16]
 [ 91  11]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+corr__target=match_mismatch_general__problem=binary__feat=all_features+corr__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                       feature  importance
60       eye__sac_speed_AOI_aggregated_Pos_min    9.551503
56   eye__sac_length_AOI_aggregated_Pos_median    3.708503
61       eye__sac_speed_AOI_aggregated_Pos_max    3.674826
550                             corr__umap_080    3.393528
540                             corr__umap_070    2.753580
569                             corr__umap_099    2.457097
506                             corr__umap_036    2.321814
178         eye__fix_duration_AOI_FD_Neg1_mean    2.293149
553                             corr__umap_083    2.231913
490                             corr__umap_020    2.203519
501                             corr__umap_031    1.631495
207          eye__fix_duration_AOI_FD_Pos1_max    1.565963
507                             corr__umap_037    1.540530
517                             corr__umap_047    1.393934
503                             corr__umap_033    1.355281
263   eye__fix_duration_AOI_aggregated_Neg_sum    1.327930
514                             corr__umap_044    1.277989
473                             corr__umap_003    1.193960
568                             corr__umap_098    1.172830
464                              eye__imf0_min    1.112741
414         eye__det_euclidean_length_2_rho_25    1.101213
497                             corr__umap_027    1.089997
529                             corr__umap_059    1.086384
551                             corr__umap_081    1.063411
505                             corr__umap_035    1.053325
502                             corr__umap_032    1.038883
37       eye__sac_speed_AOI_aggregated_Neg_max    1.038641
176          eye__fix_duration_AOI_FD_Neg1_min    1.018418
482                             corr__umap_012    1.016385
367                 eye__fractal_dim_m_3_tau_1    0.982779

================================================================================
Skipping existing experiment: exp__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__ES__refitTEST
[corr] rows missing after index match -> train: 1658, test: 160
[corr] UMAP compression: train/test features 1830 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 10:29:50,408] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+corr__target=match_mismatch_general__problem=multiclass__feat=all_features+corr__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 10:29:57,328] Trial 0 finished with value: 0.6253460585346845 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:03,813] Trial 1 finished with value: 0.5965995398346338 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:11,548] Trial 2 finished with value: 0.6246740595473257 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:18,388] Trial 3 finished with value: 0.6142851731733023 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:24,747] Trial 4 finished with value: 0.6047275413039148 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:34,982] Trial 5 finished with value: 0.6162801235923552 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.6253460585346845.
[I 2026-04-15 10:30:40,546] Trial 6 finished with value: 0.6280705170241612 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:30:51,569] Trial 7 finished with value: 0.6223319511994218 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:30:57,876] Trial 8 finished with value: 0.6137368166123208 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:12,202] Trial 9 finished with value: 0.6172568116282501 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:17,395] Trial 10 finished with value: 0.6253972665734773 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:22,505] Trial 11 finished with value: 0.6257995760049688 and parameters: {'learning_rate': 0.19928490475258703, 'max_depth': 3, 'min_child_weight': 2.3108399558144663, 'subsample': 0.7003857515532862, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.5525904909866688, 'reg_alpha': 0.000185939809238877, 'reg_lambda': 5.991143401742846}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:27,455] Trial 12 finished with value: 0.6212436246959984 and parameters: {'learning_rate': 0.1419055446041347, 'max_depth': 3, 'min_child_weight': 2.158609633387336, 'subsample': 0.7008841262770472, 'colsample_bytree': 0.8629975808647283, 'gamma': 1.9529690823553414, 'reg_alpha': 0.0001135122408011297, 'reg_lambda': 0.9808849405676635}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:32,901] Trial 13 finished with value: 0.6210722734652337 and parameters: {'learning_rate': 0.18944709763827763, 'max_depth': 4, 'min_child_weight': 2.3527346379720164, 'subsample': 0.7412255582492263, 'colsample_bytree': 0.8869350037315704, 'gamma': 1.4462652907444928, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 9.693520203364706}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:38,743] Trial 14 finished with value: 0.6250714859541695 and parameters: {'learning_rate': 0.11908675805036831, 'max_depth': 4, 'min_child_weight': 5.293870612391065, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8097524232703589, 'gamma': 1.440446761002087, 'reg_alpha': 0.003951021561695887, 'reg_lambda': 0.49258163286769713}. Best is trial 6 with value: 0.6280705170241612.
[I 2026-04-15 10:31:44,746] Trial 15 finished with value: 0.6310033505076489 and parameters: {'learning_rate': 0.06919298904036045, 'max_depth': 3, 'min_child_weight': 2.605443591982054, 'subsample': 0.8252652712609115, 'colsample_bytree': 0.895993735152329, 'gamma': 1.6890627892873857, 'reg_alpha': 7.109124434771832, 'reg_lambda': 0.00016599250040776937}. Best is trial 15 with value: 0.6310033505076489.
[I 2026-04-15 10:31:51,886] Trial 16 finished with value: 0.6379247920784028 and parameters: {'learning_rate': 0.07765052758169766, 'max_depth': 8, 'min_child_weight': 6.098806807282297, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8984310486157346, 'gamma': 1.9554673903555668, 'reg_alpha': 4.557002815792933, 'reg_lambda': 0.008593003551665814}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:31:59,363] Trial 17 finished with value: 0.6361228707733817 and parameters: {'learning_rate': 0.0725663678492993, 'max_depth': 8, 'min_child_weight': 6.556028792195321, 'subsample': 0.8421064718154707, 'colsample_bytree': 0.9973624860451081, 'gamma': 1.2236897605322707, 'reg_alpha': 7.930680487996729, 'reg_lambda': 0.00013705377030600718}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:05,319] Trial 18 finished with value: 0.62680322144673 and parameters: {'learning_rate': 0.08458155821846411, 'max_depth': 8, 'min_child_weight': 6.901986375503244, 'subsample': 0.8986446342609649, 'colsample_bytree': 0.9874282329380343, 'gamma': 1.153522453285549, 'reg_alpha': 9.52651154015087, 'reg_lambda': 0.011397783591272139}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:14,430] Trial 19 finished with value: 0.6182437773887222 and parameters: {'learning_rate': 0.05794543768959237, 'max_depth': 7, 'min_child_weight': 4.4558451353449255, 'subsample': 0.8838208732826002, 'colsample_bytree': 0.8236891489977652, 'gamma': 0.6349333920358116, 'reg_alpha': 1.181026400073092, 'reg_lambda': 0.00010085886423414332}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:23,994] Trial 20 finished with value: 0.6200460557669853 and parameters: {'learning_rate': 0.042350163788700664, 'max_depth': 7, 'min_child_weight': 6.813128232859968, 'subsample': 0.933653685551472, 'colsample_bytree': 0.9940811435755007, 'gamma': 1.2222035919132004, 'reg_alpha': 0.7568181884192757, 'reg_lambda': 0.00044247158557228}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:32,634] Trial 21 finished with value: 0.6299115089046008 and parameters: {'learning_rate': 0.07230743010060676, 'max_depth': 8, 'min_child_weight': 2.8523451481750093, 'subsample': 0.8305220639808468, 'colsample_bytree': 0.9190262075391779, 'gamma': 1.6933292393840693, 'reg_alpha': 9.499680669700998, 'reg_lambda': 0.00011591489692449949}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:40,697] Trial 22 finished with value: 0.636046704883585 and parameters: {'learning_rate': 0.06808908839867202, 'max_depth': 8, 'min_child_weight': 4.043721964376532, 'subsample': 0.8198146497087088, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.3266065687769162, 'reg_alpha': 4.333606859221959, 'reg_lambda': 0.00030496893059959274}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:47,824] Trial 23 finished with value: 0.626237025535926 and parameters: {'learning_rate': 0.09111303687578169, 'max_depth': 8, 'min_child_weight': 4.59346128841493, 'subsample': 0.8117896253284479, 'colsample_bytree': 0.783055404250946, 'gamma': 0.8599135877621263, 'reg_alpha': 2.9947595446664, 'reg_lambda': 0.008093688123924156}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:32:54,905] Trial 24 finished with value: 0.634708956358605 and parameters: {'learning_rate': 0.060484529198742594, 'max_depth': 7, 'min_child_weight': 3.7365888570293433, 'subsample': 0.8668192547531585, 'colsample_bytree': 0.7023486227822291, 'gamma': 1.3121682329011324, 'reg_alpha': 4.753413378228821, 'reg_lambda': 0.0004158953672187621}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:01,669] Trial 25 finished with value: 0.621910563626218 and parameters: {'learning_rate': 0.10293951453076333, 'max_depth': 8, 'min_child_weight': 6.603649682522216, 'subsample': 0.8122482215591038, 'colsample_bytree': 0.8307239054643843, 'gamma': 1.3060181387466048, 'reg_alpha': 0.6552291229555525, 'reg_lambda': 0.002317286038385882}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:12,542] Trial 26 finished with value: 0.617206313879898 and parameters: {'learning_rate': 0.048185678657985814, 'max_depth': 7, 'min_child_weight': 5.558597530878767, 'subsample': 0.8538762259472756, 'colsample_bytree': 0.9163245586404791, 'gamma': 0.9495449859003915, 'reg_alpha': 2.620716244370548, 'reg_lambda': 0.0003452171613037398}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:24,378] Trial 27 finished with value: 0.6247001787394701 and parameters: {'learning_rate': 0.03748780321156162, 'max_depth': 8, 'min_child_weight': 7.985291959180716, 'subsample': 0.7580785394426199, 'colsample_bytree': 0.96510279940655, 'gamma': 0.4605674952556479, 'reg_alpha': 0.11823266503149756, 'reg_lambda': 0.004590380726423293}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:31,802] Trial 28 finished with value: 0.6017428358574206 and parameters: {'learning_rate': 0.06721829185771931, 'max_depth': 7, 'min_child_weight': 3.7985560082995815, 'subsample': 0.8030841763827858, 'colsample_bytree': 0.9614142459810849, 'gamma': 1.8162574616893412, 'reg_alpha': 0.4776789659419509, 'reg_lambda': 0.02517756936961448}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:37,962] Trial 29 finished with value: 0.615961167887979 and parameters: {'learning_rate': 0.11682316050577234, 'max_depth': 8, 'min_child_weight': 5.000187850576897, 'subsample': 0.911241509469789, 'colsample_bytree': 0.7647484916633236, 'gamma': 0.9950073345286009, 'reg_alpha': 4.052955255568679, 'reg_lambda': 0.00024785014533284453}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:45,192] Trial 30 finished with value: 0.6134625354707773 and parameters: {'learning_rate': 0.07884672805053851, 'max_depth': 7, 'min_child_weight': 3.2075975201493887, 'subsample': 0.8377355970968463, 'colsample_bytree': 0.7113089070094042, 'gamma': 0.813031501239111, 'reg_alpha': 1.5253836501872167, 'reg_lambda': 0.000777282135033362}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:51,851] Trial 31 finished with value: 0.6318284886228662 and parameters: {'learning_rate': 0.05851447615350022, 'max_depth': 8, 'min_child_weight': 3.78773577141683, 'subsample': 0.8702464185009814, 'colsample_bytree': 0.7121089788851123, 'gamma': 1.2811230051201214, 'reg_alpha': 5.305741480582455, 'reg_lambda': 0.0007520641535764493}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:33:58,205] Trial 32 finished with value: 0.6294057678985248 and parameters: {'learning_rate': 0.06137177699427226, 'max_depth': 7, 'min_child_weight': 3.879413413348443, 'subsample': 0.8727524247754741, 'colsample_bytree': 0.7255449038717523, 'gamma': 1.3514317008876564, 'reg_alpha': 4.831180790904052, 'reg_lambda': 0.0005693626012396252}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:06,204] Trial 33 finished with value: 0.6267292413279517 and parameters: {'learning_rate': 0.04656871245628629, 'max_depth': 8, 'min_child_weight': 7.575057896793757, 'subsample': 0.8252272403092801, 'colsample_bytree': 0.7030131303606604, 'gamma': 1.5695967476964003, 'reg_alpha': 2.0613904975709247, 'reg_lambda': 0.003326827057793666}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:13,422] Trial 34 finished with value: 0.6135653516213773 and parameters: {'learning_rate': 0.07387974626350594, 'max_depth': 7, 'min_child_weight': 5.705498558409288, 'subsample': 0.854709682742574, 'colsample_bytree': 0.7658664050623906, 'gamma': 1.1600528691602734, 'reg_alpha': 0.0011088992224441887, 'reg_lambda': 0.000253279968210202}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:20,718] Trial 35 finished with value: 0.6207389766268474 and parameters: {'learning_rate': 0.05439351437106008, 'max_depth': 8, 'min_child_weight': 4.299567361746728, 'subsample': 0.8864388887978097, 'colsample_bytree': 0.7825570064541714, 'gamma': 1.7759020647059784, 'reg_alpha': 0.9086635035338968, 'reg_lambda': 0.0014895077577778734}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:26,660] Trial 36 finished with value: 0.6289829325656016 and parameters: {'learning_rate': 0.1004040654122123, 'max_depth': 8, 'min_child_weight': 9.999978053662037, 'subsample': 0.9273758370454327, 'colsample_bytree': 0.7262205835194464, 'gamma': 1.5595112027173634, 'reg_alpha': 3.1789007790150787, 'reg_lambda': 0.00087090969525663}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:33,028] Trial 37 finished with value: 0.6212469834832354 and parameters: {'learning_rate': 0.08650787199053014, 'max_depth': 7, 'min_child_weight': 6.237153940348237, 'subsample': 0.8573065424693415, 'colsample_bytree': 0.8357311314803126, 'gamma': 1.3873245182141336, 'reg_alpha': 0.35935365171724193, 'reg_lambda': 0.00022493708327995921}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:40,445] Trial 38 finished with value: 0.6121794881813838 and parameters: {'learning_rate': 0.05160707688425645, 'max_depth': 8, 'min_child_weight': 5.005936207596096, 'subsample': 0.7654875995931603, 'colsample_bytree': 0.7494852186350256, 'gamma': 1.9967325376063068, 'reg_alpha': 0.04779797855961288, 'reg_lambda': 0.0011632016092846832}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:34:49,890] Trial 39 finished with value: 0.6178154735830647 and parameters: {'learning_rate': 0.028522992696152435, 'max_depth': 6, 'min_child_weight': 3.323108318079665, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.7996395421646056, 'gamma': 0.6990908461317394, 'reg_alpha': 4.836636408537759, 'reg_lambda': 0.016099619611587953}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:01,392] Trial 40 finished with value: 0.6233337381956153 and parameters: {'learning_rate': 0.0645583970409809, 'max_depth': 7, 'min_child_weight': 2.8240895055307775, 'subsample': 0.7971077865252248, 'colsample_bytree': 0.9104122515516361, 'gamma': 0.35845340181584706, 'reg_alpha': 0.010238682233660545, 'reg_lambda': 0.00360105054972263}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:07,832] Trial 41 finished with value: 0.6305744248624525 and parameters: {'learning_rate': 0.06371318127795697, 'max_depth': 8, 'min_child_weight': 3.9268018314471065, 'subsample': 0.8653305244675492, 'colsample_bytree': 0.7133063042128449, 'gamma': 1.26723349901033, 'reg_alpha': 6.010256480942131, 'reg_lambda': 0.0004756212554795866}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:16,855] Trial 42 finished with value: 0.6246087038594063 and parameters: {'learning_rate': 0.04107193295956905, 'max_depth': 8, 'min_child_weight': 3.400175589421988, 'subsample': 0.8764930750525415, 'colsample_bytree': 0.7006631109995874, 'gamma': 1.0615750225598675, 'reg_alpha': 1.9172930817756324, 'reg_lambda': 0.00016320423619672038}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:28,880] Trial 43 finished with value: 0.6251757255446843 and parameters: {'learning_rate': 0.055510200957063334, 'max_depth': 8, 'min_child_weight': 4.178835149682532, 'subsample': 0.8969119166753936, 'colsample_bytree': 0.745800590156545, 'gamma': 0.008050105358543558, 'reg_alpha': 9.71746666648166, 'reg_lambda': 0.0007127925403382291}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:35,332] Trial 44 finished with value: 0.6236047178978409 and parameters: {'learning_rate': 0.07775815233150722, 'max_depth': 8, 'min_child_weight': 4.966700694211612, 'subsample': 0.8410462049393792, 'colsample_bytree': 0.7379531689132014, 'gamma': 1.2611999217956524, 'reg_alpha': 4.382111512964861, 'reg_lambda': 0.18651485735535875}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:42,180] Trial 45 finished with value: 0.633097007956973 and parameters: {'learning_rate': 0.05962420376359747, 'max_depth': 5, 'min_child_weight': 3.635141880652973, 'subsample': 0.7811046396543824, 'colsample_bytree': 0.7170693534272129, 'gamma': 1.1664271379939524, 'reg_alpha': 1.2303922502640539, 'reg_lambda': 0.0004032086807675136}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:50,537] Trial 46 finished with value: 0.6249572049601783 and parameters: {'learning_rate': 0.05031968442804142, 'max_depth': 5, 'min_child_weight': 2.823565930220462, 'subsample': 0.7790390007839519, 'colsample_bytree': 0.7269010010631523, 'gamma': 0.9281017741466631, 'reg_alpha': 0.23598542960840466, 'reg_lambda': 0.00032114900650441594}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:35:56,591] Trial 47 finished with value: 0.6202007975542767 and parameters: {'learning_rate': 0.11019676675443298, 'max_depth': 6, 'min_child_weight': 1.6684365275500759, 'subsample': 0.8113978123521884, 'colsample_bytree': 0.9377886777154115, 'gamma': 1.0623665078020748, 'reg_alpha': 1.5714992589578083, 'reg_lambda': 0.0021987418620730815}. Best is trial 16 with value: 0.6379247920784028.
[I 2026-04-15 10:36:02,896] Trial 48 finished with value: 0.6228475371773219 and parameters: {'learning_rate': 0.06847826939242974, 'max_depth': 5, 'min_child_weight': 7.510660736684067, 'subsample': 0.7570095168101112, 'colsample_bytree': 0.8747230937978419, 'gamma': 1.4972739941597846, 'reg_alpha': 2.8154972805934264, 'reg_lambda': 0.00010273688713009997}. Best is trial 16 with value: 0.6379247920784028.

[I 2026-04-15 10:41:06,514] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 10:41:14,109] Trial 0 finished with value: 0.6344958901424369 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6344958901424369.
[I 2026-04-15 10:41:25,995] Trial 1 finished with value: 0.6304976964539113 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.6344958901424369.
[I 2026-04-15 10:41:40,485] Trial 2 finished with value: 0.6355436834734819 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:42:08,039] Trial 3 finished with value: 0.6293609879643859 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:42:47,291] Trial 4 finished with value: 0.5712832667859528 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:43:42,703] Trial 5 finished with value: 0.6234137945140863 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:44:15,627] Trial 6 finished with value: 0.6192142727649657 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:44:57,545] Trial 7 finished with value: 0.6297944036745875 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 2 with value: 0.6355436834734819.
[I 2026-04-15 10:46:22,139] Trial 8 finished with value: 0.6370154479599848 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 8 with value: 0.6370154479599848.
[I 2026-04-15 10:46:46,009] Trial 9 finished with value: 0.6213984887787924 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 8 with value: 0.6370154479599848.
[I 2026-04-15 10:46:55,786] Trial 10 finished with value: 0.6281119369728402 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.040269472988759346, 'depth': 5, 'l2_leaf_reg': 19.004714025252888, 'random_strength': 0.9792716360184497, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.5356867120609548}. Best is trial 8 with value: 0.6370154479599848.
[I 2026-04-15 10:47:11,207] Trial 11 finished with value: 0.6375941563694594 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04214546166162773, 'depth': 6, 'l2_leaf_reg': 5.812688181554367, 'random_strength': 0.4258355123760916, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9184954129066811}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:47:25,396] Trial 12 finished with value: 0.6148100555431009 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.041147237192279744, 'depth': 6, 'l2_leaf_reg': 4.622476664743947, 'random_strength': 0.4708798248858636, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9654977274063041}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:47:38,198] Trial 13 finished with value: 0.6223131867328277 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.051352889842772705, 'depth': 5, 'l2_leaf_reg': 6.328670337364077, 'random_strength': 0.50302947653924, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 4.496476721795593}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:47:48,684] Trial 14 finished with value: 0.6288358775170895 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03152085797829968, 'depth': 5, 'l2_leaf_reg': 17.565695276339024, 'random_strength': 0.4858878265580449, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9102734222494313}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:48:36,771] Trial 15 finished with value: 0.6126240743460041 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12725930491366905, 'depth': 8, 'l2_leaf_reg': 3.6932245959097423, 'random_strength': 0.3436265401874141, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.6415269030630038}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:49:02,895] Trial 16 finished with value: 0.6163740118379429 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05219399788945581, 'depth': 7, 'l2_leaf_reg': 2.7092980418864854, 'random_strength': 0.5866822340476083, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.701396742550504}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:49:12,570] Trial 17 finished with value: 0.6238563906229427 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032137942695715176, 'depth': 5, 'l2_leaf_reg': 7.210465839556867, 'random_strength': 0.23738193481037873, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8702496427561192}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:49:40,626] Trial 18 finished with value: 0.6223326840271978 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11189147828063814, 'depth': 7, 'l2_leaf_reg': 11.95289733299506, 'random_strength': 0.4081870897171628, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 3.5312221489001256}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:49:54,807] Trial 19 finished with value: 0.6226192088375863 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.053587002000421255, 'depth': 6, 'l2_leaf_reg': 2.912724328492924, 'random_strength': 0.5469177849978002, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8508934521287036}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:50:59,780] Trial 20 finished with value: 0.6159188322693748 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030113924123459486, 'depth': 8, 'l2_leaf_reg': 6.182300867098616, 'random_strength': 0.7791644775697428, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9991197454058867}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:51:15,045] Trial 21 finished with value: 0.6217889382067451 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.041818259964804615, 'depth': 6, 'l2_leaf_reg': 7.656808334669259, 'random_strength': 0.39571386497587735, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7957715064837466}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:51:29,862] Trial 22 finished with value: 0.6113411782256344 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.056791088424435386, 'depth': 6, 'l2_leaf_reg': 14.573852901904033, 'random_strength': 0.0010084962427511224, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7778548319352842}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:51:43,901] Trial 23 finished with value: 0.6221830997663784 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04222686319554281, 'depth': 6, 'l2_leaf_reg': 8.704715933513809, 'random_strength': 0.29443175893952245, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8468954588321631}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:51:52,001] Trial 24 finished with value: 0.6183313872897719 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06484569491423892, 'depth': 5, 'l2_leaf_reg': 5.410215203028945, 'random_strength': 0.3966081683826013, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9242020396914479}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:52:27,382] Trial 25 finished with value: 0.6241741320024502 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03467044689036926, 'depth': 7, 'l2_leaf_reg': 10.390652731088192, 'random_strength': 0.24978592095225838, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7400551749174392}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:52:44,958] Trial 26 finished with value: 0.6319767708350228 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.024855886186666638, 'depth': 6, 'l2_leaf_reg': 13.896602659853123, 'random_strength': 0.6023358905414027, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2578643405925001}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:52:59,684] Trial 27 finished with value: 0.624058079247803 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.047400418865074186, 'depth': 6, 'l2_leaf_reg': 8.260309244424205, 'random_strength': 0.43507657562660407, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8364022233949757}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:53:29,392] Trial 28 finished with value: 0.6342913585112283 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06008533680278842, 'depth': 7, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.3192006958950435, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.772909581328503}. Best is trial 11 with value: 0.6375941563694594.
[I 2026-04-15 10:53:39,193] Trial 29 finished with value: 0.6406327750681131 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0684444686866155, 'depth': 4, 'l2_leaf_reg': 2.378432489616166, 'random_strength': 0.1818861310311614, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.752629070004311}. Best is trial 29 with value: 0.6406327750681131.
[I 2026-04-15 10:53:47,931] Trial 30 finished with value: 0.6273386340515913 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06231764186955658, 'depth': 4, 'l2_leaf_reg': 1.9971565247682472, 'random_strength': 0.14025985804542443, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.462478888697883}. Best is trial 29 with value: 0.6406327750681131.
[I 2026-04-15 10:54:04,514] Trial 31 finished with value: 0.6435558024749458 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03670607970467336, 'depth': 4, 'l2_leaf_reg': 1.6393184303854311, 'random_strength': 0.17813678238725061, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.156767885878672}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:54:20,455] Trial 32 finished with value: 0.6358113550391309 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.035454978058291516, 'depth': 4, 'l2_leaf_reg': 1.4923545273532828, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.049418489126781}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:54:36,319] Trial 33 finished with value: 0.6334826617212385 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.026813759026854726, 'depth': 4, 'l2_leaf_reg': 2.2109457065885105, 'random_strength': 0.09627743714523207, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.316151178183812}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:54:42,299] Trial 34 finished with value: 0.6408777766107214 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06765113436692416, 'depth': 4, 'l2_leaf_reg': 1.060939832170321, 'random_strength': 0.22335651929325434, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.3657134887670512}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:54:48,225] Trial 35 finished with value: 0.630449771804154 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0683060297849044, 'depth': 4, 'l2_leaf_reg': 1.0333857528995183, 'random_strength': 0.2081812525496025, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.090934777264305}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:54:54,150] Trial 36 finished with value: 0.624427862812764 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09608884882454823, 'depth': 4, 'l2_leaf_reg': 1.3781698482146965, 'random_strength': 0.010075175649263024, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.179212987218983}. Best is trial 31 with value: 0.6435558024749458.
[I 2026-04-15 10:55:00,217] Trial 37 finished with value: 0.6488976347642409 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08801519925220463, 'depth': 4, 'l2_leaf_reg': 1.2138181187999766, 'random_strength': 0.09951944635825333, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.89745123065362}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:11,817] Trial 38 finished with value: 0.6294857929101665 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0885398411686575, 'depth': 4, 'l2_leaf_reg': 1.2393779161051293, 'random_strength': 0.08706490592088004, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.994118671944463}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:17,678] Trial 39 finished with value: 0.6370134746770636 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14928291585261647, 'depth': 4, 'l2_leaf_reg': 1.8286053567805844, 'random_strength': 0.1275421055906685, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.024410976245158}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:24,794] Trial 40 finished with value: 0.6434776194308688 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07612577171614957, 'depth': 4, 'l2_leaf_reg': 1.2281591936269025, 'random_strength': 0.04447704585243033, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.585208478124145}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:31,254] Trial 41 finished with value: 0.6328052205164976 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07325527967389768, 'depth': 4, 'l2_leaf_reg': 1.2048505711130986, 'random_strength': 0.0551671728130135, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.561317567222147}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:37,991] Trial 42 finished with value: 0.6378829798534197 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08546018859288339, 'depth': 4, 'l2_leaf_reg': 1.6115497070455325, 'random_strength': 0.21828284722645125, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.590805721481734}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:44,539] Trial 43 finished with value: 0.6327180606038543 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10557634445703461, 'depth': 4, 'l2_leaf_reg': 1.189744373316671, 'random_strength': 0.057446246430111245, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.8561576327029776}. Best is trial 37 with value: 0.6488976347642409.
[I 2026-04-15 10:55:54,086] Trial 44 finished with value: 0.6326006696200837 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07259050469620511, 'depth': 5, 'l2_leaf_reg': 2.31803714131063, 'random_strength': 0.17668626861190728, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.2339505546445135}. Best is trial 37 with value: 0.6488976347642409.

                                        feature  importance
53       eye__sac_length_AOI_aggregated_Pos_min   10.029127
56    eye__sac_length_AOI_aggregated_Pos_median    9.779052
60        eye__sac_speed_AOI_aggregated_Pos_min    9.540814
206           eye__fix_duration_AOI_FD_Pos1_min    4.480646
276    eye__fix_duration_AOI_aggregated_Pos_min    3.895406
63     eye__sac_speed_AOI_aggregated_Pos_median    3.728141
54       eye__sac_length_AOI_aggregated_Pos_max    2.437045
38       eye__sac_speed_AOI_aggregated_Neg_mean    1.801476
541                              corr__umap_071    1.280923
263    eye__fix_duration_AOI_aggregated_Neg_sum    1.255980
490                              corr__umap_020    1.124639
175         eye__fix_duration_AOI_FD_Neg1_first    1.113786
4                           eye__sac_length_std    1.075792
563                              corr__umap_093    1.066217
55      eye__sac_length_AOI_aggregated_Pos_mean    1.007998
479                              corr__umap_009    0.993543
157                          eye__reg_speed_min    0.976984
37        eye__sac_speed_AOI_aggregated_Neg_max    0.952660
183           eye__fix_duration_AOI_FD_Neg1_sum    0.918327
504                              corr__umap_034    0.871303
530                              corr__umap_060    0.811175
16                      eye__sac_angle_to_x_max    0.781663
445  eye__rec_metric_euclidean_length_3_rho_500    0.762987
8                            eye__sac_speed_min    0.753760
512                              corr__umap_042    0.711343
29       eye__sac_length_AOI_aggregated_Neg_min    0.710218
168                      eye__fix_duration_mean    0.709749
531                              corr__umap_061    0.709295
283    eye__fix_duration_AOI_aggregated_Pos_sum    0.705353
484                              corr__umap_014    0.691264

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,False,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.403197,0.443771,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,NaN,0.541407,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.440106,0.486745,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,NaN,0.773737,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,False,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.403197,0.443771,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,NaN,0.541407,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.440106,0.486745,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,NaN,0.773737,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [6]:
text_cov_freq = _load_ftar_parquet(FTAR_FILES["cov_freq"])
print("cov_freq shape:", text_cov_freq.shape)
summary_cov_freq = run_ftar_set("cov_freq", text_cov_freq)
summary_cov_freq

cov_freq shape: (4442, 36296)
[cov_freq] ftar feature count after cleanup: 36295

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__ES__refitTEST
[cov_freq] rows missing after index match -> train: 1658, test: 160
[cov_freq] UMAP compression: train/test features 36295 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 11:00:52,723] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 11:00:56,443] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:01,176] Trial 1 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:05,824] Trial 2 finished with value: 0.40401640806135186 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:10,475] Trial 3 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:15,051] Trial 4 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:20,100] Trial 5 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:24,623] Trial 6 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:30,191] Trial 7 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:35,351] Trial 8 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:41,973] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:46,620] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 11:01:50,986] Trial 11 finished with value: 0.41139300788041955 and parameters: {'learning_rate': 0.1987511993802379, 'max_depth': 8, 'min_child_weight': 2.2044350854903803, 'subsample': 0.991678377353391, 'colsample_bytree': 0.701477667194265, 'gamma': 0.11220060164975498, 'reg_alpha': 9.196828714331065, 'reg_lambda': 0.00013386192543122697}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:01:55,468] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04051213471007428, 'max_depth': 3, 'min_child_weight': 3.1004044475431423, 'subsample': 0.9116162834383159, 'colsample_bytree': 0.7100901110198058, 'gamma': 0.374691275249477, 'reg_alpha': 0.0005436011712873391, 'reg_lambda': 4.172125626964391}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:01:59,844] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06975521665509983, 'max_depth': 4, 'min_child_weight': 2.5857453554799656, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.7826997023387571, 'gamma': 0.2823919717964273, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.0001174103512578146}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:08,032] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.020257525017712674, 'max_depth': 8, 'min_child_weight': 1.1157937296124318, 'subsample': 0.7004519003043, 'colsample_bytree': 0.7003207020625539, 'gamma': 0.6830924903905842, 'reg_alpha': 0.002676936711803986, 'reg_lambda': 0.00011048275234250265}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:12,565] Trial 15 finished with value: 0.4047803203900765 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 4, 'min_child_weight': 4.195345625812058, 'subsample': 0.9907425579887397, 'colsample_bytree': 0.7897604482170154, 'gamma': 1.3977616671674873, 'reg_alpha': 0.001955094662007128, 'reg_lambda': 0.010162408101986087}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:19,825] Trial 16 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 7, 'min_child_weight': 2.1597738241444584, 'subsample': 0.8338095484574592, 'colsample_bytree': 0.8433042355616011, 'gamma': 0.06976827241365269, 'reg_alpha': 0.00014577009772305112, 'reg_lambda': 1.2488822635985135}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:24,585] Trial 17 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05659842546484548, 'max_depth': 4, 'min_child_weight': 4.907699675577318, 'subsample': 0.9443578771723351, 'colsample_bytree': 0.7626074238548747, 'gamma': 0.43929064745793944, 'reg_alpha': 0.0136643465941052, 'reg_lambda': 0.007603935367473369}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:30,848] Trial 18 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09330137070176413, 'max_depth': 7, 'min_child_weight': 3.688774960542076, 'subsample': 0.8290666990399569, 'colsample_bytree': 0.8074213105844478, 'gamma': 0.8206422424187519, 'reg_alpha': 0.0009289817616571169, 'reg_lambda': 0.1605066867738566}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:35,280] Trial 19 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.13178891002152585, 'max_depth': 4, 'min_child_weight': 5.305281304001412, 'subsample': 0.9099968910969494, 'colsample_bytree': 0.8774490360677278, 'gamma': 1.326671916866274, 'reg_alpha': 1.181026400073092, 'reg_lambda': 0.0004618920269639538}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:41,414] Trial 20 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.042350163788700664, 'max_depth': 8, 'min_child_weight': 6.230828787225904, 'subsample': 0.8780617770831248, 'colsample_bytree': 0.7236108038570555, 'gamma': 0.20599457607451177, 'reg_alpha': 0.008476979473815158, 'reg_lambda': 0.021285788352892104}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:46,103] Trial 21 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.19386041513032823, 'max_depth': 8, 'min_child_weight': 1.8691073325470773, 'subsample': 0.9479766686179566, 'colsample_bytree': 0.7347166974655936, 'gamma': 0.040871923151762024, 'reg_alpha': 8.758512421731355, 'reg_lambda': 0.000486554246049936}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:52,015] Trial 22 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1605627425575188, 'max_depth': 8, 'min_child_weight': 1.5164482615272776, 'subsample': 0.9545428414591273, 'colsample_bytree': 0.7631107386738226, 'gamma': 0.5340103811959347, 'reg_alpha': 2.5972298395797493, 'reg_lambda': 0.0005964159525024359}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:02:58,906] Trial 23 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1519130167063966, 'max_depth': 7, 'min_child_weight': 2.732100449667236, 'subsample': 0.9315986153266105, 'colsample_bytree': 0.7218733741534957, 'gamma': 0.03242987132670705, 'reg_alpha': 3.785865215630281, 'reg_lambda': 0.002519345496638338}. Best is trial 11 with value: 0.41139300788041955.
[I 2026-04-15 11:03:05,130] Trial 24 finished with value: 0.4134080298786181 and parameters: {'learning_rate': 0.19547002838557048, 'max_depth': 8, 'min_child_weight': 1.9625025003282923, 'subsample': 0.9933471127726692, 'colsample_bytree': 0.8166399588819715, 'gamma': 0.26418535818823885, 'reg_alpha': 0.5532677670269095, 'reg_lambda': 0.000207980361711599}. Best is trial 24 with value: 0.4134080298786181.
[I 2026-04-15 11:03:12,880] Trial 25 finished with value: 0.4063216914650772 and parameters: {'learning_rate': 0.06636318016290889, 'max_depth': 7, 'min_child_weight': 2.084821802543143, 'subsample': 0.981843102889895, 'colsample_bytree': 0.8235789766500421, 'gamma': 0.3131509566731192, 'reg_alpha': 0.6077893727193293, 'reg_lambda': 0.00025284131635196753}. Best is trial 24 with value: 0.4134080298786181.
[I 2026-04-15 11:03:17,555] Trial 26 finished with value: 0.4085272795015442 and parameters: {'learning_rate': 0.19449136371610326, 'max_depth': 7, 'min_child_weight': 1.13977582343584, 'subsample': 0.9980748476895438, 'colsample_bytree': 0.8807007671624207, 'gamma': 0.7906550705443833, 'reg_alpha': 0.5272749430701484, 'reg_lambda': 0.0002610516228528517}. Best is trial 24 with value: 0.4134080298786181.
[I 2026-04-15 11:03:22,375] Trial 27 finished with value: 0.4267608351672932 and parameters: {'learning_rate': 0.1991293249334804, 'max_depth': 8, 'min_child_weight': 1.0259089053039858, 'subsample': 0.9974797182640591, 'colsample_bytree': 0.8807048922686844, 'gamma': 0.8859516444137383, 'reg_alpha': 0.07860376223499242, 'reg_lambda': 0.00020372135591437157}. Best is trial 27 with value: 0.4267608351672932.
[I 2026-04-15 11:03:27,679] Trial 28 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1355852907707668, 'max_depth': 8, 'min_child_weight': 1.3143486884578184, 'subsample': 0.9699899754850488, 'colsample_bytree': 0.9067869565016643, 'gamma': 1.2517727077677376, 'reg_alpha': 0.05838100706862524, 'reg_lambda': 0.00016632907016056207}. Best is trial 27 with value: 0.4267608351672932.
[I 2026-04-15 11:03:33,625] Trial 29 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.10327852888074186, 'max_depth': 8, 'min_child_weight': 1.2878695013966714, 'subsample': 0.9973660976693562, 'colsample_bytree': 0.9010813541306026, 'gamma': 0.8999809741962987, 'reg_alpha': 0.9643938488327151, 'reg_lambda': 0.003473118138692537}. Best is trial 27 with value: 0.4267608351672932.
[I 2026-04-15 11:03:39,114] Trial 30 finished with value: 0.4105063779997053 and parameters: {'learning_rate': 0.1486884265063221, 'max_depth': 7, 'min_child_weight': 1.0057927191748472, 'subsample': 0.9267184926463081, 'colsample_bytree': 0.8609757028064935, 'gamma': 0.5501587972518509, 'reg_alpha': 0.08423724350302751, 'reg_lambda': 0.00027619466391208325}. Best is trial 27 with value: 0.4267608351672932.
[I 2026-04-15 11:03:44,071] Trial 31 finished with value: 0.4421683810738485 and parameters: {'learning_rate': 0.19944628830207603, 'max_depth': 8, 'min_child_weight': 1.0744988852417214, 'subsample': 0.9684309733378741, 'colsample_bytree': 0.8628320613372197, 'gamma': 0.6038497474370403, 'reg_alpha': 0.07169622085099929, 'reg_lambda': 0.0002862844536005282}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:03:48,904] Trial 32 finished with value: 0.4142715250325125 and parameters: {'learning_rate': 0.19546202869034784, 'max_depth': 8, 'min_child_weight': 1.688288165278204, 'subsample': 0.9621058507206837, 'colsample_bytree': 0.8568049553696006, 'gamma': 0.6675922215341924, 'reg_alpha': 0.04784719294969013, 'reg_lambda': 0.0008149656461105079}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:03:54,038] Trial 33 finished with value: 0.4146658390233809 and parameters: {'learning_rate': 0.1731416672833259, 'max_depth': 8, 'min_child_weight': 1.580348094431297, 'subsample': 0.963581799336288, 'colsample_bytree': 0.8595756595297767, 'gamma': 0.9911824826440393, 'reg_alpha': 0.0498424369801216, 'reg_lambda': 0.0008874019210220807}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:03:59,207] Trial 34 finished with value: 0.41213798502010984 and parameters: {'learning_rate': 0.1703251725147414, 'max_depth': 8, 'min_child_weight': 1.5890894615156326, 'subsample': 0.9641459012287884, 'colsample_bytree': 0.861205016501931, 'gamma': 0.9685594641583312, 'reg_alpha': 0.04765448376445978, 'reg_lambda': 0.003736307584924066}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:05,294] Trial 35 finished with value: 0.41113292136192897 and parameters: {'learning_rate': 0.11284716605507222, 'max_depth': 7, 'min_child_weight': 1.0403824013872167, 'subsample': 0.8926369746155811, 'colsample_bytree': 0.9089902431555019, 'gamma': 0.6682714466926647, 'reg_alpha': 0.1335373950363431, 'reg_lambda': 0.001267013232411402}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:10,374] Trial 36 finished with value: 0.4094864612511671 and parameters: {'learning_rate': 0.16975998247110033, 'max_depth': 8, 'min_child_weight': 1.2669209087807813, 'subsample': 0.9348178699414703, 'colsample_bytree': 0.8587782479148381, 'gamma': 1.1325426526974884, 'reg_alpha': 0.016506432219678818, 'reg_lambda': 0.0008178423083891908}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:14,743] Trial 37 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.13901036356689667, 'max_depth': 7, 'min_child_weight': 1.452234921085347, 'subsample': 0.9602433384509764, 'colsample_bytree': 0.8944355082189511, 'gamma': 1.5304504518286581, 'reg_alpha': 0.04135659003653716, 'reg_lambda': 0.0010992700783496103}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:20,644] Trial 38 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08354875042775857, 'max_depth': 8, 'min_child_weight': 1.7399014374299748, 'subsample': 0.9714937095179497, 'colsample_bytree': 0.9163927780633612, 'gamma': 0.7410937579360405, 'reg_alpha': 0.24064412440734625, 'reg_lambda': 0.000504180699127236}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:25,630] Trial 39 finished with value: 0.4181274684675769 and parameters: {'learning_rate': 0.17580144457720978, 'max_depth': 6, 'min_child_weight': 1.1934003692950972, 'subsample': 0.917960927513387, 'colsample_bytree': 0.9280136591785035, 'gamma': 0.9620833532821518, 'reg_alpha': 0.00551511859211395, 'reg_lambda': 0.002150535265259932}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:30,564] Trial 40 finished with value: 0.40401640806135186 and parameters: {'learning_rate': 0.17000778412990897, 'max_depth': 5, 'min_child_weight': 1.1716669911394055, 'subsample': 0.9099721103469027, 'colsample_bytree': 0.9949496819331648, 'gamma': 0.9233572486618841, 'reg_alpha': 0.005526595806656708, 'reg_lambda': 0.006139369660112892}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:35,570] Trial 41 finished with value: 0.41622880183473543 and parameters: {'learning_rate': 0.15283761610243235, 'max_depth': 6, 'min_child_weight': 1.4364418493903965, 'subsample': 0.9779031221396919, 'colsample_bytree': 0.9280260636895895, 'gamma': 1.027731354170785, 'reg_alpha': 0.03020922939281284, 'reg_lambda': 0.0018616757765432734}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:40,398] Trial 42 finished with value: 0.4107811249118376 and parameters: {'learning_rate': 0.1486083364378018, 'max_depth': 6, 'min_child_weight': 1.419833040108903, 'subsample': 0.9810213742915963, 'colsample_bytree': 0.928563087048593, 'gamma': 1.1803238544096517, 'reg_alpha': 0.022456943945131414, 'reg_lambda': 0.0017595643053521456}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:45,265] Trial 43 finished with value: 0.4173415285279692 and parameters: {'learning_rate': 0.17556507163679438, 'max_depth': 6, 'min_child_weight': 1.228204163385599, 'subsample': 0.9255152664450703, 'colsample_bytree': 0.9589861891353739, 'gamma': 1.013653243298808, 'reg_alpha': 0.007132989685668254, 'reg_lambda': 0.014746004425473169}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:50,341] Trial 44 finished with value: 0.4219061987006302 and parameters: {'learning_rate': 0.12931119679034028, 'max_depth': 6, 'min_child_weight': 1.221412813365129, 'subsample': 0.9243213494658538, 'colsample_bytree': 0.9582389026508381, 'gamma': 1.0335397923482237, 'reg_alpha': 0.007620253781573891, 'reg_lambda': 0.014077026834357055}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:04:55,699] Trial 45 finished with value: 0.4122444429097776 and parameters: {'learning_rate': 0.10945523405375579, 'max_depth': 5, 'min_child_weight': 1.2045134542672453, 'subsample': 0.9377479460831434, 'colsample_bytree': 0.9622605370623223, 'gamma': 0.8699617973126834, 'reg_alpha': 0.003128595979578677, 'reg_lambda': 0.022367851496371837}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:05:01,051] Trial 46 finished with value: 0.42629324644823074 and parameters: {'learning_rate': 0.12910269236254038, 'max_depth': 6, 'min_child_weight': 1.0094436563009872, 'subsample': 0.9223455521880803, 'colsample_bytree': 0.9574043866704306, 'gamma': 1.2212516583383606, 'reg_alpha': 0.008961681891443387, 'reg_lambda': 0.01376428213639145}. Best is trial 31 with value: 0.4421683810738485.
[I 2026-04-15 11:05:06,033] Trial 47 finished with value: 0.41505740179566397 and parameters: {'learning_rate': 0.1253160806703145, 'max_depth': 6, 'min_child_weight': 1.0103635263870272, 'subsample': 0.8959869467722207, 'colsample_bytree': 0.9919497211970645, 'gamma': 1.5152725658077872, 'reg_alpha': 0.011927031517411963, 'reg_lambda': 0.07755010409498665}. Best is trial 31 with value: 0.4421683810738485.

[I 2026-04-15 11:09:17,473] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 11:09:21,463] Trial 0 finished with value: 0.4100978330246623 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4100978330246623.
[I 2026-04-15 11:09:30,159] Trial 1 finished with value: 0.434749654636571 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.434749654636571.
[I 2026-04-15 11:09:38,294] Trial 2 finished with value: 0.434660185026774 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.434749654636571.
[I 2026-04-15 11:09:51,839] Trial 3 finished with value: 0.4345720659072094 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.434749654636571.
[I 2026-04-15 11:10:12,273] Trial 4 finished with value: 0.47228195607349915 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:10:39,733] Trial 5 finished with value: 0.43934337627323855 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:10:53,199] Trial 6 finished with value: 0.43018582947753514 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:11:06,877] Trial 7 finished with value: 0.4138671516866351 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:11:35,725] Trial 8 finished with value: 0.4078259682843549 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:11:48,331] Trial 9 finished with value: 0.4358104756531237 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:11:52,751] Trial 10 finished with value: 0.43450554870429603 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:12:12,731] Trial 11 finished with value: 0.4686857839438393 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17040099770125652, 'depth': 8, 'l2_leaf_reg': 3.747473826638779, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12665706747865135}. Best is trial 4 with value: 0.47228195607349915.
[I 2026-04-15 11:12:32,148] Trial 12 finished with value: 0.48721375514905196 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 2.6880148841981213, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.566664895898511}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:12:52,424] Trial 13 finished with value: 0.4588363845384277 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 8, 'l2_leaf_reg': 2.3484710269750506, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9139832467937251}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:03,644] Trial 14 finished with value: 0.47579720842784295 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11980834084297441, 'depth': 7, 'l2_leaf_reg': 1.0042999777217867, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8424234616468694}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:10,253] Trial 15 finished with value: 0.4713331520945624 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12725930491366905, 'depth': 6, 'l2_leaf_reg': 1.0071882758063284, 'random_strength': 0.23672144820247215, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.1476548084452305}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:21,808] Trial 16 finished with value: 0.45471923561561 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11953437669362904, 'depth': 7, 'l2_leaf_reg': 3.1663540546289517, 'random_strength': 0.44687626268499, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.3806987663952288}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:33,413] Trial 17 finished with value: 0.4574057388509638 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14157156246981956, 'depth': 7, 'l2_leaf_reg': 5.8894197277172315, 'random_strength': 0.3491923639077172, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8726177698897599}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:37,948] Trial 18 finished with value: 0.42696315771311855 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1996505344510532, 'depth': 5, 'l2_leaf_reg': 1.3551419426021614, 'random_strength': 0.1258796785631721, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.284517710941218}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:45,154] Trial 19 finished with value: 0.4398734108081159 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05192304823622825, 'depth': 6, 'l2_leaf_reg': 2.5723035201874382, 'random_strength': 0.23645789166165657, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8374910500132723}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:13:56,483] Trial 20 finished with value: 0.4356363542770516 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10119831386826487, 'depth': 7, 'l2_leaf_reg': 1.2431144787695307, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.998285320419604}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:14:16,652] Trial 21 finished with value: 0.46350183004200696 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15998210691397624, 'depth': 8, 'l2_leaf_reg': 1.5475718306407078, 'random_strength': 0.09228499007134987, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.770556495084043}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:14:38,381] Trial 22 finished with value: 0.46371625180438336 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19883740207438072, 'depth': 8, 'l2_leaf_reg': 2.0126194501391597, 'random_strength': 0.04826458051977403, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7980142375002377}. Best is trial 12 with value: 0.48721375514905196.
[I 2026-04-15 11:15:01,871] Trial 23 finished with value: 0.4946189192171385 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15167264810235057, 'depth': 8, 'l2_leaf_reg': 2.941102588746366, 'random_strength': 0.20810944119002692, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7283153640267026}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:15:14,566] Trial 24 finished with value: 0.4457127949826903 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10472276233779726, 'depth': 7, 'l2_leaf_reg': 2.8509881546339626, 'random_strength': 0.23654868852226474, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6123594185025829}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:15:37,095] Trial 25 finished with value: 0.45726012038445996 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14709462945726684, 'depth': 8, 'l2_leaf_reg': 4.97887357414659, 'random_strength': 0.3829453678986238, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8462690158522272}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:15:48,773] Trial 26 finished with value: 0.4542991969722697 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11387389337372075, 'depth': 7, 'l2_leaf_reg': 3.2240909003630547, 'random_strength': 0.17242660362631723, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.3380733010652666}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:16:10,799] Trial 27 finished with value: 0.45892060833997284 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1455344240651982, 'depth': 8, 'l2_leaf_reg': 6.6600089767996, 'random_strength': 0.3018197145880269, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7084792737250603}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:16:22,927] Trial 28 finished with value: 0.4554922765495335 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06008533680278842, 'depth': 7, 'l2_leaf_reg': 2.1836165321118766, 'random_strength': 0.20857804368567068, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7787652095657293}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:16:48,088] Trial 29 finished with value: 0.44817072738142644 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0895870455901601, 'depth': 8, 'l2_leaf_reg': 3.415599526672519, 'random_strength': 0.12318017062915879, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.8096017578766155}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:16:53,411] Trial 30 finished with value: 0.43587392780551587 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06835657496404426, 'depth': 5, 'l2_leaf_reg': 2.6663457125495493, 'random_strength': 0.5365856760216451, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8165114308328553}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:17:14,416] Trial 31 finished with value: 0.47764818729228187 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1694156593110742, 'depth': 8, 'l2_leaf_reg': 1.8127544382051772, 'random_strength': 0.08925967733997417, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7422921733460072}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:17:34,963] Trial 32 finished with value: 0.4617752852199857 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15605061104139822, 'depth': 8, 'l2_leaf_reg': 1.3383556705773796, 'random_strength': 0.15317377884162475, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6614235826079401}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:17:55,576] Trial 33 finished with value: 0.46511884068045545 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1353922078095111, 'depth': 8, 'l2_leaf_reg': 2.1708212527978965, 'random_strength': 0.06195519789476211, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7303827932976658}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:17:59,117] Trial 34 finished with value: 0.4351596200384166 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19874545520873763, 'depth': 4, 'l2_leaf_reg': 1.8670091116745628, 'random_strength': 0.17469312340710008, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7990950135665648}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:18:12,451] Trial 35 finished with value: 0.4609891081209152 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 7, 'l2_leaf_reg': 1.1889757823553984, 'random_strength': 0.28651227910534316, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8885693053057665}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:18:37,472] Trial 36 finished with value: 0.4395382088811839 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0369055818079162, 'depth': 8, 'l2_leaf_reg': 1.52322499598893, 'random_strength': 0.08740194506482135, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6662675662319603}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:18:49,721] Trial 37 finished with value: 0.4568729874800381 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16749577259077497, 'depth': 7, 'l2_leaf_reg': 4.148779172342017, 'random_strength': 0.005853102536276536, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7809074342113056}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:19:12,230] Trial 38 finished with value: 0.4619588716271621 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11245521474139239, 'depth': 8, 'l2_leaf_reg': 1.7332512630968677, 'random_strength': 0.40594867315453076, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7336769979416427}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:19:19,807] Trial 39 finished with value: 0.4227751255198481 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09194171615055761, 'depth': 6, 'l2_leaf_reg': 2.894827694294313, 'random_strength': 0.12259529707895547, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.0281886708000636}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:19:40,187] Trial 40 finished with value: 0.46358242752543616 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17574991873057655, 'depth': 8, 'l2_leaf_reg': 10.06795044277389, 'random_strength': 0.20267271779947635, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8324162627447482}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:19:59,862] Trial 41 finished with value: 0.4781608716086815 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18146436762340198, 'depth': 8, 'l2_leaf_reg': 1.6734482808122666, 'random_strength': 0.04958680005243369, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7496908099556138}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:20:20,272] Trial 42 finished with value: 0.4618637275438754 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15232083841101737, 'depth': 8, 'l2_leaf_reg': 2.446491649581778, 'random_strength': 0.05421931341945956, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7181468961038728}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:20:40,042] Trial 43 finished with value: 0.4915461500881129 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1818137591611776, 'depth': 8, 'l2_leaf_reg': 1.144110728134095, 'random_strength': 0.09710300920509662, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7524994992623202}. Best is trial 23 with value: 0.4946189192171385.
[I 2026-04-15 11:21:00,242] Trial 44 finished with value: 0.4614532874417605 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18663046515975554, 'depth': 8, 'l2_leaf_reg': 1.4355959315947464, 'random_strength': 0.03996058284850831, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6848139865218006}. Best is trial 23 with value: 0.4946189192171385.

                                     feature  importance
495                       cov_freq__umap_025    0.180803
511                       cov_freq__umap_041    0.164715
545                       cov_freq__umap_075    0.129754
54    eye__sac_length_AOI_aggregated_Pos_max    0.094156
542                       cov_freq__umap_072    0.091342
20              eye__sac_angle_to_x_kurtosis    0.088955
46   eye__sac_length_AOI_aggregated_None_sum    0.067295
18                eye__sac_angle_to_x_median    0.055916
362     eye__lyapunov_exponent_m_4_tau_2_T_1    0.051117
151                     eye__reg_length_mean    0.040114
412       eye__corm_euclidean_length_2_rho_5    0.035832
21                  eye__sac_angle_to_x_skew    0.000000
22                eye__sac_angle_between_min    0.000000
23                eye__sac_angle_between_max    0.000000
24               eye__sac_angle_between_mean    0.000000
25             eye__sac_angle_between_median    0.000000
513                       cov_freq__umap_043    0.000000
57    eye__sac_length_AOI_aggregated_Pos_std    0.000000
537                       cov_freq__umap_067    0.000000
33    eye__sac_length_AOI_aggregated_Neg_std    0.000000
569                       cov_freq__umap_099    0.000000
0                        eye__sac_length_min    0.000000
1                        eye__sac_length_max    0.000000
2                       eye__sac_length_mean    0.000000
3                     eye__sac_length_median    0.000000
4                        eye__sac_length_std    0.000000
5                        eye__sac_length_sum    0.000000
6                   eye__sac_length_kurtosis    0.000000
7                       eye__sac_length_skew    0.000000
26                eye__sac_angle_between_std    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.50596
              precision    recall  f1-score   support

           0       0.69      0.95      0.80       227
           1       0.56      0.13      0.21       109

    accuracy                           0.68       336
   macro avg       0.63      0.54      0.51       336
weighted avg       0.65      0.68      0.61       336

Confusion matrix:
 [[216  11]
 [ 95  14]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+cov_freq__target=match_mismatch__problem=binary__feat=all_features+cov_freq__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
206            eye__fix_duration_AOI_FD_Pos1_min    4.304073
160                        eye__reg_speed_median    3.963441
56     eye__sac_length_AOI_aggregated_Pos_median    3.422764
12                            eye__sac_speed_std    3.076417
535                           cov_freq__umap_065    3.056559
526                           cov_freq__umap_056    2.726664
511                           cov_freq__umap_041    2.715421
464                                eye__imf0_min    2.592311
499                           cov_freq__umap_029    2.380854
569                           cov_freq__umap_099    2.245898
562                           cov_freq__umap_092    2.226782
563                           cov_freq__umap_093    1.990953
473                           cov_freq__umap_003    1.957467
270    eye__fix_duration_AOI_aggregated_None_std    1.956660
277     eye__fix_duration_AOI_aggregated_Pos_max    1.933717
188           eye__fix_duration_AOI_FD_None_mean    1.929804
166                        eye__fix_duration_min    1.838437
539                           cov_freq__umap_069    1.822152
516                           cov_freq__umap_046    1.777674
541                           cov_freq__umap_071    1.774676
161                           eye__reg_speed_std    1.764466
207            eye__fix_duration_AOI_FD_Pos1_max    1.609578
57        eye__sac_length_AOI_aggregated_Pos_std    1.583313
393    eye__rec_metric_euclidean_length_1_rho_25    1.557449
497                           cov_freq__umap_027    1.541632
66     eye__sac_length_AOI_aggregated_Target_max    1.535567
17                      eye__sac_angle_to_x_mean    1.487471
259  eye__fix_duration_AOI_aggregated_Neg_median    1.386473
19                       eye__sac_angle_to_x_std    1.385459
42       eye__sac_length_AOI_aggregated_None_max    1.375734

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST
[cov_freq] rows missing after index match -> train: 1658, test: 160
[cov_freq] UMAP compression: train/test features 36295 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 11:26:41,785] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+cov_freq__target=match_mismatch__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 11:26:47,961] Trial 0 finished with value: 0.5316120077640716 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:26:54,835] Trial 1 finished with value: 0.5260574447169221 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:02,837] Trial 2 finished with value: 0.5002789711598077 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:09,389] Trial 3 finished with value: 0.5033537078302239 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:15,111] Trial 4 finished with value: 0.5022519782697109 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:23,789] Trial 5 finished with value: 0.5150634249581534 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:28,747] Trial 6 finished with value: 0.5286038688797445 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:38,763] Trial 7 finished with value: 0.5177345415182508 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:44,584] Trial 8 finished with value: 0.5198394688122776 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:27:55,910] Trial 9 finished with value: 0.4985713868957504 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.5316120077640716.
[I 2026-04-15 11:28:02,346] Trial 10 finished with value: 0.5358764259326549 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 10 with value: 0.5358764259326549.
[I 2026-04-15 11:28:08,808] Trial 11 finished with value: 0.5429229832707962 and parameters: {'learning_rate': 0.050044732845096966, 'max_depth': 3, 'min_child_weight': 2.350150709689129, 'subsample': 0.7005578980255978, 'colsample_bytree': 0.8260781920528338, 'gamma': 0.5892553864010996, 'reg_alpha': 0.00014565587242354827, 'reg_lambda': 6.69351503516026}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:15,133] Trial 12 finished with value: 0.5361407955508987 and parameters: {'learning_rate': 0.06208010340123145, 'max_depth': 3, 'min_child_weight': 2.2037205970521683, 'subsample': 0.7008546103358549, 'colsample_bytree': 0.8389293880967175, 'gamma': 0.5196431454502325, 'reg_alpha': 0.000107858142176364, 'reg_lambda': 8.615341223564362}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:21,800] Trial 13 finished with value: 0.5178070334756271 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 3, 'min_child_weight': 1.0715833151496479, 'subsample': 0.7024129757389838, 'colsample_bytree': 0.8446192431123963, 'gamma': 0.7494733516705131, 'reg_alpha': 0.0006082188957755501, 'reg_lambda': 9.723758911933414}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:30,008] Trial 14 finished with value: 0.5291669784853407 and parameters: {'learning_rate': 0.03499172192077341, 'max_depth': 4, 'min_child_weight': 2.3994263689917066, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8097524232703589, 'gamma': 1.3675976641364822, 'reg_alpha': 0.00010017548790843929, 'reg_lambda': 1.186084379755129}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:37,459] Trial 15 finished with value: 0.531364870626198 and parameters: {'learning_rate': 0.020864422478061324, 'max_depth': 3, 'min_child_weight': 2.3243675044115597, 'subsample': 0.7535351961542895, 'colsample_bytree': 0.8782698102844885, 'gamma': 0.47492654949154745, 'reg_alpha': 0.002121623849007047, 'reg_lambda': 0.00016599250040776937}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:44,430] Trial 16 finished with value: 0.5329080044665848 and parameters: {'learning_rate': 0.08133394897193019, 'max_depth': 4, 'min_child_weight': 4.725860382448061, 'subsample': 0.8252173406848475, 'colsample_bytree': 0.8864398267989758, 'gamma': 0.8161570464934507, 'reg_alpha': 0.0006351096570398502, 'reg_lambda': 0.21122536547705148}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:50,829] Trial 17 finished with value: 0.5251303274468557 and parameters: {'learning_rate': 0.06149160275364805, 'max_depth': 3, 'min_child_weight': 1.981108916265279, 'subsample': 0.7017942926484083, 'colsample_bytree': 0.80151485840394, 'gamma': 1.2776895814091094, 'reg_alpha': 0.0046933992254068165, 'reg_lambda': 2.5310996823984957}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:28:57,710] Trial 18 finished with value: 0.5109144770530734 and parameters: {'learning_rate': 0.11910762396897277, 'max_depth': 4, 'min_child_weight': 1.3532179397893382, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.8281766495309447, 'gamma': 0.5984508617677521, 'reg_alpha': 0.00024395878500981365, 'reg_lambda': 0.011397783591272139}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:03,880] Trial 19 finished with value: 0.5380341742128096 and parameters: {'learning_rate': 0.0420244224436012, 'max_depth': 3, 'min_child_weight': 2.7432309718254366, 'subsample': 0.8202106492457472, 'colsample_bytree': 0.7832779407298713, 'gamma': 0.26428316665266394, 'reg_alpha': 0.0018182844319750153, 'reg_lambda': 0.345480884752595}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:11,452] Trial 20 finished with value: 0.5320499994316451 and parameters: {'learning_rate': 0.039198559458125344, 'max_depth': 4, 'min_child_weight': 3.1024256236840917, 'subsample': 0.8207531213984746, 'colsample_bytree': 0.780271265095069, 'gamma': 0.2553983244669355, 'reg_alpha': 0.0024730855611709364, 'reg_lambda': 0.5032017172116782}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:18,598] Trial 21 finished with value: 0.5363746731203733 and parameters: {'learning_rate': 0.026386668182949408, 'max_depth': 3, 'min_child_weight': 2.755433806990079, 'subsample': 0.7492159285349653, 'colsample_bytree': 0.7111774891106754, 'gamma': 0.5346605135886338, 'reg_alpha': 0.0006559879975896574, 'reg_lambda': 3.1635654223760064}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:25,733] Trial 22 finished with value: 0.5365249233025945 and parameters: {'learning_rate': 0.027084408894731224, 'max_depth': 3, 'min_child_weight': 3.1496366448655, 'subsample': 0.7525082898498494, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.30514921669494177, 'reg_alpha': 0.0009355071752904607, 'reg_lambda': 3.1329264302009507}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:33,460] Trial 23 finished with value: 0.5180034507573521 and parameters: {'learning_rate': 0.026200565694058684, 'max_depth': 4, 'min_child_weight': 3.824967017262543, 'subsample': 0.8120549145865747, 'colsample_bytree': 0.7135335928479808, 'gamma': 0.06213286911592453, 'reg_alpha': 0.010269301617526256, 'reg_lambda': 0.2503662818064834}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:40,385] Trial 24 finished with value: 0.5086533899228148 and parameters: {'learning_rate': 0.02730478226847213, 'max_depth': 3, 'min_child_weight': 6.478267349579329, 'subsample': 0.8690694010662794, 'colsample_bytree': 0.7023486227822291, 'gamma': 0.3089394734487947, 'reg_alpha': 0.0014595940670404735, 'reg_lambda': 2.4831472624788473}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:48,523] Trial 25 finished with value: 0.5224122938324662 and parameters: {'learning_rate': 0.0435181996709016, 'max_depth': 4, 'min_child_weight': 2.886716357948056, 'subsample': 0.7676213351297835, 'colsample_bytree': 0.7675631553282025, 'gamma': 0.7322756209708934, 'reg_alpha': 0.0003906189806493824, 'reg_lambda': 1.439723636136592}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:29:55,631] Trial 26 finished with value: 0.5306969028013913 and parameters: {'learning_rate': 0.029942549769412755, 'max_depth': 3, 'min_child_weight': 4.608951502252057, 'subsample': 0.7412380949511221, 'colsample_bytree': 0.8624635675981338, 'gamma': 0.20646138026113428, 'reg_alpha': 0.0014634880017205907, 'reg_lambda': 0.01451051492780337}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:30:11,206] Trial 27 finished with value: 0.5201385971249084 and parameters: {'learning_rate': 0.03809013058235464, 'max_depth': 8, 'min_child_weight': 1.6502011769864728, 'subsample': 0.7991645907677112, 'colsample_bytree': 0.9065156424741195, 'gamma': 0.3554295101027829, 'reg_alpha': 0.008078679325978612, 'reg_lambda': 1.074574736194185}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:30:21,800] Trial 28 finished with value: 0.5272629620549778 and parameters: {'learning_rate': 0.023855359111774086, 'max_depth': 5, 'min_child_weight': 3.7414781115363427, 'subsample': 0.7306490972370543, 'colsample_bytree': 0.8153726813894505, 'gamma': 0.8853577169677164, 'reg_alpha': 0.0012196534443198498, 'reg_lambda': 4.51090388826255}. Best is trial 11 with value: 0.5429229832707962.
[I 2026-04-15 11:30:28,997] Trial 29 finished with value: 0.5558533625021399 and parameters: {'learning_rate': 0.042634179509602715, 'max_depth': 4, 'min_child_weight': 2.707961483998647, 'subsample': 0.8408583571389376, 'colsample_bytree': 0.7647077074682923, 'gamma': 0.1738773723776263, 'reg_alpha': 0.0002647876203665916, 'reg_lambda': 0.28241799609129575}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:30:36,120] Trial 30 finished with value: 0.5147263007746197 and parameters: {'learning_rate': 0.05398691879324222, 'max_depth': 4, 'min_child_weight': 1.9093370241355223, 'subsample': 0.8773340262279893, 'colsample_bytree': 0.7651413959503188, 'gamma': 0.6743259843349213, 'reg_alpha': 0.00024331859043336742, 'reg_lambda': 0.030409827945620478}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:30:42,192] Trial 31 finished with value: 0.5272471717475639 and parameters: {'learning_rate': 0.04559988543121766, 'max_depth': 3, 'min_child_weight': 2.7526228533146653, 'subsample': 0.8418175939367682, 'colsample_bytree': 0.734396534273658, 'gamma': 0.20206863423574867, 'reg_alpha': 0.0003095942550014522, 'reg_lambda': 0.29003838496053413}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:30:49,904] Trial 32 finished with value: 0.5192734051866452 and parameters: {'learning_rate': 0.04065818012014535, 'max_depth': 4, 'min_child_weight': 3.7985889635192005, 'subsample': 0.7627232339641239, 'colsample_bytree': 0.7836272557799999, 'gamma': 0.04130965395691069, 'reg_alpha': 0.0007126861454372167, 'reg_lambda': 5.2330693225521046}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:30:56,042] Trial 33 finished with value: 0.5082521984616566 and parameters: {'learning_rate': 0.030702335030257048, 'max_depth': 3, 'min_child_weight': 3.098619436150247, 'subsample': 0.911059983754244, 'colsample_bytree': 0.7543709342996241, 'gamma': 0.3950887165414151, 'reg_alpha': 0.00019782735099009083, 'reg_lambda': 1.63640794885607}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:01,740] Trial 34 finished with value: 0.5261209224359732 and parameters: {'learning_rate': 0.054850942845454456, 'max_depth': 3, 'min_child_weight': 3.436644971663213, 'subsample': 0.8322489891130437, 'colsample_bytree': 0.7251679526120088, 'gamma': 0.006512470824104832, 'reg_alpha': 0.0032921943598674093, 'reg_lambda': 0.05212543436565857}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:08,812] Trial 35 finished with value: 0.5070889536753069 and parameters: {'learning_rate': 0.07232728606482658, 'max_depth': 4, 'min_child_weight': 2.078197300357676, 'subsample': 0.8045748509888625, 'colsample_bytree': 0.7729430037597153, 'gamma': 0.15385842927586374, 'reg_alpha': 0.000951529625461263, 'reg_lambda': 0.5529145676429479}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:16,188] Trial 36 finished with value: 0.501481404053419 and parameters: {'learning_rate': 0.04439853986245573, 'max_depth': 7, 'min_child_weight': 2.609939622067598, 'subsample': 0.8577175281711679, 'colsample_bytree': 0.8009912401201056, 'gamma': 0.29322210774332713, 'reg_alpha': 9.849954646989671, 'reg_lambda': 0.13666740686389284}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:24,932] Trial 37 finished with value: 0.5259417967542114 and parameters: {'learning_rate': 0.037711079962347696, 'max_depth': 5, 'min_child_weight': 5.504413175371692, 'subsample': 0.7251431677393612, 'colsample_bytree': 0.8254144639383657, 'gamma': 0.4143290613955956, 'reg_alpha': 0.00897467502328814, 'reg_lambda': 0.7810624615566127}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:30,960] Trial 38 finished with value: 0.5198608891537683 and parameters: {'learning_rate': 0.03078297711781988, 'max_depth': 3, 'min_child_weight': 1.5663707394945419, 'subsample': 0.7741102856548034, 'colsample_bytree': 0.7874592245209546, 'gamma': 0.10583927251378811, 'reg_alpha': 0.07228981101866326, 'reg_lambda': 0.3678683888839882}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:36,768] Trial 39 finished with value: 0.498922038033403 and parameters: {'learning_rate': 0.08945091316282008, 'max_depth': 5, 'min_child_weight': 4.390998958183555, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.755758383108379, 'gamma': 0.9620833532821518, 'reg_alpha': 0.00036526453276668316, 'reg_lambda': 0.10722925155210564}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:42,953] Trial 40 finished with value: 0.5244081611833938 and parameters: {'learning_rate': 0.04738797388594741, 'max_depth': 3, 'min_child_weight': 1.7407295439018735, 'subsample': 0.8806305088866302, 'colsample_bytree': 0.8595204287894501, 'gamma': 0.610144992344785, 'reg_alpha': 0.004159633636509053, 'reg_lambda': 3.774898252695784}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:49,827] Trial 41 finished with value: 0.5425395336424024 and parameters: {'learning_rate': 0.023780990846128353, 'max_depth': 3, 'min_child_weight': 2.657885567398747, 'subsample': 0.7486596626039165, 'colsample_bytree': 0.7190850653877843, 'gamma': 0.509317423004009, 'reg_alpha': 0.000436302496365971, 'reg_lambda': 2.4899736778633716}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:31:56,786] Trial 42 finished with value: 0.5322743429772955 and parameters: {'learning_rate': 0.023108952016890283, 'max_depth': 3, 'min_child_weight': 2.5789615261053274, 'subsample': 0.7219136099198403, 'colsample_bytree': 0.7246467560617968, 'gamma': 0.4638631385296243, 'reg_alpha': 0.00015466148330151592, 'reg_lambda': 2.13345902522135}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:32:02,183] Trial 43 finished with value: 0.5219245053310322 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 3, 'min_child_weight': 3.385746397161186, 'subsample': 0.7790760765830385, 'colsample_bytree': 0.7339313958915301, 'gamma': 0.27618524845177134, 'reg_alpha': 0.00043100520259055076, 'reg_lambda': 5.862656643094685}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:32:09,430] Trial 44 finished with value: 0.5151972275327984 and parameters: {'learning_rate': 0.03483924012824668, 'max_depth': 4, 'min_child_weight': 2.158872669477736, 'subsample': 0.755442051142499, 'colsample_bytree': 0.7480737451942991, 'gamma': 1.623837257243379, 'reg_alpha': 0.01558328667515757, 'reg_lambda': 0.9131669622028223}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:32:17,570] Trial 45 finished with value: 0.5188604678232376 and parameters: {'learning_rate': 0.02291040394680393, 'max_depth': 3, 'min_child_weight': 4.135514294637164, 'subsample': 0.7128142734481762, 'colsample_bytree': 0.9998084284754931, 'gamma': 0.15747077036204798, 'reg_alpha': 0.000148855465162241, 'reg_lambda': 5.7906268191725685}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:32:25,676] Trial 46 finished with value: 0.5376159881315008 and parameters: {'learning_rate': 0.0572110277330812, 'max_depth': 4, 'min_child_weight': 2.9776767726187043, 'subsample': 0.735384514605876, 'colsample_bytree': 0.7022723656277459, 'gamma': 0.36039615656232965, 'reg_alpha': 0.0018200470916817358, 'reg_lambda': 0.021807234029662535}. Best is trial 29 with value: 0.5558533625021399.
[I 2026-04-15 11:32:36,008] Trial 47 finished with value: 0.5045673367664059 and parameters: {'learning_rate': 0.05679120518361296, 'max_depth': 7, 'min_child_weight': 2.3658134895747684, 'subsample': 0.9423026329333816, 'colsample_bytree': 0.7169494131253785, 'gamma': 0.5382625155374917, 'reg_alpha': 0.002246172161774111, 'reg_lambda': 0.029212898073266498}. Best is trial 29 with value: 0.5558533625021399.

[I 2026-04-15 11:38:37,419] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 11:38:43,514] Trial 0 finished with value: 0.5018753778771093 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5018753778771093.
[I 2026-04-15 11:38:51,759] Trial 1 finished with value: 0.5000189213947986 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.5018753778771093.
[I 2026-04-15 11:39:03,700] Trial 2 finished with value: 0.4910313444551646 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 0 with value: 0.5018753778771093.
[I 2026-04-15 11:39:26,391] Trial 3 finished with value: 0.488795241338529 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 0 with value: 0.5018753778771093.
[I 2026-04-15 11:40:04,604] Trial 4 finished with value: 0.5128675960602411 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:40:49,627] Trial 5 finished with value: 0.47514091388706126 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:41:12,088] Trial 6 finished with value: 0.5040831406846367 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:41:32,430] Trial 7 finished with value: 0.472485375541103 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:42:27,614] Trial 8 finished with value: 0.5097629798223463 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:42:48,439] Trial 9 finished with value: 0.4785911952613401 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.5128675960602411.
[I 2026-04-15 11:42:54,587] Trial 10 finished with value: 0.5139655059573898 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 10 with value: 0.5139655059573898.
[I 2026-04-15 11:43:00,835] Trial 11 finished with value: 0.506969439025625 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.7651302031192428, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9606029800630493}. Best is trial 10 with value: 0.5139655059573898.
[I 2026-04-15 11:43:07,238] Trial 12 finished with value: 0.505024212933849 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1986542239767439, 'depth': 5, 'l2_leaf_reg': 2.0421230319613786, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9046688566042046}. Best is trial 10 with value: 0.5139655059573898.
[I 2026-04-15 11:43:13,425] Trial 13 finished with value: 0.4937231875721503 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13208847240962562, 'depth': 5, 'l2_leaf_reg': 1.027753711618717, 'random_strength': 0.9856534532602149, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8530372066106942}. Best is trial 10 with value: 0.5139655059573898.
[I 2026-04-15 11:43:19,939] Trial 14 finished with value: 0.49601853789399347 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12961433184836185, 'depth': 5, 'l2_leaf_reg': 3.03978208557599, 'random_strength': 0.5678297001888102, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7840310144908398}. Best is trial 10 with value: 0.5139655059573898.
[I 2026-04-15 11:43:58,130] Trial 15 finished with value: 0.520995817466074 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12725930491366905, 'depth': 8, 'l2_leaf_reg': 1.5418599470233827, 'random_strength': 0.006022682870209142, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9814769576437812}. Best is trial 15 with value: 0.520995817466074.
[I 2026-04-15 11:44:08,985] Trial 16 finished with value: 0.517100030096151 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11709680994139955, 'depth': 6, 'l2_leaf_reg': 3.120618306509048, 'random_strength': 0.3788754515751092, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9998908231041508}. Best is trial 15 with value: 0.520995817466074.
[I 2026-04-15 11:44:28,905] Trial 17 finished with value: 0.5231334152758447 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11854706354450929, 'depth': 7, 'l2_leaf_reg': 3.109945078567887, 'random_strength': 0.31789470615022025, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9950062078151276}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:44:49,711] Trial 18 finished with value: 0.4994585479913936 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05430284442415895, 'depth': 7, 'l2_leaf_reg': 5.403459727107064, 'random_strength': 0.23863894572732985, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8801136880630976}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:45:28,533] Trial 19 finished with value: 0.4980332310378974 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10757739273922036, 'depth': 8, 'l2_leaf_reg': 2.768356565197097, 'random_strength': 0.49024970086140673, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9905790567208196}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:45:48,090] Trial 20 finished with value: 0.49778484150039665 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14724478112125605, 'depth': 7, 'l2_leaf_reg': 1.213986904980901, 'random_strength': 0.09544030699775206, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.83987292510528}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:45:59,446] Trial 21 finished with value: 0.5003034098247291 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10631242425539685, 'depth': 6, 'l2_leaf_reg': 2.8952729508304147, 'random_strength': 0.3805494599868988, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9972631915775528}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:46:10,605] Trial 22 finished with value: 0.5152562018859594 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11169811014526448, 'depth': 6, 'l2_leaf_reg': 2.5274564822264427, 'random_strength': 0.395873951639028, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9473196792191455}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:46:52,101] Trial 23 finished with value: 0.4875704808236253 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03561052362226872, 'depth': 8, 'l2_leaf_reg': 3.7739920090565544, 'random_strength': 0.2432138786397907, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9991267676242424}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:47:12,101] Trial 24 finished with value: 0.5188500971700127 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1434370009702073, 'depth': 7, 'l2_leaf_reg': 6.301732208466098, 'random_strength': 0.007828742607430383, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9288057494320392}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:47:31,141] Trial 25 finished with value: 0.5161317790104971 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14670901152019752, 'depth': 7, 'l2_leaf_reg': 5.940626726376499, 'random_strength': 0.014489071604661459, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9051385720562648}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:47:52,081] Trial 26 finished with value: 0.4879079174953641 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09582614958464336, 'depth': 7, 'l2_leaf_reg': 6.913927876221443, 'random_strength': 0.15777996139260303, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:48:30,782] Trial 27 finished with value: 0.5052094813595838 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15303309743439142, 'depth': 8, 'l2_leaf_reg': 1.336540450689372, 'random_strength': 0.07734603036002391, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9436240233154792}. Best is trial 17 with value: 0.5231334152758447.
[I 2026-04-15 11:48:52,688] Trial 28 finished with value: 0.5264581206968959 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06008533680278842, 'depth': 7, 'l2_leaf_reg': 3.6768709903497356, 'random_strength': 0.22591277827104672, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9078783451466474}. Best is trial 28 with value: 0.5264581206968959.
[I 2026-04-15 11:49:38,640] Trial 29 finished with value: 0.49013539407859535 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0643446745372212, 'depth': 8, 'l2_leaf_reg': 2.365117572068508, 'random_strength': 0.23635569759060543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.682610778645282}. Best is trial 28 with value: 0.5264581206968959.
[I 2026-04-15 11:50:00,424] Trial 30 finished with value: 0.5108153635954209 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06573691855710372, 'depth': 7, 'l2_leaf_reg': 3.587851918518217, 'random_strength': 0.30318118964772667, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8357479921036259}. Best is trial 28 with value: 0.5264581206968959.
[I 2026-04-15 11:50:20,545] Trial 31 finished with value: 0.500466376901737 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09045969335711393, 'depth': 7, 'l2_leaf_reg': 5.273062021371838, 'random_strength': 0.12385946480670997, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9087993628261162}. Best is trial 28 with value: 0.5264581206968959.
[I 2026-04-15 11:50:43,418] Trial 32 finished with value: 0.49256038591052276 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03401288873980307, 'depth': 7, 'l2_leaf_reg': 2.1501111534350343, 'random_strength': 0.1721293319988055, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9666296283807014}. Best is trial 28 with value: 0.5264581206968959.
[I 2026-04-15 11:50:47,936] Trial 33 finished with value: 0.5306490803002506 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05559392944788707, 'depth': 4, 'l2_leaf_reg': 8.842899230943248, 'random_strength': 0.043178883052129406, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9252915476735867}. Best is trial 33 with value: 0.5306490803002506.
[I 2026-04-15 11:50:52,769] Trial 34 finished with value: 0.5037224692270941 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05389105548612988, 'depth': 4, 'l2_leaf_reg': 8.563974368022935, 'random_strength': 0.19184247337843252, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8720394514481397}. Best is trial 33 with value: 0.5306490803002506.
[I 2026-04-15 11:50:57,513] Trial 35 finished with value: 0.5209009477426881 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04186385138891059, 'depth': 4, 'l2_leaf_reg': 11.509110658693084, 'random_strength': 0.05586574233572972, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9711274116217343}. Best is trial 33 with value: 0.5306490803002506.
[I 2026-04-15 11:51:02,049] Trial 36 finished with value: 0.5317601408641699 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0710884880939419, 'depth': 4, 'l2_leaf_reg': 4.380519271875011, 'random_strength': 0.31344495452292204, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9226322517211356}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:08,322] Trial 37 finished with value: 0.5313390339580366 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.057988103009453805, 'depth': 4, 'l2_leaf_reg': 4.595465570670478, 'random_strength': 0.286057845507163, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.886657051931521}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:13,677] Trial 38 finished with value: 0.4555331767433783 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.057935982273818215, 'depth': 4, 'l2_leaf_reg': 4.493127072808744, 'random_strength': 0.4370060529224461, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.12221043743904225}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:18,900] Trial 39 finished with value: 0.5098384569673553 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07019146502965419, 'depth': 4, 'l2_leaf_reg': 19.441886532836552, 'random_strength': 0.5636043431146442, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8046309317048109}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:26,790] Trial 40 finished with value: 0.4990224410443757 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04352927432153813, 'depth': 4, 'l2_leaf_reg': 9.288793503446303, 'random_strength': 0.21490626995126025, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.4532051511681003}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:31,865] Trial 41 finished with value: 0.5184938840214988 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0856375828126003, 'depth': 4, 'l2_leaf_reg': 3.736848980974679, 'random_strength': 0.31232882396544864, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8823967098908903}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:37,636] Trial 42 finished with value: 0.5221828937625861 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03750880986339005, 'depth': 4, 'l2_leaf_reg': 12.819930574739152, 'random_strength': 0.2863159631397325, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9185064208923608}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:46,984] Trial 43 finished with value: 0.5050421051893186 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04729818783463902, 'depth': 5, 'l2_leaf_reg': 5.10060308633977, 'random_strength': 0.4371932748374113, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8890883743901445}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:51,689] Trial 44 finished with value: 0.5304105066133517 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07374685839979568, 'depth': 4, 'l2_leaf_reg': 7.372267359407542, 'random_strength': 0.3396922179030896, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8588891721571338}. Best is trial 36 with value: 0.5317601408641699.
[I 2026-04-15 11:51:57,125] Trial 45 finished with value: 0.545460274005615 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0740363271499583, 'depth': 4, 'l2_leaf_reg': 7.7094189513852065, 'random_strength': 0.3398421265143725, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8571120770578549}. Best is trial 45 with value: 0.545460274005615.

                                        feature  importance
213           eye__fix_duration_AOI_FD_Pos1_sum   13.141316
209        eye__fix_duration_AOI_FD_Pos1_median    6.126265
275  eye__fix_duration_AOI_aggregated_Pos_first    5.931482
0                           eye__sac_length_min    4.630632
55      eye__sac_length_AOI_aggregated_Pos_mean    3.928308
56    eye__sac_length_AOI_aggregated_Pos_median    3.188786
277    eye__fix_duration_AOI_aggregated_Pos_max    3.155938
214         eye__fix_duration_AOI_FD_Pos1_count    2.870244
270   eye__fix_duration_AOI_aggregated_None_std    2.855602
465                               eye__imf0_max    2.691688
511                          cov_freq__umap_041    2.580362
532                          cov_freq__umap_062    2.540352
389    eye__rec_metric_euclidean_length_1_rho_5    2.407698
314                    eye__incremental_entropy    2.310937
394          eye__det_euclidean_length_1_rho_25    2.105748
207           eye__fix_duration_AOI_FD_Pos1_max    1.912396
510                          cov_freq__umap_040    1.881332
390           eye__det_euclidean_length_1_rho_5    1.872356
470                          cov_freq__umap_000    1.772456
62       eye__sac_speed_AOI_aggregated_Pos_mean    1.677349
516                          cov_freq__umap_046    1.556185
267   eye__fix_duration_AOI_aggregated_None_max    1.524605
61        eye__sac_speed_AOI_aggregated_Pos_max    1.494834
449  eye__rec_metric_cityblock_length_1_rho_0.1    1.367037
266   eye__fix_duration_AOI_aggregated_None_min    1.275541
543                          cov_freq__umap_073    1.194339
557                          cov_freq__umap_087    1.044863
211      eye__fix_duration_AOI_FD_Pos1_kurtosis    1.039248
429    eye__rec_metric_euclidean_length_3_rho_5    1.013394
558                          cov_freq__umap_088    0.995750

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__ES__refitTEST
[cov_freq] rows missing after index match -> train: 1658, test: 160
[cov_freq] UMAP compression: train/test features 36295 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 11:56:17,770] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 11:56:22,536] Trial 0 finished with value: 0.49207259685298776 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.49207259685298776.
[I 2026-04-15 11:56:27,637] Trial 1 finished with value: 0.5071502449422153 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.5071502449422153.
[I 2026-04-15 11:56:33,968] Trial 2 finished with value: 0.5110894004816908 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5110894004816908.
[I 2026-04-15 11:56:39,188] Trial 3 finished with value: 0.5148308659704097 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.5148308659704097.
[I 2026-04-15 11:56:44,405] Trial 4 finished with value: 0.5163427539489776 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:56:50,074] Trial 5 finished with value: 0.49397993003734286 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:56:54,315] Trial 6 finished with value: 0.49153837968167435 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:00,672] Trial 7 finished with value: 0.50882341848828 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:05,598] Trial 8 finished with value: 0.5108301041643543 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:12,986] Trial 9 finished with value: 0.47128879993593936 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:17,645] Trial 10 finished with value: 0.5137526747488622 and parameters: {'learning_rate': 0.07985847190685645, 'max_depth': 8, 'min_child_weight': 5.7644975171451085, 'subsample': 0.8853830026900457, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4769827267624924, 'reg_alpha': 9.072541150259902, 'reg_lambda': 0.00015423477789158795}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:22,389] Trial 11 finished with value: 0.5068727347216688 and parameters: {'learning_rate': 0.0862754992306428, 'max_depth': 3, 'min_child_weight': 4.893468533033176, 'subsample': 0.8784378478970668, 'colsample_bytree': 0.9144574715071777, 'gamma': 0.7242576829236649, 'reg_alpha': 0.48049684627556033, 'reg_lambda': 5.975817202898658}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:27,015] Trial 12 finished with value: 0.4918674125628444 and parameters: {'learning_rate': 0.10757893000223027, 'max_depth': 7, 'min_child_weight': 5.2632762903781405, 'subsample': 0.9243952056242389, 'colsample_bytree': 0.999748196231103, 'gamma': 1.3956755955743716, 'reg_alpha': 0.0031841301424337977, 'reg_lambda': 0.005773580670715942}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:34,384] Trial 13 finished with value: 0.48166447497895937 and parameters: {'learning_rate': 0.06780079909653602, 'max_depth': 7, 'min_child_weight': 2.420835308313142, 'subsample': 0.8350053333721464, 'colsample_bytree': 0.9094278323229135, 'gamma': 0.7894168958301386, 'reg_alpha': 0.10275121533761483, 'reg_lambda': 0.8281558812990174}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:39,090] Trial 14 finished with value: 0.5076415175041378 and parameters: {'learning_rate': 0.11488821569781363, 'max_depth': 4, 'min_child_weight': 4.073016164806964, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8188354553909843, 'gamma': 1.9387835779506257, 'reg_alpha': 0.0001096145847994451, 'reg_lambda': 0.00011408402258979523}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:44,939] Trial 15 finished with value: 0.4972157742621994 and parameters: {'learning_rate': 0.13415544376201127, 'max_depth': 7, 'min_child_weight': 6.771844821510169, 'subsample': 0.9132837012381982, 'colsample_bytree': 0.9440515982716028, 'gamma': 0.47492654949154745, 'reg_alpha': 0.9396761753066505, 'reg_lambda': 0.5176059396199313}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:49,470] Trial 16 finished with value: 0.5158966816274166 and parameters: {'learning_rate': 0.08434310219298471, 'max_depth': 4, 'min_child_weight': 2.3335435677797833, 'subsample': 0.9942231535523712, 'colsample_bytree': 0.8847916698490143, 'gamma': 1.261991344095485, 'reg_alpha': 3.8327319720355546, 'reg_lambda': 0.009915302349540684}. Best is trial 4 with value: 0.5163427539489776.
[I 2026-04-15 11:57:54,035] Trial 17 finished with value: 0.5275081971344643 and parameters: {'learning_rate': 0.061149133733632004, 'max_depth': 3, 'min_child_weight': 2.112826953049721, 'subsample': 0.9961433213081963, 'colsample_bytree': 0.8371000028968741, 'gamma': 1.34346049477661, 'reg_alpha': 4.787778353028104, 'reg_lambda': 0.01067222644338921}. Best is trial 17 with value: 0.5275081971344643.
[I 2026-04-15 11:57:58,575] Trial 18 finished with value: 0.49785123407986687 and parameters: {'learning_rate': 0.047133493042515864, 'max_depth': 3, 'min_child_weight': 1.115133317760315, 'subsample': 0.9416473564717913, 'colsample_bytree': 0.8270517440294102, 'gamma': 1.6815751245490034, 'reg_alpha': 9.388066261152048, 'reg_lambda': 0.0010934515247783838}. Best is trial 17 with value: 0.5275081971344643.
[I 2026-04-15 11:58:03,108] Trial 19 finished with value: 0.4847036798346349 and parameters: {'learning_rate': 0.06799059904591619, 'max_depth': 3, 'min_child_weight': 2.5482533059016648, 'subsample': 0.9033665812206422, 'colsample_bytree': 0.7914403814995906, 'gamma': 1.633286492050634, 'reg_alpha': 0.008200299091801781, 'reg_lambda': 0.01773658145071271}. Best is trial 17 with value: 0.5275081971344643.
[I 2026-04-15 11:58:08,921] Trial 20 finished with value: 0.50814904639886 and parameters: {'learning_rate': 0.05766350962985036, 'max_depth': 8, 'min_child_weight': 6.770640103900383, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.8546978685611346, 'gamma': 1.79227139487183, 'reg_alpha': 0.07517026813588769, 'reg_lambda': 0.0030260406883185482}. Best is trial 17 with value: 0.5275081971344643.
[I 2026-04-15 11:58:13,181] Trial 21 finished with value: 0.5163063991966129 and parameters: {'learning_rate': 0.07722594479447936, 'max_depth': 4, 'min_child_weight': 2.4401742194662948, 'subsample': 0.9982302654803459, 'colsample_bytree': 0.8879333089505856, 'gamma': 1.2817599691288482, 'reg_alpha': 4.053346763817064, 'reg_lambda': 0.0005205101800981133}. Best is trial 17 with value: 0.5275081971344643.
[I 2026-04-15 11:58:18,530] Trial 22 finished with value: 0.5276698245045681 and parameters: {'learning_rate': 0.03826067206698506, 'max_depth': 4, 'min_child_weight': 2.079593231552357, 'subsample': 0.9683045861270267, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.2961595009287767, 'reg_alpha': 2.7156566660035613, 'reg_lambda': 0.00032081520804360617}. Best is trial 22 with value: 0.5276698245045681.
[I 2026-04-15 11:58:23,447] Trial 23 finished with value: 0.5076947757950967 and parameters: {'learning_rate': 0.03168261847650606, 'max_depth': 3, 'min_child_weight': 1.6749268261964834, 'subsample': 0.9512577216871494, 'colsample_bytree': 0.7216570006376126, 'gamma': 1.4887249221128023, 'reg_alpha': 0.9853371164574694, 'reg_lambda': 0.00020631905734581768}. Best is trial 22 with value: 0.5276698245045681.
[I 2026-04-15 11:58:28,949] Trial 24 finished with value: 0.5162238704540434 and parameters: {'learning_rate': 0.036435304131606006, 'max_depth': 4, 'min_child_weight': 2.0161586987310134, 'subsample': 0.9724921034255848, 'colsample_bytree': 0.7023486227822291, 'gamma': 0.9966556622148346, 'reg_alpha': 0.2196992231413966, 'reg_lambda': 0.0004405356018041495}. Best is trial 22 with value: 0.5276698245045681.
[I 2026-04-15 11:58:34,077] Trial 25 finished with value: 0.489885387926404 and parameters: {'learning_rate': 0.024465026179982453, 'max_depth': 3, 'min_child_weight': 3.0265725834413866, 'subsample': 0.9683896630525253, 'colsample_bytree': 0.7748572958565145, 'gamma': 1.2399715138370655, 'reg_alpha': 0.6974254663669006, 'reg_lambda': 0.0021880774625223022}. Best is trial 22 with value: 0.5276698245045681.
[I 2026-04-15 11:58:40,276] Trial 26 finished with value: 0.5338780031878761 and parameters: {'learning_rate': 0.040751154982601165, 'max_depth': 5, 'min_child_weight': 1.481060898239613, 'subsample': 0.9278372773890367, 'colsample_bytree': 0.8276051552179774, 'gamma': 1.9991361650069521, 'reg_alpha': 4.3373633356651355, 'reg_lambda': 0.005137724955539497}. Best is trial 26 with value: 0.5338780031878761.
[I 2026-04-15 11:58:46,849] Trial 27 finished with value: 0.5087726286635788 and parameters: {'learning_rate': 0.04517011571923281, 'max_depth': 5, 'min_child_weight': 1.0370559903065504, 'subsample': 0.934596231430962, 'colsample_bytree': 0.8236307680411388, 'gamma': 0.9349153308086537, 'reg_alpha': 3.569384076062551, 'reg_lambda': 0.02717874819268702}. Best is trial 26 with value: 0.5338780031878761.
[I 2026-04-15 11:58:52,862] Trial 28 finished with value: 0.4997985050628898 and parameters: {'learning_rate': 0.026805001036413718, 'max_depth': 4, 'min_child_weight': 1.4028744259670443, 'subsample': 0.9725903926442387, 'colsample_bytree': 0.8041501353251997, 'gamma': 1.5297501673057345, 'reg_alpha': 9.040537119844055, 'reg_lambda': 0.16034642105255092}. Best is trial 26 with value: 0.5338780031878761.
[I 2026-04-15 11:59:00,521] Trial 29 finished with value: 0.5184710184927355 and parameters: {'learning_rate': 0.0386209526419916, 'max_depth': 5, 'min_child_weight': 1.3733623096462608, 'subsample': 0.8230102948768425, 'colsample_bytree': 0.8451823336023022, 'gamma': 0.3724630835625541, 'reg_alpha': 2.328589885812288, 'reg_lambda': 0.003473118138692537}. Best is trial 26 with value: 0.5338780031878761.
[I 2026-04-15 11:59:05,911] Trial 30 finished with value: 0.4998972085852724 and parameters: {'learning_rate': 0.0449308872846541, 'max_depth': 4, 'min_child_weight': 2.037495826448644, 'subsample': 0.9585635801069242, 'colsample_bytree': 0.7690132361827182, 'gamma': 1.1529499247077486, 'reg_alpha': 0.0004542590223045132, 'reg_lambda': 0.01732525070236055}. Best is trial 26 with value: 0.5338780031878761.
[I 2026-04-15 11:59:13,645] Trial 31 finished with value: 0.5495937766449598 and parameters: {'learning_rate': 0.04164658503470633, 'max_depth': 5, 'min_child_weight': 1.2881641719705264, 'subsample': 0.824282618034277, 'colsample_bytree': 0.8359220572228079, 'gamma': 0.48802453410318425, 'reg_alpha': 1.8333375082446854, 'reg_lambda': 0.003946086399599971}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:21,028] Trial 32 finished with value: 0.5356266980120359 and parameters: {'learning_rate': 0.0412346933648177, 'max_depth': 5, 'min_child_weight': 1.15471757953854, 'subsample': 0.8076377565295616, 'colsample_bytree': 0.8415666635502671, 'gamma': 0.5772879555541366, 'reg_alpha': 2.3968177759412126, 'reg_lambda': 0.0003231710435374535}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:28,304] Trial 33 finished with value: 0.4934160605325135 and parameters: {'learning_rate': 0.04049297918906098, 'max_depth': 5, 'min_child_weight': 1.2030724816881486, 'subsample': 0.8194658349529976, 'colsample_bytree': 0.8067474171633603, 'gamma': 0.5335486352960812, 'reg_alpha': 1.4250623804772173, 'reg_lambda': 0.0002947826158570253}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:36,693] Trial 34 finished with value: 0.503245056018894 and parameters: {'learning_rate': 0.028256060074948238, 'max_depth': 5, 'min_child_weight': 1.5733736283335134, 'subsample': 0.8091873010353458, 'colsample_bytree': 0.8724391204889487, 'gamma': 0.2686417435507478, 'reg_alpha': 1.949287795585309, 'reg_lambda': 0.00048238327961234437}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:43,831] Trial 35 finished with value: 0.5139506974581607 and parameters: {'learning_rate': 0.05152674177080161, 'max_depth': 5, 'min_child_weight': 1.2581982541471624, 'subsample': 0.7550620418461711, 'colsample_bytree': 0.9089902431555019, 'gamma': 0.6672120431389712, 'reg_alpha': 0.42239084652585307, 'reg_lambda': 0.0009308297858153354}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:52,710] Trial 36 finished with value: 0.5010270719837447 and parameters: {'learning_rate': 0.029895695787053846, 'max_depth': 6, 'min_child_weight': 1.0322183345037281, 'subsample': 0.8561770282868674, 'colsample_bytree': 0.7061829270197956, 'gamma': 0.08251241726584713, 'reg_alpha': 2.5310225224005505, 'reg_lambda': 0.004550939727173345}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 11:59:59,879] Trial 37 finished with value: 0.505676108733375 and parameters: {'learning_rate': 0.04111276418364256, 'max_depth': 5, 'min_child_weight': 1.7705130450480544, 'subsample': 0.7149584062627203, 'colsample_bytree': 0.7817763735556841, 'gamma': 0.900708367998649, 'reg_alpha': 0.7273264330737715, 'reg_lambda': 0.00024126360196798777}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:06,770] Trial 38 finished with value: 0.5238376399937396 and parameters: {'learning_rate': 0.03626150873585642, 'max_depth': 4, 'min_child_weight': 1.464232889799646, 'subsample': 0.8671527252451583, 'colsample_bytree': 0.8680168245121774, 'gamma': 0.25904970051139764, 'reg_alpha': 5.716252301765448, 'reg_lambda': 0.0007904669695781634}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:15,284] Trial 39 finished with value: 0.4865433971319902 and parameters: {'learning_rate': 0.052579333132588474, 'max_depth': 6, 'min_child_weight': 1.2424194014488736, 'subsample': 0.802396424858698, 'colsample_bytree': 0.7483415406459965, 'gamma': 0.4347629309526847, 'reg_alpha': 1.2498425805251436, 'reg_lambda': 0.0014868095399897918}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:22,234] Trial 40 finished with value: 0.499257860454676 and parameters: {'learning_rate': 0.032942863934036094, 'max_depth': 5, 'min_child_weight': 1.8589920164494065, 'subsample': 0.7587221153137259, 'colsample_bytree': 0.8074282682624454, 'gamma': 0.17087782073154212, 'reg_alpha': 0.05713673641935538, 'reg_lambda': 0.00010593139374828276}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:27,066] Trial 41 finished with value: 0.5104359293812291 and parameters: {'learning_rate': 0.05802212300741485, 'max_depth': 4, 'min_child_weight': 2.1162092001602493, 'subsample': 0.9792400952443884, 'colsample_bytree': 0.8348515923865295, 'gamma': 1.3660325943139493, 'reg_alpha': 6.010256480942131, 'reg_lambda': 0.007719803664910767}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:32,334] Trial 42 finished with value: 0.5153757270747954 and parameters: {'learning_rate': 0.06068595995081692, 'max_depth': 3, 'min_child_weight': 1.5036974784173986, 'subsample': 0.9874802021582636, 'colsample_bytree': 0.8412192226011237, 'gamma': 0.5906888414009513, 'reg_alpha': 2.5756647404523103, 'reg_lambda': 0.03966256719950897}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:36,640] Trial 43 finished with value: 0.50074216863939 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 4, 'min_child_weight': 2.820211686720129, 'subsample': 0.9531178083712146, 'colsample_bytree': 0.8953367384762816, 'gamma': 0.8319352118895227, 'reg_alpha': 4.964890438807177, 'reg_lambda': 0.01671138999350419}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:43,046] Trial 44 finished with value: 0.5203067593472801 and parameters: {'learning_rate': 0.049045149403517334, 'max_depth': 5, 'min_child_weight': 1.1524690635469177, 'subsample': 0.7344289640494281, 'colsample_bytree': 0.8621710913336708, 'gamma': 1.823412486403801, 'reg_alpha': 0.3329848051440553, 'reg_lambda': 0.002243950770002544}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:50,335] Trial 45 finished with value: 0.5043849371872848 and parameters: {'learning_rate': 0.043438416936828164, 'max_depth': 6, 'min_child_weight': 1.819471125990546, 'subsample': 0.8304818510792629, 'colsample_bytree': 0.7945761219069097, 'gamma': 1.1336447534878473, 'reg_alpha': 1.6921448531902226, 'reg_lambda': 0.010160741346698057}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:00:58,919] Trial 46 finished with value: 0.5237067476216087 and parameters: {'learning_rate': 0.02305028522227271, 'max_depth': 5, 'min_child_weight': 3.39990972049911, 'subsample': 0.7778795444888011, 'colsample_bytree': 0.8450629643035154, 'gamma': 1.607734189871911, 'reg_alpha': 6.962630784413505, 'reg_lambda': 0.005292030746761111}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:01:05,585] Trial 47 finished with value: 0.5223024406772555 and parameters: {'learning_rate': 0.03588564271371307, 'max_depth': 4, 'min_child_weight': 1.283419148445938, 'subsample': 0.802508502760264, 'colsample_bytree': 0.7542581767628094, 'gamma': 1.9784131431389906, 'reg_alpha': 0.5420534858537835, 'reg_lambda': 0.10356035800361164}. Best is trial 31 with value: 0.5495937766449598.
[I 2026-04-15 12:01:13,711] Trial 48 finished with value: 0.5121197225203347 and parameters: {'learning_rate': 0.040589192049704396, 'max_depth': 6, 'min_child_weight': 1.6401368402710703, 'subsample': 0.8816251092679699, 'colsample_bytree': 0.7239093536971478, 'gamma': 0.6980540850395062, 'reg_alpha': 3.012697359480711, 'reg_lambda': 0.06585094788522854}. Best is trial 31 with value: 0.5495937766449598.

[I 2026-04-15 12:06:26,830] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.41053
              precision    recall  f1-score   support

           0       0.70      1.00      0.82       234
           1       0.00      0.00      0.00       102

    accuracy                           0.70       336
   macro avg       0.35      0.50      0.41       336
weighted avg       0.49      0.70      0.57       336

Confusion matrix:
 [[234   0]
 [102   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 12:06:33,174] Trial 0 finished with value: 0.5417320535936276 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5417320535936276.
[I 2026-04-15 12:06:48,240] Trial 1 finished with value: 0.5590225082030562 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5590225082030562.
[I 2026-04-15 12:06:58,386] Trial 2 finished with value: 0.5652491992189868 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5652491992189868.
[I 2026-04-15 12:07:19,960] Trial 3 finished with value: 0.5674241558363002 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5674241558363002.
[I 2026-04-15 12:07:41,960] Trial 4 finished with value: 0.5721371038047105 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:08:18,306] Trial 5 finished with value: 0.5660232612210245 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:08:39,378] Trial 6 finished with value: 0.5625799812088768 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:09:12,640] Trial 7 finished with value: 0.5667110903953718 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:10:03,669] Trial 8 finished with value: 0.5566032663465745 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:10:20,166] Trial 9 finished with value: 0.5625278581733058 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:10:26,048] Trial 10 finished with value: 0.5652373702411415 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:10:39,289] Trial 11 finished with value: 0.569525409796078 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 4.651607675299369, 'random_strength': 0.016584038838684367, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:11:03,571] Trial 12 finished with value: 0.5408583884895876 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 3.672310184878952, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.870940447219903}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:11:16,916] Trial 13 finished with value: 0.5706107048044151 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13208847240962562, 'depth': 7, 'l2_leaf_reg': 2.629249930915953, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.820059186922468}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:11:25,014] Trial 14 finished with value: 0.5612882490927756 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13003443013168167, 'depth': 6, 'l2_leaf_reg': 2.2230390331395395, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7840310144908398}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:11:48,068] Trial 15 finished with value: 0.5689989310731194 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12261083637914576, 'depth': 8, 'l2_leaf_reg': 1.0071882758063284, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9814769576437812}. Best is trial 4 with value: 0.5721371038047105.
[I 2026-04-15 12:12:01,311] Trial 16 finished with value: 0.5831787178199239 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12541132626934667, 'depth': 7, 'l2_leaf_reg': 2.628776125513198, 'random_strength': 0.02326453979441673, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7477164624869977}. Best is trial 16 with value: 0.5831787178199239.
[I 2026-04-15 12:12:26,769] Trial 17 finished with value: 0.5616177248389378 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1145322909633287, 'depth': 8, 'l2_leaf_reg': 1.556193381333541, 'random_strength': 0.4440752281517034, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.719101211089318}. Best is trial 16 with value: 0.5831787178199239.
[I 2026-04-15 12:12:33,129] Trial 18 finished with value: 0.5592543221184965 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.048446327248394636, 'depth': 5, 'l2_leaf_reg': 2.8667690532687127, 'random_strength': 0.15152455165761566, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6323997965438325}. Best is trial 16 with value: 0.5831787178199239.
[I 2026-04-15 12:12:40,733] Trial 19 finished with value: 0.5872876604395809 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15360967997703137, 'depth': 6, 'l2_leaf_reg': 1.3850595279469555, 'random_strength': 0.24326289211871252, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.740183037299242}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:12:46,205] Trial 20 finished with value: 0.5648119950252242 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09992887483337173, 'depth': 5, 'l2_leaf_reg': 1.2599803398510183, 'random_strength': 0.2801932728527251, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.858916650731588}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:12:58,627] Trial 21 finished with value: 0.558521666569001 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15998210691397624, 'depth': 7, 'l2_leaf_reg': 1.5035438017276186, 'random_strength': 0.10096870525000862, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7629006891261123}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:06,353] Trial 22 finished with value: 0.5785391560300296 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14729540999804655, 'depth': 6, 'l2_leaf_reg': 2.556030426680802, 'random_strength': 0.08921948771016305, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7217265015665681}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:14,351] Trial 23 finished with value: 0.5556979337143144 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14305381880593007, 'depth': 6, 'l2_leaf_reg': 3.0138738663456595, 'random_strength': 0.23267373411813627, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6667647512677055}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:20,071] Trial 24 finished with value: 0.5644869914209005 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1035214530380136, 'depth': 5, 'l2_leaf_reg': 6.301732208466098, 'random_strength': 0.37344254210485806, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7310354777899185}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:28,998] Trial 25 finished with value: 0.5792665704249869 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05861482058870431, 'depth': 6, 'l2_leaf_reg': 2.2488779784007598, 'random_strength': 0.20143792932046273, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6038236269954007}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:38,179] Trial 26 finished with value: 0.5718692186596863 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.055004816800755855, 'depth': 6, 'l2_leaf_reg': 2.0956721701960217, 'random_strength': 0.5503482310108637, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:48,993] Trial 27 finished with value: 0.5693187832267388 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03242208040419976, 'depth': 6, 'l2_leaf_reg': 1.2967655120267307, 'random_strength': 0.21305887750282718, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6149842224280774}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:13:54,927] Trial 28 finished with value: 0.5650645646732162 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06008533680278842, 'depth': 5, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.38193374612803843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.671622942619512}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:15,108] Trial 29 finished with value: 0.5496245068704937 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06761672362686966, 'depth': 7, 'l2_leaf_reg': 2.044367577921873, 'random_strength': 0.5321765665717613, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:20,030] Trial 30 finished with value: 0.5695478087718714 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04016316099431266, 'depth': 4, 'l2_leaf_reg': 1.247146040730933, 'random_strength': 0.2551752190486368, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8995733732357349}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:27,546] Trial 31 finished with value: 0.5681169085808389 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14671168483313615, 'depth': 6, 'l2_leaf_reg': 2.4187704768156513, 'random_strength': 0.1045353719419699, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8023185903572889}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:35,062] Trial 32 finished with value: 0.571269432993486 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11246589613090105, 'depth': 6, 'l2_leaf_reg': 1.8814970927996852, 'random_strength': 0.08331812601279182, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7189436510819843}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:44,234] Trial 33 finished with value: 0.5750030789620799 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09250749359282726, 'depth': 6, 'l2_leaf_reg': 3.7462276042328817, 'random_strength': 0.17909073448160173, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6017374201182502}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:52,405] Trial 34 finished with value: 0.5692141841445624 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19933454554546226, 'depth': 6, 'l2_leaf_reg': 5.552041780882835, 'random_strength': 0.12693573066038266, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7728961148649075}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:14:58,552] Trial 35 finished with value: 0.565118516553372 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03582143096672128, 'depth': 5, 'l2_leaf_reg': 2.6571005970729904, 'random_strength': 0.21151683645978003, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6609081939681909}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:15:11,206] Trial 36 finished with value: 0.5789358955408693 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08660798925626853, 'depth': 7, 'l2_leaf_reg': 2.2819304624759433, 'random_strength': 0.07126670701213982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7357627032912685}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:15:28,242] Trial 37 finished with value: 0.5778744567852392 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08452603735678789, 'depth': 7, 'l2_leaf_reg': 1.7895001049666668, 'random_strength': 0.06015269823620395, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.6997357414475852}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:15:41,010] Trial 38 finished with value: 0.5846479265210209 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06279445463198312, 'depth': 7, 'l2_leaf_reg': 1.4153497832148472, 'random_strength': 0.351353833848872, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.12221043743904225}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:16:02,873] Trial 39 finished with value: 0.5723588110692466 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05773283030230417, 'depth': 7, 'l2_leaf_reg': 1.3765578644825445, 'random_strength': 0.3357374754830792, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.4180462534866333}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:16:15,907] Trial 40 finished with value: 0.5668184393532627 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06734958817167165, 'depth': 7, 'l2_leaf_reg': 1.0971416373443639, 'random_strength': 0.4319796740020263, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.4532051511681003}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:16:29,694] Trial 41 finished with value: 0.5580137709970829 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08635342876960217, 'depth': 7, 'l2_leaf_reg': 1.6581226479235922, 'random_strength': 0.19507522825144005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.2907563020932256}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:16:45,054] Trial 42 finished with value: 0.5334533569225746 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0713770742351059, 'depth': 7, 'l2_leaf_reg': 2.268500402645518, 'random_strength': 0.26476294531703853, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.848341272915878}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:16:58,546] Trial 43 finished with value: 0.5657918088847155 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05120346877615951, 'depth': 7, 'l2_leaf_reg': 1.4570600973201564, 'random_strength': 0.13812438389534173, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.015511881399920935}. Best is trial 19 with value: 0.5872876604395809.
[I 2026-04-15 12:17:34,367] Trial 44 finished with value: 0.5642287064514241 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07593648126429749, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.05712928250211907, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.9134481426253878}. Best is trial 19 with value: 0.5872876604395809.

                                               feature  importance
60               eye__sac_speed_AOI_aggregated_Pos_min    0.117725
53              eye__sac_length_AOI_aggregated_Pos_min    0.098767
32           eye__sac_length_AOI_aggregated_Neg_median    0.031311
472                                 cov_freq__umap_002    0.027977
8                                   eye__sac_speed_min    0.022334
183                  eye__fix_duration_AOI_FD_Neg1_sum    0.020662
537                                 cov_freq__umap_067    0.020422
351               eye__lyapunov_exponent_m_2_tau_2_T_2    0.019067
401         eye__rec_metric_euclidean_length_1_rho_250    0.018819
395                 eye__lam_euclidean_length_1_rho_25    0.018731
509                                 cov_freq__umap_039    0.017735
532                                 cov_freq__umap_062    0.017177
527                                 cov_freq__umap_057    0.014396
490                                 cov_freq__umap_020    0.013403
482                                 cov_freq__umap_012    0.013169
352               eye__lyapunov_exponent_m_2_tau_2_T_4    0.012694
558                                 cov_freq__umap_088    0.012634
519                                 cov_freq__umap_049    0.012580
92   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.012436
36               eye__sac_speed_AOI_aggregated_Neg_min    0.012275
356               eye__lyapunov_exponent_m_3_tau_2_T_1    0.012076
506                                 cov_freq__umap_036    0.011565
10                                 eye__sac_speed_mean    0.011259
5                                  eye__sac_length_sum    0.011240
309                       eye__phase_entropy_m_4_tau_2    0.011097
164                                 eye__reg_mask_mean    0.011012
525                                 cov_freq__umap_055    0.010654
502                                 cov_freq__umap_032    0.010452
533                                 cov_freq__umap_063    0.009990
467                                 eye__imf0_kurtosis    0.009877

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.56229
              precision    recall  f1-score   support

           0       0.73      0.94      0.82       234
           1       0.58      0.21      0.30       102

    accuracy                           0.71       336
   macro avg       0.66      0.57      0.56       336
weighted avg       0.69      0.71      0.66       336

Confusion matrix:
 [[219  15]
 [ 81  21]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=binary__feat=all_features+cov_freq__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                               feature  importance
60               eye__sac_speed_AOI_aggregated_Pos_min   14.637543
519                                 cov_freq__umap_049    7.775392
275         eye__fix_duration_AOI_aggregated_Pos_first    7.011464
53              eye__sac_length_AOI_aggregated_Pos_min    6.648984
495                                 cov_freq__umap_025    4.552781
464                                      eye__imf0_min    4.393263
492                                 cov_freq__umap_022    3.633559
347               eye__lyapunov_exponent_m_2_tau_1_T_1    3.524037
509                                 cov_freq__umap_039    3.341926
62              eye__sac_speed_AOI_aggregated_Pos_mean    2.948666
393          eye__rec_metric_euclidean_length_1_rho_25    2.909384
553                                 cov_freq__umap_083    2.858273
11                               eye__sac_speed_median    2.843151
562                                 cov_freq__umap_092    2.797852
465                                      eye__imf0_max    2.761075
178                 eye__fix_duration_AOI_FD_Neg1_mean    2.654925
477                                 cov_freq__umap_007    2.563073
259        eye__fix_duration_AOI_aggregated_Neg_median    2.367491
471                                 cov_freq__umap_001    2.336637
398                 eye__det_euclidean_length_1_rho_50    2.073994
158                                 eye__reg_speed_max    1.803930
544                                 cov_freq__umap_074    1.755935
170                              eye__fix_duration_std    1.707977
333                      eye__sample_entropy_m=2_r=100    1.612006
479                                 cov_freq__umap_009    1.520382
17                            eye__sac_angle_to_x_mean    1.358071
99   eye__sac_speed_from_Pos_to_Target_from_Pos_to_...    1.353908
48              eye__sac_speed_AOI_aggregated_None_min    1.335831
565                                 cov_freq__umap_095    1.194678
366                         eye__fractal_dim_m_2_tau_2    0.926637

================================================================================
Skipping existing experiment: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST
[cov_freq] rows missing after index match -> train: 1658, test: 160
[cov_freq] UMAP compression: train/test features 36295 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 12:23:15,463] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+cov_freq__target=match_mismatch_general__problem=multiclass__feat=all_features+cov_freq__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 12:23:21,875] Trial 0 finished with value: 0.6436562896956001 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:23:28,403] Trial 1 finished with value: 0.5927866723364146 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:23:36,190] Trial 2 finished with value: 0.6294998545864445 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:23:42,155] Trial 3 finished with value: 0.6217397353555791 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:23:47,594] Trial 4 finished with value: 0.6280339407432662 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:23:55,950] Trial 5 finished with value: 0.6327778595290385 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.6436562896956001.
[I 2026-04-15 12:24:00,883] Trial 6 finished with value: 0.6453783108645307 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:12,011] Trial 7 finished with value: 0.6333665687107882 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:18,362] Trial 8 finished with value: 0.6280296855719677 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:31,594] Trial 9 finished with value: 0.6226291230361995 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:36,933] Trial 10 finished with value: 0.6224359499256342 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:43,772] Trial 11 finished with value: 0.6446952545264426 and parameters: {'learning_rate': 0.049480590164922914, 'max_depth': 3, 'min_child_weight': 2.433568079848371, 'subsample': 0.7005773360180112, 'colsample_bytree': 0.8593340115181465, 'gamma': 0.5892553864010996, 'reg_alpha': 0.00044200386917527174, 'reg_lambda': 2.743141722080137}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:50,094] Trial 12 finished with value: 0.6406971990585937 and parameters: {'learning_rate': 0.07270060595906637, 'max_depth': 3, 'min_child_weight': 2.158609633387336, 'subsample': 0.7008841262770472, 'colsample_bytree': 0.8629975808647283, 'gamma': 0.5628810811434999, 'reg_alpha': 0.0031841301424337947, 'reg_lambda': 0.7166303909201697}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:24:55,466] Trial 13 finished with value: 0.6243049884462539 and parameters: {'learning_rate': 0.12220061137597063, 'max_depth': 4, 'min_child_weight': 2.3527346379720164, 'subsample': 0.7412874856027651, 'colsample_bytree': 0.8187028502950392, 'gamma': 1.9698876526247318, 'reg_alpha': 0.002214668667244544, 'reg_lambda': 0.8313811955700386}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:04,238] Trial 14 finished with value: 0.6320460673939318 and parameters: {'learning_rate': 0.04038365884445841, 'max_depth': 4, 'min_child_weight': 5.293870612391065, 'subsample': 0.823161524080195, 'colsample_bytree': 0.8881699126650688, 'gamma': 1.3493957590129315, 'reg_alpha': 0.00010055749592247216, 'reg_lambda': 7.914082900144905}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:11,055] Trial 15 finished with value: 0.6346267769794761 and parameters: {'learning_rate': 0.0587868740285703, 'max_depth': 3, 'min_child_weight': 2.605443591982054, 'subsample': 0.7513888356581256, 'colsample_bytree': 0.895993735152329, 'gamma': 0.7134594517474053, 'reg_alpha': 0.015557995042491975, 'reg_lambda': 0.00016599250040776937}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:26,351] Trial 16 finished with value: 0.6329857822862528 and parameters: {'learning_rate': 0.022272332116943946, 'max_depth': 8, 'min_child_weight': 6.098806807282297, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8136626354725327, 'gamma': 0.392019619932354, 'reg_alpha': 0.0007480045505120689, 'reg_lambda': 0.2512688475082513}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:32,203] Trial 17 finished with value: 0.6267766908512056 and parameters: {'learning_rate': 0.15034586721900353, 'max_depth': 5, 'min_child_weight': 3.9834277617386125, 'subsample': 0.7009459034848964, 'colsample_bytree': 0.9964340432341179, 'gamma': 1.3769170463887486, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 2.2459463567791453}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:39,238] Trial 18 finished with value: 0.6213321052414018 and parameters: {'learning_rate': 0.08745712452078169, 'max_depth': 4, 'min_child_weight': 2.85252673730009, 'subsample': 0.9057707674644468, 'colsample_bytree': 0.8939882469226723, 'gamma': 0.901819626936498, 'reg_alpha': 0.05397804286576262, 'reg_lambda': 0.011397783591272139}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:51,603] Trial 19 finished with value: 0.6339190866341495 and parameters: {'learning_rate': 0.02960806247133507, 'max_depth': 7, 'min_child_weight': 6.755767154796553, 'subsample': 0.7579427635891753, 'colsample_bytree': 0.829213749065781, 'gamma': 1.1828156911485483, 'reg_alpha': 0.013061645432922842, 'reg_lambda': 1.75144139558839}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:25:58,099] Trial 20 finished with value: 0.6297402870227577 and parameters: {'learning_rate': 0.06845494927978915, 'max_depth': 3, 'min_child_weight': 1.2778798052910343, 'subsample': 0.81575335293704, 'colsample_bytree': 0.7882293720083653, 'gamma': 1.66096871917336, 'reg_alpha': 0.0013282486060217278, 'reg_lambda': 0.19865050084460098}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:26:06,058] Trial 21 finished with value: 0.6419740165520396 and parameters: {'learning_rate': 0.04672853001646515, 'max_depth': 4, 'min_child_weight': 3.5530537347320097, 'subsample': 0.7233749104923974, 'colsample_bytree': 0.7115677458085569, 'gamma': 0.3338679620088831, 'reg_alpha': 0.0003602571333924084, 'reg_lambda': 3.1751667966001214}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:26:14,577] Trial 22 finished with value: 0.6447808554151546 and parameters: {'learning_rate': 0.04312487298706795, 'max_depth': 4, 'min_child_weight': 5.034404428635182, 'subsample': 0.7264121649807225, 'colsample_bytree': 0.7802255931447097, 'gamma': 0.3390616799225444, 'reg_alpha': 8.70290869543081, 'reg_lambda': 3.5582106745501183}. Best is trial 6 with value: 0.6453783108645307.
[I 2026-04-15 12:26:22,500] Trial 23 finished with value: 0.6516705177918143 and parameters: {'learning_rate': 0.057455339642979365, 'max_depth': 5, 'min_child_weight': 7.447611077967014, 'subsample': 0.7418049576016297, 'colsample_bytree': 0.8430331147811305, 'gamma': 0.5239295156525926, 'reg_alpha': 5.4432621058706365, 'reg_lambda': 9.591567438627191}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:26:29,727] Trial 24 finished with value: 0.646370362126321 and parameters: {'learning_rate': 0.05885838631244888, 'max_depth': 5, 'min_child_weight': 7.648946186544666, 'subsample': 0.7444373834965858, 'colsample_bytree': 0.7940507610639512, 'gamma': 0.4612476301307389, 'reg_alpha': 8.656324443752194, 'reg_lambda': 6.207805475238155}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:26:38,224] Trial 25 finished with value: 0.6367998700497172 and parameters: {'learning_rate': 0.05922582770103227, 'max_depth': 5, 'min_child_weight': 7.826955248315427, 'subsample': 0.7538444233711298, 'colsample_bytree': 0.8301460472239315, 'gamma': 0.9218879931401207, 'reg_alpha': 1.144365053727635, 'reg_lambda': 9.628953846559758}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:26:43,802] Trial 26 finished with value: 0.6350211606857323 and parameters: {'learning_rate': 0.1259760404156379, 'max_depth': 5, 'min_child_weight': 7.645977531385575, 'subsample': 0.81110988244745, 'colsample_bytree': 0.8807007671624207, 'gamma': 0.4930651886979127, 'reg_alpha': 7.853987447088725, 'reg_lambda': 0.3667243028883591}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:26:51,469] Trial 27 finished with value: 0.6240535993245467 and parameters: {'learning_rate': 0.09762244493082722, 'max_depth': 7, 'min_child_weight': 9.76861735219388, 'subsample': 0.859476608504835, 'colsample_bytree': 0.9148564350193288, 'gamma': 0.7594594046589174, 'reg_alpha': 0.5881719056265049, 'reg_lambda': 0.8188274048540753}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:00,202] Trial 28 finished with value: 0.6203135690610799 and parameters: {'learning_rate': 0.06273454159758082, 'max_depth': 5, 'min_child_weight': 7.090573729394044, 'subsample': 0.76928226065336, 'colsample_bytree': 0.8434806451560264, 'gamma': 0.18086783858047273, 'reg_alpha': 4.453510790201145, 'reg_lambda': 1.3485402588225}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:10,576] Trial 29 finished with value: 0.6399101307083295 and parameters: {'learning_rate': 0.039857978991854746, 'max_depth': 6, 'min_child_weight': 9.680626967449594, 'subsample': 0.7387941925234326, 'colsample_bytree': 0.7703170143425888, 'gamma': 0.17859907002678332, 'reg_alpha': 0.05114178173778569, 'reg_lambda': 5.254476397897496}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:17,829] Trial 30 finished with value: 0.6391154005103978 and parameters: {'learning_rate': 0.0836482559695014, 'max_depth': 5, 'min_child_weight': 5.136755220260704, 'subsample': 0.7977977076977109, 'colsample_bytree': 0.8119491578840925, 'gamma': 0.4569243689999466, 'reg_alpha': 2.830767297779972, 'reg_lambda': 0.018502244216073403}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:24,199] Trial 31 finished with value: 0.6461526766485952 and parameters: {'learning_rate': 0.0435280466559753, 'max_depth': 4, 'min_child_weight': 4.790115182556671, 'subsample': 0.7212312591123682, 'colsample_bytree': 0.773550426545445, 'gamma': 0.30308910342052153, 'reg_alpha': 9.844755910648121, 'reg_lambda': 2.967013415414003}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:32,698] Trial 32 finished with value: 0.6438683907903996 and parameters: {'learning_rate': 0.05215859514520369, 'max_depth': 4, 'min_child_weight': 6.618324095703943, 'subsample': 0.7387386049171538, 'colsample_bytree': 0.7972861359695809, 'gamma': 0.06080412564073176, 'reg_alpha': 5.539360888841185, 'reg_lambda': 5.2330693225521046}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:43,623] Trial 33 finished with value: 0.6332721119176158 and parameters: {'learning_rate': 0.03411248109164023, 'max_depth': 5, 'min_child_weight': 8.012502413049388, 'subsample': 0.7622563775885167, 'colsample_bytree': 0.7566397145293241, 'gamma': 0.22805323691224771, 'reg_alpha': 2.5860329096369945, 'reg_lambda': 1.3030347165119356}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:27:56,168] Trial 34 finished with value: 0.6396517393109316 and parameters: {'learning_rate': 0.024863900838226174, 'max_depth': 5, 'min_child_weight': 4.5596827813616025, 'subsample': 0.7177632299476138, 'colsample_bytree': 0.7304490545442054, 'gamma': 0.012269916530544545, 'reg_alpha': 0.8551249098567724, 'reg_lambda': 4.2249828629987425}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:02,989] Trial 35 finished with value: 0.6445726140000559 and parameters: {'learning_rate': 0.06938306300504724, 'max_depth': 4, 'min_child_weight': 6.196839623161378, 'subsample': 0.7743555990149208, 'colsample_bytree': 0.842194521134303, 'gamma': 0.687392249255784, 'reg_alpha': 2.90040532426518, 'reg_lambda': 0.4101236442339759}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:13,151] Trial 36 finished with value: 0.6423027508261303 and parameters: {'learning_rate': 0.03752193691652603, 'max_depth': 5, 'min_child_weight': 5.623436468197661, 'subsample': 0.7336993830070873, 'colsample_bytree': 0.7667643659306297, 'gamma': 0.43541808688721506, 'reg_alpha': 0.007871286567813196, 'reg_lambda': 1.7227122138027762}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:21,251] Trial 37 finished with value: 0.6458618845965871 and parameters: {'learning_rate': 0.054953478128002956, 'max_depth': 6, 'min_child_weight': 4.385733038419907, 'subsample': 0.9065182404467309, 'colsample_bytree': 0.7984324041760964, 'gamma': 0.2928910848352299, 'reg_alpha': 9.858137022348995, 'reg_lambda': 0.08165665081633457}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:28,924] Trial 38 finished with value: 0.6412746998708544 and parameters: {'learning_rate': 0.05503444234614966, 'max_depth': 7, 'min_child_weight': 4.403119908069915, 'subsample': 0.906806558196514, 'colsample_bytree': 0.7996474595437963, 'gamma': 0.2777873415278955, 'reg_alpha': 9.026587023223186, 'reg_lambda': 0.04111614744110114}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:42,821] Trial 39 finished with value: 0.6226345778980905 and parameters: {'learning_rate': 0.028730577441172498, 'max_depth': 6, 'min_child_weight': 3.6336714570092545, 'subsample': 0.9253159750682973, 'colsample_bytree': 0.77766514941081, 'gamma': 0.10956531967118727, 'reg_alpha': 1.7797251260068534, 'reg_lambda': 0.10067490853114709}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:53,070] Trial 40 finished with value: 0.6437075249877933 and parameters: {'learning_rate': 0.04542696795331482, 'max_depth': 6, 'min_child_weight': 4.7547938717308025, 'subsample': 0.8806305088866302, 'colsample_bytree': 0.7179739885778096, 'gamma': 0.5402998850211737, 'reg_alpha': 0.3996640079057111, 'reg_lambda': 0.006960352866576534}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:28:59,020] Trial 41 finished with value: 0.6234782779000139 and parameters: {'learning_rate': 0.10439066984393583, 'max_depth': 5, 'min_child_weight': 8.761254105368215, 'subsample': 0.9991908659126955, 'colsample_bytree': 0.876684975542797, 'gamma': 0.2871563057050709, 'reg_alpha': 4.612968849785282, 'reg_lambda': 9.049590255539245}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:06,440] Trial 42 finished with value: 0.6262928177910654 and parameters: {'learning_rate': 0.07406780158581913, 'max_depth': 6, 'min_child_weight': 7.301638749400063, 'subsample': 0.9472491712941472, 'colsample_bytree': 0.802470439893226, 'gamma': 0.8368956331076072, 'reg_alpha': 0.20175044679770393, 'reg_lambda': 0.501350136705927}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:13,466] Trial 43 finished with value: 0.6351268792491312 and parameters: {'learning_rate': 0.05526011141980214, 'max_depth': 6, 'min_child_weight': 8.609547443064159, 'subsample': 0.8477285353632366, 'colsample_bytree': 0.8297114640184949, 'gamma': 0.6280551522075699, 'reg_alpha': 9.79533738249334, 'reg_lambda': 0.1865528917981161}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:19,399] Trial 44 finished with value: 0.6318177408867198 and parameters: {'learning_rate': 0.0651204074631986, 'max_depth': 5, 'min_child_weight': 5.734669724283552, 'subsample': 0.7764835203185497, 'colsample_bytree': 0.7490841328720952, 'gamma': 1.623837257243379, 'reg_alpha': 3.643027918811459, 'reg_lambda': 1.1696616469558543}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:27,530] Trial 45 finished with value: 0.6269059543063074 and parameters: {'learning_rate': 0.04904581957434358, 'max_depth': 6, 'min_child_weight': 4.201866300838412, 'subsample': 0.8845650108980115, 'colsample_bytree': 0.9056092213079534, 'gamma': 1.0328405062674963, 'reg_alpha': 1.6454668465793538, 'reg_lambda': 0.06524630017063761}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:32,903] Trial 46 finished with value: 0.6243716735453206 and parameters: {'learning_rate': 0.19774732251403448, 'max_depth': 4, 'min_child_weight': 9.9196844795211, 'subsample': 0.7120943669728472, 'colsample_bytree': 0.8674553585287559, 'gamma': 1.2246600544539983, 'reg_alpha': 0.12954847185326718, 'reg_lambda': 5.470015514792589}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:38,713] Trial 47 finished with value: 0.642867953717971 and parameters: {'learning_rate': 0.0794516300264527, 'max_depth': 6, 'min_child_weight': 3.733252027295066, 'subsample': 0.799821610413137, 'colsample_bytree': 0.8469123429520651, 'gamma': 1.8570525280007628, 'reg_alpha': 5.962616743818501, 'reg_lambda': 0.026386318342428047}. Best is trial 23 with value: 0.6516705177918143.
[I 2026-04-15 12:29:51,411] Trial 48 finished with value: 0.6146602450886391 and parameters: {'learning_rate': 0.03651581245202686, 'max_depth': 7, 'min_child_weight': 3.2406043956163386, 'subsample': 0.9362394902257625, 'colsample_bytree': 0.8192198869777547, 'gamma': 0.3959971854390473, 'reg_alpha': 0.840019337386767, 'reg_lambda': 0.004371197626165927}. Best is trial 23 with value: 0.6516705177918143.

[I 2026-04-15 12:36:38,441] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 12:36:46,511] Trial 0 finished with value: 0.6400107572122057 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6400107572122057.
[I 2026-04-15 12:36:56,831] Trial 1 finished with value: 0.6539717650356516 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:37:11,550] Trial 2 finished with value: 0.643703099405881 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:37:37,108] Trial 3 finished with value: 0.6222278970035099 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:38:18,353] Trial 4 finished with value: 0.6084511342587045 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:39:06,323] Trial 5 finished with value: 0.6180107291361053 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:39:33,628] Trial 6 finished with value: 0.6387136908391335 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:40:14,883] Trial 7 finished with value: 0.6405386838462144 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:41:34,813] Trial 8 finished with value: 0.6402136486633168 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:42:00,464] Trial 9 finished with value: 0.6340072044418064 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:42:14,553] Trial 10 finished with value: 0.6396469293065206 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:42:25,636] Trial 11 finished with value: 0.6439751316913388 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03619150798130427, 'depth': 5, 'l2_leaf_reg': 7.1136091382850015, 'random_strength': 0.40988043411436537, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8451909941303626}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:42:39,336] Trial 12 finished with value: 0.6454862792706202 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031222380286557255, 'depth': 5, 'l2_leaf_reg': 5.293108038070359, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8961594169517826}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:42:52,195] Trial 13 finished with value: 0.6482735222624537 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02736425624250135, 'depth': 5, 'l2_leaf_reg': 4.21986151444323, 'random_strength': 0.985622287735594, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8835517975415363}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:06,475] Trial 14 finished with value: 0.6407215856825625 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028163178502865416, 'depth': 5, 'l2_leaf_reg': 3.223757824247046, 'random_strength': 0.0009654705471253411, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6140559588570399}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:13,702] Trial 15 finished with value: 0.6477944247836677 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025205257405628973, 'depth': 4, 'l2_leaf_reg': 2.984768074394884, 'random_strength': 0.5623181046141312, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9814769576437812}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:23,482] Trial 16 finished with value: 0.6353581341484008 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05219399788945581, 'depth': 5, 'l2_leaf_reg': 2.491999363424314, 'random_strength': 0.9327834931991135, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8227788772356384}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:28,831] Trial 17 finished with value: 0.6322280816581929 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1270146483057091, 'depth': 4, 'l2_leaf_reg': 13.20028975606876, 'random_strength': 0.20458519629947178, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.874524819924829}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:42,541] Trial 18 finished with value: 0.6419509572452463 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03714463604136608, 'depth': 5, 'l2_leaf_reg': 7.012289062716994, 'random_strength': 0.5318002177552702, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7018128554985261}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:43:58,497] Trial 19 finished with value: 0.6489711468165875 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05761842420865604, 'depth': 6, 'l2_leaf_reg': 11.70811065763149, 'random_strength': 0.8440104680189937, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9394716488088194}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:44:19,498] Trial 20 finished with value: 0.6410106426781708 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05964420023681819, 'depth': 6, 'l2_leaf_reg': 13.524167205985677, 'random_strength': 0.8124509366883349, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7822537605433195}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:44:32,174] Trial 21 finished with value: 0.6438745727372375 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02509766518624476, 'depth': 5, 'l2_leaf_reg': 10.524370984410405, 'random_strength': 0.9932081888714701, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9318677192593007}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:44:51,076] Trial 22 finished with value: 0.6511579372487093 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03704422416146529, 'depth': 6, 'l2_leaf_reg': 5.804286078834256, 'random_strength': 0.8780591081398206, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9976734714866178}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:45:26,992] Trial 23 finished with value: 0.6372699114307062 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039368611831057776, 'depth': 7, 'l2_leaf_reg': 13.173212487369753, 'random_strength': 0.7366880152694889, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9978006098208198}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:45:42,708] Trial 24 finished with value: 0.6374455181780397 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05964559769008034, 'depth': 6, 'l2_leaf_reg': 5.922254118721694, 'random_strength': 0.881830597259037, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9300036764848725}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:45:59,341] Trial 25 finished with value: 0.6380514014822138 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03294276602686065, 'depth': 6, 'l2_leaf_reg': 8.861420766391953, 'random_strength': 0.6456008638584122, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9685573492452265}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:46:39,317] Trial 26 finished with value: 0.6488746519223618 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05311800723383, 'depth': 7, 'l2_leaf_reg': 19.179691095074105, 'random_strength': 0.7494938457012316, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.2578643405925001}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:46:59,536] Trial 27 finished with value: 0.6529242034881453 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04391964702282792, 'depth': 6, 'l2_leaf_reg': 11.710422256744732, 'random_strength': 0.5948624848957296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7123734258023668}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:47:08,961] Trial 28 finished with value: 0.6539083230702856 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.041672273937534095, 'depth': 4, 'l2_leaf_reg': 15.653245097981669, 'random_strength': 0.4589077443985027, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7111366957649109}. Best is trial 1 with value: 0.6539717650356516.
[I 2026-04-15 12:47:29,641] Trial 29 finished with value: 0.6543347370371848 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.044056096248921796, 'depth': 4, 'l2_leaf_reg': 15.531750400125706, 'random_strength': 0.1408851011800677, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.682610778645282}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:48:01,637] Trial 30 finished with value: 0.6383911107866094 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02279640925779917, 'depth': 4, 'l2_leaf_reg': 15.151675247598716, 'random_strength': 0.12150170315262819, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.986682227276261}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:48:20,225] Trial 31 finished with value: 0.6507322847748795 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04525248823983172, 'depth': 4, 'l2_leaf_reg': 16.27005252407621, 'random_strength': 0.17813678238725061, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.7214305751570644}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:48:38,746] Trial 32 finished with value: 0.6436966449837003 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04065031152121367, 'depth': 4, 'l2_leaf_reg': 8.168020493721865, 'random_strength': 0.27767379306973006, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.892814735753607}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:48:52,806] Trial 33 finished with value: 0.6541125764948079 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.030799742007547926, 'depth': 4, 'l2_leaf_reg': 18.88974313237226, 'random_strength': 0.36476685328598357, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.5024721009529562}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:49:06,973] Trial 34 finished with value: 0.6528369541025347 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.031868628586662104, 'depth': 4, 'l2_leaf_reg': 19.819006636005327, 'random_strength': 0.3400295867590044, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.199310123823186}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:49:21,757] Trial 35 finished with value: 0.653900686362596 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03121669525146724, 'depth': 4, 'l2_leaf_reg': 15.824504747524166, 'random_strength': 0.4125395394458024, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.6950118513665355}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:49:32,407] Trial 36 finished with value: 0.6464145590534707 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.028669664481378858, 'depth': 4, 'l2_leaf_reg': 9.50490099180701, 'random_strength': 0.10302736444165535, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.5277968620266718}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:49:40,023] Trial 37 finished with value: 0.6430034849552313 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0687819557082548, 'depth': 4, 'l2_leaf_reg': 11.60736884638073, 'random_strength': 0.04159376499222675, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.0394655695542703}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:50:08,194] Trial 38 finished with value: 0.6524992090569677 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.023202307816137024, 'depth': 4, 'l2_leaf_reg': 16.142882842916435, 'random_strength': 0.46902622739474087, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.611385220674696}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:50:17,136] Trial 39 finished with value: 0.6459184293913944 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19666138542450712, 'depth': 5, 'l2_leaf_reg': 14.112654194034251, 'random_strength': 0.3494173898196894, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.883347132131032}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:50:25,115] Trial 40 finished with value: 0.6374222389107873 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08699117658544306, 'depth': 4, 'l2_leaf_reg': 18.439264855449544, 'random_strength': 0.21474200120818498, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.286305886638696}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:50:39,548] Trial 41 finished with value: 0.6528365609835121 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.032922104698154396, 'depth': 4, 'l2_leaf_reg': 16.426298464288752, 'random_strength': 0.40779178070562294, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.8711351244451704}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:50:50,411] Trial 42 finished with value: 0.6537243693311579 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04858633489846496, 'depth': 4, 'l2_leaf_reg': 17.221602411574985, 'random_strength': 0.4060134830926568, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.6023455086669909}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:51:01,143] Trial 43 finished with value: 0.6514001057308538 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03394209556687517, 'depth': 4, 'l2_leaf_reg': 14.308669598462618, 'random_strength': 0.2935665796292777, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.0173836583226832}. Best is trial 29 with value: 0.6543347370371848.
[I 2026-04-15 12:51:40,591] Trial 44 finished with value: 0.6488254010565802 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.029248011886337244, 'depth': 5, 'l2_leaf_reg': 10.251508605162142, 'random_strength': 0.481431046622132, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.415156246799224}. Best is trial 29 with value: 0.6543347370371848.

                                         feature  importance
63      eye__sac_speed_AOI_aggregated_Pos_median   10.337758
60         eye__sac_speed_AOI_aggregated_Pos_min    8.754785
53        eye__sac_length_AOI_aggregated_Pos_min    8.539778
56     eye__sac_length_AOI_aggregated_Pos_median    7.335902
276     eye__fix_duration_AOI_aggregated_Pos_min    5.024279
277     eye__fix_duration_AOI_aggregated_Pos_max    3.741627
61         eye__sac_speed_AOI_aggregated_Pos_max    3.449336
278    eye__fix_duration_AOI_aggregated_Pos_mean    2.678137
55       eye__sac_length_AOI_aggregated_Pos_mean    2.384657
279  eye__fix_duration_AOI_aggregated_Pos_median    2.093244
524                           cov_freq__umap_054    2.047504
62        eye__sac_speed_AOI_aggregated_Pos_mean    1.704967
29        eye__sac_length_AOI_aggregated_Neg_min    1.569474
179         eye__fix_duration_AOI_FD_Neg1_median    1.479710
54        eye__sac_length_AOI_aggregated_Pos_max    1.357660
38        eye__sac_speed_AOI_aggregated_Neg_mean    1.276692
178           eye__fix_duration_AOI_FD_Neg1_mean    0.961076
36         eye__sac_speed_AOI_aggregated_Neg_min    0.885790
176            eye__fix_duration_AOI_FD_Neg1_min    0.798375
305                 eye__phase_entropy_m_2_tau_2    0.704981
39      eye__sac_speed_AOI_aggregated_Neg_median    0.661728
31       eye__sac_length_AOI_aggregated_Neg_mean    0.637845
275   eye__fix_duration_AOI_aggregated_Pos_first    0.536455
395           eye__lam_euclidean_length_1_rho_25    0.481068
546                           cov_freq__umap_076    0.467572
206            eye__fix_duration_AOI_FD_Pos1_min    0.461651
207            eye__fix_duration_AOI_FD_Pos1_max    0.452947
28                   eye__sac_angle_between_skew    0.452911
258    eye__fix_duration_AOI_aggregated_Neg_mean    0.439173
183            eye__fix_duration_AOI_FD_Neg1_sum    0.426872

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,False,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,binary,True,0.403197,0.505965,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch,multiclass,False,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch,multiclass,True,NaN,0.544607,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch_general,binary,False,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch_general,binary,True,0.410526,0.562286,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,multiclass,False,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,True,NaN,0.772836,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,cov_freq,match_mismatch,binary,False,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,cov_freq,match_mismatch,binary,True,0.403197,0.505965,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,cov_freq,match_mismatch,multiclass,False,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,cov_freq,match_mismatch,multiclass,True,NaN,0.544607,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,cov_freq,match_mismatch_general,binary,False,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,cov_freq,match_mismatch_general,binary,True,0.410526,0.562286,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,cov_freq,match_mismatch_general,multiclass,False,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,cov_freq,match_mismatch_general,multiclass,True,NaN,0.772836,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [7]:
text_envelope = _load_ftar_parquet(FTAR_FILES["envelope"])
print("envelope shape:", text_envelope.shape)
summary_envelope = run_ftar_set("envelope", text_envelope)
summary_envelope

envelope shape: (4442, 428)
[envelope] ftar feature count after cleanup: 427

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__ES__refitTEST

[I 2026-04-15 12:53:23,933] A new study created in memory with name: binary_xgb

[envelope] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__ES__refitTEST__no_neutral
X_train: (3016, 897), X_test: (336, 897)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 12:53:31,686] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:53:41,067] Trial 1 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:53:49,983] Trial 2 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:53:58,446] Trial 3 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:06,993] Trial 4 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:15,417] Trial 5 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:22,617] Trial 6 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:31,626] Trial 7 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:40,637] Trial 8 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:50,680] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:54:57,421] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:03,400] Trial 11 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1987511993802379, 'max_depth': 8, 'min_child_weight': 2.2044350854903803, 'subsample': 0.991678377353391, 'colsample_bytree': 0.701477667194265, 'gamma': 0.11220060164975498, 'reg_alpha': 9.196828714331065, 'reg_lambda': 0.00013386192543122697}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:10,091] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12491658728825787, 'max_depth': 3, 'min_child_weight': 3.253041711071422, 'subsample': 0.9269639649687119, 'colsample_bytree': 0.7934706144492909, 'gamma': 0.019495941942304973, 'reg_alpha': 0.0005436011712873391, 'reg_lambda': 4.172125626964391}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:17,813] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 4, 'min_child_weight': 1.9159793446750535, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.7013693620912469, 'gamma': 0.48600046581571593, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.00011913812992647485}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:31,002] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.040383658844458395, 'max_depth': 8, 'min_child_weight': 1.1157937296124318, 'subsample': 0.7004519003043, 'colsample_bytree': 0.7732828130312976, 'gamma': 0.29464130180941833, 'reg_alpha': 3.421125808225141, 'reg_lambda': 0.006106037730048314}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:38,987] Trial 15 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02128929082732021, 'max_depth': 4, 'min_child_weight': 4.195345625812058, 'subsample': 0.8475571599493473, 'colsample_bytree': 0.844821976965745, 'gamma': 0.7437277813718939, 'reg_alpha': 0.001357616284331662, 'reg_lambda': 0.8741655275059462}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:46,647] Trial 16 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.15108043676026062, 'max_depth': 7, 'min_child_weight': 2.635939156801854, 'subsample': 0.9341462060236994, 'colsample_bytree': 0.7441347259985547, 'gamma': 1.464764475541173, 'reg_alpha': 0.0001690557851152469, 'reg_lambda': 0.0005807427487454919}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:55:54,099] Trial 17 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0762942305162252, 'max_depth': 4, 'min_child_weight': 4.907699675577318, 'subsample': 0.8181815313452178, 'colsample_bytree': 0.8185597495393847, 'gamma': 0.280536267454658, 'reg_alpha': 0.9024303033822801, 'reg_lambda': 0.018867535841271068}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:07,046] Trial 18 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02775934184434466, 'max_depth': 7, 'min_child_weight': 1.6209726919199594, 'subsample': 0.9566861349051418, 'colsample_bytree': 0.8781514030059229, 'gamma': 1.2460001337349627, 'reg_alpha': 0.005301455447830579, 'reg_lambda': 1.9253855625275396}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:14,679] Trial 19 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.053435117310511156, 'max_depth': 4, 'min_child_weight': 1.0409840411779645, 'subsample': 0.8767777458793767, 'colsample_bytree': 0.7321641349085308, 'gamma': 0.6349333920358116, 'reg_alpha': 0.051727758673718365, 'reg_lambda': 0.2028286802625633}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:23,863] Trial 20 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09641570779344828, 'max_depth': 8, 'min_child_weight': 6.230828787225904, 'subsample': 0.9082899246525548, 'colsample_bytree': 0.7769763586761955, 'gamma': 0.9086848615320234, 'reg_alpha': 0.0008177979046200564, 'reg_lambda': 0.00044247158557228}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:32,799] Trial 21 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.036664573344029006, 'max_depth': 5, 'min_child_weight': 1.260973683340702, 'subsample': 0.7411452533299434, 'colsample_bytree': 0.8007167253279321, 'gamma': 1.6933292393840693, 'reg_alpha': 0.005862290348864694, 'reg_lambda': 0.03430175244923979}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:41,994] Trial 22 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02934164705222114, 'max_depth': 5, 'min_child_weight': 1.383718954125864, 'subsample': 0.7655647256435949, 'colsample_bytree': 0.7712162750826156, 'gamma': 1.4486941198581356, 'reg_alpha': 0.011613525255434064, 'reg_lambda': 0.004920659637507184}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:48,373] Trial 23 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04326280942602445, 'max_depth': 3, 'min_child_weight': 1.8625847090208365, 'subsample': 0.8195757058676902, 'colsample_bytree': 0.7218733741534957, 'gamma': 1.5083519548484634, 'reg_alpha': 0.002672717553441807, 'reg_lambda': 0.2503662818064834}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:56:56,228] Trial 24 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0269797226000463, 'max_depth': 4, 'min_child_weight': 2.8607670606754, 'subsample': 0.7032067019907043, 'colsample_bytree': 0.8166399588819715, 'gamma': 0.26418535818823885, 'reg_alpha': 0.00034953038239536285, 'reg_lambda': 0.02809951104717541}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:05,081] Trial 25 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.062167835010909035, 'max_depth': 5, 'min_child_weight': 1.4926028598809695, 'subsample': 0.756092186008002, 'colsample_bytree': 0.760391833162829, 'gamma': 1.1989544688507863, 'reg_alpha': 0.0014891967145060092, 'reg_lambda': 0.0019295679536769522}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:15,967] Trial 26 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04398537724851647, 'max_depth': 7, 'min_child_weight': 3.7884659433866483, 'subsample': 0.7237076270749806, 'colsample_bytree': 0.793317086394778, 'gamma': 0.024283760076633246, 'reg_alpha': 0.010504157495320604, 'reg_lambda': 9.883749859167906}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:23,993] Trial 27 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03150912333371182, 'max_depth': 4, 'min_child_weight': 2.05015886243293, 'subsample': 0.8174447274569743, 'colsample_bytree': 0.8674287427459931, 'gamma': 1.6931863121134303, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 2.191348928851165}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:33,550] Trial 28 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.024256656190291714, 'max_depth': 5, 'min_child_weight': 1.3495612202292022, 'subsample': 0.7186531548578046, 'colsample_bytree': 0.7218031594596818, 'gamma': 0.47605818026492147, 'reg_alpha': 0.00040856409637778736, 'reg_lambda': 0.057536026996524554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:42,038] Trial 29 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.10083126752758151, 'max_depth': 5, 'min_child_weight': 1.7572752618473877, 'subsample': 0.8726460865586815, 'colsample_bytree': 0.8191870032278322, 'gamma': 0.8168034319791714, 'reg_alpha': 0.39336049343797835, 'reg_lambda': 0.012479393926795208}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:48,464] Trial 30 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03821815608488094, 'max_depth': 3, 'min_child_weight': 4.824431698181973, 'subsample': 0.7635885306635127, 'colsample_bytree': 0.760986120522179, 'gamma': 0.16975102055504673, 'reg_alpha': 0.04796268779915355, 'reg_lambda': 0.29005401983550877}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:57:55,998] Trial 31 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09736379787597009, 'max_depth': 6, 'min_child_weight': 6.834458782518982, 'subsample': 0.8863458400179755, 'colsample_bytree': 0.9820813121623206, 'gamma': 1.3293333285335125, 'reg_alpha': 3.6506306459483784, 'reg_lambda': 0.7643028530722084}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:03,432] Trial 32 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.14530519527803176, 'max_depth': 5, 'min_child_weight': 3.6684299621284793, 'subsample': 0.9112536756247197, 'colsample_bytree': 0.905709913797324, 'gamma': 0.9687427713871858, 'reg_alpha': 0.7200409982993501, 'reg_lambda': 1.156847993899564}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:10,962] Trial 33 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08051537296255129, 'max_depth': 4, 'min_child_weight': 4.970762096331227, 'subsample': 0.9682379069839581, 'colsample_bytree': 0.915795574474822, 'gamma': 1.7874266042121612, 'reg_alpha': 0.13522734853654222, 'reg_lambda': 3.4818801693991106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:20,037] Trial 34 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05664704181033773, 'max_depth': 5, 'min_child_weight': 4.1833436310181, 'subsample': 0.8367824424647221, 'colsample_bytree': 0.9502208509011416, 'gamma': 0.6267021068662442, 'reg_alpha': 3.7728086060725397, 'reg_lambda': 0.104777653078898}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:28,532] Trial 35 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.19717327022141168, 'max_depth': 6, 'min_child_weight': 7.723969143303664, 'subsample': 0.9452443629483397, 'colsample_bytree': 0.9089902431555019, 'gamma': 0.19078329136242728, 'reg_alpha': 1.3118747726656768, 'reg_lambda': 0.4093858547878593}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:36,721] Trial 36 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08100535788073908, 'max_depth': 7, 'min_child_weight': 5.809174266099679, 'subsample': 0.9923442941382479, 'colsample_bytree': 0.9955789266825265, 'gamma': 1.982089766506439, 'reg_alpha': 0.29075758944171737, 'reg_lambda': 0.0036145523307250017}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 12:58:46,114] Trial 37 finished with value: 0.4074114276424059 and parameters: {'learning_rate': 0.12717453249055538, 'max_depth': 6, 'min_child_weight': 2.724468420054644, 'subsample': 0.7781124092585633, 'colsample_bytree': 0.7519672746782284, 'gamma': 0.39748849702997435, 'reg_alpha': 0.018200159619655026, 'reg_lambda': 0.00045629257672837617}. Best is trial 37 with value: 0.4074114276424059.
[I 2026-04-15 12:58:55,381] Trial 38 finished with value: 0.40815354857069597 and parameters: {'learning_rate': 0.1684333457262146, 'max_depth': 8, 'min_child_weight': 2.8535816025197027, 'subsample': 0.7949845038819585, 'colsample_bytree': 0.758286413375034, 'gamma': 0.3925179327660646, 'reg_alpha': 0.015898348146036387, 'reg_lambda': 0.00052915713331645}. Best is trial 38 with value: 0.40815354857069597.
[I 2026-04-15 12:59:05,029] Trial 39 finished with value: 0.4084296135736823 and parameters: {'learning_rate': 0.16201879788296997, 'max_depth': 8, 'min_child_weight': 2.829036807985648, 'subsample': 0.797982166884436, 'colsample_bytree': 0.71903680652775, 'gamma': 0.3237207907096131, 'reg_alpha': 0.02880959891543123, 'reg_lambda': 0.0005437639158273228}. Best is trial 39 with value: 0.4084296135736823.
[I 2026-04-15 12:59:14,140] Trial 40 finished with value: 0.4084296135736823 and parameters: {'learning_rate': 0.17050318668387995, 'max_depth': 8, 'min_child_weight': 2.8160651116862496, 'subsample': 0.8014265784358008, 'colsample_bytree': 0.7284842959935321, 'gamma': 0.3828755888956793, 'reg_alpha': 0.017571932137738985, 'reg_lambda': 0.00026270170056738715}. Best is trial 39 with value: 0.4084296135736823.
[I 2026-04-15 12:59:23,478] Trial 41 finished with value: 0.4101164343981508 and parameters: {'learning_rate': 0.16047526303124907, 'max_depth': 8, 'min_child_weight': 2.752144002240815, 'subsample': 0.7950067365482913, 'colsample_bytree': 0.721541342153894, 'gamma': 0.388605330518932, 'reg_alpha': 0.02079965667121653, 'reg_lambda': 0.0003163366777790578}. Best is trial 41 with value: 0.4101164343981508.
[I 2026-04-15 12:59:32,614] Trial 42 finished with value: 0.4084296135736823 and parameters: {'learning_rate': 0.17087100793912238, 'max_depth': 8, 'min_child_weight': 2.868879155753349, 'subsample': 0.8019655050025677, 'colsample_bytree': 0.7182657147436974, 'gamma': 0.39515564034324113, 'reg_alpha': 0.014402768946665923, 'reg_lambda': 0.00025540937641605827}. Best is trial 41 with value: 0.4101164343981508.
[I 2026-04-15 12:59:41,651] Trial 43 finished with value: 0.4216064008425685 and parameters: {'learning_rate': 0.17381787859949946, 'max_depth': 8, 'min_child_weight': 2.4084479348823087, 'subsample': 0.8108016971852711, 'colsample_bytree': 0.7160819993953682, 'gamma': 0.38414895067164384, 'reg_alpha': 0.05260112646680492, 'reg_lambda': 0.00019993646203640626}. Best is trial 43 with value: 0.4216064008425685.
[I 2026-04-15 12:59:50,040] Trial 44 finished with value: 0.4315742759336194 and parameters: {'learning_rate': 0.1740330448336078, 'max_depth': 8, 'min_child_weight': 2.2861434168626786, 'subsample': 0.8033847103188944, 'colsample_bytree': 0.7162145275091244, 'gamma': 0.4991365682762857, 'reg_alpha': 0.0419079667587102, 'reg_lambda': 0.00024005084670023277}. Best is trial 44 with value: 0.4315742759336194.
[I 2026-04-15 12:59:58,904] Trial 45 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.14050622303431393, 'max_depth': 8, 'min_child_weight': 2.331365001459761, 'subsample': 0.80969408914728, 'colsample_bytree': 0.71211907103922, 'gamma': 0.5323749205304112, 'reg_alpha': 0.048221017329675916, 'reg_lambda': 0.00019262507632169685}. Best is trial 44 with value: 0.4315742759336194.
[I 2026-04-15 13:00:07,034] Trial 46 finished with value: 0.41976251623855926 and parameters: {'learning_rate': 0.1818198254423525, 'max_depth': 8, 'min_child_weight': 3.2916456911280862, 'subsample': 0.834466126186372, 'colsample_bytree': 0.7269010010631523, 'gamma': 0.6820669113409926, 'reg_alpha': 0.0336270029846405, 'reg_lambda': 0.0010286312886229642}. Best is trial 44 with value: 0.4315742759336194.
[I 2026-04-15 13:00:14,949] Trial 47 finished with value: 0.42497033178291144 and parameters: {'learning_rate': 0.1960226367714495, 'max_depth': 7, 'min_child_weight': 3.3964399139325034, 'subsample': 0.835591940544763, 'colsample_bytree': 0.7376240579939313, 'gamma': 0.6826160388180569, 'reg_alpha': 0.03276055336841785, 'reg_lambda': 0.0010507244799768593}. Best is trial 44 with value: 0.4315742759336194.

[I 2026-04-15 13:06:49,730] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 13:06:56,371] Trial 0 finished with value: 0.41789771660791275 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.41789771660791275.
[I 2026-04-15 13:07:09,074] Trial 1 finished with value: 0.4122259911748737 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.41789771660791275.
[I 2026-04-15 13:07:21,052] Trial 2 finished with value: 0.4245739559332152 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4245739559332152.
[I 2026-04-15 13:07:42,093] Trial 3 finished with value: 0.4190266033678992 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.4245739559332152.
[I 2026-04-15 13:08:10,693] Trial 4 finished with value: 0.4572868760639822 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:08:45,645] Trial 5 finished with value: 0.4080429283611719 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:09:05,035] Trial 6 finished with value: 0.40792944394139846 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:09:25,625] Trial 7 finished with value: 0.41381521908367547 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:10:07,626] Trial 8 finished with value: 0.41202291535373314 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:10:26,237] Trial 9 finished with value: 0.4440708184350653 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:10:32,982] Trial 10 finished with value: 0.41899753768823533 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:10:49,922] Trial 11 finished with value: 0.44262412446941857 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 1.0029240690742995, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.610132565398292}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:11:21,495] Trial 12 finished with value: 0.4339612853056247 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12249084061852454, 'depth': 8, 'l2_leaf_reg': 1.0091362923696217, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8686828876459834}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:11:37,692] Trial 13 finished with value: 0.4449666385873604 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11898154973533921, 'depth': 7, 'l2_leaf_reg': 1.837768855108871, 'random_strength': 0.8189963197512329, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6043614825558973}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:11:47,644] Trial 14 finished with value: 0.4235533131735242 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12805190845928294, 'depth': 6, 'l2_leaf_reg': 2.0956663066759345, 'random_strength': 0.5701475813832674, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8037124817876364}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:12:16,947] Trial 15 finished with value: 0.4552548640961638 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19598537701914995, 'depth': 8, 'l2_leaf_reg': 3.016699755646488, 'random_strength': 0.45029490611659134, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7739112708398744}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:12:45,805] Trial 16 finished with value: 0.4231272394531724 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19131988478502077, 'depth': 8, 'l2_leaf_reg': 2.9232306112755424, 'random_strength': 0.412688443468574, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.797687922696281}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:13:15,585] Trial 17 finished with value: 0.4361822450275019 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14275466267871886, 'depth': 8, 'l2_leaf_reg': 3.276532958863645, 'random_strength': 0.06053350696868557, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7504830733407016}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:13:21,979] Trial 18 finished with value: 0.42805379407898425 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19985043137862515, 'depth': 5, 'l2_leaf_reg': 5.264973114859012, 'random_strength': 0.23602544965976288, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8588601513341848}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:13:54,251] Trial 19 finished with value: 0.4223788989366985 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.051518582818118774, 'depth': 8, 'l2_leaf_reg': 1.3850595279469555, 'random_strength': 0.4829643842290205, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9760142595052473}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:14:06,169] Trial 20 finished with value: 0.41956979196441535 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03443627085922845, 'depth': 6, 'l2_leaf_reg': 2.6816725490896114, 'random_strength': 0.1287599717617915, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7184699810620169}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:14:23,297] Trial 21 finished with value: 0.4429719157471672 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10655297757416377, 'depth': 7, 'l2_leaf_reg': 1.4119174343150898, 'random_strength': 0.7300873584639261, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6495004272204769}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:14:39,797] Trial 22 finished with value: 0.4450666232036253 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14729540999804655, 'depth': 7, 'l2_leaf_reg': 2.4796097241346207, 'random_strength': 0.5752695337475517, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8502499746925232}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:15:10,239] Trial 23 finished with value: 0.4309837831432968 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1499457813803112, 'depth': 8, 'l2_leaf_reg': 3.657645659780482, 'random_strength': 0.5568499723682396, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.844547702941241}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:15:26,598] Trial 24 finished with value: 0.44763256614536745 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1570014225159189, 'depth': 7, 'l2_leaf_reg': 2.398217337905601, 'random_strength': 0.3553455453745054, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9103798347145856}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:15:57,942] Trial 25 finished with value: 0.44809534402017426 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10026152460673635, 'depth': 8, 'l2_leaf_reg': 1.4423972004819452, 'random_strength': 0.3079093323108386, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7981559644444874}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:16:28,436] Trial 26 finished with value: 0.44834520366177444 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09886042770559259, 'depth': 8, 'l2_leaf_reg': 1.3142947433560932, 'random_strength': 0.25893964630364785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2578643405925001}. Best is trial 4 with value: 0.4572868760639822.
[I 2026-04-15 13:17:01,427] Trial 27 finished with value: 0.4583898552618814 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06254714294108608, 'depth': 8, 'l2_leaf_reg': 1.339346121419973, 'random_strength': 0.19601935922458713, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.30094396714113597}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:17:08,513] Trial 28 finished with value: 0.4245088867345441 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06008533680278842, 'depth': 5, 'l2_leaf_reg': 6.7592261812965715, 'random_strength': 0.05746492960484993, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.22093428076232235}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:17:45,616] Trial 29 finished with value: 0.4138609227128445 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06438653139051287, 'depth': 8, 'l2_leaf_reg': 1.6858529654608678, 'random_strength': 0.16949858293204126, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.372884007233596}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:18:28,653] Trial 30 finished with value: 0.41619143569344813 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03186159068517414, 'depth': 8, 'l2_leaf_reg': 2.094178149449421, 'random_strength': 0.11565254175933039, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 4.4993264036145195}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:18:59,353] Trial 31 finished with value: 0.44640407898982415 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09045969335711393, 'depth': 8, 'l2_leaf_reg': 1.2361609394093316, 'random_strength': 0.2387352048236026, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.018656635512937447}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:19:32,036] Trial 32 finished with value: 0.4436693046780777 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06880523561477993, 'depth': 8, 'l2_leaf_reg': 1.2610224295461252, 'random_strength': 0.22179575128030937, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.2496012120303899}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:19:36,650] Trial 33 finished with value: 0.42325095306389926 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.055499900100721915, 'depth': 4, 'l2_leaf_reg': 1.65130281677046, 'random_strength': 0.4025440391420045, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.7261105928486886}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:19:59,337] Trial 34 finished with value: 0.4132659739543793 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04321116524522745, 'depth': 7, 'l2_leaf_reg': 2.15140482215135, 'random_strength': 0.2821788899193597, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.975004681004118}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:20:28,965] Trial 35 finished with value: 0.45306722190513105 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1134759102794279, 'depth': 8, 'l2_leaf_reg': 1.1787840874866142, 'random_strength': 0.17962981722971272, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.7000234865377997}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:20:45,959] Trial 36 finished with value: 0.43630671840629015 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1671214037877078, 'depth': 7, 'l2_leaf_reg': 1.1655547022493051, 'random_strength': 0.08721084697436166, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.6808148443122644}. Best is trial 27 with value: 0.4583898552618814.
[I 2026-04-15 13:21:15,085] Trial 37 finished with value: 0.47391608713721006 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13912843200618177, 'depth': 8, 'l2_leaf_reg': 1.552671517933063, 'random_strength': 0.010792706670687602, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7764764414838314}. Best is trial 37 with value: 0.47391608713721006.
[I 2026-04-15 13:21:48,087] Trial 38 finished with value: 0.42878396816692493 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13245943153256215, 'depth': 8, 'l2_leaf_reg': 3.6281860879757795, 'random_strength': 0.17861329307378576, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.038358585564376}. Best is trial 37 with value: 0.47391608713721006.
[I 2026-04-15 13:22:03,572] Trial 39 finished with value: 0.48546030982916166 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19666138542450712, 'depth': 7, 'l2_leaf_reg': 1.6021782155023976, 'random_strength': 0.02228535513347562, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7291532991056355}. Best is trial 39 with value: 0.48546030982916166.
[I 2026-04-15 13:22:20,759] Trial 40 finished with value: 0.44158642296786876 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08539653161611863, 'depth': 7, 'l2_leaf_reg': 1.720329233685724, 'random_strength': 0.006984718928208079, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.8398656389400195}. Best is trial 39 with value: 0.48546030982916166.
[I 2026-04-15 13:22:49,858] Trial 41 finished with value: 0.46910100832017654 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.18096543962504613, 'depth': 8, 'l2_leaf_reg': 1.5332870689928502, 'random_strength': 0.04942957574688679, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.9292584815282197}. Best is trial 39 with value: 0.48546030982916166.
[I 2026-04-15 13:23:05,854] Trial 42 finished with value: 0.4584277444715194 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1792008933643985, 'depth': 7, 'l2_leaf_reg': 1.5060669047239092, 'random_strength': 0.0541755845612667, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.8287779639621659}. Best is trial 39 with value: 0.48546030982916166.
[I 2026-04-15 13:23:15,350] Trial 43 finished with value: 0.46313363758822323 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.16827382692144505, 'depth': 6, 'l2_leaf_reg': 1.503526967409685, 'random_strength': 0.02570131292640044, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.812477890755445}. Best is trial 39 with value: 0.48546030982916166.
[I 2026-04-15 13:23:25,113] Trial 44 finished with value: 0.44059872378709514 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.16406152799357135, 'depth': 6, 'l2_leaf_reg': 1.5414217425015795, 'random_strength': 0.031599563427062785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.9038476905214048}. Best is trial 39 with value: 0.48546030982916166.

                                        feature  importance
708            envelope__envelope_Fp1_upper_max    0.083657
517            envelope__envelope_C3_lower_mean    0.075384
808           envelope__envelope_P8_upper_count    0.061135
638             envelope__envelope_F8_upper_max    0.054905
26                   eye__sac_angle_between_std    0.049759
188          eye__fix_duration_AOI_FD_None_mean    0.043735
209        eye__fix_duration_AOI_FD_Pos1_median    0.043110
870            envelope__envelope_T7_upper_mean    0.042886
869             envelope__envelope_T7_upper_max    0.042213
53       eye__sac_length_AOI_aggregated_Pos_min    0.041823
19                      eye__sac_angle_to_x_std    0.035074
761             envelope__envelope_P1_lower_min    0.035006
373               eye__corr_dim_m_2_tau_1_r_400    0.034954
540            envelope__envelope_CP1_upper_max    0.032522
844     envelope__envelope_PO7_upper_max_sample    0.032146
371                eye__corr_dim_m_2_tau_1_r_50    0.031138
404        eye__corm_euclidean_length_1_rho_250    0.029751
795      envelope__envelope_P6_upper_max_sample    0.026794
827            envelope__envelope_PO5_upper_max    0.025983
15                      eye__sac_angle_to_x_min    0.024934
303                        eye__fuzzy_m_4_r_800    0.024667
11                        eye__sac_speed_median    0.023673
309                eye__phase_entropy_m_4_tau_2    0.021770
401  eye__rec_metric_euclidean_length_1_rho_250    0.017232
687            envelope__envelope_FCz_upper_max    0.015862
744            envelope__envelope_O2_upper_mean    0.015334
801           envelope__envelope_P7_upper_count    0.015027
185         eye__fix_duration_AOI_FD_None_first    0.012952
809      envelope__envelope_P8_upper_max_sample    0.006574
17                     eye__sac_angle_to_x_mean    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.47627
              precision    recall  f1-score   support

           0       0.68      0.93      0.79       227
           1       0.42      0.10      0.16       109

    accuracy                           0.66       336
   macro avg       0.55      0.52      0.48       336
weighted avg       0.60      0.66      0.59       336

Confusion matrix:
 [[212  15]
 [ 98  11]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+envelope__target=match_mismatch__problem=binary__feat=all_features+envelope__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
60        eye__sac_speed_AOI_aggregated_Pos_min    7.090042
708            envelope__envelope_Fp1_upper_max    7.009586
19                      eye__sac_angle_to_x_std    6.714314
283    eye__fix_duration_AOI_aggregated_Pos_sum    4.872021
481            envelope__envelope_AF4_lower_min    4.648374
26                   eye__sac_angle_between_std    4.486506
792             envelope__envelope_P6_upper_max    4.395881
709           envelope__envelope_Fp1_upper_mean    4.309601
208          eye__fix_duration_AOI_FD_Pos1_mean    4.150051
190           eye__fix_duration_AOI_FD_None_std    4.113197
268  eye__fix_duration_AOI_aggregated_None_mean    4.001035
374                eye__corr_dim_m_2_tau_2_r_50    3.950980
465                               eye__imf0_max    3.936529
660           envelope__envelope_FC3_upper_mean    3.732072
505             envelope__envelope_C2_upper_max    3.703461
41      eye__sac_length_AOI_aggregated_None_min    3.148505
659            envelope__envelope_FC3_upper_max    2.964268
17                     eye__sac_angle_to_x_mean    2.921455
164                          eye__reg_mask_mean    2.870651
301                        eye__fuzzy_m_4_r_200    2.856685
366                  eye__fractal_dim_m_2_tau_2    2.816555
36        eye__sac_speed_AOI_aggregated_Neg_min    2.775292
845            envelope__envelope_PO7_lower_min    2.181037
262   eye__fix_duration_AOI_aggregated_Neg_skew    2.155785
726            envelope__envelope_Fpz_lower_min    2.010205
12                           eye__sac_speed_std    1.834077
241      eye__fix_duration_AOI_FD_Pos2_kurtosis    0.351834
10                          eye__sac_speed_mean    0.000000
11                        eye__sac_speed_median    0.000000
13                      eye__sac_speed_kurtosis    0.000000

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__ES__refitTEST

[I 2026-04-15 13:24:41,226] A new study created in memory with name: multiclass_xgb

[envelope] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+envelope__target=match_mismatch__problem=multiclass__feat=all_features+envelope__ES__refitTEST__no_neutral
X_train: (3016, 897), X_test: (336, 897)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 13:24:54,017] Trial 0 finished with value: 0.5181443857167151 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5181443857167151.
[I 2026-04-15 13:25:07,066] Trial 1 finished with value: 0.5186258142340765 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.5186258142340765.
[I 2026-04-15 13:25:20,349] Trial 2 finished with value: 0.5249175832175264 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5249175832175264.
[I 2026-04-15 13:25:30,651] Trial 3 finished with value: 0.526793802898184 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.526793802898184.
[I 2026-04-15 13:25:39,371] Trial 4 finished with value: 0.5180653650648734 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.526793802898184.
[I 2026-04-15 13:25:52,489] Trial 5 finished with value: 0.5093586078955579 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.526793802898184.
[I 2026-04-15 13:26:00,550] Trial 6 finished with value: 0.531510151254577 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.531510151254577.
[I 2026-04-15 13:26:15,759] Trial 7 finished with value: 0.5312488355295563 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.531510151254577.
[I 2026-04-15 13:26:25,478] Trial 8 finished with value: 0.4921398403365801 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.531510151254577.
[I 2026-04-15 13:26:39,816] Trial 9 finished with value: 0.5173291383876268 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.531510151254577.
[I 2026-04-15 13:26:46,331] Trial 10 finished with value: 0.536846284418669 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 10 with value: 0.536846284418669.
[I 2026-04-15 13:26:52,780] Trial 11 finished with value: 0.5513680991689823 and parameters: {'learning_rate': 0.19928490475258703, 'max_depth': 3, 'min_child_weight': 2.3108399558144663, 'subsample': 0.7003857515532862, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.5525904909866688, 'reg_alpha': 0.000185939809238877, 'reg_lambda': 5.991143401742846}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:00,768] Trial 12 finished with value: 0.5440449436946426 and parameters: {'learning_rate': 0.19001657682154638, 'max_depth': 3, 'min_child_weight': 1.0277001574826408, 'subsample': 0.7008546103358549, 'colsample_bytree': 0.845235942520865, 'gamma': 1.4415935609939878, 'reg_alpha': 0.00010846875746792476, 'reg_lambda': 8.615080016175616}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:09,173] Trial 13 finished with value: 0.5444888037834119 and parameters: {'learning_rate': 0.1140750661511307, 'max_depth': 3, 'min_child_weight': 2.2579846872875393, 'subsample': 0.7024129757389838, 'colsample_bytree': 0.8176955515976587, 'gamma': 1.397199681337342, 'reg_alpha': 0.00018303207295231196, 'reg_lambda': 9.723756582880274}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:17,551] Trial 14 finished with value: 0.5416341196762052 and parameters: {'learning_rate': 0.12828589692956935, 'max_depth': 4, 'min_child_weight': 2.2726569545045745, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8097524232703589, 'gamma': 1.417518741468783, 'reg_alpha': 0.002748885779508337, 'reg_lambda': 0.921886521195144}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:26,093] Trial 15 finished with value: 0.521751345572838 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 3, 'min_child_weight': 2.4370747834999373, 'subsample': 0.7534685419054485, 'colsample_bytree': 0.8816898523164896, 'gamma': 1.2513887824418548, 'reg_alpha': 0.0014549851997912573, 'reg_lambda': 0.00016599250040776937}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:34,709] Trial 16 finished with value: 0.5295807894101462 and parameters: {'learning_rate': 0.0986464214048007, 'max_depth': 4, 'min_child_weight': 2.5038668224918172, 'subsample': 0.8251111348819288, 'colsample_bytree': 0.8136626354725327, 'gamma': 1.6970684105452913, 'reg_alpha': 0.00010336002589443003, 'reg_lambda': 2.048298914217056}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:43,294] Trial 17 finished with value: 0.539080448334658 and parameters: {'learning_rate': 0.07432476880169292, 'max_depth': 3, 'min_child_weight': 4.907699675577318, 'subsample': 0.7017933899797236, 'colsample_bytree': 0.8916128199512082, 'gamma': 0.7974598064407175, 'reg_alpha': 0.009143706837700352, 'reg_lambda': 0.2745772615328829}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:50,358] Trial 18 finished with value: 0.5125283958085689 and parameters: {'learning_rate': 0.14381036677031409, 'max_depth': 4, 'min_child_weight': 1.8746330709514636, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.7811134247031547, 'gamma': 1.9962745598251384, 'reg_alpha': 0.0007713572458478184, 'reg_lambda': 0.011397783591272139}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:27:57,644] Trial 19 finished with value: 0.5354629478316555 and parameters: {'learning_rate': 0.091475771534705, 'max_depth': 3, 'min_child_weight': 2.705197594750985, 'subsample': 0.8198443939626202, 'colsample_bytree': 0.840235300203723, 'gamma': 1.2763326476302224, 'reg_alpha': 0.00033643546568832736, 'reg_lambda': 1.7834236291570933}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:04,470] Trial 20 finished with value: 0.5346268363075943 and parameters: {'learning_rate': 0.14548393835232945, 'max_depth': 4, 'min_child_weight': 1.414159861066715, 'subsample': 0.7453760182978487, 'colsample_bytree': 0.8181135886080299, 'gamma': 1.6601980324494632, 'reg_alpha': 0.0018271384911770086, 'reg_lambda': 9.793285621082266}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:11,727] Trial 21 finished with value: 0.5322701497829674 and parameters: {'learning_rate': 0.19853471970723305, 'max_depth': 3, 'min_child_weight': 1.0260861692338186, 'subsample': 0.7057801732079598, 'colsample_bytree': 0.8504595907589511, 'gamma': 1.4319318601240472, 'reg_alpha': 0.00020217695115341095, 'reg_lambda': 4.585383572893035}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:19,359] Trial 22 finished with value: 0.5315609741940753 and parameters: {'learning_rate': 0.1513607545207894, 'max_depth': 3, 'min_child_weight': 1.317989523733909, 'subsample': 0.7363640090107189, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.5759488496354166, 'reg_alpha': 0.00011283383126812055, 'reg_lambda': 9.83426268524823}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:27,566] Trial 23 finished with value: 0.5190266354341663 and parameters: {'learning_rate': 0.1968427417089621, 'max_depth': 4, 'min_child_weight': 2.134766170514464, 'subsample': 0.7636558716165969, 'colsample_bytree': 0.9057249139369133, 'gamma': 1.2638955400718501, 'reg_alpha': 0.0008106096728773281, 'reg_lambda': 3.18529168172313}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:35,964] Trial 24 finished with value: 0.5225125686453114 and parameters: {'learning_rate': 0.10840753450762841, 'max_depth': 3, 'min_child_weight': 3.1552585445044166, 'subsample': 0.7000682503389764, 'colsample_bytree': 0.8421036227771447, 'gamma': 0.8638280093819819, 'reg_alpha': 0.00021365482294930974, 'reg_lambda': 0.20910257481992103}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:44,466] Trial 25 finished with value: 0.5180672693015567 and parameters: {'learning_rate': 0.16151955061333395, 'max_depth': 4, 'min_child_weight': 1.5799781807171152, 'subsample': 0.728458558021207, 'colsample_bytree': 0.8715573772461903, 'gamma': 1.4900456236440405, 'reg_alpha': 0.0053757930857464015, 'reg_lambda': 1.2564116167641186}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:28:53,293] Trial 26 finished with value: 0.5308161146766989 and parameters: {'learning_rate': 0.06445009916740925, 'max_depth': 3, 'min_child_weight': 1.1973694573613087, 'subsample': 0.7998041232261551, 'colsample_bytree': 0.9117715346100396, 'gamma': 1.840142611852237, 'reg_alpha': 0.00010170183971949589, 'reg_lambda': 3.6092398925172278}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:00,680] Trial 27 finished with value: 0.5195581916533096 and parameters: {'learning_rate': 0.12516131953057943, 'max_depth': 8, 'min_child_weight': 6.613138572831469, 'subsample': 0.7580785394426199, 'colsample_bytree': 0.8315045947189968, 'gamma': 1.2958475327518477, 'reg_alpha': 6.965845760085163, 'reg_lambda': 0.3718850987634851}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:10,427] Trial 28 finished with value: 0.5184931889903066 and parameters: {'learning_rate': 0.1355852907707668, 'max_depth': 5, 'min_child_weight': 3.7985560082995815, 'subsample': 0.7194687653268301, 'colsample_bytree': 0.7919926839218181, 'gamma': 1.1259420914792355, 'reg_alpha': 0.00042959350941529335, 'reg_lambda': 4.654603114018479}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:19,657] Trial 29 finished with value: 0.5298599029980705 and parameters: {'learning_rate': 0.08194044450484951, 'max_depth': 4, 'min_child_weight': 2.893735181164301, 'subsample': 0.7216031359001228, 'colsample_bytree': 0.862264901697844, 'gamma': 0.9339451847591622, 'reg_alpha': 0.0005441429906987551, 'reg_lambda': 1.1997008452947158}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:35,464] Trial 30 finished with value: 0.5020383224749045 and parameters: {'learning_rate': 0.04928774610107739, 'max_depth': 7, 'min_child_weight': 1.898531469403904, 'subsample': 0.8741863509676351, 'colsample_bytree': 0.7712563201152532, 'gamma': 0.6078691954282296, 'reg_alpha': 0.0010051772491623603, 'reg_lambda': 0.018502244216073403}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:43,491] Trial 31 finished with value: 0.5489028972693366 and parameters: {'learning_rate': 0.16866110400560339, 'max_depth': 4, 'min_child_weight': 2.2393334492959984, 'subsample': 0.8369390560781191, 'colsample_bytree': 0.8085173271394611, 'gamma': 1.3827678692991425, 'reg_alpha': 0.003295761051311551, 'reg_lambda': 1.0122234047207779}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:49,737] Trial 32 finished with value: 0.5408869797796998 and parameters: {'learning_rate': 0.16559893626701808, 'max_depth': 3, 'min_child_weight': 3.7364386257275437, 'subsample': 0.9916144715572369, 'colsample_bytree': 0.8252128293185987, 'gamma': 1.7715376479949836, 'reg_alpha': 0.00021715124189929002, 'reg_lambda': 5.2330693225521046}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:29:56,638] Trial 33 finished with value: 0.5086674098656815 and parameters: {'learning_rate': 0.17433612907187754, 'max_depth': 4, 'min_child_weight': 2.1149522985505276, 'subsample': 0.93574192454753, 'colsample_bytree': 0.7987307824513826, 'gamma': 1.584339698609923, 'reg_alpha': 0.0026738538315449795, 'reg_lambda': 2.097724229295805}. Best is trial 11 with value: 0.5513680991689823.
[I 2026-04-15 13:30:05,080] Trial 34 finished with value: 0.5523340116496865 and parameters: {'learning_rate': 0.10785698842028985, 'max_depth': 3, 'min_child_weight': 1.6525665498751003, 'subsample': 0.8140166545284996, 'colsample_bytree': 0.7558478440961497, 'gamma': 1.5517858107119737, 'reg_alpha': 0.009501422799541892, 'reg_lambda': 5.425564053406996}. Best is trial 34 with value: 0.5523340116496865.
[I 2026-04-15 13:30:13,265] Trial 35 finished with value: 0.5336016978910016 and parameters: {'learning_rate': 0.11253699409043781, 'max_depth': 3, 'min_child_weight': 1.6977867465937477, 'subsample': 0.8860802273321252, 'colsample_bytree': 0.7526738587322793, 'gamma': 1.3506967230937583, 'reg_alpha': 0.006205778570731329, 'reg_lambda': 2.956469982746642}. Best is trial 34 with value: 0.5523340116496865.
[I 2026-04-15 13:30:21,843] Trial 36 finished with value: 0.5533064140396461 and parameters: {'learning_rate': 0.10297721572471759, 'max_depth': 4, 'min_child_weight': 1.9528646230103912, 'subsample': 0.8501672079283927, 'colsample_bytree': 0.7197524868651167, 'gamma': 1.572400366578588, 'reg_alpha': 0.04627798289876159, 'reg_lambda': 0.4848873317314768}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:30:32,009] Trial 37 finished with value: 0.5449960210384536 and parameters: {'learning_rate': 0.06526963907561349, 'max_depth': 5, 'min_child_weight': 1.8814124435338269, 'subsample': 0.8485520940701623, 'colsample_bytree': 0.7163082187007225, 'gamma': 1.5916149060578055, 'reg_alpha': 0.013602008459904821, 'reg_lambda': 0.4705354123686576}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:30:40,811] Trial 38 finished with value: 0.533704776161259 and parameters: {'learning_rate': 0.08701510862509343, 'max_depth': 5, 'min_child_weight': 1.501656839166524, 'subsample': 0.8177205153400385, 'colsample_bytree': 0.726077840871908, 'gamma': 1.7489188585452142, 'reg_alpha': 0.07228981101866326, 'reg_lambda': 0.1207064440810526}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:30:49,063] Trial 39 finished with value: 0.5267595345574995 and parameters: {'learning_rate': 0.07382801158040468, 'max_depth': 4, 'min_child_weight': 1.9952789138326694, 'subsample': 0.9077211070856394, 'colsample_bytree': 0.7656894433196361, 'gamma': 1.1956454568327737, 'reg_alpha': 0.06438122692374232, 'reg_lambda': 0.673384066015158}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:30:56,121] Trial 40 finished with value: 0.536239092293691 and parameters: {'learning_rate': 0.09710329241274235, 'max_depth': 5, 'min_child_weight': 2.7449682819859276, 'subsample': 0.8356363449627755, 'colsample_bytree': 0.702633193287773, 'gamma': 1.881896682697966, 'reg_alpha': 0.48156333244243904, 'reg_lambda': 0.055303069191364546}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:31:05,797] Trial 41 finished with value: 0.5315832343603164 and parameters: {'learning_rate': 0.06283498441116185, 'max_depth': 5, 'min_child_weight': 1.7236691277727003, 'subsample': 0.85452686183422, 'colsample_bytree': 0.7232218325188241, 'gamma': 1.5959522458739879, 'reg_alpha': 0.013238594206176381, 'reg_lambda': 0.5038704087822707}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:31:18,258] Trial 42 finished with value: 0.5331359300249852 and parameters: {'learning_rate': 0.04290223393397782, 'max_depth': 5, 'min_child_weight': 1.197887898534103, 'subsample': 0.8718542257601215, 'colsample_bytree': 0.716670800383706, 'gamma': 1.542146774799366, 'reg_alpha': 0.024635343027192252, 'reg_lambda': 0.1495432366660679}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:31:31,630] Trial 43 finished with value: 0.5054072620036073 and parameters: {'learning_rate': 0.042712458651530824, 'max_depth': 7, 'min_child_weight': 1.8165337982001901, 'subsample': 0.8021950003510748, 'colsample_bytree': 0.7311446935731623, 'gamma': 1.6495369411048222, 'reg_alpha': 0.012764110667093475, 'reg_lambda': 0.8742279694602458}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:31:43,082] Trial 44 finished with value: 0.5458744734702964 and parameters: {'learning_rate': 0.035311579768541934, 'max_depth': 4, 'min_child_weight': 2.490162234417805, 'subsample': 0.8552816180528644, 'colsample_bytree': 0.7468455521672392, 'gamma': 1.7738486094024872, 'reg_alpha': 0.041527448390983115, 'reg_lambda': 0.396603100286399}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:31:53,528] Trial 45 finished with value: 0.5314578728714059 and parameters: {'learning_rate': 0.025280490228586118, 'max_depth': 4, 'min_child_weight': 3.2834545100933705, 'subsample': 0.8818965825242624, 'colsample_bytree': 0.7493499225436079, 'gamma': 1.7971690896936114, 'reg_alpha': 0.04778432980344779, 'reg_lambda': 1.6088563908593108}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:32:03,348] Trial 46 finished with value: 0.5453121735984215 and parameters: {'learning_rate': 0.03458781939961334, 'max_depth': 4, 'min_child_weight': 2.350889580078091, 'subsample': 0.863035707174753, 'colsample_bytree': 0.7798773994763937, 'gamma': 1.9227275373261483, 'reg_alpha': 0.12749357951172122, 'reg_lambda': 0.03274489100704657}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:32:11,994] Trial 47 finished with value: 0.5492820239927405 and parameters: {'learning_rate': 0.028728275782731832, 'max_depth': 3, 'min_child_weight': 2.976073313066358, 'subsample': 0.8366268329521419, 'colsample_bytree': 0.7406005327573336, 'gamma': 1.7252620302705817, 'reg_alpha': 0.37183354772932914, 'reg_lambda': 0.08849090076929614}. Best is trial 36 with value: 0.5533064140396461.
[I 2026-04-15 13:32:21,686] Trial 48 finished with value: 0.5319811988305592 and parameters: {'learning_rate': 0.020402705721698684, 'max_depth': 3, 'min_child_weight': 4.627554498842088, 'subsample': 0.8340460375567512, 'colsample_bytree': 0.7379637591786586, 'gamma': 0.08149559731807443, 'reg_alpha': 0.5568544526055085, 'reg_lambda': 0.004371197626165927}. Best is trial 36 with value: 0.5533064140396461.

[I 2026-04-15 13:40:02,380] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 13:40:12,167] Trial 0 finished with value: 0.4789735090295473 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4789735090295473.
[I 2026-04-15 13:40:22,667] Trial 1 finished with value: 0.520328452418778 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.520328452418778.
[I 2026-04-15 13:40:42,623] Trial 2 finished with value: 0.5090387348373587 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.520328452418778.
[I 2026-04-15 13:41:17,638] Trial 3 finished with value: 0.5171312377136661 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.520328452418778.
[I 2026-04-15 13:42:14,205] Trial 4 finished with value: 0.5052128939750519 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.520328452418778.
[I 2026-04-15 13:43:11,662] Trial 5 finished with value: 0.5227080147968594 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:43:46,101] Trial 6 finished with value: 0.4911458418785052 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:44:24,102] Trial 7 finished with value: 0.5022351917736031 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:45:45,051] Trial 8 finished with value: 0.492301722547478 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:46:19,963] Trial 9 finished with value: 0.5037278748819247 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:46:29,876] Trial 10 finished with value: 0.5106155014116871 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13758961780051104, 'depth': 5, 'l2_leaf_reg': 3.488642800600504, 'random_strength': 0.9932352657390002, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2288521688237315}. Best is trial 5 with value: 0.5227080147968594.
[I 2026-04-15 13:46:41,614] Trial 11 finished with value: 0.531895473272811 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020555942730797597, 'depth': 4, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.6685793167353322, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9503537613945793}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:46:55,419] Trial 12 finished with value: 0.49834209343217173 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03703255942764144, 'depth': 5, 'l2_leaf_reg': 4.9111270507640645, 'random_strength': 0.7070480378024606, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9946818027860475}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:47:04,903] Trial 13 finished with value: 0.49593547913864006 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11898154973533921, 'depth': 5, 'l2_leaf_reg': 2.869741965176845, 'random_strength': 0.8189963197512329, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.6792923137266189}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:48:29,225] Trial 14 finished with value: 0.5014090801834732 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032189307821966336, 'depth': 8, 'l2_leaf_reg': 5.354459614051499, 'random_strength': 0.547821525114958, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.916229110655147}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:48:36,473] Trial 15 finished with value: 0.5099888124065355 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05218876227232107, 'depth': 4, 'l2_leaf_reg': 6.616683977629639, 'random_strength': 0.8090150166544848, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.5090916719722371}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:48:55,804] Trial 16 finished with value: 0.49189382897316547 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11369048720900607, 'depth': 6, 'l2_leaf_reg': 19.386044555309596, 'random_strength': 0.9870122995978218, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.4439866348375925}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:49:06,443] Trial 17 finished with value: 0.5086812790773775 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0593808534112181, 'depth': 5, 'l2_leaf_reg': 2.9195098060219813, 'random_strength': 0.4440752281517034, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8761581007262902}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:49:49,333] Trial 18 finished with value: 0.5110737395011069 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0290625826214462, 'depth': 7, 'l2_leaf_reg': 10.99008129788996, 'random_strength': 0.6026864810715507, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 4.284517710941218}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:51:41,114] Trial 19 finished with value: 0.5148927203656632 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020795590480586056, 'depth': 8, 'l2_leaf_reg': 2.0217637164737443, 'random_strength': 0.7726007237334462, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8618579713400556}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:51:47,482] Trial 20 finished with value: 0.4887845131836692 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18560668806854996, 'depth': 4, 'l2_leaf_reg': 7.44489054089179, 'random_strength': 0.9045587947773057, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9992519999660833}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:51:57,575] Trial 21 finished with value: 0.5150004391670246 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026206923687310084, 'depth': 4, 'l2_leaf_reg': 14.873401389553072, 'random_strength': 0.24449374386947742, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6125052081172798}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:52:04,971] Trial 22 finished with value: 0.5235832922964543 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022728927690328804, 'depth': 4, 'l2_leaf_reg': 13.085348682130165, 'random_strength': 0.0010084962427511224, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8143059951170093}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:52:21,210] Trial 23 finished with value: 0.4953083614961555 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020141104326691636, 'depth': 5, 'l2_leaf_reg': 12.444022113559406, 'random_strength': 0.7366880152694889, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8162462872417852}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:52:44,732] Trial 24 finished with value: 0.5291272998928769 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0378273644365385, 'depth': 6, 'l2_leaf_reg': 18.714489129896585, 'random_strength': 0.007828742607430383, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9362825509069933}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:53:04,120] Trial 25 finished with value: 0.5186103786515927 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03901140793251274, 'depth': 6, 'l2_leaf_reg': 18.64456720034626, 'random_strength': 0.021872675016628707, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9260976481198112}. Best is trial 11 with value: 0.531895473272811.
[I 2026-04-15 13:53:11,267] Trial 26 finished with value: 0.5363612211579694 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02475273053567768, 'depth': 4, 'l2_leaf_reg': 19.14614474201571, 'random_strength': 0.07840138956483744, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9487191219824307}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:21,063] Trial 27 finished with value: 0.500845336305366 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032268980599861455, 'depth': 5, 'l2_leaf_reg': 19.486782317627895, 'random_strength': 0.11077527654487317, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9457430520716483}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:28,599] Trial 28 finished with value: 0.5346561122760145 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025965680855705397, 'depth': 4, 'l2_leaf_reg': 9.041079381517344, 'random_strength': 0.21141492922357286, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9555263645550741}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:38,287] Trial 29 finished with value: 0.5153654758838024 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027235477083433848, 'depth': 4, 'l2_leaf_reg': 9.18580056385939, 'random_strength': 0.1866034951911129, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8760713893717211}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:46,181] Trial 30 finished with value: 0.5117542793515425 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024280522470528046, 'depth': 4, 'l2_leaf_reg': 5.9318742532235085, 'random_strength': 0.3907160585984534, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.966114685821196}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:52,248] Trial 31 finished with value: 0.5272680013577014 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031569539620450955, 'depth': 4, 'l2_leaf_reg': 16.116256770815575, 'random_strength': 0.08722614983936845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9174729610424477}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:53:59,216] Trial 32 finished with value: 0.5147780904916366 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.038524891500961694, 'depth': 4, 'l2_leaf_reg': 12.453464730623887, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9662502026981846}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:54:12,288] Trial 33 finished with value: 0.5188796222030458 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024267846717355695, 'depth': 5, 'l2_leaf_reg': 16.58596982634627, 'random_strength': 0.22102000649836664, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8966908048057997}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:54:20,330] Trial 34 finished with value: 0.5064470629102324 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028571662952138154, 'depth': 4, 'l2_leaf_reg': 8.601623927999245, 'random_strength': 0.3033993327017441, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9632276131303642}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:54:35,987] Trial 35 finished with value: 0.5140730595247185 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.034929543541021055, 'depth': 6, 'l2_leaf_reg': 11.609660273808593, 'random_strength': 0.1292874688665694, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9470806658701122}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:54:47,838] Trial 36 finished with value: 0.5252714700645503 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04460759505655829, 'depth': 5, 'l2_leaf_reg': 14.819201419542624, 'random_strength': 0.07780153563993641, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.859682672732351}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:54:53,673] Trial 37 finished with value: 0.5091311435451248 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02315480629344739, 'depth': 4, 'l2_leaf_reg': 19.902612663329954, 'random_strength': 0.029339924719945315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9868579285299688}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:55:01,256] Trial 38 finished with value: 0.5225500803546108 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.057935982273818215, 'depth': 4, 'l2_leaf_reg': 14.099311875539653, 'random_strength': 0.5619381427872815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9012970737883077}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:55:34,446] Trial 39 finished with value: 0.5204618314861872 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.041337759841264594, 'depth': 7, 'l2_leaf_reg': 7.644617357989993, 'random_strength': 0.26858668462040874, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.937991900962857}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:55:57,887] Trial 40 finished with value: 0.5105216526095018 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029729219037791032, 'depth': 6, 'l2_leaf_reg': 10.06795044277389, 'random_strength': 0.3799062750278092, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8361259072587689}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:56:05,484] Trial 41 finished with value: 0.5255104853020354 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03334999261049111, 'depth': 4, 'l2_leaf_reg': 16.394979975372884, 'random_strength': 0.06889463647097584, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9112048765476347}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:56:11,094] Trial 42 finished with value: 0.510855196134112 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024975581974855367, 'depth': 4, 'l2_leaf_reg': 16.809751096447275, 'random_strength': 0.08821064886313636, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9649594679622218}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:56:18,290] Trial 43 finished with value: 0.5357215018917607 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02208276206210579, 'depth': 4, 'l2_leaf_reg': 14.8119609687331, 'random_strength': 0.041972719480406706, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9310137125974756}. Best is trial 26 with value: 0.5363612211579694.
[I 2026-04-15 13:56:31,668] Trial 44 finished with value: 0.5133010916693069 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.021856518434661024, 'depth': 5, 'l2_leaf_reg': 14.175445471180646, 'random_strength': 0.16521428129820367, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.950156439487531}. Best is trial 26 with value: 0.5363612211579694.

                                 feature  importance
213    eye__fix_duration_AOI_FD_Pos1_sum   36.424238
207    eye__fix_duration_AOI_FD_Pos1_max   20.593943
465                        eye__imf0_max   12.671508
0                    eye__sac_length_min   12.566909
394   eye__det_euclidean_length_1_rho_25    7.655101
422  eye__det_euclidean_length_2_rho_250    6.696906
190    eye__fix_duration_AOI_FD_None_std    3.391396
2                   eye__sac_length_mean    0.000000
3                 eye__sac_length_median    0.000000
4                    eye__sac_length_std    0.000000
5                    eye__sac_length_sum    0.000000
6               eye__sac_length_kurtosis    0.000000
7                   eye__sac_length_skew    0.000000
840   envelope__envelope_PO6_lower_count    0.000000
9                     eye__sac_speed_max    0.000000
10                   eye__sac_speed_mean    0.000000
11                 eye__sac_speed_median    0.000000
12                    eye__sac_speed_std    0.000000
13               eye__sac_speed_kurtosis    0.000000
14                   eye__sac_speed_skew    0.000000
15               eye__sac_angle_to_x_min    0.000000
16               eye__sac_angle_to_x_max    0.000000
17              eye__sac_angle_to_x_mean    0.000000
18            eye__sac_angle_to_x_median    0.000000
19               eye__sac_angle_to_x_std    0.000000
20          eye__sac_angle_to_x_kurtosis    0.000000
21              eye__sac_angle_to_x_skew    0.000000
22            eye__sac_angle_between_min    0.000000
23            eye__sac_angle_between_max    0.000000
24           eye__sac_angle_between_mean    0.000000

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__ES__refitTEST

[I 2026-04-15 13:57:56,762] A new study created in memory with name: binary_xgb

[envelope] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__ES__refitTEST__no_neutral
X_train: (3016, 897), X_test: (336, 897)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 13:58:05,500] Trial 0 finished with value: 0.5235763117925663 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5235763117925663.
[I 2026-04-15 13:58:14,217] Trial 1 finished with value: 0.5375638495093733 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.5375638495093733.
[I 2026-04-15 13:58:24,244] Trial 2 finished with value: 0.5308078946893877 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 1 with value: 0.5375638495093733.
[I 2026-04-15 13:58:32,505] Trial 3 finished with value: 0.5218978978876279 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 1 with value: 0.5375638495093733.
[I 2026-04-15 13:58:41,110] Trial 4 finished with value: 0.5443885131645062 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.5443885131645062.
[I 2026-04-15 13:58:50,445] Trial 5 finished with value: 0.5565944247762218 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 5 with value: 0.5565944247762218.
[I 2026-04-15 13:58:57,060] Trial 6 finished with value: 0.5501627106975562 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 5 with value: 0.5565944247762218.
[I 2026-04-15 13:59:07,680] Trial 7 finished with value: 0.562605052852558 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 13:59:14,541] Trial 8 finished with value: 0.5381917448932274 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 13:59:27,750] Trial 9 finished with value: 0.5556056498194185 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 13:59:38,536] Trial 10 finished with value: 0.4960364808312292 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 6.0796977549919955, 'subsample': 0.8386834652924317, 'colsample_bytree': 0.9984958032960148, 'gamma': 1.343695477455153, 'reg_alpha': 9.157669588453277, 'reg_lambda': 7.2116802788205145}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 13:59:48,183] Trial 11 finished with value: 0.5523519131578851 and parameters: {'learning_rate': 0.05192425810192299, 'max_depth': 7, 'min_child_weight': 9.82128943308808, 'subsample': 0.9990638778029864, 'colsample_bytree': 0.8277506537128274, 'gamma': 1.2615827674464564, 'reg_alpha': 0.012646341639534743, 'reg_lambda': 0.009324403762925917}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 13:59:58,516] Trial 12 finished with value: 0.5445544097062145 and parameters: {'learning_rate': 0.03677282124112453, 'max_depth': 7, 'min_child_weight': 6.832289877926147, 'subsample': 0.9227014502820593, 'colsample_bytree': 0.8676669111635186, 'gamma': 0.5934862123369633, 'reg_alpha': 0.0030093802418649854, 'reg_lambda': 0.009609695076519731}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 14:00:08,510] Trial 13 finished with value: 0.561237667295387 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 6, 'min_child_weight': 2.397388022036258, 'subsample': 0.830708901865747, 'colsample_bytree': 0.7012088256639494, 'gamma': 0.8109762788390166, 'reg_alpha': 0.00039428482627718264, 'reg_lambda': 0.1455342066074402}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 14:00:19,220] Trial 14 finished with value: 0.5403786698344517 and parameters: {'learning_rate': 0.07090426368435447, 'max_depth': 8, 'min_child_weight': 2.3840195928535883, 'subsample': 0.8362591830089495, 'colsample_bytree': 0.7031145958882905, 'gamma': 0.8188697774435277, 'reg_alpha': 0.00010631849056947566, 'reg_lambda': 0.22512724496605152}. Best is trial 7 with value: 0.562605052852558.
[I 2026-04-15 14:00:28,867] Trial 15 finished with value: 0.5672354307688054 and parameters: {'learning_rate': 0.028737984629152037, 'max_depth': 4, 'min_child_weight': 2.4370747834999373, 'subsample': 0.806374713062561, 'colsample_bytree': 0.8186764859196548, 'gamma': 1.4919749451196884, 'reg_alpha': 0.0012293364524432959, 'reg_lambda': 0.00016599250040776937}. Best is trial 15 with value: 0.5672354307688054.
[I 2026-04-15 14:00:36,824] Trial 16 finished with value: 0.5683397683255281 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 3, 'min_child_weight': 1.0502021255959635, 'subsample': 0.8041114582782714, 'colsample_bytree': 0.8183434224850645, 'gamma': 1.5542610676395547, 'reg_alpha': 0.001594350622226877, 'reg_lambda': 0.000366051516059916}. Best is trial 16 with value: 0.5683397683255281.
[I 2026-04-15 14:00:43,767] Trial 17 finished with value: 0.5625917756960921 and parameters: {'learning_rate': 0.027860714128807258, 'max_depth': 3, 'min_child_weight': 1.2305180646191543, 'subsample': 0.8715702573267258, 'colsample_bytree': 0.8131557307738727, 'gamma': 1.53124147749681, 'reg_alpha': 0.0014265183507096556, 'reg_lambda': 0.00012713197739349708}. Best is trial 16 with value: 0.5683397683255281.
[I 2026-04-15 14:00:54,357] Trial 18 finished with value: 0.5764449337399583 and parameters: {'learning_rate': 0.025878949905868424, 'max_depth': 4, 'min_child_weight': 1.115133317760315, 'subsample': 0.7446808508456166, 'colsample_bytree': 0.8939539047445909, 'gamma': 1.5062740430664145, 'reg_alpha': 0.00011324883295395535, 'reg_lambda': 0.00012717420925272599}. Best is trial 18 with value: 0.5764449337399583.
[I 2026-04-15 14:01:03,857] Trial 19 finished with value: 0.54673980215032 and parameters: {'learning_rate': 0.04046238467289684, 'max_depth': 4, 'min_child_weight': 1.0169866894031812, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.905359217093405, 'gamma': 1.717736886590301, 'reg_alpha': 0.00011558556454002054, 'reg_lambda': 0.0004400061916069779}. Best is trial 18 with value: 0.5764449337399583.
[I 2026-04-15 14:01:13,058] Trial 20 finished with value: 0.5600554392390182 and parameters: {'learning_rate': 0.026511122210527274, 'max_depth': 3, 'min_child_weight': 1.1607241639893446, 'subsample': 0.7258082682623863, 'colsample_bytree': 0.8466445670931371, 'gamma': 1.3137326012601065, 'reg_alpha': 0.0003089447741034449, 'reg_lambda': 0.0030260406883185482}. Best is trial 18 with value: 0.5764449337399583.
[I 2026-04-15 14:01:25,505] Trial 21 finished with value: 0.5497845878464875 and parameters: {'learning_rate': 0.020579886320611702, 'max_depth': 4, 'min_child_weight': 1.654160776142618, 'subsample': 0.7525865500684601, 'colsample_bytree': 0.7913915931745173, 'gamma': 1.4447631229311897, 'reg_alpha': 0.0019476719421755884, 'reg_lambda': 0.00011527206709895885}. Best is trial 18 with value: 0.5764449337399583.
[I 2026-04-15 14:01:36,901] Trial 22 finished with value: 0.5871648093018706 and parameters: {'learning_rate': 0.02934164705222114, 'max_depth': 4, 'min_child_weight': 2.221021411353977, 'subsample': 0.8095351471456746, 'colsample_bytree': 0.8866358056959667, 'gamma': 1.5722276237792954, 'reg_alpha': 0.0008586984104416208, 'reg_lambda': 0.00032761879353840454}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:01:47,079] Trial 23 finished with value: 0.5679408986726632 and parameters: {'learning_rate': 0.03168261847650606, 'max_depth': 3, 'min_child_weight': 2.029251808961463, 'subsample': 0.7568909134771207, 'colsample_bytree': 0.9023242543144618, 'gamma': 1.6885949466891772, 'reg_alpha': 0.006607105004233236, 'reg_lambda': 0.0003999623629198284}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:01:59,319] Trial 24 finished with value: 0.5830610330329534 and parameters: {'learning_rate': 0.024112010417207556, 'max_depth': 4, 'min_child_weight': 1.0085761944657667, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.8497673240355377, 'gamma': 1.9561901364543655, 'reg_alpha': 0.0003101767111808309, 'reg_lambda': 0.0003928580701871986}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:02:10,421] Trial 25 finished with value: 0.5514154659576159 and parameters: {'learning_rate': 0.022972015958630753, 'max_depth': 4, 'min_child_weight': 1.334323699100925, 'subsample': 0.8102664503344786, 'colsample_bytree': 0.8914303169437323, 'gamma': 1.981048332578869, 'reg_alpha': 0.0002263036718414207, 'reg_lambda': 0.003627585427352053}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:02:22,205] Trial 26 finished with value: 0.5437666877565686 and parameters: {'learning_rate': 0.03856336294174205, 'max_depth': 5, 'min_child_weight': 1.4752675003544249, 'subsample': 0.8837196141420148, 'colsample_bytree': 0.8544314162170806, 'gamma': 1.803589842305922, 'reg_alpha': 0.000815265240565209, 'reg_lambda': 0.0008496108028930329}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:02:34,881] Trial 27 finished with value: 0.5836941224241984 and parameters: {'learning_rate': 0.020082082119177704, 'max_depth': 4, 'min_child_weight': 4.206575405259022, 'subsample': 0.8238986764828641, 'colsample_bytree': 0.9148564350193288, 'gamma': 1.9643651260840589, 'reg_alpha': 0.000222979762149347, 'reg_lambda': 0.00022914736134552592}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:02:47,128] Trial 28 finished with value: 0.558240897657327 and parameters: {'learning_rate': 0.021554269120633303, 'max_depth': 5, 'min_child_weight': 4.40685513354448, 'subsample': 0.8540572934218149, 'colsample_bytree': 0.9204418701010977, 'gamma': 1.9968368359202997, 'reg_alpha': 0.00024997711943880793, 'reg_lambda': 0.01873366831600227}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:02:55,352] Trial 29 finished with value: 0.5481663559816913 and parameters: {'learning_rate': 0.04486960055375249, 'max_depth': 4, 'min_child_weight': 3.879228757044569, 'subsample': 0.8230102948768425, 'colsample_bytree': 0.9694004158218161, 'gamma': 1.820488829810749, 'reg_alpha': 0.0005114460398121012, 'reg_lambda': 0.000300891603117569}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:02,700] Trial 30 finished with value: 0.5741408191299298 and parameters: {'learning_rate': 0.053052340918608505, 'max_depth': 4, 'min_child_weight': 2.897068892285185, 'subsample': 0.8888099480923972, 'colsample_bytree': 0.8700860498568088, 'gamma': 1.6350559932181143, 'reg_alpha': 0.0006576371289967251, 'reg_lambda': 0.0014146617327536785}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:11,827] Trial 31 finished with value: 0.5466809756349797 and parameters: {'learning_rate': 0.023489203320145684, 'max_depth': 4, 'min_child_weight': 5.004691167111767, 'subsample': 0.7212312591123682, 'colsample_bytree': 0.8451733807481742, 'gamma': 1.8493692519829772, 'reg_alpha': 0.00010992096306877786, 'reg_lambda': 0.00021843067634206832}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:20,599] Trial 32 finished with value: 0.5466289084362799 and parameters: {'learning_rate': 0.02500689179908352, 'max_depth': 3, 'min_child_weight': 3.241318118231724, 'subsample': 0.7683256718565565, 'colsample_bytree': 0.9173196001522652, 'gamma': 1.2039838667759508, 'reg_alpha': 0.00020396100374007805, 'reg_lambda': 0.00010288098273456854}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:30,049] Trial 33 finished with value: 0.5388575424347013 and parameters: {'learning_rate': 0.030439578981250878, 'max_depth': 4, 'min_child_weight': 2.10094040343661, 'subsample': 0.8465528294920363, 'colsample_bytree': 0.8780504658531091, 'gamma': 1.417664400061721, 'reg_alpha': 0.0005672055249648491, 'reg_lambda': 0.0006827714469031514}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:41,349] Trial 34 finished with value: 0.5289692160907663 and parameters: {'learning_rate': 0.03413843768260688, 'max_depth': 5, 'min_child_weight': 1.140184121738581, 'subsample': 0.8156203952460893, 'colsample_bytree': 0.8937226276679157, 'gamma': 1.7352187582316627, 'reg_alpha': 0.003371303594580621, 'reg_lambda': 0.0005880488088278426}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:53,588] Trial 35 finished with value: 0.5682938782455969 and parameters: {'learning_rate': 0.020558155510143592, 'max_depth': 4, 'min_child_weight': 3.6680330884945596, 'subsample': 0.7363373026569046, 'colsample_bytree': 0.9560644415258122, 'gamma': 1.6295270653091691, 'reg_alpha': 0.0001860256500196045, 'reg_lambda': 0.00025499703355737343}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:03:59,804] Trial 36 finished with value: 0.5517915785438353 and parameters: {'learning_rate': 0.1346910839639991, 'max_depth': 5, 'min_child_weight': 1.5100266756792826, 'subsample': 0.9208792784970337, 'colsample_bytree': 0.9197244816959672, 'gamma': 1.9150541921380608, 'reg_alpha': 0.006661233321529639, 'reg_lambda': 0.0036145523307250017}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:07,503] Trial 37 finished with value: 0.5413583920310988 and parameters: {'learning_rate': 0.025662273346971604, 'max_depth': 4, 'min_child_weight': 2.8188121090904863, 'subsample': 0.7629459145377818, 'colsample_bytree': 0.784786880795776, 'gamma': 1.6117502243099202, 'reg_alpha': 0.0009238999007967267, 'reg_lambda': 0.0011441995070465686}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:14,925] Trial 38 finished with value: 0.53314304996957 and parameters: {'learning_rate': 0.041456885981448886, 'max_depth': 3, 'min_child_weight': 4.822228558170451, 'subsample': 0.7943182785976476, 'colsample_bytree': 0.8615068478954363, 'gamma': 1.7824774307830993, 'reg_alpha': 0.07228981101866326, 'reg_lambda': 0.0001839203632966776}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:25,800] Trial 39 finished with value: 0.5520428896788927 and parameters: {'learning_rate': 0.03458897077519895, 'max_depth': 5, 'min_child_weight': 1.2976607832033333, 'subsample': 0.8610078337649006, 'colsample_bytree': 0.9371402870771892, 'gamma': 1.9028236256018671, 'reg_alpha': 0.0003129388624641822, 'reg_lambda': 0.0023385937523196345}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:33,531] Trial 40 finished with value: 0.5343439578736657 and parameters: {'learning_rate': 0.09710329241274235, 'max_depth': 4, 'min_child_weight': 1.8799779495935922, 'subsample': 0.7743362982140576, 'colsample_bytree': 0.8862882800097723, 'gamma': 1.1216074770241276, 'reg_alpha': 0.00016276857744815164, 'reg_lambda': 0.0007616770055829006}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:42,020] Trial 41 finished with value: 0.5677870856904512 and parameters: {'learning_rate': 0.046126644180825904, 'max_depth': 4, 'min_child_weight': 2.702915850534577, 'subsample': 0.9112474236456913, 'colsample_bytree': 0.8671915467531491, 'gamma': 1.6457909912702682, 'reg_alpha': 0.0006762657057513074, 'reg_lambda': 0.0013363993733480522}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:50,644] Trial 42 finished with value: 0.5849997502800236 and parameters: {'learning_rate': 0.05104191418957416, 'max_depth': 4, 'min_child_weight': 3.824159282423026, 'subsample': 0.9472491712941472, 'colsample_bytree': 0.8389283788147918, 'gamma': 1.9895369868731914, 'reg_alpha': 0.0004668516355857427, 'reg_lambda': 0.0002573565530576953}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:04:56,611] Trial 43 finished with value: 0.5867194199579053 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 5, 'min_child_weight': 4.280960611730248, 'subsample': 0.948962132923611, 'colsample_bytree': 0.8322226125616373, 'gamma': 1.9739793590352421, 'reg_alpha': 0.00043100520259055076, 'reg_lambda': 0.00022471195515990595}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:05:03,142] Trial 44 finished with value: 0.5566282339171276 and parameters: {'learning_rate': 0.14446820660612647, 'max_depth': 5, 'min_child_weight': 4.189740230529212, 'subsample': 0.9586874597872753, 'colsample_bytree': 0.8311866328674276, 'gamma': 1.978157201925738, 'reg_alpha': 0.00240596615177854, 'reg_lambda': 0.0002447304724127134}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:05:09,511] Trial 45 finished with value: 0.5418933964320864 and parameters: {'learning_rate': 0.09572141830908731, 'max_depth': 5, 'min_child_weight': 5.113311666188504, 'subsample': 0.9507966293287013, 'colsample_bytree': 0.8382767768188021, 'gamma': 1.883193514014031, 'reg_alpha': 0.0004033348775224037, 'reg_lambda': 2.115660425364487}. Best is trial 22 with value: 0.5871648093018706.
[I 2026-04-15 14:05:15,416] Trial 46 finished with value: 0.5943878743658327 and parameters: {'learning_rate': 0.19263117584672038, 'max_depth': 6, 'min_child_weight': 6.268532574251493, 'subsample': 0.9903978411617756, 'colsample_bytree': 0.7686759445970438, 'gamma': 1.7667788531196673, 'reg_alpha': 0.004015739503626379, 'reg_lambda': 0.005125504511068475}. Best is trial 46 with value: 0.5943878743658327.
[I 2026-04-15 14:05:21,539] Trial 47 finished with value: 0.5760334547506625 and parameters: {'learning_rate': 0.19706867939072217, 'max_depth': 6, 'min_child_weight': 6.107886113042631, 'subsample': 0.9851289743063716, 'colsample_bytree': 0.7645364459035793, 'gamma': 1.7584098946610613, 'reg_alpha': 0.011927031517411963, 'reg_lambda': 0.025973846327152723}. Best is trial 46 with value: 0.5943878743658327.

[I 2026-04-15 14:12:45,800] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.41053
              precision    recall  f1-score   support

           0       0.70      1.00      0.82       234
           1       0.00      0.00      0.00       102

    accuracy                           0.70       336
   macro avg       0.35      0.50      0.41       336
weighted avg       0.49      0.70      0.57       336

Confusion matrix:
 [[234   0]
 [102   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 14:12:54,990] Trial 0 finished with value: 0.5585579784018042 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5585579784018042.
[I 2026-04-15 14:13:17,588] Trial 1 finished with value: 0.5310695334401019 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.5585579784018042.
[I 2026-04-15 14:13:34,821] Trial 2 finished with value: 0.5597496517150568 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5597496517150568.
[I 2026-04-15 14:14:22,537] Trial 3 finished with value: 0.5711923650965767 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:14:52,672] Trial 4 finished with value: 0.5564732014210778 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:16:13,996] Trial 5 finished with value: 0.5558054079868703 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:16:47,515] Trial 6 finished with value: 0.5491636511311504 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:17:39,317] Trial 7 finished with value: 0.5570659004578371 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:19:20,454] Trial 8 finished with value: 0.5510560793040464 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:19:43,426] Trial 9 finished with value: 0.5447738448323755 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:19:51,512] Trial 10 finished with value: 0.5646728963731055 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1570794430403163, 'depth': 5, 'l2_leaf_reg': 5.721398227528868, 'random_strength': 0.9905905821371315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9500025439539328}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:20:00,090] Trial 11 finished with value: 0.559868500862663 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15842934156643917, 'depth': 5, 'l2_leaf_reg': 5.551899558479872, 'random_strength': 0.9656743478883708, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9613774767504824}. Best is trial 3 with value: 0.5711923650965767.
[I 2026-04-15 14:20:10,133] Trial 12 finished with value: 0.5867883992811832 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12532682381011637, 'depth': 5, 'l2_leaf_reg': 3.1926486598631105, 'random_strength': 0.6263742048623379, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9357491826204533}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:20:37,580] Trial 13 finished with value: 0.5695891049987755 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11898154973533921, 'depth': 6, 'l2_leaf_reg': 2.869741965176845, 'random_strength': 0.6147412493036409, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8656745003586366}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:20:47,173] Trial 14 finished with value: 0.5658558672341829 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11379106434434597, 'depth': 5, 'l2_leaf_reg': 2.566752493748643, 'random_strength': 0.5701475813832674, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8572724179170484}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:21:38,628] Trial 15 finished with value: 0.5516248731812653 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05165446068032083, 'depth': 7, 'l2_leaf_reg': 10.103348102311275, 'random_strength': 0.7482749262321198, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6176070773540004}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:21:48,472] Trial 16 finished with value: 0.5790396713034421 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11709680994139955, 'depth': 5, 'l2_leaf_reg': 18.878920630320945, 'random_strength': 0.4776807852053371, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8748671141374693}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:21:57,788] Trial 17 finished with value: 0.5469918899359659 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12762958122674847, 'depth': 5, 'l2_leaf_reg': 18.93357457210446, 'random_strength': 0.4440752281517034, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8686941275905087}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:22:02,784] Trial 18 finished with value: 0.5563910562657823 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19963498896671686, 'depth': 4, 'l2_leaf_reg': 3.1476499762416403, 'random_strength': 0.33779213305576217, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.998940256994706}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:22:27,913] Trial 19 finished with value: 0.5595213092941005 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0349761581581011, 'depth': 5, 'l2_leaf_reg': 1.5235750922982971, 'random_strength': 0.535646162667113, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9088321320460828}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:22:49,497] Trial 20 finished with value: 0.5790701942668803 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10097582571003508, 'depth': 6, 'l2_leaf_reg': 7.504948576053869, 'random_strength': 0.7791644775697428, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8290562500466551}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:23:09,816] Trial 21 finished with value: 0.5689937993308163 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0994635720219915, 'depth': 6, 'l2_leaf_reg': 6.877709527445314, 'random_strength': 0.7955885391406006, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8114350940989358}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:23:19,422] Trial 22 finished with value: 0.5640283035161766 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.124717527913953, 'depth': 5, 'l2_leaf_reg': 13.040216529950115, 'random_strength': 0.8781865695288962, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8282291333845571}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:23:50,429] Trial 23 finished with value: 0.5711032554299509 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0631580676111052, 'depth': 6, 'l2_leaf_reg': 3.7160198720941273, 'random_strength': 0.6797145892076547, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8964372800907491}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:23:56,145] Trial 24 finished with value: 0.5593740859836007 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13926443759709256, 'depth': 4, 'l2_leaf_reg': 2.3824742923266418, 'random_strength': 0.40773421333107396, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9516453161538777}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:24:12,880] Trial 25 finished with value: 0.573484419009533 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10083137614255099, 'depth': 6, 'l2_leaf_reg': 8.123067691847435, 'random_strength': 0.5022529932924235, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9149261800352041}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:24:24,786] Trial 26 finished with value: 0.5645768791901922 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09471200761606746, 'depth': 5, 'l2_leaf_reg': 19.439645408677265, 'random_strength': 0.700944426103652, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:24:34,339] Trial 27 finished with value: 0.5580608207406622 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15303309743439142, 'depth': 5, 'l2_leaf_reg': 3.6871455062783745, 'random_strength': 0.5814864037394372, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7909141903325292}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:24:58,828] Trial 28 finished with value: 0.5684557554841688 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06008533680278842, 'depth': 6, 'l2_leaf_reg': 5.681866412291265, 'random_strength': 0.871060978413532, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8352014415771207}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:25:07,548] Trial 29 finished with value: 0.5670087893658062 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10923791471094639, 'depth': 4, 'l2_leaf_reg': 2.326732807538136, 'random_strength': 0.1818861310311614, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:25:15,051] Trial 30 finished with value: 0.5565391321144846 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08872798466240263, 'depth': 4, 'l2_leaf_reg': 12.461466842070452, 'random_strength': 0.7960052829691011, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9972248034815151}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:25:34,912] Trial 31 finished with value: 0.5700603749635884 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1378147779882243, 'depth': 6, 'l2_leaf_reg': 7.69603733076793, 'random_strength': 0.5427735377907323, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.911337743643361}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:26:02,516] Trial 32 finished with value: 0.5657068818621686 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10476529100993044, 'depth': 6, 'l2_leaf_reg': 9.251278264567583, 'random_strength': 0.5015230680723729, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8964445941416959}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:27:35,740] Trial 33 finished with value: 0.5549957299402809 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06763778083675664, 'depth': 7, 'l2_leaf_reg': 16.156830047682433, 'random_strength': 0.38569080347081985, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9278545032520714}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:27:45,151] Trial 34 finished with value: 0.5654289862939827 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08231250495932962, 'depth': 5, 'l2_leaf_reg': 6.401364393499368, 'random_strength': 0.4962835647524263, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.873707327678247}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:28:00,169] Trial 35 finished with value: 0.5824962291790757 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17691133625585045, 'depth': 6, 'l2_leaf_reg': 4.585167314260698, 'random_strength': 0.7163386383608032, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9328668361495169}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:28:06,946] Trial 36 finished with value: 0.5701419851466794 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1873633494019642, 'depth': 5, 'l2_leaf_reg': 4.603942350431931, 'random_strength': 0.7186161816698788, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9600260087865536}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:28:22,788] Trial 37 finished with value: 0.571925547172911 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1739434669338095, 'depth': 6, 'l2_leaf_reg': 3.4314648956270717, 'random_strength': 0.6120983186330142, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8542310805012474}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:28:44,019] Trial 38 finished with value: 0.5824260861257916 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13704872619158745, 'depth': 7, 'l2_leaf_reg': 1.8377870972862385, 'random_strength': 0.282140374228006, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.12221043743904225}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:29:00,917] Trial 39 finished with value: 0.5549807854664093 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13935836112146038, 'depth': 7, 'l2_leaf_reg': 1.6834069706998165, 'random_strength': 0.24179311413366156, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.4180462534866333}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:29:41,867] Trial 40 finished with value: 0.5619387476248403 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1684123477044819, 'depth': 8, 'l2_leaf_reg': 1.3003395172711054, 'random_strength': 0.031242684729725634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4532051511681003}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:30:07,875] Trial 41 finished with value: 0.5577878430369971 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1433422643136159, 'depth': 7, 'l2_leaf_reg': 1.981029127373373, 'random_strength': 0.1224942681285999, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.2907563020932256}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:30:30,737] Trial 42 finished with value: 0.5391054423998359 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12879318015295807, 'depth': 7, 'l2_leaf_reg': 4.802258387570076, 'random_strength': 0.26476294531703853, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 3.848341272915878}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:30:45,159] Trial 43 finished with value: 0.5496370797459507 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11329039816987715, 'depth': 6, 'l2_leaf_reg': 1.9764999052734809, 'random_strength': 0.6459622940147998, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.015511881399920935}. Best is trial 12 with value: 0.5867883992811832.
[I 2026-04-15 14:31:35,572] Trial 44 finished with value: 0.5790579389135603 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.16406152799357135, 'depth': 8, 'l2_leaf_reg': 1.0805726085898093, 'random_strength': 0.9310316417844701, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.9134481426253878}. Best is trial 12 with value: 0.5867883992811832.

                                               feature  importance
53              eye__sac_length_AOI_aggregated_Pos_min    0.326428
526                    envelope__envelope_C5_upper_max    0.095498
183                  eye__fix_duration_AOI_FD_Neg1_sum    0.077776
339                      eye__sample_entropy_m=3_r=200    0.064980
5                                  eye__sac_length_sum    0.041076
352               eye__lyapunov_exponent_m_2_tau_2_T_4    0.032730
343                      eye__sample_entropy_m=4_r=100    0.030018
282          eye__fix_duration_AOI_aggregated_Pos_skew    0.028468
419                 eye__lam_euclidean_length_2_rho_50    0.027898
361               eye__lyapunov_exponent_m_4_tau_1_T_4    0.025879
615                   envelope__envelope_F4_lower_mean    0.025820
335                      eye__sample_entropy_m=2_r=400    0.025652
552                  envelope__envelope_CP2_lower_mean    0.024756
91   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.024340
467                                 eye__imf0_kurtosis    0.023193
464                                      eye__imf0_min    0.020899
389           eye__rec_metric_euclidean_length_1_rho_5    0.017130
557            envelope__envelope_CP3_upper_max_sample    0.016577
374                       eye__corr_dim_m_2_tau_2_r_50    0.016085
865             envelope__envelope_Pz_upper_max_sample    0.015745
428               eye__corm_euclidean_length_2_rho_500    0.015343
536             envelope__envelope_C6_upper_max_sample    0.013204
167                              eye__fix_duration_max    0.010507
9                                   eye__sac_speed_max    0.000000
10                                 eye__sac_speed_mean    0.000000
11                               eye__sac_speed_median    0.000000
12                                  eye__sac_speed_std    0.000000
13                             eye__sac_speed_kurtosis    0.000000
14                                 eye__sac_speed_skew    0.000000
15                             eye__sac_angle_to_x_min    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.54276
              precision    recall  f1-score   support

           0       0.72      0.86      0.78       234
           1       0.42      0.24      0.30       102

    accuracy                           0.67       336
   macro avg       0.57      0.55      0.54       336
weighted avg       0.63      0.67      0.64       336

Confusion matrix:
 [[201  33]
 [ 78  24]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+envelope__target=match_mismatch_general__problem=binary__feat=all_features+envelope__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
60        eye__sac_speed_AOI_aggregated_Pos_min   12.485115
464                               eye__imf0_min    5.574784
63     eye__sac_speed_AOI_aggregated_Pos_median    5.139601
53       eye__sac_length_AOI_aggregated_Pos_min    3.279876
177           eye__fix_duration_AOI_FD_Neg1_max    2.654484
56    eye__sac_length_AOI_aggregated_Pos_median    2.548601
284  eye__fix_duration_AOI_aggregated_Pos_count    2.328759
62       eye__sac_speed_AOI_aggregated_Pos_mean    2.083247
527            envelope__envelope_C5_upper_mean    1.923883
465                               eye__imf0_max    1.647893
276    eye__fix_duration_AOI_aggregated_Pos_min    1.594779
183           eye__fix_duration_AOI_FD_Neg1_sum    1.579422
526             envelope__envelope_C5_upper_max    1.547326
283    eye__fix_duration_AOI_aggregated_Pos_sum    1.491892
214         eye__fix_duration_AOI_FD_Pos1_count    1.402340
339               eye__sample_entropy_m=3_r=200    1.384750
58       eye__sac_length_AOI_aggregated_Pos_sum    1.248393
333               eye__sample_entropy_m=2_r=100    1.162073
59     eye__sac_length_AOI_aggregated_Pos_count    0.999105
724          envelope__envelope_Fpz_upper_count    0.956047
5                           eye__sac_length_sum    0.941001
178          eye__fix_duration_AOI_FD_Neg1_mean    0.940052
470            envelope__envelope_AF3_upper_max    0.869928
594            envelope__envelope_F1_lower_mean    0.758607
338               eye__sample_entropy_m=3_r=100    0.748810
55      eye__sac_length_AOI_aggregated_Pos_mean    0.729343
364        eye__lyapunov_exponent_m_4_tau_2_T_4    0.726338
616           envelope__envelope_F4_lower_count    0.705867
205         eye__fix_duration_AOI_FD_Pos1_first    0.687288
17                     eye__sac_angle_to_x_mean    0.671951

================================================================================
Skipping existing experiment: exp__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__ES__refitTEST

[I 2026-04-15 14:36:39,051] A new study created in memory with name: multiclass_xgb

[envelope] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+envelope__target=match_mismatch_general__problem=multiclass__feat=all_features+envelope__ES__refitTEST__no_neutral
X_train: (3016, 897), X_test: (336, 897)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 14:36:52,287] Trial 0 finished with value: 0.6355243783819278 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6355243783819278.
[I 2026-04-15 14:37:03,543] Trial 1 finished with value: 0.6033589049957374 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6355243783819278.
[I 2026-04-15 14:37:18,025] Trial 2 finished with value: 0.6477704323737992 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:37:29,575] Trial 3 finished with value: 0.6315822828275914 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:37:39,850] Trial 4 finished with value: 0.6267681417452459 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:37:54,914] Trial 5 finished with value: 0.6303688927803931 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:38:02,487] Trial 6 finished with value: 0.616320085123772 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:38:20,203] Trial 7 finished with value: 0.6347377660280122 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:38:29,309] Trial 8 finished with value: 0.6223289654672803 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:38:47,971] Trial 9 finished with value: 0.6321963216778156 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:39:00,407] Trial 10 finished with value: 0.6375017241194291 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8323975169664899, 'colsample_bytree': 0.8251024923043149, 'gamma': 1.4856799266904641, 'reg_alpha': 0.000753460297138337, 'reg_lambda': 0.00839106795699683}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:39:15,570] Trial 11 finished with value: 0.6334548048530879 and parameters: {'learning_rate': 0.02089455746646233, 'max_depth': 3, 'min_child_weight': 1.135288732717072, 'subsample': 0.8353558436496413, 'colsample_bytree': 0.8180636702553983, 'gamma': 1.5641273671613192, 'reg_alpha': 0.001025825225917495, 'reg_lambda': 0.00013386192543122697}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:39:27,021] Trial 12 finished with value: 0.6320512821174158 and parameters: {'learning_rate': 0.03354619122916201, 'max_depth': 3, 'min_child_weight': 1.038097995864505, 'subsample': 0.8399612829075968, 'colsample_bytree': 0.8200005224971499, 'gamma': 1.4680777089523493, 'reg_alpha': 0.00011387661530562773, 'reg_lambda': 0.01499851504388292}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:39:41,686] Trial 13 finished with value: 0.6314113200303624 and parameters: {'learning_rate': 0.031881988246076944, 'max_depth': 4, 'min_child_weight': 1.9159793446750535, 'subsample': 0.9036482938650877, 'colsample_bytree': 0.8662972465284487, 'gamma': 1.4276816646933954, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.00924430035454938}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:39:55,658] Trial 14 finished with value: 0.6448420888496715 and parameters: {'learning_rate': 0.026400300850169575, 'max_depth': 4, 'min_child_weight': 1.4366364833229337, 'subsample': 0.755956762637413, 'colsample_bytree': 0.8005626508692825, 'gamma': 1.6809947029884436, 'reg_alpha': 0.003951021561695887, 'reg_lambda': 0.08684001071432124}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:40:08,379] Trial 15 finished with value: 0.6433508181559454 and parameters: {'learning_rate': 0.04337983961355566, 'max_depth': 4, 'min_child_weight': 2.4370747834999373, 'subsample': 0.700717276709995, 'colsample_bytree': 0.7822288900388755, 'gamma': 1.7289563765719622, 'reg_alpha': 0.006712313916827947, 'reg_lambda': 0.2973687673999081}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:40:27,232] Trial 16 finished with value: 0.642840309995483 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 5, 'min_child_weight': 1.401772539325163, 'subsample': 0.7530229364402534, 'colsample_bytree': 0.7820551876399596, 'gamma': 1.2580988324244256, 'reg_alpha': 0.004722964991735355, 'reg_lambda': 9.968625683962115}. Best is trial 2 with value: 0.6477704323737992.
[I 2026-04-15 14:40:37,307] Trial 17 finished with value: 0.6483149651763611 and parameters: {'learning_rate': 0.06386447566308097, 'max_depth': 4, 'min_child_weight': 2.112826953049721, 'subsample': 0.7562229812287704, 'colsample_bytree': 0.8911833935295822, 'gamma': 1.7458000307374977, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 0.04566126540691047}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:40:48,814] Trial 18 finished with value: 0.6221318038102602 and parameters: {'learning_rate': 0.06520299635911386, 'max_depth': 7, 'min_child_weight': 2.477783087802394, 'subsample': 0.802188999875465, 'colsample_bytree': 0.8868948588223814, 'gamma': 1.9967996445943748, 'reg_alpha': 0.00011324883295395535, 'reg_lambda': 0.0332040448019982}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:01,342] Trial 19 finished with value: 0.6273525400410899 and parameters: {'learning_rate': 0.06245303278886836, 'max_depth': 5, 'min_child_weight': 2.4831869070953374, 'subsample': 0.7326207173509872, 'colsample_bytree': 0.905359217093405, 'gamma': 1.2763326476302224, 'reg_alpha': 0.0004201525736812989, 'reg_lambda': 1.75144139558839}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:10,363] Trial 20 finished with value: 0.6286895301438472 and parameters: {'learning_rate': 0.12332056020715612, 'max_depth': 4, 'min_child_weight': 2.069856511655879, 'subsample': 0.7755540332188732, 'colsample_bytree': 0.8466445670931371, 'gamma': 0.8041858310280126, 'reg_alpha': 0.0002435588667602119, 'reg_lambda': 0.027125158825363038}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:22,863] Trial 21 finished with value: 0.6346548393420433 and parameters: {'learning_rate': 0.04193893386504259, 'max_depth': 4, 'min_child_weight': 1.3389653248846412, 'subsample': 0.7594081894889367, 'colsample_bytree': 0.7930773268607395, 'gamma': 1.6933292393840693, 'reg_alpha': 0.008238148821385818, 'reg_lambda': 0.0779650172699757}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:37,957] Trial 22 finished with value: 0.6387112198990442 and parameters: {'learning_rate': 0.026485948294219096, 'max_depth': 4, 'min_child_weight': 1.3779795401477957, 'subsample': 0.7238316570019883, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.7134459720037398, 'reg_alpha': 0.001747661765504845, 'reg_lambda': 0.22888110539469084}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:49,231] Trial 23 finished with value: 0.6272383157527484 and parameters: {'learning_rate': 0.07032559325719123, 'max_depth': 5, 'min_child_weight': 1.5833952715892017, 'subsample': 0.810174905328713, 'colsample_bytree': 0.8484326557698801, 'gamma': 1.5884287664391992, 'reg_alpha': 0.015286333973764218, 'reg_lambda': 0.03462663233049626}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:41:59,382] Trial 24 finished with value: 0.6446917727337964 and parameters: {'learning_rate': 0.05379004661708725, 'max_depth': 3, 'min_child_weight': 2.1351397000997276, 'subsample': 0.7604835970378565, 'colsample_bytree': 0.8032578791616165, 'gamma': 1.342428776528223, 'reg_alpha': 0.002433054446470995, 'reg_lambda': 0.00388717784996061}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:42:13,048] Trial 25 finished with value: 0.6427222124055594 and parameters: {'learning_rate': 0.03853687223725238, 'max_depth': 4, 'min_child_weight': 1.2769076021252788, 'subsample': 0.7000695502104095, 'colsample_bytree': 0.9142997906893345, 'gamma': 1.8487447540185435, 'reg_alpha': 0.08182160179687056, 'reg_lambda': 0.10721558290219826}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:42:22,339] Trial 26 finished with value: 0.622651957592995 and parameters: {'learning_rate': 0.08771828600942085, 'max_depth': 5, 'min_child_weight': 1.6052482263124435, 'subsample': 0.8134019647402086, 'colsample_bytree': 0.8386843696454813, 'gamma': 1.668913496898968, 'reg_alpha': 0.056066322830741956, 'reg_lambda': 0.44472004610139754}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:42:30,822] Trial 27 finished with value: 0.6356671269745618 and parameters: {'learning_rate': 0.05464538448979926, 'max_depth': 3, 'min_child_weight': 2.592347060174137, 'subsample': 0.871832950015089, 'colsample_bytree': 0.9812035275447117, 'gamma': 1.8177062851741825, 'reg_alpha': 0.0002922312961656095, 'reg_lambda': 0.045231249744769574}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:42:43,802] Trial 28 finished with value: 0.6446766972690119 and parameters: {'learning_rate': 0.029095475443705207, 'max_depth': 4, 'min_child_weight': 1.211332068178639, 'subsample': 0.7631153254908576, 'colsample_bytree': 0.7626117831078648, 'gamma': 1.9937762962290544, 'reg_alpha': 0.5955551013207283, 'reg_lambda': 1.5522345955183416}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:42:56,759] Trial 29 finished with value: 0.6432634891634297 and parameters: {'learning_rate': 0.049723079395445714, 'max_depth': 4, 'min_child_weight': 3.7732795948683333, 'subsample': 0.7232719522866222, 'colsample_bytree': 0.8762332070651453, 'gamma': 0.3701657633828719, 'reg_alpha': 0.001174308241427692, 'reg_lambda': 0.19267676551490856}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:43:16,267] Trial 30 finished with value: 0.6428903028928713 and parameters: {'learning_rate': 0.02470274643678689, 'max_depth': 7, 'min_child_weight': 2.9731708672341908, 'subsample': 0.7443296163657399, 'colsample_bytree': 0.7165916960107654, 'gamma': 1.1529499247077486, 'reg_alpha': 5.544154050118195, 'reg_lambda': 0.018502244216073403}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:43:27,824] Trial 31 finished with value: 0.6463568372798181 and parameters: {'learning_rate': 0.03651988309093289, 'max_depth': 3, 'min_child_weight': 2.026606745409394, 'subsample': 0.7683689084659552, 'colsample_bytree': 0.7994871991483051, 'gamma': 1.364277979631065, 'reg_alpha': 0.0020015304844456716, 'reg_lambda': 0.002347813871069803}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:43:39,281] Trial 32 finished with value: 0.6481815139468236 and parameters: {'learning_rate': 0.03720544429626329, 'max_depth': 3, 'min_child_weight': 1.7407529247209939, 'subsample': 0.7740567030488487, 'colsample_bytree': 0.7658253508792211, 'gamma': 1.3730153733803858, 'reg_alpha': 0.013097615285336385, 'reg_lambda': 0.00025216223266929947}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:43:50,731] Trial 33 finished with value: 0.6377783188428259 and parameters: {'learning_rate': 0.037103448441930476, 'max_depth': 3, 'min_child_weight': 1.7939245538391406, 'subsample': 0.8196042583576644, 'colsample_bytree': 0.760948434173675, 'gamma': 0.8836885918350262, 'reg_alpha': 0.012220329931709186, 'reg_lambda': 0.0002524346937605646}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:00,762] Trial 34 finished with value: 0.6473744067888978 and parameters: {'learning_rate': 0.03813236119483475, 'max_depth': 3, 'min_child_weight': 2.1178310929342206, 'subsample': 0.7739065284020767, 'colsample_bytree': 0.7765166651894659, 'gamma': 1.3545986554921858, 'reg_alpha': 0.04023289425457161, 'reg_lambda': 0.00024185840289260918}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:09,699] Trial 35 finished with value: 0.6364458240352653 and parameters: {'learning_rate': 0.049287122037836834, 'max_depth': 3, 'min_child_weight': 1.736350617094106, 'subsample': 0.8643979448741383, 'colsample_bytree': 0.7671927399731043, 'gamma': 1.561343079023601, 'reg_alpha': 0.0641469703655661, 'reg_lambda': 0.0005486923917867134}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:25,671] Trial 36 finished with value: 0.6277521370033937 and parameters: {'learning_rate': 0.04464060525540579, 'max_depth': 8, 'min_child_weight': 2.2737218504236383, 'subsample': 0.7941551032981569, 'colsample_bytree': 0.7262205835194464, 'gamma': 1.248755091335061, 'reg_alpha': 0.03753903627695459, 'reg_lambda': 0.00039090475375473774}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:35,657] Trial 37 finished with value: 0.6401016142666648 and parameters: {'learning_rate': 0.07443905174477107, 'max_depth': 3, 'min_child_weight': 5.031319770201959, 'subsample': 0.9082942015205822, 'colsample_bytree': 0.7432061277021199, 'gamma': 0.9699979618347508, 'reg_alpha': 0.14091832806250573, 'reg_lambda': 0.00011079465667735099}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:46,397] Trial 38 finished with value: 0.6459585477872217 and parameters: {'learning_rate': 0.05951758130694301, 'max_depth': 4, 'min_child_weight': 2.7667818507570647, 'subsample': 0.738192155593702, 'colsample_bytree': 0.7752274251804459, 'gamma': 1.8096534010291476, 'reg_alpha': 0.37177352271587105, 'reg_lambda': 0.0009655009800527512}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:44:56,079] Trial 39 finished with value: 0.6171508009612872 and parameters: {'learning_rate': 0.09328437368289517, 'max_depth': 5, 'min_child_weight': 3.4005362633475404, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9146127279773172, 'gamma': 1.1666853444152756, 'reg_alpha': 0.020838506322806018, 'reg_lambda': 0.005518591835370787}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:45:07,488] Trial 40 finished with value: 0.6442536943025056 and parameters: {'learning_rate': 0.03197195753030266, 'max_depth': 3, 'min_child_weight': 4.106053655300299, 'subsample': 0.9315282011857021, 'colsample_bytree': 0.8332243521636145, 'gamma': 1.4091099551613793, 'reg_alpha': 0.010238682233660545, 'reg_lambda': 0.00022922455564261497}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:45:18,643] Trial 41 finished with value: 0.6456900994515304 and parameters: {'learning_rate': 0.038932503220068485, 'max_depth': 3, 'min_child_weight': 1.9680277166677937, 'subsample': 0.7776393384700028, 'colsample_bytree': 0.8126696981520347, 'gamma': 1.3430822971382634, 'reg_alpha': 0.0017584147898220253, 'reg_lambda': 0.0020983365062237267}. Best is trial 17 with value: 0.6483149651763611.
[I 2026-04-15 14:45:30,077] Trial 42 finished with value: 0.6508170012957448 and parameters: {'learning_rate': 0.03617183055820972, 'max_depth': 3, 'min_child_weight': 1.536261757085539, 'subsample': 0.7744820108901801, 'colsample_bytree': 0.7521670530072357, 'gamma': 1.492749640836041, 'reg_alpha': 0.0276855102599512, 'reg_lambda': 0.0010027478466534587}. Best is trial 42 with value: 0.6508170012957448.
[I 2026-04-15 14:45:37,180] Trial 43 finished with value: 0.6310790046759596 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 3, 'min_child_weight': 1.4814645685663355, 'subsample': 0.794093197572422, 'colsample_bytree': 0.7522095220680105, 'gamma': 1.5815880699870106, 'reg_alpha': 0.03706537754349238, 'reg_lambda': 0.0010208282599865155}. Best is trial 42 with value: 0.6508170012957448.
[I 2026-04-15 14:45:48,308] Trial 44 finished with value: 0.6460389402164608 and parameters: {'learning_rate': 0.04764784126688481, 'max_depth': 3, 'min_child_weight': 1.819027133801932, 'subsample': 0.7783635742365786, 'colsample_bytree': 0.7279988138015538, 'gamma': 1.0182828474944383, 'reg_alpha': 0.020485851146369957, 'reg_lambda': 0.0002129583072755142}. Best is trial 42 with value: 0.6508170012957448.
[I 2026-04-15 14:46:06,221] Trial 45 finished with value: 0.6294047480856695 and parameters: {'learning_rate': 0.030843978601055793, 'max_depth': 6, 'min_child_weight': 1.126428842084615, 'subsample': 0.8284602525388959, 'colsample_bytree': 0.8631540137549558, 'gamma': 1.486180947679746, 'reg_alpha': 0.17292092171471524, 'reg_lambda': 0.0004627408322792529}. Best is trial 42 with value: 0.6508170012957448.
[I 2026-04-15 14:46:20,705] Trial 46 finished with value: 0.6396843696297887 and parameters: {'learning_rate': 0.023659244302464102, 'max_depth': 4, 'min_child_weight': 1.6778776823035824, 'subsample': 0.7133000599408842, 'colsample_bytree': 0.7113178643906757, 'gamma': 1.8776428225096025, 'reg_alpha': 0.04108355009591018, 'reg_lambda': 0.00014325345459314175}. Best is trial 42 with value: 0.6508170012957448.
[I 2026-04-15 14:46:31,447] Trial 47 finished with value: 0.6386927060803159 and parameters: {'learning_rate': 0.0347044105528559, 'max_depth': 3, 'min_child_weight': 2.2759317224259226, 'subsample': 0.8533717549401846, 'colsample_bytree': 0.9489264178120715, 'gamma': 1.5049783996121084, 'reg_alpha': 0.8880368836456252, 'reg_lambda': 0.0007568559363580668}. Best is trial 42 with value: 0.6508170012957448.

[I 2026-04-15 14:56:45,539] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 14:56:55,142] Trial 0 finished with value: 0.6352743426672984 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6352743426672984.
[I 2026-04-15 14:57:10,739] Trial 1 finished with value: 0.6553038926072227 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 14:57:32,636] Trial 2 finished with value: 0.6388479360883415 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 14:58:12,167] Trial 3 finished with value: 0.633161243446067 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 14:59:13,707] Trial 4 finished with value: 0.6124244374842077 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:00:33,327] Trial 5 finished with value: 0.6220321283851936 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:01:11,599] Trial 6 finished with value: 0.645616320812322 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:02:00,665] Trial 7 finished with value: 0.6436406558720107 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:04:08,196] Trial 8 finished with value: 0.6411113209757121 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:04:46,021] Trial 9 finished with value: 0.6309169907802549 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:05:01,335] Trial 10 finished with value: 0.6518824510741161 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:05:19,079] Trial 11 finished with value: 0.6512997667747173 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02005507141938724, 'depth': 4, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.20696700950514785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9614099298964858}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:05:42,899] Trial 12 finished with value: 0.6463744749977174 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027764326872075, 'depth': 5, 'l2_leaf_reg': 13.859731742356656, 'random_strength': 0.02812276405828626, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9357491826204533}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:06:00,319] Trial 13 finished with value: 0.6500814602667134 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03322501342278858, 'depth': 5, 'l2_leaf_reg': 5.838384756610479, 'random_strength': 0.41707559629394864, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8632850879711638}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:06:12,091] Trial 14 finished with value: 0.6438723539567561 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030222670442179623, 'depth': 4, 'l2_leaf_reg': 12.426243216075434, 'random_strength': 0.25638596891348014, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.854423035046473}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:06:33,346] Trial 15 finished with value: 0.6472306509121011 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04315045626888051, 'depth': 5, 'l2_leaf_reg': 7.121033915506331, 'random_strength': 0.5623181046141312, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6176070773540004}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:06:46,702] Trial 16 finished with value: 0.646012775583412 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025442312064675076, 'depth': 4, 'l2_leaf_reg': 19.65746270514377, 'random_strength': 0.1700256269337071, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:06:58,135] Trial 17 finished with value: 0.6462092874276237 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14275466267871886, 'depth': 5, 'l2_leaf_reg': 3.018829982744686, 'random_strength': 0.3491923639077172, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8209911986048593}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:07:08,051] Trial 18 finished with value: 0.6487480215585228 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03605757243651936, 'depth': 4, 'l2_leaf_reg': 10.900060400715537, 'random_strength': 0.9580941097934477, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.698248945081633}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:07:58,306] Trial 19 finished with value: 0.6503807987339573 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02454817143834262, 'depth': 6, 'l2_leaf_reg': 15.02736353807733, 'random_strength': 0.09034787353342093, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8929426303227499}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:08:12,357] Trial 20 finished with value: 0.6509964211342542 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05556630319732194, 'depth': 5, 'l2_leaf_reg': 7.562538869139835, 'random_strength': 0.5403540417857632, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6974305317851217}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:08:26,675] Trial 21 finished with value: 0.6501799375784305 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023019309640846735, 'depth': 4, 'l2_leaf_reg': 19.77486834699798, 'random_strength': 0.2155112731616703, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9782757475322561}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:08:44,113] Trial 22 finished with value: 0.6484296136844381 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02226960886405234, 'depth': 4, 'l2_leaf_reg': 19.263733111977828, 'random_strength': 0.0010084962427511224, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.933538606219811}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:08:58,738] Trial 23 finished with value: 0.6499780931749358 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020059294280321893, 'depth': 4, 'l2_leaf_reg': 14.543166788394092, 'random_strength': 0.15204462278039574, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9465092361336046}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:09:15,064] Trial 24 finished with value: 0.640203713621573 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0378273644365385, 'depth': 5, 'l2_leaf_reg': 9.424280459905566, 'random_strength': 0.3215117622286761, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7919719974279151}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:09:27,711] Trial 25 finished with value: 0.6512663880583418 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028887555377161433, 'depth': 4, 'l2_leaf_reg': 12.377669687249657, 'random_strength': 0.20285221659318764, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8917022815953088}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:09:48,278] Trial 26 finished with value: 0.6480028918452005 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.020457102373961783, 'depth': 5, 'l2_leaf_reg': 16.416833959093335, 'random_strength': 0.4253505173932581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:10:00,657] Trial 27 finished with value: 0.6456057314305289 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026527071571090403, 'depth': 4, 'l2_leaf_reg': 16.595179434297577, 'random_strength': 0.24981134039633576, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9697310994119842}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:10:37,676] Trial 28 finished with value: 0.652407125708572 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03322651802115874, 'depth': 6, 'l2_leaf_reg': 11.771097794948876, 'random_strength': 0.08795573581437278, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.90601745834071}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:11:15,324] Trial 29 finished with value: 0.6318072157485093 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.059466403331839356, 'depth': 6, 'l2_leaf_reg': 5.433003262215447, 'random_strength': 0.10544685694340253, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:12:16,986] Trial 30 finished with value: 0.6486637290127898 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033230367789247574, 'depth': 7, 'l2_leaf_reg': 2.673451035861274, 'random_strength': 0.10582488043550581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8819933760800733}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:12:30,129] Trial 31 finished with value: 0.6498945292574134 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02494827192857719, 'depth': 4, 'l2_leaf_reg': 13.045523301384094, 'random_strength': 0.15721999786246993, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9287086886671528}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:12:42,652] Trial 32 finished with value: 0.6484127446077919 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030537166290287146, 'depth': 4, 'l2_leaf_reg': 9.38849246291926, 'random_strength': 0.24629580101721812, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9125429299002304}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:13:09,071] Trial 33 finished with value: 0.6496647464498282 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04107242941765479, 'depth': 6, 'l2_leaf_reg': 11.524533616362167, 'random_strength': 0.06157196688292925, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9720595902837403}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:13:33,799] Trial 34 finished with value: 0.6444056766521553 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02330902747344571, 'depth': 5, 'l2_leaf_reg': 17.085715995815473, 'random_strength': 0.38454194837646544, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8330650004276805}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:13:44,617] Trial 35 finished with value: 0.6450863002141292 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05144604895142679, 'depth': 4, 'l2_leaf_reg': 8.255515282761897, 'random_strength': 0.2855921655081574, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.656001878923024}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:13:55,498] Trial 36 finished with value: 0.6394348127043552 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09608884882454823, 'depth': 5, 'l2_leaf_reg': 13.950347755887039, 'random_strength': 0.17254880096560116, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7315195031490394}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:16:00,973] Trial 37 finished with value: 0.633854378014058 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03295699498742718, 'depth': 8, 'l2_leaf_reg': 19.803777792265144, 'random_strength': 0.062271297024973304, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.04451881606481045}. Best is trial 1 with value: 0.6553038926072227.
[I 2026-04-15 15:16:39,663] Trial 38 finished with value: 0.6580984103145837 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020012247703397153, 'depth': 6, 'l2_leaf_reg': 8.676841767774652, 'random_strength': 0.1336769070260152, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7819235428128806}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:18:04,799] Trial 39 finished with value: 0.6453600731275162 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.027301150563282743, 'depth': 7, 'l2_leaf_reg': 6.8693496388637145, 'random_strength': 0.11893478785754996, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 3.91602211054221}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:18:34,130] Trial 40 finished with value: 0.643447852826086 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02248843599086594, 'depth': 6, 'l2_leaf_reg': 8.459372846495476, 'random_strength': 0.013233460374438108, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7829044709310956}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:20:30,780] Trial 41 finished with value: 0.6415686735812559 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.021078394236070084, 'depth': 7, 'l2_leaf_reg': 16.31079805309101, 'random_strength': 0.20933072455906676, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7570756707547227}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:21:13,723] Trial 42 finished with value: 0.6532780812388024 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02025206983903839, 'depth': 6, 'l2_leaf_reg': 10.72132116409193, 'random_strength': 0.3245765228499089, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9559349879293932}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:21:49,184] Trial 43 finished with value: 0.6488677756909991 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02547481484727591, 'depth': 6, 'l2_leaf_reg': 10.543279882779448, 'random_strength': 0.30500648838956534, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7312040889420934}. Best is trial 38 with value: 0.6580984103145837.
[I 2026-04-15 15:22:32,581] Trial 44 finished with value: 0.6434987656983224 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022965523171504604, 'depth': 6, 'l2_leaf_reg': 9.592260356076352, 'random_strength': 0.35858818538632914, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.819276521734624}. Best is trial 38 with value: 0.6580984103145837.

                                               feature  importance
56           eye__sac_length_AOI_aggregated_Pos_median    7.251115
53              eye__sac_length_AOI_aggregated_Pos_min    6.763889
63            eye__sac_speed_AOI_aggregated_Pos_median    5.728875
60               eye__sac_speed_AOI_aggregated_Pos_min    4.064787
62              eye__sac_speed_AOI_aggregated_Pos_mean    2.672050
178                 eye__fix_duration_AOI_FD_Neg1_mean    2.356228
276           eye__fix_duration_AOI_aggregated_Pos_min    2.214647
61               eye__sac_speed_AOI_aggregated_Pos_max    2.099593
168                             eye__fix_duration_mean    1.883088
54              eye__sac_length_AOI_aggregated_Pos_max    1.757331
55             eye__sac_length_AOI_aggregated_Pos_mean    1.649622
425         eye__rec_metric_euclidean_length_2_rho_500    1.571638
8                                   eye__sac_speed_min    1.506225
405         eye__rec_metric_euclidean_length_1_rho_500    1.468732
0                                  eye__sac_length_min    1.399546
31             eye__sac_length_AOI_aggregated_Neg_mean    1.242927
166                              eye__fix_duration_min    1.213265
279        eye__fix_duration_AOI_aggregated_Pos_median    1.191335
3                               eye__sac_length_median    1.119004
28                         eye__sac_angle_between_skew    1.072729
169                           eye__fix_duration_median    1.009230
176                  eye__fix_duration_AOI_FD_Neg1_min    1.003194
32           eye__sac_length_AOI_aggregated_Neg_median    0.951951
347               eye__lyapunov_exponent_m_2_tau_1_T_1    0.920475
175                eye__fix_duration_AOI_FD_Neg1_first    0.895968
184                eye__fix_duration_AOI_FD_Neg1_count    0.830801
177                  eye__fix_duration_AOI_FD_Neg1_max    0.820776
179               eye__fix_duration_AOI_FD_Neg1_median    0.820427
305                       eye__phase_entropy_m_2_tau_2    0.754572
89   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.737409

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,False,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,binary,True,0.403197,0.476267,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch,multiclass,False,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch,multiclass,True,NaN,0.505935,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,envelope,match_mismatch_general,binary,False,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,envelope,match_mismatch_general,binary,True,0.410526,0.542756,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,envelope,match_mismatch_general,multiclass,False,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,envelope,match_mismatch_general,multiclass,True,NaN,0.820915,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,envelope,match_mismatch,binary,False,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,envelope,match_mismatch,binary,True,0.403197,0.476267,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,envelope,match_mismatch,multiclass,False,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,envelope,match_mismatch,multiclass,True,NaN,0.505935,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,envelope,match_mismatch_general,binary,False,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,envelope,match_mismatch_general,binary,True,0.410526,0.542756,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,envelope,match_mismatch_general,multiclass,False,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,envelope,match_mismatch_general,multiclass,True,NaN,0.820915,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [8]:
text_freq_bands = _load_ftar_parquet(FTAR_FILES["freq_bands"])
print("freq_bands shape:", text_freq_bands.shape)
summary_freq_bands = run_ftar_set("freq_bands", text_freq_bands)
summary_freq_bands

freq_bands shape: (4442, 18362)
[freq_bands] ftar feature count after cleanup: 18361

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__ES__refitTEST
[freq_bands] rows missing after index match -> train: 1658, test: 160
[freq_bands] UMAP compression: train/test features 18361 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 15:30:20,557] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 15:30:24,610] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 15:30:29,598] Trial 1 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 15:30:34,640] Trial 2 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 15:30:39,624] Trial 3 finished with value: 0.4047750241239829 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 15:30:45,398] Trial 4 finished with value: 0.40804016705728074 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.40804016705728074.
[I 2026-04-15 15:30:51,483] Trial 5 finished with value: 0.4075716770478466 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 4 with value: 0.40804016705728074.
[I 2026-04-15 15:30:56,318] Trial 6 finished with value: 0.40497588413275515 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 4 with value: 0.40804016705728074.
[I 2026-04-15 15:31:02,447] Trial 7 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 4 with value: 0.40804016705728074.
[I 2026-04-15 15:31:07,937] Trial 8 finished with value: 0.41142690139246185 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:14,730] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:18,657] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11205588890315138, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8345351823143565, 'colsample_bytree': 0.8543230417001932, 'gamma': 1.3577299273807322, 'reg_alpha': 9.489578816424906, 'reg_lambda': 0.00015640362680098967}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:24,109] Trial 11 finished with value: 0.4027343097906718 and parameters: {'learning_rate': 0.08621855693937233, 'max_depth': 8, 'min_child_weight': 5.262425700550083, 'subsample': 0.893839626256697, 'colsample_bytree': 0.9145278309276617, 'gamma': 1.3104700566590528, 'reg_alpha': 1.811950242626371, 'reg_lambda': 0.002691378467733369}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:29,359] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07392183219836841, 'max_depth': 7, 'min_child_weight': 1.978511508670819, 'subsample': 0.9110905830371788, 'colsample_bytree': 0.999748196231103, 'gamma': 1.9047778262288537, 'reg_alpha': 0.8262259722410685, 'reg_lambda': 0.0007183080195481499}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:33,506] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12844075092236562, 'max_depth': 7, 'min_child_weight': 2.1881316983127173, 'subsample': 0.8389531725758507, 'colsample_bytree': 0.9258600689573643, 'gamma': 1.5379727109603907, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.007656455211866107}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:38,480] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1325131092618503, 'max_depth': 7, 'min_child_weight': 6.090383066997274, 'subsample': 0.9309381051275829, 'colsample_bytree': 0.8179424149152037, 'gamma': 1.0791845306157912, 'reg_alpha': 0.00010480002361979782, 'reg_lambda': 0.0001149404517214395}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:45,136] Trial 15 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0673128885316642, 'max_depth': 7, 'min_child_weight': 2.605443591982054, 'subsample': 0.8680457619873497, 'colsample_bytree': 0.8836559825946437, 'gamma': 0.684152480075638, 'reg_alpha': 0.0817914901103317, 'reg_lambda': 0.0007196069353435589}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:51,423] Trial 16 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05323656579640047, 'max_depth': 8, 'min_child_weight': 1.3197480093163605, 'subsample': 0.9942231535523713, 'colsample_bytree': 0.9706995565892128, 'gamma': 1.6120341607758626, 'reg_alpha': 0.005785923247348316, 'reg_lambda': 0.008593003551665814}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:31:55,944] Trial 17 finished with value: 0.40497588413275515 and parameters: {'learning_rate': 0.09100834444045469, 'max_depth': 4, 'min_child_weight': 6.6145195623550945, 'subsample': 0.809723099750917, 'colsample_bytree': 0.9559671865014475, 'gamma': 0.40842171415177475, 'reg_alpha': 1.5572731705925729, 'reg_lambda': 0.0023073258991014537}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:32:00,075] Trial 18 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.13572324503277164, 'max_depth': 6, 'min_child_weight': 4.447043294973266, 'subsample': 0.7543655957773596, 'colsample_bytree': 0.8899841161653445, 'gamma': 1.9973041301401762, 'reg_alpha': 0.2516611104111061, 'reg_lambda': 0.0003376411856190126}. Best is trial 8 with value: 0.41142690139246185.
[I 2026-04-15 15:32:06,230] Trial 19 finished with value: 0.41221286467453616 and parameters: {'learning_rate': 0.07293682018510707, 'max_depth': 7, 'min_child_weight': 1.4444276805611285, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.8382489936054243, 'gamma': 1.2763326476302224, 'reg_alpha': 0.0064650635797320775, 'reg_lambda': 0.0023805889009396526}. Best is trial 19 with value: 0.41221286467453616.
[I 2026-04-15 15:32:09,963] Trial 20 finished with value: 0.41699748574713313 and parameters: {'learning_rate': 0.18797810181672966, 'max_depth': 4, 'min_child_weight': 1.448005606504117, 'subsample': 0.701100226549241, 'colsample_bytree': 0.833827090589568, 'gamma': 1.2938553917815745, 'reg_alpha': 0.003956159087266928, 'reg_lambda': 0.019072723549575683}. Best is trial 20 with value: 0.41699748574713313.
[I 2026-04-15 15:32:13,746] Trial 21 finished with value: 0.4088827998573468 and parameters: {'learning_rate': 0.19533555606702324, 'max_depth': 4, 'min_child_weight': 1.5197172750449006, 'subsample': 0.7117452532833489, 'colsample_bytree': 0.8273850997729796, 'gamma': 1.2672824984600277, 'reg_alpha': 0.0034965474738539257, 'reg_lambda': 0.017443007316083236}. Best is trial 20 with value: 0.41699748574713313.
[I 2026-04-15 15:32:17,801] Trial 22 finished with value: 0.405935470538425 and parameters: {'learning_rate': 0.15714579741973822, 'max_depth': 3, 'min_child_weight': 1.0087524775118908, 'subsample': 0.7029731632232117, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.8817677247421759, 'reg_alpha': 0.0014465800732849606, 'reg_lambda': 0.0038517087686136477}. Best is trial 20 with value: 0.41699748574713313.
[I 2026-04-15 15:32:22,900] Trial 23 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11107701012334556, 'max_depth': 5, 'min_child_weight': 1.5833952715892017, 'subsample': 0.7391373322670772, 'colsample_bytree': 0.8524789205247496, 'gamma': 1.1514996764372953, 'reg_alpha': 0.013021336281854569, 'reg_lambda': 0.03113312454798587}. Best is trial 20 with value: 0.41699748574713313.
[I 2026-04-15 15:32:27,691] Trial 24 finished with value: 0.4104978076826886 and parameters: {'learning_rate': 0.10862126150154874, 'max_depth': 4, 'min_child_weight': 2.4483629139990715, 'subsample': 0.7288975852414764, 'colsample_bytree': 0.799822299173903, 'gamma': 1.4328593804437237, 'reg_alpha': 0.0005441929656801093, 'reg_lambda': 0.18295303654943043}. Best is trial 20 with value: 0.41699748574713313.
[I 2026-04-15 15:32:32,850] Trial 25 finished with value: 0.4178802673726318 and parameters: {'learning_rate': 0.14945250306510333, 'max_depth': 6, 'min_child_weight': 1.2989472545489185, 'subsample': 0.7592549061855012, 'colsample_bytree': 0.8397083447791017, 'gamma': 0.9572773113824686, 'reg_alpha': 0.0012010090604401156, 'reg_lambda': 0.017254765368792235}. Best is trial 25 with value: 0.4178802673726318.
[I 2026-04-15 15:32:37,150] Trial 26 finished with value: 0.42151564975962186 and parameters: {'learning_rate': 0.18971192603822265, 'max_depth': 3, 'min_child_weight': 1.2236140021242328, 'subsample': 0.7602500782950713, 'colsample_bytree': 0.8276051552179774, 'gamma': 0.9246756046557595, 'reg_alpha': 0.001501143159389054, 'reg_lambda': 0.018926133195797303}. Best is trial 26 with value: 0.42151564975962186.
[I 2026-04-15 15:32:41,478] Trial 27 finished with value: 0.4242971900072999 and parameters: {'learning_rate': 0.19959839833792142, 'max_depth': 3, 'min_child_weight': 1.1186252316108558, 'subsample': 0.7580785394426199, 'colsample_bytree': 0.7770663532934639, 'gamma': 0.9048045783666798, 'reg_alpha': 0.0012304317457153048, 'reg_lambda': 0.022238857001143576}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:32:46,005] Trial 28 finished with value: 0.41331072683071163 and parameters: {'learning_rate': 0.14663486384195276, 'max_depth': 3, 'min_child_weight': 1.2482036708403357, 'subsample': 0.8150391226653676, 'colsample_bytree': 0.7850633722676211, 'gamma': 0.9051884619019107, 'reg_alpha': 0.00010783132288118588, 'reg_lambda': 0.28910386218320955}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:32:50,473] Trial 29 finished with value: 0.4242971900072999 and parameters: {'learning_rate': 0.1988599537550515, 'max_depth': 3, 'min_child_weight': 1.103454495511174, 'subsample': 0.7602863788475458, 'colsample_bytree': 0.7741349215841203, 'gamma': 0.47583908329123287, 'reg_alpha': 0.00041942765924320646, 'reg_lambda': 0.057794541426514405}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:32:54,813] Trial 30 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.19334245484924667, 'max_depth': 3, 'min_child_weight': 1.2005561916757657, 'subsample': 0.8086552806626984, 'colsample_bytree': 0.7736393250539384, 'gamma': 0.5076131178991343, 'reg_alpha': 0.00037872041809710515, 'reg_lambda': 5.484594606053764}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:32:59,076] Trial 31 finished with value: 0.4176219906892246 and parameters: {'learning_rate': 0.15857192262280478, 'max_depth': 3, 'min_child_weight': 1.1558094467212776, 'subsample': 0.7697140397331746, 'colsample_bytree': 0.8119141096188296, 'gamma': 0.746857981603871, 'reg_alpha': 0.0013621966722788899, 'reg_lambda': 0.06695615833448064}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:33:03,420] Trial 32 finished with value: 0.413086038165656 and parameters: {'learning_rate': 0.16559893626701808, 'max_depth': 3, 'min_child_weight': 1.8417813492819701, 'subsample': 0.7570575827826812, 'colsample_bytree': 0.7729909852288415, 'gamma': 0.2725018791679506, 'reg_alpha': 0.0002849964866013775, 'reg_lambda': 0.03148098258187295}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:33:07,415] Trial 33 finished with value: 0.4236422137107042 and parameters: {'learning_rate': 0.19724452794512384, 'max_depth': 4, 'min_child_weight': 1.1438299467799569, 'subsample': 0.7266062045187626, 'colsample_bytree': 0.7146546245407901, 'gamma': 0.9323049819585425, 'reg_alpha': 0.0012765156591333076, 'reg_lambda': 0.015186575020637427}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:33:11,510] Trial 34 finished with value: 0.41142690139246185 and parameters: {'learning_rate': 0.19633201783737833, 'max_depth': 4, 'min_child_weight': 1.1127916724293272, 'subsample': 0.7239923070817518, 'colsample_bytree': 0.7119987876010652, 'gamma': 0.6388632658260478, 'reg_alpha': 0.0002534201821493374, 'reg_lambda': 1.7655429317422575}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:33:15,732] Trial 35 finished with value: 0.4228093538771492 and parameters: {'learning_rate': 0.1713429599587807, 'max_depth': 3, 'min_child_weight': 1.707467620441563, 'subsample': 0.7326254296817062, 'colsample_bytree': 0.7575504871403768, 'gamma': 0.44960351063185344, 'reg_alpha': 0.000902130769132092, 'reg_lambda': 0.005162089528174083}. Best is trial 27 with value: 0.4242971900072999.
[I 2026-04-15 15:33:19,903] Trial 36 finished with value: 0.4259294648829277 and parameters: {'learning_rate': 0.16976230784069646, 'max_depth': 3, 'min_child_weight': 1.7327291497906467, 'subsample': 0.7349903818601863, 'colsample_bytree': 0.7262205835194464, 'gamma': 0.3701369532713258, 'reg_alpha': 0.0006346633112000338, 'reg_lambda': 0.005876414249633082}. Best is trial 36 with value: 0.4259294648829277.
[I 2026-04-15 15:33:24,798] Trial 37 finished with value: 0.4093953639826219 and parameters: {'learning_rate': 0.13901036356689667, 'max_depth': 4, 'min_child_weight': 1.0676004400458576, 'subsample': 0.7781124092585633, 'colsample_bytree': 0.72440627237641, 'gamma': 0.2660344482791355, 'reg_alpha': 0.0029011351400096428, 'reg_lambda': 0.09215715102252248}. Best is trial 36 with value: 0.4259294648829277.
[I 2026-04-15 15:33:29,464] Trial 38 finished with value: 0.43377187428653763 and parameters: {'learning_rate': 0.1684333457262146, 'max_depth': 4, 'min_child_weight': 2.102158001763086, 'subsample': 0.7461506440774581, 'colsample_bytree': 0.7316157867727037, 'gamma': 0.8007096715792918, 'reg_alpha': 0.00021043207188492283, 'reg_lambda': 0.04111614744110114}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:34,812] Trial 39 finished with value: 0.4071038039413468 and parameters: {'learning_rate': 0.10150580701586197, 'max_depth': 5, 'min_child_weight': 2.689747281756382, 'subsample': 0.7443477271004068, 'colsample_bytree': 0.7391405879612443, 'gamma': 0.1329953001165749, 'reg_alpha': 0.00019368665359435408, 'reg_lambda': 0.27608497748487243}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:39,163] Trial 40 finished with value: 0.4078058310351545 and parameters: {'learning_rate': 0.040257617951018156, 'max_depth': 3, 'min_child_weight': 2.0067727922726735, 'subsample': 0.7961155793882885, 'colsample_bytree': 0.7586148885257289, 'gamma': 0.7718523156885946, 'reg_alpha': 0.000560400635571141, 'reg_lambda': 0.04752806877382847}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:43,690] Trial 41 finished with value: 0.40570184855036173 and parameters: {'learning_rate': 0.17151877852537875, 'max_depth': 4, 'min_child_weight': 3.137506780606423, 'subsample': 0.7203707752985596, 'colsample_bytree': 0.7227907618131898, 'gamma': 0.5313014561711509, 'reg_alpha': 0.0008072426468600223, 'reg_lambda': 0.010813303900046851}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:48,418] Trial 42 finished with value: 0.40763231060666527 and parameters: {'learning_rate': 0.12368387583666934, 'max_depth': 4, 'min_child_weight': 2.279360290192466, 'subsample': 0.7461809894896384, 'colsample_bytree': 0.7011080792760416, 'gamma': 0.3852575491301983, 'reg_alpha': 0.00017911232829780855, 'reg_lambda': 0.04206622021785093}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:52,750] Trial 43 finished with value: 0.41321642086293936 and parameters: {'learning_rate': 0.1736849941156265, 'max_depth': 3, 'min_child_weight': 1.7401346090306422, 'subsample': 0.7722802557206424, 'colsample_bytree': 0.724986622933485, 'gamma': 0.008050105358543558, 'reg_alpha': 0.002456155091611816, 'reg_lambda': 0.005001352731798243}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:33:58,656] Trial 44 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.02188029840119486, 'max_depth': 5, 'min_child_weight': 1.4015774996555874, 'subsample': 0.7196438236834991, 'colsample_bytree': 0.7507030699980668, 'gamma': 0.8452441308481953, 'reg_alpha': 0.0004600102791032878, 'reg_lambda': 0.16078965118905145}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:34:02,631] Trial 45 finished with value: 0.40866938731005165 and parameters: {'learning_rate': 0.14859229783751185, 'max_depth': 3, 'min_child_weight': 1.8699161452283728, 'subsample': 0.7973501110178125, 'colsample_bytree': 0.736274525209226, 'gamma': 1.0114270022893674, 'reg_alpha': 0.008053119773856253, 'reg_lambda': 0.7179715368512191}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:34:06,616] Trial 46 finished with value: 0.42349070853420756 and parameters: {'learning_rate': 0.17879745403339825, 'max_depth': 4, 'min_child_weight': 1.13519437290037, 'subsample': 0.7330658951825129, 'colsample_bytree': 0.7696587140478959, 'gamma': 0.17859042973810035, 'reg_alpha': 0.00016432228086391324, 'reg_lambda': 0.01168311957875049}. Best is trial 38 with value: 0.43377187428653763.
[I 2026-04-15 15:34:10,177] Trial 47 finished with value: 0.4182811068622083 and parameters: {'learning_rate': 0.1581172384774968, 'max_depth': 3, 'min_child_weight': 1.586108366008051, 'subsample': 0.745860548136955, 'colsample_bytree': 0.7169494131253786, 'gamma': 0.7352963565631336, 'reg_alpha': 0.001961587325192462, 'reg_lambda': 0.0011544477473172056}. Best is trial 38 with value: 0.43377187428653763.

[I 2026-04-15 15:37:59,244] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 15:38:03,568] Trial 0 finished with value: 0.40843385855377773 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.40843385855377773.
[I 2026-04-15 15:38:12,059] Trial 1 finished with value: 0.4196639829499322 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4196639829499322.
[I 2026-04-15 15:38:19,552] Trial 2 finished with value: 0.4261574089824858 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4261574089824858.
[I 2026-04-15 15:38:32,501] Trial 3 finished with value: 0.42140377174060795 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.4261574089824858.
[I 2026-04-15 15:38:52,196] Trial 4 finished with value: 0.4703955544723996 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:39:15,674] Trial 5 finished with value: 0.41538997927344856 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:39:28,910] Trial 6 finished with value: 0.4158393773312587 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:39:43,521] Trial 7 finished with value: 0.40978645654904644 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:40:12,644] Trial 8 finished with value: 0.4088604936958724 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:40:24,658] Trial 9 finished with value: 0.42878383477368553 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:40:29,097] Trial 10 finished with value: 0.42186266476099255 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:40:39,848] Trial 11 finished with value: 0.44574656811776836 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 1.0029240690742995, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.610132565398292}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:40:58,886] Trial 12 finished with value: 0.4570462559582928 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 8, 'l2_leaf_reg': 1.0091362923696217, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8686828876459834}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:41:18,720] Trial 13 finished with value: 0.4695385255844434 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 8, 'l2_leaf_reg': 1.8397252946102833, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8964878379203041}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:41:38,635] Trial 14 finished with value: 0.45702498249679724 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12960885498831629, 'depth': 8, 'l2_leaf_reg': 2.0956663066759345, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8424234616468694}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:41:45,426] Trial 15 finished with value: 0.4474682388029703 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12261083637914576, 'depth': 6, 'l2_leaf_reg': 3.016699755646488, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9814769576437812}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:42:04,637] Trial 16 finished with value: 0.4642515777413475 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12541132626934667, 'depth': 8, 'l2_leaf_reg': 1.5178377370645912, 'random_strength': 0.09255807539467345, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7982762909636927}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:42:15,583] Trial 17 finished with value: 0.4337167419073049 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1432748777214715, 'depth': 7, 'l2_leaf_reg': 3.276532958863645, 'random_strength': 0.4440752281517034, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8836194347943916}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:42:20,385] Trial 18 finished with value: 0.43859892216427987 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10208292973065027, 'depth': 5, 'l2_leaf_reg': 2.6601338671543076, 'random_strength': 0.22683551332574908, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7608741990248086}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:42:42,450] Trial 19 finished with value: 0.43279673769753435 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.051518582818118774, 'depth': 8, 'l2_leaf_reg': 1.3850595279469555, 'random_strength': 0.08036170107695785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9211876106857644}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:42:49,348] Trial 20 finished with value: 0.4313650486265104 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1544829685042153, 'depth': 6, 'l2_leaf_reg': 5.569849053748985, 'random_strength': 0.5670330472756, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.822026085437717}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:43:09,797] Trial 21 finished with value: 0.470157565653643 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10894913478329087, 'depth': 8, 'l2_leaf_reg': 1.474680020313855, 'random_strength': 0.08931420872156286, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7948272611360603}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:43:29,965] Trial 22 finished with value: 0.4540320370131947 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11066258554499758, 'depth': 8, 'l2_leaf_reg': 1.3255341254537023, 'random_strength': 0.0010084962427513444, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7383775275859609}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:43:40,364] Trial 23 finished with value: 0.4593791973628076 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19919632455184128, 'depth': 7, 'l2_leaf_reg': 2.221168336280611, 'random_strength': 0.22068238455617156, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7994578167239308}. Best is trial 4 with value: 0.4703955544723996.
[I 2026-04-15 15:44:00,405] Trial 24 finished with value: 0.47471154923482584 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14603408175909446, 'depth': 8, 'l2_leaf_reg': 1.525107566724828, 'random_strength': 0.08365877092444227, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7315152450254329}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:44:11,554] Trial 25 finished with value: 0.4622681602946209 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.149905097968601, 'depth': 7, 'l2_leaf_reg': 1.317372416322618, 'random_strength': 0.3868169924557151, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7079411078895562}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:44:32,457] Trial 26 finished with value: 0.46015742935831633 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09616630347870851, 'depth': 8, 'l2_leaf_reg': 2.5574187367593852, 'random_strength': 0.10564277630860319, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:44:37,286] Trial 27 finished with value: 0.4312888680677637 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05739457992706806, 'depth': 5, 'l2_leaf_reg': 3.7289714152131666, 'random_strength': 0.20289943454127296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6586122753434075}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:44:50,653] Trial 28 finished with value: 0.4381867569048035 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.036710656683473196, 'depth': 7, 'l2_leaf_reg': 1.4348272003970692, 'random_strength': 0.26343343226066795, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7419990238026172}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:45:14,328] Trial 29 finished with value: 0.4279792214356833 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06366623464300361, 'depth': 8, 'l2_leaf_reg': 1.7056675450098129, 'random_strength': 0.12115872780470982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 24 with value: 0.47471154923482584.
[I 2026-04-15 15:45:33,489] Trial 30 finished with value: 0.4778657871783467 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15255242537438815, 'depth': 8, 'l2_leaf_reg': 2.276826904760006, 'random_strength': 0.07058773079953745, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7813779527221643}. Best is trial 30 with value: 0.4778657871783467.
[I 2026-04-15 15:45:53,178] Trial 31 finished with value: 0.4857303111486794 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1657660661095975, 'depth': 8, 'l2_leaf_reg': 2.366968334857507, 'random_strength': 0.08919543814498276, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.786986132087842}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:46:13,005] Trial 32 finished with value: 0.4605821336571113 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1727664934856563, 'depth': 8, 'l2_leaf_reg': 2.243337863951294, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.720217071679626}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:46:16,528] Trial 33 finished with value: 0.43937731667323915 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15416085166518698, 'depth': 4, 'l2_leaf_reg': 2.54380769546854, 'random_strength': 0.05843696221114046, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7731120118306755}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:46:27,636] Trial 34 finished with value: 0.467901034652983 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17755624611506923, 'depth': 7, 'l2_leaf_reg': 6.061026328994233, 'random_strength': 0.15104492934478406, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.8341789381053895}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:46:51,286] Trial 35 finished with value: 0.43563046512694165 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 8, 'l2_leaf_reg': 3.0977863065508147, 'random_strength': 0.3876511800088076, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6702135508991707}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:47:03,293] Trial 36 finished with value: 0.44733185610942483 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14484129766267592, 'depth': 7, 'l2_leaf_reg': 1.1746508492668255, 'random_strength': 0.24679273226325016, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7315195031490394}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:47:23,050] Trial 37 finished with value: 0.460790205860398 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0888937341494891, 'depth': 8, 'l2_leaf_reg': 1.905751333015056, 'random_strength': 0.14479709943430044, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.04451881606481045}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:47:43,919] Trial 38 finished with value: 0.4408470348312981 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11332854805437405, 'depth': 8, 'l2_leaf_reg': 3.929972352548604, 'random_strength': 0.30056544557257936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7747204929354136}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:47:54,658] Trial 39 finished with value: 0.444205820235689 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1968333386895604, 'depth': 7, 'l2_leaf_reg': 1.1683128991606822, 'random_strength': 0.5563924947808183, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 3.91602211054221}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:47:57,988] Trial 40 finished with value: 0.4371374495427549 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08699117658544306, 'depth': 4, 'l2_leaf_reg': 4.910043836426696, 'random_strength': 0.07294791011308957, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6881491682512761}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:48:17,604] Trial 41 finished with value: 0.4797270558324244 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13820519638802226, 'depth': 8, 'l2_leaf_reg': 1.523627509811776, 'random_strength': 0.04958680005243369, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7964202449235998}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:48:37,135] Trial 42 finished with value: 0.4559193240948396 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16222980468574658, 'depth': 8, 'l2_leaf_reg': 1.723144713970273, 'random_strength': 0.05421931341945956, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.756218282272714}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:48:56,732] Trial 43 finished with value: 0.4525527746563152 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1435072271418442, 'depth': 8, 'l2_leaf_reg': 2.0668434869033137, 'random_strength': 0.04993318478108543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8219038983781162}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:49:19,649] Trial 44 finished with value: 0.43905712037835665 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13041587893306625, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.13016009167697468, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7807224710642443}. Best is trial 31 with value: 0.4857303111486794.
[I 2026-04-15 15:49:39,037] Trial 45 finished with value: 0.4437191923692959 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18039627159258767, 'depth': 8, 'l2_leaf_reg': 1.6499765688307355, 'random_strength': 0.7929157495500838, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7566131459647656}. Best is trial 31 with value: 0.4857303111486794.

                                    feature  importance
506                    freq_bands__umap_036    0.233589
505                    freq_bands__umap_035    0.228586
503                    freq_bands__umap_033    0.223108
551                    freq_bands__umap_081    0.121159
473                    freq_bands__umap_003    0.108387
40    eye__sac_speed_AOI_aggregated_Neg_std    0.081780
33   eye__sac_length_AOI_aggregated_Neg_std    0.003392
19                  eye__sac_angle_to_x_std    0.000000
20             eye__sac_angle_to_x_kurtosis    0.000000
21                 eye__sac_angle_to_x_skew    0.000000
22               eye__sac_angle_between_min    0.000000
23               eye__sac_angle_between_max    0.000000
24              eye__sac_angle_between_mean    0.000000
25            eye__sac_angle_between_median    0.000000
513                    freq_bands__umap_043    0.000000
57   eye__sac_length_AOI_aggregated_Pos_std    0.000000
545                    freq_bands__umap_075    0.000000
537                    freq_bands__umap_067    0.000000
569                    freq_bands__umap_099    0.000000
0                       eye__sac_length_min    0.000000
1                       eye__sac_length_max    0.000000
2                      eye__sac_length_mean    0.000000
3                    eye__sac_length_median    0.000000
4                       eye__sac_length_std    0.000000
5                       eye__sac_length_sum    0.000000
6                  eye__sac_length_kurtosis    0.000000
7                      eye__sac_length_skew    0.000000
26               eye__sac_angle_between_std    0.000000
27          eye__sac_angle_between_kurtosis    0.000000
28              eye__sac_angle_between_skew    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.44346
              precision    recall  f1-score   support

           0       0.68      0.98      0.80       227
           1       0.50      0.05      0.08       109

    accuracy                           0.68       336
   macro avg       0.59      0.51      0.44       336
weighted avg       0.62      0.68      0.57       336

Confusion matrix:
 [[222   5]
 [104   5]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+freq_bands__target=match_mismatch__problem=binary__feat=all_features+freq_bands__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
56    eye__sac_length_AOI_aggregated_Pos_median    7.929667
566                        freq_bands__umap_096    6.437563
539                        freq_bands__umap_069    6.244486
314                    eye__incremental_entropy    5.607097
534                        freq_bands__umap_064    5.569658
503                        freq_bands__umap_033    5.091466
569                        freq_bands__umap_099    5.011515
486                        freq_bands__umap_016    4.469390
538                        freq_bands__umap_068    4.196055
472                        freq_bands__umap_002    4.131260
475                        freq_bands__umap_005    3.834628
284  eye__fix_duration_AOI_aggregated_Pos_count    3.696173
277    eye__fix_duration_AOI_aggregated_Pos_max    3.539256
516                        freq_bands__umap_046    3.495773
268  eye__fix_duration_AOI_aggregated_None_mean    3.467090
523                        freq_bands__umap_053    3.275082
465                               eye__imf0_max    3.034274
464                               eye__imf0_min    3.032930
565                        freq_bands__umap_095    2.854913
346               eye__sample_entropy_m=4_r=800    2.482407
182          eye__fix_duration_AOI_FD_Neg1_skew    2.324706
19                      eye__sac_angle_to_x_std    2.268266
321                       eye__hurst_exponent.5    1.783929
568                        freq_bands__umap_098    1.774232
476                        freq_bands__umap_006    1.766890
443         eye__lam_euclidean_length_3_rho_250    1.657092
205         eye__fix_duration_AOI_FD_Pos1_first    1.024199
3                        eye__sac_length_median    0.000000
4                           eye__sac_length_std    0.000000
5                           eye__sac_length_sum    0.000000

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST
[freq_bands] rows missing after index match -> train: 1658, test: 160
[freq_bands] UMAP compression: train/test features 18361 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 15:53:41,870] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+freq_bands__target=match_mismatch__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 15:53:47,924] Trial 0 finished with value: 0.5060541778049406 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5060541778049406.
[I 2026-04-15 15:53:54,825] Trial 1 finished with value: 0.4910257042981999 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5060541778049406.
[I 2026-04-15 15:54:02,379] Trial 2 finished with value: 0.5205113368452865 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:08,442] Trial 3 finished with value: 0.5190176728793976 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:13,807] Trial 4 finished with value: 0.5175921089710424 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:22,459] Trial 5 finished with value: 0.5078883918175973 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:27,684] Trial 6 finished with value: 0.5178041078403175 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:37,588] Trial 7 finished with value: 0.5061012993649725 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:44,045] Trial 8 finished with value: 0.49136273488332355 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:54:54,466] Trial 9 finished with value: 0.5105163255378211 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:01,059] Trial 10 finished with value: 0.5167809287934663 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8323975169664899, 'colsample_bytree': 0.8251024923043149, 'gamma': 1.4856799266904641, 'reg_alpha': 0.000753460297138337, 'reg_lambda': 0.00839106795699683}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:08,203] Trial 11 finished with value: 0.5196720696740108 and parameters: {'learning_rate': 0.08340624238172284, 'max_depth': 4, 'min_child_weight': 4.72589178768227, 'subsample': 0.8681103830281228, 'colsample_bytree': 0.8277506537128274, 'gamma': 0.7242576829236649, 'reg_alpha': 0.004104493362805331, 'reg_lambda': 0.6308960659343819}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:14,627] Trial 12 finished with value: 0.49014692424101475 and parameters: {'learning_rate': 0.03499279857296113, 'max_depth': 3, 'min_child_weight': 2.1544447474728132, 'subsample': 0.908224417422708, 'colsample_bytree': 0.8200005224971499, 'gamma': 1.388531138825063, 'reg_alpha': 0.004426984370678881, 'reg_lambda': 8.192221849084122}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:20,787] Trial 13 finished with value: 0.5162566003029618 and parameters: {'learning_rate': 0.06933320335699729, 'max_depth': 4, 'min_child_weight': 1.0271749888333273, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.8685753186474328, 'gamma': 0.5784678776724193, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 0.3975935845640876}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:28,079] Trial 14 finished with value: 0.51168462814726 and parameters: {'learning_rate': 0.04038365884445841, 'max_depth': 4, 'min_child_weight': 5.293870612391065, 'subsample': 0.755956762637413, 'colsample_bytree': 0.7902234731076087, 'gamma': 1.479903987880859, 'reg_alpha': 0.0001004306624937685, 'reg_lambda': 0.022070090189769947}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:34,486] Trial 15 finished with value: 0.5190440710705829 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 5, 'min_child_weight': 2.4370747834999373, 'subsample': 0.8303830123198209, 'colsample_bytree': 0.7035193179308173, 'gamma': 0.8197688721302416, 'reg_alpha': 0.0053443858874273305, 'reg_lambda': 0.00016599250040776937}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:41,895] Trial 16 finished with value: 0.49537770479096127 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 4, 'min_child_weight': 1.3352420898821897, 'subsample': 0.9000589504081506, 'colsample_bytree': 0.8029023571986477, 'gamma': 1.7034494005187308, 'reg_alpha': 0.0005074275470750733, 'reg_lambda': 1.8152074057562284}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:46,957] Trial 17 finished with value: 0.4989423505329269 and parameters: {'learning_rate': 0.06057148734549923, 'max_depth': 3, 'min_child_weight': 2.753062054218423, 'subsample': 0.8087096498193439, 'colsample_bytree': 0.8497830228868134, 'gamma': 1.2236897605322707, 'reg_alpha': 0.009913060169943573, 'reg_lambda': 0.1359490889687767}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:55:54,530] Trial 18 finished with value: 0.5116700832209358 and parameters: {'learning_rate': 0.09330137070176413, 'max_depth': 7, 'min_child_weight': 5.8133534038793355, 'subsample': 0.9318271613739229, 'colsample_bytree': 0.8868948588223814, 'gamma': 0.7517851526654891, 'reg_alpha': 0.0016833335803052476, 'reg_lambda': 0.031418657807086005}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:56:02,967] Trial 19 finished with value: 0.48448007628229184 and parameters: {'learning_rate': 0.05000525014409872, 'max_depth': 5, 'min_child_weight': 4.022246494025659, 'subsample': 0.7042325464765103, 'colsample_bytree': 0.7827630840837515, 'gamma': 0.37481570918063334, 'reg_alpha': 0.00016767217242076926, 'reg_lambda': 0.22592104221750378}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:56:10,000] Trial 20 finished with value: 0.4982703110659833 and parameters: {'learning_rate': 0.030629073551862982, 'max_depth': 4, 'min_child_weight': 1.448005606504117, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.8466445670931371, 'gamma': 1.6633902606414754, 'reg_alpha': 0.05020909596203195, 'reg_lambda': 1.2912395231475258}. Best is trial 2 with value: 0.5205113368452865.
[I 2026-04-15 15:56:16,031] Trial 21 finished with value: 0.5226379428325739 and parameters: {'learning_rate': 0.13991093006284086, 'max_depth': 5, 'min_child_weight': 2.3669066394654332, 'subsample': 0.8611386022001416, 'colsample_bytree': 0.7040537086642553, 'gamma': 0.855086491533449, 'reg_alpha': 0.005999527922726178, 'reg_lambda': 0.00013702832592630656}. Best is trial 21 with value: 0.5226379428325739.
[I 2026-04-15 15:56:21,831] Trial 22 finished with value: 0.5135161351871594 and parameters: {'learning_rate': 0.13803603597184622, 'max_depth': 5, 'min_child_weight': 2.0128157918624656, 'subsample': 0.8801766797143009, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.8951224526529732, 'reg_alpha': 0.013211487018448625, 'reg_lambda': 0.00010275426836285777}. Best is trial 21 with value: 0.5226379428325739.
[I 2026-04-15 15:56:28,374] Trial 23 finished with value: 0.5140703334006591 and parameters: {'learning_rate': 0.09235546036730008, 'max_depth': 4, 'min_child_weight': 2.583545057891247, 'subsample': 0.8500649660939663, 'colsample_bytree': 0.9023242543144618, 'gamma': 0.6017583585790188, 'reg_alpha': 0.001833893722992526, 'reg_lambda': 0.011006179291942505}. Best is trial 21 with value: 0.5226379428325739.
[I 2026-04-15 15:56:33,466] Trial 24 finished with value: 0.5267676715791355 and parameters: {'learning_rate': 0.14297839174327748, 'max_depth': 5, 'min_child_weight': 1.2158542117865274, 'subsample': 0.8229043196346122, 'colsample_bytree': 0.7676538231698826, 'gamma': 1.0002689071555713, 'reg_alpha': 0.0013419587534221206, 'reg_lambda': 0.000424955385784902}. Best is trial 24 with value: 0.5267676715791355.
[I 2026-04-15 15:56:38,493] Trial 25 finished with value: 0.5300399342965548 and parameters: {'learning_rate': 0.18762530221343066, 'max_depth': 5, 'min_child_weight': 1.3071068181675392, 'subsample': 0.7630780798507649, 'colsample_bytree': 0.7272129870121996, 'gamma': 1.2564977582646124, 'reg_alpha': 0.0012163352999225103, 'reg_lambda': 0.0003568644319340937}. Best is trial 25 with value: 0.5300399342965548.
[I 2026-04-15 15:56:42,920] Trial 26 finished with value: 0.5364888270652748 and parameters: {'learning_rate': 0.18971192603822265, 'max_depth': 6, 'min_child_weight': 1.2196488089004114, 'subsample': 0.8108618195483643, 'colsample_bytree': 0.7223768405381139, 'gamma': 1.2072053291338327, 'reg_alpha': 0.0012760007177938639, 'reg_lambda': 0.0002627406544434103}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:56:47,642] Trial 27 finished with value: 0.5259913138422655 and parameters: {'learning_rate': 0.19959839833792142, 'max_depth': 7, 'min_child_weight': 1.1843511828206854, 'subsample': 0.8229162329578518, 'colsample_bytree': 0.731776212727121, 'gamma': 1.2876828820547983, 'reg_alpha': 0.000222979762149347, 'reg_lambda': 0.00035756316269210055}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:56:53,509] Trial 28 finished with value: 0.526988320948524 and parameters: {'learning_rate': 0.19587304034123018, 'max_depth': 6, 'min_child_weight': 1.642327270312343, 'subsample': 0.7418457820685559, 'colsample_bytree': 0.7647190080328792, 'gamma': 0.9880687859706809, 'reg_alpha': 0.0012061924672351564, 'reg_lambda': 0.0030124582001619772}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:56:59,258] Trial 29 finished with value: 0.5142729313114424 and parameters: {'learning_rate': 0.19889636835780897, 'max_depth': 8, 'min_child_weight': 1.706284887306442, 'subsample': 0.7356936885023716, 'colsample_bytree': 0.7600570762894452, 'gamma': 1.2230105010633916, 'reg_alpha': 0.00041517258102074985, 'reg_lambda': 0.00303087323657766}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:05,315] Trial 30 finished with value: 0.5298898432710423 and parameters: {'learning_rate': 0.16597221024006528, 'max_depth': 7, 'min_child_weight': 1.556548824492271, 'subsample': 0.7263403937734849, 'colsample_bytree': 0.7226605005377547, 'gamma': 1.1326826981887554, 'reg_alpha': 0.0010222737425168026, 'reg_lambda': 0.0003441159368901683}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:11,572] Trial 31 finished with value: 0.5274882850458056 and parameters: {'learning_rate': 0.1657363823819051, 'max_depth': 7, 'min_child_weight': 1.560591953507572, 'subsample': 0.7212312591123682, 'colsample_bytree': 0.7180732907993358, 'gamma': 1.0830483076536956, 'reg_alpha': 0.0008102673877725388, 'reg_lambda': 0.0003420353102101175}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:17,414] Trial 32 finished with value: 0.5053096940164469 and parameters: {'learning_rate': 0.16237073444114977, 'max_depth': 7, 'min_child_weight': 1.165523413263945, 'subsample': 0.7224939011126889, 'colsample_bytree': 0.7198203222204294, 'gamma': 1.399364916153476, 'reg_alpha': 0.00028684960389761924, 'reg_lambda': 0.00035265423665640225}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:24,110] Trial 33 finished with value: 0.508247649362682 and parameters: {'learning_rate': 0.11505760096286849, 'max_depth': 8, 'min_child_weight': 1.500637391956245, 'subsample': 0.7622011981664306, 'colsample_bytree': 0.7214201155147665, 'gamma': 1.1474807988588764, 'reg_alpha': 0.0006690075055932802, 'reg_lambda': 0.0007528553426777376}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:29,940] Trial 34 finished with value: 0.493125004870068 and parameters: {'learning_rate': 0.1639679444580962, 'max_depth': 7, 'min_child_weight': 1.8497043781640787, 'subsample': 0.703285579153645, 'colsample_bytree': 0.720843606002292, 'gamma': 1.3138703008323156, 'reg_alpha': 0.0009896962609213494, 'reg_lambda': 0.0002465846470185174}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:35,546] Trial 35 finished with value: 0.5143493623985239 and parameters: {'learning_rate': 0.16900129579911036, 'max_depth': 7, 'min_child_weight': 1.2985062318679534, 'subsample': 0.7677898129193084, 'colsample_bytree': 0.7482461793246162, 'gamma': 1.5285091339974364, 'reg_alpha': 0.0023711080203840853, 'reg_lambda': 0.0007208767676837778}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:41,159] Trial 36 finished with value: 0.49328407905433935 and parameters: {'learning_rate': 0.10874412697328054, 'max_depth': 8, 'min_child_weight': 1.9528646230103912, 'subsample': 0.7208002037677809, 'colsample_bytree': 0.7322790339924452, 'gamma': 0.9888138832697575, 'reg_alpha': 9.849954646989671, 'reg_lambda': 0.0011716704457219774}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:47,244] Trial 37 finished with value: 0.52515396691508 and parameters: {'learning_rate': 0.15073097213548717, 'max_depth': 6, 'min_child_weight': 1.5125946019560614, 'subsample': 0.752814368467784, 'colsample_bytree': 0.7761469833565707, 'gamma': 1.1908562523465251, 'reg_alpha': 0.00012851579792865346, 'reg_lambda': 0.00021698939695255842}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:51,822] Trial 38 finished with value: 0.5147468806482229 and parameters: {'learning_rate': 0.1803820887619129, 'max_depth': 7, 'min_child_weight': 1.1156787688677188, 'subsample': 0.8075206361576107, 'colsample_bytree': 0.7525901023322803, 'gamma': 1.5594557549269679, 'reg_alpha': 0.00036360278888590916, 'reg_lambda': 0.00320199314712709}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:57:57,198] Trial 39 finished with value: 0.5316964870537975 and parameters: {'learning_rate': 0.12997165988730827, 'max_depth': 6, 'min_child_weight': 3.0283817920184024, 'subsample': 0.7343409779139651, 'colsample_bytree': 0.7340514746983096, 'gamma': 1.0701014859107845, 'reg_alpha': 0.009923689030571538, 'reg_lambda': 0.00046699298129044534}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:02,143] Trial 40 finished with value: 0.5108879810399245 and parameters: {'learning_rate': 0.13196745061942314, 'max_depth': 6, 'min_child_weight': 7.617508512022196, 'subsample': 0.7777511769136559, 'colsample_bytree': 0.7341450066596452, 'gamma': 1.3322589660233384, 'reg_alpha': 0.012458745147523148, 'reg_lambda': 0.001253254481622873}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:08,228] Trial 41 finished with value: 0.5074532379022239 and parameters: {'learning_rate': 0.15454818718575036, 'max_depth': 6, 'min_child_weight': 3.1332024281408675, 'subsample': 0.7317321782154047, 'colsample_bytree': 0.7164604525959932, 'gamma': 1.0697129626835302, 'reg_alpha': 0.0024898576731396554, 'reg_lambda': 0.0004890914745625038}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:14,286] Trial 42 finished with value: 0.49372713981157557 and parameters: {'learning_rate': 0.18525701365139943, 'max_depth': 7, 'min_child_weight': 1.3057275849375065, 'subsample': 0.7462955984950861, 'colsample_bytree': 0.7415832148723662, 'gamma': 0.9216475094901043, 'reg_alpha': 0.04713209193993019, 'reg_lambda': 0.00022761146249092117}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:21,654] Trial 43 finished with value: 0.5129107145782864 and parameters: {'learning_rate': 0.10722932277714205, 'max_depth': 6, 'min_child_weight': 1.7268702567557486, 'subsample': 0.7131312635275866, 'colsample_bytree': 0.9996533142159789, 'gamma': 1.0945891884075472, 'reg_alpha': 0.0005979853605085815, 'reg_lambda': 0.00010226780495456603}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:27,598] Trial 44 finished with value: 0.5217960100386838 and parameters: {'learning_rate': 0.12563645494166398, 'max_depth': 6, 'min_child_weight': 1.4268803616601982, 'subsample': 0.7986910453937869, 'colsample_bytree': 0.8021070178516594, 'gamma': 1.2449289109120023, 'reg_alpha': 0.008469169960137312, 'reg_lambda': 0.001817187651946103}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:33,632] Trial 45 finished with value: 0.5137919965101786 and parameters: {'learning_rate': 0.17497920202883013, 'max_depth': 8, 'min_child_weight': 2.2055433755767164, 'subsample': 0.7285403067137692, 'colsample_bytree': 0.7141964467850941, 'gamma': 1.0328405062674963, 'reg_alpha': 0.002571658302257172, 'reg_lambda': 0.0006357176841566614}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:39,743] Trial 46 finished with value: 0.502053065928457 and parameters: {'learning_rate': 0.15326438874760445, 'max_depth': 7, 'min_child_weight': 1.0136174089734318, 'subsample': 0.7725835721322916, 'colsample_bytree': 0.7494746412841569, 'gamma': 1.136676516713314, 'reg_alpha': 0.024413444409771962, 'reg_lambda': 0.004928005710537199}. Best is trial 26 with value: 0.5364888270652748.
[I 2026-04-15 15:58:45,867] Trial 47 finished with value: 0.5202425646403808 and parameters: {'learning_rate': 0.1782096444816778, 'max_depth': 6, 'min_child_weight': 1.5498035560252836, 'subsample': 0.7536115210999801, 'colsample_bytree': 0.7321423956775485, 'gamma': 0.931668978275423, 'reg_alpha': 0.0010679317936056361, 'reg_lambda': 0.0009284072086507938}. Best is trial 26 with value: 0.5364888270652748.

[I 2026-04-15 16:03:50,258] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 16:03:56,559] Trial 0 finished with value: 0.4987525026120506 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4987525026120506.
[I 2026-04-15 16:04:01,635] Trial 1 finished with value: 0.5276430540568608 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:04:13,462] Trial 2 finished with value: 0.5056682906775909 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:04:33,984] Trial 3 finished with value: 0.4824656713436046 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:05:11,649] Trial 4 finished with value: 0.49131192036995247 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:05:51,410] Trial 5 finished with value: 0.48977144885963864 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:06:11,413] Trial 6 finished with value: 0.5050430414757368 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:06:30,781] Trial 7 finished with value: 0.5049299937104428 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:07:13,527] Trial 8 finished with value: 0.514707138268868 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:07:33,606] Trial 9 finished with value: 0.47373214788302165 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:07:39,108] Trial 10 finished with value: 0.5023423022972235 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:07:47,699] Trial 11 finished with value: 0.4859397481339802 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.036826826336510646, 'depth': 5, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.4701090789076655, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.12665706747865135}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:07:56,832] Trial 12 finished with value: 0.4932357362550638 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.035566347462426914, 'depth': 5, 'l2_leaf_reg': 13.859731742356656, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.36456682418988}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:08:03,646] Trial 13 finished with value: 0.4966876781804618 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027947807428585644, 'depth': 5, 'l2_leaf_reg': 5.838384756610479, 'random_strength': 0.003957918169967434, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9002484961325342}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:08:49,857] Trial 14 finished with value: 0.4957204007804612 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0526276450184995, 'depth': 8, 'l2_leaf_reg': 12.89199389846631, 'random_strength': 0.418834921524961, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.606285613613393}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:08:54,125] Trial 15 finished with value: 0.5129162619261948 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12030166125543672, 'depth': 4, 'l2_leaf_reg': 2.984768074394884, 'random_strength': 0.5623181046141312, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 3.6415269030630038}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:09:06,599] Trial 16 finished with value: 0.4891334613371928 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029595070274508826, 'depth': 6, 'l2_leaf_reg': 7.372401598396334, 'random_strength': 0.19687158337179542, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8322248048125416}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:09:14,310] Trial 17 finished with value: 0.47900394677571434 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05620177025709193, 'depth': 5, 'l2_leaf_reg': 14.039323149871295, 'random_strength': 0.36766050559739283, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.1946053668168188}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:09:45,836] Trial 18 finished with value: 0.5196280831922087 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.026814014994424547, 'depth': 7, 'l2_leaf_reg': 10.124656610254672, 'random_strength': 0.5165900059679249, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.6566720920064946}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:10:06,908] Trial 19 finished with value: 0.48507187627813597 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02671016197089986, 'depth': 7, 'l2_leaf_reg': 9.794195580907935, 'random_strength': 0.615070904868543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.864570349188645}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:10:20,962] Trial 20 finished with value: 0.49270377805769144 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03485475867731072, 'depth': 6, 'l2_leaf_reg': 6.548528117273506, 'random_strength': 0.7791644775697428, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6951668146641582}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:11:05,168] Trial 21 finished with value: 0.4986552028517547 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.044367593163022315, 'depth': 8, 'l2_leaf_reg': 15.847575403471977, 'random_strength': 0.5172566173187358, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.8422953986825608}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:11:30,481] Trial 22 finished with value: 0.5019823490511293 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02503293647826436, 'depth': 7, 'l2_leaf_reg': 11.227584530628642, 'random_strength': 0.46375500543323817, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.2231853991910526}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:12:14,891] Trial 23 finished with value: 0.4759517196941594 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04234587708627211, 'depth': 8, 'l2_leaf_reg': 15.858965986411098, 'random_strength': 0.31209263999046083, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.6522255476033973}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:12:42,389] Trial 24 finished with value: 0.4983388790466671 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.022281398460486313, 'depth': 7, 'l2_leaf_reg': 8.597982189232559, 'random_strength': 0.1441390309251948, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.4610268597562444}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:13:31,636] Trial 25 finished with value: 0.49566903729437567 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03294276602686065, 'depth': 8, 'l2_leaf_reg': 5.374492442480787, 'random_strength': 0.5443508589351533, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.1991843163653235}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:13:44,904] Trial 26 finished with value: 0.4934100794526005 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05032308747718214, 'depth': 6, 'l2_leaf_reg': 12.075100349443963, 'random_strength': 0.4253505173932581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.348965176597016}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:14:09,803] Trial 27 finished with value: 0.5165578291348242 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02433152543349453, 'depth': 7, 'l2_leaf_reg': 16.595179434297577, 'random_strength': 0.7161881167310962, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.232749902429259}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:14:32,748] Trial 28 finished with value: 0.5218683284921166 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024923028921800813, 'depth': 7, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.7431832126676428, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6742814696752747}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:14:37,423] Trial 29 finished with value: 0.4807675171332868 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030255932472249024, 'depth': 4, 'l2_leaf_reg': 3.1955971204189613, 'random_strength': 0.9494230374911499, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6894583537527291}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:14:51,343] Trial 30 finished with value: 0.4938203463463484 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023230255701866535, 'depth': 6, 'l2_leaf_reg': 2.487724791072764, 'random_strength': 0.8832916107588447, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7813779527221643}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:15:12,685] Trial 31 finished with value: 0.492714925811418 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02494827192857719, 'depth': 7, 'l2_leaf_reg': 3.821547036680055, 'random_strength': 0.7213985616632561, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6524329936641386}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:15:33,239] Trial 32 finished with value: 0.5038521281038455 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030432256311154, 'depth': 7, 'l2_leaf_reg': 1.978392674166035, 'random_strength': 0.829215156577578, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.718001550342615}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:15:46,987] Trial 33 finished with value: 0.47273237583912964 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.024332722412758814, 'depth': 6, 'l2_leaf_reg': 7.933793345955863, 'random_strength': 0.6767737581258189, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6028878153594331}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:16:07,601] Trial 34 finished with value: 0.5001423081401029 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04005079150789061, 'depth': 7, 'l2_leaf_reg': 9.26693795761133, 'random_strength': 0.6073871114165474, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9979235787949021}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:16:27,756] Trial 35 finished with value: 0.5123440475661899 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.060582964609854614, 'depth': 7, 'l2_leaf_reg': 17.423767095370646, 'random_strength': 0.7163386383608032, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.914537096779279}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:16:47,568] Trial 36 finished with value: 0.5084392121927389 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14570163022887114, 'depth': 7, 'l2_leaf_reg': 2.172098425519041, 'random_strength': 0.7819515511972442, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.811855994042351}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:17:09,132] Trial 37 finished with value: 0.49724407141418686 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021588402918286613, 'depth': 7, 'l2_leaf_reg': 1.3052680006751538, 'random_strength': 0.5725202084809178, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.04451881606481045}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:17:23,809] Trial 38 finished with value: 0.502137672485211 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020012247703397153, 'depth': 6, 'l2_leaf_reg': 11.667607210268034, 'random_strength': 0.6876161372233813, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7384521706567103}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:17:35,319] Trial 39 finished with value: 0.49047133219245787 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.027301150563282743, 'depth': 6, 'l2_leaf_reg': 4.5562462855552095, 'random_strength': 0.15552667023858488, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.6486471090594035}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:17:42,673] Trial 40 finished with value: 0.48789233371564655 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03106553503224162, 'depth': 5, 'l2_leaf_reg': 3.193377287310293, 'random_strength': 0.3771524057207538, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7959041258107066}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:18:27,402] Trial 41 finished with value: 0.490515096961632 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06879318575454156, 'depth': 8, 'l2_leaf_reg': 15.433405452579004, 'random_strength': 0.06751999009628318, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.445310821028189}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:19:14,672] Trial 42 finished with value: 0.48940645848583403 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09644991447980489, 'depth': 8, 'l2_leaf_reg': 17.390851950534202, 'random_strength': 0.26476294531703853, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.9181342395060645}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:20:12,872] Trial 43 finished with value: 0.47230614669616533 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04016059553442157, 'depth': 8, 'l2_leaf_reg': 10.672752396491699, 'random_strength': 0.9000008357566543, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.2738126634095435}. Best is trial 1 with value: 0.5276430540568608.
[I 2026-04-15 16:21:00,172] Trial 44 finished with value: 0.4957793622732589 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04596482178744564, 'depth': 8, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.6215608692599073, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.5216584104755375}. Best is trial 1 with value: 0.5276430540568608.

                                        feature  importance
213           eye__fix_duration_AOI_FD_Pos1_sum   14.057469
207           eye__fix_duration_AOI_FD_Pos1_max    6.042850
56    eye__sac_length_AOI_aggregated_Pos_median    5.890182
0                           eye__sac_length_min    2.836884
283    eye__fix_duration_AOI_aggregated_Pos_sum    2.784856
491                        freq_bands__umap_021    2.729574
394          eye__det_euclidean_length_1_rho_25    2.632783
556                        freq_bands__umap_086    2.516984
488                        freq_bands__umap_018    2.452564
60        eye__sac_speed_AOI_aggregated_Pos_min    2.268127
465                               eye__imf0_max    2.155433
526                        freq_bands__umap_056    1.837555
209        eye__fix_duration_AOI_FD_Pos1_median    1.675786
398          eye__det_euclidean_length_1_rho_50    1.641418
284  eye__fix_duration_AOI_aggregated_Pos_count    1.634835
275  eye__fix_duration_AOI_aggregated_Pos_first    1.591758
270   eye__fix_duration_AOI_aggregated_None_std    1.577527
206           eye__fix_duration_AOI_FD_Pos1_min    1.408644
186           eye__fix_duration_AOI_FD_None_min    1.400806
390           eye__det_euclidean_length_1_rho_5    1.399447
55      eye__sac_length_AOI_aggregated_Pos_mean    1.385690
565                        freq_bands__umap_095    1.331031
505                        freq_bands__umap_035    1.285072
190           eye__fix_duration_AOI_FD_None_std    1.275583
545                        freq_bands__umap_075    1.265374
63     eye__sac_speed_AOI_aggregated_Pos_median    1.138237
295                        eye__fuzzy_m_2_r_200    1.122724
550                        freq_bands__umap_080    1.113630
503                        freq_bands__umap_033    1.105060
280    eye__fix_duration_AOI_aggregated_Pos_std    1.061314

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__ES__refitTEST
[freq_bands] rows missing after index match -> train: 1658, test: 160
[freq_bands] UMAP compression: train/test features 18361 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 16:25:40,093] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 16:25:44,966] Trial 0 finished with value: 0.5370499783372765 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:25:49,718] Trial 1 finished with value: 0.5155164874412033 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:25:55,175] Trial 2 finished with value: 0.5157058872446819 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:25:59,859] Trial 3 finished with value: 0.5161847054271448 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:04,499] Trial 4 finished with value: 0.507105754308091 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:09,560] Trial 5 finished with value: 0.5353657229109414 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:13,392] Trial 6 finished with value: 0.5022812651802003 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:18,954] Trial 7 finished with value: 0.5221281086796747 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:23,244] Trial 8 finished with value: 0.5313300508809236 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:29,967] Trial 9 finished with value: 0.5072023667394641 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:34,433] Trial 10 finished with value: 0.5067097519259598 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:39,084] Trial 11 finished with value: 0.5111995192171248 and parameters: {'learning_rate': 0.05335789734744574, 'max_depth': 3, 'min_child_weight': 5.088983724000999, 'subsample': 0.991678377353391, 'colsample_bytree': 0.701477667194265, 'gamma': 0.11719776682332067, 'reg_alpha': 0.000512080763851695, 'reg_lambda': 0.007113440172520569}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:44,689] Trial 12 finished with value: 0.49624678720759946 and parameters: {'learning_rate': 0.03817252027154219, 'max_depth': 4, 'min_child_weight': 3.2530417110714236, 'subsample': 0.9142027310606369, 'colsample_bytree': 0.7891814052225758, 'gamma': 0.3591665923508207, 'reg_alpha': 0.002764508045268526, 'reg_lambda': 4.172125626964391}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:49,943] Trial 13 finished with value: 0.5033464950127208 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 4, 'min_child_weight': 1.0894180501110897, 'subsample': 0.8497716981244118, 'colsample_bytree': 0.7826997023387571, 'gamma': 0.702635428731692, 'reg_alpha': 0.008558377329818284, 'reg_lambda': 0.00015764742688390395}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:26:56,253] Trial 14 finished with value: 0.49079487498463925 and parameters: {'learning_rate': 0.020257525017712674, 'max_depth': 4, 'min_child_weight': 6.673670271952152, 'subsample': 0.7004519003043, 'colsample_bytree': 0.8391610261172083, 'gamma': 0.29464130180941833, 'reg_alpha': 0.00067394934195344, 'reg_lambda': 0.011924988205055102}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:03,077] Trial 15 finished with value: 0.5222690064065321 and parameters: {'learning_rate': 0.04443784254669017, 'max_depth': 7, 'min_child_weight': 4.126885029445393, 'subsample': 0.9907425579887397, 'colsample_bytree': 0.7512336731684173, 'gamma': 1.3977616671674873, 'reg_alpha': 0.029597081039346603, 'reg_lambda': 0.5440445551043959}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:11,724] Trial 16 finished with value: 0.5147801100154563 and parameters: {'learning_rate': 0.02759913422564854, 'max_depth': 7, 'min_child_weight': 2.4133975370484113, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8697240947421665, 'gamma': 0.5125696661198353, 'reg_alpha': 0.00011961118581577438, 'reg_lambda': 0.009179232958184663}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:17,238] Trial 17 finished with value: 0.532915026676642 and parameters: {'learning_rate': 0.061694039035179504, 'max_depth': 4, 'min_child_weight': 6.897157387462384, 'subsample': 0.9453797750373166, 'colsample_bytree': 0.8131557307738727, 'gamma': 0.20565705809139748, 'reg_alpha': 0.001379251409310888, 'reg_lambda': 2.0330363018876305}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:22,262] Trial 18 finished with value: 0.5293181647458706 and parameters: {'learning_rate': 0.07555777069766632, 'max_depth': 8, 'min_child_weight': 9.437067520151778, 'subsample': 0.8290666990399569, 'colsample_bytree': 0.7096579728783863, 'gamma': 0.8425004342868845, 'reg_alpha': 6.917446092400471, 'reg_lambda': 0.1605066867738566}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:26,580] Trial 19 finished with value: 0.5349050302046894 and parameters: {'learning_rate': 0.12549292256352204, 'max_depth': 3, 'min_child_weight': 3.933656862825005, 'subsample': 0.8745592957044831, 'colsample_bytree': 0.7656347065644271, 'gamma': 0.010975442374407507, 'reg_alpha': 0.0156062880585437, 'reg_lambda': 0.02234261407031923}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:32,832] Trial 20 finished with value: 0.5248194191539013 and parameters: {'learning_rate': 0.04126056054589154, 'max_depth': 5, 'min_child_weight': 2.5608303358748854, 'subsample': 0.9329445693572309, 'colsample_bytree': 0.8181135886080299, 'gamma': 1.212620360204875, 'reg_alpha': 0.07810938403403807, 'reg_lambda': 0.00014979337155117755}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:37,311] Trial 21 finished with value: 0.5064000741231813 and parameters: {'learning_rate': 0.12673166290356555, 'max_depth': 3, 'min_child_weight': 4.046758993442458, 'subsample': 0.8831500796248434, 'colsample_bytree': 0.7638247762325668, 'gamma': 0.03332032225194852, 'reg_alpha': 0.012362606730895547, 'reg_lambda': 0.01920440408747861}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:41,513] Trial 22 finished with value: 0.49694235318034047 and parameters: {'learning_rate': 0.053364195435492014, 'max_depth': 3, 'min_child_weight': 5.084353525012288, 'subsample': 0.9683045861270267, 'colsample_bytree': 0.7245972585476756, 'gamma': 0.22239192484630682, 'reg_alpha': 0.002741098445445144, 'reg_lambda': 0.004458740287924128}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:45,712] Trial 23 finished with value: 0.5184253472402665 and parameters: {'learning_rate': 0.08668425925956756, 'max_depth': 4, 'min_child_weight': 3.504274546275131, 'subsample': 0.82014325872588, 'colsample_bytree': 0.7616127914535255, 'gamma': 0.4949476930936201, 'reg_alpha': 0.015286333973764218, 'reg_lambda': 0.03113312454798587}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:49,224] Trial 24 finished with value: 0.5205393455736179 and parameters: {'learning_rate': 0.1288355401008581, 'max_depth': 3, 'min_child_weight': 2.0239978284456073, 'subsample': 0.9104965062272944, 'colsample_bytree': 0.7739139805016806, 'gamma': 0.17999631134315733, 'reg_alpha': 0.0004490446734726716, 'reg_lambda': 0.0036633844915168142}. Best is trial 0 with value: 0.5370499783372765.
[I 2026-04-15 16:27:54,330] Trial 25 finished with value: 0.5444485006537056 and parameters: {'learning_rate': 0.062167835010909035, 'max_depth': 6, 'min_child_weight': 7.534694305695784, 'subsample': 0.7491623687077937, 'colsample_bytree': 0.8130126611584401, 'gamma': 0.3324859722583041, 'reg_alpha': 0.052260120065571784, 'reg_lambda': 0.00048644194671023554}. Best is trial 25 with value: 0.5444485006537056.
[I 2026-04-15 16:27:59,368] Trial 26 finished with value: 0.5441546786658383 and parameters: {'learning_rate': 0.06084614044863651, 'max_depth': 6, 'min_child_weight': 7.645977531385575, 'subsample': 0.7481882366843804, 'colsample_bytree': 0.8807007671624207, 'gamma': 0.6583000273542949, 'reg_alpha': 0.06445643618098176, 'reg_lambda': 0.00045703992875045617}. Best is trial 25 with value: 0.5444485006537056.
[I 2026-04-15 16:28:05,815] Trial 27 finished with value: 0.5487944676120391 and parameters: {'learning_rate': 0.06375454098950903, 'max_depth': 7, 'min_child_weight': 7.391240168366946, 'subsample': 0.7517066409092666, 'colsample_bytree': 0.8976400587805315, 'gamma': 0.7712051244943476, 'reg_alpha': 0.5071070403802035, 'reg_lambda': 0.00044039900388373194}. Best is trial 27 with value: 0.5487944676120391.
[I 2026-04-15 16:28:12,148] Trial 28 finished with value: 0.5519235568456698 and parameters: {'learning_rate': 0.0631253078543828, 'max_depth': 7, 'min_child_weight': 7.376894486189243, 'subsample': 0.758297878628801, 'colsample_bytree': 0.8933926790667814, 'gamma': 0.911241008056949, 'reg_alpha': 0.6732257644603001, 'reg_lambda': 0.0003435720875311541}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:17,920] Trial 29 finished with value: 0.5262519767213027 and parameters: {'learning_rate': 0.10060379419497202, 'max_depth': 7, 'min_child_weight': 5.626125476423405, 'subsample': 0.7532980951102703, 'colsample_bytree': 0.9087109390380042, 'gamma': 0.8999809741962987, 'reg_alpha': 0.4463460356250751, 'reg_lambda': 0.0003313559143238185}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:23,829] Trial 30 finished with value: 0.5189073673901844 and parameters: {'learning_rate': 0.06738702584890381, 'max_depth': 8, 'min_child_weight': 7.672967761917163, 'subsample': 0.8088485638813001, 'colsample_bytree': 0.9042027613808296, 'gamma': 1.2370019069315308, 'reg_alpha': 0.9625022094561827, 'reg_lambda': 0.0010731035188570465}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:30,035] Trial 31 finished with value: 0.5428920845001517 and parameters: {'learning_rate': 0.0668072710623678, 'max_depth': 7, 'min_child_weight': 7.465857231416313, 'subsample': 0.7390925235685201, 'colsample_bytree': 0.8700808852920733, 'gamma': 0.6844228246558097, 'reg_alpha': 0.11643775417655519, 'reg_lambda': 0.0004189904231595747}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:35,775] Trial 32 finished with value: 0.521742830809593 and parameters: {'learning_rate': 0.059417208100337904, 'max_depth': 6, 'min_child_weight': 9.9711224388853, 'subsample': 0.7583111037123275, 'colsample_bytree': 0.8977573978255657, 'gamma': 0.9605841853713354, 'reg_alpha': 0.051663736107891656, 'reg_lambda': 0.00040014006265812137}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:41,489] Trial 33 finished with value: 0.5330798157306044 and parameters: {'learning_rate': 0.07789889238504447, 'max_depth': 7, 'min_child_weight': 6.253161570648292, 'subsample': 0.712960468554356, 'colsample_bytree': 0.8554120053405533, 'gamma': 0.7192693288390282, 'reg_alpha': 5.398544760435502, 'reg_lambda': 0.00010510346217542648}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:46,820] Trial 34 finished with value: 0.5445273895510767 and parameters: {'learning_rate': 0.09806644122206337, 'max_depth': 6, 'min_child_weight': 8.172682163790427, 'subsample': 0.7676532918498928, 'colsample_bytree': 0.9224480328399748, 'gamma': 0.5654951757083865, 'reg_alpha': 0.4295027752561135, 'reg_lambda': 0.0007068116447926672}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:52,910] Trial 35 finished with value: 0.5175280603502935 and parameters: {'learning_rate': 0.09859134750745889, 'max_depth': 8, 'min_child_weight': 4.703287067797473, 'subsample': 0.7715131095668873, 'colsample_bytree': 0.9883275963116822, 'gamma': 0.48302204100681867, 'reg_alpha': 0.6533675757957937, 'reg_lambda': 0.002282503840813602}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:28:57,740] Trial 36 finished with value: 0.5018130360429383 and parameters: {'learning_rate': 0.1497493852133137, 'max_depth': 7, 'min_child_weight': 8.130482885911654, 'subsample': 0.7274243054998057, 'colsample_bytree': 0.9261705109007842, 'gamma': 0.7983208832720018, 'reg_alpha': 2.35364499082693, 'reg_lambda': 0.0006549036113061483}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:02,598] Trial 37 finished with value: 0.5126162088000301 and parameters: {'learning_rate': 0.08920552844878676, 'max_depth': 5, 'min_child_weight': 5.732208853242217, 'subsample': 0.8069014852926227, 'colsample_bytree': 0.9609064030194963, 'gamma': 1.420437637079452, 'reg_alpha': 0.2373302134384462, 'reg_lambda': 0.0002764289086239329}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:06,486] Trial 38 finished with value: 0.521605698129388 and parameters: {'learning_rate': 0.19944985887563255, 'max_depth': 6, 'min_child_weight': 6.716823112374985, 'subsample': 0.7682130689850268, 'colsample_bytree': 0.915150343545669, 'gamma': 0.989478788249698, 'reg_alpha': 3.328695365647468, 'reg_lambda': 0.0009025826684052095}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:12,194] Trial 39 finished with value: 0.5182131340236464 and parameters: {'learning_rate': 0.11126569946953857, 'max_depth': 7, 'min_child_weight': 5.3285972166066, 'subsample': 0.7985505758435528, 'colsample_bytree': 0.956463418136673, 'gamma': 0.6143833269504613, 'reg_alpha': 1.1723232406043913, 'reg_lambda': 0.0001941504416309326}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:17,456] Trial 40 finished with value: 0.5325455566793558 and parameters: {'learning_rate': 0.07391053360089844, 'max_depth': 6, 'min_child_weight': 8.665353210344543, 'subsample': 0.7302822673459124, 'colsample_bytree': 0.8088305467374133, 'gamma': 0.3860096673257681, 'reg_alpha': 0.3857301488765273, 'reg_lambda': 0.00162618847579804}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:22,824] Trial 41 finished with value: 0.5323606455039799 and parameters: {'learning_rate': 0.0580205713280086, 'max_depth': 6, 'min_child_weight': 7.672595183221457, 'subsample': 0.7485114786897757, 'colsample_bytree': 0.8905133947318503, 'gamma': 0.7955146339361261, 'reg_alpha': 0.05536799500110389, 'reg_lambda': 0.0006873063979625181}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:29,372] Trial 42 finished with value: 0.5341562997209668 and parameters: {'learning_rate': 0.04612347040113525, 'max_depth': 6, 'min_child_weight': 7.149956829991187, 'subsample': 0.7629030336247413, 'colsample_bytree': 0.874696070941902, 'gamma': 0.616755567130342, 'reg_alpha': 0.17719019807820707, 'reg_lambda': 0.0005394412915754052}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:34,709] Trial 43 finished with value: 0.5337249290378178 and parameters: {'learning_rate': 0.08237482283908742, 'max_depth': 5, 'min_child_weight': 6.106619388146731, 'subsample': 0.7802832468800018, 'colsample_bytree': 0.8575286357920681, 'gamma': 1.123592081091756, 'reg_alpha': 0.5626155404701432, 'reg_lambda': 0.00024390876366896114}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:41,231] Trial 44 finished with value: 0.5260354102401629 and parameters: {'learning_rate': 0.035311579768541934, 'max_depth': 6, 'min_child_weight': 8.368692169663772, 'subsample': 0.7083656281859476, 'colsample_bytree': 0.9281824342918125, 'gamma': 0.5592752338934113, 'reg_alpha': 0.2563189958441381, 'reg_lambda': 0.002561008392157794}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:47,422] Trial 45 finished with value: 0.5423456835949665 and parameters: {'learning_rate': 0.05027951781192925, 'max_depth': 7, 'min_child_weight': 9.74247156517685, 'subsample': 0.7396989703433557, 'colsample_bytree': 0.8889086494595554, 'gamma': 0.90179344923744, 'reg_alpha': 0.04964723873609578, 'reg_lambda': 0.001080508819829799}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:53,298] Trial 46 finished with value: 0.5410607267024163 and parameters: {'learning_rate': 0.0711935173416445, 'max_depth': 5, 'min_child_weight': 6.50959042934114, 'subsample': 0.7790087452588921, 'colsample_bytree': 0.9458666255773154, 'gamma': 0.4250671584309914, 'reg_alpha': 0.8425996188286622, 'reg_lambda': 0.00010842881876225622}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:29:59,185] Trial 47 finished with value: 0.5311802564636944 and parameters: {'learning_rate': 0.0567398279693129, 'max_depth': 6, 'min_child_weight': 4.627030044494538, 'subsample': 0.7502662421917462, 'colsample_bytree': 0.9165983268789274, 'gamma': 0.723176334849618, 'reg_alpha': 1.727479205713239, 'reg_lambda': 0.005038952464862571}. Best is trial 28 with value: 0.5519235568456698.
[I 2026-04-15 16:30:03,820] Trial 48 finished with value: 0.5435053276083004 and parameters: {'learning_rate': 0.09289688446546364, 'max_depth': 8, 'min_child_weight': 8.180483774449945, 'subsample': 0.7945965728610568, 'colsample_bytree': 0.8386321927625622, 'gamma': 0.2965759670945566, 'reg_alpha': 0.13521686578099054, 'reg_lambda': 0.0012711211421515254}. Best is trial 28 with value: 0.5519235568456698.

[I 2026-04-15 16:34:55,522] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.41053
              precision    recall  f1-score   support

           0       0.70      1.00      0.82       234
           1       0.00      0.00      0.00       102

    accuracy                           0.70       336
   macro avg       0.35      0.50      0.41       336
weighted avg       0.49      0.70      0.57       336

Confusion matrix:
 [[234   0]
 [102   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 16:35:01,497] Trial 0 finished with value: 0.5347109165699029 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5347109165699029.
[I 2026-04-15 16:35:17,693] Trial 1 finished with value: 0.5564403343643085 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.5564403343643085.
[I 2026-04-15 16:35:28,934] Trial 2 finished with value: 0.5592570358370403 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5592570358370403.
[I 2026-04-15 16:35:52,147] Trial 3 finished with value: 0.5903665351244263 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:36:12,589] Trial 4 finished with value: 0.5815168279802146 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:36:48,684] Trial 5 finished with value: 0.5467248329982723 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:37:10,057] Trial 6 finished with value: 0.5681771999153444 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:37:40,954] Trial 7 finished with value: 0.5635265293044858 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:38:45,934] Trial 8 finished with value: 0.5672910078629476 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:39:02,536] Trial 9 finished with value: 0.5801560991505923 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:39:10,088] Trial 10 finished with value: 0.5501893738238864 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1570794430403163, 'depth': 5, 'l2_leaf_reg': 5.721398227528868, 'random_strength': 0.9905905821371315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9500025439539328}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:39:21,719] Trial 11 finished with value: 0.5690029924767692 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 7, 'l2_leaf_reg': 2.444372124283309, 'random_strength': 0.016584038838684367, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:39:42,850] Trial 12 finished with value: 0.5720495253774498 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11814309083021705, 'depth': 8, 'l2_leaf_reg': 1.0239872964798657, 'random_strength': 0.5646362703740951, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7700735894451282}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:39:55,187] Trial 13 finished with value: 0.5894197495738034 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12938342032918101, 'depth': 7, 'l2_leaf_reg': 2.629249930915953, 'random_strength': 0.6827922413166337, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6147778927863947}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:40:06,334] Trial 14 finished with value: 0.5769526425700529 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11594493230437271, 'depth': 6, 'l2_leaf_reg': 3.086418536519601, 'random_strength': 0.6508705212142727, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.6020504841431196}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:40:32,281] Trial 15 finished with value: 0.5627980230628332 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05165446068032083, 'depth': 7, 'l2_leaf_reg': 8.41320832673556, 'random_strength': 0.8175414961981752, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6695957928236803}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:40:40,133] Trial 16 finished with value: 0.5589454249642158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11709680994139955, 'depth': 6, 'l2_leaf_reg': 18.878920630320945, 'random_strength': 0.4776807852053371, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6878223152997199}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:40:51,134] Trial 17 finished with value: 0.575813908183833 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032149666688976744, 'depth': 5, 'l2_leaf_reg': 3.4185965819472686, 'random_strength': 0.9915934669471993, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.617352449025832}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:41:23,091] Trial 18 finished with value: 0.5791653741443732 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05807569124447247, 'depth': 7, 'l2_leaf_reg': 10.665558307476653, 'random_strength': 0.7074586204636575, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8523249955395609}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:41:35,847] Trial 19 finished with value: 0.5889514552857167 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13902308048331793, 'depth': 7, 'l2_leaf_reg': 1.575934485222398, 'random_strength': 0.5642270992204163, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7126313376797004}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:42:15,880] Trial 20 finished with value: 0.5722847204439447 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09360235108041075, 'depth': 8, 'l2_leaf_reg': 6.471045142465734, 'random_strength': 0.3751213336050085, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.987613701207767}. Best is trial 3 with value: 0.5903665351244263.
[I 2026-04-15 16:42:28,060] Trial 21 finished with value: 0.6016433925343253 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14038407643252843, 'depth': 7, 'l2_leaf_reg': 1.5037154032926952, 'random_strength': 0.5669450501721055, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7105108269858103}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:42:39,194] Trial 22 finished with value: 0.568158784904736 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19311573782844788, 'depth': 7, 'l2_leaf_reg': 2.1378358958391086, 'random_strength': 0.5798570891295728, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6640748954107852}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:42:44,130] Trial 23 finished with value: 0.5845097278239866 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1396048177562797, 'depth': 5, 'l2_leaf_reg': 1.4192811604634659, 'random_strength': 0.8589073924586663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7362485157248078}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:42:53,377] Trial 24 finished with value: 0.5717497739633112 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09972230982301122, 'depth': 6, 'l2_leaf_reg': 2.6905011802310215, 'random_strength': 0.7157557221507137, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6374347193578318}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:43:06,850] Trial 25 finished with value: 0.5743139288730307 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06654091514380892, 'depth': 7, 'l2_leaf_reg': 1.282949055932139, 'random_strength': 0.43397093405391374, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8155398920037588}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:43:14,305] Trial 26 finished with value: 0.5602466239128255 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.10305270403973457, 'depth': 6, 'l2_leaf_reg': 3.761201747390766, 'random_strength': 0.6198279124112652, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:43:27,893] Trial 27 finished with value: 0.5539772444444383 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1400826915844479, 'depth': 7, 'l2_leaf_reg': 1.9690827980201993, 'random_strength': 0.905670207995821, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7133539387783083}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:44:35,159] Trial 28 finished with value: 0.5840831930785817 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03744259590667534, 'depth': 8, 'l2_leaf_reg': 3.037880631240932, 'random_strength': 0.766852344059723, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8768843114813252}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:44:58,177] Trial 29 finished with value: 0.55158642360464 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07751771692092001, 'depth': 7, 'l2_leaf_reg': 5.460892620437703, 'random_strength': 0.5181255096532799, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:45:05,238] Trial 30 finished with value: 0.56769034107962 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15255242537438815, 'depth': 6, 'l2_leaf_reg': 2.25528902729068, 'random_strength': 0.6935971856048144, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6578310180867784}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:45:17,574] Trial 31 finished with value: 0.5697814042254519 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13665303893898414, 'depth': 7, 'l2_leaf_reg': 1.726260590009391, 'random_strength': 0.5427735377907323, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7197387025421268}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:45:30,106] Trial 32 finished with value: 0.5796985787328592 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.197948594981505, 'depth': 7, 'l2_leaf_reg': 1.3622557387008092, 'random_strength': 0.6066806412012888, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7838006202860541}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:45:33,793] Trial 33 finished with value: 0.5810304773150561 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1218984909323225, 'depth': 4, 'l2_leaf_reg': 1.6268519960626835, 'random_strength': 0.286725263221369, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6901267606140264}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:46:00,411] Trial 34 finished with value: 0.5495166602149852 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0834718875164476, 'depth': 8, 'l2_leaf_reg': 1.2763478184128416, 'random_strength': 0.3813730649101845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7349266884786119}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:46:13,696] Trial 35 finished with value: 0.5556517709319917 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1676132219081862, 'depth': 7, 'l2_leaf_reg': 1.876976839951365, 'random_strength': 0.7738922635820752, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6303366268236803}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:47:44,169] Trial 36 finished with value: 0.5884149526003153 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06374253933170573, 'depth': 8, 'l2_leaf_reg': 13.056454416579511, 'random_strength': 0.6705749989685297, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8016865679333974}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:47:59,602] Trial 37 finished with value: 0.5738158482429533 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08932622850801265, 'depth': 7, 'l2_leaf_reg': 2.648273456136969, 'random_strength': 0.5227801473175325, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.04451881606481045}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:48:07,626] Trial 38 finished with value: 0.567982667909041 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1354029168800375, 'depth': 6, 'l2_leaf_reg': 1.1942178803494599, 'random_strength': 0.282140374228006, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.6990513951000529}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:48:36,829] Trial 39 finished with value: 0.5256336046661515 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1057539189166556, 'depth': 8, 'l2_leaf_reg': 4.401852594543895, 'random_strength': 0.43924980720806267, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 3.91602211054221}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:48:53,444] Trial 40 finished with value: 0.5798046632092277 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07147490942653682, 'depth': 7, 'l2_leaf_reg': 1.6527997279055722, 'random_strength': 0.6008673902462883, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6741709317447653}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:50:22,156] Trial 41 finished with value: 0.593717785417073 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06350627699780982, 'depth': 8, 'l2_leaf_reg': 13.449436366893822, 'random_strength': 0.6617088218697404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7956248656822552}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:52:06,482] Trial 42 finished with value: 0.5719084426304312 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.037610771546976035, 'depth': 8, 'l2_leaf_reg': 13.154523798215772, 'random_strength': 0.7203803231746607, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7147342492222047}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:54:03,421] Trial 43 finished with value: 0.5639295816138721 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05216709869051545, 'depth': 8, 'l2_leaf_reg': 9.182078544382932, 'random_strength': 0.6459622940147998, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8908753803317654}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:54:28,249] Trial 44 finished with value: 0.5918639834888203 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1269889402268533, 'depth': 7, 'l2_leaf_reg': 11.440522098136574, 'random_strength': 0.5490263856332466, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7662793020927694}. Best is trial 21 with value: 0.6016433925343253.
[I 2026-04-15 16:55:21,997] Trial 45 finished with value: 0.5701231790395271 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.08586953281801113, 'depth': 8, 'l2_leaf_reg': 11.332975241056872, 'random_strength': 0.7929157495500838, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7589944658705887}. Best is trial 21 with value: 0.6016433925343253.

                                       feature  importance
53      eye__sac_length_AOI_aggregated_Pos_min    0.077155
60       eye__sac_speed_AOI_aggregated_Pos_min    0.068627
184        eye__fix_duration_AOI_FD_Neg1_count    0.026270
532                       freq_bands__umap_062    0.023419
503                       freq_bands__umap_033    0.018785
540                       freq_bands__umap_070    0.018361
339              eye__sample_entropy_m=3_r=200    0.015423
374               eye__corr_dim_m_2_tau_2_r_50    0.015037
504                       freq_bands__umap_034    0.014483
183          eye__fix_duration_AOI_FD_Neg1_sum    0.014426
38      eye__sac_speed_AOI_aggregated_Neg_mean    0.014355
518                       freq_bands__umap_048    0.014331
465                              eye__imf0_max    0.013083
8                           eye__sac_speed_min    0.012730
333              eye__sample_entropy_m=2_r=100    0.012349
506                       freq_bands__umap_036    0.011994
464                              eye__imf0_min    0.011879
277   eye__fix_duration_AOI_aggregated_Pos_max    0.011681
510                       freq_bands__umap_040    0.011269
543                       freq_bands__umap_073    0.011253
413  eye__rec_metric_euclidean_length_2_rho_25    0.011205
556                       freq_bands__umap_086    0.011170
554                       freq_bands__umap_084    0.010822
558                       freq_bands__umap_088    0.010262
561                       freq_bands__umap_091    0.010242
356       eye__lyapunov_exponent_m_3_tau_2_T_1    0.010118
36       eye__sac_speed_AOI_aggregated_Neg_min    0.009400
41     eye__sac_length_AOI_aggregated_None_min    0.009075
552                       freq_bands__umap_082    0.009045
548                       freq_bands__umap_078    0.008982

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.58805
              precision    recall  f1-score   support

           0       0.74      0.91      0.82       234
           1       0.56      0.26      0.36       102

    accuracy                           0.71       336
   macro avg       0.65      0.59      0.59       336
weighted avg       0.69      0.71      0.68       336

Confusion matrix:
 [[213  21]
 [ 75  27]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=binary__feat=all_features+freq_bands__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
60        eye__sac_speed_AOI_aggregated_Pos_min    7.626471
62       eye__sac_speed_AOI_aggregated_Pos_mean    7.130273
53       eye__sac_length_AOI_aggregated_Pos_min    5.247777
183           eye__fix_duration_AOI_FD_Neg1_sum    4.214611
535                        freq_bands__umap_065    3.567811
494                        freq_bands__umap_024    3.001354
166                       eye__fix_duration_min    2.900363
542                        freq_bands__umap_072    2.897779
553                        freq_bands__umap_083    2.795035
547                        freq_bands__umap_077    2.497927
512                        freq_bands__umap_042    2.275372
495                        freq_bands__umap_025    2.234403
284  eye__fix_duration_AOI_aggregated_Pos_count    2.197149
178          eye__fix_duration_AOI_FD_Neg1_mean    1.947184
255  eye__fix_duration_AOI_aggregated_Neg_first    1.922467
360        eye__lyapunov_exponent_m_4_tau_1_T_2    1.878582
283    eye__fix_duration_AOI_aggregated_Pos_sum    1.826477
469                            eye__imf0_energy    1.759963
351        eye__lyapunov_exponent_m_2_tau_2_T_2    1.744557
309                eye__phase_entropy_m_4_tau_2    1.661989
554                        freq_bands__umap_084    1.640619
333               eye__sample_entropy_m=2_r=100    1.598701
540                        freq_bands__umap_070    1.545672
532                        freq_bands__umap_062    1.517233
522                        freq_bands__umap_052    1.500412
25                eye__sac_angle_between_median    1.486558
511                        freq_bands__umap_041    1.425273
173                       eye__fix_duration_sum    1.385159
525                        freq_bands__umap_055    1.363847
510                        freq_bands__umap_040    1.317950

================================================================================
Skipping existing experiment: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST
[freq_bands] rows missing after index match -> train: 1658, test: 160
[freq_bands] UMAP compression: train/test features 18361 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 16:59:46,443] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+freq_bands__target=match_mismatch_general__problem=multiclass__feat=all_features+freq_bands__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 16:59:53,211] Trial 0 finished with value: 0.6367235586152875 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 16:59:59,678] Trial 1 finished with value: 0.6002572785254179 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:07,441] Trial 2 finished with value: 0.6282824566758816 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:13,400] Trial 3 finished with value: 0.619962224767765 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:18,887] Trial 4 finished with value: 0.6312109038953894 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:27,012] Trial 5 finished with value: 0.623804640411003 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:31,496] Trial 6 finished with value: 0.6217763525719102 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:41,598] Trial 7 finished with value: 0.6310885739053158 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:00:47,627] Trial 8 finished with value: 0.6233330073661345 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:01:01,052] Trial 9 finished with value: 0.6285093819861649 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:01:08,436] Trial 10 finished with value: 0.634890745822563 and parameters: {'learning_rate': 0.049007017193771964, 'max_depth': 3, 'min_child_weight': 2.4108367235045933, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.8365039320348027, 'gamma': 0.40299971253046807, 'reg_alpha': 0.000158408987766231, 'reg_lambda': 8.557890375269768}. Best is trial 0 with value: 0.6367235586152875.
[I 2026-04-15 17:01:14,890] Trial 11 finished with value: 0.642746868468862 and parameters: {'learning_rate': 0.050044732845096966, 'max_depth': 3, 'min_child_weight': 2.350150709689129, 'subsample': 0.7005578980255978, 'colsample_bytree': 0.8260781920528338, 'gamma': 0.5892553864010996, 'reg_alpha': 0.00014565587242354827, 'reg_lambda': 6.69351503516026}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:01:22,093] Trial 12 finished with value: 0.6406885895531328 and parameters: {'learning_rate': 0.03659306060638565, 'max_depth': 3, 'min_child_weight': 3.235195406057617, 'subsample': 0.7008495643983494, 'colsample_bytree': 0.8129341056382718, 'gamma': 0.4440336518658533, 'reg_alpha': 0.000107858142176364, 'reg_lambda': 9.161272856858456}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:01:30,549] Trial 13 finished with value: 0.6420309039870583 and parameters: {'learning_rate': 0.029405164284549205, 'max_depth': 3, 'min_child_weight': 1.0715833151496479, 'subsample': 0.7024129801738459, 'colsample_bytree': 0.8383198446351168, 'gamma': 0.7331854888100613, 'reg_alpha': 0.0006082188957755501, 'reg_lambda': 9.728416829166896}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:01:41,927] Trial 14 finished with value: 0.6415144414544338 and parameters: {'learning_rate': 0.020338499095053454, 'max_depth': 4, 'min_child_weight': 1.1157937296124318, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8710442744149802, 'gamma': 0.7218831677473481, 'reg_alpha': 0.001640604932342923, 'reg_lambda': 0.9220750650051349}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:01:48,516] Trial 15 finished with value: 0.636522076148711 and parameters: {'learning_rate': 0.026850592331027975, 'max_depth': 3, 'min_child_weight': 1.0719435316018555, 'subsample': 0.7535351961542895, 'colsample_bytree': 0.8960864396945134, 'gamma': 1.3977616671674873, 'reg_alpha': 0.0009011849194051503, 'reg_lambda': 0.00016599250040776937}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:01:54,871] Trial 16 finished with value: 0.6309974004145915 and parameters: {'learning_rate': 0.061921537114114765, 'max_depth': 4, 'min_child_weight': 2.2670687329482937, 'subsample': 0.8252173406848475, 'colsample_bytree': 0.8374062021385964, 'gamma': 0.9544416575390137, 'reg_alpha': 0.0045923956759843405, 'reg_lambda': 2.0486168651094316}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:02:00,450] Trial 17 finished with value: 0.6396063864714195 and parameters: {'learning_rate': 0.07432476880169292, 'max_depth': 3, 'min_child_weight': 2.329324750075676, 'subsample': 0.7017933899773783, 'colsample_bytree': 0.7841680989726945, 'gamma': 1.2776895814091094, 'reg_alpha': 0.00028701399107782666, 'reg_lambda': 0.26958685659480713}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:02:09,285] Trial 18 finished with value: 0.6331630003105211 and parameters: {'learning_rate': 0.026779649734291994, 'max_depth': 4, 'min_child_weight': 1.3969904312383343, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.8074213105844478, 'gamma': 0.649297221699898, 'reg_alpha': 0.0036864843926879714, 'reg_lambda': 0.011397783591272139}. Best is trial 11 with value: 0.642746868468862.
[I 2026-04-15 17:02:16,988] Trial 19 finished with value: 0.6455321665398053 and parameters: {'learning_rate': 0.03851350957788583, 'max_depth': 3, 'min_child_weight': 5.305281304001412, 'subsample': 0.8198443929187631, 'colsample_bytree': 0.905359217093405, 'gamma': 1.4147991259598252, 'reg_alpha': 0.0003653616176385446, 'reg_lambda': 5.013929738871201}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:02:25,014] Trial 20 finished with value: 0.6337580997139816 and parameters: {'learning_rate': 0.04151293012381518, 'max_depth': 4, 'min_child_weight': 5.211158205743225, 'subsample': 0.8207531213984746, 'colsample_bytree': 0.9106383590440886, 'gamma': 1.489652013481267, 'reg_alpha': 0.009823117637889693, 'reg_lambda': 1.6582465086707034}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:02:33,709] Trial 21 finished with value: 0.6391001995486651 and parameters: {'learning_rate': 0.026386668182949408, 'max_depth': 3, 'min_child_weight': 6.7786467188313, 'subsample': 0.7492306392792902, 'colsample_bytree': 0.859013476113369, 'gamma': 0.855086491533449, 'reg_alpha': 0.0004982236502462503, 'reg_lambda': 5.244190796472579}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:02:40,274] Trial 22 finished with value: 0.6337358959917976 and parameters: {'learning_rate': 0.05392627672101755, 'max_depth': 3, 'min_child_weight': 4.118053949654519, 'subsample': 0.8971522198150251, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.2395419790616393, 'reg_alpha': 0.0014891615657974516, 'reg_lambda': 3.191917862894938}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:02:49,580] Trial 23 finished with value: 0.6280306251637647 and parameters: {'learning_rate': 0.03786440415908813, 'max_depth': 4, 'min_child_weight': 2.6019495712684133, 'subsample': 0.7281807657643797, 'colsample_bytree': 0.8354918751169618, 'gamma': 0.5586849888896056, 'reg_alpha': 0.00024813950342493225, 'reg_lambda': 9.74972357042643}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:02:57,564] Trial 24 finished with value: 0.6417697239558913 and parameters: {'learning_rate': 0.029657973835890236, 'max_depth': 3, 'min_child_weight': 1.7944764233656916, 'subsample': 0.8119333415120897, 'colsample_bytree': 0.9104627140498132, 'gamma': 1.5968046283026516, 'reg_alpha': 0.00012278110603532692, 'reg_lambda': 0.2501541526564842}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:03,933] Trial 25 finished with value: 0.6294790283209725 and parameters: {'learning_rate': 0.06819502718512985, 'max_depth': 4, 'min_child_weight': 4.771305592351959, 'subsample': 0.7607782960568759, 'colsample_bytree': 0.8186756099892157, 'gamma': 0.8751455585246037, 'reg_alpha': 0.001520870864178763, 'reg_lambda': 1.3586031603961515}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:10,243] Trial 26 finished with value: 0.6389315540709508 and parameters: {'learning_rate': 0.04412146858927282, 'max_depth': 3, 'min_child_weight': 1.3046077012569928, 'subsample': 0.9950275800498969, 'colsample_bytree': 0.980675824174857, 'gamma': 1.2052496287965841, 'reg_alpha': 0.00044894616900385093, 'reg_lambda': 3.8072072193589546}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:22,153] Trial 27 finished with value: 0.6289822791219439 and parameters: {'learning_rate': 0.05909602164567074, 'max_depth': 8, 'min_child_weight': 6.970867707567396, 'subsample': 0.8720856925655933, 'colsample_bytree': 0.8674287427459931, 'gamma': 0.2851370389041168, 'reg_alpha': 0.0009613127850010945, 'reg_lambda': 0.49484874317655525}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:34,397] Trial 28 finished with value: 0.6345220701372989 and parameters: {'learning_rate': 0.024006283214162163, 'max_depth': 5, 'min_child_weight': 2.739613318525203, 'subsample': 0.7306490972370543, 'colsample_bytree': 0.8877489016277046, 'gamma': 1.012412572675069, 'reg_alpha': 0.010026879763102126, 'reg_lambda': 4.51090388826255}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:42,649] Trial 29 finished with value: 0.6374073369179482 and parameters: {'learning_rate': 0.0439590903151853, 'max_depth': 4, 'min_child_weight': 3.800417820724975, 'subsample': 0.7017877676143269, 'colsample_bytree': 0.783643867307126, 'gamma': 0.44515122862123374, 'reg_alpha': 0.0002819744462784858, 'reg_lambda': 2.504335084592909}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:03:56,456] Trial 30 finished with value: 0.6271322512862906 and parameters: {'learning_rate': 0.030336819947649935, 'max_depth': 7, 'min_child_weight': 2.0936635908936494, 'subsample': 0.8028829447597539, 'colsample_bytree': 0.8523677565590156, 'gamma': 0.24439280327642754, 'reg_alpha': 5.544154050118195, 'reg_lambda': 0.018502244216073403}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:04,431] Trial 31 finished with value: 0.6438568671831972 and parameters: {'learning_rate': 0.03030906897474284, 'max_depth': 3, 'min_child_weight': 1.7802391875886718, 'subsample': 0.8247027190873617, 'colsample_bytree': 0.91178435822514, 'gamma': 1.653226578900761, 'reg_alpha': 0.00011110669625954632, 'reg_lambda': 0.20918990594666514}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:10,465] Trial 32 finished with value: 0.6324443412666395 and parameters: {'learning_rate': 0.037198237869916446, 'max_depth': 3, 'min_child_weight': 1.6129039172038349, 'subsample': 0.8444170063774857, 'colsample_bytree': 0.9146200364061116, 'gamma': 1.7077118546753536, 'reg_alpha': 0.0004726346447793099, 'reg_lambda': 1.231841967610746}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:16,800] Trial 33 finished with value: 0.6403558476101705 and parameters: {'learning_rate': 0.03263063931621245, 'max_depth': 3, 'min_child_weight': 1.8722075869868675, 'subsample': 0.7624957880869829, 'colsample_bytree': 0.9595222146487158, 'gamma': 1.417664400061721, 'reg_alpha': 0.00010834566958265212, 'reg_lambda': 0.22389331123166273}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:26,945] Trial 34 finished with value: 0.6287034388548067 and parameters: {'learning_rate': 0.023453449316540944, 'max_depth': 4, 'min_child_weight': 1.23341356420145, 'subsample': 0.9408008086573181, 'colsample_bytree': 0.9922589689862711, 'gamma': 1.5721880980401792, 'reg_alpha': 0.00022562979281488108, 'reg_lambda': 3.5516460967097347}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:34,092] Trial 35 finished with value: 0.632884071832635 and parameters: {'learning_rate': 0.03966083780303173, 'max_depth': 3, 'min_child_weight': 2.8512685303145346, 'subsample': 0.87076709419252, 'colsample_bytree': 0.9261677071059683, 'gamma': 1.7688241349815554, 'reg_alpha': 0.0007746503057369835, 'reg_lambda': 0.061221774507392364}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:39,177] Trial 36 finished with value: 0.6177658679539719 and parameters: {'learning_rate': 0.13469108396399915, 'max_depth': 4, 'min_child_weight': 1.5603699220140008, 'subsample': 0.8367618091916508, 'colsample_bytree': 0.8935775033503351, 'gamma': 1.9661881256144547, 'reg_alpha': 0.0023517224092716397, 'reg_lambda': 0.0044054856338788025}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:45,455] Trial 37 finished with value: 0.6400008733730826 and parameters: {'learning_rate': 0.08861230515914893, 'max_depth': 3, 'min_child_weight': 2.094482889498763, 'subsample': 0.896192308399012, 'colsample_bytree': 0.9533357199881549, 'gamma': 0.7518545284489423, 'reg_alpha': 0.00022050217210815872, 'reg_lambda': 0.7810624615566127}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:04:53,232] Trial 38 finished with value: 0.6307589089084937 and parameters: {'learning_rate': 0.04808308568725651, 'max_depth': 5, 'min_child_weight': 1.0016514431595034, 'subsample': 0.773012415314698, 'colsample_bytree': 0.8411870131530093, 'gamma': 1.8145774081828168, 'reg_alpha': 0.07228981101866326, 'reg_lambda': 0.40527191891571224}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:05:00,915] Trial 39 finished with value: 0.6424375745730467 and parameters: {'learning_rate': 0.03402138579491196, 'max_depth': 3, 'min_child_weight': 1.4576565056770308, 'subsample': 0.7386433861932167, 'colsample_bytree': 0.7617088257884488, 'gamma': 1.3280414384059687, 'reg_alpha': 0.0005123767328193797, 'reg_lambda': 5.986147139503594}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:05:08,256] Trial 40 finished with value: 0.6331985408949488 and parameters: {'learning_rate': 0.05426990828860108, 'max_depth': 4, 'min_child_weight': 1.4444333176659638, 'subsample': 0.8614070394579207, 'colsample_bytree': 0.768840270361212, 'gamma': 1.3322589660233384, 'reg_alpha': 0.010238682233660545, 'reg_lambda': 0.026457023183280144}. Best is trial 19 with value: 0.6455321665398053.
[I 2026-04-15 17:05:15,185] Trial 41 finished with value: 0.6486629349880654 and parameters: {'learning_rate': 0.03321401289221903, 'max_depth': 3, 'min_child_weight': 1.1573045648813463, 'subsample': 0.7197447833162448, 'colsample_bytree': 0.7044963184462653, 'gamma': 1.1419639227487697, 'reg_alpha': 0.0004054009760059494, 'reg_lambda': 6.6996487566946765}. Best is trial 41 with value: 0.6486629349880654.
[I 2026-04-15 17:05:21,365] Trial 42 finished with value: 0.6467527488908104 and parameters: {'learning_rate': 0.03389113562792851, 'max_depth': 3, 'min_child_weight': 1.854212795562353, 'subsample': 0.7195414679172313, 'colsample_bytree': 0.7179474095273537, 'gamma': 1.1330986139890966, 'reg_alpha': 0.00035757524375529904, 'reg_lambda': 4.874584197631888}. Best is trial 41 with value: 0.6486629349880654.
[I 2026-04-15 17:05:30,815] Trial 43 finished with value: 0.608368270978615 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 7, 'min_child_weight': 1.8746682860055326, 'subsample': 0.717081508473888, 'colsample_bytree': 0.7103127366839026, 'gamma': 0.008050105358543558, 'reg_alpha': 0.8005656164286727, 'reg_lambda': 0.1083454156926391}. Best is trial 41 with value: 0.6486629349880654.
[I 2026-04-15 17:05:38,127] Trial 44 finished with value: 0.6448812945531024 and parameters: {'learning_rate': 0.03453878943281012, 'max_depth': 3, 'min_child_weight': 3.4550397181468933, 'subsample': 0.773272709680305, 'colsample_bytree': 0.7128323074223478, 'gamma': 1.2017267450208469, 'reg_alpha': 0.00014982088044709395, 'reg_lambda': 2.1924421250914166}. Best is trial 41 with value: 0.6486629349880654.
[I 2026-04-15 17:05:47,255] Trial 45 finished with value: 0.6445538250732081 and parameters: {'learning_rate': 0.023323251478377483, 'max_depth': 3, 'min_child_weight': 3.4982977837122373, 'subsample': 0.7965891018750654, 'colsample_bytree': 0.7266093173475784, 'gamma': 1.131917081836781, 'reg_alpha': 0.0003483380315074311, 'reg_lambda': 2.115660425364487}. Best is trial 41 with value: 0.6486629349880654.
[I 2026-04-15 17:05:55,663] Trial 46 finished with value: 0.6487492176089079 and parameters: {'learning_rate': 0.02313086709617066, 'max_depth': 3, 'min_child_weight': 3.5311752273625316, 'subsample': 0.7768758898957817, 'colsample_bytree': 0.7269010010631523, 'gamma': 1.1370902480865925, 'reg_alpha': 0.0003868328712918109, 'reg_lambda': 1.977565450146555}. Best is trial 46 with value: 0.6487492176089079.
[I 2026-04-15 17:06:03,880] Trial 47 finished with value: 0.6347069473172172 and parameters: {'learning_rate': 0.033951605168623986, 'max_depth': 4, 'min_child_weight': 5.554979983354495, 'subsample': 0.7704935962916807, 'colsample_bytree': 0.7299848555559104, 'gamma': 1.1519212247047796, 'reg_alpha': 0.0011274023910075124, 'reg_lambda': 0.906464267371923}. Best is trial 46 with value: 0.6487492176089079.

[I 2026-04-15 17:13:25,522] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 17:13:33,374] Trial 0 finished with value: 0.6317636845364394 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6317636845364394.
[I 2026-04-15 17:13:44,028] Trial 1 finished with value: 0.6482380892967529 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:13:57,507] Trial 2 finished with value: 0.6461341570193632 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:14:22,098] Trial 3 finished with value: 0.6375093001835224 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:15:00,470] Trial 4 finished with value: 0.593967449504632 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:15:52,461] Trial 5 finished with value: 0.6324044659928686 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:16:22,002] Trial 6 finished with value: 0.6269246277989315 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:16:53,690] Trial 7 finished with value: 0.6402428896816549 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:18:16,511] Trial 8 finished with value: 0.6385227463862444 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:18:38,244] Trial 9 finished with value: 0.6326936510167496 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:18:49,995] Trial 10 finished with value: 0.635507832115296 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 1 with value: 0.6482380892967529.
[I 2026-04-15 17:18:59,555] Trial 11 finished with value: 0.6505412209978602 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03619150798130427, 'depth': 5, 'l2_leaf_reg': 7.1136091382850015, 'random_strength': 0.40988043411436537, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8451909941303626}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:10,914] Trial 12 finished with value: 0.6453202684414701 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031222380286557255, 'depth': 5, 'l2_leaf_reg': 5.293108038070359, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8961594169517826}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:20,910] Trial 13 finished with value: 0.6430254033692016 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033456846134581275, 'depth': 5, 'l2_leaf_reg': 12.789516619192685, 'random_strength': 0.0038022866978305314, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8530372066106942}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:31,400] Trial 14 finished with value: 0.6433681402390887 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02892904291231476, 'depth': 5, 'l2_leaf_reg': 6.786082022169199, 'random_strength': 0.48735830954286813, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8170272509034645}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:38,034] Trial 15 finished with value: 0.6498733321499943 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.037317381229506605, 'depth': 4, 'l2_leaf_reg': 12.268633130748121, 'random_strength': 0.18977020431574917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6176070773540004}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:45,682] Trial 16 finished with value: 0.642536038201411 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.048080843341726714, 'depth': 5, 'l2_leaf_reg': 3.6573360408574995, 'random_strength': 0.3831792574982257, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:51,031] Trial 17 finished with value: 0.6492785039159652 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.038995357115126056, 'depth': 4, 'l2_leaf_reg': 2.9463430992501776, 'random_strength': 0.5837833079273658, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6322352942029613}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:19:57,699] Trial 18 finished with value: 0.6298818469841749 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12320201760251838, 'depth': 5, 'l2_leaf_reg': 7.0563774482484085, 'random_strength': 0.22683551332574908, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8836775513987538}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:13,214] Trial 19 finished with value: 0.6376878265627803 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.062143287777609614, 'depth': 6, 'l2_leaf_reg': 10.244834031906784, 'random_strength': 0.3775448556454687, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6003729067725609}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:18,655] Trial 20 finished with value: 0.6454838915060599 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05415403772901829, 'depth': 4, 'l2_leaf_reg': 2.6816725490896114, 'random_strength': 0.06993453064575018, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8009062311783178}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:25,061] Trial 21 finished with value: 0.6463634845769772 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03791289274181211, 'depth': 4, 'l2_leaf_reg': 2.9853634847973907, 'random_strength': 0.5853083290616844, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6024392127835715}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:31,469] Trial 22 finished with value: 0.6502515802139257 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03871820598217327, 'depth': 4, 'l2_leaf_reg': 5.776609020093216, 'random_strength': 0.4662835797173768, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6706941884466439}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:43,877] Trial 23 finished with value: 0.6447897891434372 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02457583942738467, 'depth': 5, 'l2_leaf_reg': 5.800515696619005, 'random_strength': 0.44412180196566875, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6824133266069023}. Best is trial 11 with value: 0.6505412209978602.
[I 2026-04-15 17:20:49,534] Trial 24 finished with value: 0.6555844095019759 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0373824316179635, 'depth': 4, 'l2_leaf_reg': 8.90689198462332, 'random_strength': 0.2908247450346389, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7447283267816753}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:20:56,374] Trial 25 finished with value: 0.6419418848995022 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05819280885155775, 'depth': 5, 'l2_leaf_reg': 8.255719748139715, 'random_strength': 0.30204519444654404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7462124225786951}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:21:01,696] Trial 26 finished with value: 0.6478537881434449 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.028071445014028897, 'depth': 4, 'l2_leaf_reg': 6.49875818364319, 'random_strength': 0.5773309554424011, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:21:15,920] Trial 27 finished with value: 0.6518292762919257 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04033570067225661, 'depth': 6, 'l2_leaf_reg': 9.123739367123386, 'random_strength': 0.3868921715286747, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7232878927717789}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:21:29,876] Trial 28 finished with value: 0.6376404467856085 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0510446836214298, 'depth': 6, 'l2_leaf_reg': 9.20709617132373, 'random_strength': 0.3461440475598164, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7709483145984364}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:21:58,187] Trial 29 finished with value: 0.6372073466381322 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.034779517865570896, 'depth': 6, 'l2_leaf_reg': 13.953052199173902, 'random_strength': 0.12115872780470982, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.682610778645282}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:22:12,436] Trial 30 finished with value: 0.6342954794579156 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04550599601371992, 'depth': 6, 'l2_leaf_reg': 4.625741680305088, 'random_strength': 0.4235883656389261, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.721684490830003}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:22:17,566] Trial 31 finished with value: 0.6486636106311964 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.043292031246326024, 'depth': 4, 'l2_leaf_reg': 5.511729874543469, 'random_strength': 0.5399408717546628, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6585522632137342}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:22:27,947] Trial 32 finished with value: 0.6375240159679858 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023916454394007938, 'depth': 5, 'l2_leaf_reg': 8.165751656981243, 'random_strength': 0.2931694563805304, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8319847333792794}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:22:34,220] Trial 33 finished with value: 0.6476979998629155 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04076493332186003, 'depth': 4, 'l2_leaf_reg': 11.099048261900775, 'random_strength': 0.41089265009288795, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7244300139614648}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:23:03,066] Trial 34 finished with value: 0.6448079491642986 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0313817842702746, 'depth': 7, 'l2_leaf_reg': 8.098118689612168, 'random_strength': 0.5192616898222805, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7909554732116266}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:23:13,143] Trial 35 finished with value: 0.6467857029426421 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02581631443108418, 'depth': 5, 'l2_leaf_reg': 3.782424395523235, 'random_strength': 0.3419132414709689, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7269227693396461}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:23:19,271] Trial 36 finished with value: 0.6484638903078459 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03522495651535337, 'depth': 4, 'l2_leaf_reg': 5.774596024264, 'random_strength': 0.6705749989685297, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6721466427950614}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:23:24,815] Trial 37 finished with value: 0.6373226630946192 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06935325932977954, 'depth': 4, 'l2_leaf_reg': 8.980813490190384, 'random_strength': 0.2525921554710257, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7086413853294191}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:23:42,619] Trial 38 finished with value: 0.632495549326088 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04227985656161994, 'depth': 6, 'l2_leaf_reg': 16.142882842916435, 'random_strength': 0.1500537390352102, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.12221043743904225}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:04,400] Trial 39 finished with value: 0.6162174953364872 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19666138542450712, 'depth': 7, 'l2_leaf_reg': 6.9407768474139955, 'random_strength': 0.7280106193321223, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8705867532894543}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:12,864] Trial 40 finished with value: 0.6474556878693265 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05588551818597722, 'depth': 5, 'l2_leaf_reg': 1.7880266128945397, 'random_strength': 0.46795259115523763, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.4532051511681003}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:20,017] Trial 41 finished with value: 0.6481511758037206 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.036950428266353134, 'depth': 4, 'l2_leaf_reg': 12.104841831419503, 'random_strength': 0.1815010654937183, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6469755847682555}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:26,618] Trial 42 finished with value: 0.6527075958800959 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032175053387329504, 'depth': 4, 'l2_leaf_reg': 11.507755461485997, 'random_strength': 0.3202572457391523, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6185391262853808}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:32,885] Trial 43 finished with value: 0.6507869551675638 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027630739124783504, 'depth': 4, 'l2_leaf_reg': 10.369420241442562, 'random_strength': 0.3257133318107438, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6916065309560085}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:39,249] Trial 44 finished with value: 0.6431141114486958 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02841619660818607, 'depth': 4, 'l2_leaf_reg': 14.685997520962148, 'random_strength': 0.30879924924866564, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7774673890569194}. Best is trial 24 with value: 0.6555844095019759.
[I 2026-04-15 17:24:49,681] Trial 45 finished with value: 0.6549760174007615 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023351696294052877, 'depth': 5, 'l2_leaf_reg': 19.868586544676756, 'random_strength': 0.22185389326670724, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.694547261569267}. Best is trial 24 with value: 0.6555844095019759.

                                               feature  importance
56           eye__sac_length_AOI_aggregated_Pos_median   11.894400
58              eye__sac_length_AOI_aggregated_Pos_sum   11.135280
275         eye__fix_duration_AOI_aggregated_Pos_first    9.872559
53              eye__sac_length_AOI_aggregated_Pos_min    6.411800
63            eye__sac_speed_AOI_aggregated_Pos_median    5.032136
62              eye__sac_speed_AOI_aggregated_Pos_mean    3.246429
532                               freq_bands__umap_062    3.245042
490                               freq_bands__umap_020    3.215304
0                                  eye__sac_length_min    2.909855
166                              eye__fix_duration_min    2.782568
279        eye__fix_duration_AOI_aggregated_Pos_median    2.115464
55             eye__sac_length_AOI_aggregated_Pos_mean    1.927333
276           eye__fix_duration_AOI_aggregated_Pos_min    1.717040
176                  eye__fix_duration_AOI_FD_Neg1_min    1.672077
60               eye__sac_speed_AOI_aggregated_Pos_min    1.318577
175                eye__fix_duration_AOI_FD_Neg1_first    1.293773
178                 eye__fix_duration_AOI_FD_Neg1_mean    1.286108
494                               freq_bands__umap_024    1.193117
527                               freq_bands__umap_057    1.080652
278          eye__fix_duration_AOI_aggregated_Pos_mean    1.016378
502                               freq_bands__umap_032    0.944062
32           eye__sac_length_AOI_aggregated_Neg_median    0.822093
54              eye__sac_length_AOI_aggregated_Pos_max    0.783262
31             eye__sac_length_AOI_aggregated_Neg_mean    0.746099
258          eye__fix_duration_AOI_aggregated_Neg_mean    0.733427
91   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.687367
30              eye__sac_length_AOI_aggregated_Neg_max    0.681504
307                       eye__phase_entropy_m_3_tau_2    0.680176
474                               freq_bands__umap_004    0.675751
277           eye__fix_duration_AOI_aggregated_Pos_max    0.670634

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,False,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,binary,True,0.403197,0.443463,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch,multiclass,False,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch,multiclass,True,NaN,0.544316,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,freq_bands,match_mismatch_general,binary,False,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,freq_bands,match_mismatch_general,binary,True,0.410526,0.588046,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,freq_bands,match_mismatch_general,multiclass,False,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,freq_bands,match_mismatch_general,multiclass,True,NaN,0.708828,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,freq_bands,match_mismatch,binary,False,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,freq_bands,match_mismatch,binary,True,0.403197,0.443463,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,freq_bands,match_mismatch,multiclass,False,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,freq_bands,match_mismatch,multiclass,True,NaN,0.544316,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,freq_bands,match_mismatch_general,binary,False,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,freq_bands,match_mismatch_general,binary,True,0.410526,0.588046,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,freq_bands,match_mismatch_general,multiclass,False,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,freq_bands,match_mismatch_general,multiclass,True,NaN,0.708828,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [9]:
text_PID = _load_ftar_parquet(FTAR_FILES["PID"])
print("PID shape:", text_PID.shape)
summary_PID = run_ftar_set("PID", text_PID)
summary_PID

PID shape: (4442, 611)
[PID] ftar feature count after cleanup: 610

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__ES__refitTEST

[I 2026-04-15 17:28:11,384] A new study created in memory with name: binary_xgb

[PID] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__ES__refitTEST__no_neutral
X_train: (3016, 1080), X_test: (336, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 17:28:20,528] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 17:28:31,650] Trial 1 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 17:28:40,763] Trial 2 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 17:28:50,880] Trial 3 finished with value: 0.4125026256033442 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:01,088] Trial 4 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:11,231] Trial 5 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:19,592] Trial 6 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:30,320] Trial 7 finished with value: 0.4113053099905785 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:39,925] Trial 8 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:50,482] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:29:55,926] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08757688804274504, 'max_depth': 3, 'min_child_weight': 4.926890130404868, 'subsample': 0.8636522230468259, 'colsample_bytree': 0.8646722768462439, 'gamma': 1.411720649791067, 'reg_alpha': 9.265570153067632, 'reg_lambda': 8.122224546810095}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:05,405] Trial 11 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.031702962830749956, 'max_depth': 4, 'min_child_weight': 5.66261309436717, 'subsample': 0.8387066013238305, 'colsample_bytree': 0.9894826834868345, 'gamma': 0.810300425187616, 'reg_alpha': 0.48049684627556033, 'reg_lambda': 0.3857798743296257}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:16,602] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07561377665306217, 'max_depth': 7, 'min_child_weight': 6.619493520104159, 'subsample': 0.8358799703358235, 'colsample_bytree': 0.999748196231103, 'gamma': 1.1556906359171761, 'reg_alpha': 0.0031841301424337977, 'reg_lambda': 0.4058319699835376}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:26,161] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11198932069742602, 'max_depth': 4, 'min_child_weight': 2.2197380363876666, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.9257125038420886, 'gamma': 0.6007222005882018, 'reg_alpha': 0.37406121101032624, 'reg_lambda': 0.12270544609248879}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:38,812] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0230021639842471, 'max_depth': 7, 'min_child_weight': 4.169486032784437, 'subsample': 0.8172919248612467, 'colsample_bytree': 0.8204703108224801, 'gamma': 1.3248780393112758, 'reg_alpha': 0.0001096145847994451, 'reg_lambda': 0.01039162947426362}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:49,899] Trial 15 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04045248226040531, 'max_depth': 5, 'min_child_weight': 2.495974171712466, 'subsample': 0.8851753710073659, 'colsample_bytree': 0.9028451614515682, 'gamma': 0.9301080514901593, 'reg_alpha': 0.06975638223757245, 'reg_lambda': 0.00016599250040776937}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:30:57,679] Trial 16 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05967297880371984, 'max_depth': 3, 'min_child_weight': 8.081953262965312, 'subsample': 0.9341462060236994, 'colsample_bytree': 0.9663814197013302, 'gamma': 0.7072128692989745, 'reg_alpha': 1.4801498655697052, 'reg_lambda': 2.198889492670607}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:07,882] Trial 17 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.10877316258091171, 'max_depth': 8, 'min_child_weight': 4.508421510723996, 'subsample': 0.80795370323802, 'colsample_bytree': 0.833222568445511, 'gamma': 1.4687357450667158, 'reg_alpha': 0.010392145389935256, 'reg_lambda': 0.018867535841271068}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:18,508] Trial 18 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03284327359018468, 'max_depth': 6, 'min_child_weight': 1.115133317760315, 'subsample': 0.7446808508456166, 'colsample_bytree': 0.901349971445933, 'gamma': 0.49919193349368973, 'reg_alpha': 8.325050739402274, 'reg_lambda': 0.17877276965962163}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:28,812] Trial 19 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.026692761721150773, 'max_depth': 5, 'min_child_weight': 6.619678426618048, 'subsample': 0.851659849912455, 'colsample_bytree': 0.9565565824792837, 'gamma': 0.41227582838302573, 'reg_alpha': 0.26511437704441265, 'reg_lambda': 1.75144139558839}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:36,552] Trial 20 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.13289429952646395, 'max_depth': 4, 'min_child_weight': 2.7402286143342476, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.9723630402473995, 'gamma': 0.9733325383225249, 'reg_alpha': 0.9347558977541993, 'reg_lambda': 9.711686255289472}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:45,396] Trial 21 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04441068965868737, 'max_depth': 4, 'min_child_weight': 3.3102625390132645, 'subsample': 0.7084221523591787, 'colsample_bytree': 0.7815133255444485, 'gamma': 0.28632917154383, 'reg_alpha': 0.00068495441547159, 'reg_lambda': 2.031762138320672}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:31:54,479] Trial 22 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04782497432272511, 'max_depth': 5, 'min_child_weight': 4.043721964376532, 'subsample': 0.7029731632232117, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.2117137769510506, 'reg_alpha': 0.0007113361509717478, 'reg_lambda': 0.6213195624337876}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:02,607] Trial 23 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03814074882390723, 'max_depth': 3, 'min_child_weight': 3.6181903713397485, 'subsample': 0.7391373322670772, 'colsample_bytree': 0.9131873993161814, 'gamma': 0.8201615043884495, 'reg_alpha': 0.0010771298871084217, 'reg_lambda': 3.92205860272957}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:11,719] Trial 24 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.06382460004332387, 'max_depth': 4, 'min_child_weight': 5.140559487718575, 'subsample': 0.8743095839141729, 'colsample_bytree': 0.8531318713570645, 'gamma': 0.22147624959206302, 'reg_alpha': 0.00015628544653785645, 'reg_lambda': 0.8638510340482634}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:21,767] Trial 25 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.062167835010909035, 'max_depth': 6, 'min_child_weight': 7.534694305695784, 'subsample': 0.7663617656308367, 'colsample_bytree': 0.7906135583339632, 'gamma': 0.3577339332216787, 'reg_alpha': 0.04934038660451684, 'reg_lambda': 0.2418647524426841}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:33,087] Trial 26 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.026440153758186192, 'max_depth': 5, 'min_child_weight': 2.783741654696655, 'subsample': 0.8125104614342165, 'colsample_bytree': 0.8807007671624207, 'gamma': 1.5807096045905777, 'reg_alpha': 0.15010308882241408, 'reg_lambda': 1.2039003177423915}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:48,071] Trial 27 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052297917058085855, 'max_depth': 7, 'min_child_weight': 2.020296186187318, 'subsample': 0.7225209800790457, 'colsample_bytree': 0.9755378965373238, 'gamma': 0.8042676284576658, 'reg_alpha': 0.6578255485982006, 'reg_lambda': 3.9115781824113967}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:32:56,447] Trial 28 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08342488697243093, 'max_depth': 4, 'min_child_weight': 9.76007519353103, 'subsample': 0.7547134572751286, 'colsample_bytree': 0.820035056633983, 'gamma': 1.09978648075625, 'reg_alpha': 4.038538105287643, 'reg_lambda': 0.10175269177434051}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:33:03,277] Trial 29 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.19839989166716254, 'max_depth': 3, 'min_child_weight': 4.068879829557542, 'subsample': 0.795809487174427, 'colsample_bytree': 0.7163707750869759, 'gamma': 0.03026729632376557, 'reg_alpha': 0.016026477755680738, 'reg_lambda': 0.033041629411520106}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:33:12,634] Trial 30 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.13997006153395214, 'max_depth': 8, 'min_child_weight': 7.1530372372635505, 'subsample': 0.8290452443221675, 'colsample_bytree': 0.7657646523033833, 'gamma': 1.2994280162825436, 'reg_alpha': 0.008203022993152499, 'reg_lambda': 3.8719776140021014}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:33:24,292] Trial 31 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.15930064792467968, 'max_depth': 8, 'min_child_weight': 1.954409027329548, 'subsample': 0.9292624489633464, 'colsample_bytree': 0.7210390418027017, 'gamma': 0.0034910221906602167, 'reg_alpha': 3.6506306459483784, 'reg_lambda': 0.0003420353102101175}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:33:38,690] Trial 32 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03806926410494467, 'max_depth': 7, 'min_child_weight': 1.0512469590477043, 'subsample': 0.8981956877717316, 'colsample_bytree': 0.7503457333474564, 'gamma': 0.1430619298153524, 'reg_alpha': 3.1748193644524427, 'reg_lambda': 0.0012138824603477514}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:33:47,954] Trial 33 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07051137408226468, 'max_depth': 5, 'min_child_weight': 1.2781938385197917, 'subsample': 0.9682379069839581, 'colsample_bytree': 0.7683947955452304, 'gamma': 1.724455332780253, 'reg_alpha': 0.20056745895858524, 'reg_lambda': 0.0037004816664007534}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:34:02,101] Trial 34 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09806644122206337, 'max_depth': 8, 'min_child_weight': 1.7354857018120946, 'subsample': 0.9408008086573181, 'colsample_bytree': 0.9415008586884099, 'gamma': 0.13778108730449845, 'reg_alpha': 1.3867942020445465, 'reg_lambda': 0.05033028856409485}. Best is trial 3 with value: 0.4125026256033442.
[I 2026-04-15 17:34:11,412] Trial 35 finished with value: 0.45416140312110553 and parameters: {'learning_rate': 0.19717327022141168, 'max_depth': 6, 'min_child_weight': 1.6230766089807804, 'subsample': 0.9573078669103848, 'colsample_bytree': 0.8054870151769092, 'gamma': 0.4405255927464341, 'reg_alpha': 0.002200417821075227, 'reg_lambda': 0.000614834011118542}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:34:21,145] Trial 36 finished with value: 0.42298263312864826 and parameters: {'learning_rate': 0.1917647519262428, 'max_depth': 6, 'min_child_weight': 1.4592940184695014, 'subsample': 0.7689808501865404, 'colsample_bytree': 0.8144748666678426, 'gamma': 0.4877421109092696, 'reg_alpha': 0.0022833224640357776, 'reg_lambda': 0.0044054856338788025}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:34:29,802] Trial 37 finished with value: 0.42218493732390094 and parameters: {'learning_rate': 0.19845719303441478, 'max_depth': 6, 'min_child_weight': 1.2910844053678079, 'subsample': 0.9955425422793488, 'colsample_bytree': 0.8365696555750584, 'gamma': 0.6444209633410323, 'reg_alpha': 0.002114845756554045, 'reg_lambda': 0.00045629257672837617}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:34:38,343] Trial 38 finished with value: 0.4298945126618082 and parameters: {'learning_rate': 0.1999329625752988, 'max_depth': 6, 'min_child_weight': 1.5123561554425708, 'subsample': 0.985824363725574, 'colsample_bytree': 0.8077902930003867, 'gamma': 0.5002676852830112, 'reg_alpha': 0.0021145428690364965, 'reg_lambda': 0.00052915713331645}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:34:45,705] Trial 39 finished with value: 0.42103406083383005 and parameters: {'learning_rate': 0.19596826555722682, 'max_depth': 6, 'min_child_weight': 1.4693497053343645, 'subsample': 0.9981470135234803, 'colsample_bytree': 0.8123805831807002, 'gamma': 0.48326664127020647, 'reg_alpha': 0.0018446362233390196, 'reg_lambda': 0.0005989327691964987}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:34:55,355] Trial 40 finished with value: 0.4177170906364717 and parameters: {'learning_rate': 0.16556263925866552, 'max_depth': 7, 'min_child_weight': 1.2453066851329448, 'subsample': 0.978159276858197, 'colsample_bytree': 0.8027740566425997, 'gamma': 0.5997759226083884, 'reg_alpha': 0.0002853471245533513, 'reg_lambda': 0.00010876474298140306}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:04,205] Trial 41 finished with value: 0.42236772486772484 and parameters: {'learning_rate': 0.1978005704744436, 'max_depth': 6, 'min_child_weight': 1.5206530535069596, 'subsample': 0.9999139162929123, 'colsample_bytree': 0.8070077084124045, 'gamma': 0.43821829752394204, 'reg_alpha': 0.0022755378716622465, 'reg_lambda': 0.0004980787039255169}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:14,409] Trial 42 finished with value: 0.41699673017118855 and parameters: {'learning_rate': 0.14713643198605608, 'max_depth': 6, 'min_child_weight': 1.4737965011467073, 'subsample': 0.9600938624993322, 'colsample_bytree': 0.8364377619649241, 'gamma': 0.47481123817489695, 'reg_alpha': 0.0029058705419329842, 'reg_lambda': 0.0032639209193003}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:23,492] Trial 43 finished with value: 0.4134614863757208 and parameters: {'learning_rate': 0.18116396018870703, 'max_depth': 6, 'min_child_weight': 1.6069344760298176, 'subsample': 0.9834726281987849, 'colsample_bytree': 0.8446649785300898, 'gamma': 0.6667226677866994, 'reg_alpha': 0.0016373594627634102, 'reg_lambda': 0.000360486445043648}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:33,257] Trial 44 finished with value: 0.4277939184200339 and parameters: {'learning_rate': 0.1809608717331446, 'max_depth': 6, 'min_child_weight': 1.1637972603407079, 'subsample': 0.955165637910112, 'colsample_bytree': 0.8016315930130333, 'gamma': 0.3306566168460704, 'reg_alpha': 0.004081861566207099, 'reg_lambda': 0.0006012216095516829}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:44,376] Trial 45 finished with value: 0.40687003194964977 and parameters: {'learning_rate': 0.12559159241270618, 'max_depth': 7, 'min_child_weight': 1.1715363431948447, 'subsample': 0.9579705168658518, 'colsample_bytree': 0.7798784995972755, 'gamma': 0.3103236746338486, 'reg_alpha': 0.005291655202011778, 'reg_lambda': 0.0010057279058074348}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:35:53,635] Trial 46 finished with value: 0.4242566804639772 and parameters: {'learning_rate': 0.15720168687417221, 'max_depth': 6, 'min_child_weight': 1.448249390381044, 'subsample': 0.9196405246374275, 'colsample_bytree': 0.7958605192788923, 'gamma': 0.3950527059262678, 'reg_alpha': 0.00038641256558267454, 'reg_lambda': 0.002941375403322532}. Best is trial 35 with value: 0.45416140312110553.
[I 2026-04-15 17:36:03,904] Trial 47 finished with value: 0.4167992380636019 and parameters: {'learning_rate': 0.1502295944534729, 'max_depth': 6, 'min_child_weight': 1.0243944932531424, 'subsample': 0.9165576256250342, 'colsample_bytree': 0.7966008189267676, 'gamma': 0.25175392461018076, 'reg_alpha': 0.0003564417784715798, 'reg_lambda': 0.0020907477762443305}. Best is trial 35 with value: 0.45416140312110553.

[I 2026-04-15 17:43:36,716] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 17:43:44,135] Trial 0 finished with value: 0.4266267849729293 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4266267849729293.
[I 2026-04-15 17:43:54,994] Trial 1 finished with value: 0.42218037626661353 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.4266267849729293.
[I 2026-04-15 17:44:09,789] Trial 2 finished with value: 0.4190901490304213 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 0 with value: 0.4266267849729293.
[I 2026-04-15 17:44:37,667] Trial 3 finished with value: 0.41010932744841855 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 0 with value: 0.4266267849729293.
[I 2026-04-15 17:45:17,015] Trial 4 finished with value: 0.4610988215053034 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:46:07,394] Trial 5 finished with value: 0.4312602104060378 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:46:34,740] Trial 6 finished with value: 0.40652319089925204 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:47:02,476] Trial 7 finished with value: 0.41177105553403126 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:47:57,000] Trial 8 finished with value: 0.40641290943742125 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:48:20,876] Trial 9 finished with value: 0.4263110788639934 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:48:28,540] Trial 10 finished with value: 0.437981831673418 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:48:36,284] Trial 11 finished with value: 0.4399608919880217 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17040099770125652, 'depth': 5, 'l2_leaf_reg': 1.7651302031192428, 'random_strength': 0.004072030335889598, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9606029800630493}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:48:44,500] Trial 12 finished with value: 0.44783484307471605 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865009089283614, 'depth': 5, 'l2_leaf_reg': 1.9426894697963841, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.994759737357233}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:48:52,905] Trial 13 finished with value: 0.4444953680371102 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12778080184558183, 'depth': 5, 'l2_leaf_reg': 2.869741965176845, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8530372066106942}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:49:00,408] Trial 14 finished with value: 0.44782750111572983 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11980834084297441, 'depth': 5, 'l2_leaf_reg': 1.0042999777217867, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8424234616468694}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:49:39,738] Trial 15 finished with value: 0.44831510767863336 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1983058867595879, 'depth': 8, 'l2_leaf_reg': 2.566528746990451, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7749871487988538}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:50:20,670] Trial 16 finished with value: 0.4405358082866962 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12769952952541253, 'depth': 8, 'l2_leaf_reg': 3.7344029023245366, 'random_strength': 0.3788754515751092, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7723396018781626}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:51:02,827] Trial 17 finished with value: 0.46001282148187206 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14275466267871886, 'depth': 8, 'l2_leaf_reg': 2.6698711793578207, 'random_strength': 0.24803672218181055, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.719101211089318}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:51:25,106] Trial 18 finished with value: 0.4490987135270823 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10148368561184581, 'depth': 7, 'l2_leaf_reg': 1.3551419426021614, 'random_strength': 0.22683551332574908, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6945796693410654}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:52:11,642] Trial 19 finished with value: 0.4474302370157245 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.051518582818118774, 'depth': 8, 'l2_leaf_reg': 2.859017003229577, 'random_strength': 0.49983480587919177, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6006970978747742}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:52:33,332] Trial 20 finished with value: 0.44040603532008726 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14724478112125605, 'depth': 7, 'l2_leaf_reg': 5.569849053748985, 'random_strength': 0.09259182272544825, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.83987292510528}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:52:55,965] Trial 21 finished with value: 0.4410398959616148 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09972223006837518, 'depth': 7, 'l2_leaf_reg': 1.2513070177822687, 'random_strength': 0.22910028593887521, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7083422316334627}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:53:37,751] Trial 22 finished with value: 0.4332522419497593 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10697380648057649, 'depth': 8, 'l2_leaf_reg': 1.4362207725534237, 'random_strength': 0.26741864381569924, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7217265015665681}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:54:00,234] Trial 23 finished with value: 0.429672755043379 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1483345316552758, 'depth': 7, 'l2_leaf_reg': 2.5170312857628154, 'random_strength': 0.40783151151962893, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6520483656141892}. Best is trial 4 with value: 0.4610988215053034.
[I 2026-04-15 17:54:38,921] Trial 24 finished with value: 0.4658594653189624 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15392826311546115, 'depth': 8, 'l2_leaf_reg': 1.1819573069685256, 'random_strength': 0.10352699518084174, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7397123483634142}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:55:18,419] Trial 25 finished with value: 0.46519921105820683 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15037777743519554, 'depth': 8, 'l2_leaf_reg': 2.2971198576950442, 'random_strength': 0.08913893004668884, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7479843910794272}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:55:57,104] Trial 26 finished with value: 0.4612530116288812 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1609160344339687, 'depth': 8, 'l2_leaf_reg': 1.4257410330798606, 'random_strength': 0.10564277630860319, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.2578643405925001}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:56:10,997] Trial 27 finished with value: 0.4366811098551894 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05949748415259578, 'depth': 6, 'l2_leaf_reg': 1.2103822845014938, 'random_strength': 0.11079638511105384, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.30094396714113597}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:56:59,953] Trial 28 finished with value: 0.4237090602740662 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.03322651802115874, 'depth': 8, 'l2_leaf_reg': 2.2325918112358436, 'random_strength': 0.5903174516353481, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.22090791623893452}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:57:13,221] Trial 29 finished with value: 0.45277738877868645 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1552082549780848, 'depth': 6, 'l2_leaf_reg': 3.415599526672519, 'random_strength': 0.1548930266122582, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.3784693681010873}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:57:57,692] Trial 30 finished with value: 0.4276581509955479 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06370170941379975, 'depth': 8, 'l2_leaf_reg': 2.1079127696299667, 'random_strength': 0.07935939493432596, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.4993264036145195}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:58:36,258] Trial 31 finished with value: 0.44492778494335533 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.17092573150396184, 'depth': 8, 'l2_leaf_reg': 1.5852469258692508, 'random_strength': 0.0690487501490466, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.370956938236069}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:59:17,623] Trial 32 finished with value: 0.44035058281134765 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11848339113636773, 'depth': 8, 'l2_leaf_reg': 1.5329333510444516, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.164704118387009}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:59:23,423] Trial 33 finished with value: 0.44422446253118264 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.166924005748709, 'depth': 4, 'l2_leaf_reg': 1.1986222397225308, 'random_strength': 0.11702928597775096, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8124372597464988}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 17:59:45,579] Trial 34 finished with value: 0.4362441890711408 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13632762209391217, 'depth': 7, 'l2_leaf_reg': 1.6232507650445824, 'random_strength': 0.06174959231423252, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7472482470928609}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:00:24,889] Trial 35 finished with value: 0.46185706713886343 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19698308006711232, 'depth': 8, 'l2_leaf_reg': 2.164548832810617, 'random_strength': 0.1980851747322217, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8013450384462601}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:01:14,170] Trial 36 finished with value: 0.4247934008507589 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0369055818079162, 'depth': 8, 'l2_leaf_reg': 2.0422908551167214, 'random_strength': 0.20213290553502822, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8944651875449812}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:01:40,227] Trial 37 finished with value: 0.41605954057210826 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09148378272595663, 'depth': 7, 'l2_leaf_reg': 3.4018989991369857, 'random_strength': 0.14764264497705526, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.7272701169983553}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:02:20,847] Trial 38 finished with value: 0.4499063811953203 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11282418240420612, 'depth': 8, 'l2_leaf_reg': 5.976017987259388, 'random_strength': 0.3153466848119302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8091209931804272}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:02:42,879] Trial 39 finished with value: 0.4613604178147157 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19725921948830644, 'depth': 7, 'l2_leaf_reg': 1.1546455257845178, 'random_strength': 0.4449309386022971, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7286242350522154}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:03:05,952] Trial 40 finished with value: 0.45202441982905306 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1923860584682235, 'depth': 7, 'l2_leaf_reg': 1.1247914482903878, 'random_strength': 0.5626214379767001, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8944332647208674}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:03:48,891] Trial 41 finished with value: 0.45016939275483214 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.15951896204309618, 'depth': 8, 'l2_leaf_reg': 1.3427332011533557, 'random_strength': 0.7421559909719516, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7846903294020604}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:04:28,992] Trial 42 finished with value: 0.44575249728261235 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1824233629675439, 'depth': 8, 'l2_leaf_reg': 2.2943966551580495, 'random_strength': 0.44087216290420056, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.81915270756881}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:04:51,680] Trial 43 finished with value: 0.4407188439539111 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13788706248114596, 'depth': 7, 'l2_leaf_reg': 1.0676007809774801, 'random_strength': 0.12828519737994842, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.009663903294347631}. Best is trial 24 with value: 0.4658594653189624.
[I 2026-04-15 18:05:32,115] Trial 44 finished with value: 0.4247045550088423 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.16177403819017017, 'depth': 8, 'l2_leaf_reg': 1.7964097050475787, 'random_strength': 0.3403567261721979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 0.7508362597585981}. Best is trial 24 with value: 0.4658594653189624.

                                                feature  importance
856                PID__PID_F4_second_deriv_energy_mean    0.096620
796                 PID__PID_F5_first_deriv_energy_mean    0.071615
809                PID__PID_Fp1_first_deriv_energy_mean    0.068990
209                eye__fix_duration_AOI_FD_Pos1_median    0.058834
62               eye__sac_speed_AOI_aggregated_Pos_mean    0.054956
26                           eye__sac_angle_between_std    0.050780
547                       PID__PID_Cz_second_deriv_mean    0.050418
155                                eye__reg_length_skew    0.049904
59             eye__sac_length_AOI_aggregated_Pos_count    0.047311
830                PID__PID_POz_first_deriv_energy_mean    0.044344
543                      PID__PID_CP3_second_deriv_mean    0.040773
859                PID__PID_F7_second_deriv_energy_mean    0.038704
164                                  eye__reg_mask_mean    0.036888
376                       eye__corr_dim_m_2_tau_2_r_400    0.034777
579                       PID__PID_P8_second_deriv_mean    0.034250
867               PID__PID_FCz_second_deriv_energy_mean    0.032932
190                   eye__fix_duration_AOI_FD_None_std    0.029925
788                PID__PID_CP4_first_deriv_energy_mean    0.029179
832                 PID__PID_T7_first_deriv_energy_mean    0.025121
837               PID__PID_AF4_second_deriv_energy_mean    0.023820
741                              PID__PID_FC3_data_mean    0.019631
165                             eye__fix_duration_first    0.014904
84    eye__sac_speed_from_Neg_to_Target_from_Neg_to_...    0.013611
44           eye__sac_length_AOI_aggregated_None_median    0.008390
18                           eye__sac_angle_to_x_median    0.006806
113   eye__sac_length_from_Target_to_Neg_from_Target...    0.005754
475                        PID__PID_C2_first_deriv_mean    0.005505
54               eye__sac_length_AOI_aggregated_Pos_max    0.005255
1047                      PID__PID_FC4_data_energy_mean    0.000000
31              eye__sac_length_AOI_aggregated_Neg_mean    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.40415
              precision    recall  f1-score   support

           0       0.66      0.93      0.78       227
           1       0.12      0.02      0.03       109

    accuracy                           0.64       336
   macro avg       0.39      0.48      0.40       336
weighted avg       0.49      0.64      0.53       336

Confusion matrix:
 [[212  15]
 [107   2]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+PID__target=match_mismatch__problem=binary__feat=all_features+PID__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
490                 PID__PID_F4_first_deriv_mean    3.324916
494                 PID__PID_F8_first_deriv_mean    2.797865
464                                eye__imf0_min    2.709566
279  eye__fix_duration_AOI_aggregated_Pos_median    2.661753
54        eye__sac_length_AOI_aggregated_Pos_max    2.485543
275   eye__fix_duration_AOI_aggregated_Pos_first    2.154953
270    eye__fix_duration_AOI_aggregated_None_std    2.144253
837        PID__PID_AF4_second_deriv_energy_mean    1.922667
172                       eye__fix_duration_skew    1.686450
164                           eye__reg_mask_mean    1.682515
588                PID__PID_T7_second_deriv_mean    1.325362
475                 PID__PID_C2_first_deriv_mean    1.322344
570                PID__PID_O2_second_deriv_mean    1.307920
208           eye__fix_duration_AOI_FD_Pos1_mean    1.278296
822          PID__PID_P7_first_deriv_energy_mean    1.203691
1                            eye__sac_length_max    1.178163
471                PID__PID_AF4_first_deriv_mean    1.178120
154                     eye__reg_length_kurtosis    1.141480
190            eye__fix_duration_AOI_FD_None_std    1.119122
817          PID__PID_P2_first_deriv_energy_mean    1.091487
19                       eye__sac_angle_to_x_std    1.090889
155                         eye__reg_length_skew    1.079930
503                PID__PID_FT8_first_deriv_mean    1.076096
589                PID__PID_T8_second_deriv_mean    1.071784
163                          eye__reg_speed_skew    1.025677
17                      eye__sac_angle_to_x_mean    1.020731
20                  eye__sac_angle_to_x_kurtosis    1.012545
509                 PID__PID_O2_first_deriv_mean    0.929953
421   eye__rec_metric_euclidean_length_2_rho_250    0.927038
2                           eye__sac_length_mean    0.908870

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__ES__refitTEST

[I 2026-04-15 18:08:55,949] A new study created in memory with name: multiclass_xgb

[PID] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch__problem=multiclass__feat=all_features+PID__ES__refitTEST__no_neutral
X_train: (3016, 1080), X_test: (336, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 18:09:12,531] Trial 0 finished with value: 0.5277899689909593 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5277899689909593.
[I 2026-04-15 18:09:30,570] Trial 1 finished with value: 0.5013216936582024 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5277899689909593.
[I 2026-04-15 18:09:47,065] Trial 2 finished with value: 0.5278186780178891 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.5278186780178891.
[I 2026-04-15 18:10:02,456] Trial 3 finished with value: 0.49221053340583076 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.5278186780178891.
[I 2026-04-15 18:10:15,571] Trial 4 finished with value: 0.5103323543451309 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.5278186780178891.
[I 2026-04-15 18:10:31,535] Trial 5 finished with value: 0.5282544165105808 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 5 with value: 0.5282544165105808.
[I 2026-04-15 18:10:41,883] Trial 6 finished with value: 0.5396537329566351 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.5396537329566351.
[I 2026-04-15 18:11:02,812] Trial 7 finished with value: 0.5447915702365014 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:11:15,673] Trial 8 finished with value: 0.5189461422560409 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:11:39,242] Trial 9 finished with value: 0.5343114158802466 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:11:56,078] Trial 10 finished with value: 0.5179522621433293 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 6.0796977549919955, 'subsample': 0.8386834652924317, 'colsample_bytree': 0.9984958032960148, 'gamma': 1.343695477455153, 'reg_alpha': 9.157669588453277, 'reg_lambda': 7.2116802788205145}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:12:05,511] Trial 11 finished with value: 0.5339261356476196 and parameters: {'learning_rate': 0.18034503935054141, 'max_depth': 4, 'min_child_weight': 9.82128943308808, 'subsample': 0.701047216919461, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.304587838920539, 'reg_alpha': 0.004655286732860811, 'reg_lambda': 0.3857798743296257}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:12:24,262] Trial 12 finished with value: 0.5256392850479303 and parameters: {'learning_rate': 0.03463737347266536, 'max_depth': 7, 'min_child_weight': 6.852955380636017, 'subsample': 0.7452386219369388, 'colsample_bytree': 0.8604727246366422, 'gamma': 1.9111186935907507, 'reg_alpha': 0.021276477216451234, 'reg_lambda': 0.4093532596834662}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:12:38,689] Trial 13 finished with value: 0.5227526022672715 and parameters: {'learning_rate': 0.06643109118849368, 'max_depth': 4, 'min_child_weight': 2.4110330308098, 'subsample': 0.830708901865747, 'colsample_bytree': 0.9964572475248108, 'gamma': 1.5212779937515775, 'reg_alpha': 0.00039428482627718264, 'reg_lambda': 0.1260891501452632}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:13:03,177] Trial 14 finished with value: 0.5071874661435402 and parameters: {'learning_rate': 0.033477764234539284, 'max_depth': 7, 'min_child_weight': 4.645026244324928, 'subsample': 0.7533165692412906, 'colsample_bytree': 0.9007915070826333, 'gamma': 0.7380569829534882, 'reg_alpha': 0.003951021561695887, 'reg_lambda': 0.010503332619820302}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:13:14,749] Trial 15 finished with value: 0.5241468945908427 and parameters: {'learning_rate': 0.12303889473804241, 'max_depth': 5, 'min_child_weight': 7.66964634930763, 'subsample': 0.8057550099598993, 'colsample_bytree': 0.8126476121538668, 'gamma': 1.113374315932778, 'reg_alpha': 0.42935330799030347, 'reg_lambda': 0.00016599250040776937}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:13:26,770] Trial 16 finished with value: 0.5172231415092736 and parameters: {'learning_rate': 0.0489025517956362, 'max_depth': 3, 'min_child_weight': 5.196603542656908, 'subsample': 0.8849956891079398, 'colsample_bytree': 0.8978409621396142, 'gamma': 0.4547004750001311, 'reg_alpha': 0.06508175231237738, 'reg_lambda': 2.198889492670607}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:13:41,983] Trial 17 finished with value: 0.516952746314679 and parameters: {'learning_rate': 0.07432476880169292, 'max_depth': 8, 'min_child_weight': 8.321736922127522, 'subsample': 0.7409151006662548, 'colsample_bytree': 0.964244348061153, 'gamma': 1.548335427709699, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 0.018867535841271068}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:14:03,038] Trial 18 finished with value: 0.5184205622119002 and parameters: {'learning_rate': 0.027064564138418134, 'max_depth': 6, 'min_child_weight': 2.547676403345648, 'subsample': 0.812735608930163, 'colsample_bytree': 0.8948460237310025, 'gamma': 1.9972642562490481, 'reg_alpha': 0.014348853877452968, 'reg_lambda': 0.18046364557236313}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:14:16,184] Trial 19 finished with value: 0.5292823266378157 and parameters: {'learning_rate': 0.13178891002152585, 'max_depth': 5, 'min_child_weight': 4.067081955187476, 'subsample': 0.7224640238818689, 'colsample_bytree': 0.8236891489977652, 'gamma': 0.8818204857810077, 'reg_alpha': 0.8496486371140398, 'reg_lambda': 1.75144139558839}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:14:31,593] Trial 20 finished with value: 0.5129323178218418 and parameters: {'learning_rate': 0.04099883162263712, 'max_depth': 4, 'min_child_weight': 9.74521314185495, 'subsample': 0.7626063278876597, 'colsample_bytree': 0.9686582636618576, 'gamma': 1.3456841171498741, 'reg_alpha': 0.0012981874931845077, 'reg_lambda': 9.713302321935345}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:14:58,101] Trial 21 finished with value: 0.50931762585066 and parameters: {'learning_rate': 0.020387011599342725, 'max_depth': 6, 'min_child_weight': 1.0357560456399333, 'subsample': 0.7937317565401297, 'colsample_bytree': 0.7065196760827404, 'gamma': 0.5624636315547151, 'reg_alpha': 0.09079993768936402, 'reg_lambda': 0.07715500200506628}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:15:23,514] Trial 22 finished with value: 0.5191415384694283 and parameters: {'learning_rate': 0.024281630594772542, 'max_depth': 7, 'min_child_weight': 2.718644864205449, 'subsample': 0.8178804513917594, 'colsample_bytree': 0.7802255931447097, 'gamma': 0.5652157819330013, 'reg_alpha': 0.06361005849198872, 'reg_lambda': 0.03593944713828602}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:15:46,649] Trial 23 finished with value: 0.5238367096366984 and parameters: {'learning_rate': 0.028271415313006358, 'max_depth': 6, 'min_child_weight': 3.245518771246124, 'subsample': 0.7801783513373922, 'colsample_bytree': 0.8438433489192577, 'gamma': 1.0018514605561721, 'reg_alpha': 0.17141196179730497, 'reg_lambda': 0.9966096062899275}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:16:03,223] Trial 24 finished with value: 0.5065190756744756 and parameters: {'learning_rate': 0.05606476341890665, 'max_depth': 5, 'min_child_weight': 6.516643867155444, 'subsample': 0.8690694010662794, 'colsample_bytree': 0.7023486227822291, 'gamma': 0.6616141910089972, 'reg_alpha': 0.2529567107849939, 'reg_lambda': 0.1953404348341715}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:16:25,408] Trial 25 finished with value: 0.5046499331258361 and parameters: {'learning_rate': 0.02010075403923017, 'max_depth': 6, 'min_child_weight': 7.940315364932537, 'subsample': 0.7335162123291286, 'colsample_bytree': 0.8762727739011799, 'gamma': 1.7149128650839291, 'reg_alpha': 0.040951600605909806, 'reg_lambda': 0.005212897550620363}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:16:47,771] Trial 26 finished with value: 0.5416872302753099 and parameters: {'learning_rate': 0.03625711387355986, 'max_depth': 7, 'min_child_weight': 5.082670430524074, 'subsample': 0.9109056663796594, 'colsample_bytree': 0.8364165815258958, 'gamma': 0.35792151444634945, 'reg_alpha': 0.011457469214315797, 'reg_lambda': 0.02402300154209137}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:17:08,778] Trial 27 finished with value: 0.5142958198038257 and parameters: {'learning_rate': 0.09762244493082722, 'max_depth': 8, 'min_child_weight': 5.426693736053088, 'subsample': 0.9284969703518289, 'colsample_bytree': 0.8366608501995183, 'gamma': 0.286588693616594, 'reg_alpha': 0.012504352216688271, 'reg_lambda': 0.016976714323223695}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:17:31,711] Trial 28 finished with value: 0.5110018254419479 and parameters: {'learning_rate': 0.03963059942512648, 'max_depth': 7, 'min_child_weight': 7.207589079351472, 'subsample': 0.9979782879666353, 'colsample_bytree': 0.9171384694126249, 'gamma': 0.3452612003622443, 'reg_alpha': 0.0016195524991496932, 'reg_lambda': 0.22829179548347994}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:17:43,072] Trial 29 finished with value: 0.4966388042613609 and parameters: {'learning_rate': 0.19889260167166048, 'max_depth': 7, 'min_child_weight': 3.828772320310965, 'subsample': 0.9105417875441117, 'colsample_bytree': 0.807122564931832, 'gamma': 0.9050043919534608, 'reg_alpha': 0.010384606972024995, 'reg_lambda': 1.206707978610952}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:17:54,436] Trial 30 finished with value: 0.5092421865570452 and parameters: {'learning_rate': 0.04294662151243258, 'max_depth': 5, 'min_child_weight': 5.008032175592528, 'subsample': 0.9295998351849856, 'colsample_bytree': 0.8770644292327855, 'gamma': 1.2370019069315308, 'reg_alpha': 5.544154050118195, 'reg_lambda': 3.8719776140021014}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:18:15,259] Trial 31 finished with value: 0.5184752387380429 and parameters: {'learning_rate': 0.029153853903757063, 'max_depth': 6, 'min_child_weight': 3.2704821341526094, 'subsample': 0.8491250431264402, 'colsample_bytree': 0.7657745178679489, 'gamma': 0.19620649878932883, 'reg_alpha': 0.0389938081856514, 'reg_lambda': 0.05477695257749335}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:18:37,193] Trial 32 finished with value: 0.5251134636212069 and parameters: {'learning_rate': 0.02334598279920557, 'max_depth': 6, 'min_child_weight': 8.463692574070096, 'subsample': 0.709884192484843, 'colsample_bytree': 0.7331998078833697, 'gamma': 0.40406428312352816, 'reg_alpha': 0.10623983865646257, 'reg_lambda': 0.10201708259396597}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:19:00,970] Trial 33 finished with value: 0.5208028196193516 and parameters: {'learning_rate': 0.05978043114838697, 'max_depth': 7, 'min_child_weight': 2.8610416204535225, 'subsample': 0.7622441927863998, 'colsample_bytree': 0.7836582812826473, 'gamma': 0.5223382572658477, 'reg_alpha': 0.006315637140669494, 'reg_lambda': 0.025876649143395814}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:19:35,547] Trial 34 finished with value: 0.514408058508652 and parameters: {'learning_rate': 0.03343618011346409, 'max_depth': 8, 'min_child_weight': 2.2739786229370127, 'subsample': 0.7998893528316241, 'colsample_bytree': 0.965618180341717, 'gamma': 0.01686400166629809, 'reg_alpha': 0.6811545704521212, 'reg_lambda': 0.004233849116165555}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:19:52,034] Trial 35 finished with value: 0.536851965506377 and parameters: {'learning_rate': 0.03925666456925301, 'max_depth': 4, 'min_child_weight': 1.9588885148790827, 'subsample': 0.7276564954307426, 'colsample_bytree': 0.9189955170416764, 'gamma': 0.6905488011340445, 'reg_alpha': 0.002175945547949986, 'reg_lambda': 0.6101750669703605}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:20:09,982] Trial 36 finished with value: 0.5180323723713183 and parameters: {'learning_rate': 0.03753902518009916, 'max_depth': 4, 'min_child_weight': 1.9528646230103912, 'subsample': 0.7239569783626745, 'colsample_bytree': 0.9229989158560111, 'gamma': 0.7403989609194466, 'reg_alpha': 0.002277853505196298, 'reg_lambda': 0.47952896424132374}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:20:23,899] Trial 37 finished with value: 0.5136761942020938 and parameters: {'learning_rate': 0.04704343746662034, 'max_depth': 3, 'min_child_weight': 1.5519354452079943, 'subsample': 0.726296909779895, 'colsample_bytree': 0.9502437873220061, 'gamma': 0.15234353281096732, 'reg_alpha': 0.0006288250826263256, 'reg_lambda': 0.908771609799562}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:20:40,804] Trial 38 finished with value: 0.5097937752058003 and parameters: {'learning_rate': 0.14841598023640515, 'max_depth': 5, 'min_child_weight': 1.1846862623315515, 'subsample': 0.7607675734805526, 'colsample_bytree': 0.9139785588858028, 'gamma': 0.25904970051139764, 'reg_alpha': 0.000684416497861566, 'reg_lambda': 0.2571083235887143}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:20:53,589] Trial 39 finished with value: 0.5086487694944256 and parameters: {'learning_rate': 0.09083938789401047, 'max_depth': 4, 'min_child_weight': 2.0318391090469277, 'subsample': 0.9729965854716095, 'colsample_bytree': 0.985135973676384, 'gamma': 1.000847243127733, 'reg_alpha': 0.0002601186695052955, 'reg_lambda': 0.5758613804141668}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:21:11,640] Trial 40 finished with value: 0.5140381853684225 and parameters: {'learning_rate': 0.03062147333750453, 'max_depth': 5, 'min_child_weight': 5.819014648406732, 'subsample': 0.8737734477694243, 'colsample_bytree': 0.8817294719869149, 'gamma': 1.7511341972310097, 'reg_alpha': 0.007626408511346302, 'reg_lambda': 3.5022282697354865}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:21:33,385] Trial 41 finished with value: 0.5318018286846842 and parameters: {'learning_rate': 0.047276697140870697, 'max_depth': 6, 'min_child_weight': 4.216082525247502, 'subsample': 0.7787297828221821, 'colsample_bytree': 0.856844056880923, 'gamma': 0.669294199296976, 'reg_alpha': 0.032833597493022726, 'reg_lambda': 0.05192714216548729}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:21:50,488] Trial 42 finished with value: 0.5040287387247184 and parameters: {'learning_rate': 0.02539080946187146, 'max_depth': 5, 'min_child_weight': 3.4329951529735108, 'subsample': 0.8298188545420353, 'colsample_bytree': 0.9354037095819698, 'gamma': 0.46435526013192535, 'reg_alpha': 0.019565709900138156, 'reg_lambda': 0.09469214902201885}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:22:04,828] Trial 43 finished with value: 0.5358870013516754 and parameters: {'learning_rate': 0.037878206624172316, 'max_depth': 4, 'min_child_weight': 1.636775019024293, 'subsample': 0.705397568194451, 'colsample_bytree': 0.737951259645381, 'gamma': 0.8029761029948947, 'reg_alpha': 0.14668834701526617, 'reg_lambda': 0.2982480301632897}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:22:19,683] Trial 44 finished with value: 0.5436114461426271 and parameters: {'learning_rate': 0.035311579768541934, 'max_depth': 3, 'min_child_weight': 1.5343387304012852, 'subsample': 0.7022581490875461, 'colsample_bytree': 0.9497167729741283, 'gamma': 0.8339268328457652, 'reg_alpha': 2.0411179003800597, 'reg_lambda': 0.3525353646371749}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:22:34,903] Trial 45 finished with value: 0.5222017803362236 and parameters: {'learning_rate': 0.030926553735957818, 'max_depth': 3, 'min_child_weight': 1.3655067685683842, 'subsample': 0.7400562454582863, 'colsample_bytree': 0.9501335982217101, 'gamma': 1.112422557945643, 'reg_alpha': 1.4854157471537102, 'reg_lambda': 0.8252766142515591}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:22:48,319] Trial 46 finished with value: 0.5153423492163747 and parameters: {'learning_rate': 0.05093649744758775, 'max_depth': 3, 'min_child_weight': 1.313736999013072, 'subsample': 0.7104287531927982, 'colsample_bytree': 0.9811552221158616, 'gamma': 1.5134272209074786, 'reg_alpha': 2.9183094913110197, 'reg_lambda': 0.16468933227019106}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:23:01,540] Trial 47 finished with value: 0.508920408948067 and parameters: {'learning_rate': 0.06772727270000847, 'max_depth': 4, 'min_child_weight': 9.022944054241323, 'subsample': 0.749107314713364, 'colsample_bytree': 0.9310956124702877, 'gamma': 1.2126992075996668, 'reg_alpha': 0.003117899294068189, 'reg_lambda': 1.4610551100689602}. Best is trial 7 with value: 0.5447915702365014.
[I 2026-04-15 18:23:14,628] Trial 48 finished with value: 0.5321127049957057 and parameters: {'learning_rate': 0.03594872443782828, 'max_depth': 3, 'min_child_weight': 1.6401368402710708, 'subsample': 0.7693262564323453, 'colsample_bytree': 0.9082327216213018, 'gamma': 0.8893763568599621, 'reg_alpha': 0.3833389162526949, 'reg_lambda': 0.3758570705686006}. Best is trial 7 with value: 0.5447915702365014.

[I 2026-04-15 18:38:28,402] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 18:38:38,281] Trial 0 finished with value: 0.46761104446242463 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.46761104446242463.
[I 2026-04-15 18:38:55,361] Trial 1 finished with value: 0.4931494581412623 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4931494581412623.
[I 2026-04-15 18:39:20,379] Trial 2 finished with value: 0.49808519605174995 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.49808519605174995.
[I 2026-04-15 18:40:07,756] Trial 3 finished with value: 0.5416534326311958 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:41:25,740] Trial 4 finished with value: 0.5195545567795771 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:43:09,212] Trial 5 finished with value: 0.4900901129826919 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:43:51,177] Trial 6 finished with value: 0.4878039495240841 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:44:37,561] Trial 7 finished with value: 0.4940720329470689 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:46:21,295] Trial 8 finished with value: 0.4909539696866332 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:47:05,118] Trial 9 finished with value: 0.523943446281114 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:47:18,699] Trial 10 finished with value: 0.5031136277644235 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1570794430403163, 'depth': 5, 'l2_leaf_reg': 5.721398227528868, 'random_strength': 0.9905905821371315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9500025439539328}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:48:06,771] Trial 11 finished with value: 0.4972724593079716 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11440146940676205, 'depth': 7, 'l2_leaf_reg': 1.0055494782392767, 'random_strength': 0.8447250365019746, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.610132565398292}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:49:01,564] Trial 12 finished with value: 0.5053991268794346 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05174771285605761, 'depth': 7, 'l2_leaf_reg': 2.7728115183376625, 'random_strength': 0.6348316867316592, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6321797169112121}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:49:24,379] Trial 13 finished with value: 0.5123319395683392 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11898154973533921, 'depth': 6, 'l2_leaf_reg': 1.0243898522210106, 'random_strength': 0.9872568024263515, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8599786866753021}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:50:36,797] Trial 14 finished with value: 0.534863306026263 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032189307821966336, 'depth': 7, 'l2_leaf_reg': 2.8548672618995736, 'random_strength': 0.7239838132164096, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6796078903462887}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:51:12,024] Trial 15 finished with value: 0.5034709765983051 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03158712721771952, 'depth': 6, 'l2_leaf_reg': 3.1686229979975122, 'random_strength': 0.5908553977238399, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7050761452300236}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:51:30,239] Trial 16 finished with value: 0.5265178770899949 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03411360365691947, 'depth': 5, 'l2_leaf_reg': 7.372401598396334, 'random_strength': 0.4776807852053371, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8182234869712319}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:52:37,930] Trial 17 finished with value: 0.5165920513870965 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0593808534112181, 'depth': 7, 'l2_leaf_reg': 11.347663493082347, 'random_strength': 0.7320346383582577, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.6922144307592991}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:52:56,796] Trial 18 finished with value: 0.5063125922754546 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03705635981523311, 'depth': 5, 'l2_leaf_reg': 2.5170514356418203, 'random_strength': 0.5451099103981927, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8602997903820767}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:56:01,134] Trial 19 finished with value: 0.5093616395481111 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02610553896261639, 'depth': 8, 'l2_leaf_reg': 4.115804022215761, 'random_strength': 0.7938660564295515, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7457143454695254}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:56:55,657] Trial 20 finished with value: 0.509337051487634 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06264220303642364, 'depth': 7, 'l2_leaf_reg': 19.60965277102468, 'random_strength': 0.3937119620267663, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.6657484549901347}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:57:13,240] Trial 21 finished with value: 0.5140189166500929 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03660677448285459, 'depth': 5, 'l2_leaf_reg': 7.4492138888587, 'random_strength': 0.4844931341563402, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8309891269506943}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:57:31,088] Trial 22 finished with value: 0.5359802301733685 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03904665394769623, 'depth': 5, 'l2_leaf_reg': 7.161486413008518, 'random_strength': 0.681364080359283, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7985291040012883}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:58:02,551] Trial 23 finished with value: 0.5378912790301119 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04328992050153678, 'depth': 6, 'l2_leaf_reg': 5.545295354971215, 'random_strength': 0.6928839151250676, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7875178256853149}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:58:35,704] Trial 24 finished with value: 0.5114861842882992 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.042147881557940636, 'depth': 6, 'l2_leaf_reg': 9.327278930598505, 'random_strength': 0.6731407694306932, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7850831819671604}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:58:52,032] Trial 25 finished with value: 0.5000483744973041 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.055410734069366925, 'depth': 5, 'l2_leaf_reg': 5.717256991747445, 'random_strength': 0.896737080925635, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8873715721682847}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:58:59,273] Trial 26 finished with value: 0.5274364084732304 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09726601442604568, 'depth': 4, 'l2_leaf_reg': 5.8275656703107765, 'random_strength': 0.5691385797105732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:59:26,829] Trial 27 finished with value: 0.5035762673699483 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06996526265025156, 'depth': 6, 'l2_leaf_reg': 11.817092997132576, 'random_strength': 0.6826595629030466, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.9174233909712339}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 18:59:44,663] Trial 28 finished with value: 0.5030327560406839 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.043529595974910316, 'depth': 5, 'l2_leaf_reg': 8.561601381315374, 'random_strength': 0.9052200692625049, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.7333327496499376}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 19:00:07,114] Trial 29 finished with value: 0.527293409148584 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08724066527355809, 'depth': 6, 'l2_leaf_reg': 6.692220247780366, 'random_strength': 0.7963597041313875, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 19:00:20,743] Trial 30 finished with value: 0.5376674506598184 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027299881236764724, 'depth': 4, 'l2_leaf_reg': 3.5509108315059983, 'random_strength': 0.5826276589595287, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8040122370142464}. Best is trial 3 with value: 0.5416534326311958.
[I 2026-04-15 19:00:33,819] Trial 31 finished with value: 0.543011500297695 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02824831521957341, 'depth': 4, 'l2_leaf_reg': 3.593120749727222, 'random_strength': 0.5995947136964218, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8023185903572889}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:00:46,413] Trial 32 finished with value: 0.5195255762766595 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026614294977530276, 'depth': 4, 'l2_leaf_reg': 2.092360864796638, 'random_strength': 0.5356284334166043, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8192095525988323}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:00:55,688] Trial 33 finished with value: 0.506068378525381 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022864797726258546, 'depth': 4, 'l2_leaf_reg': 3.828306676438086, 'random_strength': 0.41151356945355444, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7882556133291732}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:01:07,365] Trial 34 finished with value: 0.5279773352735435 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02908131482288015, 'depth': 4, 'l2_leaf_reg': 3.3045580371466645, 'random_strength': 0.6037002156054808, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.9979235787949021}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:01:21,996] Trial 35 finished with value: 0.49763338463188855 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.020261729863419613, 'depth': 4, 'l2_leaf_reg': 4.927355049252618, 'random_strength': 0.16082059774872098, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.7204610152536303}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:01:36,654] Trial 36 finished with value: 0.5178125156754585 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028669664481378858, 'depth': 4, 'l2_leaf_reg': 1.6719047497077888, 'random_strength': 0.26518380751142245, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7719645897899117}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:01:47,882] Trial 37 finished with value: 0.526457626248665 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.02325074425248687, 'depth': 4, 'l2_leaf_reg': 2.1815003730836335, 'random_strength': 0.5399757248347946, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.04451881606481045}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:03:29,479] Trial 38 finished with value: 0.5168857928916254 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04808129694327533, 'depth': 8, 'l2_leaf_reg': 3.584237612959309, 'random_strength': 0.6372971117056575, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8451896386752173}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:03:42,957] Trial 39 finished with value: 0.4979851162292012 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06992107212211822, 'depth': 4, 'l2_leaf_reg': 15.27293445814073, 'random_strength': 0.4184629203486027, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 3.91602211054221}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:05:45,780] Trial 40 finished with value: 0.5131760295432437 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023346583323313467, 'depth': 8, 'l2_leaf_reg': 4.614504985034627, 'random_strength': 0.2859837733000461, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8811756029209239}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:06:02,993] Trial 41 finished with value: 0.5025497358880922 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039961272534939564, 'depth': 5, 'l2_leaf_reg': 5.074114703409317, 'random_strength': 0.6772152484584787, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8067837403060516}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:06:21,054] Trial 42 finished with value: 0.5208798665056107 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03761077154697602, 'depth': 5, 'l2_leaf_reg': 10.714272979191733, 'random_strength': 0.7190282073971249, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.8006001231893353}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:06:39,593] Trial 43 finished with value: 0.5064041126904347 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04774290548505899, 'depth': 5, 'l2_leaf_reg': 6.522216170777854, 'random_strength': 0.7770963364054898, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.7569852422558075}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:06:48,354] Trial 44 finished with value: 0.5371883349688342 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02994726858421259, 'depth': 4, 'l2_leaf_reg': 12.788098902973799, 'random_strength': 0.6215608692599073, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.772166733812454}. Best is trial 31 with value: 0.543011500297695.
[I 2026-04-15 19:06:59,162] Trial 45 finished with value: 0.5269212952885367 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030075172843017185, 'depth': 4, 'l2_leaf_reg': 13.394247683551189, 'random_strength': 0.003701014064702468, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7654875017373999}. Best is trial 31 with value: 0.543011500297695.

                                         feature  importance
208           eye__fix_duration_AOI_FD_Pos1_mean    6.705244
55       eye__sac_length_AOI_aggregated_Pos_mean    6.081454
205          eye__fix_duration_AOI_FD_Pos1_first    5.076829
58        eye__sac_length_AOI_aggregated_Pos_sum    4.962777
277     eye__fix_duration_AOI_aggregated_Pos_max    4.857560
414           eye__det_euclidean_length_2_rho_25    4.545650
54        eye__sac_length_AOI_aggregated_Pos_max    4.121136
868        PID__PID_FT7_second_deriv_energy_mean    3.972635
59      eye__sac_length_AOI_aggregated_Pos_count    3.386901
270    eye__fix_duration_AOI_aggregated_None_std    3.154523
394           eye__det_euclidean_length_1_rho_25    3.074345
60         eye__sac_speed_AOI_aggregated_Pos_min    3.007285
213            eye__fix_duration_AOI_FD_Pos1_sum    2.886265
1077                PID__PID_T8_data_energy_mean    2.737890
284   eye__fix_duration_AOI_aggregated_Pos_count    2.337194
187            eye__fix_duration_AOI_FD_None_max    1.635725
586               PID__PID_POz_second_deriv_mean    1.623272
186            eye__fix_duration_AOI_FD_None_min    1.518781
832          PID__PID_T7_first_deriv_energy_mean    1.420851
565               PID__PID_Fp1_second_deriv_mean    1.348042
515                 PID__PID_P5_first_deriv_mean    1.347996
446          eye__det_euclidean_length_3_rho_500    1.346432
0                            eye__sac_length_min    1.336526
64         eye__sac_speed_AOI_aggregated_Pos_std    1.323404
389     eye__rec_metric_euclidean_length_1_rho_5    1.311202
211       eye__fix_duration_AOI_FD_Pos1_kurtosis    1.281029
266    eye__fix_duration_AOI_aggregated_None_min    1.250085
526                 PID__PID_Pz_first_deriv_mean    1.233523
831          PID__PID_Pz_first_deriv_energy_mean    1.216373
536                PID__PID_C2_second_deriv_mean    1.186722

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST

[I 2026-04-15 19:09:15,567] A new study created in memory with name: binary_xgb

[PID] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST__no_neutral
X_train: (3016, 1080), X_test: (336, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 19:09:26,374] Trial 0 finished with value: 0.4919936434073776 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.4919936434073776.
[I 2026-04-15 19:09:37,555] Trial 1 finished with value: 0.5151597843740066 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 1 with value: 0.5151597843740066.
[I 2026-04-15 19:09:52,705] Trial 2 finished with value: 0.553556507249002 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.553556507249002.
[I 2026-04-15 19:10:03,240] Trial 3 finished with value: 0.5406985704379266 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.553556507249002.
[I 2026-04-15 19:10:13,740] Trial 4 finished with value: 0.5716073788440759 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 4 with value: 0.5716073788440759.
[I 2026-04-15 19:10:25,857] Trial 5 finished with value: 0.58535524483075 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:10:34,290] Trial 6 finished with value: 0.5355594540562896 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:10:46,344] Trial 7 finished with value: 0.5814363120713336 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:10:54,362] Trial 8 finished with value: 0.5504583404784478 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:11:10,599] Trial 9 finished with value: 0.5706281397103417 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:11:20,800] Trial 10 finished with value: 0.530828812291642 and parameters: {'learning_rate': 0.053574840865446394, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.9948638614233253, 'colsample_bytree': 0.8365039320348027, 'gamma': 1.3709161615904817, 'reg_alpha': 0.0003269908763524355, 'reg_lambda': 0.00839106795699683}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:11:34,333] Trial 11 finished with value: 0.5609320117673757 and parameters: {'learning_rate': 0.03231772671434705, 'max_depth': 7, 'min_child_weight': 9.82128943308808, 'subsample': 0.8387066013238305, 'colsample_bytree': 0.9853854325968012, 'gamma': 1.1266428947523253, 'reg_alpha': 0.012646341639534743, 'reg_lambda': 0.00013386192543122697}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:11:48,083] Trial 12 finished with value: 0.5647861248707324 and parameters: {'learning_rate': 0.03677282124112453, 'max_depth': 7, 'min_child_weight': 5.9752070205206556, 'subsample': 0.9227014502820593, 'colsample_bytree': 0.839153517743987, 'gamma': 0.5934862123369633, 'reg_alpha': 0.0030093802418649854, 'reg_lambda': 0.012729000183049172}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:12:00,941] Trial 13 finished with value: 0.5105178277633238 and parameters: {'learning_rate': 0.02144158286805027, 'max_depth': 6, 'min_child_weight': 6.857520517807074, 'subsample': 0.830708901865747, 'colsample_bytree': 0.7012088256639494, 'gamma': 1.5105057458377462, 'reg_alpha': 8.457871731466039, 'reg_lambda': 0.1455342066074402}. Best is trial 5 with value: 0.58535524483075.
[I 2026-04-15 19:12:13,065] Trial 14 finished with value: 0.5906565385797734 and parameters: {'learning_rate': 0.06870601128688399, 'max_depth': 8, 'min_child_weight': 7.445239260743859, 'subsample': 0.9870030703299256, 'colsample_bytree': 0.8880624944018081, 'gamma': 0.7218831677473481, 'reg_alpha': 0.06926103504427304, 'reg_lambda': 0.011924988205055102}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:12:25,393] Trial 15 finished with value: 0.5436022448674895 and parameters: {'learning_rate': 0.06919298904036045, 'max_depth': 8, 'min_child_weight': 4.5715175950844875, 'subsample': 0.9907425579887397, 'colsample_bytree': 0.8782698102844885, 'gamma': 0.026193432718633558, 'reg_alpha': 0.0017781443527443105, 'reg_lambda': 0.008535187299907751}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:12:41,851] Trial 16 finished with value: 0.5776624456335687 and parameters: {'learning_rate': 0.05325889492294849, 'max_depth': 8, 'min_child_weight': 2.3886199011481484, 'subsample': 0.9374231092171544, 'colsample_bytree': 0.797418911969743, 'gamma': 0.3827339168043826, 'reg_alpha': 0.05163736470611545, 'reg_lambda': 0.000366051516059916}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:12:50,331] Trial 17 finished with value: 0.5780892072560309 and parameters: {'learning_rate': 0.1146883413997056, 'max_depth': 3, 'min_child_weight': 6.951332015268755, 'subsample': 0.9669589257824658, 'colsample_bytree': 0.8860011999072293, 'gamma': 0.7484292950465277, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 0.0034288948731140472}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:13:00,131] Trial 18 finished with value: 0.5142241385747278 and parameters: {'learning_rate': 0.08692531941506346, 'max_depth': 4, 'min_child_weight': 4.886095457095131, 'subsample': 0.9008588986612591, 'colsample_bytree': 0.8074213105844478, 'gamma': 0.2809989717735992, 'reg_alpha': 0.014126797540635236, 'reg_lambda': 9.699586322297742}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:13:15,420] Trial 19 finished with value: 0.5801562245537268 and parameters: {'learning_rate': 0.06130326546866995, 'max_depth': 7, 'min_child_weight': 2.4769439111180587, 'subsample': 0.9693334695645044, 'colsample_bytree': 0.905359217093405, 'gamma': 0.41170010304088833, 'reg_alpha': 0.5260813231920917, 'reg_lambda': 0.022835058640281777}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:13:28,091] Trial 20 finished with value: 0.574357360785192 and parameters: {'learning_rate': 0.044539280527547964, 'max_depth': 8, 'min_child_weight': 7.562921828400587, 'subsample': 0.8722945279490208, 'colsample_bytree': 0.8466445670931371, 'gamma': 0.8649089199942468, 'reg_alpha': 0.05428197488852677, 'reg_lambda': 0.004119751544499884}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:13:42,574] Trial 21 finished with value: 0.5666697556064595 and parameters: {'learning_rate': 0.026386668182949408, 'max_depth': 6, 'min_child_weight': 8.391299194442972, 'subsample': 0.9151352514258673, 'colsample_bytree': 0.9964244522822499, 'gamma': 1.2389910011973826, 'reg_alpha': 0.2455280537358515, 'reg_lambda': 0.2209752068966986}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:13:52,355] Trial 22 finished with value: 0.5258855650084842 and parameters: {'learning_rate': 0.04063880191794829, 'max_depth': 4, 'min_child_weight': 9.531646446808141, 'subsample': 0.8168255772342443, 'colsample_bytree': 0.9144225106490009, 'gamma': 0.9663785186351638, 'reg_alpha': 0.9368026447039309, 'reg_lambda': 0.03593944713828602}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:14:07,645] Trial 23 finished with value: 0.5762749203097008 and parameters: {'learning_rate': 0.028271415313006358, 'max_depth': 7, 'min_child_weight': 5.502389471005037, 'subsample': 0.8080321379937969, 'colsample_bytree': 0.96317743952449, 'gamma': 0.6406471264184546, 'reg_alpha': 0.015286333973764218, 'reg_lambda': 0.3136498684053461}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:14:18,559] Trial 24 finished with value: 0.5244277305866377 and parameters: {'learning_rate': 0.06157351750280884, 'max_depth': 6, 'min_child_weight': 7.627322198174557, 'subsample': 0.7548589579960588, 'colsample_bytree': 0.9645491791777111, 'gamma': 1.3676872960807138, 'reg_alpha': 0.1113023319794592, 'reg_lambda': 0.08318865530476535}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:14:28,544] Trial 25 finished with value: 0.5390016914059508 and parameters: {'learning_rate': 0.04697808335809872, 'max_depth': 5, 'min_child_weight': 6.448457759571395, 'subsample': 0.7000695502104095, 'colsample_bytree': 0.7783114139036986, 'gamma': 0.14883417330023221, 'reg_alpha': 0.005716635581196808, 'reg_lambda': 0.015819192698718246}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:14:40,311] Trial 26 finished with value: 0.5604109863802796 and parameters: {'learning_rate': 0.07037400390508607, 'max_depth': 7, 'min_child_weight': 3.9295774390802567, 'subsample': 0.9712626494317296, 'colsample_bytree': 0.8191881363506156, 'gamma': 0.9834173570524479, 'reg_alpha': 0.035803070731610286, 'reg_lambda': 0.7799767562107858}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:14:53,755] Trial 27 finished with value: 0.548059825093193 and parameters: {'learning_rate': 0.02670349393801741, 'max_depth': 6, 'min_child_weight': 8.68470776661941, 'subsample': 0.9970676590604486, 'colsample_bytree': 0.8674287427459931, 'gamma': 0.44499599521807376, 'reg_alpha': 4.821162575028007, 'reg_lambda': 0.004410118156501105}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:15:07,162] Trial 28 finished with value: 0.5386331911477118 and parameters: {'learning_rate': 0.05392014219909454, 'max_depth': 8, 'min_child_weight': 5.185056510192481, 'subsample': 0.8844809028648355, 'colsample_bytree': 0.9071730099080445, 'gamma': 1.204877190327487, 'reg_alpha': 0.4776789659419509, 'reg_lambda': 0.028548227151180838}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:15:17,926] Trial 29 finished with value: 0.5078986673549617 and parameters: {'learning_rate': 0.04183292862753337, 'max_depth': 4, 'min_child_weight': 3.7482920187178674, 'subsample': 0.940960296666434, 'colsample_bytree': 0.7545658393093484, 'gamma': 0.2796741006933227, 'reg_alpha': 0.11316902374363022, 'reg_lambda': 2.9603525521016802}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:15:27,435] Trial 30 finished with value: 0.5778760410208887 and parameters: {'learning_rate': 0.11135563668762403, 'max_depth': 5, 'min_child_weight': 8.167234471209412, 'subsample': 0.8471233543279311, 'colsample_bytree': 0.7113089070094042, 'gamma': 0.6756331176320052, 'reg_alpha': 0.0012070221346910397, 'reg_lambda': 1.5661934343663604}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:15:40,136] Trial 31 finished with value: 0.5643136402872369 and parameters: {'learning_rate': 0.06423528747478131, 'max_depth': 7, 'min_child_weight': 2.3331581863885087, 'subsample': 0.9676600255654639, 'colsample_bytree': 0.899737565719324, 'gamma': 0.4876017270758706, 'reg_alpha': 0.5440169934737646, 'reg_lambda': 0.02278429170393459}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:15:53,230] Trial 32 finished with value: 0.5283086425417702 and parameters: {'learning_rate': 0.08405498726442652, 'max_depth': 7, 'min_child_weight': 2.3469602590323437, 'subsample': 0.9553120439159577, 'colsample_bytree': 0.921252894159415, 'gamma': 0.15951247546252917, 'reg_alpha': 0.9302533807431427, 'reg_lambda': 0.08646036327716504}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:16:09,612] Trial 33 finished with value: 0.5452345963507088 and parameters: {'learning_rate': 0.05929390369019458, 'max_depth': 8, 'min_child_weight': 2.8392175983048378, 'subsample': 0.971135727577219, 'colsample_bytree': 0.9642074212617365, 'gamma': 0.17183659926792713, 'reg_alpha': 0.2519981669991467, 'reg_lambda': 0.00811752719606577}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:16:25,407] Trial 34 finished with value: 0.5212678299951943 and parameters: {'learning_rate': 0.04820134887914015, 'max_depth': 7, 'min_child_weight': 1.7568804628295533, 'subsample': 0.926591573882573, 'colsample_bytree': 0.8585401398613407, 'gamma': 0.5001148644184299, 'reg_alpha': 2.5479385768225726, 'reg_lambda': 0.04449619709257878}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:16:34,689] Trial 35 finished with value: 0.5101410561222984 and parameters: {'learning_rate': 0.14524202195766972, 'max_depth': 6, 'min_child_weight': 2.8688451084212483, 'subsample': 0.9784599456270623, 'colsample_bytree': 0.9290382413140106, 'gamma': 0.8960325945408297, 'reg_alpha': 0.06852529039692437, 'reg_lambda': 0.0007890861196917543}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:16:45,926] Trial 36 finished with value: 0.5470851927676388 and parameters: {'learning_rate': 0.07280870872551735, 'max_depth': 7, 'min_child_weight': 9.999978053662037, 'subsample': 0.950207509705075, 'colsample_bytree': 0.9011724996905589, 'gamma': 0.7731784122740455, 'reg_alpha': 0.006711152709447055, 'reg_lambda': 0.002886252958763231}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:01,421] Trial 37 finished with value: 0.5398152905429294 and parameters: {'learning_rate': 0.035887590148471954, 'max_depth': 8, 'min_child_weight': 2.107959538128198, 'subsample': 0.7283530388261409, 'colsample_bytree': 0.9529773647868732, 'gamma': 0.3590181337235734, 'reg_alpha': 0.02275783317568924, 'reg_lambda': 0.1408860782814851}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:13,056] Trial 38 finished with value: 0.5529504020456772 and parameters: {'learning_rate': 0.10244501360979821, 'max_depth': 5, 'min_child_weight': 1.4479031670559976, 'subsample': 0.7607675734805526, 'colsample_bytree': 0.9837504910736228, 'gamma': 0.2246977743132616, 'reg_alpha': 0.19133769088855535, 'reg_lambda': 0.019466571109906673}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:24,542] Trial 39 finished with value: 0.5525346660811981 and parameters: {'learning_rate': 0.13322255056672344, 'max_depth': 6, 'min_child_weight': 3.323108318079665, 'subsample': 0.796114374091663, 'colsample_bytree': 0.8922360128543361, 'gamma': 0.09791050839278687, 'reg_alpha': 2.512141095366742, 'reg_lambda': 0.0011388849690304066}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:38,947] Trial 40 finished with value: 0.5602451993800831 and parameters: {'learning_rate': 0.031057703656355434, 'max_depth': 6, 'min_child_weight': 4.190299732473478, 'subsample': 0.9829918265289436, 'colsample_bytree': 0.7765380388234422, 'gamma': 1.7511341972310097, 'reg_alpha': 1.2580857126912044, 'reg_lambda': 0.048151765499772924}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:47,605] Trial 41 finished with value: 0.5524312084621643 and parameters: {'learning_rate': 0.09242081510034124, 'max_depth': 3, 'min_child_weight': 6.799206027641376, 'subsample': 0.9579689974015038, 'colsample_bytree': 0.8811247044777919, 'gamma': 0.7397082200786983, 'reg_alpha': 0.00014571501444147906, 'reg_lambda': 0.002592321756219555}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:17:57,124] Trial 42 finished with value: 0.5704380823426214 and parameters: {'learning_rate': 0.07777147181692994, 'max_depth': 4, 'min_child_weight': 7.182666369605005, 'subsample': 0.9987875664377339, 'colsample_bytree': 0.8674043264874436, 'gamma': 0.5525142213502074, 'reg_alpha': 0.00024720228541080997, 'reg_lambda': 0.00631303664916852}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:18:04,613] Trial 43 finished with value: 0.5661199126815548 and parameters: {'learning_rate': 0.1956836633811061, 'max_depth': 3, 'min_child_weight': 5.819132130683035, 'subsample': 0.9407921725814061, 'colsample_bytree': 0.8267155938464021, 'gamma': 1.0648229368863344, 'reg_alpha': 0.0009509053229172417, 'reg_lambda': 0.013177984692364388}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:18:14,211] Trial 44 finished with value: 0.5846661873524328 and parameters: {'learning_rate': 0.14360114203512134, 'max_depth': 5, 'min_child_weight': 6.308348604394303, 'subsample': 0.9019769047611563, 'colsample_bytree': 0.9449233549167171, 'gamma': 0.7083596036288, 'reg_alpha': 0.47217358330067766, 'reg_lambda': 0.0005206681185776964}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:18:22,119] Trial 45 finished with value: 0.5641625547533093 and parameters: {'learning_rate': 0.1542143984063937, 'max_depth': 5, 'min_child_weight': 8.2527037394733, 'subsample': 0.9147612332435421, 'colsample_bytree': 0.9416992680528679, 'gamma': 0.4098864842196379, 'reg_alpha': 0.3334550654150905, 'reg_lambda': 0.0001714896798559155}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:18:35,126] Trial 46 finished with value: 0.5371720095835154 and parameters: {'learning_rate': 0.023224953717813742, 'max_depth': 5, 'min_child_weight': 8.830194180734397, 'subsample': 0.8589331749525749, 'colsample_bytree': 0.951132306229627, 'gamma': 0.9259309552257444, 'reg_alpha': 0.5761893604234303, 'reg_lambda': 0.00032114900650441594}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:18:48,036] Trial 47 finished with value: 0.5647406087819926 and parameters: {'learning_rate': 0.055332726796330896, 'max_depth': 7, 'min_child_weight': 6.01148402310725, 'subsample': 0.8965843653185397, 'colsample_bytree': 0.9272320706358853, 'gamma': 0.6672974025531104, 'reg_alpha': 0.1554753809491366, 'reg_lambda': 0.0004719059765223214}. Best is trial 14 with value: 0.5906565385797734.
[I 2026-04-15 19:19:05,691] Trial 48 finished with value: 0.5088655778685021 and parameters: {'learning_rate': 0.03725737415974644, 'max_depth': 5, 'min_child_weight': 1.019777155940096, 'subsample': 0.9839174543150089, 'colsample_bytree': 0.9834090058105124, 'gamma': 0.023391844833003217, 'reg_alpha': 0.037668374963552374, 'reg_lambda': 0.0014345048431466236}. Best is trial 14 with value: 0.5906565385797734.

[I 2026-04-15 19:29:28,102] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.50032
              precision    recall  f1-score   support

           0       0.71      0.91      0.80       234
           1       0.40      0.14      0.20       102

    accuracy                           0.68       336
   macro avg       0.55      0.52      0.50       336
weighted avg       0.61      0.68      0.62       336

Confusion matrix:
 [[213  21]
 [ 88  14]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 19:29:39,577] Trial 0 finished with value: 0.5455404220363863 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5455404220363863.
[I 2026-04-15 19:30:04,354] Trial 1 finished with value: 0.5444575843924375 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.5455404220363863.
[I 2026-04-15 19:30:28,710] Trial 2 finished with value: 0.5801073257182789 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5801073257182789.
[I 2026-04-15 19:31:26,951] Trial 3 finished with value: 0.5743526437631605 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.5801073257182789.
[I 2026-04-15 19:32:12,537] Trial 4 finished with value: 0.5823989896444453 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:33:30,102] Trial 5 finished with value: 0.5599156685003699 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:34:20,765] Trial 6 finished with value: 0.5504115614131111 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:35:33,515] Trial 7 finished with value: 0.5354864551973045 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:38:04,609] Trial 8 finished with value: 0.5420761772781952 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:38:37,590] Trial 9 finished with value: 0.5451671598917942 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:38:47,712] Trial 10 finished with value: 0.5637603714280791 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:39:07,582] Trial 11 finished with value: 0.5636976238326152 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039688510872899645, 'depth': 6, 'l2_leaf_reg': 5.099113810219792, 'random_strength': 0.009181969852355254, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:39:16,297] Trial 12 finished with value: 0.5613897216168688 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19865482678572852, 'depth': 5, 'l2_leaf_reg': 2.5661282769743514, 'random_strength': 0.4056021261617175, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8098142139158072}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:39:26,479] Trial 13 finished with value: 0.5489717078647176 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13208847240962562, 'depth': 5, 'l2_leaf_reg': 6.381137193432291, 'random_strength': 0.008517488278889707, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.75842730538531}. Best is trial 4 with value: 0.5823989896444453.
[I 2026-04-15 19:40:06,580] Trial 14 finished with value: 0.5856232415170539 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04234001494954542, 'depth': 7, 'l2_leaf_reg': 1.1491748140889606, 'random_strength': 0.29107942442033097, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8791010705732631}. Best is trial 14 with value: 0.5856232415170539.
[I 2026-04-15 19:41:31,049] Trial 15 finished with value: 0.5706439692481202 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033323727950433785, 'depth': 8, 'l2_leaf_reg': 1.0071882758063284, 'random_strength': 0.20664358001435718, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.891611978943904}. Best is trial 14 with value: 0.5856232415170539.
[I 2026-04-15 19:41:58,958] Trial 16 finished with value: 0.5679215723039037 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1200968091310539, 'depth': 7, 'l2_leaf_reg': 1.5570360207622767, 'random_strength': 0.5657469824738883, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9998908231041508}. Best is trial 14 with value: 0.5856232415170539.
[I 2026-04-15 19:43:14,860] Trial 17 finished with value: 0.5905841254611852 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0593808534112181, 'depth': 8, 'l2_leaf_reg': 2.82249298588333, 'random_strength': 0.2763752143244782, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8712793297296567}. Best is trial 17 with value: 0.5905841254611852.
[I 2026-04-15 19:43:45,845] Trial 18 finished with value: 0.5854676541800132 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0560932081847863, 'depth': 7, 'l2_leaf_reg': 3.0977987972818526, 'random_strength': 0.28223662782846237, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8690337285758514}. Best is trial 17 with value: 0.5905841254611852.
[I 2026-04-15 19:45:37,022] Trial 19 finished with value: 0.5915276671509838 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03135524873132374, 'depth': 8, 'l2_leaf_reg': 2.707149610125713, 'random_strength': 0.4973905284705819, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9394716488088194}. Best is trial 19 with value: 0.5915276671509838.
[I 2026-04-15 19:47:18,182] Trial 20 finished with value: 0.5750840694178964 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.029658377596316215, 'depth': 8, 'l2_leaf_reg': 2.8678323608457363, 'random_strength': 0.5403540417857632, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9732500380980695}. Best is trial 19 with value: 0.5915276671509838.
[I 2026-04-15 19:48:40,909] Trial 21 finished with value: 0.5882511422283262 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05600734530318811, 'depth': 8, 'l2_leaf_reg': 3.248984259788118, 'random_strength': 0.4123264876993609, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9243362118172915}. Best is trial 19 with value: 0.5915276671509838.
[I 2026-04-15 19:49:55,005] Trial 22 finished with value: 0.5918252962805047 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05716724370318515, 'depth': 8, 'l2_leaf_reg': 3.532519107030247, 'random_strength': 0.46375500543323817, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9275170107765649}. Best is trial 22 with value: 0.5918252962805047.
[I 2026-04-15 19:51:10,636] Trial 23 finished with value: 0.592883438824797 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05942360154287183, 'depth': 8, 'l2_leaf_reg': 3.7160198720941273, 'random_strength': 0.4867075185103654, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9393539242373402}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 19:53:54,297] Trial 24 finished with value: 0.5872830459190862 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.033849810857827435, 'depth': 8, 'l2_leaf_reg': 3.912904053773784, 'random_strength': 0.6248499864041119, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.94595979169518}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 19:54:44,632] Trial 25 finished with value: 0.574797292101866 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02410465135730132, 'depth': 7, 'l2_leaf_reg': 2.2784275075366898, 'random_strength': 0.48895751777985624, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9986863284042589}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 19:56:19,051] Trial 26 finished with value: 0.5927292370783386 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04834191993299331, 'depth': 8, 'l2_leaf_reg': 5.590327979162349, 'random_strength': 0.5819617111104287, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 19:57:11,794] Trial 27 finished with value: 0.5586063424909442 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04989811027813795, 'depth': 7, 'l2_leaf_reg': 6.096222373114259, 'random_strength': 0.7290542417594967, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.30094396714113597}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 19:58:51,250] Trial 28 finished with value: 0.5904623716127007 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0677847934393328, 'depth': 8, 'l2_leaf_reg': 6.152034526410033, 'random_strength': 0.5892407526546868, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.22090791623893452}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:01:28,568] Trial 29 finished with value: 0.56184204455822 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09678061842608895, 'depth': 8, 'l2_leaf_reg': 8.206176429216297, 'random_strength': 0.6986013153360966, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.3784693681010873}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:02:57,097] Trial 30 finished with value: 0.5485153364708248 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.037862862901104, 'depth': 7, 'l2_leaf_reg': 3.57836069176285, 'random_strength': 0.8321767031919783, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.4993264036145195}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:04:17,319] Trial 31 finished with value: 0.5330357041096541 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06750797032531844, 'depth': 8, 'l2_leaf_reg': 5.207325572311704, 'random_strength': 0.509098738784929, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.370956938236069}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:06:01,850] Trial 32 finished with value: 0.536311227097128 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05062171233150041, 'depth': 8, 'l2_leaf_reg': 2.184231397205728, 'random_strength': 0.43442575663831495, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.164704118387009}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:06:10,840] Trial 33 finished with value: 0.5693960547618963 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030172520816565584, 'depth': 4, 'l2_leaf_reg': 3.692877333021469, 'random_strength': 0.34992987595602554, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9031074386459936}. Best is trial 23 with value: 0.592883438824797.
[I 2026-04-15 20:09:35,565] Trial 34 finished with value: 0.6110015496712137 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.036133823489542985, 'depth': 8, 'l2_leaf_reg': 2.093572196234382, 'random_strength': 0.3692788548048864, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9562522596307999}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:10:30,977] Trial 35 finished with value: 0.5763103608508452 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03758993516745618, 'depth': 6, 'l2_leaf_reg': 2.004079439322665, 'random_strength': 0.16082059774872098, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9693781393698435}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:13:24,399] Trial 36 finished with value: 0.5910530931671303 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04559186193307832, 'depth': 8, 'l2_leaf_reg': 1.4825270988579682, 'random_strength': 0.379036026954157, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8323916028876972}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:14:36,960] Trial 37 finished with value: 0.5586007930914 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09148378272595663, 'depth': 7, 'l2_leaf_reg': 7.790602970906816, 'random_strength': 0.6040471033397699, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 3.7272701169983553}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:18:09,324] Trial 38 finished with value: 0.5913539055842285 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.062448682793995035, 'depth': 8, 'l2_leaf_reg': 4.658807765263027, 'random_strength': 0.538984823128872, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9108085693968756}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:19:32,089] Trial 39 finished with value: 0.580413105380428 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.052727898404944, 'depth': 7, 'l2_leaf_reg': 9.487303782909526, 'random_strength': 0.22600617994322342, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.7286242350522154}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:22:59,847] Trial 40 finished with value: 0.5992632239710307 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.043679743030237486, 'depth': 8, 'l2_leaf_reg': 11.676545448257057, 'random_strength': 0.3520499495648465, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9578432943148413}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:26:35,724] Trial 41 finished with value: 0.5839987863119274 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04403610500171344, 'depth': 8, 'l2_leaf_reg': 19.94290880084992, 'random_strength': 0.33725247544773795, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9665181864728165}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:30:17,137] Trial 42 finished with value: 0.5896811266330285 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.035733058635069356, 'depth': 8, 'l2_leaf_reg': 11.810328046697018, 'random_strength': 0.4495851359966937, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9608262852135698}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:35:19,862] Trial 43 finished with value: 0.5922905644314638 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027585617252842445, 'depth': 8, 'l2_leaf_reg': 12.795247889655034, 'random_strength': 0.3309878043845945, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9155067053501276}. Best is trial 34 with value: 0.6110015496712137.
[I 2026-04-15 20:37:50,395] Trial 44 finished with value: 0.5748515271855242 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025593339808530048, 'depth': 7, 'l2_leaf_reg': 13.779608518182842, 'random_strength': 0.3292299108233315, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9819829223763028}. Best is trial 34 with value: 0.6110015496712137.

                                        feature  importance
56    eye__sac_length_AOI_aggregated_Pos_median    0.034906
60        eye__sac_speed_AOI_aggregated_Pos_min    0.027653
486                PID__PID_Cz_first_deriv_mean    0.017595
1027               PID__PID_C5_data_energy_mean    0.014559
806        PID__PID_FCz_first_deriv_energy_mean    0.011044
478                PID__PID_C5_first_deriv_mean    0.010993
791         PID__PID_Cz_first_deriv_energy_mean    0.009843
184         eye__fix_duration_AOI_FD_Neg1_count    0.009478
783         PID__PID_C5_first_deriv_energy_mean    0.008882
714                      PID__PID_AF3_data_mean    0.008482
818         PID__PID_P3_first_deriv_energy_mean    0.007321
339               eye__sample_entropy_m=3_r=200    0.007177
32    eye__sac_length_AOI_aggregated_Neg_median    0.007001
738                       PID__PID_F8_data_mean    0.006957
508                PID__PID_O1_first_deriv_mean    0.006598
816         PID__PID_P1_first_deriv_energy_mean    0.006363
798         PID__PID_F7_first_deriv_energy_mean    0.006363
792         PID__PID_F1_first_deriv_energy_mean    0.006285
817         PID__PID_P2_first_deriv_energy_mean    0.006098
406         eye__det_euclidean_length_1_rho_500    0.006072
529               PID__PID_TP7_first_deriv_mean    0.005996
183           eye__fix_duration_AOI_FD_Neg1_sum    0.005955
334               eye__sample_entropy_m=2_r=200    0.005905
795         PID__PID_F4_first_deriv_energy_mean    0.005808
722                       PID__PID_C5_data_mean    0.005792
834        PID__PID_TP7_first_deriv_energy_mean    0.005740
177           eye__fix_duration_AOI_FD_Neg1_max    0.005546
520               PID__PID_PO4_first_deriv_mean    0.005408
1064               PID__PID_P5_data_energy_mean    0.005385
826        PID__PID_PO5_first_deriv_energy_mean    0.005378

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.60317
              precision    recall  f1-score   support

           0       0.75      0.86      0.80       234
           1       0.52      0.33      0.40       102

    accuracy                           0.70       336
   macro avg       0.63      0.60      0.60       336
weighted avg       0.68      0.70      0.68       336

Confusion matrix:
 [[202  32]
 [ 68  34]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+PID__target=match_mismatch_general__problem=binary__feat=all_features+PID__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                        feature  importance
60        eye__sac_speed_AOI_aggregated_Pos_min    9.108060
464                               eye__imf0_min    5.159229
183           eye__fix_duration_AOI_FD_Neg1_sum    1.770953
333               eye__sample_entropy_m=2_r=100    1.634796
284  eye__fix_duration_AOI_aggregated_Pos_count    1.444710
53       eye__sac_length_AOI_aggregated_Pos_min    1.437798
817         PID__PID_P2_first_deriv_energy_mean    1.276754
54       eye__sac_length_AOI_aggregated_Pos_max    1.112546
62       eye__sac_speed_AOI_aggregated_Pos_mean    1.074834
465                               eye__imf0_max    1.064627
56    eye__sac_length_AOI_aggregated_Pos_median    1.050205
177           eye__fix_duration_AOI_FD_Neg1_max    0.870372
61        eye__sac_speed_AOI_aggregated_Pos_max    0.827120
11                        eye__sac_speed_median    0.806018
276    eye__fix_duration_AOI_aggregated_Pos_min    0.802899
5                           eye__sac_length_sum    0.710077
791         PID__PID_Cz_first_deriv_energy_mean    0.691006
478                PID__PID_C5_first_deriv_mean    0.665921
263    eye__fix_duration_AOI_aggregated_Neg_sum    0.663837
486                PID__PID_Cz_first_deriv_mean    0.639827
32    eye__sac_length_AOI_aggregated_Neg_median    0.612553
883        PID__PID_P7_second_deriv_energy_mean    0.605243
283    eye__fix_duration_AOI_aggregated_Pos_sum    0.566385
512                PID__PID_P2_first_deriv_mean    0.564457
257    eye__fix_duration_AOI_aggregated_Neg_max    0.544761
783         PID__PID_C5_first_deriv_energy_mean    0.538572
59     eye__sac_length_AOI_aggregated_Pos_count    0.535110
63     eye__sac_speed_AOI_aggregated_Pos_median    0.527056
277    eye__fix_duration_AOI_aggregated_Pos_max    0.502807
504               PID__PID_Fp1_first_deriv_mean    0.492877

================================================================================
Skipping existing experiment: exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST

[I 2026-04-15 20:58:55,396] A new study created in memory with name: multiclass_xgb

[PID] rows missing after index match -> train: 1658, test: 160

================================================================================
Running: exp__X_name=screen+PID__target=match_mismatch_general__problem=multiclass__feat=all_features+PID__ES__refitTEST__no_neutral
X_train: (3016, 1080), X_test: (336, 1080)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 20:59:13,986] Trial 0 finished with value: 0.635956094440027 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.635956094440027.
[I 2026-04-15 20:59:31,297] Trial 1 finished with value: 0.6090490042414035 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.635956094440027.
[I 2026-04-15 20:59:51,760] Trial 2 finished with value: 0.6405406996684714 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:00:06,690] Trial 3 finished with value: 0.6310217147272495 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:00:17,921] Trial 4 finished with value: 0.6205514651125796 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:00:38,734] Trial 5 finished with value: 0.6216200237139333 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:00:48,793] Trial 6 finished with value: 0.6276939713620844 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:01:13,610] Trial 7 finished with value: 0.6278232873636296 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:01:24,780] Trial 8 finished with value: 0.6079974754797575 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:01:54,316] Trial 9 finished with value: 0.6342135695903093 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:02:14,501] Trial 10 finished with value: 0.6330871904182457 and parameters: {'learning_rate': 0.023921952016615802, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8323975169664899, 'colsample_bytree': 0.8251024923043149, 'gamma': 1.4856799266904641, 'reg_alpha': 0.000753460297138337, 'reg_lambda': 0.00839106795699683}. Best is trial 2 with value: 0.6405406996684714.
[I 2026-04-15 21:02:30,201] Trial 11 finished with value: 0.6476323822609064 and parameters: {'learning_rate': 0.04576434565047688, 'max_depth': 3, 'min_child_weight': 2.3905799325075687, 'subsample': 0.7007682715107971, 'colsample_bytree': 0.792839147773371, 'gamma': 0.5892553864010996, 'reg_alpha': 0.00035288433980529597, 'reg_lambda': 6.866439769808518}. Best is trial 11 with value: 0.6476323822609064.
[I 2026-04-15 21:02:49,711] Trial 12 finished with value: 0.6516615856875936 and parameters: {'learning_rate': 0.03463737347266536, 'max_depth': 3, 'min_child_weight': 1.8013333198609394, 'subsample': 0.7011742284537262, 'colsample_bytree': 0.812338321746966, 'gamma': 1.388531138825063, 'reg_alpha': 0.00011046383485499768, 'reg_lambda': 8.695553254091415}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:03:05,642] Trial 13 finished with value: 0.6502935109296868 and parameters: {'learning_rate': 0.03835024457420548, 'max_depth': 3, 'min_child_weight': 2.2136911944932556, 'subsample': 0.7024126991302786, 'colsample_bytree': 0.8553787592407296, 'gamma': 1.3589328557629148, 'reg_alpha': 0.0001835329481134243, 'reg_lambda': 9.724469378980013}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:03:26,282] Trial 14 finished with value: 0.6415383941082713 and parameters: {'learning_rate': 0.032221131606127267, 'max_depth': 4, 'min_child_weight': 2.237689207762887, 'subsample': 0.7407348278626916, 'colsample_bytree': 0.8710442744149802, 'gamma': 1.4070763230684742, 'reg_alpha': 0.0001000946101155844, 'reg_lambda': 8.399152598419297}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:03:39,415] Trial 15 finished with value: 0.6370571214841426 and parameters: {'learning_rate': 0.06919298904036045, 'max_depth': 3, 'min_child_weight': 2.4370747834999373, 'subsample': 0.700717276709995, 'colsample_bytree': 0.837529415994899, 'gamma': 1.3491140443341108, 'reg_alpha': 0.004467741323313117, 'reg_lambda': 1.2735104728489444}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:04:00,184] Trial 16 finished with value: 0.6406458625041525 and parameters: {'learning_rate': 0.027825922586861836, 'max_depth': 4, 'min_child_weight': 1.0390220542707507, 'subsample': 0.8319464978824339, 'colsample_bytree': 0.8921254911151859, 'gamma': 1.2444329479101315, 'reg_alpha': 0.00010543775528511165, 'reg_lambda': 0.30142816102311787}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:04:15,311] Trial 17 finished with value: 0.6358403366224017 and parameters: {'learning_rate': 0.04191300360152842, 'max_depth': 3, 'min_child_weight': 1.5188371557080198, 'subsample': 0.738246873299525, 'colsample_bytree': 0.8074972464120408, 'gamma': 1.653078858715917, 'reg_alpha': 0.0024812870915905173, 'reg_lambda': 2.5310996823984957}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:04:30,567] Trial 18 finished with value: 0.6360335235271916 and parameters: {'learning_rate': 0.057673843325961635, 'max_depth': 4, 'min_child_weight': 4.165219471679138, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.8461121982963495, 'gamma': 0.832911477007952, 'reg_alpha': 0.0016833335803052476, 'reg_lambda': 9.699586322297742}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:04:45,365] Trial 19 finished with value: 0.634510183146334 and parameters: {'learning_rate': 0.03829639207999195, 'max_depth': 3, 'min_child_weight': 2.020530849628887, 'subsample': 0.7579427635891753, 'colsample_bytree': 0.905359217093405, 'gamma': 1.6321408741876482, 'reg_alpha': 0.00029525751253105167, 'reg_lambda': 0.01451463332937745}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:05:06,447] Trial 20 finished with value: 0.6409498680967562 and parameters: {'learning_rate': 0.027306861787714735, 'max_depth': 4, 'min_child_weight': 2.7634485035433674, 'subsample': 0.8147015203889975, 'colsample_bytree': 0.7716916083804688, 'gamma': 1.212620360204875, 'reg_alpha': 0.011736033826735966, 'reg_lambda': 0.00014979337155117755}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:05:21,133] Trial 21 finished with value: 0.6325843354061254 and parameters: {'learning_rate': 0.04910035569450224, 'max_depth': 3, 'min_child_weight': 2.544159615417053, 'subsample': 0.7058080671325933, 'colsample_bytree': 0.7939940953670682, 'gamma': 0.4862149631108893, 'reg_alpha': 0.0002430878065892432, 'reg_lambda': 3.586573852445899}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:05:35,191] Trial 22 finished with value: 0.6418848785138933 and parameters: {'learning_rate': 0.06808908839867202, 'max_depth': 3, 'min_child_weight': 1.3690951002974245, 'subsample': 0.7217042679666316, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.8324921402193809, 'reg_alpha': 0.000829944242006393, 'reg_lambda': 9.834804218951255}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:05:52,040] Trial 23 finished with value: 0.6331618302953983 and parameters: {'learning_rate': 0.040942919764565225, 'max_depth': 4, 'min_child_weight': 2.8952127786720476, 'subsample': 0.7568909134771207, 'colsample_bytree': 0.8144878446934021, 'gamma': 0.5586849888896056, 'reg_alpha': 0.0002718352493053437, 'reg_lambda': 1.5242241472226805}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:06:06,935] Trial 24 finished with value: 0.6461891936958127 and parameters: {'learning_rate': 0.037072813835812256, 'max_depth': 3, 'min_child_weight': 1.9695137788464347, 'subsample': 0.700068543084044, 'colsample_bytree': 0.849019299203021, 'gamma': 0.8638280093819819, 'reg_alpha': 0.00020891410171073693, 'reg_lambda': 3.924956908612555}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:06:28,914] Trial 25 finished with value: 0.6326345720024391 and parameters: {'learning_rate': 0.027736935451139498, 'max_depth': 4, 'min_child_weight': 1.6722237587826616, 'subsample': 0.7291761585946146, 'colsample_bytree': 0.86368840074975, 'gamma': 0.41387292144862065, 'reg_alpha': 0.0009528628755647427, 'reg_lambda': 0.2768867791633537}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:06:43,558] Trial 26 finished with value: 0.6281404283928848 and parameters: {'learning_rate': 0.05625265643266363, 'max_depth': 3, 'min_child_weight': 2.213202528399577, 'subsample': 0.7602856568575334, 'colsample_bytree': 0.7793603136206904, 'gamma': 0.7015061381116343, 'reg_alpha': 0.00010170183971949589, 'reg_lambda': 1.0083790862624018}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:07:20,232] Trial 27 finished with value: 0.6400412328479128 and parameters: {'learning_rate': 0.02028337079338744, 'max_depth': 8, 'min_child_weight': 1.2444861623368333, 'subsample': 0.8772061654964453, 'colsample_bytree': 0.8260946596438464, 'gamma': 0.9925717200855599, 'reg_alpha': 6.166485205705214, 'reg_lambda': 5.390671246071665}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:07:39,229] Trial 28 finished with value: 0.6275409775544945 and parameters: {'learning_rate': 0.047105639570648956, 'max_depth': 5, 'min_child_weight': 3.543312720029747, 'subsample': 0.8118314220732303, 'colsample_bytree': 0.9071730099080445, 'gamma': 1.4534803139742762, 'reg_alpha': 0.0004300524057320289, 'reg_lambda': 0.28910386218320955}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:07:55,269] Trial 29 finished with value: 0.64417477528941 and parameters: {'learning_rate': 0.08194044450484951, 'max_depth': 4, 'min_child_weight': 4.638163082698516, 'subsample': 0.7216927661879304, 'colsample_bytree': 0.7614288790824788, 'gamma': 0.2931147485051485, 'reg_alpha': 0.002522079492458128, 'reg_lambda': 2.5456793226211563}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:08:16,580] Trial 30 finished with value: 0.6344985415995454 and parameters: {'learning_rate': 0.04732655102423342, 'max_depth': 7, 'min_child_weight': 3.2299048801632777, 'subsample': 0.718826809404803, 'colsample_bytree': 0.7165916960107654, 'gamma': 1.2370019069315308, 'reg_alpha': 0.008203022993152499, 'reg_lambda': 2.217302181469101}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:08:31,810] Trial 31 finished with value: 0.6380491189893266 and parameters: {'learning_rate': 0.04016306100280543, 'max_depth': 3, 'min_child_weight': 1.954409027329548, 'subsample': 0.7067828873456918, 'colsample_bytree': 0.8552210580779271, 'gamma': 0.8991917628048917, 'reg_alpha': 0.0002468321001697823, 'reg_lambda': 4.136963165705642}. Best is trial 12 with value: 0.6516615856875936.
[I 2026-04-15 21:08:45,782] Trial 32 finished with value: 0.6576653286472451 and parameters: {'learning_rate': 0.03592951812756398, 'max_depth': 3, 'min_child_weight': 1.8166945021005823, 'subsample': 0.7016359151246816, 'colsample_bytree': 0.8007018469458203, 'gamma': 0.7044666665577126, 'reg_alpha': 0.0001765905510954914, 'reg_lambda': 5.2330693225521046}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:09:05,197] Trial 33 finished with value: 0.6342042551352705 and parameters: {'learning_rate': 0.031000935948205653, 'max_depth': 3, 'min_child_weight': 1.708360889752354, 'subsample': 0.7453793003820912, 'colsample_bytree': 0.792694573275166, 'gamma': 0.35966453300825985, 'reg_alpha': 0.0005124008566829228, 'reg_lambda': 6.173044160280713}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:09:25,494] Trial 34 finished with value: 0.639718774822357 and parameters: {'learning_rate': 0.03630681980566249, 'max_depth': 4, 'min_child_weight': 1.2478017916559103, 'subsample': 0.7252380216910256, 'colsample_bytree': 0.8071914383364726, 'gamma': 0.7136352220163941, 'reg_alpha': 0.0015460257167583165, 'reg_lambda': 1.2686999341107108}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:09:45,385] Trial 35 finished with value: 0.636296518786131 and parameters: {'learning_rate': 0.024284773322738092, 'max_depth': 3, 'min_child_weight': 2.3403820668975115, 'subsample': 0.7138467696644364, 'colsample_bytree': 0.7881549795461045, 'gamma': 0.18078121473194297, 'reg_alpha': 0.00017153299539506982, 'reg_lambda': 0.6158189519714937}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:09:55,950] Trial 36 finished with value: 0.6383365030252302 and parameters: {'learning_rate': 0.13469108396399915, 'max_depth': 3, 'min_child_weight': 1.4385421261571025, 'subsample': 0.7711051165171251, 'colsample_bytree': 0.7606206901513338, 'gamma': 1.5489788827758089, 'reg_alpha': 0.0004525199579634149, 'reg_lambda': 5.392922569116147}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:10:09,418] Trial 37 finished with value: 0.6288544730778518 and parameters: {'learning_rate': 0.043150264683228294, 'max_depth': 4, 'min_child_weight': 2.724468420054644, 'subsample': 0.9785482037213632, 'colsample_bytree': 0.8235942304651409, 'gamma': 1.8236636510342816, 'reg_alpha': 0.0012030685772182793, 'reg_lambda': 2.1556905775847026}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:10:28,929] Trial 38 finished with value: 0.6165847875286803 and parameters: {'learning_rate': 0.0609893083192022, 'max_depth': 7, 'min_child_weight': 2.0941043560721413, 'subsample': 0.7365940927592417, 'colsample_bytree': 0.8321943279076469, 'gamma': 0.978070472752393, 'reg_alpha': 0.07228981101866326, 'reg_lambda': 0.8085695884747843}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:10:53,330] Trial 39 finished with value: 0.6319713810720683 and parameters: {'learning_rate': 0.0340622250292117, 'max_depth': 5, 'min_child_weight': 1.7953891379433045, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.7298095522324257, 'gamma': 0.6990908461317394, 'reg_alpha': 0.00017794097745299297, 'reg_lambda': 9.542232477595944}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:11:09,158] Trial 40 finished with value: 0.6291394274260887 and parameters: {'learning_rate': 0.05229506973949812, 'max_depth': 4, 'min_child_weight': 6.390730092849743, 'subsample': 0.9312647070030003, 'colsample_bytree': 0.7999946577210449, 'gamma': 1.120344084195127, 'reg_alpha': 0.0005050473843433629, 'reg_lambda': 0.12669421344099815}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:11:23,054] Trial 41 finished with value: 0.6460489571458505 and parameters: {'learning_rate': 0.03812863228801232, 'max_depth': 3, 'min_child_weight': 1.8945408084067807, 'subsample': 0.7030574456398498, 'colsample_bytree': 0.8479133113763936, 'gamma': 0.6637446191534078, 'reg_alpha': 0.0001633589995225851, 'reg_lambda': 3.9012033407691935}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:11:39,185] Trial 42 finished with value: 0.6484957257611141 and parameters: {'learning_rate': 0.030062027200319367, 'max_depth': 3, 'min_child_weight': 1.6170521233598776, 'subsample': 0.7003589876510606, 'colsample_bytree': 0.8876400421932057, 'gamma': 1.345652398044282, 'reg_alpha': 0.924180900169408, 'reg_lambda': 4.702580245919753}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:12:00,216] Trial 43 finished with value: 0.6428418674525959 and parameters: {'learning_rate': 0.029809398614583947, 'max_depth': 3, 'min_child_weight': 1.568712274951229, 'subsample': 0.7511547792422296, 'colsample_bytree': 0.9996533142159789, 'gamma': 1.367695084065892, 'reg_alpha': 0.8005656164286727, 'reg_lambda': 1.7677083845138253}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:12:28,934] Trial 44 finished with value: 0.6477273427529477 and parameters: {'learning_rate': 0.02473699741727301, 'max_depth': 3, 'min_child_weight': 1.2158914750746799, 'subsample': 0.7286673307689242, 'colsample_bytree': 0.8816770047075918, 'gamma': 1.7851419154910793, 'reg_alpha': 6.74815575672893, 'reg_lambda': 5.70612407024693}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:12:50,641] Trial 45 finished with value: 0.6447065315482257 and parameters: {'learning_rate': 0.02457877317872568, 'max_depth': 3, 'min_child_weight': 1.204374486074783, 'subsample': 0.7729827942009242, 'colsample_bytree': 0.8867289567972266, 'gamma': 1.7971690896936114, 'reg_alpha': 2.5034256798544394, 'reg_lambda': 0.4414255463849161}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:13:16,434] Trial 46 finished with value: 0.6416951907707437 and parameters: {'learning_rate': 0.02173683594273251, 'max_depth': 4, 'min_child_weight': 1.1247498788502144, 'subsample': 0.7312616451791444, 'colsample_bytree': 0.9184336496833805, 'gamma': 1.7599818459802112, 'reg_alpha': 0.5127485282012385, 'reg_lambda': 5.48795945948198}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:13:43,575] Trial 47 finished with value: 0.643662660045657 and parameters: {'learning_rate': 0.02617850327120291, 'max_depth': 3, 'min_child_weight': 1.4253897705248926, 'subsample': 0.7168590707074378, 'colsample_bytree': 0.8694176516827492, 'gamma': 1.5701432985741086, 'reg_alpha': 9.710389008391143, 'reg_lambda': 2.8502552111208583}. Best is trial 32 with value: 0.6576653286472451.
[I 2026-04-15 21:14:05,055] Trial 48 finished with value: 0.6464755215993936 and parameters: {'learning_rate': 0.022791219186428898, 'max_depth': 3, 'min_child_weight': 1.6401368402710703, 'subsample': 0.7981199892847557, 'colsample_bytree': 0.9496493198537965, 'gamma': 1.9518637989498937, 'reg_alpha': 2.348659739086987, 'reg_lambda': 0.025480851334519404}. Best is trial 32 with value: 0.6576653286472451.

[I 2026-04-15 21:31:34,896] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 21:31:48,782] Trial 0 finished with value: 0.62227135023457 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.62227135023457.
[I 2026-04-15 21:32:13,421] Trial 1 finished with value: 0.6486174000448082 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:32:45,222] Trial 2 finished with value: 0.6423570812916353 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:33:38,219] Trial 3 finished with value: 0.6315071793627183 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:34:58,772] Trial 4 finished with value: 0.61220392559379 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:36:55,450] Trial 5 finished with value: 0.6393141809558336 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:37:51,101] Trial 6 finished with value: 0.6283055209956675 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:39:09,110] Trial 7 finished with value: 0.6455903363833394 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:42:13,807] Trial 8 finished with value: 0.6400614428533841 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:43:03,300] Trial 9 finished with value: 0.6339581052111904 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6486174000448082.
[I 2026-04-15 21:43:28,701] Trial 10 finished with value: 0.6567072679361761 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:43:52,127] Trial 11 finished with value: 0.6486437298006754 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02005507141938724, 'depth': 4, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.20696700950514785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9614099298964858}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:44:26,138] Trial 12 finished with value: 0.6554873715720613 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02773911038527166, 'depth': 5, 'l2_leaf_reg': 19.276136746270595, 'random_strength': 0.3008805194885487, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9694888529772017}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:44:46,407] Trial 13 finished with value: 0.6407809921240011 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03383769175128965, 'depth': 5, 'l2_leaf_reg': 6.137972289439494, 'random_strength': 0.005333101970815796, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9715986510881334}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:45:11,942] Trial 14 finished with value: 0.6494362877430664 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.030832894768454664, 'depth': 5, 'l2_leaf_reg': 12.49605285737672, 'random_strength': 0.4100750513516051, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8791010705732631}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:45:41,664] Trial 15 finished with value: 0.6443233811630096 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03699604572505095, 'depth': 5, 'l2_leaf_reg': 18.234028524908812, 'random_strength': 0.5623181046141312, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8993268614028405}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:46:06,132] Trial 16 finished with value: 0.654305940431494 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.026510550793148457, 'depth': 5, 'l2_leaf_reg': 3.4677749005132785, 'random_strength': 0.24975973556094924, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8690032808569894}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:46:17,996] Trial 17 finished with value: 0.6458678560545801 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05270434151146841, 'depth': 4, 'l2_leaf_reg': 6.833075327945019, 'random_strength': 0.3491923639077172, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9935818138690481}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:46:32,281] Trial 18 finished with value: 0.6234101227544516 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1196127262797001, 'depth': 5, 'l2_leaf_reg': 10.68122006875492, 'random_strength': 0.9580941097934477, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.926761243212412}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:47:43,451] Trial 19 finished with value: 0.6491246986867303 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02487998532743962, 'depth': 6, 'l2_leaf_reg': 14.289634071353467, 'random_strength': 0.5684540704304097, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8458175994747911}. Best is trial 10 with value: 0.6567072679361761.
[I 2026-04-15 21:47:54,702] Trial 20 finished with value: 0.6626349044622225 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03975803268759683, 'depth': 4, 'l2_leaf_reg': 2.6816725490896114, 'random_strength': 0.10705551985998438, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8290562500466551}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:48:07,614] Trial 21 finished with value: 0.6478403642785732 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.038334658508870745, 'depth': 4, 'l2_leaf_reg': 2.48264177509736, 'random_strength': 0.13058751843288344, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8254881108000223}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:48:23,060] Trial 22 finished with value: 0.6544324288069946 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02970422470780815, 'depth': 4, 'l2_leaf_reg': 2.7153362426812984, 'random_strength': 0.0010084962427511224, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9426309060893129}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:48:39,509] Trial 23 finished with value: 0.6466204489072722 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05852941498258112, 'depth': 5, 'l2_leaf_reg': 1.3544753856234777, 'random_strength': 0.2904799983880022, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9987867094597019}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:48:53,076] Trial 24 finished with value: 0.6494970802879282 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04078979343015537, 'depth': 4, 'l2_leaf_reg': 5.410215203028945, 'random_strength': 0.1026023463325959, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9229170690988975}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:49:19,800] Trial 25 finished with value: 0.6538124607933051 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023447695938273682, 'depth': 5, 'l2_leaf_reg': 2.677803840161381, 'random_strength': 0.23127249197296668, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8016849253908013}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:49:33,699] Trial 26 finished with value: 0.657779623199817 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.030879870863949943, 'depth': 4, 'l2_leaf_reg': 7.846046519336854, 'random_strength': 0.4253505173932581, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.2578643405925001}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:49:44,408] Trial 27 finished with value: 0.6538986120682205 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.032268980599861455, 'depth': 4, 'l2_leaf_reg': 8.260309244424205, 'random_strength': 0.43462025137210464, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.30094396714113597}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:49:57,848] Trial 28 finished with value: 0.653881656534838 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.022551429392912128, 'depth': 4, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.3910281584610583, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.22090791623893452}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:50:08,187] Trial 29 finished with value: 0.6451165722644355 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06439842941433138, 'depth': 4, 'l2_leaf_reg': 2.119194925074463, 'random_strength': 0.5035994255457021, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.3784693681010873}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:50:52,659] Trial 30 finished with value: 0.6346899526547417 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05009973086526217, 'depth': 6, 'l2_leaf_reg': 3.7861982619308256, 'random_strength': 0.08059479351129284, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 4.4993264036145195}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:51:20,805] Trial 31 finished with value: 0.6520102081252592 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.028363855839368006, 'depth': 4, 'l2_leaf_reg': 17.276320944567004, 'random_strength': 0.3316239971610172, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.370956938236069}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:52:05,549] Trial 32 finished with value: 0.6463205667963383 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.026291742280289316, 'depth': 5, 'l2_leaf_reg': 12.651260408130746, 'random_strength': 0.16781911115818815, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.164704118387009}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:52:22,659] Trial 33 finished with value: 0.6498029597469503 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03509085152246554, 'depth': 4, 'l2_leaf_reg': 8.589514054181063, 'random_strength': 0.26641501967442593, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8965970132977528}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:52:40,366] Trial 34 finished with value: 0.6618075322194907 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04089306889686301, 'depth': 4, 'l2_leaf_reg': 15.030876143718894, 'random_strength': 0.17469312340710008, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8497061968093587}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:52:51,876] Trial 35 finished with value: 0.6474916775526047 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.042512349302064094, 'depth': 4, 'l2_leaf_reg': 14.848365856888373, 'random_strength': 0.16536453874756446, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7775584038776752}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:53:05,146] Trial 36 finished with value: 0.6552693408536541 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04484056577692611, 'depth': 4, 'l2_leaf_reg': 10.272976689274119, 'random_strength': 0.18430991745742425, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8268568555645157}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:53:24,081] Trial 37 finished with value: 0.6329373650902521 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.057988103009453805, 'depth': 4, 'l2_leaf_reg': 11.915691408664156, 'random_strength': 0.034908299881090996, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 3.7272701169983553}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:53:51,232] Trial 38 finished with value: 0.6508503994481434 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.022561894643695676, 'depth': 4, 'l2_leaf_reg': 5.37427714782171, 'random_strength': 0.10309278692479733, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7290451040609561}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:54:19,787] Trial 39 finished with value: 0.6259074624721545 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19666138542450712, 'depth': 6, 'l2_leaf_reg': 7.3933120840479605, 'random_strength': 0.5073028539987454, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.7286242350522154}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:54:39,198] Trial 40 finished with value: 0.640309849747311 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03781041583172137, 'depth': 5, 'l2_leaf_reg': 1.7880266128945397, 'random_strength': 0.37753530469756347, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.85246605533644}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:54:58,931] Trial 41 finished with value: 0.6543787323967558 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028376811215528697, 'depth': 4, 'l2_leaf_reg': 19.96284653164551, 'random_strength': 0.19698715197529215, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.954759256244684}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:55:33,353] Trial 42 finished with value: 0.650036341457521 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03308189385812732, 'depth': 5, 'l2_leaf_reg': 16.140630798233275, 'random_strength': 0.3168239913397423, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9104355796767025}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:56:00,599] Trial 43 finished with value: 0.6582719677158814 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02083412248376795, 'depth': 4, 'l2_leaf_reg': 14.534137823354385, 'random_strength': 0.257436599978296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8054899354361744}. Best is trial 20 with value: 0.6626349044622225.
[I 2026-04-15 21:56:30,193] Trial 44 finished with value: 0.6573007028792168 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02083568805702849, 'depth': 4, 'l2_leaf_reg': 14.912033943997267, 'random_strength': 0.2312744433836305, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7927906895644151}. Best is trial 20 with value: 0.6626349044622225.

                                               feature  importance
56           eye__sac_length_AOI_aggregated_Pos_median   11.074327
63            eye__sac_speed_AOI_aggregated_Pos_median    7.075666
53              eye__sac_length_AOI_aggregated_Pos_min    7.040510
62              eye__sac_speed_AOI_aggregated_Pos_mean    6.269328
60               eye__sac_speed_AOI_aggregated_Pos_min    4.125146
544                     PID__PID_CP4_second_deriv_mean    2.936185
178                 eye__fix_duration_AOI_FD_Neg1_mean    2.328713
284         eye__fix_duration_AOI_aggregated_Pos_count    2.043635
166                              eye__fix_duration_min    1.941292
176                  eye__fix_duration_AOI_FD_Neg1_min    1.847281
177                  eye__fix_duration_AOI_FD_Neg1_max    1.642441
58              eye__sac_length_AOI_aggregated_Pos_sum    1.636336
870              PID__PID_Fp1_second_deriv_energy_mean    1.577012
278          eye__fix_duration_AOI_aggregated_Pos_mean    1.509410
54              eye__sac_length_AOI_aggregated_Pos_max    1.348354
32           eye__sac_length_AOI_aggregated_Neg_median    1.281300
0                                  eye__sac_length_min    1.189837
283           eye__fix_duration_AOI_aggregated_Pos_sum    1.081985
445         eye__rec_metric_euclidean_length_3_rho_500    1.068567
277           eye__fix_duration_AOI_aggregated_Pos_max    0.981313
55             eye__sac_length_AOI_aggregated_Pos_mean    0.883327
28                         eye__sac_angle_between_skew    0.868527
175                eye__fix_duration_AOI_FD_Neg1_first    0.848252
405         eye__rec_metric_euclidean_length_1_rho_500    0.833518
91   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.803448
809               PID__PID_Fp1_first_deriv_energy_mean    0.756100
92   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.731593
385                      eye__corr_dim_m_4_tau_1_r_400    0.723288
849              PID__PID_CP4_second_deriv_energy_mean    0.667591
425         eye__rec_metric_euclidean_length_2_rho_500    0.667370

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,False,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,binary,True,0.403197,0.404151,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch,multiclass,False,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch,multiclass,True,NaN,0.540870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,PID,match_mismatch_general,binary,False,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,PID,match_mismatch_general,binary,True,0.500321,0.603175,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,PID,match_mismatch_general,multiclass,False,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,PID,match_mismatch_general,multiclass,True,NaN,0.745125,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,PID,match_mismatch,binary,False,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,PID,match_mismatch,binary,True,0.403197,0.404151,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,PID,match_mismatch,multiclass,False,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,PID,match_mismatch,multiclass,True,NaN,0.540870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,PID,match_mismatch_general,binary,False,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,PID,match_mismatch_general,binary,True,0.500321,0.603175,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,PID,match_mismatch_general,multiclass,False,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,PID,match_mismatch_general,multiclass,True,NaN,0.745125,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [10]:
text_stat = _load_ftar_parquet(FTAR_FILES["stat"])
print("stat shape:", text_stat.shape)
summary_stat = run_ftar_set("stat", text_stat)
summary_stat

stat shape: (4442, 8236)
[stat] ftar feature count after cleanup: 8235

================================================================================
Skipping existing experiment: exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST
[stat] rows missing after index match -> train: 1658, test: 160
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 22:04:21,194] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 22:04:25,232] Trial 0 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:30,142] Trial 1 finished with value: 0.40352843125103893 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:34,946] Trial 2 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:39,635] Trial 3 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:44,748] Trial 4 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:50,437] Trial 5 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:04:55,192] Trial 6 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:05:00,831] Trial 7 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 0 with value: 0.40517617025578806.
[I 2026-04-15 22:05:05,980] Trial 8 finished with value: 0.4134557401482612 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:12,407] Trial 9 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:16,280] Trial 10 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11205588890315138, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.8345351823143565, 'colsample_bytree': 0.8543230417001932, 'gamma': 1.3577299273807322, 'reg_alpha': 9.489578816424906, 'reg_lambda': 0.00015640362680098967}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:20,755] Trial 11 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.05650939330260564, 'max_depth': 3, 'min_child_weight': 2.322330894118641, 'subsample': 0.7009303665284197, 'colsample_bytree': 0.810746971052945, 'gamma': 0.5892553864010996, 'reg_alpha': 0.000458516332228122, 'reg_lambda': 6.69351503516026}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:25,889] Trial 12 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.04075368674461933, 'max_depth': 4, 'min_child_weight': 2.8562067930535315, 'subsample': 0.7005391803807246, 'colsample_bytree': 0.999748196231103, 'gamma': 1.17498604192392, 'reg_alpha': 0.0005108910738055835, 'reg_lambda': 0.005628617972415363}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:30,930] Trial 13 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.11198932069742602, 'max_depth': 4, 'min_child_weight': 3.832378734922381, 'subsample': 0.7499415088949786, 'colsample_bytree': 0.7013693620912469, 'gamma': 0.45555356551772197, 'reg_alpha': 0.0036088022609738614, 'reg_lambda': 8.133522870163986}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:36,046] Trial 14 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07507576282412888, 'max_depth': 4, 'min_child_weight': 1.8849983821529872, 'subsample': 0.8327690499419715, 'colsample_bytree': 0.896755559294825, 'gamma': 1.4300503604766472, 'reg_alpha': 0.00010018646830937977, 'reg_lambda': 0.0001149404517214395}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:42,376] Trial 15 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.020253161906525208, 'max_depth': 7, 'min_child_weight': 5.997648729167906, 'subsample': 0.7343748005433923, 'colsample_bytree': 0.808215380740725, 'gamma': 0.8297825975919082, 'reg_alpha': 1.4427088337205427, 'reg_lambda': 0.8741655275059462}. Best is trial 8 with value: 0.4134557401482612.
[I 2026-04-15 22:05:48,251] Trial 16 finished with value: 0.42272719066395137 and parameters: {'learning_rate': 0.1468608387142319, 'max_depth': 7, 'min_child_weight': 1.3197480093163605, 'subsample': 0.8220119032312526, 'colsample_bytree': 0.8433042355616011, 'gamma': 0.3140458986440714, 'reg_alpha': 0.0045923956759843405, 'reg_lambda': 0.009820629819375128}. Best is trial 16 with value: 0.42272719066395137.
[I 2026-04-15 22:05:53,753] Trial 17 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.14901421729412756, 'max_depth': 8, 'min_child_weight': 1.2180785621788082, 'subsample': 0.8870911863689172, 'colsample_bytree': 0.8575478706685005, 'gamma': 0.8619102412837221, 'reg_alpha': 0.004665268650328248, 'reg_lambda': 0.010587687730752296}. Best is trial 16 with value: 0.42272719066395137.
[I 2026-04-15 22:05:58,571] Trial 18 finished with value: 0.4084094120511331 and parameters: {'learning_rate': 0.1417072165979035, 'max_depth': 7, 'min_child_weight': 1.6362301609790535, 'subsample': 0.8233422545057508, 'colsample_bytree': 0.9122375861390972, 'gamma': 1.3861006630123034, 'reg_alpha': 1.8250181476965615, 'reg_lambda': 0.0011738373677233824}. Best is trial 16 with value: 0.42272719066395137.
[I 2026-04-15 22:06:04,149] Trial 19 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12549292256352204, 'max_depth': 7, 'min_child_weight': 2.31024559580701, 'subsample': 0.9330088308146224, 'colsample_bytree': 0.8364366095199258, 'gamma': 0.6314244053607774, 'reg_alpha': 0.06011206751270975, 'reg_lambda': 0.0037654308980085483}. Best is trial 16 with value: 0.42272719066395137.
[I 2026-04-15 22:06:10,055] Trial 20 finished with value: 0.42398974587005145 and parameters: {'learning_rate': 0.19104277493883481, 'max_depth': 8, 'min_child_weight': 1.388727650536842, 'subsample': 0.7987845970801662, 'colsample_bytree': 0.9337493432709228, 'gamma': 0.32970508636838924, 'reg_alpha': 0.008980235956897564, 'reg_lambda': 0.019072723549575683}. Best is trial 20 with value: 0.42398974587005145.
[I 2026-04-15 22:06:16,070] Trial 21 finished with value: 0.44049422359932205 and parameters: {'learning_rate': 0.1955759947993397, 'max_depth': 8, 'min_child_weight': 1.0107164012771785, 'subsample': 0.8071268922635821, 'colsample_bytree': 0.9563631326469857, 'gamma': 0.2604017696784924, 'reg_alpha': 0.009590937991847369, 'reg_lambda': 0.019596741589935986}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:22,029] Trial 22 finished with value: 0.43754261325356403 and parameters: {'learning_rate': 0.19026081394505462, 'max_depth': 8, 'min_child_weight': 1.010170234706639, 'subsample': 0.8073660560048375, 'colsample_bytree': 0.9738782647850786, 'gamma': 0.2890342091701042, 'reg_alpha': 0.001579251807123468, 'reg_lambda': 0.023880754049408152}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:27,940] Trial 23 finished with value: 0.43940829048111046 and parameters: {'learning_rate': 0.1972645494518396, 'max_depth': 8, 'min_child_weight': 1.060452288435265, 'subsample': 0.8080321379937969, 'colsample_bytree': 0.9922682621675052, 'gamma': 0.28336278930028497, 'reg_alpha': 0.012738940100125579, 'reg_lambda': 0.02287173192573527}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:34,105] Trial 24 finished with value: 0.41143553138652617 and parameters: {'learning_rate': 0.195483096745204, 'max_depth': 8, 'min_child_weight': 1.0058837797110276, 'subsample': 0.8604693689487211, 'colsample_bytree': 0.9880013987970429, 'gamma': 0.18150573755899035, 'reg_alpha': 0.0015025982789921887, 'reg_lambda': 0.18295303654943043}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:41,983] Trial 25 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.08654516861412428, 'max_depth': 8, 'min_child_weight': 1.1622978609501213, 'subsample': 0.7626842528247109, 'colsample_bytree': 0.9660367345335691, 'gamma': 0.10315445277570834, 'reg_alpha': 0.01236490740961966, 'reg_lambda': 0.031526956258471454}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:48,121] Trial 26 finished with value: 0.42540499880030413 and parameters: {'learning_rate': 0.16412197203885595, 'max_depth': 8, 'min_child_weight': 1.0204776769468602, 'subsample': 0.8107226981634955, 'colsample_bytree': 0.9671519776449058, 'gamma': 0.46649158968472704, 'reg_alpha': 0.001501143159389054, 'reg_lambda': 0.21237488770751628}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:53,485] Trial 27 finished with value: 0.42974441649260764 and parameters: {'learning_rate': 0.19962542283849521, 'max_depth': 7, 'min_child_weight': 1.5143004260462738, 'subsample': 0.8532039365201661, 'colsample_bytree': 0.98348541388546, 'gamma': 0.48242026966545914, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 0.02482364619077187}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:06:59,066] Trial 28 finished with value: 0.41943644781535866 and parameters: {'learning_rate': 0.1355852907707668, 'max_depth': 8, 'min_child_weight': 1.1233261777143821, 'subsample': 0.8873056730847009, 'colsample_bytree': 0.9127929340977436, 'gamma': 0.24901240481731085, 'reg_alpha': 0.0014466366849462664, 'reg_lambda': 0.09888245502097247}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:05,072] Trial 29 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.10231345999972308, 'max_depth': 7, 'min_child_weight': 2.1655836490844256, 'subsample': 0.8052720421577734, 'colsample_bytree': 0.9529059243849687, 'gamma': 0.02534762815610153, 'reg_alpha': 0.0002566078465660969, 'reg_lambda': 0.003473118138692537}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:10,855] Trial 30 finished with value: 0.4169371159522821 and parameters: {'learning_rate': 0.1648172108376686, 'max_depth': 8, 'min_child_weight': 1.2266857860316907, 'subsample': 0.769058634139215, 'colsample_bytree': 0.99592594818776, 'gamma': 0.7381027689415107, 'reg_alpha': 0.04976046689430822, 'reg_lambda': 0.00050676465985771}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:16,367] Trial 31 finished with value: 0.4282378020778789 and parameters: {'learning_rate': 0.1984948377014955, 'max_depth': 7, 'min_child_weight': 1.5211065181096537, 'subsample': 0.8491250431264402, 'colsample_bytree': 0.9799807556333362, 'gamma': 0.4159621106208913, 'reg_alpha': 0.00012599544191526008, 'reg_lambda': 0.02889355057219004}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:22,307] Trial 32 finished with value: 0.4158018036005457 and parameters: {'learning_rate': 0.17312926156782985, 'max_depth': 8, 'min_child_weight': 1.8692072949288774, 'subsample': 0.8484134968490815, 'colsample_bytree': 0.9551098528520606, 'gamma': 0.3656834466404999, 'reg_alpha': 0.001099921790120491, 'reg_lambda': 0.013779387730549247}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:28,345] Trial 33 finished with value: 0.4206393752792806 and parameters: {'learning_rate': 0.19726591368596116, 'max_depth': 7, 'min_child_weight': 1.492445999543386, 'subsample': 0.8749504444555989, 'colsample_bytree': 0.9800715698154353, 'gamma': 0.2198714985262559, 'reg_alpha': 0.016555122204151455, 'reg_lambda': 0.041928850832473004}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:35,302] Trial 34 finished with value: 0.41617555080503443 and parameters: {'learning_rate': 0.15806992601581554, 'max_depth': 8, 'min_child_weight': 1.18595982849944, 'subsample': 0.8111114428271764, 'colsample_bytree': 0.9170081580181145, 'gamma': 0.0060225362243786495, 'reg_alpha': 0.002727793094862022, 'reg_lambda': 0.02156602939406286}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:41,637] Trial 35 finished with value: 0.40892989418826076 and parameters: {'learning_rate': 0.13114196102162154, 'max_depth': 8, 'min_child_weight': 1.3442030864419017, 'subsample': 0.840035348788142, 'colsample_bytree': 0.9583807235718356, 'gamma': 0.530965520460542, 'reg_alpha': 0.007840352837885822, 'reg_lambda': 0.3484017584808823}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:47,001] Trial 36 finished with value: 0.41876193943176104 and parameters: {'learning_rate': 0.17645142657347174, 'max_depth': 7, 'min_child_weight': 1.0988734519360883, 'subsample': 0.8648792019495258, 'colsample_bytree': 0.9982829315650151, 'gamma': 0.7229251774369615, 'reg_alpha': 0.00021385295128400423, 'reg_lambda': 0.06850317402563985}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:07:54,449] Trial 37 finished with value: 0.40687003194964977 and parameters: {'learning_rate': 0.09579958471740684, 'max_depth': 8, 'min_child_weight': 1.7379327440327128, 'subsample': 0.9082942015205822, 'colsample_bytree': 0.9293758048449686, 'gamma': 0.12424350502059298, 'reg_alpha': 0.0006894757709940456, 'reg_lambda': 0.004878399971041485}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:00,934] Trial 38 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.1486876894246933, 'max_depth': 7, 'min_child_weight': 1.3908613260761074, 'subsample': 0.7774456092394741, 'colsample_bytree': 0.9769538461445708, 'gamma': 0.2667583694666345, 'reg_alpha': 0.030461003842245933, 'reg_lambda': 0.051250877236625185}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:06,854] Trial 39 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.07391239341075699, 'max_depth': 6, 'min_child_weight': 4.795746008322342, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9464658172251725, 'gamma': 0.9615979140756251, 'reg_alpha': 0.002912339461076138, 'reg_lambda': 0.002516289712584303}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:12,080] Trial 40 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.17964911163004893, 'max_depth': 5, 'min_child_weight': 1.3023726284305557, 'subsample': 0.9183954316083046, 'colsample_bytree': 0.8817294719869149, 'gamma': 0.503247409598044, 'reg_alpha': 0.0002853471245533513, 'reg_lambda': 1.7287204976144017}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:17,690] Trial 41 finished with value: 0.418102902975364 and parameters: {'learning_rate': 0.1978674041727687, 'max_depth': 7, 'min_child_weight': 1.544023743530522, 'subsample': 0.8536387081337625, 'colsample_bytree': 0.9807054700340553, 'gamma': 0.40205654422793036, 'reg_alpha': 0.00012994010749211912, 'reg_lambda': 0.02788115886604693}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:23,555] Trial 42 finished with value: 0.42520365385885917 and parameters: {'learning_rate': 0.19990062713811446, 'max_depth': 8, 'min_child_weight': 1.9627606395615909, 'subsample': 0.8223780983903453, 'colsample_bytree': 0.9785899502598513, 'gamma': 0.39129346740423926, 'reg_alpha': 0.00020543889823761044, 'reg_lambda': 0.0174208240747211}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:29,304] Trial 43 finished with value: 0.4149524175115764 and parameters: {'learning_rate': 0.16307049998253992, 'max_depth': 6, 'min_child_weight': 2.640793524447493, 'subsample': 0.7987694408435809, 'colsample_bytree': 0.9589861891353739, 'gamma': 0.09606883411831701, 'reg_alpha': 0.0008367054227505015, 'reg_lambda': 0.006872753234285106}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:37,453] Trial 44 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.025308440279021516, 'max_depth': 7, 'min_child_weight': 1.5008369379843554, 'subsample': 0.844998462507282, 'colsample_bytree': 0.9855482295873643, 'gamma': 0.6851310543660379, 'reg_alpha': 0.00014982088044709395, 'reg_lambda': 0.03635942207788901}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:43,966] Trial 45 finished with value: 0.40517617025578806 and parameters: {'learning_rate': 0.12285851201267499, 'max_depth': 6, 'min_child_weight': 1.063406794347973, 'subsample': 0.872241792324033, 'colsample_bytree': 0.9246362718285043, 'gamma': 0.20199696360690347, 'reg_alpha': 0.11889255680818622, 'reg_lambda': 0.11222321734540802}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:48,434] Trial 46 finished with value: 0.42393655712335354 and parameters: {'learning_rate': 0.17880156486308235, 'max_depth': 7, 'min_child_weight': 1.1753591310806424, 'subsample': 0.7891802597369043, 'colsample_bytree': 0.7761938807285488, 'gamma': 0.5232663305431802, 'reg_alpha': 0.00049187274429192, 'reg_lambda': 0.06175681899649365}. Best is trial 21 with value: 0.44049422359932205.
[I 2026-04-15 22:08:55,396] Trial 47 finished with value: 0.4124967817125299 and parameters: {'learning_rate': 0.04270019726430054, 'max_depth': 8, 'min_child_weight': 1.6670141553708315, 'subsample': 0.8306612428709106, 'colsample_bytree': 0.944262613104243, 'gamma': 0.41305659138130324, 'reg_alpha': 0.4978150922319268, 'reg_lambda': 0.013853253076111786}. Best is trial 21 with value: 0.44049422359932205.

[I 2026-04-15 22:13:42,917] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.40320
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       227
           1       0.00      0.00      0.00       109

    accuracy                           0.68       336
   macro avg       0.34      0.50      0.40       336
weighted avg       0.46      0.68      0.54       336

Confusion matrix:
 [[227   0]
 [109   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 22:13:47,160] Trial 0 finished with value: 0.4156016409314246 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.4156016409314246.
[I 2026-04-15 22:13:54,332] Trial 1 finished with value: 0.4466589162454446 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.4466589162454446.
[I 2026-04-15 22:14:01,831] Trial 2 finished with value: 0.4493541832067489 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.4493541832067489.
[I 2026-04-15 22:14:14,456] Trial 3 finished with value: 0.43714053564039435 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.4493541832067489.
[I 2026-04-15 22:14:34,056] Trial 4 finished with value: 0.45927502283171656 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:14:57,537] Trial 5 finished with value: 0.43131115807371434 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:15:11,302] Trial 6 finished with value: 0.42823141303697954 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:15:24,709] Trial 7 finished with value: 0.423705448807998 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:15:53,266] Trial 8 finished with value: 0.4486813473225776 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:16:05,885] Trial 9 finished with value: 0.43459253886406346 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:16:10,282] Trial 10 finished with value: 0.4365754051633187 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1778306687966044, 'depth': 5, 'l2_leaf_reg': 1.7837574033604577, 'random_strength': 0.9540130779924979, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9347183475124077}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:16:18,011] Trial 11 finished with value: 0.45581618026955667 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039688510872899645, 'depth': 6, 'l2_leaf_reg': 5.099113810219792, 'random_strength': 0.009181969852355254, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.833903649877709}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:16:24,872] Trial 12 finished with value: 0.45771981402559914 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18096761375717862, 'depth': 6, 'l2_leaf_reg': 3.975114748255217, 'random_strength': 0.028693101195908906, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.870940447219903}. Best is trial 4 with value: 0.45927502283171656.
[I 2026-04-15 22:16:29,692] Trial 13 finished with value: 0.4639018086870103 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16670569716980282, 'depth': 5, 'l2_leaf_reg': 2.620090560440639, 'random_strength': 0.0037720293037742936, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.8653475007457172}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:34,441] Trial 14 finished with value: 0.45448567391942685 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1300874690951754, 'depth': 5, 'l2_leaf_reg': 2.257313132718344, 'random_strength': 0.1688936484673199, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9748236988951016}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:39,076] Trial 15 finished with value: 0.46353001987592735 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1239026629506878, 'depth': 5, 'l2_leaf_reg': 1.0071882758063284, 'random_strength': 0.31206105154509634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7749871487988538}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:43,890] Trial 16 finished with value: 0.4472242307986206 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12108666640421716, 'depth': 5, 'l2_leaf_reg': 1.2846500142154254, 'random_strength': 0.3137992692687554, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8937719218565839}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:48,135] Trial 17 finished with value: 0.43321932193035106 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.13539265699233594, 'depth': 5, 'l2_leaf_reg': 2.662362735660741, 'random_strength': 0.4799271423408365, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8162483296787814}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:50,929] Trial 18 finished with value: 0.45471545513381856 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10203610453810633, 'depth': 4, 'l2_leaf_reg': 2.881829461452535, 'random_strength': 0.24697728749479825, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.7645456325443565}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:54,969] Trial 19 finished with value: 0.4507968731686381 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15360967997703137, 'depth': 5, 'l2_leaf_reg': 1.0431711469541898, 'random_strength': 0.4122971633258843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8702668376114777}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:16:58,796] Trial 20 finished with value: 0.4454700588169158 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10703009378318894, 'depth': 4, 'l2_leaf_reg': 3.3087001901349935, 'random_strength': 0.5768270915340084, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9983102891728626}. Best is trial 13 with value: 0.4639018086870103.
[I 2026-04-15 22:17:03,640] Trial 21 finished with value: 0.4647139297539706 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18722110879072262, 'depth': 5, 'l2_leaf_reg': 1.500402773571507, 'random_strength': 0.11294926863183517, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7222029963023738}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:08,260] Trial 22 finished with value: 0.454631557384031 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1986500868605524, 'depth': 5, 'l2_leaf_reg': 1.4130503287724903, 'random_strength': 0.09120130561842338, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.698748896369546}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:12,975] Trial 23 finished with value: 0.449416268403094 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14373350686385342, 'depth': 5, 'l2_leaf_reg': 1.2636955824707263, 'random_strength': 0.2137910872687585, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.6091939622990619}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:16,597] Trial 24 finished with value: 0.4512279709676056 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15662339594840094, 'depth': 4, 'l2_leaf_reg': 2.3824742923266418, 'random_strength': 0.10483082630505443, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7926388468297152}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:21,460] Trial 25 finished with value: 0.4531148503428224 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05829916383468929, 'depth': 5, 'l2_leaf_reg': 1.9571949252374385, 'random_strength': 0.23993672090416535, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8390781370200497}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:28,427] Trial 26 finished with value: 0.4605511229557138 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11508780853372258, 'depth': 6, 'l2_leaf_reg': 1.3506833700781025, 'random_strength': 0.3607099525190214, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.2578643405925001}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:35,266] Trial 27 finished with value: 0.4463403966355697 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15799190820645195, 'depth': 6, 'l2_leaf_reg': 1.608815916296475, 'random_strength': 0.010326882922194525, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7090926452858933}. Best is trial 21 with value: 0.4647139297539706.
[I 2026-04-15 22:17:40,045] Trial 28 finished with value: 0.47754384166808367 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1955351635760887, 'depth': 5, 'l2_leaf_reg': 3.322086026767902, 'random_strength': 0.13996143324324323, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7358064801390373}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:17:43,903] Trial 29 finished with value: 0.41706667904555306 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19528664142977667, 'depth': 4, 'l2_leaf_reg': 5.905949838898528, 'random_strength': 0.13407785596086386, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.682610778645282}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:17:47,529] Trial 30 finished with value: 0.4376544137443168 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09152208576731441, 'depth': 4, 'l2_leaf_reg': 3.357545599420781, 'random_strength': 0.07671241970873162, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7336985816547222}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:17:52,258] Trial 31 finished with value: 0.46073174646864 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1628151557525332, 'depth': 5, 'l2_leaf_reg': 1.967713404290251, 'random_strength': 0.17813678238725061, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6524329936641386}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:17:57,115] Trial 32 finished with value: 0.4604445086181963 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1325914901866085, 'depth': 5, 'l2_leaf_reg': 3.335480012185806, 'random_strength': 0.278721520761854, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7922623723635095}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:00,748] Trial 33 finished with value: 0.44492419896680285 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16713002848788422, 'depth': 4, 'l2_leaf_reg': 1.149041464524067, 'random_strength': 0.15988991665230357, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7277201076655215}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:05,598] Trial 34 finished with value: 0.45377028744239495 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1988089431200569, 'depth': 5, 'l2_leaf_reg': 6.313119891555885, 'random_strength': 0.2002446155747437, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.6674571313099292}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:10,303] Trial 35 finished with value: 0.4456309236729849 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032067311498450116, 'depth': 5, 'l2_leaf_reg': 2.1925381202831997, 'random_strength': 0.35321943567171366, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7912739908663046}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:17,390] Trial 36 finished with value: 0.44973253739528635 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06050151686076975, 'depth': 6, 'l2_leaf_reg': 1.5584359335569202, 'random_strength': 0.06605427617927143, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.76933759135313}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:24,407] Trial 37 finished with value: 0.45680926551286527 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11771775804610904, 'depth': 6, 'l2_leaf_reg': 2.5060757482846276, 'random_strength': 0.13470898459797997, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.9111372334333256}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:35,983] Trial 38 finished with value: 0.4603347455317982 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13427648809111872, 'depth': 7, 'l2_leaf_reg': 2.8692615519149394, 'random_strength': 0.0467685493002387, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.12221043743904225}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:39,912] Trial 39 finished with value: 0.4483192819806163 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06992107212211822, 'depth': 4, 'l2_leaf_reg': 8.612780840739351, 'random_strength': 0.5636043431146442, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'subsample': 0.844418957661561}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:47,432] Trial 40 finished with value: 0.4421123273318953 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08699117658544306, 'depth': 6, 'l2_leaf_reg': 3.8745670217494896, 'random_strength': 0.4296713155530345, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.4532051511681003}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:52,099] Trial 41 finished with value: 0.4725285006979628 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17217476502520698, 'depth': 5, 'l2_leaf_reg': 1.883189969619925, 'random_strength': 0.19413709790846126, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.654524093944025}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:18:56,747] Trial 42 finished with value: 0.4457498154100523 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17683577082812155, 'depth': 5, 'l2_leaf_reg': 2.0152412964024324, 'random_strength': 0.11930665695110794, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6830519096034556}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:19:01,625] Trial 43 finished with value: 0.45989804275491103 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1526567587478759, 'depth': 5, 'l2_leaf_reg': 1.7783751621809551, 'random_strength': 0.2618956523277753, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.6099481156493649}. Best is trial 28 with value: 0.47754384166808367.
[I 2026-04-15 22:19:06,528] Trial 44 finished with value: 0.4620612893201811 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17990378043226554, 'depth': 5, 'l2_leaf_reg': 1.5168410187685029, 'random_strength': 0.32455977599405866, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7131758799196177}. Best is trial 28 with value: 0.47754384166808367.

                                    feature  importance
520                          stat__umap_050    0.063219
476                          stat__umap_006    0.056929
477                          stat__umap_007    0.043735
62   eye__sac_speed_AOI_aggregated_Pos_mean    0.042267
517                          stat__umap_047    0.036710
487                          stat__umap_017    0.033539
518                          stat__umap_048    0.032870
483                          stat__umap_013    0.032735
26               eye__sac_angle_between_std    0.032662
564                          stat__umap_094    0.026466
551                          stat__umap_081    0.026246
187       eye__fix_duration_AOI_FD_None_max    0.026134
465                           eye__imf0_max    0.022464
173                   eye__fix_duration_sum    0.022366
208      eye__fix_duration_AOI_FD_Pos1_mean    0.019799
516                          stat__umap_046    0.019720
550                          stat__umap_080    0.019282
569                          stat__umap_099    0.018586
345           eye__sample_entropy_m=4_r=400    0.018240
525                          stat__umap_055    0.017763
524                          stat__umap_054    0.017592
295                    eye__fuzzy_m_2_r_200    0.017580
480                          stat__umap_010    0.017574
559                          stat__umap_089    0.017386
365              eye__fractal_dim_m_2_tau_1    0.017286
534                          stat__umap_064    0.016999
497                          stat__umap_027    0.016350
473                          stat__umap_003    0.015621
13                  eye__sac_speed_kurtosis    0.015548
33   eye__sac_length_AOI_aggregated_Neg_std    0.014789

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.44991
              precision    recall  f1-score   support

           0       0.68      0.95      0.79       227
           1       0.37      0.06      0.11       109

    accuracy                           0.66       336
   macro avg       0.52      0.51      0.45       336
weighted avg       0.58      0.66      0.57       336

Confusion matrix:
 [[215  12]
 [102   7]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch__problem=binary__feat=all_features+stat__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                         feature  importance
525                               stat__umap_055    5.460309
544                               stat__umap_074    4.972506
477                               stat__umap_007    4.643773
205          eye__fix_duration_AOI_FD_Pos1_first    4.447286
521                               stat__umap_051    3.891794
277     eye__fix_duration_AOI_aggregated_Pos_max    2.938715
471                               stat__umap_001    2.873043
213            eye__fix_duration_AOI_FD_Pos1_sum    2.779027
558                               stat__umap_088    2.618161
516                               stat__umap_046    2.452129
279  eye__fix_duration_AOI_aggregated_Pos_median    2.163203
502                               stat__umap_032    2.062898
505                               stat__umap_035    1.996795
542                               stat__umap_072    1.887810
472                               stat__umap_002    1.879292
464                                eye__imf0_min    1.875082
513                               stat__umap_043    1.847296
520                               stat__umap_050    1.794016
508                               stat__umap_038    1.787554
547                               stat__umap_077    1.637332
555                               stat__umap_085    1.511125
3                         eye__sac_length_median    1.484591
478                               stat__umap_008    1.472319
206            eye__fix_duration_AOI_FD_Pos1_min    1.441203
56     eye__sac_length_AOI_aggregated_Pos_median    1.401895
495                               stat__umap_025    1.325727
554                               stat__umap_084    1.264770
26                    eye__sac_angle_between_std    1.247442
270    eye__fix_duration_AOI_aggregated_None_std    1.208467
168                       eye__fix_duration_mean    1.200031

================================================================================
Skipping existing experiment: exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST
[stat] rows missing after index match -> train: 1658, test: 160
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 22:21:24,487] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch__problem=multiclass__feat=all_features+stat__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 22:21:31,309] Trial 0 finished with value: 0.5278189666129759 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:21:38,586] Trial 1 finished with value: 0.5153974024204823 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:21:46,261] Trial 2 finished with value: 0.5250217761376262 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:21:53,261] Trial 3 finished with value: 0.5254660174242328 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:21:59,559] Trial 4 finished with value: 0.5145710947673658 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:22:09,122] Trial 5 finished with value: 0.5117547175362571 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 0 with value: 0.5278189666129759.
[I 2026-04-15 22:22:14,444] Trial 6 finished with value: 0.539932401590196 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:22:25,195] Trial 7 finished with value: 0.5049864606096637 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:22:31,588] Trial 8 finished with value: 0.5331426016338783 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:22:43,527] Trial 9 finished with value: 0.5149559730320785 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:22:49,156] Trial 10 finished with value: 0.5305792857135788 and parameters: {'learning_rate': 0.18766497951716743, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.7247992174446418, 'colsample_bytree': 0.857465440887474, 'gamma': 1.4666973037439077, 'reg_alpha': 0.00034551764945249807, 'reg_lambda': 8.128245614093935}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:22:57,030] Trial 11 finished with value: 0.5131510113428299 and parameters: {'learning_rate': 0.12339330697838734, 'max_depth': 4, 'min_child_weight': 2.141849215303333, 'subsample': 0.8211964516617682, 'colsample_bytree': 0.8784655823343067, 'gamma': 1.2615827674464564, 'reg_alpha': 9.16157529770763, 'reg_lambda': 0.00013386192543122697}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:23:03,160] Trial 12 finished with value: 0.5097297496258716 and parameters: {'learning_rate': 0.11905828681188078, 'max_depth': 7, 'min_child_weight': 2.158609633387336, 'subsample': 0.7452386219369388, 'colsample_bytree': 0.8942426617557693, 'gamma': 1.912091861487041, 'reg_alpha': 0.009648903671603344, 'reg_lambda': 0.0057996628441294}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:23:09,339] Trial 13 finished with value: 0.5140923793348318 and parameters: {'learning_rate': 0.1395445738342445, 'max_depth': 4, 'min_child_weight': 5.32911732339547, 'subsample': 0.8389531725758507, 'colsample_bytree': 0.9953328592284332, 'gamma': 1.3012629299990455, 'reg_alpha': 0.003159705858480362, 'reg_lambda': 0.8313811955700386}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:23:18,103] Trial 14 finished with value: 0.5399279739967697 and parameters: {'learning_rate': 0.0769608000493544, 'max_depth': 7, 'min_child_weight': 2.538570219904526, 'subsample': 0.7003884052701798, 'colsample_bytree': 0.8174182786587119, 'gamma': 0.762482860020731, 'reg_alpha': 1.4388846773732515, 'reg_lambda': 0.0001149404517214395}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:23:28,723] Trial 15 finished with value: 0.512680955027754 and parameters: {'learning_rate': 0.07110493189253295, 'max_depth': 8, 'min_child_weight': 2.6074738589707267, 'subsample': 0.700717276709995, 'colsample_bytree': 0.8108543741131289, 'gamma': 0.684152480075638, 'reg_alpha': 0.05025080765504081, 'reg_lambda': 0.0001206957062179857}. Best is trial 6 with value: 0.539932401590196.
[I 2026-04-15 22:23:37,425] Trial 16 finished with value: 0.5557226151174767 and parameters: {'learning_rate': 0.08502001198905001, 'max_depth': 7, 'min_child_weight': 6.098806807282297, 'subsample': 0.7446246655636095, 'colsample_bytree': 0.8136626354725327, 'gamma': 0.4547004750001311, 'reg_alpha': 0.9081504040194485, 'reg_lambda': 0.36194010266714643}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:23:44,788] Trial 17 finished with value: 0.5200651702611826 and parameters: {'learning_rate': 0.16354935624983347, 'max_depth': 5, 'min_child_weight': 6.9717096557836955, 'subsample': 0.750718973432724, 'colsample_bytree': 0.833222568445511, 'gamma': 0.34943470304298285, 'reg_alpha': 0.00010798658012149677, 'reg_lambda': 0.33583402330971174}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:23:50,393] Trial 18 finished with value: 0.5231833258865728 and parameters: {'learning_rate': 0.09330137070176413, 'max_depth': 3, 'min_child_weight': 9.437067520151778, 'subsample': 0.9211124710016527, 'colsample_bytree': 0.8868948588223814, 'gamma': 1.6578121497744966, 'reg_alpha': 0.02158528759865327, 'reg_lambda': 1.9253855625275396}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:00,205] Trial 19 finished with value: 0.5289296947821353 and parameters: {'learning_rate': 0.05000525014409872, 'max_depth': 7, 'min_child_weight': 7.030268851240765, 'subsample': 0.8229466296473977, 'colsample_bytree': 0.7832779407298713, 'gamma': 0.9171262370469488, 'reg_alpha': 0.5974912510135608, 'reg_lambda': 0.2028286802625633}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:09,471] Trial 20 finished with value: 0.5175023127945535 and parameters: {'learning_rate': 0.09794913268106452, 'max_depth': 8, 'min_child_weight': 4.444094431055928, 'subsample': 0.8664465043311603, 'colsample_bytree': 0.8528813698260476, 'gamma': 0.504639066194593, 'reg_alpha': 0.0016525042611136116, 'reg_lambda': 0.012990779275666834}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:17,520] Trial 21 finished with value: 0.5080844630952068 and parameters: {'learning_rate': 0.0710477193130518, 'max_depth': 7, 'min_child_weight': 7.131742700783314, 'subsample': 0.7365331332462244, 'colsample_bytree': 0.8236979463098082, 'gamma': 0.7784291749337856, 'reg_alpha': 7.011388471581676, 'reg_lambda': 0.0216262259602837}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:28,496] Trial 22 finished with value: 0.5252498041825009 and parameters: {'learning_rate': 0.061307472835649426, 'max_depth': 7, 'min_child_weight': 4.043721964376532, 'subsample': 0.7029731632232117, 'colsample_bytree': 0.7003025488728253, 'gamma': 0.41231879700895296, 'reg_alpha': 1.4838465696154295, 'reg_lambda': 1.2843895121000328}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:37,163] Trial 23 finished with value: 0.5188306377211785 and parameters: {'learning_rate': 0.08506155753781036, 'max_depth': 5, 'min_child_weight': 5.486783737451253, 'subsample': 0.7612626565861186, 'colsample_bytree': 0.9023242543144618, 'gamma': 0.6352893738691254, 'reg_alpha': 0.0760399149297615, 'reg_lambda': 6.504725337855871}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:47,029] Trial 24 finished with value: 0.5100843206962471 and parameters: {'learning_rate': 0.04081423385668021, 'max_depth': 6, 'min_child_weight': 2.8607670606754, 'subsample': 0.8049158161788651, 'colsample_bytree': 0.8032578791616165, 'gamma': 0.8954921347254543, 'reg_alpha': 0.732207792452028, 'reg_lambda': 0.334403682118992}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:24:52,609] Trial 25 finished with value: 0.5221100941414266 and parameters: {'learning_rate': 0.13795447675596198, 'max_depth': 8, 'min_child_weight': 7.758275304192676, 'subsample': 0.7289442719859409, 'colsample_bytree': 0.8427005060279542, 'gamma': 1.2054603053267499, 'reg_alpha': 3.128259887648442, 'reg_lambda': 0.00034443938512887187}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:01,778] Trial 26 finished with value: 0.5536488832832839 and parameters: {'learning_rate': 0.06266102303727544, 'max_depth': 7, 'min_child_weight': 5.81866298490907, 'subsample': 0.7599091319966401, 'colsample_bytree': 0.9125472352699092, 'gamma': 0.21223872338090677, 'reg_alpha': 0.1657924447547112, 'reg_lambda': 0.09421884413766399}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:11,195] Trial 27 finished with value: 0.5281445659350228 and parameters: {'learning_rate': 0.06375454098950903, 'max_depth': 6, 'min_child_weight': 5.993905865246571, 'subsample': 0.7618226428701382, 'colsample_bytree': 0.9148564350193288, 'gamma': 0.062038540962042255, 'reg_alpha': 0.15430160205829124, 'reg_lambda': 0.14178082489131547}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:20,565] Trial 28 finished with value: 0.5142312683445072 and parameters: {'learning_rate': 0.024006283214162163, 'max_depth': 5, 'min_child_weight': 9.815147127156202, 'subsample': 0.8088438067387685, 'colsample_bytree': 0.8643336587225768, 'gamma': 0.19696197046215497, 'reg_alpha': 0.03175663256017887, 'reg_lambda': 0.03176720034272318}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:27,792] Trial 29 finished with value: 0.5355552756395182 and parameters: {'learning_rate': 0.19915345754132346, 'max_depth': 4, 'min_child_weight': 4.7339814692432025, 'subsample': 0.7196179367490124, 'colsample_bytree': 0.771229102546878, 'gamma': 0.27205874974515065, 'reg_alpha': 0.349945117458121, 'reg_lambda': 4.8653525928123535}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:35,554] Trial 30 finished with value: 0.5180340923740068 and parameters: {'learning_rate': 0.05724418418922279, 'max_depth': 4, 'min_child_weight': 3.6341373309578513, 'subsample': 0.7497617666707884, 'colsample_bytree': 0.9201965693410064, 'gamma': 0.43608734717208125, 'reg_alpha': 0.010359517424654326, 'reg_lambda': 2.9906164981120984}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:47,107] Trial 31 finished with value: 0.5281828569135926 and parameters: {'learning_rate': 0.04572618327648617, 'max_depth': 7, 'min_child_weight': 3.2704821341526094, 'subsample': 0.7134611943631547, 'colsample_bytree': 0.8209974926575127, 'gamma': 0.5680156888658818, 'reg_alpha': 0.780299515821967, 'reg_lambda': 0.6001412333138312}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:25:57,510] Trial 32 finished with value: 0.52439518306391 and parameters: {'learning_rate': 0.07354610821624814, 'max_depth': 7, 'min_child_weight': 2.525358677524814, 'subsample': 0.7329436294925963, 'colsample_bytree': 0.8722382443279704, 'gamma': 0.2838842512319345, 'reg_alpha': 3.182102684204706, 'reg_lambda': 0.06132614280613821}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:08,536] Trial 33 finished with value: 0.524831216089791 and parameters: {'learning_rate': 0.04048023700870204, 'max_depth': 8, 'min_child_weight': 6.112345622975207, 'subsample': 0.7656389321327816, 'colsample_bytree': 0.841778592561408, 'gamma': 0.7149796250916397, 'reg_alpha': 1.3754548247158631, 'reg_lambda': 0.0035923213095200852}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:19,163] Trial 34 finished with value: 0.5277978531616897 and parameters: {'learning_rate': 0.10139763141625639, 'max_depth': 8, 'min_child_weight': 8.10868447769638, 'subsample': 0.7170712126847174, 'colsample_bytree': 0.9610301104587525, 'gamma': 0.011916381358366646, 'reg_alpha': 0.09835188544740942, 'reg_lambda': 0.2514740308474202}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:25,969] Trial 35 finished with value: 0.5166013616992425 and parameters: {'learning_rate': 0.08448681154206797, 'max_depth': 7, 'min_child_weight': 3.8591247727515356, 'subsample': 0.7743555990149208, 'colsample_bytree': 0.7910430557057415, 'gamma': 1.4457120947886504, 'reg_alpha': 0.39441709162513017, 'reg_lambda': 0.09518211571476133}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:33,773] Trial 36 finished with value: 0.5218496862052608 and parameters: {'learning_rate': 0.15490087506713238, 'max_depth': 6, 'min_child_weight': 4.962375712100585, 'subsample': 0.7443690879880418, 'colsample_bytree': 0.9093901178510172, 'gamma': 0.48584644254043363, 'reg_alpha': 0.04627798289876159, 'reg_lambda': 0.5625695164693647}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:41,955] Trial 37 finished with value: 0.537955979809918 and parameters: {'learning_rate': 0.10748291512916353, 'max_depth': 5, 'min_child_weight': 6.406956470349021, 'subsample': 0.7002998264340431, 'colsample_bytree': 0.8081214724109311, 'gamma': 0.1657338363328758, 'reg_alpha': 4.7652531458545155, 'reg_lambda': 0.04426204509261672}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:50,767] Trial 38 finished with value: 0.5085981111743256 and parameters: {'learning_rate': 0.03078297711781988, 'max_depth': 7, 'min_child_weight': 1.7581538419093217, 'subsample': 0.7773896451204679, 'colsample_bytree': 0.7647576355122898, 'gamma': 1.9967325376063068, 'reg_alpha': 0.224450270099774, 'reg_lambda': 0.000773126477533916}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:26:57,860] Trial 39 finished with value: 0.5197273189450251 and parameters: {'learning_rate': 0.06495801184668813, 'max_depth': 6, 'min_child_weight': 7.838735952267295, 'subsample': 0.9971657244931591, 'colsample_bytree': 0.9281548645243509, 'gamma': 0.9620833532821518, 'reg_alpha': 0.015072692334905435, 'reg_lambda': 1.2554322204950144}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:04,150] Trial 40 finished with value: 0.4963053059124971 and parameters: {'learning_rate': 0.05347495618719025, 'max_depth': 8, 'min_child_weight': 1.3630647761264083, 'subsample': 0.8806305088866302, 'colsample_bytree': 0.8817294719869149, 'gamma': 1.7511341972310097, 'reg_alpha': 1.5294715501543994, 'reg_lambda': 0.019333295396081748}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:12,728] Trial 41 finished with value: 0.5434253089605972 and parameters: {'learning_rate': 0.08326174423479003, 'max_depth': 5, 'min_child_weight': 6.393392355661882, 'subsample': 0.7061964854451654, 'colsample_bytree': 0.8071830440059986, 'gamma': 0.15060213894217273, 'reg_alpha': 6.010256480942131, 'reg_lambda': 0.03667132144606723}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:21,201] Trial 42 finished with value: 0.5373934204876443 and parameters: {'learning_rate': 0.07993478900226807, 'max_depth': 5, 'min_child_weight': 8.59391591367563, 'subsample': 0.7188870747053309, 'colsample_bytree': 0.7794288835951115, 'gamma': 0.11828681987590678, 'reg_alpha': 0.9500684256416182, 'reg_lambda': 0.13871853085945668}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:29,338] Trial 43 finished with value: 0.5061364369842287 and parameters: {'learning_rate': 0.08877693200717594, 'max_depth': 5, 'min_child_weight': 5.195925663409944, 'subsample': 0.7574677988504848, 'colsample_bytree': 0.8282566004224481, 'gamma': 0.22098507917769158, 'reg_alpha': 4.92785816877256, 'reg_lambda': 0.03832684853931652}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:37,190] Trial 44 finished with value: 0.503845638919883 and parameters: {'learning_rate': 0.10927419851484416, 'max_depth': 6, 'min_child_weight': 6.951299115302035, 'subsample': 0.7970446872131419, 'colsample_bytree': 0.8018026167584528, 'gamma': 0.3517446265927378, 'reg_alpha': 2.43175296668483, 'reg_lambda': 0.004474826397777142}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:46,038] Trial 45 finished with value: 0.5217438736805144 and parameters: {'learning_rate': 0.07095906319984602, 'max_depth': 6, 'min_child_weight': 5.885095083031212, 'subsample': 0.7360446603310447, 'colsample_bytree': 0.8683606789592011, 'gamma': 0.8138340634537324, 'reg_alpha': 0.4596126585465058, 'reg_lambda': 0.010478373160422149}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:52,413] Trial 46 finished with value: 0.5189108706502116 and parameters: {'learning_rate': 0.13738402343372322, 'max_depth': 4, 'min_child_weight': 2.197355304433547, 'subsample': 0.7103053278278572, 'colsample_bytree': 0.7451527158884894, 'gamma': 1.0508994211878697, 'reg_alpha': 0.17656820442654056, 'reg_lambda': 0.08577245857534604}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:27:58,491] Trial 47 finished with value: 0.5014731124153259 and parameters: {'learning_rate': 0.0579171556245216, 'max_depth': 5, 'min_child_weight': 4.223622856025668, 'subsample': 0.9290624612419202, 'colsample_bytree': 0.8501033916903782, 'gamma': 0.5553714069138195, 'reg_alpha': 9.735090925581614, 'reg_lambda': 0.4148528492014256}. Best is trial 16 with value: 0.5557226151174767.
[I 2026-04-15 22:28:09,127] Trial 48 finished with value: 0.5129136346216956 and parameters: {'learning_rate': 0.07683812384025919, 'max_depth': 7, 'min_child_weight': 9.041418639113672, 'subsample': 0.7307612311558545, 'colsample_bytree': 0.9538993994008745, 'gamma': 0.08290002137556839, 'reg_alpha': 4.5159321205056315, 'reg_lambda': 0.2285384274162168}. Best is trial 16 with value: 0.5557226151174767.

[I 2026-04-15 22:34:24,385] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 22:34:29,363] Trial 0 finished with value: 0.47922600365100176 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.47922600365100176.
[I 2026-04-15 22:34:35,653] Trial 1 finished with value: 0.48857210843805043 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.48857210843805043.
[I 2026-04-15 22:34:47,909] Trial 2 finished with value: 0.5094845431449679 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:35:08,112] Trial 3 finished with value: 0.47626095311074845 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:35:47,423] Trial 4 finished with value: 0.49762045003628397 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:36:28,414] Trial 5 finished with value: 0.4973777207111961 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:36:52,168] Trial 6 finished with value: 0.4998104053246324 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:37:08,269] Trial 7 finished with value: 0.47769310122034686 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:38:10,211] Trial 8 finished with value: 0.49859261800305554 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:38:32,296] Trial 9 finished with value: 0.4851107923198419 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:38:39,750] Trial 10 finished with value: 0.505110756218752 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.040269472988759346, 'depth': 5, 'l2_leaf_reg': 5.1892447574518465, 'random_strength': 0.402192133386275, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9290346996252341}. Best is trial 2 with value: 0.5094845431449679.
[I 2026-04-15 22:38:47,534] Trial 11 finished with value: 0.5116470674313003 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.039688510872899645, 'depth': 5, 'l2_leaf_reg': 5.365538882909708, 'random_strength': 0.4258355123760916, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9494635180573001}. Best is trial 11 with value: 0.5116470674313003.
[I 2026-04-15 22:38:56,286] Trial 12 finished with value: 0.48501637802029945 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03251444710110255, 'depth': 5, 'l2_leaf_reg': 6.949461600155238, 'random_strength': 0.9991606541036766, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8769747357034408}. Best is trial 11 with value: 0.5116470674313003.
[I 2026-04-15 22:39:03,256] Trial 13 finished with value: 0.5240453433155147 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.050542481439380664, 'depth': 5, 'l2_leaf_reg': 2.8824168632634826, 'random_strength': 0.31869584453654215, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9981635950986539}. Best is trial 13 with value: 0.5240453433155147.
[I 2026-04-15 22:39:10,266] Trial 14 finished with value: 0.480771232821244 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05398665603897518, 'depth': 5, 'l2_leaf_reg': 2.73070238175551, 'random_strength': 0.5677421943270291, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9937770364486957}. Best is trial 13 with value: 0.5240453433155147.
[I 2026-04-15 22:39:17,250] Trial 15 finished with value: 0.5124408683628813 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11744433554515392, 'depth': 5, 'l2_leaf_reg': 2.8844930217360134, 'random_strength': 0.26246148668228464, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.9836930935808665}. Best is trial 13 with value: 0.5240453433155147.
[I 2026-04-15 22:39:21,869] Trial 16 finished with value: 0.510662857156144 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12769952952541253, 'depth': 4, 'l2_leaf_reg': 2.8218139867298184, 'random_strength': 0.2401452891916075, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8552831364350295}. Best is trial 13 with value: 0.5240453433155147.
[I 2026-04-15 22:39:32,882] Trial 17 finished with value: 0.5287471994850196 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14084946141083501, 'depth': 6, 'l2_leaf_reg': 2.9203977962363554, 'random_strength': 0.28056032990898183, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9905062814711142}. Best is trial 17 with value: 0.5287471994850196.
[I 2026-04-15 22:39:43,785] Trial 18 finished with value: 0.5352901903149685 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19970555820191693, 'depth': 6, 'l2_leaf_reg': 1.7209605016239704, 'random_strength': 0.05342085262572388, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8605881010594605}. Best is trial 18 with value: 0.5352901903149685.
[I 2026-04-15 22:39:54,927] Trial 19 finished with value: 0.48416758997407866 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19869667635280852, 'depth': 6, 'l2_leaf_reg': 1.0431711469541898, 'random_strength': 0.02168205363963461, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8405984150760577}. Best is trial 18 with value: 0.5352901903149685.
[I 2026-04-15 22:40:14,328] Trial 20 finished with value: 0.5145985093826362 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14827144329187528, 'depth': 7, 'l2_leaf_reg': 2.10327174265179, 'random_strength': 0.09853403407341324, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9144187895195209}. Best is trial 18 with value: 0.5352901903149685.
[I 2026-04-15 22:40:25,727] Trial 21 finished with value: 0.540432566542649 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1587155623263993, 'depth': 6, 'l2_leaf_reg': 1.391107891936582, 'random_strength': 0.17943599187788942, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9988302880607687}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:40:36,557] Trial 22 finished with value: 0.512337102412739 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16033119814992391, 'depth': 6, 'l2_leaf_reg': 1.4765341937623395, 'random_strength': 0.0010084962427513444, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9045296300642661}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:40:47,384] Trial 23 finished with value: 0.49222243695172746 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11018759994785463, 'depth': 6, 'l2_leaf_reg': 1.3779602156154476, 'random_strength': 0.20146346207523438, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.8211894303344343}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:41:07,326] Trial 24 finished with value: 0.5011282632048054 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1470116674162838, 'depth': 7, 'l2_leaf_reg': 2.1593235430988282, 'random_strength': 0.13420986632452686, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9536936137751271}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:41:18,458] Trial 25 finished with value: 0.5072388070930003 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19845586361919906, 'depth': 6, 'l2_leaf_reg': 3.6442131827163133, 'random_strength': 0.07030945573305093, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8870479673256282}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:41:29,786] Trial 26 finished with value: 0.5224144888296192 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.130088020119806, 'depth': 6, 'l2_leaf_reg': 1.379042258631206, 'random_strength': 0.5273563599463302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.2578643405925001}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:41:49,668] Trial 27 finished with value: 0.5057679308252765 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10066809050238769, 'depth': 7, 'l2_leaf_reg': 1.785965532156924, 'random_strength': 0.22023559274806942, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.958676088673954}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:01,118] Trial 28 finished with value: 0.4977164264881847 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1639280479211134, 'depth': 6, 'l2_leaf_reg': 2.1700898641855693, 'random_strength': 0.3645571522826789, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7836733373263609}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:13,808] Trial 29 finished with value: 0.50239473977744 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.059466403331839356, 'depth': 6, 'l2_leaf_reg': 1.1995307164044227, 'random_strength': 0.14619619142114398, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.682610778645282}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:20,512] Trial 30 finished with value: 0.5243583195210959 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14106549628635248, 'depth': 5, 'l2_leaf_reg': 3.69919382209412, 'random_strength': 0.1611965821103578, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9538943527595121}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:24,936] Trial 31 finished with value: 0.52208574458954 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1378147779882243, 'depth': 4, 'l2_leaf_reg': 3.740223540957959, 'random_strength': 0.13539337761458006, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9641443711739687}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:31,484] Trial 32 finished with value: 0.5046192038862338 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17454582175932523, 'depth': 5, 'l2_leaf_reg': 2.4199487851673966, 'random_strength': 0.19691508083803816, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9295718681130014}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:35,840] Trial 33 finished with value: 0.4895294144281509 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09155586353587712, 'depth': 4, 'l2_leaf_reg': 1.711810769864183, 'random_strength': 0.06507041441585266, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9968250704557682}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:47,721] Trial 34 finished with value: 0.5218897144137051 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11454863231237558, 'depth': 6, 'l2_leaf_reg': 3.399988599661921, 'random_strength': 0.2877891286571602, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9658736365304418}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:42:54,410] Trial 35 finished with value: 0.5084804757914422 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17691133625585045, 'depth': 5, 'l2_leaf_reg': 1.981460766462703, 'random_strength': 0.16082059774872098, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.8739401864365863}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:43:14,428] Trial 36 finished with value: 0.5051424630610482 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15257628733133233, 'depth': 7, 'l2_leaf_reg': 1.2242053119337013, 'random_strength': 0.34272480037854497, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9226322517211356}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:43:25,732] Trial 37 finished with value: 0.5017790020244521 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06935325932977954, 'depth': 6, 'l2_leaf_reg': 2.494350616832291, 'random_strength': 0.03684731868310004, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.944439022327033}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:43:32,536] Trial 38 finished with value: 0.5152174278239524 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.08900884802051168, 'depth': 5, 'l2_leaf_reg': 1.6434023252593484, 'random_strength': 0.1176065322044406, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.12221043743904225}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:43:37,276] Trial 39 finished with value: 0.5186790547144345 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1971575504585232, 'depth': 4, 'l2_leaf_reg': 6.679130640048444, 'random_strength': 0.18590143457047364, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9760700825563173}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:43:57,914] Trial 40 finished with value: 0.49596901100894075 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.12731509915681785, 'depth': 7, 'l2_leaf_reg': 3.249781786823145, 'random_strength': 0.2551267960781406, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.4532051511681003}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:44:04,814] Trial 41 finished with value: 0.49837215655001144 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06558401132441743, 'depth': 5, 'l2_leaf_reg': 4.234459776486467, 'random_strength': 0.34989579911406354, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9982182709978896}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:44:12,136] Trial 42 finished with value: 0.5093812421239161 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04706121890747946, 'depth': 5, 'l2_leaf_reg': 5.267081011976017, 'random_strength': 0.30533622401524046, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.9989254511625467}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:44:24,620] Trial 43 finished with value: 0.5049520442353034 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032204325515053776, 'depth': 6, 'l2_leaf_reg': 4.317480865401942, 'random_strength': 0.45040113332643394, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.9700004081580144}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:44:31,319] Trial 44 finished with value: 0.5194502891222643 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.10626991133958834, 'depth': 5, 'l2_leaf_reg': 19.592769665417347, 'random_strength': 0.3100892930773712, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.9030145372783749}. Best is trial 21 with value: 0.540432566542649.
[I 2026-04-15 22:44:43,197] Trial 45 finished with value: 0.5090199190785379 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05597673751127566, 'depth': 6, 'l2_leaf_reg': 3.167524249335022, 'random_strength': 0.09648883321576895, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7442588652303395}. Best is trial 21 with value: 0.540432566542649.

                                    feature  importance
213       eye__fix_duration_AOI_FD_Pos1_sum   23.951234
208      eye__fix_duration_AOI_FD_Pos1_mean   17.870101
394      eye__det_euclidean_length_1_rho_25   16.173911
473                          stat__umap_003    8.940361
557                          stat__umap_087    7.874614
494                          stat__umap_024    6.099125
490                          stat__umap_020    5.695356
540                          stat__umap_070    4.113581
489                          stat__umap_019    3.855545
159                     eye__reg_speed_mean    2.989756
518                          stat__umap_048    2.436417
22               eye__sac_angle_between_min    0.000000
23               eye__sac_angle_between_max    0.000000
24              eye__sac_angle_between_mean    0.000000
25            eye__sac_angle_between_median    0.000000
513                          stat__umap_043    0.000000
57   eye__sac_length_AOI_aggregated_Pos_std    0.000000
545                          stat__umap_075    0.000000
537                          stat__umap_067    0.000000
33   eye__sac_length_AOI_aggregated_Neg_std    0.000000
569                          stat__umap_099    0.000000
0                       eye__sac_length_min    0.000000
1                       eye__sac_length_max    0.000000
2                      eye__sac_length_mean    0.000000
3                    eye__sac_length_median    0.000000
4                       eye__sac_length_std    0.000000
5                       eye__sac_length_sum    0.000000
6                  eye__sac_length_kurtosis    0.000000
7                      eye__sac_length_skew    0.000000
26               eye__sac_angle_between_std    0.000000

================================================================================
Skipping existing experiment: exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST
[stat] rows missing after index match -> train: 1658, test: 160
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 22:48:13,144] A new study created in memory with name: binary_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 22:48:18,414] Trial 0 finished with value: 0.5093184169503049 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.5093184169503049.
[I 2026-04-15 22:48:23,293] Trial 1 finished with value: 0.4738828476585356 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.5093184169503049.
[I 2026-04-15 22:48:28,989] Trial 2 finished with value: 0.4975511387373168 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.5093184169503049.
[I 2026-04-15 22:48:34,552] Trial 3 finished with value: 0.5130087033361732 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.5130087033361732.
[I 2026-04-15 22:48:40,464] Trial 4 finished with value: 0.5003162513691086 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.5130087033361732.
[I 2026-04-15 22:48:46,984] Trial 5 finished with value: 0.5180366548758104 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:48:52,013] Trial 6 finished with value: 0.5055247925797863 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:48:59,982] Trial 7 finished with value: 0.5063535785244713 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:49:05,566] Trial 8 finished with value: 0.4677718093816215 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:49:14,779] Trial 9 finished with value: 0.4664294964372312 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:49:20,360] Trial 10 finished with value: 0.47136360504102204 and parameters: {'learning_rate': 0.053574840865446394, 'max_depth': 3, 'min_child_weight': 1.0155291768008887, 'subsample': 0.9948638614233253, 'colsample_bytree': 0.8365039320348027, 'gamma': 1.3709161615904817, 'reg_alpha': 0.0003269908763524355, 'reg_lambda': 0.00839106795699683}. Best is trial 5 with value: 0.5180366548758104.
[I 2026-04-15 22:49:26,170] Trial 11 finished with value: 0.5218452446359287 and parameters: {'learning_rate': 0.0862754992306428, 'max_depth': 4, 'min_child_weight': 5.262425700550083, 'subsample': 0.893839626256697, 'colsample_bytree': 0.8707153554142966, 'gamma': 0.5892553864010996, 'reg_alpha': 0.012651599006804258, 'reg_lambda': 0.00013386192543122697}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:49:31,197] Trial 12 finished with value: 0.4873100980266412 and parameters: {'learning_rate': 0.06983074866808828, 'max_depth': 3, 'min_child_weight': 5.9752070205206556, 'subsample': 0.9212430234210502, 'colsample_bytree': 0.8602373376309449, 'gamma': 0.4440336518658533, 'reg_alpha': 0.008409942689392089, 'reg_lambda': 0.00028122977914576394}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:49:36,585] Trial 13 finished with value: 0.4920124421386445 and parameters: {'learning_rate': 0.11198932069742602, 'max_depth': 4, 'min_child_weight': 6.009433385249269, 'subsample': 0.9937787728865991, 'colsample_bytree': 0.7012088256639494, 'gamma': 0.05050170446433089, 'reg_alpha': 0.002773800315564188, 'reg_lambda': 0.00011358170529229651}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:49:42,732] Trial 14 finished with value: 0.5112862700841255 and parameters: {'learning_rate': 0.040383658844458395, 'max_depth': 4, 'min_child_weight': 9.603797240033792, 'subsample': 0.843949145174496, 'colsample_bytree': 0.8097524232703589, 'gamma': 0.7218831677473481, 'reg_alpha': 0.02177008901271327, 'reg_lambda': 0.005784301275421651}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:49:50,508] Trial 15 finished with value: 0.47322271923204534 and parameters: {'learning_rate': 0.05687319968364797, 'max_depth': 7, 'min_child_weight': 2.4370747834999373, 'subsample': 0.9520126624855079, 'colsample_bytree': 0.8895961609314555, 'gamma': 0.3009904672967907, 'reg_alpha': 0.0012547372494007612, 'reg_lambda': 0.010162408101986087}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:49:57,751] Trial 16 finished with value: 0.5139028806944779 and parameters: {'learning_rate': 0.0853168739589385, 'max_depth': 7, 'min_child_weight': 4.725860382448061, 'subsample': 0.845938676992285, 'colsample_bytree': 0.8136626354725327, 'gamma': 0.30031089858044413, 'reg_alpha': 0.00012251060359668995, 'reg_lambda': 9.968625683962115}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:50:05,451] Trial 17 finished with value: 0.47832410991647634 and parameters: {'learning_rate': 0.02300517827628486, 'max_depth': 4, 'min_child_weight': 7.024816684854098, 'subsample': 0.8931789925924474, 'colsample_bytree': 0.8911833935295822, 'gamma': 0.9341804995429147, 'reg_alpha': 0.051139630855816784, 'reg_lambda': 0.00029406177221515865}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:50:11,306] Trial 18 finished with value: 0.4585423148559945 and parameters: {'learning_rate': 0.13361669780940957, 'max_depth': 8, 'min_child_weight': 4.3831186698533955, 'subsample': 0.9563137840719209, 'colsample_bytree': 0.7680506539977247, 'gamma': 0.493699484889836, 'reg_alpha': 0.011818447127095977, 'reg_lambda': 0.01625548754291248}. Best is trial 11 with value: 0.5218452446359287.
[I 2026-04-15 22:50:16,748] Trial 19 finished with value: 0.5328784163212048 and parameters: {'learning_rate': 0.06716043490858357, 'max_depth': 3, 'min_child_weight': 7.061389388184088, 'subsample': 0.9240097848015859, 'colsample_bytree': 0.8456850223312827, 'gamma': 1.2943758710461541, 'reg_alpha': 0.5260813231920917, 'reg_lambda': 0.00010085499993559673}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:21,783] Trial 20 finished with value: 0.46787660787105323 and parameters: {'learning_rate': 0.06918985077065092, 'max_depth': 3, 'min_child_weight': 2.7402286143342476, 'subsample': 0.9207298960109805, 'colsample_bytree': 0.8466445670931371, 'gamma': 1.3156726914952745, 'reg_alpha': 0.7002432793304612, 'reg_lambda': 0.00014979337155117755}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:26,773] Trial 21 finished with value: 0.5094292675898605 and parameters: {'learning_rate': 0.05114565450564106, 'max_depth': 3, 'min_child_weight': 7.704835907154113, 'subsample': 0.9706931573584311, 'colsample_bytree': 0.9176581135794517, 'gamma': 1.26774744725873, 'reg_alpha': 6.510602308821657, 'reg_lambda': 0.0006856927219959023}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:32,473] Trial 22 finished with value: 0.472036269351253 and parameters: {'learning_rate': 0.06808908839867202, 'max_depth': 4, 'min_child_weight': 6.949253941772419, 'subsample': 0.9139169150232854, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.5994069338007728, 'reg_alpha': 0.002741098445445144, 'reg_lambda': 0.0028530072858489303}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:37,290] Trial 23 finished with value: 0.46342676752932066 and parameters: {'learning_rate': 0.09515226356727045, 'max_depth': 5, 'min_child_weight': 4.919120252733107, 'subsample': 0.8732521019633523, 'colsample_bytree': 0.8253282251586339, 'gamma': 0.7055626076297523, 'reg_alpha': 0.06513367175251855, 'reg_lambda': 0.00040335482827866877}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:42,456] Trial 24 finished with value: 0.4944705832033314 and parameters: {'learning_rate': 0.03584466130315171, 'max_depth': 3, 'min_child_weight': 5.469534515419367, 'subsample': 0.8319075029990273, 'colsample_bytree': 0.7754421148758146, 'gamma': 0.15726265469687586, 'reg_alpha': 0.016615877631711986, 'reg_lambda': 0.00010784231315464299}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:51,080] Trial 25 finished with value: 0.503340633676598 and parameters: {'learning_rate': 0.027709560077344986, 'max_depth': 6, 'min_child_weight': 7.568826374052203, 'subsample': 0.9353490969542783, 'colsample_bytree': 0.859326929187057, 'gamma': 0.9749804785625722, 'reg_alpha': 0.6974254663669006, 'reg_lambda': 0.004023240737178961}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:50:56,997] Trial 26 finished with value: 0.465326080397562 and parameters: {'learning_rate': 0.04564748302835156, 'max_depth': 4, 'min_child_weight': 3.7884659433866483, 'subsample': 0.9794350071088911, 'colsample_bytree': 0.970209042913855, 'gamma': 1.5081554840801978, 'reg_alpha': 0.09647689539774514, 'reg_lambda': 0.0008358318763432936}. Best is trial 19 with value: 0.5328784163212048.
[I 2026-04-15 22:51:03,382] Trial 27 finished with value: 0.5339019499340638 and parameters: {'learning_rate': 0.06237501836268466, 'max_depth': 5, 'min_child_weight': 9.609661796169744, 'subsample': 0.8940058872745171, 'colsample_bytree': 0.9144737415578947, 'gamma': 0.5058455033041347, 'reg_alpha': 4.821162575028007, 'reg_lambda': 0.01936652659582208}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:08,251] Trial 28 finished with value: 0.5100438176039911 and parameters: {'learning_rate': 0.14101981470638733, 'max_depth': 5, 'min_child_weight': 9.852627093884763, 'subsample': 0.8202303274092494, 'colsample_bytree': 0.9071730099080445, 'gamma': 0.8155349940602767, 'reg_alpha': 8.91317586861654, 'reg_lambda': 0.28910386218320955}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:13,547] Trial 29 finished with value: 0.49848203289656884 and parameters: {'learning_rate': 0.08194044450484951, 'max_depth': 4, 'min_child_weight': 6.9079413907975935, 'subsample': 0.8857282112970704, 'colsample_bytree': 0.8686643397369748, 'gamma': 0.5437090605056768, 'reg_alpha': 4.053999651466604, 'reg_lambda': 0.033041629411520106}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:19,584] Trial 30 finished with value: 0.5255798017466407 and parameters: {'learning_rate': 0.060241837680033605, 'max_depth': 4, 'min_child_weight': 3.86913686646003, 'subsample': 0.866286198650893, 'colsample_bytree': 0.9217138476007593, 'gamma': 1.1529499247077486, 'reg_alpha': 1.324852029687221, 'reg_lambda': 2.0105737617027115}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:25,578] Trial 31 finished with value: 0.4807825358370085 and parameters: {'learning_rate': 0.06378906817605891, 'max_depth': 4, 'min_child_weight': 3.6147425925570484, 'subsample': 0.8669313787133609, 'colsample_bytree': 0.9181266000680885, 'gamma': 1.1842156518582818, 'reg_alpha': 1.5637791531432323, 'reg_lambda': 3.2841213067929047}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:31,155] Trial 32 finished with value: 0.4912485306223398 and parameters: {'learning_rate': 0.04475057567368288, 'max_depth': 3, 'min_child_weight': 3.9002496541075784, 'subsample': 0.9050935762151926, 'colsample_bytree': 0.905709913797324, 'gamma': 1.4805106362688136, 'reg_alpha': 3.3879239126847565, 'reg_lambda': 1.397016212681904}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:37,989] Trial 33 finished with value: 0.46712190073294535 and parameters: {'learning_rate': 0.05977806483369986, 'max_depth': 5, 'min_child_weight': 2.910345290348873, 'subsample': 0.9305490300151547, 'colsample_bytree': 0.9852032227090469, 'gamma': 0.38891379668486803, 'reg_alpha': 0.7643857686619203, 'reg_lambda': 0.16965347563555622}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:43,118] Trial 34 finished with value: 0.46042971935585103 and parameters: {'learning_rate': 0.07654375646990852, 'max_depth': 4, 'min_child_weight': 2.2739786229370127, 'subsample': 0.8775499343729516, 'colsample_bytree': 0.9534576248534832, 'gamma': 0.816861594030918, 'reg_alpha': 2.0198690494968883, 'reg_lambda': 9.419866217971832}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:47,276] Trial 35 finished with value: 0.5090104874771767 and parameters: {'learning_rate': 0.09921542470551874, 'max_depth': 3, 'min_child_weight': 5.35753708809237, 'subsample': 0.8174430996099585, 'colsample_bytree': 0.878197225245026, 'gamma': 0.6491263357091972, 'reg_alpha': 0.24868759712058153, 'reg_lambda': 1.7823668665545231}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:52,630] Trial 36 finished with value: 0.4740644461434971 and parameters: {'learning_rate': 0.09112955012771541, 'max_depth': 5, 'min_child_weight': 7.8757686041231425, 'subsample': 0.8561770282868674, 'colsample_bytree': 0.9255595923642188, 'gamma': 0.9160911483717842, 'reg_alpha': 0.9077067052997777, 'reg_lambda': 0.02392811007761565}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:51:58,674] Trial 37 finished with value: 0.4727811803486485 and parameters: {'learning_rate': 0.061409512408948805, 'max_depth': 5, 'min_child_weight': 4.2094645936979855, 'subsample': 0.9426565929852313, 'colsample_bytree': 0.899961797632891, 'gamma': 1.1479630244268224, 'reg_alpha': 4.7652531458545155, 'reg_lambda': 0.0010947809329097567}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:52:04,737] Trial 38 finished with value: 0.4953374799156097 and parameters: {'learning_rate': 0.047330864666550905, 'max_depth': 4, 'min_child_weight': 6.603264303154726, 'subsample': 0.8984245226668873, 'colsample_bytree': 0.7915368729804593, 'gamma': 1.387609916981438, 'reg_alpha': 0.346564242970205, 'reg_lambda': 0.00020567902497701734}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:52:09,859] Trial 39 finished with value: 0.5207544982484859 and parameters: {'learning_rate': 0.07622491842126036, 'max_depth': 3, 'min_child_weight': 3.323108318079665, 'subsample': 0.8802111991897676, 'colsample_bytree': 0.843229501965383, 'gamma': 1.2196140548665035, 'reg_alpha': 2.74652421623767, 'reg_lambda': 0.000496303222222567}. Best is trial 27 with value: 0.5339019499340638.
[I 2026-04-15 22:52:16,212] Trial 40 finished with value: 0.5401770679112178 and parameters: {'learning_rate': 0.11019243319672105, 'max_depth': 4, 'min_child_weight': 5.154645793243162, 'subsample': 0.7282571436393164, 'colsample_bytree': 0.9516650851597603, 'gamma': 1.7511341972310097, 'reg_alpha': 1.140023002822655, 'reg_lambda': 0.6639025117560498}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:21,262] Trial 41 finished with value: 0.5008218155135173 and parameters: {'learning_rate': 0.11980642874348703, 'max_depth': 4, 'min_child_weight': 5.136612998468634, 'subsample': 0.7670519375284118, 'colsample_bytree': 0.9998910555029998, 'gamma': 1.7802713772449135, 'reg_alpha': 1.2934287899958519, 'reg_lambda': 0.7983330955678263}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:26,211] Trial 42 finished with value: 0.5151491103358201 and parameters: {'learning_rate': 0.18930441592459712, 'max_depth': 5, 'min_child_weight': 8.140827719253585, 'subsample': 0.7063521844150831, 'colsample_bytree': 0.947463630132383, 'gamma': 1.7249249742820658, 'reg_alpha': 0.4137779013740246, 'reg_lambda': 3.1058536693657186}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:31,016] Trial 43 finished with value: 0.5203655206463913 and parameters: {'learning_rate': 0.1464703288761579, 'max_depth': 4, 'min_child_weight': 5.984757415874021, 'subsample': 0.7402472173400247, 'colsample_bytree': 0.9589861891353739, 'gamma': 1.9439916744372123, 'reg_alpha': 0.14668834701526617, 'reg_lambda': 0.34934809854311843}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:35,526] Trial 44 finished with value: 0.46745667095187515 and parameters: {'learning_rate': 0.10211516878909413, 'max_depth': 3, 'min_child_weight': 8.780257751091339, 'subsample': 0.8580452577891823, 'colsample_bytree': 0.9314888140053647, 'gamma': 1.623837257243379, 'reg_alpha': 7.281344667462186, 'reg_lambda': 5.584170715572051}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:41,583] Trial 45 finished with value: 0.5189826486582912 and parameters: {'learning_rate': 0.07227270858088447, 'max_depth': 4, 'min_child_weight': 4.535937145061294, 'subsample': 0.7396989703433557, 'colsample_bytree': 0.8844872296809789, 'gamma': 1.0328405062674963, 'reg_alpha': 0.4628005483897851, 'reg_lambda': 0.09618826059577894}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:47,099] Trial 46 finished with value: 0.465934781680183 and parameters: {'learning_rate': 0.08694562979767717, 'max_depth': 5, 'min_child_weight': 6.526025152058815, 'subsample': 0.9130473269902177, 'colsample_bytree': 0.8674553585287559, 'gamma': 1.837797454069094, 'reg_alpha': 1.1500137041110567, 'reg_lambda': 0.9662066746612809}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:52,391] Trial 47 finished with value: 0.5053554603150039 and parameters: {'learning_rate': 0.10781622414139032, 'max_depth': 6, 'min_child_weight': 4.071085900787864, 'subsample': 0.809407277225346, 'colsample_bytree': 0.8275367002677138, 'gamma': 1.5041684073485024, 'reg_alpha': 2.179869069407203, 'reg_lambda': 0.38232213310928004}. Best is trial 40 with value: 0.5401770679112178.
[I 2026-04-15 22:52:58,777] Trial 48 finished with value: 0.47374052367068054 and parameters: {'learning_rate': 0.05467567160789259, 'max_depth': 4, 'min_child_weight': 5.733511884959791, 'subsample': 0.8908299896509159, 'colsample_bytree': 0.9611815450747571, 'gamma': 0.20482649336760367, 'reg_alpha': 0.00663388366222688, 'reg_lambda': 1.8546086701286593}. Best is trial 40 with value: 0.5401770679112178.

[I 2026-04-15 22:56:53,110] A new study created in memory with name: binary_catboost

[xgb] Test macro-F1: 0.41053
              precision    recall  f1-score   support

           0       0.70      1.00      0.82       234
           1       0.00      0.00      0.00       102

    accuracy                           0.70       336
   macro avg       0.35      0.50      0.41       336
weighted avg       0.49      0.70      0.57       336

Confusion matrix:
 [[234   0]
 [102   0]]

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 22:57:01,399] Trial 0 finished with value: 0.5662804737429885 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.5662804737429885.
[I 2026-04-15 22:57:19,249] Trial 1 finished with value: 0.5628847385908566 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 0 with value: 0.5662804737429885.
[I 2026-04-15 22:57:31,973] Trial 2 finished with value: 0.571807006355608 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 2 with value: 0.571807006355608.
[I 2026-04-15 22:58:05,650] Trial 3 finished with value: 0.5649602653222976 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 2 with value: 0.571807006355608.
[I 2026-04-15 22:58:27,668] Trial 4 finished with value: 0.564071298320375 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 2 with value: 0.571807006355608.
[I 2026-04-15 22:59:12,157] Trial 5 finished with value: 0.5718458304899121 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 5 with value: 0.5718458304899121.
[I 2026-04-15 22:59:43,751] Trial 6 finished with value: 0.5577323556086797 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 5 with value: 0.5718458304899121.
[I 2026-04-15 23:00:18,526] Trial 7 finished with value: 0.553808715968003 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 5 with value: 0.5718458304899121.
[I 2026-04-15 23:01:56,070] Trial 8 finished with value: 0.5682304816025538 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 5 with value: 0.5718458304899121.
[I 2026-04-15 23:02:14,913] Trial 9 finished with value: 0.5746819378399868 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:02:20,787] Trial 10 finished with value: 0.5522629507031265 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15550029108275915, 'depth': 5, 'l2_leaf_reg': 1.2809979042149076, 'random_strength': 0.9947887102560302, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.9526058892396143}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:02:35,304] Trial 11 finished with value: 0.5631381728866803 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11440146940676205, 'depth': 7, 'l2_leaf_reg': 2.742987236870024, 'random_strength': 0.9064945863745015, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.12665706747865135}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:04:17,787] Trial 12 finished with value: 0.5690613206201045 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04998551125540691, 'depth': 8, 'l2_leaf_reg': 4.100313566450956, 'random_strength': 0.7772595956734192, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8961594169517826}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:04:33,210] Trial 13 finished with value: 0.5653573291278939 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.11898154973533921, 'depth': 7, 'l2_leaf_reg': 1.0238446469613984, 'random_strength': 0.8156671077112546, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.6792923137266189}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:05:00,137] Trial 14 finished with value: 0.5664313330550355 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.032189307821966336, 'depth': 6, 'l2_leaf_reg': 5.074742486962073, 'random_strength': 0.6272330422168962, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.606285613613393}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:05:33,968] Trial 15 finished with value: 0.5661115539817213 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06198333778793942, 'depth': 8, 'l2_leaf_reg': 2.6568334541509646, 'random_strength': 0.7601734526910771, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.5090916719722371}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:05:53,563] Trial 16 finished with value: 0.5741708402184957 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0940460617910006, 'depth': 7, 'l2_leaf_reg': 2.2807868820414248, 'random_strength': 0.9870761342433301, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.4439866348375925}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:06:02,141] Trial 17 finished with value: 0.5596254339340863 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1296076371180265, 'depth': 6, 'l2_leaf_reg': 2.2491568629305903, 'random_strength': 0.9962098892690202, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6139089554995273}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:06:12,036] Trial 18 finished with value: 0.5717973228979341 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.05667426255176448, 'depth': 5, 'l2_leaf_reg': 1.4078460751151975, 'random_strength': 0.8983064530916779, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 4.284517710941218}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:06:35,029] Trial 19 finished with value: 0.5651631941710615 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.037166449902837344, 'depth': 7, 'l2_leaf_reg': 1.0431711469541898, 'random_strength': 0.5198504622145179, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.864570349188645}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:06:52,910] Trial 20 finished with value: 0.5615372886970904 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.09768257524170247, 'depth': 7, 'l2_leaf_reg': 3.1410534373893713, 'random_strength': 0.8946470316245522, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8290562500466551}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:08:28,893] Trial 21 finished with value: 0.5659406765405846 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07986243892172552, 'depth': 8, 'l2_leaf_reg': 6.218378960062811, 'random_strength': 0.7300873584639261, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'bagging_temperature': 1.3813853373226277}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:08:48,124] Trial 22 finished with value: 0.5668347421158406 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.09192345019447731, 'depth': 7, 'l2_leaf_reg': 3.3837673452854147, 'random_strength': 0.8468790143117622, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 1.721572505732469}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:10:38,141] Trial 23 finished with value: 0.5649873453350472 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07116270371656437, 'depth': 8, 'l2_leaf_reg': 2.0374424781308926, 'random_strength': 0.9444245207610357, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 2.052503972868977}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:10:52,673] Trial 24 finished with value: 0.5743364017916466 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.13779738961806276, 'depth': 7, 'l2_leaf_reg': 6.138843366574976, 'random_strength': 0.5516934984923189, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.8159395793304558}. Best is trial 9 with value: 0.5746819378399868.
[I 2026-04-15 23:10:59,106] Trial 25 finished with value: 0.5887539359446178 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1978574236710984, 'depth': 5, 'l2_leaf_reg': 6.859815797012152, 'random_strength': 0.561995003338989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7163645842120283}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:04,583] Trial 26 finished with value: 0.5682335560369032 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.18408503262403944, 'depth': 5, 'l2_leaf_reg': 6.817008013022632, 'random_strength': 0.5237727413584929, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.20804943923300878}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:09,627] Trial 27 finished with value: 0.5641994013359816 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.14754690919303176, 'depth': 5, 'l2_leaf_reg': 8.793400170113596, 'random_strength': 0.4681901007696785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7569297555813881}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:18,640] Trial 28 finished with value: 0.5741787435074981 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16439362557217638, 'depth': 6, 'l2_leaf_reg': 6.204867473634264, 'random_strength': 0.4013545643729506, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.671622942619512}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:23,134] Trial 29 finished with value: 0.5423840717105057 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19537951767742687, 'depth': 4, 'l2_leaf_reg': 11.091456469923664, 'random_strength': 0.5874440235504843, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'bagging_temperature': 3.4508923671465133}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:27,111] Trial 30 finished with value: 0.5568192809520447 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.1365554016314927, 'depth': 4, 'l2_leaf_reg': 5.206034156563591, 'random_strength': 0.325404116256493, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 0.7498849090795263}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:37,060] Trial 31 finished with value: 0.565505788881421 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16118207502507137, 'depth': 6, 'l2_leaf_reg': 6.220871672245975, 'random_strength': 0.40608666459132214, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6641658103603222}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:43,192] Trial 32 finished with value: 0.5859513564772845 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.16547357430697746, 'depth': 5, 'l2_leaf_reg': 8.052689085144975, 'random_strength': 0.22775517160367398, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6614656800862186}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:50,022] Trial 33 finished with value: 0.556204260895089 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.1133175289722824, 'depth': 5, 'l2_leaf_reg': 12.532332793977409, 'random_strength': 0.22387737470290953, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7552137488515859}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:53,951] Trial 34 finished with value: 0.5772453365994622 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19904310502920364, 'depth': 4, 'l2_leaf_reg': 8.305407320310794, 'random_strength': 0.09075069888034099, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6327981553857482}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:11:57,728] Trial 35 finished with value: 0.5776011935172837 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19531218495497735, 'depth': 4, 'l2_leaf_reg': 8.297599736474998, 'random_strength': 0.06444324129424173, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6384185828051118}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:12:01,586] Trial 36 finished with value: 0.5703156631973436 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.18962838341155488, 'depth': 4, 'l2_leaf_reg': 8.677254139546331, 'random_strength': 0.009506386377809664, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.7212920574493731}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:12:05,980] Trial 37 finished with value: 0.5591529160140198 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.167303972980893, 'depth': 4, 'l2_leaf_reg': 18.475375083313914, 'random_strength': 0.12364403203602692, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6035615052851848}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:12:09,855] Trial 38 finished with value: 0.5505350066690737 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19551171333858394, 'depth': 4, 'l2_leaf_reg': 7.566280934935893, 'random_strength': 0.2145201417265732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.6548372059635253}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:12:15,032] Trial 39 finished with value: 0.5515278047288985 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17057993581499414, 'depth': 5, 'l2_leaf_reg': 14.069949680287985, 'random_strength': 0.10096451550260635, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7965754476903585}. Best is trial 25 with value: 0.5887539359446178.
[I 2026-04-15 23:12:18,917] Trial 40 finished with value: 0.5969978238073944 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.14965749861451616, 'depth': 4, 'l2_leaf_reg': 10.06795044277389, 'random_strength': 0.008709619055765783, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6403347098437049}. Best is trial 40 with value: 0.5969978238073944.
[I 2026-04-15 23:12:22,502] Trial 41 finished with value: 0.5533664216852738 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.15167925463689486, 'depth': 4, 'l2_leaf_reg': 9.474442733798165, 'random_strength': 0.004113680877660296, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6373803442460334}. Best is trial 40 with value: 0.5969978238073944.
[I 2026-04-15 23:12:25,973] Trial 42 finished with value: 0.5623742077764505 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.19844403979701145, 'depth': 4, 'l2_leaf_reg': 11.12982339379207, 'random_strength': 0.0608732753517238, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6948761783072619}. Best is trial 40 with value: 0.5969978238073944.
[I 2026-04-15 23:12:29,370] Trial 43 finished with value: 0.5691454405307677 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17589600516467696, 'depth': 4, 'l2_leaf_reg': 7.9269584495949434, 'random_strength': 0.22396269976735828, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.6456460099739724}. Best is trial 40 with value: 0.5969978238073944.
[I 2026-04-15 23:12:34,513] Trial 44 finished with value: 0.5721781208064545 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.12238230666162798, 'depth': 5, 'l2_leaf_reg': 13.606262321101763, 'random_strength': 0.17546978259832985, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.7176895837987861}. Best is trial 40 with value: 0.5969978238073944.

                                       feature  importance
276   eye__fix_duration_AOI_aggregated_Pos_min    0.261598
53      eye__sac_length_AOI_aggregated_Pos_min    0.199560
520                             stat__umap_050    0.104314
518                             stat__umap_048    0.073923
183          eye__fix_duration_AOI_FD_Neg1_sum    0.064289
569                             stat__umap_099    0.063677
32   eye__sac_length_AOI_aggregated_Neg_median    0.060008
553                             stat__umap_083    0.054100
374               eye__corr_dim_m_2_tau_2_r_50    0.037855
544                             stat__umap_074    0.034530
499                             stat__umap_029    0.020555
494                             stat__umap_024    0.013197
498                             stat__umap_028    0.012395
22                  eye__sac_angle_between_min    0.000000
23                  eye__sac_angle_between_max    0.000000
24                 eye__sac_angle_between_mean    0.000000
25               eye__sac_angle_between_median    0.000000
513                             stat__umap_043    0.000000
57      eye__sac_length_AOI_aggregated_Pos_std    0.000000
545                             stat__umap_075    0.000000
537                             stat__umap_067    0.000000
33      eye__sac_length_AOI_aggregated_Neg_std    0.000000
0                          eye__sac_length_min    0.000000
1                          eye__sac_length_max    0.000000
2                         eye__sac_length_mean    0.000000
3                       eye__sac_length_median    0.000000
4                          eye__sac_length_std    0.000000
5                          eye__sac_length_sum    0.000000
6                     eye__sac_length_kurtosis    0.000000
7                         eye__sac_length_skew    0.000000

=== Refit CATBOOST with saved best params ===

[catboost] Test macro-F1: 0.55372
              precision    recall  f1-score   support

           0       0.73      0.89      0.80       234
           1       0.48      0.23      0.31       102

    accuracy                           0.69       336
   macro avg       0.60      0.56      0.55       336
weighted avg       0.65      0.69      0.65       336

Confusion matrix:
 [[209  25]
 [ 79  23]]
Saved feature importances: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\feature_importances_eye_ftar\exp__X_name=screen+stat__target=match_mismatch_general__problem=binary__feat=all_features+stat__ES__refitTEST__no_neutral__catboost.csv
Top 30 features for CATBOOST:

                                               feature  importance
60               eye__sac_speed_AOI_aggregated_Pos_min   26.785404
507                                     stat__umap_037   10.313941
480                                     stat__umap_010    4.454962
279        eye__fix_duration_AOI_aggregated_Pos_median    4.065283
542                                     stat__umap_072    3.748388
183                  eye__fix_duration_AOI_FD_Neg1_sum    3.499988
518                                     stat__umap_048    2.997661
503                                     stat__umap_033    2.940729
464                                      eye__imf0_min    2.884340
53              eye__sac_length_AOI_aggregated_Pos_min    2.540504
557                                     stat__umap_087    2.406560
56           eye__sac_length_AOI_aggregated_Pos_median    2.279074
540                                     stat__umap_070    2.165030
32           eye__sac_length_AOI_aggregated_Neg_median    2.119635
465                                      eye__imf0_max    2.021403
563                                     stat__umap_093    1.895267
521                                     stat__umap_051    1.809757
55             eye__sac_length_AOI_aggregated_Pos_mean    1.743637
553                                     stat__umap_083    1.650513
474                                     stat__umap_004    1.482762
258          eye__fix_duration_AOI_aggregated_Neg_mean    1.422776
333                      eye__sample_entropy_m=2_r=100    1.420178
335                      eye__sample_entropy_m=2_r=400    1.384153
483                                     stat__umap_013    1.346377
511                                     stat__umap_041    1.343057
356               eye__lyapunov_exponent_m_3_tau_2_T_1    1.214154
179               eye__fix_duration_AOI_FD_Neg1_median    1.121469
487                                     stat__umap_017    0.943100
394                 eye__det_euclidean_length_1_rho_25    0.879366
89   eye__sac_length_from_Pos_to_Target_from_Pos_to...    0.872477

================================================================================
Skipping existing experiment: exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST
[stat] rows missing after index match -> train: 1658, test: 160
[stat] UMAP compression: train/test features 8235 -> 100

c:\Users\LEGION\miniconda3\envs\table_methods\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(
[I 2026-04-15 23:14:32,856] A new study created in memory with name: multiclass_xgb

================================================================================
Running: exp__X_name=screen+stat__target=match_mismatch_general__problem=multiclass__feat=all_features+stat__ES__refitTEST__no_neutral
X_train: (3016, 570), X_test: (336, 570)

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-04-15 23:14:39,831] Trial 0 finished with value: 0.6335231401118657 and parameters: {'learning_rate': 0.04534239315199742, 'max_depth': 4, 'min_child_weight': 3.6133378418934727, 'subsample': 0.7172121707956832, 'colsample_bytree': 0.7642269046455532, 'gamma': 0.2930268354654828, 'reg_alpha': 0.0005749550436838274, 'reg_lambda': 2.9181778067053106}. Best is trial 0 with value: 0.6335231401118657.
[I 2026-04-15 23:14:46,743] Trial 1 finished with value: 0.5904082540554374 and parameters: {'learning_rate': 0.1707594054749505, 'max_depth': 8, 'min_child_weight': 1.8407677988385938, 'subsample': 0.9514458866935752, 'colsample_bytree': 0.7320289895353271, 'gamma': 0.030927525032881986, 'reg_alpha': 2.3384483013779853, 'reg_lambda': 0.0007548524119611296}. Best is trial 0 with value: 0.6335231401118657.
[I 2026-04-15 23:14:56,025] Trial 2 finished with value: 0.6321484171287657 and parameters: {'learning_rate': 0.0333616681035175, 'max_depth': 5, 'min_child_weight': 1.3687627858565237, 'subsample': 0.7729441794314539, 'colsample_bytree': 0.7929937842534774, 'gamma': 1.660443067751983, 'reg_alpha': 0.005206283604457903, 'reg_lambda': 0.048491021513312554}. Best is trial 0 with value: 0.6335231401118657.
[I 2026-04-15 23:15:03,579] Trial 3 finished with value: 0.6344671241523491 and parameters: {'learning_rate': 0.09682808232572594, 'max_depth': 5, 'min_child_weight': 4.396257072995133, 'subsample': 0.8647426591908396, 'colsample_bytree': 0.9365018559965254, 'gamma': 0.81847464877263, 'reg_alpha': 0.3776934848037953, 'reg_lambda': 0.6036578421550512}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:10,472] Trial 4 finished with value: 0.6255336814732251 and parameters: {'learning_rate': 0.07947711612968353, 'max_depth': 7, 'min_child_weight': 5.931203450567599, 'subsample': 0.8982687541415775, 'colsample_bytree': 0.9379105369910391, 'gamma': 1.8319746898789904, 'reg_alpha': 0.17136302676182727, 'reg_lambda': 0.0015254608266614567}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:20,691] Trial 5 finished with value: 0.6130502453376458 and parameters: {'learning_rate': 0.052924627979311564, 'max_depth': 6, 'min_child_weight': 8.988540550355523, 'subsample': 0.9734090828573316, 'colsample_bytree': 0.7482522636195154, 'gamma': 0.14566720014922496, 'reg_alpha': 0.02288299663390803, 'reg_lambda': 0.008397536831549925}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:26,054] Trial 6 finished with value: 0.6199724825026378 and parameters: {'learning_rate': 0.17193943391258518, 'max_depth': 5, 'min_child_weight': 9.058532530510401, 'subsample': 0.741043947428219, 'colsample_bytree': 0.8813281338011174, 'gamma': 1.919407758835323, 'reg_alpha': 0.02691311205056786, 'reg_lambda': 0.6116057984930577}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:37,491] Trial 7 finished with value: 0.6289685444202382 and parameters: {'learning_rate': 0.03343607084946427, 'max_depth': 6, 'min_child_weight': 8.53858134948892, 'subsample': 0.7901637300699476, 'colsample_bytree': 0.9706012436601046, 'gamma': 1.0802957747332012, 'reg_alpha': 0.23583332496680523, 'reg_lambda': 0.12925751194525387}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:44,078] Trial 8 finished with value: 0.6207718211121536 and parameters: {'learning_rate': 0.11776571038558667, 'max_depth': 6, 'min_child_weight': 1.6356850192005823, 'subsample': 0.7836726194461838, 'colsample_bytree': 0.9416238883410388, 'gamma': 1.1030228579956167, 'reg_alpha': 1.492039624585635, 'reg_lambda': 0.0017236198656601991}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:15:58,874] Trial 9 finished with value: 0.6315150049258693 and parameters: {'learning_rate': 0.021001223201279434, 'max_depth': 6, 'min_child_weight': 3.206813667671944, 'subsample': 0.7881737543608885, 'colsample_bytree': 0.7424547380314808, 'gamma': 0.5940923936128994, 'reg_alpha': 0.09675777070062458, 'reg_lambda': 0.07330033701760204}. Best is trial 3 with value: 0.6344671241523491.
[I 2026-04-15 23:16:08,400] Trial 10 finished with value: 0.6376970039538365 and parameters: {'learning_rate': 0.08757688804274504, 'max_depth': 3, 'min_child_weight': 4.926890130404868, 'subsample': 0.8636522230468259, 'colsample_bytree': 0.8646722768462439, 'gamma': 1.411720649791067, 'reg_alpha': 9.265570153067632, 'reg_lambda': 8.122224546810095}. Best is trial 10 with value: 0.6376970039538365.
[I 2026-04-15 23:16:15,704] Trial 11 finished with value: 0.6382572689591797 and parameters: {'learning_rate': 0.0862754992306428, 'max_depth': 3, 'min_child_weight': 4.928424312424371, 'subsample': 0.8622852909563201, 'colsample_bytree': 0.8639556069094153, 'gamma': 1.2957804292612796, 'reg_alpha': 9.52866280527941, 'reg_lambda': 5.975817202898658}. Best is trial 11 with value: 0.6382572689591797.
[I 2026-04-15 23:16:25,146] Trial 12 finished with value: 0.6429873646374198 and parameters: {'learning_rate': 0.07313057902644354, 'max_depth': 3, 'min_child_weight': 5.2632762903781405, 'subsample': 0.8533111603054561, 'colsample_bytree': 0.845235942520865, 'gamma': 1.4498559141176184, 'reg_alpha': 9.356833111719883, 'reg_lambda': 8.615067167390345}. Best is trial 12 with value: 0.6429873646374198.
[I 2026-04-15 23:16:33,272] Trial 13 finished with value: 0.6325780564408996 and parameters: {'learning_rate': 0.06492294965644875, 'max_depth': 3, 'min_child_weight': 2.145123124916511, 'subsample': 0.9136920654097946, 'colsample_bytree': 0.8176955515976587, 'gamma': 1.4030051519904494, 'reg_alpha': 8.457871731466039, 'reg_lambda': 9.723756468311608}. Best is trial 12 with value: 0.6429873646374198.
[I 2026-04-15 23:16:38,534] Trial 14 finished with value: 0.6258221768495879 and parameters: {'learning_rate': 0.12900808294784968, 'max_depth': 4, 'min_child_weight': 5.972219673487665, 'subsample': 0.8250091618240228, 'colsample_bytree': 0.8881699126650688, 'gamma': 1.4705148990600059, 'reg_alpha': 1.4388846773732515, 'reg_lambda': 1.186069177689351}. Best is trial 12 with value: 0.6429873646374198.
[I 2026-04-15 23:16:45,009] Trial 15 finished with value: 0.616922617231318 and parameters: {'learning_rate': 0.06483410659075636, 'max_depth': 3, 'min_child_weight': 2.4370747834999373, 'subsample': 0.8375460781488447, 'colsample_bytree': 0.8279431186491103, 'gamma': 1.2513887824418548, 'reg_alpha': 0.0003362014187651234, 'reg_lambda': 0.00016599250040776937}. Best is trial 12 with value: 0.6429873646374198.
[I 2026-04-15 23:16:51,828] Trial 16 finished with value: 0.631980473538357 and parameters: {'learning_rate': 0.12345957554158152, 'max_depth': 4, 'min_child_weight': 6.098806807282297, 'subsample': 0.9027095858716521, 'colsample_bytree': 0.8968973468136499, 'gamma': 0.7552852538767579, 'reg_alpha': 0.0043466878579049295, 'reg_lambda': 0.21568760088362365}. Best is trial 12 with value: 0.6429873646374198.
[I 2026-04-15 23:16:59,398] Trial 17 finished with value: 0.6469065808812013 and parameters: {'learning_rate': 0.04339805738694319, 'max_depth': 3, 'min_child_weight': 4.2538784311888875, 'subsample': 0.9345993170135337, 'colsample_bytree': 0.8334694686086871, 'gamma': 1.6373335275931558, 'reg_alpha': 3.4450630323844456, 'reg_lambda': 2.5310996823984957}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:07,234] Trial 18 finished with value: 0.6338958251133204 and parameters: {'learning_rate': 0.03881131495184731, 'max_depth': 4, 'min_child_weight': 2.5039829421275557, 'subsample': 0.9376343737313951, 'colsample_bytree': 0.793326557295932, 'gamma': 1.626531029175154, 'reg_alpha': 0.6970550979386677, 'reg_lambda': 0.011397783591272139}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:18,376] Trial 19 finished with value: 0.6449792075977829 and parameters: {'learning_rate': 0.025083437492149144, 'max_depth': 3, 'min_child_weight': 3.809233688634627, 'subsample': 0.9568554910337991, 'colsample_bytree': 0.8320483297268331, 'gamma': 1.6948479167771318, 'reg_alpha': 2.7879126125749165, 'reg_lambda': 1.892885864526953}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:26,904] Trial 20 finished with value: 0.6178942355684252 and parameters: {'learning_rate': 0.03075841927855508, 'max_depth': 4, 'min_child_weight': 3.6228412753315604, 'subsample': 0.9980261580375686, 'colsample_bytree': 0.7882293720083653, 'gamma': 1.7310890674995647, 'reg_alpha': 0.061868306037098995, 'reg_lambda': 1.2912395231475258}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:37,159] Trial 21 finished with value: 0.6463500908474715 and parameters: {'learning_rate': 0.020636513396096054, 'max_depth': 3, 'min_child_weight': 4.097008476076435, 'subsample': 0.9357046690663077, 'colsample_bytree': 0.834639662254313, 'gamma': 1.938443122903397, 'reg_alpha': 4.053346763817064, 'reg_lambda': 2.3103353352519114}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:47,408] Trial 22 finished with value: 0.6371785415865101 and parameters: {'learning_rate': 0.020941946504209254, 'max_depth': 3, 'min_child_weight': 1.0411844002676933, 'subsample': 0.9417741914751723, 'colsample_bytree': 0.7003025488728253, 'gamma': 1.9827641605771762, 'reg_alpha': 2.5972298395797493, 'reg_lambda': 0.34654012852924526}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:17:56,739] Trial 23 finished with value: 0.6293127617359024 and parameters: {'learning_rate': 0.026200565694058684, 'max_depth': 4, 'min_child_weight': 4.171451535589099, 'subsample': 0.9654474340426159, 'colsample_bytree': 0.8259944347986997, 'gamma': 1.7918360845946688, 'reg_alpha': 0.6620631867349566, 'reg_lambda': 2.213335815177025}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:18:05,955] Trial 24 finished with value: 0.632093735146223 and parameters: {'learning_rate': 0.028527670150757505, 'max_depth': 3, 'min_child_weight': 2.8607670606754, 'subsample': 0.9933471127726692, 'colsample_bytree': 0.8442742792290308, 'gamma': 1.5968046283026516, 'reg_alpha': 3.2721716427059535, 'reg_lambda': 3.0364750738054096}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:18:16,204] Trial 25 finished with value: 0.636097996141535 and parameters: {'learning_rate': 0.023942635354104642, 'max_depth': 4, 'min_child_weight': 3.780351154787026, 'subsample': 0.921409824242835, 'colsample_bytree': 0.9117844501763885, 'gamma': 1.980344780545534, 'reg_alpha': 0.7729774165324371, 'reg_lambda': 0.7272795791606014}. Best is trial 17 with value: 0.6469065808812013.
[I 2026-04-15 23:18:23,531] Trial 26 finished with value: 0.6487281238369439 and parameters: {'learning_rate': 0.040175975180750945, 'max_depth': 3, 'min_child_weight': 7.041301149996665, 'subsample': 0.8976819604566662, 'colsample_bytree': 0.8072009229292966, 'gamma': 1.7980050083264616, 'reg_alpha': 0.00010170183971949589, 'reg_lambda': 2.6433519285135962}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:18:31,703] Trial 27 finished with value: 0.6326313108094147 and parameters: {'learning_rate': 0.051330002519974154, 'max_depth': 8, 'min_child_weight': 6.99477812843529, 'subsample': 0.8791572451498362, 'colsample_bytree': 0.807377580196461, 'gamma': 1.8411668972051312, 'reg_alpha': 0.00010841852240555758, 'reg_lambda': 0.018623870394863126}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:18:39,981] Trial 28 finished with value: 0.6330288140055667 and parameters: {'learning_rate': 0.04462931653709854, 'max_depth': 5, 'min_child_weight': 6.754775118070535, 'subsample': 0.8886321358683172, 'colsample_bytree': 0.7644464826364104, 'gamma': 1.5705899833745987, 'reg_alpha': 0.003824632296020421, 'reg_lambda': 0.28910386218320955}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:18:48,893] Trial 29 finished with value: 0.6355490179069716 and parameters: {'learning_rate': 0.03766750811248539, 'max_depth': 4, 'min_child_weight': 7.584880119774541, 'subsample': 0.923359926213851, 'colsample_bytree': 0.7803332936028062, 'gamma': 0.38883452453921374, 'reg_alpha': 0.00047130060461607917, 'reg_lambda': 2.574845264360704}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:18:57,948] Trial 30 finished with value: 0.5957382522641682 and parameters: {'learning_rate': 0.051442616620291225, 'max_depth': 7, 'min_child_weight': 3.227456312517323, 'subsample': 0.980062953219214, 'colsample_bytree': 0.8635492829931792, 'gamma': 1.2370019069315308, 'reg_alpha': 0.010359517424654326, 'reg_lambda': 3.8719776140021014}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:06,702] Trial 31 finished with value: 0.6363427894355476 and parameters: {'learning_rate': 0.025464569692969417, 'max_depth': 3, 'min_child_weight': 4.201556932358043, 'subsample': 0.9567137039944535, 'colsample_bytree': 0.8323471274399092, 'gamma': 1.7222953734874433, 'reg_alpha': 0.0015304489202607014, 'reg_lambda': 1.6450329059364075}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:16,200] Trial 32 finished with value: 0.6427368082242233 and parameters: {'learning_rate': 0.039053576781094286, 'max_depth': 3, 'min_child_weight': 2.880610663290158, 'subsample': 0.9351416892402981, 'colsample_bytree': 0.8084207263727557, 'gamma': 1.5493738684684668, 'reg_alpha': 4.556785573846336, 'reg_lambda': 3.823306174825022}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:25,878] Trial 33 finished with value: 0.644110767707697 and parameters: {'learning_rate': 0.022833017173608867, 'max_depth': 3, 'min_child_weight': 5.281764190658211, 'subsample': 0.9118012207172859, 'colsample_bytree': 0.7668875918380216, 'gamma': 1.864803377616973, 'reg_alpha': 1.4569612018970501, 'reg_lambda': 0.9720534616622194}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:34,450] Trial 34 finished with value: 0.6337595912284943 and parameters: {'learning_rate': 0.029036298467730405, 'max_depth': 4, 'min_child_weight': 4.44542191382614, 'subsample': 0.9531682615833933, 'colsample_bytree': 0.8460009611207868, 'gamma': 1.6814808259941956, 'reg_alpha': 4.316751793697554, 'reg_lambda': 0.44115854935792786}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:41,274] Trial 35 finished with value: 0.6418778054356861 and parameters: {'learning_rate': 0.04531304562372113, 'max_depth': 3, 'min_child_weight': 3.9135941477072116, 'subsample': 0.8833686523447721, 'colsample_bytree': 0.8112465354365526, 'gamma': 1.7328301037884535, 'reg_alpha': 0.00012115697212277958, 'reg_lambda': 0.06829321627138647}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:48,092] Trial 36 finished with value: 0.6308007889416736 and parameters: {'learning_rate': 0.03575792258889261, 'max_depth': 4, 'min_child_weight': 9.999978053662037, 'subsample': 0.9803388001484654, 'colsample_bytree': 0.7922368958888468, 'gamma': 1.993277016437442, 'reg_alpha': 0.3206236148169948, 'reg_lambda': 0.18395169111744}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:19:57,062] Trial 37 finished with value: 0.6383818160893475 and parameters: {'learning_rate': 0.031186567829902586, 'max_depth': 3, 'min_child_weight': 4.540654868732579, 'subsample': 0.9432993924418345, 'colsample_bytree': 0.8725804212740953, 'gamma': 0.9055694078056846, 'reg_alpha': 0.10572730556430868, 'reg_lambda': 4.029088627699283}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:11,363] Trial 38 finished with value: 0.6283106597121845 and parameters: {'learning_rate': 0.02055372198455572, 'max_depth': 7, 'min_child_weight': 3.3033814309550134, 'subsample': 0.8998312405460218, 'colsample_bytree': 0.9062848411670144, 'gamma': 1.815386615224227, 'reg_alpha': 0.012588264472009439, 'reg_lambda': 1.635924937919882}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:18,904] Trial 39 finished with value: 0.62380505618265 and parameters: {'learning_rate': 0.05584160729380164, 'max_depth': 5, 'min_child_weight': 2.543959867879358, 'subsample': 0.9295569219611657, 'colsample_bytree': 0.8378870430774553, 'gamma': 1.5017444066055297, 'reg_alpha': 0.44454196769162313, 'reg_lambda': 0.6353431054122816}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:27,517] Trial 40 finished with value: 0.6335032420327817 and parameters: {'learning_rate': 0.042787210675254685, 'max_depth': 4, 'min_child_weight': 8.138109599228684, 'subsample': 0.7282571436393164, 'colsample_bytree': 0.7227262753181135, 'gamma': 1.3322589660233384, 'reg_alpha': 0.04661948645598939, 'reg_lambda': 0.11361178722668636}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:37,325] Trial 41 finished with value: 0.6418356827542315 and parameters: {'learning_rate': 0.02248176083824718, 'max_depth': 3, 'min_child_weight': 5.383702780653734, 'subsample': 0.9112474236456912, 'colsample_bytree': 0.7645370142723238, 'gamma': 1.8831987670296404, 'reg_alpha': 1.5267416955399489, 'reg_lambda': 0.9335832905414381}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:46,308] Trial 42 finished with value: 0.6411085854535292 and parameters: {'learning_rate': 0.025702845374385223, 'max_depth': 3, 'min_child_weight': 6.790284928191239, 'subsample': 0.9613644491089367, 'colsample_bytree': 0.7730902537796961, 'gamma': 1.9051273560222226, 'reg_alpha': 1.6260911918772327, 'reg_lambda': 1.8066997107699188}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:20:56,860] Trial 43 finished with value: 0.6482154545222707 and parameters: {'learning_rate': 0.023285085443595525, 'max_depth': 3, 'min_child_weight': 5.439361763172197, 'subsample': 0.8154347009924832, 'colsample_bytree': 0.9996533142159789, 'gamma': 1.7815152189125198, 'reg_alpha': 4.429757776198998, 'reg_lambda': 0.9550429093264331}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:21:07,637] Trial 44 finished with value: 0.6379664588010877 and parameters: {'learning_rate': 0.02716037777758527, 'max_depth': 3, 'min_child_weight': 5.74403411863766, 'subsample': 0.8084008187507296, 'colsample_bytree': 0.9870989969231999, 'gamma': 1.6768986701642015, 'reg_alpha': 5.40778801752528, 'reg_lambda': 5.141383704445234}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:21:14,712] Trial 45 finished with value: 0.6323207548872496 and parameters: {'learning_rate': 0.033551835320814974, 'max_depth': 3, 'min_child_weight': 4.748715611633716, 'subsample': 0.762832148284882, 'colsample_bytree': 0.999808428475493, 'gamma': 1.7812753432000386, 'reg_alpha': 0.0012118870034915085, 'reg_lambda': 0.4859696153208844}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:21:23,523] Trial 46 finished with value: 0.6421978013552059 and parameters: {'learning_rate': 0.023414456035366498, 'max_depth': 3, 'min_child_weight': 3.4849365862503396, 'subsample': 0.7044631716730756, 'colsample_bytree': 0.9556987040663716, 'gamma': 1.6064584388577645, 'reg_alpha': 2.2564975942337644, 'reg_lambda': 2.4525662882536188}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:21:33,347] Trial 47 finished with value: 0.6348775039932514 and parameters: {'learning_rate': 0.03174243529736897, 'max_depth': 4, 'min_child_weight': 2.917083717884543, 'subsample': 0.8249016224693347, 'colsample_bytree': 0.8574597061226553, 'gamma': 1.1217931356187516, 'reg_alpha': 0.8867313024664268, 'reg_lambda': 6.984281252160741}. Best is trial 26 with value: 0.6487281238369439.
[I 2026-04-15 23:21:42,354] Trial 48 finished with value: 0.6402622771980733 and parameters: {'learning_rate': 0.020402705721698684, 'max_depth': 3, 'min_child_weight': 3.995354589417096, 'subsample': 0.8044437021499481, 'colsample_bytree': 0.8008543594830347, 'gamma': 1.8825470180538422, 'reg_alpha': 0.18842459992706426, 'reg_lambda': 0.004371197626165927}. Best is trial 26 with value: 0.6487281238369439.

[I 2026-04-15 23:27:36,665] A new study created in memory with name: multiclass_catboost

[xgb] skipped due to error: value 0 for Parameter num_class should be greater equal to 1
num_class: Number of output class in the multi-class classification.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 23:27:44,262] Trial 0 finished with value: 0.6294443427315789 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.07226675683786944, 'depth': 4, 'l2_leaf_reg': 1.8990530558141054, 'random_strength': 0.1465134177327414, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 4.973275478387985}. Best is trial 0 with value: 0.6294443427315789.
[I 2026-04-15 23:27:53,972] Trial 1 finished with value: 0.6514023595772884 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.025573683975272207, 'depth': 4, 'l2_leaf_reg': 13.70317538683857, 'random_strength': 0.1755724094154989, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.6972589059086052}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:28:08,976] Trial 2 finished with value: 0.6463619033266641 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04408953922191573, 'depth': 6, 'l2_leaf_reg': 7.783380341443863, 'random_strength': 0.3550143979212732, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.763694929754526}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:28:36,821] Trial 3 finished with value: 0.6187431111938617 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.07947711612968353, 'depth': 7, 'l2_leaf_reg': 10.13635941823749, 'random_strength': 0.6608958471385917, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 4, 'subsample': 0.694672084766431}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:29:17,810] Trial 4 finished with value: 0.5868148242500113 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.17977081100711048, 'depth': 8, 'l2_leaf_reg': 1.6190445824143818, 'random_strength': 0.07283360007461248, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 5, 'subsample': 0.7490749306744428}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:30:07,467] Trial 5 finished with value: 0.6299615814702026 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0804372303445056, 'depth': 8, 'l2_leaf_reg': 4.288359536877175, 'random_strength': 0.7572943188410588, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 1.5027288344991263}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:30:35,379] Trial 6 finished with value: 0.6440065574541666 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0945259455808759, 'depth': 7, 'l2_leaf_reg': 10.041037842616635, 'random_strength': 0.6441114315245845, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 5, 'bagging_temperature': 2.757557144989042}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:31:10,752] Trial 7 finished with value: 0.6490580287635279 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.021001223201279434, 'depth': 6, 'l2_leaf_reg': 4.5542524165716305, 'random_strength': 0.2939125145362952, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'bagging_temperature': 2.8651059714289637}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:32:29,686] Trial 8 finished with value: 0.634545962490685 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04804685707982532, 'depth': 8, 'l2_leaf_reg': 16.241394657731572, 'random_strength': 0.46406638857005, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 2.770323299683593}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:32:54,652] Trial 9 finished with value: 0.6293985030442077 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0770330191832716, 'depth': 7, 'l2_leaf_reg': 1.0065954205902736, 'random_strength': 0.8527464074001909, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'subsample': 0.6403054710405697}. Best is trial 1 with value: 0.6514023595772884.
[I 2026-04-15 23:33:08,032] Trial 10 finished with value: 0.652217892888349 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02011014934116818, 'depth': 4, 'l2_leaf_reg': 18.98104482996519, 'random_strength': 0.24761117474300404, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9511501249171788}. Best is trial 10 with value: 0.652217892888349.
[I 2026-04-15 23:33:21,054] Trial 11 finished with value: 0.6442737230392757 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02005507141938724, 'depth': 4, 'l2_leaf_reg': 19.809778323827157, 'random_strength': 0.20696700950514785, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9614099298964858}. Best is trial 10 with value: 0.652217892888349.
[I 2026-04-15 23:33:36,406] Trial 12 finished with value: 0.6459243714001031 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.027764326872075, 'depth': 5, 'l2_leaf_reg': 13.859731742356656, 'random_strength': 0.02812276405828626, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9357491826204533}. Best is trial 10 with value: 0.652217892888349.
[I 2026-04-15 23:33:47,552] Trial 13 finished with value: 0.6540457615303426 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03322501342278858, 'depth': 5, 'l2_leaf_reg': 5.838384756610479, 'random_strength': 0.41707559629394864, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8632850879711638}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:33:58,757] Trial 14 finished with value: 0.6359129914961197 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03370473289704124, 'depth': 5, 'l2_leaf_reg': 5.074742486962073, 'random_strength': 0.4100750513516051, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8751822615532037}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:08,949] Trial 15 finished with value: 0.646492531671933 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03699604572505095, 'depth': 5, 'l2_leaf_reg': 3.318965785058889, 'random_strength': 0.5623181046141312, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8596016221292856}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:19,255] Trial 16 finished with value: 0.6420309990268838 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05219399788945581, 'depth': 5, 'l2_leaf_reg': 7.372401598396334, 'random_strength': 0.32206278483112116, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9998908231041508}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:27,620] Trial 17 finished with value: 0.6522951112757758 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02781230966142742, 'depth': 4, 'l2_leaf_reg': 2.638662249585972, 'random_strength': 0.5608545766645552, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8593015822272716}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:38,745] Trial 18 finished with value: 0.6501550865686586 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03134984837092198, 'depth': 5, 'l2_leaf_reg': 2.5170514356418203, 'random_strength': 0.9580941097934477, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'subsample': 0.8523249955395609}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:51,737] Trial 19 finished with value: 0.6374650490135295 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.11517845539649318, 'depth': 6, 'l2_leaf_reg': 3.464048297828438, 'random_strength': 0.537536625079855, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8241748973514169}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:34:58,698] Trial 20 finished with value: 0.6347226570120712 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03897768169062489, 'depth': 4, 'l2_leaf_reg': 6.490572769074826, 'random_strength': 0.6642024809671923, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8935219730294973}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:08,718] Trial 21 finished with value: 0.6415051845905138 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023415154911833228, 'depth': 4, 'l2_leaf_reg': 2.331636607669012, 'random_strength': 0.46141876818447314, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9203131859679261}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:16,556] Trial 22 finished with value: 0.650440689947275 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.028656649435200014, 'depth': 4, 'l2_leaf_reg': 1.45245334404263, 'random_strength': 0.26741864381569924, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.7993822446824579}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:26,488] Trial 23 finished with value: 0.6469397531278958 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05852941498258112, 'depth': 5, 'l2_leaf_reg': 2.9730805436521885, 'random_strength': 0.3983525266342971, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.9743503344495901}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:35,066] Trial 24 finished with value: 0.6474920324295721 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.02688579009137549, 'depth': 4, 'l2_leaf_reg': 5.410215203028945, 'random_strength': 0.5498465317379635, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.9175852671803286}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:47,486] Trial 25 finished with value: 0.6414709948570567 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.023447695938273682, 'depth': 5, 'l2_leaf_reg': 10.253683087244148, 'random_strength': 0.23632400821301136, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.8155398920037588}. Best is trial 13 with value: 0.6540457615303426.
[I 2026-04-15 23:35:52,979] Trial 26 finished with value: 0.6543704976273661 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.0422544636882029, 'depth': 4, 'l2_leaf_reg': 1.258351684550954, 'random_strength': 0.12618201606872187, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.2578643405925001}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:06,263] Trial 27 finished with value: 0.6467849535876651 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.04106920389751102, 'depth': 6, 'l2_leaf_reg': 1.3314698531232398, 'random_strength': 0.0944546831155002, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 0.30094396714113597}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:16,364] Trial 28 finished with value: 0.6425517352259079 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.033854178534185236, 'depth': 5, 'l2_leaf_reg': 1.047664443935959, 'random_strength': 0.768274502589992, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 0.22090791623893452}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:22,035] Trial 29 finished with value: 0.6466978573056227 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.059466403331839356, 'depth': 4, 'l2_leaf_reg': 2.093841462169336, 'random_strength': 0.1408851011800677, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'bagging_temperature': 1.3784693681010873}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:34,663] Trial 30 finished with value: 0.6446874113880812 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.047983719563150264, 'depth': 4, 'l2_leaf_reg': 1.7599195962418166, 'random_strength': 0.6187360717782715, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 3, 'bagging_temperature': 4.4993264036145195}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:45,218] Trial 31 finished with value: 0.6486813698424918 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.030923179039661117, 'depth': 4, 'l2_leaf_reg': 1.2361609394093316, 'random_strength': 0.016612243628624207, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 1.370956938236069}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:36:59,791] Trial 32 finished with value: 0.6478030375692742 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.023887553529808533, 'depth': 4, 'l2_leaf_reg': 2.8583068985788223, 'random_strength': 0.15807384977069389, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 2, 'bagging_temperature': 4.164704118387009}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:37:07,428] Trial 33 finished with value: 0.6523240383361568 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.03553924130979592, 'depth': 4, 'l2_leaf_reg': 1.951822262044558, 'random_strength': 0.3744607005391597, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.8870777447371211}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:37:15,056] Trial 34 finished with value: 0.6419043003536892 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.0364934554603031, 'depth': 4, 'l2_leaf_reg': 1.9668688279274023, 'random_strength': 0.40119289121464935, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8983918350360512}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:37:23,588] Trial 35 finished with value: 0.639901385303606 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04447435821281938, 'depth': 5, 'l2_leaf_reg': 3.752092867399971, 'random_strength': 0.4771046256334318, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 4, 'subsample': 0.8413157221585863}. Best is trial 26 with value: 0.6543704976273661.
[I 2026-04-15 23:37:30,691] Trial 36 finished with value: 0.6548710472535982 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05269246807196571, 'depth': 4, 'l2_leaf_reg': 1.5462609814906587, 'random_strength': 0.3335621175040127, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7881518118880378}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:37:41,614] Trial 37 finished with value: 0.6415387341225356 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.06935325932977954, 'depth': 5, 'l2_leaf_reg': 1.531681846043177, 'random_strength': 0.3386334026447094, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'bagging_temperature': 3.7272701169983553}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:37:47,947] Trial 38 finished with value: 0.6461529026968648 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.053138013035247636, 'depth': 4, 'l2_leaf_reg': 1.1717070757864472, 'random_strength': 0.3884437999756948, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.781943466665233}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:01,157] Trial 39 finished with value: 0.6320416390596024 and parameters: {'bootstrap_type': 'Bayesian', 'learning_rate': 0.19666138542450712, 'depth': 6, 'l2_leaf_reg': 1.7188059724040359, 'random_strength': 0.29919504806502784, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'bagging_temperature': 0.7286242350522154}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:07,353] Trial 40 finished with value: 0.6335168219974138 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.04321240223810891, 'depth': 4, 'l2_leaf_reg': 2.132493667487511, 'random_strength': 0.098407013861207, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Newton', 'leaf_estimation_iterations': 1, 'subsample': 0.7345463298037899}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:15,592] Trial 41 finished with value: 0.6383191072582288 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.031005166629005352, 'depth': 4, 'l2_leaf_reg': 1.4987205679108677, 'random_strength': 0.5970233360746173, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.877843211306949}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:21,992] Trial 42 finished with value: 0.6410346040751943 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.035209696592514904, 'depth': 4, 'l2_leaf_reg': 2.446491649581778, 'random_strength': 0.5235371197833634, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 2, 'subsample': 0.8387455612130073}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:28,543] Trial 43 finished with value: 0.6461487756880966 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.06643887407299388, 'depth': 4, 'l2_leaf_reg': 1.800227105468024, 'random_strength': 0.44676379858247545, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 1, 'subsample': 0.7900874558959946}. Best is trial 36 with value: 0.6548710472535982.
[I 2026-04-15 23:38:38,232] Trial 44 finished with value: 0.6407566696520886 and parameters: {'bootstrap_type': 'Bernoulli', 'learning_rate': 0.05031286862818335, 'depth': 5, 'l2_leaf_reg': 4.250055984148924, 'random_strength': 0.7109027337743221, 'grow_policy': 'SymmetricTree', 'leaf_estimation_method': 'Gradient', 'leaf_estimation_iterations': 3, 'subsample': 0.718325599130871}. Best is trial 36 with value: 0.6548710472535982.

                                               feature  importance
56           eye__sac_length_AOI_aggregated_Pos_median   13.210942
275         eye__fix_duration_AOI_aggregated_Pos_first    9.439212
58              eye__sac_length_AOI_aggregated_Pos_sum    7.775808
53              eye__sac_length_AOI_aggregated_Pos_min    6.267648
63            eye__sac_speed_AOI_aggregated_Pos_median    4.806906
278          eye__fix_duration_AOI_aggregated_Pos_mean    3.371740
542                                     stat__umap_072    3.205570
491                                     stat__umap_021    2.787353
276           eye__fix_duration_AOI_aggregated_Pos_min    2.603435
508                                     stat__umap_038    2.281582
176                  eye__fix_duration_AOI_FD_Neg1_min    2.171776
54              eye__sac_length_AOI_aggregated_Pos_max    1.995941
55             eye__sac_length_AOI_aggregated_Pos_mean    1.923704
62              eye__sac_speed_AOI_aggregated_Pos_mean    1.914923
60               eye__sac_speed_AOI_aggregated_Pos_min    1.828189
175                eye__fix_duration_AOI_FD_Neg1_first    1.681810
177                  eye__fix_duration_AOI_FD_Neg1_max    1.241692
279        eye__fix_duration_AOI_aggregated_Pos_median    1.206071
166                              eye__fix_duration_min    1.140738
487                                     stat__umap_017    1.116139
91   eye__sac_length_from_Pos_to_Target_from_Pos_to...    1.106679
546                                     stat__umap_076    1.079734
0                                  eye__sac_length_min    1.073126
183                  eye__fix_duration_AOI_FD_Neg1_sum    1.031071
552                                     stat__umap_082    1.004217
541                                     stat__umap_071    0.993341
283           eye__fix_duration_AOI_aggregated_Pos_sum    0.962999
562                                     stat__umap_092    0.836097
38              eye__sac_speed_AOI_aggregated_Neg_mean    0.791515
179               eye__fix_duration_AOI_FD_Neg1_median    0.754310

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,False,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,binary,True,0.403197,0.449908,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch,multiclass,False,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch,multiclass,True,NaN,0.568418,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,stat,match_mismatch_general,binary,False,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,stat,match_mismatch_general,binary,True,0.410526,0.553716,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,stat,match_mismatch_general,multiclass,False,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,stat,match_mismatch_general,multiclass,True,NaN,0.800452,C:\Users\LEGION\Projects\CB_exepriment\dataset...

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,stat,match_mismatch,binary,False,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,stat,match_mismatch,binary,True,0.403197,0.449908,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,stat,match_mismatch,multiclass,False,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,stat,match_mismatch,multiclass,True,NaN,0.568418,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,stat,match_mismatch_general,binary,False,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,stat,match_mismatch_general,binary,True,0.410526,0.553716,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,stat,match_mismatch_general,multiclass,False,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,stat,match_mismatch_general,multiclass,True,NaN,0.800452,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [11]:
all_summaries = [
    summary_corr,
    summary_cov_freq,
    summary_envelope,
    summary_freq_bands,
    summary_PID,
    summary_stat,
]
all_results = pd.concat(all_summaries, ignore_index=True)
all_results

,set,target,split,no_neutral,xgb_test,catboost_test,file
0,corr,match_mismatch,binary,False,0.398399,0.414870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
1,corr,match_mismatch,binary,True,0.403197,0.443771,C:\Users\LEGION\Projects\CB_exepriment\dataset...
2,corr,match_mismatch,multiclass,False,0.596315,0.608868,C:\Users\LEGION\Projects\CB_exepriment\dataset...
3,corr,match_mismatch,multiclass,True,NaN,0.541407,C:\Users\LEGION\Projects\CB_exepriment\dataset...
4,corr,match_mismatch_general,binary,False,0.426946,0.529915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
5,corr,match_mismatch_general,binary,True,0.440106,0.486745,C:\Users\LEGION\Projects\CB_exepriment\dataset...
6,corr,match_mismatch_general,multiclass,False,0.799472,0.808972,C:\Users\LEGION\Projects\CB_exepriment\dataset...
7,corr,match_mismatch_general,multiclass,True,NaN,0.773737,C:\Users\LEGION\Projects\CB_exepriment\dataset...
8,cov_freq,match_mismatch,binary,False,0.399740,0.403406,C:\Users\LEGION\Projects\CB_exepriment\dataset...
9,cov_freq,match_mismatch,binary,True,0.403197,0.505965,C:\Users\LEGION\Projects\CB_exepriment\dataset...
10,cov_freq,match_mismatch,multiclass,False,0.621595,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
11,cov_freq,match_mismatch,multiclass,True,NaN,0.544607,C:\Users\LEGION\Projects\CB_exepriment\dataset...
12,cov_freq,match_mismatch_general,binary,False,0.398957,0.576895,C:\Users\LEGION\Projects\CB_exepriment\dataset...
13,cov_freq,match_mismatch_general,binary,True,0.410526,0.562286,C:\Users\LEGION\Projects\CB_exepriment\dataset...
14,cov_freq,match_mismatch_general,multiclass,False,0.802246,0.803497,C:\Users\LEGION\Projects\CB_exepriment\dataset...
15,cov_freq,match_mismatch_general,multiclass,True,NaN,0.772836,C:\Users\LEGION\Projects\CB_exepriment\dataset...
16,envelope,match_mismatch,binary,False,0.399740,0.410272,C:\Users\LEGION\Projects\CB_exepriment\dataset...
17,envelope,match_mismatch,binary,True,0.403197,0.476267,C:\Users\LEGION\Projects\CB_exepriment\dataset...
18,envelope,match_mismatch,multiclass,False,0.621856,0.621466,C:\Users\LEGION\Projects\CB_exepriment\dataset...
19,envelope,match_mismatch,multiclass,True,NaN,0.505935,C:\Users\LEGION\Projects\CB_exepriment\dataset...
20,envelope,match_mismatch_general,binary,False,0.398957,0.554178,C:\Users\LEGION\Projects\CB_exepriment\dataset...
21,envelope,match_mismatch_general,binary,True,0.410526,0.542756,C:\Users\LEGION\Projects\CB_exepriment\dataset...
22,envelope,match_mismatch_general,multiclass,False,0.806555,0.808673,C:\Users\LEGION\Projects\CB_exepriment\dataset...
23,envelope,match_mismatch_general,multiclass,True,NaN,0.820915,C:\Users\LEGION\Projects\CB_exepriment\dataset...
24,freq_bands,match_mismatch,binary,False,0.399740,0.416763,C:\Users\LEGION\Projects\CB_exepriment\dataset...
25,freq_bands,match_mismatch,binary,True,0.403197,0.443463,C:\Users\LEGION\Projects\CB_exepriment\dataset...
26,freq_bands,match_mismatch,multiclass,False,0.633477,0.628659,C:\Users\LEGION\Projects\CB_exepriment\dataset...
27,freq_bands,match_mismatch,multiclass,True,NaN,0.544316,C:\Users\LEGION\Projects\CB_exepriment\dataset...
28,freq_bands,match_mismatch_general,binary,False,0.484267,0.531461,C:\Users\LEGION\Projects\CB_exepriment\dataset...
29,freq_bands,match_mismatch_general,binary,True,0.410526,0.588046,C:\Users\LEGION\Projects\CB_exepriment\dataset...
30,freq_bands,match_mismatch_general,multiclass,False,0.808328,0.801248,C:\Users\LEGION\Projects\CB_exepriment\dataset...
31,freq_bands,match_mismatch_general,multiclass,True,NaN,0.708828,C:\Users\LEGION\Projects\CB_exepriment\dataset...
32,PID,match_mismatch,binary,False,0.399740,0.402184,C:\Users\LEGION\Projects\CB_exepriment\dataset...
33,PID,match_mismatch,binary,True,0.403197,0.404151,C:\Users\LEGION\Projects\CB_exepriment\dataset...
34,PID,match_mismatch,multiclass,False,0.623863,0.614744,C:\Users\LEGION\Projects\CB_exepriment\dataset...
35,PID,match_mismatch,multiclass,True,NaN,0.540870,C:\Users\LEGION\Projects\CB_exepriment\dataset...
36,PID,match_mismatch_general,binary,False,0.404235,0.567179,C:\Users\LEGION\Projects\CB_exepriment\dataset...
37,PID,match_mismatch_general,binary,True,0.500321,0.603175,C:\Users\LEGION\Projects\CB_exepriment\dataset...
38,PID,match_mismatch_general,multiclass,False,0.802558,0.814880,C:\Users\LEGION\Projects\CB_exepriment\dataset...
39,PID,match_mismatch_general,multiclass,True,NaN,0.745125,C:\Users\LEGION\Projects\CB_exepriment\dataset...
40,stat,match_mismatch,binary,False,0.399740,0.436073,C:\Users\LEGION\Projects\CB_exepriment\dataset...
41,stat,match_mismatch,binary,True,0.403197,0.449908,C:\Users\LEGION\Projects\CB_exepriment\dataset...
42,stat,match_mismatch,multiclass,False,0.626858,0.618859,C:\Users\LEGION\Projects\CB_exepriment\dataset...
43,stat,match_mismatch,multiclass,True,NaN,0.568418,C:\Users\LEGION\Projects\CB_exepriment\dataset...
44,stat,match_mismatch_general,binary,False,0.439737,0.554900,C:\Users\LEGION\Projects\CB_exepriment\dataset...
45,stat,match_mismatch_general,binary,True,0.410526,0.553716,C:\Users\LEGION\Projects\CB_exepriment\dataset...
46,stat,match_mismatch_general,multiclass,False,0.801435,0.817319,C:\Users\LEGION\Projects\CB_exepriment\dataset...
47,stat,match_mismatch_general,multiclass,True,NaN,0.800452,C:\Users\LEGION\Projects\CB_exepriment\dataset...

In [12]:
summary_path = OUT_DIR / "summary_eye_ftar.csv"
all_results.to_csv(summary_path, index=False)
print("Saved summary:", summary_path)

all_results.groupby(["set", "target", "split"], as_index=False)[["xgb_test", "catboost_test"]].mean()

Saved summary: C:\Users\LEGION\Projects\CB_exepriment\dataset_v2\optuna_results_eye_ftar\summary_eye_ftar.csv

           set                  target       split  xgb_test  catboost_test
0          PID          match_mismatch      binary  0.401468       0.403168
1          PID          match_mismatch  multiclass  0.623863       0.577807
2          PID  match_mismatch_general      binary  0.452278       0.585177
3          PID  match_mismatch_general  multiclass  0.802558       0.780003
4         corr          match_mismatch      binary  0.400798       0.429320
5         corr          match_mismatch  multiclass  0.596315       0.575137
6         corr  match_mismatch_general      binary  0.433526       0.508330
7         corr  match_mismatch_general  multiclass  0.799472       0.791354
8     cov_freq          match_mismatch      binary  0.401468       0.454685
9     cov_freq          match_mismatch  multiclass  0.621595       0.586633
10    cov_freq  match_mismatch_general      binary  0.404742       0.569591
11    cov_freq  match_mismatch_general  multiclass  0.802246       0.788166
12    envelope          match_mismatch      binary  0.401468       0.443270
13    envelope          match_mismatch  multiclass  0.621856       0.563700
14    envelope  match_mismatch_general      binary  0.404742       0.548467
15    envelope  match_mismatch_general  multiclass  0.806555       0.814794
16  freq_bands          match_mismatch      binary  0.401468       0.430113
17  freq_bands          match_mismatch  multiclass  0.633477       0.586488
18  freq_bands  match_mismatch_general      binary  0.447397       0.559753
19  freq_bands  match_mismatch_general  multiclass  0.808328       0.755038
20        stat          match_mismatch      binary  0.401468       0.442990
21        stat          match_mismatch  multiclass  0.626858       0.593638
22        stat  match_mismatch_general      binary  0.425132       0.554308
23        stat  match_mismatch_general  multiclass  0.801435       0.808886